var config = {};
config.menus = [{
	name: "home",
	showName: "关于盛隆",
	url: 'http://m.shenglong-electric.com.cn/aboutMe',
	icon: '/images/tabs/home.png',
	submenus: [{
		name: "introduction",
		showName: "公司简介",
		url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/13',
		icon: '',
		submenus: []
	}, {
		name: "partyProfile",
		showName: "党建概况",
		url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/14',
		icon: '',
		submenus: []
	}, {
		name: "corporateStrategy_long-term",
		showName: "公司战略",
		url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/30',
		icon: '',
		submenus: [{
			name: "corporateStrategy_long-term",
			showName: "长期目标",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/30',
			icon: '',
			submenus: []
		}, {
			name: "corporateStrategy_medium-term",
			showName: "中期目标",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/31',
			icon: '',
			submenus: []
		}]
	}, {
		name: "history",
		showName: "发展历程",
		url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/15',
		icon: '',
		submenus: []
	}, {
		name: "qualification",
		showName: "资质认证",
		url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/16',
		icon: '',
		submenus: []
	}, {
		name: "culture_purpose",
		showName: "盛隆文化",
		url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/18',
		icon: '',
		submenus: [{
			name: "culture_purpose",
			showName: "盛隆宗旨",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/18',
			icon: '',
			submenus: []
		}, {
			name: "culture_idea",
			showName: "盛隆理念",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/19',
			icon: '',
			submenus: []
		}, {
			name: "culture_target",
			showName: "盛隆文化目标",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/20',
			icon: '',
			submenus: []
		}, {
			name: "culture_mechanism",
			showName: "盛隆机制",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/21',
			icon: '',
			submenus: []
		}, {
			name: "culture_song",
			showName: "盛隆之歌",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/22',
			icon: '',
			submenus: []
		}, {
			name: "culture_badge",
			showName: "盛隆徽",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/23',
			icon: '',
			submenus: []
		}, {
			name: "culture_flag",
			showName: "盛隆旗",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/24',
			icon: '',
			submenus: []
		}, {
			name: "culture_rule",
			showName: "盛隆法则",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/25',
			icon: '',
			submenus: []
		}, {
			name: "culture_ethic",
			showName: "盛隆理论",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/26',
			icon: '',
			submenus: []
		}, {
			name: "culture_philosophy",
			showName: "盛隆哲学",
			url: 'http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/27',
			icon: '',
			submenus: []
		}]
	}]
}, {
	name: "news",
	showName: "新闻中心",
	url: 'http://m.shenglong-electric.com.cn/news',
	icon: '/images/tabs/news.png',
	submenus: [{
		name: "company",
		showName: "公司新闻",
		url: 'http://m.shenglong-electric.com.cn/news/dirlist/cid/7',
		icon: '',
		submenus: []
	}, {
		name: "media",
		showName: "媒体报道",
		url: 'http://m.shenglong-electric.com.cn/news/dirlist/cid/13',
		icon: '',
		submenus: []
	}, {
		name: "video",
		showName: "视频报道",
		url: 'http://m.shenglong-electric.com.cn/news/dirlist/cid/14',
		icon: '',
		submenus: []
	}, {
		name: "elegant_demeanour",
		showName: "盛隆风采",
		url: 'http://m.shenglong-electric.com.cn/gallery',
		icon: '',
		submenus: []
	}]
}, {
	name: "product",
	showName: "产品与服务",
	url: 'http://m.shenglong-electric.com.cn/product',
	icon: '/images/tabs/product.png',
	submenus: [{
		name: "ctspdsb",
		showName: "成套输配电设备",
		url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/20',
		icon: '',
		submenus: [{
			name: "gyxl",
			showName: "高压系列",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/20',
			icon: '',
			submenus: []
		}, {
			name: "gydyyzsbdz",
			showName: "高压/低压预装式变电站",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/21',
			icon: '',
			submenus: []
		}, {
			name: "dyxl",
			showName: "低压系列",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/22',
			icon: '',
			submenus: []
		}, {
			name: "kzbhp",
			showName: "控制保护屏",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/23',
			icon: '',
			submenus: []
		}, {
			name: "sxxl",
			showName: "三箱系列",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/24',
			icon: '',
			submenus: []
		}]
	}, {
		name: "dlzndlbhcpjjfa",
		showName: "电力智能、电力保护产品解决方案",
		url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/25',
		icon: '',
		submenus: [{
			name: "znwldgnyb",
			showName: "智能网路多功能仪表",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/25',
			icon: '',
			submenus: []
		}, {
			name: "znpdjkxt",
			showName: "智能配电监控系统",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/26',
			icon: '',
			submenus: []
		}, {
			name: "dqhzjkxt",
			showName: "电气火灾监控系统",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/27',
			icon: '',
			submenus: []
		}, {
			name: "zbjdlbhxt",
			showName: "综保及电力保护系统",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/29',
			icon: '',
			submenus: []
		}]
	}, {
		name: "dljnjzxcpjjfa",
		showName: "电力节能及增效产品解决方案",
		url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/28',
		icon: '',
		submenus: [{
			name: "yydllbq",
			showName: "有源电力滤波器",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/28',
			icon: '',
			submenus: []
		}, {
			name: "dgnxbbhq",
			showName: "多功能谐波保护器",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/30',
			icon: '',
			submenus: []
		}]
	}, {
		name: "dlgczcbfw",
		showName: "电力工程总承包服务",
		url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/17',
		icon: '',
		submenus: [{
			name: "ywgs",
			showName: "业务概述",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/17',
			icon: '',
			submenus: []
		}, {
			name: "ywfw",
			showName: "业务范围",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/18',
			icon: '',
			submenus: []
		}, {
			name: "zzrz",
			showName: "资质认证",
			url: 'http://m.shenglong-electric.com.cn/product/detail/page_id/19',
			icon: '',
			submenus: []
		}]
	}]
}, {
	name: "customer",
	showName: "客户与成功案例",
	url: 'http://m.shenglong-electric.com.cn/opus',
	icon: '/images/tabs/customer.png',
	submenus: [{
		name: "hbdbxb",
		showName: "华北、东北、西北地区",
		url: 'http://m.shenglong-electric.com.cn/opus/detail/page_id/29',
		icon: '',
		submenus: []
	}, {
		name: "hzxn",
		showName: "华中、西南地区",
		url: 'http://m.shenglong-electric.com.cn/opus/detail/page_id/28',
		icon: '',
		submenus: []
	}, {
		name: "hdhn",
		showName: "华东、华南地区",
		url: 'http://m.shenglong-electric.com.cn/opus/detail/page_id/31',
		icon: '',
		submenus: []
	}, {
		name: "otherCountryAndArea",
		showName: "其它国家和地区",
		url: 'http://m.shenglong-electric.com.cn/opus/detail/page_id/30',
		icon: '',
		submenus: []
	}, {
		name: "near",
		showName: "附近",
		url: 'http://map.baidu.com',
		icon: '',
		submenus: []
	}]
}, {
	name: "connect",
	showName: "联系我们",
	url: 'http://m.shenglong-electric.com.cn/contact',
	icon: '/images/tabs/connect.png',
	submenus: [{
		name: "companys",
		showName: "五大营",
		url: 'http://m.shenglong-electric.com.cn/contact/detail/page_id/2',
		icon: '',
		submenus: [{
			name: "wuhan",
			showName: "武汉公司",
			url: '',
			icon: '',
			submenus: []
		}, {
			name: "beijing",
			showName: "北京公司",
			url: '',
			icon: '',
			submenus: []
		}, {
			name: "guangzhou",
			showName: "广州公司",
			url: '',
			icon: '',
			submenus: []
		}, {
			name: "shanghai",
			showName: "上海公司",
			url: '',
			icon: '',
			submenus: []
		}, {
			name: "chongqing",
			showName: "重庆公司",
			url: '',
			icon: '',
			submenus: []
		}]
	}, {
		name: "consultAndFeedback",
		showName: "咨询与反馈",
		url: 'http://m.shenglong-electric.com.cn/email',
		icon: '',
		submenus: []
	}, {
		name: "interview",
		showName: "人才招聘",
		url: 'http://m.shenglong-electric.com.cn/jobs',
		icon: '',
		submenus: []
	}]
}];
exports.config = config;
exports.menus = config.menus;