var config = {};
config.menus = [
    {
        "banner": "",
        "icon": "/images/tabs/home.png",
        "id": 1,
        "menu_code": "001",
        "menu_name": "home",
        "menu_showName": "关于盛隆",
        "newsId": "",
        "pageId": "",
        "parentCode": "",
        "parentId": 0,
        "sl_cid": "",
        "sl_url": "",
        "submenus": [
            {
                "banner": "",
                "icon": "",
                "id": 2,
                "menu_code": "001001",
                "menu_name": "introduction",
                "menu_showName": "公司简介",
                "newsId": "",
                "pageId": "13",
                "parentCode": "001",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/13",
                "submenus": [],
                "type": 1,
                "url": "/website/page_template.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 3,
                "menu_code": "001002",
                "menu_name": "partyProfile",
                "menu_showName": "党建概况",
                "newsId": "",
                "pageId": "14",
                "parentCode": "001",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/14",
                "submenus": [],
                "type": 1,
                "url": "/website/page_template.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 4,
                "menu_code": "001003",
                "menu_name": "corporateStrategy_long-term",
                "menu_showName": "公司战略",
                "newsId": "",
                "pageId": "",
                "parentCode": "001",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "",
                "submenus": [
                    {
                        "banner": "",
                        "icon": "",
                        "id": 5,
                        "menu_code": "001003001",
                        "menu_name": "corporateStrategy_long-term",
                        "menu_showName": "长期目标",
                        "newsId": "",
                        "pageId": "30",
                        "parentCode": "001003",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/30",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 6,
                        "menu_code": "001003002",
                        "menu_name": "corporateStrategy_medium-term",
                        "menu_showName": "中期目标",
                        "newsId": "",
                        "pageId": "31",
                        "parentCode": "001003",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/31",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    }
                ],
                "type": 0,
                "url": "/website/submenu.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 7,
                "menu_code": "001004",
                "menu_name": "history",
                "menu_showName": "发展历程",
                "newsId": "",
                "pageId": "15",
                "parentCode": "001",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/15",
                "submenus": [],
                "type": 1,
                "url": "/website/page_template.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 8,
                "menu_code": "001005",
                "menu_name": "qualification",
                "menu_showName": "资质认证",
                "newsId": "",
                "pageId": "16",
                "parentCode": "001",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/16",
                "submenus": [],
                "type": 1,
                "url": "/website/page_template.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 9,
                "menu_code": "001006",
                "menu_name": "culture_purpose",
                "menu_showName": "盛隆文化",
                "newsId": "",
                "pageId": "",
                "parentCode": "001",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "",
                "submenus": [
                    {
                        "banner": "",
                        "icon": "",
                        "id": 10,
                        "menu_code": "001006001",
                        "menu_name": "culture_purpose",
                        "menu_showName": "盛隆宗旨",
                        "newsId": "",
                        "pageId": "18",
                        "parentCode": "001006",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/18",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 11,
                        "menu_code": "001006002",
                        "menu_name": "culture_idea",
                        "menu_showName": "盛隆理念",
                        "newsId": "",
                        "pageId": "19",
                        "parentCode": "001006",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/19",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 12,
                        "menu_code": "001006003",
                        "menu_name": "culture_target",
                        "menu_showName": "盛隆文化目标",
                        "newsId": "",
                        "pageId": "20",
                        "parentCode": "001006",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/20",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 13,
                        "menu_code": "001006004",
                        "menu_name": "culture_mechanism",
                        "menu_showName": "盛隆机制",
                        "newsId": "",
                        "pageId": "21",
                        "parentCode": "001006",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/21",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 14,
                        "menu_code": "001006005",
                        "menu_name": "culture_song",
                        "menu_showName": "盛隆之歌",
                        "newsId": "",
                        "pageId": "22",
                        "parentCode": "001006",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/22",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 15,
                        "menu_code": "001006006",
                        "menu_name": "culture_badge",
                        "menu_showName": "盛隆徽",
                        "newsId": "",
                        "pageId": "23",
                        "parentCode": "001006",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/23",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 16,
                        "menu_code": "001006007",
                        "menu_name": "culture_flag",
                        "menu_showName": "盛隆旗",
                        "newsId": "",
                        "pageId": "24",
                        "parentCode": "001006",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/24",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 17,
                        "menu_code": "001006008",
                        "menu_name": "culture_rule",
                        "menu_showName": "盛隆法则",
                        "newsId": "",
                        "pageId": "25",
                        "parentCode": "001006",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/25",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 18,
                        "menu_code": "001006009",
                        "menu_name": "culture_ethic",
                        "menu_showName": "盛隆理论",
                        "newsId": "",
                        "pageId": "26",
                        "parentCode": "001006",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/26",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 19,
                        "menu_code": "001006010",
                        "menu_name": "culture_philosophy",
                        "menu_showName": "盛隆哲学",
                        "newsId": "",
                        "pageId": "27",
                        "parentCode": "001006",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/aboutMe/detail/page_id/27",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    }
                ],
                "type": 0,
                "url": "/website/submenu.html"
            }
        ],
        "type": 0,
        "url": "/website/page_template.html"
    },
    {
        "banner": "",
        "icon": "/images/tabs/news.png",
        "id": 20,
        "menu_code": "002",
        "menu_name": "news",
        "menu_showName": "新闻中心",
        "newsId": "",
        "pageId": "",
        "parentCode": "",
        "parentId": 0,
        "sl_cid": "",
        "sl_url": "",
        "submenus": [
            {
                "banner": "",
                "icon": "",
                "id": 21,
                "menu_code": "002001",
                "menu_name": "company",
                "menu_showName": "公司新闻",
                "newsId": "7",
                "pageId": "",
                "parentCode": "002",
                "parentId": 0,
                "sl_cid": "7",
                "sl_url": "http://m.shenglong-electric.com.cn/news/dirlist/cid/7",
                "submenus": [],
                "type": 2,
                "url": "/website/newslist_template.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 22,
                "menu_code": "002002",
                "menu_name": "media",
                "menu_showName": "媒体报道",
                "newsId": "13",
                "pageId": "",
                "parentCode": "002",
                "parentId": 0,
                "sl_cid": "13",
                "sl_url": "http://m.shenglong-electric.com.cn/news/dirlist/cid/13",
                "submenus": [],
                "type": 2,
                "url": "/website/newslist_template.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 23,
                "menu_code": "002003",
                "menu_name": "video",
                "menu_showName": "视频报道",
                "newsId": "14",
                "pageId": "",
                "parentCode": "002",
                "parentId": 0,
                "sl_cid": "14",
                "sl_url": "http://m.shenglong-electric.com.cn/news/dirlist/cid/14",
                "submenus": [],
                "type": 2,
                "url": "/website/newslist_template.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 24,
                "menu_code": "002004",
                "menu_name": "elegant_demeanour",
                "menu_showName": "盛隆风采",
                "newsId": "",
                "pageId": "",
                "parentCode": "002",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://m.shenglong-electric.com.cn/gallery",
                "submenus": [],
                "type": 3,
                "url": "/website/gallery_template.html"
            }
        ],
        "type": 0,
        "url": "/website/page_template.html"
    },
    {
        "banner": "",
        "icon": "/images/tabs/product.png",
        "id": 25,
        "menu_code": "003",
        "menu_name": "product",
        "menu_showName": "产品与服务",
        "newsId": "",
        "pageId": "",
        "parentCode": "",
        "parentId": 0,
        "sl_cid": "",
        "sl_url": "",
        "submenus": [
            {
                "banner": "",
                "icon": "",
                "id": 26,
                "menu_code": "003001",
                "menu_name": "ctspdsb",
                "menu_showName": "成套输配电设备",
                "newsId": "",
                "pageId": "",
                "parentCode": "003",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "",
                "submenus": [
                    {
                        "banner": "",
                        "icon": "",
                        "id": 27,
                        "menu_code": "003001001",
                        "menu_name": "gyxl",
                        "menu_showName": "高压系列",
                        "newsId": "",
                        "pageId": "20",
                        "parentCode": "003001",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/20",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 28,
                        "menu_code": "003001002",
                        "menu_name": "gydyyzsbdz",
                        "menu_showName": "高压/低压预装式变电站",
                        "newsId": "",
                        "pageId": "21",
                        "parentCode": "003001",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/21",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 29,
                        "menu_code": "003001003",
                        "menu_name": "dyxl",
                        "menu_showName": "低压系列",
                        "newsId": "",
                        "pageId": "22",
                        "parentCode": "003001",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/22",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 30,
                        "menu_code": "003001004",
                        "menu_name": "kzbhp",
                        "menu_showName": "控制保护屏",
                        "newsId": "",
                        "pageId": "23",
                        "parentCode": "003001",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/23",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 31,
                        "menu_code": "003001005",
                        "menu_name": "sxxl",
                        "menu_showName": "三箱系列",
                        "newsId": "",
                        "pageId": "24",
                        "parentCode": "003001",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/24",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    }
                ],
                "type": 0,
                "url": "/website/submenu.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 32,
                "menu_code": "003002",
                "menu_name": "dlzndlbhcpjjfa",
                "menu_showName": "电力智能、电力保护产品解决方案",
                "newsId": "",
                "pageId": "",
                "parentCode": "003",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "",
                "submenus": [
                    {
                        "banner": "",
                        "icon": "",
                        "id": 33,
                        "menu_code": "003002001",
                        "menu_name": "znwldgnyb",
                        "menu_showName": "智能网路多功能仪表",
                        "newsId": "",
                        "pageId": "25",
                        "parentCode": "003002",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/25",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 34,
                        "menu_code": "003002002",
                        "menu_name": "znpdjkxt",
                        "menu_showName": "智能配电监控系统",
                        "newsId": "",
                        "pageId": "26",
                        "parentCode": "003002",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/26",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 35,
                        "menu_code": "003002003",
                        "menu_name": "dqhzjkxt",
                        "menu_showName": "电气火灾监控系统",
                        "newsId": "",
                        "pageId": "27",
                        "parentCode": "003002",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/27",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 36,
                        "menu_code": "003002004",
                        "menu_name": "zbjdlbhxt",
                        "menu_showName": "综保及电力保护系统",
                        "newsId": "",
                        "pageId": "29",
                        "parentCode": "003002",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/29",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    }
                ],
                "type": 0,
                "url": "/website/submenu.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 37,
                "menu_code": "003003",
                "menu_name": "dljnjzxcpjjfa",
                "menu_showName": "电力节能及增效产品解决方案",
                "newsId": "",
                "pageId": "",
                "parentCode": "003",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "",
                "submenus": [
                    {
                        "banner": "",
                        "icon": "",
                        "id": 38,
                        "menu_code": "003003001",
                        "menu_name": "yydllbq",
                        "menu_showName": "有源电力滤波器",
                        "newsId": "",
                        "pageId": "28",
                        "parentCode": "003003",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/28",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 39,
                        "menu_code": "003003002",
                        "menu_name": "dgnxbbhq",
                        "menu_showName": "多功能谐波保护器",
                        "newsId": "",
                        "pageId": "30",
                        "parentCode": "003003",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/30",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    }
                ],
                "type": 0,
                "url": "/website/submenu.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 40,
                "menu_code": "003004",
                "menu_name": "dlgczcbfw",
                "menu_showName": "电力工程总承包服务",
                "newsId": "",
                "pageId": "",
                "parentCode": "003",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "",
                "submenus": [
                    {
                        "banner": "",
                        "icon": "",
                        "id": 41,
                        "menu_code": "003004001",
                        "menu_name": "ywgs",
                        "menu_showName": "业务概述",
                        "newsId": "",
                        "pageId": "17",
                        "parentCode": "003004",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/17",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 42,
                        "menu_code": "003004002",
                        "menu_name": "ywfw",
                        "menu_showName": "业务范围",
                        "newsId": "",
                        "pageId": "18",
                        "parentCode": "003004",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/18",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 43,
                        "menu_code": "003004003",
                        "menu_name": "zzrz",
                        "menu_showName": "资质认证",
                        "newsId": "",
                        "pageId": "19",
                        "parentCode": "003004",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "http://m.shenglong-electric.com.cn/product/detail/page_id/19",
                        "submenus": [],
                        "type": 1,
                        "url": "/website/page_template.html"
                    }
                ],
                "type": 0,
                "url": "/website/submenu.html"
            }
        ],
        "type": 0,
        "url": "/website/page_template.html"
    },
    {
        "banner": "",
        "icon": "/images/tabs/customer.png",
        "id": 44,
        "menu_code": "004",
        "menu_name": "customer",
        "menu_showName": "客户与成功案例",
        "newsId": "",
        "pageId": "",
        "parentCode": "",
        "parentId": 0,
        "sl_cid": "",
        "sl_url": "",
        "submenus": [
            {
                "banner": "",
                "icon": "",
                "id": 45,
                "menu_code": "004001",
                "menu_name": "hbdbxb",
                "menu_showName": "华北、东北、西北地区",
                "newsId": "",
                "pageId": "29",
                "parentCode": "004",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://m.shenglong-electric.com.cn/opus/detail/page_id/29",
                "submenus": [],
                "type": 1,
                "url": "/website/page_template.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 46,
                "menu_code": "004002",
                "menu_name": "hzxn",
                "menu_showName": "华中、西南地区",
                "newsId": "",
                "pageId": "28",
                "parentCode": "004",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://m.shenglong-electric.com.cn/opus/detail/page_id/28",
                "submenus": [],
                "type": 1,
                "url": "/website/page_template.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 47,
                "menu_code": "004003",
                "menu_name": "hdhn",
                "menu_showName": "华东、华南地区",
                "newsId": "",
                "pageId": "31",
                "parentCode": "004",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://m.shenglong-electric.com.cn/opus/detail/page_id/31",
                "submenus": [],
                "type": 1,
                "url": "/website/page_template.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 48,
                "menu_code": "004004",
                "menu_name": "otherCountryAndArea",
                "menu_showName": "其它国家和地区",
                "newsId": "",
                "pageId": "30",
                "parentCode": "004",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://m.shenglong-electric.com.cn/opus/detail/page_id/30",
                "submenus": [],
                "type": 1,
                "url": "/website/page_template.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 49,
                "menu_code": "004005",
                "menu_name": "near",
                "menu_showName": "附近",
                "newsId": "",
                "pageId": "",
                "parentCode": "004",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://map.baidu.com",
                "submenus": [],
                "type": 3,
                "url": "http://map.baidu.com"
            }
        ],
        "type": 0,
        "url": "/website/page_template.html"
    },
    {
        "banner": "",
        "icon": "/images/tabs/connect.png",
        "id": 50,
        "menu_code": "005",
        "menu_name": "connect",
        "menu_showName": "联系我们",
        "newsId": "",
        "pageId": "",
        "parentCode": "",
        "parentId": 0,
        "sl_cid": "",
        "sl_url": "",
        "submenus": [
            {
                "banner": "",
                "icon": "",
                "id": 51,
                "menu_code": "005001",
                "menu_name": "companys",
                "menu_showName": "五大营",
                "newsId": "",
                "pageId": "",
                "parentCode": "005",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "",
                "submenus": [
                    {
                        "banner": "",
                        "icon": "",
                        "id": 52,
                        "menu_code": "005001001",
                        "menu_name": "wuhan",
                        "menu_showName": "武汉公司",
                        "newsId": "",
                        "pageId": "",
                        "parentCode": "005001",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "",
                        "submenus": [],
                        "type": 3,
                        "url": ""
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 53,
                        "menu_code": "005001002",
                        "menu_name": "beijing",
                        "menu_showName": "北京公司",
                        "newsId": "",
                        "pageId": "",
                        "parentCode": "005001",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "",
                        "submenus": [],
                        "type": 3,
                        "url": ""
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 54,
                        "menu_code": "005001003",
                        "menu_name": "guangzhou",
                        "menu_showName": "广州公司",
                        "newsId": "",
                        "pageId": "",
                        "parentCode": "005001",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "",
                        "submenus": [],
                        "type": 3,
                        "url": ""
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 55,
                        "menu_code": "005001004",
                        "menu_name": "shanghai",
                        "menu_showName": "上海公司",
                        "newsId": "",
                        "pageId": "",
                        "parentCode": "005001",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "",
                        "submenus": [],
                        "type": 3,
                        "url": ""
                    },
                    {
                        "banner": "",
                        "icon": "",
                        "id": 56,
                        "menu_code": "005001005",
                        "menu_name": "chongqing",
                        "menu_showName": "重庆公司",
                        "newsId": "",
                        "pageId": "",
                        "parentCode": "005001",
                        "parentId": 0,
                        "sl_cid": "",
                        "sl_url": "",
                        "submenus": [],
                        "type": 3,
                        "url": ""
                    }
                ],
                "type": 0,
                "url": "/website/submenu.html"
            },
            {
                "banner": "",
                "icon": "",
                "id": 57,
                "menu_code": "005002",
                "menu_name": "consultAndFeedback",
                "menu_showName": "咨询与反馈",
                "newsId": "",
                "pageId": "",
                "parentCode": "005",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://m.shenglong-electric.com.cn/email",
                "submenus": [],
                "type": 3,
                "url": "http://m.shenglong-electric.com.cn/email"
            },
            {
                "banner": "",
                "icon": "",
                "id": 58,
                "menu_code": "005003",
                "menu_name": "interview",
                "menu_showName": "人才招聘",
                "newsId": "",
                "pageId": "",
                "parentCode": "005",
                "parentId": 0,
                "sl_cid": "",
                "sl_url": "http://m.shenglong-electric.com.cn/jobs",
                "submenus": [],
                "type": 3,
                "url": "http://m.shenglong-electric.com.cn/jobs"
            }
        ],
        "type": 0,
        "url": "/website/page_template.html"
    }
];
exports.config = config;
exports.menus = config.menus;