
namespace eval ::ttk::dialog::file {   
    ::msgcat::mcset en Location Lokalizacja
    ::msgcat::mcset en Filter Filtr
    ::msgcat::mcset en Name Nazwa
    ::msgcat::mcset en Size Rozmiar
    ::msgcat::mcset en Date Data
    ::msgcat::mcset en Permissions Uprawnienia
    ::msgcat::mcset en Owner Właściciel
    ::msgcat::mcset en Group Grupa
    ::msgcat::mcset en Folder Folder
    ::msgcat::mcset en Sorting Sortowanie
    ::msgcat::mcset en Reverse Odwróć
    
    ::msgcat::mcset en {Short View} {Widok skrócony}
    ::msgcat::mcset en {Detailed View} {Widok szczegółowy}
    ::msgcat::mcset en {Show Hidden Files} {Pokazuj ukryte pliki}
    ::msgcat::mcset en {Separate Folders} {Oddziel foldery}
    ::msgcat::mcset en {By Name} {Po nazwie}
    ::msgcat::mcset en {By Date} {Po dacie}
    ::msgcat::mcset en {By Size} {Po rozmiarze}
    ::msgcat::mcset en {Folders First} {Najpierw foldery}
    ::msgcat::mcset en {New Folder} {Nowy folder}
    ::msgcat::mcset en {Create new folder in} {Stwórz nowy folder}
    
    ::msgcat::mcset en {File "%s" already exists. Do you want to overwrite it?} {Plik "%s" już istnieje. Czy chcesz go nadpisać?}
    ::msgcat::mcset en {File "%s" does not exist.} {Plik "%s" nie istnieje.}
    ::msgcat::mcset en {Cannot change to the directory "%s". Permission denied.} {Nie można prześć do katalogu "%s". Brak uprawnień.}
}


