# SQLiteStudio 'de_de' localization file

# Unchanged translations

### File: ../src/win_assoc.tcl
mcset de_de {File associations} {File associations}

### File: ../src/win_assoc.tcl
mcset de_de {Following file extensions could not be associated to the current SQLiteStudio version:
%s} {Following file extensions could not be associated to the current SQLiteStudio version:
%s}

### File: ../src/win_assoc.tcl
mcset de_de {Click the link below to find out what is possible reason and solutions.} {Click the link below to find out what is possible reason and solutions.}

### File: ../src/cfg_win.tcl
mcset de_de Ok Ok

### File: ../src/cfg_win.tcl
mcset de_de Apply Übernehmen

### File: ../src/cfg_win.tcl
mcset de_de Cancel Abbruch

### File: ../src/cfg_win.tcl
mcset de_de Theme Design

### File: ../src/cfg_win.tcl
mcset de_de {Select theme to use:} {Design auswählen:}

### File: ../src/cfg_win.tcl
mcset de_de {Theme version:} {Design Versionen:}

### File: ../src/cfg_win.tcl
mcset de_de Shortcuts Abkürzungen

### File: ../src/cfg_win.tcl
mcset de_de {Global shortcuts} {Global shortcuts}

### File: ../src/cfg_win.tcl
mcset de_de {Open SQL editor} {SQL Editor öffnen}

### File: ../src/cfg_win.tcl
mcset de_de {Opens SQL editor window.} {Opens SQL editor window.}

### File: ../src/cfg_win.tcl
mcset de_de {Close selected task} {Close selected task}

### File: ../src/cfg_win.tcl
mcset de_de {Closes active MDI window.} {Closes active MDI window.}

### File: ../src/cfg_win.tcl
mcset de_de {Restore last closed task} {Restore last closed task}

### File: ../src/cfg_win.tcl
mcset de_de {Restores last closed MDI window.} {Restores last closed MDI window.}

### File: ../src/cfg_win.tcl
mcset de_de {Open settings} {Optionen öffnen}

### File: ../src/cfg_win.tcl
mcset de_de {Opens SQLiteStudio settings window.} {SQLiteStudio Einstellungenfenster öffnen.}

### File: ../src/cfg_win.tcl
mcset de_de {Next task} {Nächste Aufgabe}

### File: ../src/cfg_win.tcl
mcset de_de {Switches task (window) to next, placed on the right from active task on taskbar.} {Switches task (window) to next, placed on the right from active task on taskbar.}

### File: ../src/cfg_win.tcl
mcset de_de {Next task (alternative)} {Nächste Aufgabe (alternativ)}

### File: ../src/cfg_win.tcl
mcset de_de {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.}

### File: ../src/cfg_win.tcl
mcset de_de {Previous task} {Vorherige Aufgabe}

### File: ../src/cfg_win.tcl
mcset de_de {Switches task (window) to previous, placed on the left from active task on taskbar.} {Switches task (window) to previous, placed on the left from active task on taskbar.}

### File: ../src/cfg_win.tcl
mcset de_de {Previous task (alternative)} {Vorherige Aufgabe (alternativ)}

### File: ../src/cfg_win.tcl
mcset de_de {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.}

### File: ../src/cfg_win.tcl
mcset de_de {Editor and table window shortcuts} {Editor and table window shortcuts}

### File: ../src/cfg_win.tcl
mcset de_de {SQL editor completion} {SQL editor completion}

### File: ../src/cfg_win.tcl
mcset de_de {Invokes SQL completion in editor window.} {Invokes SQL completion in editor window.}

### File: ../src/cfg_win.tcl
mcset de_de {Execute SQL query} {SQL Abfrage ausführen}

### File: ../src/cfg_win.tcl
mcset de_de {Executes SQL query typed in editor.} {Executes SQL query typed in editor.}

### File: ../src/cfg_win.tcl
mcset de_de {Explain SQL query} {SQL Abfrage erklären (Explain)}

### File: ../src/cfg_win.tcl
mcset de_de {Calls EXPLAIN on SQL query typed in editor.} {Calls EXPLAIN on SQL query typed in editor.}

### File: ../src/cfg_win.tcl
mcset de_de {Format SQL code} {Format SQL code}

### File: ../src/cfg_win.tcl
mcset de_de {Formats SQL code typed in editor.} {Formats SQL code typed in editor.}

### File: ../src/cfg_win.tcl
mcset de_de {Load SQL from file} {Lade SQL-Anweisung aus Datei}

### File: ../src/cfg_win.tcl
mcset de_de {Loads SQL from file to the editor.} {Loads SQL from file to the editor.}

### File: ../src/cfg_win.tcl
mcset de_de {Save SQL to file} {Sichere SQL-Anweisungen in Datei}

### File: ../src/cfg_win.tcl
mcset de_de {Saves contents of the editor into a file.} {Saves contents of the editor into a file.}

### File: ../src/cfg_win.tcl
mcset de_de {Execute SQL from file} {SQL von einer Datei ausführen}

### File: ../src/cfg_win.tcl
mcset de_de {Executes SQL directly from file, without loading it to the editor.} {Executes SQL directly from file, without loading it to the editor.}

### File: ../src/cfg_win.tcl
mcset de_de {Next tab} {Nächstes Tab}

### File: ../src/cfg_win.tcl
mcset de_de {Switches to next tab of editor window (result or history).} {Switches to next tab of editor window (result or history).}

### File: ../src/cfg_win.tcl
mcset de_de {Previous tab} {Vorheriges Tab}

### File: ../src/cfg_win.tcl
mcset de_de {Switches to previous tab of editor window (query or result).} {Switches to previous tab of editor window (query or result).}

### File: ../src/cfg_win.tcl
mcset de_de {Next subtab} {Next subtab}

### File: ../src/cfg_win.tcl
mcset de_de {Switches to next subtab (form view in results tab).} {Switches to next subtab (form view in results tab).}

### File: ../src/cfg_win.tcl
mcset de_de {Previous subtab} {Previous subtab}

### File: ../src/cfg_win.tcl
mcset de_de {Switches to previous subtab (grid view in results tab).} {Switches to previous subtab (grid view in results tab).}

### File: ../src/cfg_win.tcl
mcset de_de Refresh Refresh

### File: ../src/cfg_win.tcl
mcset de_de {Re-executes SQL query so results data is refreshed.} {Re-executes SQL query so results data is refreshed.}

### File: ../src/cfg_win.tcl
mcset de_de {Delete selected row} {Markierte Zeile löschen}

### File: ../src/cfg_win.tcl
mcset de_de {Deletes selected row.} {Ausgewählte Zeilen löschen.}

### File: ../src/cfg_win.tcl
mcset de_de {Add new row} {Neue Tabelle hinzufügen}

### File: ../src/cfg_win.tcl
mcset de_de {Adds new empty row without commiting it.} {Adds new empty row without commiting it.}

### File: ../src/cfg_win.tcl
mcset de_de {Erase cells data} {Erase cells data}

### File: ../src/cfg_win.tcl
mcset de_de {Erases data of selected cells.} {Erases data of selected cells.}

### File: ../src/cfg_win.tcl
mcset de_de {Next editor database in list} {Next editor database in list}

### File: ../src/cfg_win.tcl
mcset de_de {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)} {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)}

### File: ../src/cfg_win.tcl
mcset de_de {Previous editor database in list} {Previous editor database in list}

### File: ../src/cfg_win.tcl
mcset de_de {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)} {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)}

### File: ../src/cfg_win.tcl
mcset de_de {Commit edition in Form View} {Commit edition in Form View}

### File: ../src/cfg_win.tcl
mcset de_de {Commits edition in Form View of query results or table data preview.} {Commits edition in Form View of query results or table data preview.}

### File: ../src/cfg_win.tcl
mcset de_de {Rollback edition in Form View} {Rollback edition in Form View}

### File: ../src/cfg_win.tcl
mcset de_de {Rolls back edition in Form View of query results or table data preview.} {Rolls back edition in Form View of query results or table data preview.}

### File: ../src/cfg_win.tcl
mcset de_de {Jump to first row in Form View} {Jump to first row in Form View}

### File: ../src/cfg_win.tcl
mcset de_de {Jumps to first row of query results grid
or table data preview grid in Form View.} {Jumps to first row of query results grid
or table data preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset de_de {Go to previous row in Form View} {Go to previous row in Form View}

### File: ../src/cfg_win.tcl
mcset de_de {Goes to previous row of query results grid
or table data preview grid row in Form View.} {Goes to previous row of query results grid
or table data preview grid row in Form View.}

### File: ../src/cfg_win.tcl
mcset de_de {Go to next row in Form View} {Go to next row in Form View}

### File: ../src/cfg_win.tcl
mcset de_de {Goes to next row of query results grid
or table data preview grid row in Form View.} {Goes to next row of query results grid
or table data preview grid row in Form View.}

### File: ../src/cfg_win.tcl
mcset de_de {Jump to last row in Form View} {Jump to last row in Form View}

### File: ../src/cfg_win.tcl
mcset de_de {Jumps to last row of query results grid
or table data preview grid in Form View.} {Jumps to last row of query results grid
or table data preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset de_de {Switch NULL value in form edit field} {Switch NULL value in form edit field}

### File: ../src/cfg_win.tcl
mcset de_de {Sets or unsets NULL value in currently selected
column in form view data edit mode.} {Sets or unsets NULL value in currently selected
column in form view data edit mode.}

### File: ../src/cfg_win.tcl
mcset de_de Plugins Plugins

### File: ../src/cfg_win.tcl
mcset de_de {SQL formatter plugins} {SQL formatter plugins}

### File: ../src/cfg_win.tcl
mcset de_de {Use following SQL formatter plugin:} {Use following SQL formatter plugin:}

### File: ../src/cfg_win.tcl
mcset de_de {Configure formatter plugin} {Configure formatter plugin}

### File: ../src/cfg_win.tcl
mcset de_de Configure Konfigurieren

### File: ../src/cfg_win.tcl
mcset de_de {Populating plugins} {Populating plugins}

### File: ../src/cfg_win.tcl
mcset de_de {Default table populating plugin:} {Default table populating plugin:}

### File: ../src/cfg_win.tcl
mcset de_de Miscellaneous Verschiedenes

### File: ../src/cfg_win.tcl
mcset de_de {Restore session after next start} {Restore session after next start}

### File: ../src/cfg_win.tcl
mcset de_de {All windows and their contents (such as SQL code)
will be restored while next application startup.} {All windows and their contents (such as SQL code)
will be restored while next application startup.}

### File: ../src/cfg_win.tcl
mcset de_de {Show line numbers in SQL editor} {Show line numbers in SQL editor}

### File: ../src/cfg_win.tcl
mcset de_de {All SQL editor windows will contain line numbers on the left side of window.} {All SQL editor windows will contain line numbers on the left side of window.}

### File: ../src/cfg_win.tcl
mcset de_de {Underline syntax errors in SQL editor} {Underline syntax errors in SQL editor}

### File: ../src/cfg_win.tcl
mcset de_de {Makes errors to be marked with underline.
You can also define foreground and background color for errors.} {Makes errors to be marked with underline.
You can also define foreground and background color for errors.}

### File: ../src/cfg_win.tcl
mcset de_de {Show SQLite system tables and indexes in databases tree} {Show SQLite system tables and indexes in databases tree}

### File: ../src/cfg_win.tcl
mcset de_de {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.} {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.}

### File: ../src/cfg_win.tcl
mcset de_de {Open items with single mouse click in databases tree} {Open items with single mouse click in databases tree}

### File: ../src/cfg_win.tcl
mcset de_de {Items in database tree are open by double click by default.
This option switches it to single click.} {Items in database tree are open by double click by default.
This option switches it to single click.}

### File: ../src/cfg_win.tcl
mcset de_de {Show ROWID as default instead of row order number in table data view} {Show ROWID as default instead of row order number in table data view}

### File: ../src/cfg_win.tcl
mcset de_de {This option affects first column from the left on the data tab of the table window.} {This option affects first column from the left on the data tab of the table window.}

### File: ../src/cfg_win.tcl
mcset de_de {Do not show 'did you know that...' dialog at startup.} {Do not show 'did you know that...' dialog at startup.}

### File: ../src/cfg_win.tcl
mcset de_de {Uncheck this option to show the dialog.} {Uncheck this option to show the dialog.}

### File: ../src/cfg_win.tcl
mcset de_de {Check for updates at startup.} {Check for updates at startup.}

### File: ../src/cfg_win.tcl
mcset de_de {If enabled, application will will check
for new version available at startup.} {If enabled, application will will check
for new version available at startup.}

### File: ../src/cfg_win.tcl
mcset de_de {Sort custom SQL functions list by name} {Sort custom SQL functions list by name}

### File: ../src/cfg_win.tcl
mcset de_de {This list is placed in Custom SQL funcions dialog.} {This list is placed in Custom SQL funcions dialog.}

### File: ../src/cfg_win.tcl
mcset de_de {Select all contents when editing the table cell} {Select all contents when editing the table cell}

### File: ../src/cfg_win.tcl
mcset de_de {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.} {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.}

### File: ../src/cfg_win.tcl
mcset de_de {Ask if clipboard contents should be cut} {Ask if clipboard contents should be cut}

### File: ../src/cfg_win.tcl
mcset de_de {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.} {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.}

### File: ../src/cfg_win.tcl
mcset de_de {Rows per page in Table Window and Editor Results:} {Rows per page in Table Window and Editor Results:}

### File: ../src/cfg_win.tcl
mcset de_de {More results per page causes slower loading of single data page. Value 1000 should be right.} {More results per page causes slower loading of single data page. Value 1000 should be right.}

### File: ../src/cfg_win.tcl
mcset de_de {History entries limit:} {History entries limit:}

### File: ../src/cfg_win.tcl
mcset de_de {Number of rows to remember in SQL editor history.} {Number of rows to remember in SQL editor history.}

### File: ../src/cfg_win.tcl
mcset de_de {Insertion cursor blinking period (milliseconds):} {Insertion cursor blinking period (milliseconds):}

### File: ../src/cfg_win.tcl
mcset de_de {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.} {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.}

### File: ../src/cfg_win.tcl
mcset de_de {Web browser:} Internetbrowser:

### File: ../src/cfg_win.tcl
mcset de_de {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.} {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.}

### File: ../src/cfg_win.tcl
mcset de_de Language: Language:

### File: ../src/cfg_win.tcl
mcset de_de {Tab in table window on open:} {Tab in table window on open:}

### File: ../src/cfg_win.tcl
mcset de_de {Table structure} Tabellenstruktur

### File: ../src/cfg_win.tcl
mcset de_de {Table data} Tabellendaten

### File: ../src/cfg_win.tcl
mcset de_de {Select which tab should be opened for start in table window,
when you just opened that window.} {Select which tab should be opened for start in table window,
when you just opened that window.}

### File: ../src/cfg_win.tcl
mcset de_de {View default display mode:} {View default display mode:}

### File: ../src/cfg_win.tcl
mcset de_de {Edition dialog} {Edition dialog}

### File: ../src/cfg_win.tcl
mcset de_de {Data view} {Data view}

### File: ../src/cfg_win.tcl
mcset de_de {Defines what is displayed by default when user opens a view.} {Defines what is displayed by default when user opens a view.}

### File: ../src/cfg_win.tcl
mcset de_de {Editor window results layout} {Editor window results layout}

### File: ../src/cfg_win.tcl
mcset de_de {Show results in separated tab} {Show results in separated tab}

### File: ../src/cfg_win.tcl
mcset de_de {Show results in frame below query} {Show results in frame below query}

### File: ../src/cfg_win.tcl
mcset de_de {Database tree display mode} {Database tree display mode}

### File: ../src/cfg_win.tcl
mcset de_de {Show indexes and triggers linked under referenced table.} {Show indexes and triggers linked under referenced table.}

### File: ../src/cfg_win.tcl
mcset de_de {Show indexes and triggers in their own groups.} {Show indexes and triggers in their own groups.}

### File: ../src/cfg_win.tcl
mcset de_de {Show column names linked under the table.} {Show column names linked under the table.}

### File: ../src/cfg_win.tcl
mcset de_de {Plain text results} {Plain text results}

### File: ../src/cfg_win.tcl
mcset de_de {Display NULL values as:} {Display NULL values as:}

### File: ../src/cfg_win.tcl
mcset de_de {Maximum column width:} {Maximale Spaltenlänge:}

### File: ../src/cfg_win.tcl
mcset de_de {Values longer than specified here will be cut in plain text results.} {Values longer than specified here will be cut in plain text results.}

### File: ../src/cfg_win.tcl
mcset de_de Colors Farben

### File: ../src/cfg_win.tcl
mcset de_de {Global colors} {Globale Farben}

### File: ../src/cfg_win.tcl
mcset de_de {MDI windows title bar background color} {MDI windows title bar background color}

### File: ../src/cfg_win.tcl
mcset de_de {MDI windows title bar foreground color} {MDI windows title bar foreground color}

### File: ../src/cfg_win.tcl
mcset de_de {MDI windows title bar button background color} {MDI windows title bar button background color}

### File: ../src/cfg_win.tcl
mcset de_de {MDI windows title bar active button background color} {MDI windows title bar active button background color}

### File: ../src/cfg_win.tcl
mcset de_de {SQL Editor} {SQL Editor}

### File: ../src/cfg_win.tcl
mcset de_de {Editor standard font color} {Editor standard font color}

### File: ../src/cfg_win.tcl
mcset de_de {Editor background} {Editor Hintergrund}

### File: ../src/cfg_win.tcl
mcset de_de {Selected foreground color} {Selected foreground color}

### File: ../src/cfg_win.tcl
mcset de_de {Selected background color} {Selected background color}

### File: ../src/cfg_win.tcl
mcset de_de {Disabled background color} {Disabled background color}

### File: ../src/cfg_win.tcl
mcset de_de {Tables color} Tabellenfarbe

### File: ../src/cfg_win.tcl
mcset de_de {Brackets color} {Brackets color}

### File: ../src/cfg_win.tcl
mcset de_de {Square brackets color} {Square brackets color}

### File: ../src/cfg_win.tcl
mcset de_de {Keywords color} Schlüsselwortfarbe

### File: ../src/cfg_win.tcl
mcset de_de {Variables color} Variablenfarbe

### File: ../src/cfg_win.tcl
mcset de_de {Strings color} Zeichenkettenfarbe

### File: ../src/cfg_win.tcl
mcset de_de {Comments color} Kommentarfarbe

### File: ../src/cfg_win.tcl
mcset de_de {Matched brackets foreground color} {Matched brackets foreground color}

### File: ../src/cfg_win.tcl
mcset de_de {Matched brackets background color} {Matched brackets background color}

### File: ../src/cfg_win.tcl
mcset de_de {Syntax error color} Syntaxfehlerfarbe

### File: ../src/cfg_win.tcl
mcset de_de {Tcl editor} {Tcl Editor}

### File: ../src/cfg_win.tcl
mcset de_de {Options color} {Farbe der Optionen}

### File: ../src/cfg_win.tcl
mcset de_de {Quoted character color} {Quoted character color}

### File: ../src/cfg_win.tcl
mcset de_de {Trees colors} Baumstrukturfarben

### File: ../src/cfg_win.tcl
mcset de_de {Tree background} {Baumstruktur Hintergrund}

### File: ../src/cfg_win.tcl
mcset de_de {Tree standard font color} {Tree standard font color}

### File: ../src/cfg_win.tcl
mcset de_de {Tree selected background color} {Tree selected background color}

### File: ../src/cfg_win.tcl
mcset de_de {Tree selected foreground color} {Tree selected foreground color}

### File: ../src/cfg_win.tcl
mcset de_de {Color for number of objects in tree branch} {Color for number of objects in tree branch}

### File: ../src/cfg_win.tcl
mcset de_de {Grids colors} {Datengitter Farben}

### File: ../src/cfg_win.tcl
mcset de_de {Grid background} Datengitterhintergrund

### File: ../src/cfg_win.tcl
mcset de_de {Grid standard font color} {Grid standard font color}

### File: ../src/cfg_win.tcl
mcset de_de {Grid selected background color} {Grid selected background color}

### File: ../src/cfg_win.tcl
mcset de_de {Grid selected foreground color} {Grid selected foreground color}

### File: ../src/cfg_win.tcl
mcset de_de {Grid base column background color} {Grid base column background color}

### File: ../src/cfg_win.tcl
mcset de_de {Foreground color for cells with NULL value} {Foreground color for cells with NULL value}

### File: ../src/cfg_win.tcl
mcset de_de {Status fields colors} {Statusfeld Farben}

### File: ../src/cfg_win.tcl
mcset de_de {Background color} Hintergrundfarbe

### File: ../src/cfg_win.tcl
mcset de_de {Foreground color} Vordergrundfarbe

### File: ../src/cfg_win.tcl
mcset de_de {Error foreground color} {Vordergrundfarbe von Fehlern}

### File: ../src/cfg_win.tcl
mcset de_de {Information foreground color} {Vordergrundfarbe von Informationen}

### File: ../src/cfg_win.tcl
mcset de_de {Information (second kind) foreground color} {Information (second kind) foreground color}

### File: ../src/cfg_win.tcl
mcset de_de {Miscellaneous colors} {Weitere Farben}

### File: ../src/cfg_win.tcl
mcset de_de {Context hints background color} {Context hints background color}

### File: ../src/cfg_win.tcl
mcset de_de {Context hints foreground color} {Context hints foreground color}

### File: ../src/cfg_win.tcl
mcset de_de Fonts Schriften

### File: ../src/cfg_win.tcl
mcset de_de {SQL editor font} {SQL-Editor Schrift}

### File: ../src/cfg_win.tcl
mcset de_de {Status fields font} {Statusfelder Schrift}

### File: ../src/cfg_win.tcl
mcset de_de {Grid font} {Datengitter Schrift}

### File: ../src/cfg_win.tcl
mcset de_de {Tree font} {Baumstruktur Schrift}

### File: ../src/cfg_win.tcl
mcset de_de {Tree additional labels font} {Tree additional labels font}

### File: ../src/cfg_win.tcl
mcset de_de {Context hints font} {Context hints font}

### File: ../src/cfg_win.tcl
mcset de_de {Changed language needs application to be restarted.} {Changed language needs application to be restarted.}

### File: ../src/cfg_win.tcl
mcset de_de {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.} {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.}

### File: ../src/cfg_win.tcl
mcset de_de {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.} {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.}

### File: ../src/cfg_win.tcl
mcset de_de {SQL formatter options} {SQL formatter options}

### File: ../src/db/db_file_types.tcl
mcset de_de {All SQLite Databases} {Alle SQLite Datenbanken}

### File: ../src/db/db_file_types.tcl
mcset de_de {SQLite 3 Databases} {SQLite 3 Datenbanken}

### File: ../src/db/db_file_types.tcl
mcset de_de {SQLite 2 Databases} {SQLite 2 Datenbanken}

### File: ../src/db/db_file_types.tcl
mcset de_de {All files} {Alle Dateien}

### File: ../src/db/query_executor.tcl
mcset de_de {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.} {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.}

### File: ../src/db/query_executor.tcl
mcset de_de {Invalid database name: %s} {Ungültiger Datenbankname: %s}

### File: ../src/db/query_executor.tcl
mcset de_de {Imbalanced 'BEGIN' ocurrence in query.} {Imbalanced 'BEGIN' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset de_de {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.} {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset de_de {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.} {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset de_de {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.} {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset de_de {Cannot use more than one 'BEGIN'.} {Cannot use more than one 'BEGIN'.}

### File: ../src/db/query_executor.tcl
mcset de_de {Imbalanced 'COMMIT' ocurrence in query.} {Imbalanced 'COMMIT' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset de_de {Imbalanced 'ROLLBACK' ocurrence in query.} {Imbalanced 'ROLLBACK' ocurrence in query.}

### File: ../src/db/sqlite2.tcl
mcset de_de {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)} {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)}

### File: ../src/db/db.tcl
mcset de_de {An internal logic error in SQLite} {Ein interner Logikfehler in SQLite}

### File: ../src/db/db.tcl
mcset de_de {Access permission denied} {Zugriffserlaubnis verweigert}

### File: ../src/db/db.tcl
mcset de_de {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.} {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.}

### File: ../src/db/db.tcl
mcset de_de {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.} {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.}

### File: ../src/db/db.tcl
mcset de_de {A malloc() failed} {Ein malloc() ist fehlgeschlagen}

### File: ../src/db/db.tcl
mcset de_de {Attempt to write a readonly database} {Es wurde versucht eine "nur-lesen" Datenbank zu beschreiben}

### File: ../src/db/db.tcl
mcset de_de {Disk I/O error occurred} {Disk I/O Fehler aufgetreten}

### File: ../src/db/db.tcl
mcset de_de {The database disk image is malformed} {Die Datenbankdatei ist fehlerhaft}

### File: ../src/db/db.tcl
mcset de_de {Database is full} {Database ist voll}

### File: ../src/db/db.tcl
mcset de_de {Unable to open the database file} {Unable to open the database file}

### File: ../src/db/db.tcl
mcset de_de {Database lock protocol error} {Database lock protocol error}

### File: ../src/db/db.tcl
mcset de_de {Database is empty} {Databank ist leer}

### File: ../src/db/db.tcl
mcset de_de {The database schema changed} {Datenbank Schema geändert}

### File: ../src/db/db.tcl
mcset de_de {String or BLOB exceeds size limit} {String or BLOB exceeds size limit}

### File: ../src/db/db.tcl
mcset de_de {Library used incorrectly} {Library used incorrectly}

### File: ../src/db/db.tcl
mcset de_de {Uses OS features not supported on host} {Uses OS features not supported on host}

### File: ../src/db/db.tcl
mcset de_de {Authorization denied} {Authorization denied}

### File: ../src/db/db.tcl
mcset de_de {Auxiliary database format error} {Auxiliary database format error}

### File: ../src/db/db.tcl
mcset de_de {2nd parameter to sqlite3_bind out of range} {2nd parameter to sqlite3_bind out of range}

### File: ../src/db/db.tcl
mcset de_de {File opened that is not a database file} {Bei der geöffneten Datei handelt es sich nicht um eine Datenbank}

### File: ../src/db/db.tcl
mcset de_de {Error while opening %s database:
%s} {Fehler beim Öffnen %s der Datenbank:
%s}

### File: ../src/db/db.tcl
mcset de_de {Not enough parameters passed to function '%s'.} {Nicht genug Parameter für Funktion '%s'.}

### File: ../src/db/db.tcl
mcset de_de {Cannot read file: %s} {Kann Datei %s nicht lesen}

### File: ../src/db/db.tcl
mcset de_de {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.} {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.}

### File: ../src/db/db.tcl
mcset de_de {Could not attach database %s. Error message from SQLite:
%s} {Could not attach database %s. Error message from SQLite:
%s}

### File: ../src/db/db.tcl
mcset de_de {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.} {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.}

### File: ../src/db/sqlite3.tcl
mcset de_de {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)} {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)}

### File: ../src/completion_routines.tcl
mcset de_de {Problem with attaching database:
%s} {Problem with attaching database:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Error from importing plugin:
%s} {Error from importing plugin:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Error creating table '%s':
%s

Importing aborted.} {Error creating table '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Error trying to import data to '%s':
%s

Importing aborted.} {Error trying to import data to '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset de_de Importing... Importing...

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Importing to table '%s'.} {Importing to table '%s'.}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?} {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?} {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Problem occured while importing row number %s:
%s

What would you like to do?} {Problem occured while importing row number %s:
%s

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Importing finished.} {Importing finished.}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Import problem} {Import problem}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Skip this data row} {Skip this data row}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Keep data rows imported so far (%s) and abort} {Keep data rows imported so far (%s) and abort}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Rollback data rows imported so far and abort} {Rollback data rows imported so far and abort}

### File: ../src/plugins/import_plugin.tcl
mcset de_de {Ignore it and proceed} {Ignore it and proceed}

### File: ../src/plugins/import_plugin.tcl
mcset de_de Abort Abbrechen

### File: ../src/plugins/sql_formatting/enterprise/format_s.tcl
mcset de_de name Name

### File: ../src/plugins/sql_formatting/basic.tcl
mcset de_de {Reduce group of whitespaces into one whitespace.} {Reduce group of whitespaces into one whitespace.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset de_de {Uppercase keywords.} {Großgeschriebene Schlüsselwörter.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset de_de {Separate ")" and after contents with single whitespace.} {Separate ")" and after contents with single whitespace.}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {SQLite3 only} {Nur SQLite3}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de Indentation Einrückung

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {New lines} {Neue Linien}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {White spaces} Leerzeichen

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de Names Namen

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de Comments Kommentare

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Tab size:} Tabgröße:

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Line up keywords in multi-line queries} {Line up keywords in multi-line queries}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Ident contents of parenthesis block} {Ident contents of parenthesis block}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Ident parenthesis block in new line} {Ident parenthesis block in new line}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Before opening parenthesis in column definitions} {Before opening parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After opening parenthesis in column definitions} {After opening parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Before closinging parenthesis in column definitions} {Before closinging parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After closinging parenthesis in column definitions} {After closinging parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Before opening parenthesis in expressions} {Before opening parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After opening parenthesis in expressions} {After opening parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Before closinging parenthesis in expressions} {Before closinging parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After closinging parenthesis in expressions} {After closinging parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After comma} {Nach Komma}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After comma in function arguments list} {After comma in function arguments list}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After logical block of query} {After logical block of query}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After semicolon} {Nach Semikolon}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Never before semicolon} {Niemals vor Semikolon}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Before comma in lists} {Vor dem Komma in der Liste}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After comma in lists} {Nach dem Komma in der Liste}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Before opening parenthesis} {Before opening parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After opening parenthesis} {After opening parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Before closing parenthesis} {Before closing parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After closing parenthesis} {After closing parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Before dot operator (in path to database object)} {Before dot operator (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After dot operator (in path to database object)} {After dot operator (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Before mathematical operator} {Before mathematical operator}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {After mathematical operator} {After mathematical operator}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Uppercase keywords} {Großgeschriebene Schlüsselwörter}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Uppercase datatype names} {Großgeschriebene Datentypen}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Always use name wrapping} {Always use name wrapping}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Preferred name wrapper} {Preferred name wrapper}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Expand one line comments (/* ... */) to multiline} {Erweitere einzeilige Kommentare (/* ... */) zu mehrzeiligen Kommentaren}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Indent multi line comments} {Indent multi line comments}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset de_de {Use "*" character for each line} {Benutze das "*" Zeichen für jede Linie}

### File: ../src/plugins/import/csv.tcl
mcset de_de {, (comma)} {, (Komma)}

### File: ../src/plugins/import/csv.tcl
mcset de_de {; (semicolon)} {; (Semikolon)}

### File: ../src/plugins/import/csv.tcl
mcset de_de {\t (tab)} {\t (Tab)}

### File: ../src/plugins/import/csv.tcl
mcset de_de {  (white-space)} {  (Leerzeichen)}

### File: ../src/plugins/import/csv.tcl
mcset de_de Custom Eigen

### File: ../src/plugins/import/csv.tcl
mcset de_de {Input file} {Input file}

### File: ../src/plugins/import/csv.tcl
mcset de_de Browse ...

### File: ../src/plugins/import/csv.tcl
mcset de_de {Show options} {Show options}

### File: ../src/plugins/import/csv.tcl
mcset de_de {Column names} {Column names}

### File: ../src/plugins/import/csv.tcl
mcset de_de {Treat first row as column names} {Treat first row as column names}

### File: ../src/plugins/import/csv.tcl
mcset de_de {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.} {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.}

### File: ../src/plugins/import/csv.tcl
mcset de_de {Columns separator:} {Spalten Trennzeichen:}

### File: ../src/plugins/import/csv.tcl
mcset de_de {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.} {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.}

### File: ../src/plugins/import/csv.tcl
mcset de_de {NULL handling} {NULL handling}

### File: ../src/plugins/import/csv.tcl
mcset de_de {Treat following values as NULL:} {Treat following values as NULL:}

### File: ../src/plugins/import/csv.tcl
mcset de_de Workarounds Workarounds

### File: ../src/plugins/import/csv.tcl
mcset de_de {Expect Microsoft format of CSV} {Expect Microsoft format of CSV}

### File: ../src/plugins/import/csv.tcl
mcset de_de {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.} {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.}

### File: ../src/plugins/import/csv.tcl
mcset de_de Encoding Encoding

### File: ../src/plugins/import/csv.tcl
mcset de_de {Convert from encoding:} {Convert from encoding:}

### File: ../src/plugins/import/csv.tcl
mcset de_de {Input file cannot be empty.} {Input file cannot be empty.}

### File: ../src/plugins/import/csv.tcl
mcset de_de {Input file is not readable.} {Input file is not readable.}

### File: ../src/plugins/import/csv.tcl
mcset de_de {CSV separator cannot be empty.} {CSV Trennzeichen darf nicht leer sein.}

### File: ../src/plugins/import/csv.tcl
mcset de_de {CSV files} {CSV files}

### File: ../src/plugins/import/csv.tcl
mcset de_de {Text files} {Text files}

### File: ../src/plugins/import/csv.tcl
mcset de_de {File to import from} {File to import from}

### File: ../src/plugins/import/dbf.tcl
mcset de_de Auto-detect Auto-detect

### File: ../src/plugins/import/dbf.tcl
mcset de_de {dBase files} {dBase files}

### File: ../src/plugins/import/regexp.tcl
mcset de_de {Regular expression} {Regular expression}

### File: ../src/plugins/import/regexp.tcl
mcset de_de {Visual editor} {Visual editor}

### File: ../src/plugins/import/regexp.tcl
mcset de_de {Use Regular Expression Groups to identify columns.} {Use Regular Expression Groups to identify columns.}

### File: ../src/plugins/import/regexp.tcl
mcset de_de {Case insensitive} {Case insensitive}

### File: ../src/plugins/import/regexp.tcl
mcset de_de Help Hilfe

### File: ../src/plugins/import/regexp.tcl
mcset de_de {RegExp error:
%s} {RegExp error:
%s}

### File: ../src/plugins/export/xls.tcl
mcset de_de {Column names as first row} {Feldnamen als erste Reihe}

### File: ../src/plugins/export/xls.tcl
mcset de_de {If enabled, then first row of exported document will be a list of column names.} {If enabled, then first row of exported document will be a list of column names.}

### File: ../src/plugins/export/xls.tcl
mcset de_de Encoding: Kodierung:

### File: ../src/plugins/export/plain.tcl
mcset de_de {Export NULL values as:} {NULL Werte exportieren als:}

### File: ../src/plugins/export/plain.tcl
mcset de_de {Fixed column width:} {Fixed column width:}

### File: ../src/plugins/export/plain.tcl
mcset de_de {Database: %s (%s, %s)} {Database: %s (%s, %s)}

### File: ../src/plugins/export/plain.tcl
mcset de_de {Table: %s} {Tabelle: %s}

### File: ../src/plugins/export/plain.tcl
mcset de_de {Index: %s} {Index: %s}

### File: ../src/plugins/export/plain.tcl
mcset de_de {Trigger: %s} {Trigger: %s}

### File: ../src/plugins/export/plain.tcl
mcset de_de {View: %s} {View: %s}

### File: ../src/plugins/export/csv.tcl
mcset de_de {If enabled, then first row of exported CSV will be a list of column names.} {If enabled, then first row of exported CSV will be a list of column names.}

### File: ../src/plugins/export/csv.tcl
mcset de_de {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.} {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.}

### File: ../src/plugins/export/json.tcl
mcset de_de {Indented lines} {Indented lines}

### File: ../src/plugins/export/json.tcl
mcset de_de {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.} {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.}

### File: ../src/plugins/export/json.tcl
mcset de_de {Align lines} {Align lines}

### File: ../src/plugins/export/json.tcl
mcset de_de {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.} {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.}

### File: ../src/plugins/export/json.tcl
mcset de_de {Each row as object} {Each row as object}

### File: ../src/plugins/export/json.tcl
mcset de_de {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.} {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.}

### File: ../src/plugins/export/xml.tcl
mcset de_de {No extra white-spaces or new lines} {Ohne extra Leerzeichen oder neue Zeile}

### File: ../src/plugins/export/xml.tcl
mcset de_de {XML tags will be places char-by-char, without any extra white-spaces.} {XML Tags werden ohne extra Leerzeichen exportiert.}

### File: ../src/plugins/export/xml.tcl
mcset de_de {Format output to be human readable} {Lesbare, formatierte Ausgabe}

### File: ../src/plugins/export/xml.tcl
mcset de_de {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.} {Jeder Tag wird in eine neue Zeile geschrieben und das gesamte Dokument wird, zur besseren Lesbarkeit, ausgerichtet.}

### File: ../src/plugins/export/xml.tcl
mcset de_de {Generate XSD file} {XSD Datei erstellen}

### File: ../src/plugins/export/xml.tcl
mcset de_de {Generates XML Schema Definition file using
export file name and extension *.xsd.} {Generates XML Schema Definition file using
export file name and extension *.xsd.}

### File: ../src/plugins/export/xml.tcl
mcset de_de {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s} {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s}

### File: ../src/plugins/export/html.tcl
mcset de_de {First row of exported data will be header
with names of columns, just like in results grid.} {First row of exported data will be header
with names of columns, just like in results grid.}

### File: ../src/plugins/export/html.tcl
mcset de_de {Row numbers as first column} {Zeilennummer als erstes Feld}

### File: ../src/plugins/export/html.tcl
mcset de_de {First column of exported data
will contain row order number.} {First column of exported data
will contain row order number.}

### File: ../src/plugins/export/html.tcl
mcset de_de {Full column names} {Vollständige Feldnamen}

### File: ../src/plugins/export/html.tcl
mcset de_de {Column names in header will be prepended with "table_name." prefix.} {Column names in header will be prepended with "table_name." prefix.}

### File: ../src/plugins/export/html.tcl
mcset de_de {Show types} {Typen anzeigen}

### File: ../src/plugins/export/html.tcl
mcset de_de {Column headers will contain data types.} {Header enthält die Datentypen.}

### File: ../src/plugins/export/html.tcl
mcset de_de {no type} {Kein Typ}

### File: ../src/plugins/export/html.tcl
mcset de_de {For table:} {Für Tabelle:}

### File: ../src/plugins/export/html.tcl
mcset de_de Unique: Einzigartig:

### File: ../src/plugins/export/html.tcl
mcset de_de Yes Ja

### File: ../src/plugins/export/html.tcl
mcset de_de No Nein

### File: ../src/plugins/export/html.tcl
mcset de_de Column Feld

### File: ../src/plugins/export/html.tcl
mcset de_de Collating Collating

### File: ../src/plugins/export/html.tcl
mcset de_de {Sort order} Sortierreihenfolge

### File: ../src/plugins/export/html.tcl
mcset de_de Activated: Aktiviert:

### File: ../src/plugins/export/html.tcl
mcset de_de Action: Aktion:

### File: ../src/plugins/export/html.tcl
mcset de_de {Activate condition:} {Aktivierte Bedingung:}

### File: ../src/plugins/export/html.tcl
mcset de_de {Code executed:} {Code ausgeführt:}

### File: ../src/plugins/export/html.tcl
mcset de_de {Exported database: %s} {Exportierte Datenbank: %s}

### File: ../src/plugins/export/html.tcl
mcset de_de {Generated on %s with %s} {Erstellt am %s mit %s}

### File: ../src/plugins/export/html.tcl
mcset de_de {Exported table: %s} {Exportierte Tabelle: %s}

### File: ../src/plugins/export/html.tcl
mcset de_de {Results of SQL query} {Ergebnis der SQL Abfrage}

### File: ../src/plugins/export/dbf.tcl
mcset de_de {Cannot overwrite file '%s'.} {Cannot overwrite file '%s'.}

### File: ../src/plugins/export/sql.tcl
mcset de_de {Name of table for exported data:} {Name of table for exported data:}

### File: ../src/plugins/export/sql.tcl
mcset de_de {Include "CREATE TABLE" statement at the begining.} {Fügen Sie "CREATE TABLE" an den Anfang ihrer Abfrage.}

### File: ../src/plugins/export/sql.tcl
mcset de_de {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.} {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.}

### File: ../src/plugins/export/sql.tcl
mcset de_de {Include table declaration} {Include table declaration}

### File: ../src/plugins/export/sql.tcl
mcset de_de {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.} {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.}

### File: ../src/plugins/export/sql.tcl
mcset de_de {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.} {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.}

### File: ../src/plugins/export/pdf.tcl
mcset de_de Dimensions Dimensions

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Paper size:} {Paper size:}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Margin size:} {Margin size:}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Cell padding:} {Cell padding:}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Limit amount of data bytes in single cell to:} {Limit amount of data bytes in single cell to:}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Font size:} {Font size:}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Built-in font} {Built-in font}

### File: ../src/plugins/export/pdf.tcl
mcset de_de Font: Font:

### File: ../src/plugins/export/pdf.tcl
mcset de_de {TrueType font} {TrueType font}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Font file:} {Font file:}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Font encoding:} {Font encoding:}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Columns and rows} {Columns and rows}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Header background} {Header background}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Empty space} {Empty space}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Fill empty space in cells} {Fill empty space in cells}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.} {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Minimum height of empty space to fill:} {Minimum height of empty space to fill:}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.} {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Empty space background} {Empty space background}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {TTF Fonts} {TTF Fonts}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {All Files} {All Files}

### File: ../src/plugins/export/pdf.tcl
mcset de_de {Open TTF font} {Open TTF font}

### File: ../src/plugins/populating/random.tcl
mcset de_de {Include alpha characters} {Include alpha characters}

### File: ../src/plugins/populating/random.tcl
mcset de_de {Include numeric characters} {Include numeric characters}

### File: ../src/plugins/populating/random.tcl
mcset de_de {Include whitespace characters} {Include whitespace characters}

### File: ../src/plugins/populating/random.tcl
mcset de_de {Include binary characters} {Include binary characters}

### File: ../src/plugins/populating/random.tcl
mcset de_de {Minimum length:} {Minimale Länge:}

### File: ../src/plugins/populating/random.tcl
mcset de_de {Maximum length:} {Maximale Länge:}

### File: ../src/plugins/populating/random_number.tcl
mcset de_de {Minimum value:} {Minimaler Wert:}

### File: ../src/plugins/populating/random_number.tcl
mcset de_de {Maximum value:} {Maximaler Wert:}

### File: ../src/plugins/populating/random_number.tcl
mcset de_de {Constant prefix:} {Feste Vorsilbe:}

### File: ../src/plugins/populating/random_number.tcl
mcset de_de {Constant suffix:} {Feste Nachsilbe:}

### File: ../src/plugins/populating/sql.tcl
mcset de_de {Initialisation code} {Initialisation code}

### File: ../src/plugins/populating/sql.tcl
mcset de_de {Per iteration code} {Per iteration code}

### File: ../src/plugins/populating/sql.tcl
mcset de_de {Closing code} {Closing code}

### File: ../src/plugins/populating/constant.tcl
mcset de_de {Value to use:} {Wert benutzen:}

### File: ../src/plugins/populating/sequence.tcl
mcset de_de {Start from:} {Start von:}

### File: ../src/plugins/populating/dictionary.tcl
mcset de_de {Dictionary file:} Wörterbuchdatei:

### File: ../src/plugins/populating/dictionary.tcl
mcset de_de {Dictionary words separator:} {Wörterbuch Trennzeichen:}

### File: ../src/plugins/populating/dictionary.tcl
mcset de_de Whitespace Leerzeichen

### File: ../src/plugins/populating/dictionary.tcl
mcset de_de {Line break} Zeilenumbruch

### File: ../src/plugins/populating/dictionary.tcl
mcset de_de {Method of using words:} Wörterverwendungsmethode:

### File: ../src/plugins/populating/dictionary.tcl
mcset de_de Randomly Zufällig

### File: ../src/plugins/populating/dictionary.tcl
mcset de_de Consecutively Fortlaufend

### File: ../src/plugins/populating/dictionary.tcl
mcset de_de {Dictionary file doesn't exist, or unreadable.} {Dictionary file doesn't exist, or unreadable.}

### File: ../src/plugins/populating/dictionary.tcl
mcset de_de {Dictionary file is empty!} {Wörterbuchdatei ist leer!}

### File: ../src/plugins/populating/dictionary.tcl
mcset de_de {Dictionary file} Wörterbuchdatei

### File: ../src/taskbar.tcl
mcset de_de Database: Datenbank:

### File: ../src/taskbar.tcl
mcset de_de Table: Tabelle:

### File: ../src/taskbar.tcl
mcset de_de {Type new name for a window} {Tippen Sie einen neuen Namen ein}

### File: ../src/taskbar.tcl
mcset de_de {Window with given name already exists. Please type other name.} {Window with given name already exists. Please type other name.}

### File: ../src/taskbar.tcl
mcset de_de {Type new name for a task} {Type new name for a task}

### File: ../src/taskbar.tcl
mcset de_de {Close selected window} {Gewähltes Fenster schließen}

### File: ../src/taskbar.tcl
mcset de_de {Close other windows} {Andere Fenster schließen}

### File: ../src/taskbar.tcl
mcset de_de {Close all windows} {Alle Fenster schließen}

### File: ../src/taskbar.tcl
mcset de_de {Restore last closed window} {Restore last closed window}

### File: ../src/taskbar.tcl
mcset de_de {Rename selected window} {Gewähltes Fenster umbennen}

### File: ../src/windows/table_win.tcl
mcset de_de Structure Struktur

### File: ../src/windows/table_win.tcl
mcset de_de Data Daten

### File: ../src/windows/table_win.tcl
mcset de_de Constraints Beschränkungen

### File: ../src/windows/table_win.tcl
mcset de_de Indexes Indizes

### File: ../src/windows/table_win.tcl
mcset de_de Triggers Trigger

### File: ../src/windows/table_win.tcl
mcset de_de {Grid view} Gitteransicht

### File: ../src/windows/table_win.tcl
mcset de_de {Form view} Formularansicht

### File: ../src/windows/table_win.tcl
mcset de_de {Refresh table columns and DDL (%s)} {Felder und DDL (%s) aktualisieren}

### File: ../src/windows/table_win.tcl
mcset de_de {Edit table (%s)} {Bearbeite Tabelle (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Export table data (%s)} {Export table data (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Import data to table (%s)} {Import data to table (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Populate table (%s)} {Populate table (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Create similar table} {Ähnliche Tabelle erstellen}

### File: ../src/windows/table_win.tcl
mcset de_de {Refresh table data (%s)} {Daten aktualisieren (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Add custom number of rows} {Add custom number of rows}

### File: ../src/windows/table_win.tcl
mcset de_de {Add new row (%s)} {Neue Zeile hinzufügen (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Delete selected row (%s)} {Gewählte Zeile löschen (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Commit changes (%s)} {Commit changes (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Rollback new row (%s)} {Rollback new row (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {First %s rows} {Erste %s Zeilen}

### File: ../src/windows/table_win.tcl
mcset de_de {Previous %s rows} {Vorherige %s Zeilen}

### File: ../src/windows/table_win.tcl
mcset de_de {Next %s rows} {Nächste %s Zeilen}

### File: ../src/windows/table_win.tcl
mcset de_de {Last %s rows} {Letzte %s Zeilen}

### File: ../src/windows/table_win.tcl
mcset de_de {Export table data} {Tabellendaten exportieren}

### File: ../src/windows/table_win.tcl
mcset de_de {Import data to table} {Import data to table}

### File: ../src/windows/table_win.tcl
mcset de_de {Populate table} {Tabelle ausfüllen}

### File: ../src/windows/table_win.tcl
mcset de_de {Enter phrase you want to look for} {Suchausdruck eingeben}

### File: ../src/windows/table_win.tcl
mcset de_de {Apply data filter} {Datenfilter übernehmen}

### File: ../src/windows/table_win.tcl
mcset de_de {Clear data filter} {Datenfilter löschen}

### File: ../src/windows/table_win.tcl
mcset de_de {Total rows: %s} {Anzahl Zeilen: %s}

### File: ../src/windows/table_win.tcl
mcset de_de {Rollback changes (%s)} {Rollback changes (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {First row from data grid (%s)} {First row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Previous row from data grid (%s)} {Previous row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Next row from data grid (%s)} {Next row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Last row from data grid (%s)} {Last row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Field switching mode.

Click it to make <Tab> key to insert tab characters.} {Field switching mode.

Click it to make <Tab> key to insert tab characters.}

### File: ../src/windows/table_win.tcl
mcset de_de {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.} {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.}

### File: ../src/windows/table_win.tcl
mcset de_de {Refresh table indexes (%s)} {Indizes akzualisieren (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Create new index (%s)} {Erzeuge neuen Index (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Edit index (%s)} {Bearbeite Index (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Delete index (%s)} {Lösche Index (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Refresh table triggers (%s)} {Aktualisiere Trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Create new trigger (%s)} {Erzeuge neuen Trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Edit trigger (%s)} {Bearbeite Trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Delete trigger (%s)} {Lösche Trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset de_de {Constraint name} {Name Beschränkung}

### File: ../src/windows/table_win.tcl
mcset de_de {Column name} Feldname

### File: ../src/windows/table_win.tcl
mcset de_de Default Standard

### File: ../src/windows/table_win.tcl
mcset de_de {Not NULL} {Nicht NULL}

### File: ../src/windows/table_win.tcl
mcset de_de {Primary key} Primärschlüssel

### File: ../src/windows/table_win.tcl
mcset de_de Unique Eindeutig

### File: ../src/windows/table_win.tcl
mcset de_de Collate Kollation

### File: ../src/windows/table_win.tcl
mcset de_de Check Prüfen

### File: ../src/windows/table_win.tcl
mcset de_de {Foreign key} Fremdschlüssel

### File: ../src/windows/table_win.tcl
mcset de_de {Index name} Indexname

### File: ../src/windows/table_win.tcl
mcset de_de {On column} {On column}

### File: ../src/windows/table_win.tcl
mcset de_de {SQL code} {SQL Code}

### File: ../src/windows/table_win.tcl
mcset de_de {Trigger name} Triggername

### File: ../src/windows/table_win.tcl
mcset de_de {On table} {On table}

### File: ../src/windows/table_win.tcl
mcset de_de Name Name

### File: ../src/windows/table_win.tcl
mcset de_de {Data type} Datentyp

### File: ../src/windows/table_win.tcl
mcset de_de {Default value} Standardwert

### File: ../src/windows/table_win.tcl
mcset de_de {Refreshing dependencies} {Refreshing dependencies}

### File: ../src/windows/table_win.tcl
mcset de_de {Refreshing table columns...} {Tabellenspalten erneuern...}

### File: ../src/windows/table_win.tcl
mcset de_de {Refreshing table data...} {Tabellendaten erneuern...}

### File: ../src/windows/table_win.tcl
mcset de_de {Refreshing table indexes...} {Tabellenindize erneuern...}

### File: ../src/windows/table_win.tcl
mcset de_de {Refreshing table triggers...} {Tabellentrigger erneuern...}

### File: ../src/windows/table_win.tcl
mcset de_de {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.} {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.}

### File: ../src/windows/table_win.tcl
mcset de_de {Check condition} Gültigkeitsprüfung

### File: ../src/windows/table_win.tcl
mcset de_de {Total rows: %s (filtered)} {Gesammte Zeilen: %s (gefiltert)}

### File: ../src/windows/table_win.tcl
mcset de_de {Pending commits} {Pending commits}

### File: ../src/windows/table_win.tcl
mcset de_de {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?} {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?}

### File: ../src/windows/table_win.tcl
mcset de_de {Loading data...} {Daten laden...}

### File: ../src/windows/table_win.tcl
mcset de_de {Loading table '%s'...} {Tabelle laden '%s'...}

### File: ../src/windows/table_win.tcl
mcset de_de {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.} {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.}

### File: ../src/windows/table_win.tcl
mcset de_de {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.} {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.}

### File: ../src/windows/table_win.tcl
mcset de_de {Edit table} {Tabelle bearbeiten}

### File: ../src/windows/table_win.tcl
mcset de_de {Enter number of rows to add:} {Enter number of rows to add:}

### File: ../src/windows/table_win.tcl
mcset de_de {Add rows} {Add rows}

### File: ../src/windows/table_win.tcl
mcset de_de {New index} {Neuer Index}

### File: ../src/windows/table_win.tcl
mcset de_de {Index '%s' has no DDL. Probably it's system index and should not be edited.} {Index '%s' has no DDL. Probably it's system index and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset de_de {Edit index} {Index bearbeiten}

### File: ../src/windows/table_win.tcl
mcset de_de {Delete index} {Index löschen}

### File: ../src/windows/table_win.tcl
mcset de_de {Are you sure you want to delete '%s' index?} {Wollen Sie wirklich den Index '%s' löschen?}

### File: ../src/windows/table_win.tcl
mcset de_de {New trigger} {Neuer Trigger}

### File: ../src/windows/table_win.tcl
mcset de_de {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.} {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset de_de {Edit trigger} {Trigger bearbeiten}

### File: ../src/windows/table_win.tcl
mcset de_de {Delete trigger} {Trigger löschen}

### File: ../src/windows/table_win.tcl
mcset de_de {Are you sure you want to delete '%s' trigger?} {Wollen Sie wirklich den Trigger '%s' löschen?}

### File: ../src/windows/table_win.tcl
mcset de_de {Export table} {Tabelle exportieren}

### File: ../src/windows/table_win.tcl
mcset de_de {Import data} {Import data}

### File: ../src/windows/editor_win.tcl
mcset de_de {SQL query} {SQL Abfrage}

### File: ../src/windows/editor_win.tcl
mcset de_de Results Ergebnis

### File: ../src/windows/editor_win.tcl
mcset de_de History Protokoll

### File: ../src/windows/editor_win.tcl
mcset de_de {Execute query (%s)} {Abfrage (%s) ausführen}

### File: ../src/windows/editor_win.tcl
mcset de_de {Execute query with plain string results} {Abfrageausführuhng mit Klartext Ergebnis}

### File: ../src/windows/editor_win.tcl
mcset de_de {Explain query (%s)} {Explain query (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Format SQL code (%s)} {Formatiere SQL Code (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Refresh syntax highlighting (%s)} {Aktualisiere Syntaxhervorhebung (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Clear history} {Lösche Protokoll}

### File: ../src/windows/editor_win.tcl
mcset de_de {Export results} {Exportiere Ergebnisse}

### File: ../src/windows/editor_win.tcl
mcset de_de {Create view from query} {View aus der Abfrage erstellen}

### File: ../src/windows/editor_win.tcl
mcset de_de {Execute SQL from file (%s)} {SQL aus einer Datei ausführen (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Load SQL from file (%s)} {Lade SQL von einer Datei (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Save SQL to file (%s)} {Speichere in SQL Datei (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Default database for SQL executing
(%s/%s)} {Default database for SQL executing
(%s/%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de Database Datenbank

### File: ../src/windows/editor_win.tcl
mcset de_de {Execution date} Ausführungsdatum

### File: ../src/windows/editor_win.tcl
mcset de_de {Execution time (s)} {Ausführungsdauer (s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Rows affected} {Zeilen betroffen}

### File: ../src/windows/editor_win.tcl
mcset de_de SQL SQL

### File: ../src/windows/editor_win.tcl
mcset de_de {Plain text view} {Plain text view}

### File: ../src/windows/editor_win.tcl
mcset de_de {Refresh results (%s)} {Refresh results (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Commit row (%s)} {Commit row (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Rollback row (%s)} {Rollback row (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Copy (%s)} {Kopieren (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Cut (%s)} {Ausschneiden (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Paste (%s)} {Einfügen (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Show line numbers} {Zeilennummern zeigen}

### File: ../src/windows/editor_win.tcl
mcset de_de {Delete selected history entry (%s)} {Delete selected history entry (%s)}

### File: ../src/windows/editor_win.tcl
mcset de_de {Choose the database first.} {Zuerst eine Datenbank wählen.}

### File: ../src/windows/editor_win.tcl
mcset de_de {Error while trying to collect completion list: %s} {Error while trying to collect completion list: %s}

### File: ../src/windows/editor_win.tcl
mcset de_de {Can't open %s file for reading.} {Kann Datei %s nicht zum Lesen öffnen.}

### File: ../src/windows/editor_win.tcl
mcset de_de {Can't open %s file for writting.} {Kann Datei %s nicht zum Schreiben öffnen.}

### File: ../src/windows/editor_win.tcl
mcset de_de {SQL code saved in %s.} {SQL-Anweisungen in %s gesichert.}

### File: ../src/windows/editor_win.tcl
mcset de_de {Are you sure you want to clear queries history?} {Wollen Sie wirklich die Abfragehistorie löschen?}

### File: ../src/windows/editor_win.tcl
mcset de_de {Delete the history entry} {Delete the history entry}

### File: ../src/windows/editor_win.tcl
mcset de_de {Are you sure you want to delete selected queries history entry?} {Are you sure you want to delete selected queries history entry?}

### File: ../src/windows/editor_win.tcl
mcset de_de Processing... Ausführung...

### File: ../src/windows/editor_win.tcl
mcset de_de {Processing query...} {Abfrage wird ausgeführt...}

### File: ../src/windows/editor_win.tcl
mcset de_de {No results to export.} {Keine Ergebnisse zum Exportieren.}

### File: ../src/windows/editor_win.tcl
mcset de_de {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.} {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.}

### File: ../src/windows/editor_win.tcl
mcset de_de {Query execution...} Abfragenausführung...

### File: ../src/windows/editor_win.tcl
mcset de_de {Executing SQL query...} {Führe SQL Abfrage aus...}

### File: ../src/windows/editor_win.tcl
mcset de_de {Error while executing query: %s} {Fehler bei Ausführung der Abfrage: %s}

### File: ../src/windows/editor_win.tcl
mcset de_de {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s} {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s}

### File: ../src/windows/editor_win.tcl
mcset de_de {%s row(s) read in %s second(s).} {%s row(s) read in %s second(s).}

### File: ../src/windows/editor_win.tcl
mcset de_de {%s row(s) affected in %s second(s).} {%s Zeile(n) betroffen in %s Sekunden.}

### File: ../src/windows/editor_win.tcl
mcset de_de {No SELECT statements found in editor or in selected part of SQL code.} {No SELECT statements found in editor or in selected part of SQL code.}

### File: ../src/windows/editor_win.tcl
mcset de_de {More than one SELECT statements found. Please select the one you're interested in and then try again.} {More than one SELECT statements found. Please select the one you're interested in and then try again.}

### File: ../src/windows/editor_win.tcl
mcset de_de {New view} {Neuer View}

### File: ../src/windows/editor_win.tcl
mcset de_de {Fill query parameters} {Fill query parameters}

### File: ../src/error.tcl
mcset de_de {Background error} Hintergrundfehler

### File: ../src/error.tcl
mcset de_de Close Schließen

### File: ../src/error.tcl
mcset de_de {Report the bug} {Fehler melden}

### File: ../src/dialogs/about_dialog.tcl
mcset de_de About Über

### File: ../src/dialogs/about_dialog.tcl
mcset de_de {Packages and plugins} {Pakete und Erweiterungen}

### File: ../src/dialogs/about_dialog.tcl
mcset de_de Licence Lizenz

### File: ../src/dialogs/about_dialog.tcl
mcset de_de {Installed plugins:} {Installierte Erweiterungen:}

### File: ../src/dialogs/about_dialog.tcl
mcset de_de {Used Tcl packages:} {Benutzte Tcl Pakete:}

### File: ../src/dialogs/about_dialog.tcl
mcset de_de {SQLite3 engine version: %s} {SQLite3 Engine Version: %s}

### File: ../src/dialogs/searchdialog.tcl
mcset de_de {Global expression understeands '*', '?' and \[chars].} {Global expression understeands '*', '?' and \[chars].}

### File: ../src/dialogs/searchdialog.tcl
mcset de_de Find Suchen

### File: ../src/dialogs/searchdialog.tcl
mcset de_de Replace Ersetzen

### File: ../src/dialogs/searchdialog.tcl
mcset de_de {Do you want to replace marked text?} {Wollen Sie den markierten Text ersetzen?}

### File: ../src/dialogs/searchdialog.tcl
mcset de_de {Replace all} {Alles ersetzen}

### File: ../src/dialogs/searchdialog.tcl
mcset de_de {Replacing finished.} {Ersetzen beendet.}

### File: ../src/dialogs/searchdialog.tcl
mcset de_de {Cannot match the pattern!} {Kann keine Übereinstimmung finden!}

### File: ../src/dialogs/bind_param.tcl
mcset de_de {Query number %s} {Abfragennummer %s}

### File: ../src/dialogs/bind_param.tcl
mcset de_de {Parameter number %s (named: %s):} {Parameter number %s (named: %s):}

### File: ../src/dialogs/bind_param.tcl
mcset de_de {NULL value} {NULL value}

### File: ../src/dialogs/bind_param.tcl
mcset de_de {You can use '%s' keyboard shortcut to switch NULL value.} {You can use '%s' keyboard shortcut to switch NULL value.}

### File: ../src/dialogs/bind_param.tcl
mcset de_de {Copy value to other '%s' parameters (%s)} {Copy value to other '%s' parameters (%s)}

### File: ../src/dialogs/bind_param.tcl
mcset de_de {By enabling this all parameters with same name
will also have same value as this one.} {By enabling this all parameters with same name
will also have same value as this one.}

### File: ../src/dialogs/bind_param.tcl
mcset de_de {Execute query} {Abfrage ausführen}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset de_de Collation Kollation

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset de_de Sort Sortieren

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset de_de {Named constraint:} {Named constraint:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset de_de {On conflict:} {Bei Konflikt:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset de_de {Constraint is marked as being named, but there's no name filled in.} {Constraint is marked as being named, but there's no name filled in.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset de_de {Collation for column '%s' is enabled, but there's no collation name filled in.} {Collation for column '%s' is enabled, but there's no collation name filled in.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset de_de {No columns are selected.} {Keine Spalten ausgewählt.}

### File: ../src/dialogs/populate_table.tcl
mcset de_de {Number of rows to insert:} {Anzahl Zeilen zum Einfügen:}

### File: ../src/dialogs/populate_table.tcl
mcset de_de {On a constraint violation:} {On a constraint violation:}

### File: ../src/dialogs/populate_table.tcl
mcset de_de Mode Methode

### File: ../src/dialogs/populate_table.tcl
mcset de_de {Select table to display available columns} {Wählen Sie eine Tabelle zur Anzeige der vorhandenen Felder}

### File: ../src/dialogs/populate_table.tcl
mcset de_de Populate Ausfüllen

### File: ../src/dialogs/populate_table.tcl
mcset de_de {Error occured while populating table:
%s} {Fehler aufgetreten beim Ausfüllen der Tabelle:
%s}

### File: ../src/dialogs/populate_table.tcl
mcset de_de Configuration Konfiguration

### File: ../src/dialogs/populate_table.tcl
mcset de_de {You have to type valid number of rows to insert.} {You have to type valid number of rows to insert.}

### File: ../src/dialogs/populate_table.tcl
mcset de_de {You have to select at least one column to populate.} {Sie müssen mindestens ein Feld zum Ausfüllen wählen.}

### File: ../src/dialogs/populate_table.tcl
mcset de_de Populating... Füllen...

### File: ../src/dialogs/populate_table.tcl
mcset de_de {Populating table '%s'.} {Fülle Tabelle '%s'.}

### File: ../src/dialogs/populate_table.tcl
mcset de_de Stop Stopp

### File: ../src/dialogs/table_dialog_fk.tcl
mcset de_de {Foreign table:} {Fremdschlüssel Tabelle:}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset de_de {Local column} {Lokale Spalte}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset de_de {Foreign column} {Fremde Spalte}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset de_de Reactions Reactions

### File: ../src/dialogs/table_dialog_fk.tcl
mcset de_de {ON UPDATE} {ON UPDATE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset de_de {ON DELETE} {ON DELETE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset de_de MATCH MATCH

### File: ../src/dialogs/table_dialog_fk.tcl
mcset de_de {Deferred foreign key} {Deferred foreign key}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset de_de {No foreign table selected.} {No foreign table selected.}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset de_de {There's no foreign column assigned for local column '%s'.} {There's no foreign column assigned for local column '%s'.}

### File: ../src/dialogs/import_dialog.tcl
mcset de_de {Import from:} {Import from:}

### File: ../src/dialogs/import_dialog.tcl
mcset de_de {Import to:} {Import to:}

### File: ../src/dialogs/import_dialog.tcl
mcset de_de Table Tabelle

### File: ../src/dialogs/import_dialog.tcl
mcset de_de Existing Existing

### File: ../src/dialogs/import_dialog.tcl
mcset de_de {Create new table} {Create new table}

### File: ../src/dialogs/import_dialog.tcl
mcset de_de Import Import

### File: ../src/dialogs/import_dialog.tcl
mcset de_de {Import method is not selected.} {Import method is not selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset de_de {You have to choose database.} {Sie müssen eine Datenbank auswählen.}

### File: ../src/dialogs/import_dialog.tcl
mcset de_de {No existing table is selected.} {No existing table is selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset de_de {Table typed to create already exists. Please change table name.} {Table typed to create already exists. Please change table name.}

### File: ../src/dialogs/view_dialog.tcl
mcset de_de View Ansicht

### File: ../src/dialogs/view_dialog.tcl
mcset de_de {View name:} View-Name:

### File: ../src/dialogs/view_dialog.tcl
mcset de_de {Code executed to get view data:} {Code für View ausgeführt:}

### File: ../src/dialogs/view_dialog.tcl
mcset de_de Create Erzeugen

### File: ../src/dialogs/view_dialog.tcl
mcset de_de Change Ändern

### File: ../src/dialogs/view_dialog.tcl
mcset de_de {You have to specify database.} {Sie müssen eine Datenbank angeben.}

### File: ../src/dialogs/view_dialog.tcl
mcset de_de {You have to specify view name.} {Sie müssen einen Namen für den View angeben.}

### File: ../src/dialogs/view_dialog.tcl
mcset de_de {You havn't wrote a code for the view.} {Sie heben keinen Code für den View geschrieben.}

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {Export data} {Daten exportieren}

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {Only structure, without data} {Nur Struktur, keine Daten}

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {Table or view} {Table or view}

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {Output file} Dateiname

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {Export format} Ausgabeformat

### File: ../src/dialogs/export_dialog.tcl
mcset de_de Export Export

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {You have to choose file.} {Sie müssen eine Datei wählen.}

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {Can't write to file: %s} {Kann nicht in Datei: %s schreiben}

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {You have to choose table.} {Sie müssen eine Tabelle auswählen.}

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {Exporting database '%s'.} {Exportiere Datenbank '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {Exporting table '%s'.} {Exportiere Tabelle '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {Exporting view '%s'.} {Exporting view '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {Exporting results.} Exportergebnisse.

### File: ../src/dialogs/export_dialog.tcl
mcset de_de Exporting... Exportierung...

### File: ../src/dialogs/export_dialog.tcl
mcset de_de {Cannot write to file: %s
Please select other file.} {Kann Datei nicht beschreiben: %s
Bitte wählen Sie eine andere Datei.}

### File: ../src/dialogs/bug_report_login.tcl
mcset de_de {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.} {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.}

### File: ../src/dialogs/bug_report_login.tcl
mcset de_de Login: Login:

### File: ../src/dialogs/bug_report_login.tcl
mcset de_de Password: Password:

### File: ../src/dialogs/bug_report_login.tcl
mcset de_de Validate Validate

### File: ../src/dialogs/bug_report_login.tcl
mcset de_de {Validation result} {Validation result}

### File: ../src/dialogs/bug_report_login.tcl
mcset de_de {Not validated yet} {Not validated yet}

### File: ../src/dialogs/bug_report_login.tcl
mcset de_de Validating... Validating...

### File: ../src/dialogs/bug_report_login.tcl
mcset de_de {Validating login and password...} {Validating login and password...}

### File: ../src/dialogs/bug_report_login.tcl
mcset de_de {Invalid login or password.} {Invalid login or password.}

### File: ../src/dialogs/bug_report_login.tcl
mcset de_de {Login and password are correct.} {Login and password are correct.}

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Your e-mail address or user (both optional)} {Your e-mail address or user (both optional)}

### File: ../src/dialogs/bug_report.tcl
mcset de_de or oder

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Log in} {Log in}

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Logged in} {Logged in}

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Log out} {Log out}

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Brief description:} Auftragsbeschreibung:

### File: ../src/dialogs/bug_report.tcl
mcset de_de {How to reproduce problem (if possible):} {Wie kann der Fehler reproduziert werden (wenn möglich):}

### File: ../src/dialogs/bug_report.tcl
mcset de_de {What is the problem:} {Was ist das Problem:}

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Show more (optional)} {Show more (optional)}

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Operating system:} Betriebssystem:

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Take screenshots of all SQLiteStudio windows and attach them} {Machen Sie einen Screenshot von allen SQLiteStudio Fenstern und fügen sie sie bei}

### File: ../src/dialogs/bug_report.tcl
mcset de_de Send Senden

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Describe your feature request:} {Beschreibe dein Funktionsvorschlag:}

### File: ../src/dialogs/bug_report.tcl
mcset de_de Hide Hide

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Please fill 'Brief' field.} {Please fill 'Brief' field.}

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Please fill at least one of 'Description' or 'How to reproduce' fields.} {Please fill at least one of 'Description' or 'How to reproduce' fields.}

### File: ../src/dialogs/bug_report.tcl
mcset de_de {Please provide valid e-mail address or leave 'E-mail' empty.} {Please provide valid e-mail address or leave 'E-mail' empty.}

### File: ../src/dialogs/bug_report.tcl
mcset de_de {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.} {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Database to convert:} {Datenbank zum Konvertieren:}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Converted database name:} {Name der konvertierten Datenbank:}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {File to use for converted database:} {Datei für konvertierte Datenbank:}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Choose new file for database} {Neue Datei für Datenbank wählen}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Database version:} Datenbankversion:

### File: ../src/dialogs/db_convert.tcl
mcset de_de Convert Konvertieren

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Convert database} {Konvertiere Datenbank}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {You chave to choose database to convert.} {Sie müssen einen Datenbank zum Konvertieren auswählen.}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Error resolving database with name %s!} {Ausführungsfehler bei Datenbank %s!}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {You have to specify new database file.} {Sie müssen eine neue Datenbankdatei angeben.}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Cannot use existing file for converted database.} {Kann keine bestehende Datei für konvertierte Datenbank benutzen.}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Cannot use existing name for converted database.} {Kann keine bestehenden Namen für konvertierte Datenbank benutzen.}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Cannot find handler for database labeled with: %s} {Kann keinen Handlet dür Datenbank: %s finden}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Error while trying to create database: %s} {Fehler beim Erstellen der Datrenbank: %s}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Database converting error} Datenbankkonvertierungsfehler

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s} {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s}

### File: ../src/dialogs/db_convert.tcl
mcset de_de {Choose file} {Datei wählen}

### File: ../src/dialogs/yesno.tcl
mcset de_de Question Question

### File: ../src/dialogs/yesno.tcl
mcset de_de Warning Warnung

### File: ../src/dialogs/yesno.tcl
mcset de_de Error Fehler

### File: ../src/dialogs/yesno.tcl
mcset de_de Information Information

### File: ../src/dialogs/import_db.tcl
mcset de_de {Import from one of databases:} {Importieren einer der Datenbanken:}

### File: ../src/dialogs/import_db.tcl
mcset de_de {Choose database file to import:} {Datenbankdatei zum Importieren auswählen:}

### File: ../src/dialogs/import_db.tcl
mcset de_de {No database chosen.} {Keine Datenbank ausgewählt.}

### File: ../src/dialogs/import_db.tcl
mcset de_de {Cannot open specified database.} {Kann angegebene Datenbank nicht öffnen.}

### File: ../src/dialogs/import_db.tcl
mcset de_de {Error while importing database:
%s} {Fehler beim Importieren der Datenbank:
%s}

### File: ../src/dialogs/import_db.tcl
mcset de_de {Select file} {Datei auswählen}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de Column: Feld:

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Column constraints:} Spaltenbeschränkung:

### File: ../src/dialogs/column_dialog.tcl
mcset de_de Add Hinzufügen

### File: ../src/dialogs/column_dialog.tcl
mcset de_de Size Größe

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Maximal length of value in column.} {Feldlänge. Maximale Anzahl Zeichen für Feldwert}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Primary key configuration} {Primary key configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de Autoincrement Autoincrement

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Sort order:} Sortierreihenfolge:

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {No foreign column selected.} {No foreign column selected.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Choose ON UPDATE action, or disable it.} {Choose ON UPDATE action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Choose ON DELETE action, or disable it.} {Choose ON DELETE action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Choose MATCH action, or disable it.} {Choose MATCH action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Foreign key configuration} {Foreign key configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Foreign column:} {Foreign column:}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Unique configuration} {Unique configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Fill in the condition expression.} {Fill in the condition expression.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Check condition configuration} {Check condition configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de Condition: Kondition:

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Not null configuration} {Not null configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Fill in the collation name.} {Fill in the collation name.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Collating configuration} {Collating configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Collation name:} Kollationsname:

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Fill in the default value.} {Fill in the default value.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Default value configuration} {Default value configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Default value:} Standardwert:

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Use value as:} {Use value as:}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {A literal value} {A literal value}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {An expression} {An expression}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Column primary key is not configured correctly.} {Column primary key is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {AUTOINCREMENT is allowed only with INTEGER type of column.} {AUTOINCREMENT is allowed only with INTEGER type of column.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Column foreign key is not configured correctly.} {Column foreign key is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Column 'unique' constraint is not configured correctly.} {Column 'unique' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Column 'check' constraint is not configured correctly.} {Column 'check' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Column 'notnull' constraint is not configured correctly.} {Column 'notnull' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Column 'default' constraint is not configured correctly.} {Column 'default' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Column 'collate' constraint is not configured correctly.} {Column 'collate' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {No column name is specified.} {No column name is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Column with name '%s' already exists in the table.} {Column with name '%s' already exists in the table.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Data type bounds are given, but no data type name is specified.} {Data type bounds are given, but no data type name is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Data type precision is given, but no data type size is specified.} {Data type precision is given, but no data type size is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Data type size has invalid format. Only integer value is allowed.} {Data type size has invalid format. Only integer value is allowed.}

### File: ../src/dialogs/column_dialog.tcl
mcset de_de {Data type precision has invalid format. Only integer value is allowed.} {Data type precision has invalid format. Only integer value is allowed.}

### File: ../src/dialogs/assoc_dialog.tcl
mcset de_de {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:} {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:}

### File: ../src/dialogs/assoc_dialog.tcl
mcset de_de {Current associations} {Current associations}

### File: ../src/dialogs/assoc_dialog.tcl
mcset de_de {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.} {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {Database file:} Datenbankdatei:

### File: ../src/dialogs/db_edit.tcl
mcset de_de {Database name:} Datenbankname:

### File: ../src/dialogs/db_edit.tcl
mcset de_de {Generate automatically} {Automatisch generiert}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {Type name in field below:} {Namen bitte unterhalb eingeben:}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {Remember it permanently} {Dauerhaft merken}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {If disabled, then the database will be registered only
for this single SQLiteStudio session.} {If disabled, then the database will be registered only
for this single SQLiteStudio session.}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {Edit database} {Datenbank bearbeiten}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {Add database} {Datenbank hinzufügen}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {File '%s' doesn't exist!} {File '%s' doesn't exist!}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {You have to specify database file.} {Sie müssen eine Datenbankdatei angeben.}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {Database named '%s' already exists on databases list. Please pick other name.} {Database named '%s' already exists on databases list. Please pick other name.}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.} {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.} {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {Type not existing file for new database} {Type not existing file for new database}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {Select existing database file} {Select existing database file}

### File: ../src/dialogs/db_edit.tcl
mcset de_de {%s is not supported database!} {%s ist keine unterstützte Datenbank!}

### File: ../src/dialogs/table_dialog_pk.tcl
mcset de_de {Using autoincrement with more than one column at once is forbidden.} {Using autoincrement with more than one column at once is forbidden.}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de Previous Zurück

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de Next Weiter

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {Do not show this dialog at startup} {Dialog beim Start nicht zeigen}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		} {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			You can configure all SQL editor syntax colors in settings.
		} {
			You can configure all SQL editor syntax colors in settings.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		} {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		} {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		} {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		} {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		} {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		} {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		} {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		} {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		} {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		} {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		} {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		} {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		} {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		} {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		} {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		} {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset de_de {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		} {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		}

### File: ../src/dialogs/import_table.tcl
mcset de_de Separator: Trennzeichen:

### File: ../src/dialogs/import_table.tcl
mcset de_de {Common separator is \t (tab), but sometimes others can be met.} {Der üblüche Separator ist \t (tab), manchmal auch andere Zeichen.}

### File: ../src/dialogs/import_table.tcl
mcset de_de {Import data file for '%s' table:} {Importiere Datendatei für Tabelle '%s':}

### File: ../src/dialogs/import_table.tcl
mcset de_de {File '%s' isn't readable!} {Datei '%s' ist nicht lesbar!}

### File: ../src/dialogs/import_table.tcl
mcset de_de {Error while trying to copy data:
%s} {Fehler beim Versuch Daten zu kopieren:
%s}

### File: ../src/dialogs/release_notes_dialog.tcl
mcset de_de {Don't show this dialog after update.} {Don't show this dialog after update.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de Trigger Trigger

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {On action:} {Auf Aktion:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {Trigger name:} {Trigger Name:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de When: Wenn:

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {On table:} {Auf Tabelle:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {Execute code for:} {Code ausführen für:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.} {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {Execute code only when:} {Code ausführen nur wenn:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {Code executed for above configuration:} {Code wurde für obige Konfiguration ausgeführt:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {You have to specify view.} {Sie müssen einen View angeben.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {You have to specify table.} {Sie müssen eine Tabelle angeben.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {You have to specify trigger name.} {Sie müssen einen Triggernamen angeben.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {You have to specify 'action' condition.} {Sie müssen eine Bedingung für 'on action' angeben.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {You havn't wrote a code for the trigger.} {Sie haben keinen Code zum Trigger geschrieben.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset de_de {On view:} {Auf view:}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de Columns: Felder:

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Table constraints:} Tabellenbeschränkung:

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Table name:} Tabellenname:

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Add column} {Feld hinzufügen}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Edit selected} {Auswahl bearbeiten}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Delete selected} {Auswahl löschen}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de Type Type

### File: ../src/dialogs/table_dialog.tcl
mcset de_de Details Details

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.} {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Edit column} {Feld bearbeiten}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Delete column} {Spalte löschen}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Are you sure you want to delete column '%s'?} {Are you sure you want to delete column '%s'?}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Constraint change} {Constraint change}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Are you sure you want to change constraint type?
Current constraint configuration will be lost.} {Are you sure you want to change constraint type?
Current constraint configuration will be lost.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Table constraint number %s (%s) is not configured correctly.} {Table constraint number %s (%s) is not configured correctly.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {There's no column defined.} {Es wurde keine Spalte definiert.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {There is already a table with name '%s'. Please change the name of this table.} {There is already a table with name '%s'. Please change the name of this table.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {There is already an index with name '%s'. Please change the name of this index.} {There is already an index with name '%s'. Please change the name of this index.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {There is already a trigger with name '%s'. Please change the name of this trigger.} {There is already a trigger with name '%s'. Please change the name of this trigger.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {There is already a view with name '%s'. Please change the name of this view.} {There is already a view with name '%s'. Please change the name of this view.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Trigger parsing problem} {Trigger parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Index parsing problem} {Index parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {View parsing problem} {View parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.} {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {%s(%s) referencing %s(%s)} {%s(%s) referencing %s(%s)}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s} {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Do you want to continue anyway?} {Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?} {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Modifying table...} {Modifiziere Tabelle...}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Modifying table '%s'.} {Modifiziere Tabelle '%s'.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Could not recreate triggers for modified table.} {Could not recreate triggers for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Could not recreate indexes for modified table.} {Could not recreate indexes for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Could not recreate views for modified table.} {Could not recreate views for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Trigger recreation problem} {Trigger recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Index recreation problem} {Index recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {Could not recreate foreign keys for tables referencing modified table.} {Could not recreate foreign keys for tables referencing modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {View recreation problem} {View recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset de_de {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).} {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).}

### File: ../src/dialogs/table_dialog_chk.tcl
mcset de_de {Condition expression cannot be empty.} {Condition expression cannot be empty.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset de_de {What would you like to do?} {Was möchten Sie tun?}

### File: ../src/dialogs/new_version_dialog.tcl
mcset de_de {Install it automatically} {Automatisch installieren}

### File: ../src/dialogs/new_version_dialog.tcl
mcset de_de {Go to download page} {Zur Downloadseite gehen}

### File: ../src/dialogs/new_version_dialog.tcl
mcset de_de {Package download} {Paket herunterladen}

### File: ../src/dialogs/new_version_dialog.tcl
mcset de_de {Insufficient privileges to perform automatic update.} {Insufficient privileges to perform automatic update.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset de_de {Check for updates at startup} {Beim Start auf Updates prüfen}

### File: ../src/dialogs/new_version_dialog.tcl
mcset de_de {New version of SQLiteStudio is available: %s} {Eine neue Version von SQLiteStudio ist verfügbar: %s}

### File: ../src/dialogs/trigger_dialog_cols.tcl
mcset de_de {Trigger columns} {Trigger columns}

### File: ../src/dialogs/blob_edit.tcl
mcset de_de Commit Commit

### File: ../src/dialogs/bug_history.tcl
mcset de_de Clear Leeren

### File: ../src/dialogs/bug_history.tcl
mcset de_de {Reported on} {Gemeldet am}

### File: ../src/dialogs/bug_history.tcl
mcset de_de Brief Auftrag

### File: ../src/dialogs/bug_history.tcl
mcset de_de URL URL

### File: ../src/dialogs/bug_history.tcl
mcset de_de Discussion Diskussion

### File: ../src/dialogs/bug_history.tcl
mcset de_de {Clear reports} {Protokoll leeren}

### File: ../src/dialogs/bug_history.tcl
mcset de_de {Do you want to clear whole bug reports history?} {Wollen sie das Fehlerprotokoll leeren?}

### File: ../src/dialogs/index_dialog.tcl
mcset de_de Index Index

### File: ../src/dialogs/index_dialog.tcl
mcset de_de {Index name:} Indexname:

### File: ../src/dialogs/index_dialog.tcl
mcset de_de Available Available

### File: ../src/dialogs/index_dialog.tcl
mcset de_de Indexed Indexed

### File: ../src/dialogs/index_dialog.tcl
mcset de_de {Modifying index} {Modifying index}

### File: ../src/dialogs/index_dialog.tcl
mcset de_de {Modifying index '%s'} {Modifying index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset de_de {Creating index} {Creating index}

### File: ../src/dialogs/index_dialog.tcl
mcset de_de {Creating index '%s'} {Creating index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset de_de {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?} {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?}

### File: ../src/dialogs/index_dialog.tcl
mcset de_de {Unique values} {Einzigartige Werte}

### File: ../src/dialogs/index_dialog.tcl
mcset de_de {Same values for '%s'} {Gleiche Werte für '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset de_de {You have to select at least one column.} {Sie müssen mindestens ein Feld wählen.}

### File: ../src/dialogs/index_dialog.tcl
mcset de_de {You have to specify index name.} {Sie müssen einen Indexnamen angeben.}

### File: ../src/dialogs/functions_dialog.tcl
mcset de_de Implementation: Implementierung:

### File: ../src/dialogs/functions_dialog.tcl
mcset de_de Name: Name:

### File: ../src/dialogs/functions_dialog.tcl
mcset de_de {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.} {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.}

### File: ../src/dialogs/functions_dialog.tcl
mcset de_de {Cannot use two functions with same name! Change name for '%s'.} {Zwei Funktionen mit gleichem Namen sind nicht möglich! Ändern Sie den Namen für '%s'.}

### File: ../src/dialogs/functions_dialog.tcl
mcset de_de {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! } {'tcl' oder 'sqlfile' sind als Funktionsname unzulässig, diese Namen sind reserviert! }

### File: ../src/dialogs/functions_dialog.tcl
mcset de_de {Function '%s' is not implemented!} {Funktion '%s' ist nicht implementiert!}

### File: ../src/dialogs/functions_dialog.tcl
mcset de_de {Delete function} {Funktion löschen}

### File: ../src/dialogs/functions_dialog.tcl
mcset de_de {Are you sure you want to delete function '%s'?} {Funktion '%s' wirklich löschen?}

### File: ../src/mainwindow.tcl
mcset de_de {Connect to selected database} {Datenbank verbinden}

### File: ../src/mainwindow.tcl
mcset de_de {Disconnect from selected database} {Datenbankverbindung trennen}

### File: ../src/mainwindow.tcl
mcset de_de {Remove selected database from list} {Ausgewählte Datenbank aus Liste entfernen}

### File: ../src/mainwindow.tcl
mcset de_de {New table} {Neue Tabelle}

### File: ../src/mainwindow.tcl
mcset de_de {Drop table} {Lösche Tabelle}

### File: ../src/mainwindow.tcl
mcset de_de {Drop index} {Lösche Index}

### File: ../src/mainwindow.tcl
mcset de_de {Drop trigger} {Lösche Trigger}

### File: ../src/mainwindow.tcl
mcset de_de {Edit view} {Bearbeite View}

### File: ../src/mainwindow.tcl
mcset de_de {Drop view} {Lösche View}

### File: ../src/mainwindow.tcl
mcset de_de {Arrange cascade windows layout} {Fenster überlappend anordnen}

### File: ../src/mainwindow.tcl
mcset de_de {Arrange intelligent windows layout} {Fenster nebeneinander anordnen}

### File: ../src/mainwindow.tcl
mcset de_de {Refresh databases tree (%s)} {Aktualisiere Datenbankbaum (%s)}

### File: ../src/mainwindow.tcl
mcset de_de {Open SQL query editor} {Öffne SQL Abfrage Editor}

### File: ../src/mainwindow.tcl
mcset de_de {Settings (%s)} {Settings (%s)}

### File: ../src/mainwindow.tcl
mcset de_de {Open SQL functions editor} {Öffne SQL Funktionen Editor}

### File: ../src/mainwindow.tcl
mcset de_de {Clear objects filter} {Clear objects filter}

### File: ../src/mainwindow.tcl
mcset de_de {Enter object name you want to look for} {Enter object name you want to look for}

### File: ../src/mainwindow.tcl
mcset de_de Databases Datenbanken

### File: ../src/mainwindow.tcl
mcset de_de Tools Werkzeuge

### File: ../src/mainwindow.tcl
mcset de_de Connect Verbinden

### File: ../src/mainwindow.tcl
mcset de_de Disconnect Trennen

### File: ../src/mainwindow.tcl
mcset de_de {Remove from list} {Entfernen aus der Liste}

### File: ../src/mainwindow.tcl
mcset de_de {View main toolbar} {Symbolleiste Datenbank}

### File: ../src/mainwindow.tcl
mcset de_de {View structure toolbar} {Symbolleiste Struktur}

### File: ../src/mainwindow.tcl
mcset de_de {View windows toolbar} {Symbolleiste Fenster}

### File: ../src/mainwindow.tcl
mcset de_de {View tools toolbar} {Symbolleiste Werkzeuge}

### File: ../src/mainwindow.tcl
mcset de_de {View configuration toolbar} {Symbolleiste Konfiguration}

### File: ../src/mainwindow.tcl
mcset de_de {Refresh databases tree} {Datenbankbaum aktualisieren}

### File: ../src/mainwindow.tcl
mcset de_de {Custom SQL functions} {Benutzerdefinierte SQL Funktionen}

### File: ../src/mainwindow.tcl
mcset de_de {Export database} {Exportiere Datenbank}

### File: ../src/mainwindow.tcl
mcset de_de {Export table or view} {Export table or view}

### File: ../src/mainwindow.tcl
mcset de_de {Import data to a table} {Import data to a table}

### File: ../src/mainwindow.tcl
mcset de_de {SQLiteStudio home page} {SQLiteStudio home page}

### File: ../src/mainwindow.tcl
mcset de_de {SQLiteStudio manual} {SQLiteStudio Handbuch}

### File: ../src/mainwindow.tcl
mcset de_de {SQLite documentation} {SQLite Dokumentation}

### File: ../src/mainwindow.tcl
mcset de_de {SQLiteStudio support forum} {SQLiteStudio Support Forum}

### File: ../src/mainwindow.tcl
mcset de_de {Report a bug} {Einen Fehler melden}

### File: ../src/mainwindow.tcl
mcset de_de {Send feature request} {Featureanfrage senden}

### File: ../src/mainwindow.tcl
mcset de_de {Show bug reports history} {Fehlerprotokoll zeigen}

### File: ../src/mainwindow.tcl
mcset de_de {Show tips window} {Zeige Tipps Fenster}

### File: ../src/mainwindow.tcl
mcset de_de ChangeLog Änderungen

### File: ../src/mainwindow.tcl
mcset de_de Roadmap Aussichten

### File: ../src/mainwindow.tcl
mcset de_de {Check for new version} {Nach neuer Version suchen}

### File: ../src/mainwindow.tcl
mcset de_de Donate Donate

### File: ../src/mainwindow.tcl
mcset de_de {Did you know that...} {Wussten Sie schon, dass...}

### File: ../src/mainwindow.tcl
mcset de_de {Editor %s} {Editor %s}

### File: ../src/mainwindow.tcl
mcset de_de Settings Einstellungen

### File: ../src/mainwindow.tcl
mcset de_de {SQLiteStudio roadmap} {SQLiteStudio Aussichten}

### File: ../src/mainwindow.tcl
mcset de_de {Can't start web browser, because:
%s} {Can't start web browser, because:
%s}

### File: ../src/mainwindow.tcl
mcset de_de {Can't start %s web browser, because:
%s} {Can't start %s web browser, because:
%s}

### File: ../src/mainwindow.tcl
mcset de_de {About SQLiteStudio} {Über SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset de_de {SQLiteStudio ChangeLog} {SQLiteStudio Änderungen}

### File: ../src/mainwindow.tcl
mcset de_de {There is no new version available.} {There is no new version available.}

### File: ../src/mainwindow.tcl
mcset de_de {New version} {Neue Version}

### File: ../src/mainwindow.tcl
mcset de_de {Report bug} {Fehler melden}

### File: ../src/mainwindow.tcl
mcset de_de {Feature request} {Feature request}

### File: ../src/mainwindow.tcl
mcset de_de {Reports history} Fehlerprotokoll

### File: ../src/mainwindow.tcl
mcset de_de {Reporting bug} {Fehler melden}

### File: ../src/mainwindow.tcl
mcset de_de {Reporting bug to SQLiteStudio bugs database...} {Reporting bug to SQLiteStudio bugs database...}

### File: ../src/mainwindow.tcl
mcset de_de {Problem occurred while reporting bug. You can ignore it and get back to your work.} {Problem occurred while reporting bug. You can ignore it and get back to your work.}

### File: ../src/mainwindow.tcl
mcset de_de Ignore Ignorieren

### File: ../src/mainwindow.tcl
mcset de_de {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history} {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history}

### File: ../src/mainwindow.tcl
mcset de_de {A timeout occured while downloading new version. Try again, or download it manually.} {A timeout occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset de_de {An error occured while downloading new version. Try again, or download it manually.} {An error occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset de_de Downloading... Downloading...

### File: ../src/mainwindow.tcl
mcset de_de {Downloading SQLiteStudio v%s...} {Downloading SQLiteStudio v%s...}

### File: ../src/mainwindow.tcl
mcset de_de {Problem with saving new SQLiteStudio version to:
%s
Details:
%s} {Problem with saving new SQLiteStudio version to:
%s
Details:
%s}

### File: ../src/mainwindow.tcl
mcset de_de {Problem with getting new SQLiteStudio version
Details:
%s} {Problem with getting new SQLiteStudio version
Details:
%s}

### File: ../src/mainwindow.tcl
mcset de_de {This is unknown binary distribution. Cannot determinate binary file to download for update.} {This is unknown binary distribution. Cannot determinate binary file to download for update.}

### File: ../src/data_editor.tcl
mcset de_de {There are uncommited rows.
Are you sure you want to close '%s' window anywy?} {There are uncommited rows.
Are you sure you want to close '%s' window anywy?}

### File: ../src/common/ddl_dialog.tcl
mcset de_de {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s} {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s}

### File: ../src/common/color_picker.tcl
mcset de_de {Choose color} {Farbe wählen}

### File: ../src/common/shortcut_edit.tcl
mcset de_de {Forbidden shortcut key combination: %s} {Verbotene Kurzwegtastenkombination: %s}

### File: ../src/common/common.tcl
mcset de_de Copy Kopieren

### File: ../src/common/common.tcl
mcset de_de Cut Cut

### File: ../src/common/common.tcl
mcset de_de Paste Einfügen

### File: ../src/common/blob_edit_panel.tcl
mcset de_de {Text edit} {Text bearbeiten}

### File: ../src/common/blob_edit_panel.tcl
mcset de_de {Hexadecimal edit} {Hexadezimal bearbeiten}

### File: ../src/common/common_sql.tcl
mcset de_de {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
} {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
}

### File: ../src/common/hex_editor.tcl
mcset de_de {Overwrite characters,
instead of inserting} {Overwrite characters,
instead of inserting}

### File: ../src/common/hex_editor.tcl
mcset de_de Processing {In Bearbeitung}

### File: ../src/common/hex_editor.tcl
mcset de_de {Processing data...} {Daten werden bearbeitet...}

### File: ../src/sql_editor.tcl
mcset de_de {Replace dialog} {Dialog Ersetzen}

### File: ../src/sql_editor.tcl
mcset de_de {Search dialog} {Dialog Suchen}

### File: ../src/trees/db_tree.tcl
mcset de_de Loading Loading

### File: ../src/trees/db_tree.tcl
mcset de_de {Loading database list} {Loading database list}

### File: ../src/trees/db_tree.tcl
mcset de_de {Given database file doesn't exist or is unreadable.} {Given database file doesn't exist or is unreadable.}

### File: ../src/trees/db_tree.tcl
mcset de_de Vacuum Vacuum

### File: ../src/trees/db_tree.tcl
mcset de_de {Integrity check} {Intentigrität Prüfen}

### File: ../src/trees/db_tree.tcl
mcset de_de {Import schema from other database} {Schema aus einer anderen Datenbank importieren}

### File: ../src/trees/db_tree.tcl
mcset de_de {Reset autoincrement for '%s'} {Reset autoincrement for '%s'}

### File: ../src/trees/db_tree.tcl
mcset de_de {Erase table data} {Erase table data}

### File: ../src/trees/db_tree.tcl
mcset de_de {Create foreign key} {Erzeuge Fremdschlüssel}

### File: ../src/trees/db_tree.tcl
mcset de_de {Show view data} {Zeige View Daten}

### File: ../src/trees/db_tree.tcl
mcset de_de {Export view} {Export view}

### File: ../src/trees/db_tree.tcl
mcset de_de {Sort databases alphabetically} {Sort databases alphabetically}

### File: ../src/trees/db_tree.tcl
mcset de_de {Given database is already on the list.} {Given database is already on the list.}

### File: ../src/trees/db_tree.tcl
mcset de_de {Given database name is already on the list.} {Given database name is already on the list.}

### File: ../src/trees/db_tree.tcl
mcset de_de Tables Tabellen

### File: ../src/trees/db_tree.tcl
mcset de_de Views Views

### File: ../src/trees/db_tree.tcl
mcset de_de {SQLite system table} {SQLite System Tabelle}

### File: ../src/trees/db_tree.tcl
mcset de_de Columns Columns

### File: ../src/trees/db_tree.tcl
mcset de_de {SQLite system index} {SQLite system index}

### File: ../src/trees/db_tree.tcl
mcset de_de {Remove database} {Entferne Datenbank}

### File: ../src/trees/db_tree.tcl
mcset de_de {Are you sure you want to remove '%s' database from the list?} {Wollen Sie wirklich die Datenbank '%s' aus der Liste löschen?}

### File: ../src/trees/db_tree.tcl
mcset de_de {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.} {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.}

### File: ../src/trees/db_tree.tcl
mcset de_de {'%s' is a virtual table, therefore cannot be browsed in table window.} {'%s' is a virtual table, therefore cannot be browsed in table window.}

### File: ../src/trees/db_tree.tcl
mcset de_de {Table '%s' has no DDL. Probably it's system table and should not be edited.} {Table '%s' has no DDL. Probably it's system table and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset de_de {'%s' is a virtual table, therefore cannot be edited in table dialog.} {'%s' is a virtual table, therefore cannot be edited in table dialog.}

### File: ../src/trees/db_tree.tcl
mcset de_de {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.} {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.}

### File: ../src/trees/db_tree.tcl
mcset de_de {Integrity check (%s)} {Intentigritätsprüfung (%s)}

### File: ../src/trees/db_tree.tcl
mcset de_de {Are you sure you want to DROP '%s' table?} {Wollen Sie wirklich die Tabelle '%s' löschen?}

### File: ../src/trees/db_tree.tcl
mcset de_de {Dropping table} {Dropping table}

### File: ../src/trees/db_tree.tcl
mcset de_de {Dropping table '%s'} {Dropping table '%s'}

### File: ../src/trees/db_tree.tcl
mcset de_de {Dropping index} {Dropping index}

### File: ../src/trees/db_tree.tcl
mcset de_de {Dropping index '%s'} {Dropping index '%s'}

### File: ../src/trees/db_tree.tcl
mcset de_de {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?} {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset de_de {Fix trigger} {Fix trigger}

### File: ../src/trees/db_tree.tcl
mcset de_de {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.} {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset de_de {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?} {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset de_de {Fix view} {Fix view}

### File: ../src/trees/db_tree.tcl
mcset de_de {View '%s' has no DDL. Probably it's system view and should not be edited.} {View '%s' has no DDL. Probably it's system view and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset de_de {Delete view} {Delete view}

### File: ../src/trees/db_tree.tcl
mcset de_de {Are you sure you want to delete '%s' view?} {Wollen Sie wirklich den View '%s' löschen?}

### File: ../src/trees/db_tree.tcl
mcset de_de {Erase data} {Erase data}

### File: ../src/trees/db_tree.tcl
mcset de_de {Are you sure you want to delete all data from table '%s'?} {Are you sure you want to delete all data from table '%s'?}

### File: ../src/trees/db_tree.tcl
mcset de_de {Deleting data} {Deleting data}

### File: ../src/trees/db_tree.tcl
mcset de_de {Deleting data from table '%s'} {Deleting data from table '%s'}

### File: ../src/trees/db_tree.tcl
mcset de_de {'%s' view data} {'%s' view data}

### File: ../src/trees/db_tree.tcl
mcset de_de {Are you sure you want to make a vacuum?} {Wollen Sie wirklich Vacuum ausführen?}

### File: ../src/trees/db_tree.tcl
mcset de_de Vacuuming Vacuuming

### File: ../src/trees/db_tree.tcl
mcset de_de {Vacuuming '%s'} {Vacuuming '%s'}

### File: ../src/trees/db_tree.tcl
mcset de_de {SQL files} {SQL Dateien}

### File: ../src/trees/db_tree.tcl
mcset de_de {Select SQL file to be executed} {SQL Datei zum ausführen auswählen}

### File: ../src/trees/db_tree.tcl
mcset de_de {Error while executing SQL:
%s} {Error while executing SQL:
%s}

### File: ../src/trees/db_tree.tcl
mcset de_de {SQL executed sucessfly.} {SQL erfolgreich ausgeführt.}

### File: ../src/trees/db_tree.tcl
mcset de_de {Import database schema} {Datenbankschema importieren}

### File: ../src/trees/db_tree.tcl
mcset de_de {Database: %s} {Database: %s}

### File: ../src/trees/db_tree.tcl
mcset de_de URI: URI:

### File: ../src/trees/db_tree.tcl
mcset de_de Version: Version:

### File: ../src/trees/db_tree.tcl
mcset de_de {File size:} {File size:}

### File: ../src/trees/db_tree.tcl
mcset de_de {Schema version:} {Schema version:}

### File: ../src/trees/db_tree.tcl
mcset de_de {Virtual table} {Virtual table}

### File: ../src/trees/db_tree.tcl
mcset de_de Indexes: Indexes:

### File: ../src/trees/db_tree.tcl
mcset de_de Triggers: Triggers:

### File: ../src/trees/db_tree.tcl
mcset de_de {Column: %s} {Feld: %s}

### File: ../src/trees/db_tree.tcl
mcset de_de {Not null} {Not null}

### File: ../src/trees/db_tree.tcl
mcset de_de {Indexed table:} {Indexed table:}

### File: ../src/trees/db_tree.tcl
mcset de_de {Copy index '%s' for table '%s'} {Copy index '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset de_de {Move index '%s' to table '%s'} {Move index '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset de_de {Copy trigger '%s' for table '%s'} {Copy trigger '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset de_de {Move trigger '%s' to table '%s'} {Move trigger '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset de_de {Copy view '%s' for database '%s'} {Copy view '%s' for database '%s'}

### File: ../src/trees/db_tree.tcl
mcset de_de {Move view '%s' to database '%s'} {Move view '%s' to database '%s'}

### File: ../src/trees/db_tree.tcl
mcset de_de {View '%s' has no DDL, therefore cannot be edited.} {View '%s' has no DDL, therefore cannot be edited.}

### File: ../src/trees/db_tree.tcl
mcset de_de {Copy view} {Copy view}

### File: ../src/trees/db_tree.tcl
mcset de_de {Move view} {Move view}

### File: ../src/trees/db_tree.tcl
mcset de_de Move Move

### File: ../src/trees/db_tree.tcl
mcset de_de {Copy index} {Copy index}

### File: ../src/trees/db_tree.tcl
mcset de_de {Move index} {Move index}

### File: ../src/trees/db_tree.tcl
mcset de_de {Copy trigger} {Copy trigger}

### File: ../src/trees/db_tree.tcl
mcset de_de {Move trigger} {Move trigger}

### File: ../src/trees/db_tree.tcl
mcset de_de {Copy table '%s' to database '%s' (include data, indexes and triggers)} {Copy table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset de_de {Copy table '%s' to database '%s' (include data)} {Copy table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset de_de {Copy table '%s' to database '%s' (include indexes and triggers)} {Copy table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset de_de {Copy table '%s' to database '%s' (skip data, indexes and triggers)} {Copy table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset de_de {Move table '%s' to database '%s' (include data, indexes and triggers)} {Move table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset de_de {Move table '%s' to database '%s' (include data)} {Move table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset de_de {Move table '%s' to database '%s' (include indexes and triggers)} {Move table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset de_de {Move table '%s' to database '%s' (skip data, indexes and triggers)} {Move table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset de_de {Copying table...} {Copying table...}

### File: ../src/trees/db_tree.tcl
mcset de_de {Copying table '%s' from '%s' to '%s'.} {Copying table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset de_de {Moving table...} {Moving table...}

### File: ../src/trees/db_tree.tcl
mcset de_de {Moving table '%s' from '%s' to '%s'.} {Moving table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset de_de {Could not create object in target database:
%s} {Could not create object in target database:
%s}

### File: ../src/trees/db_tree.tcl
mcset de_de {Could not copy data:
%s} {Could not copy data:
%s}

### File: ../src/trees/db_tree.tcl
mcset de_de {Could not copy table data from source database to target database. Details: %s} {Could not copy table data from source database to target database. Details: %s}

### File: ../src/trees/db_tree.tcl
mcset de_de {Could not delete object(s) from source database. Details: %s} {Could not delete object(s) from source database. Details: %s}

### File: ../src/grids/dbgrid.tcl
mcset de_de {Edit BLOB entry:} {Bearbeite BLOB Eintrag:}

### File: ../src/grids/dbgrid.tcl
mcset de_de {BLOB edit} {BLOB bearbeiten}

### File: ../src/grids/dbgrid.tcl
mcset de_de {Cannot commit. Details:
%s} {Cannot commit. Details:
%s}

### File: ../src/grids/grid.tcl
mcset de_de {You have to select a cell before paste any contents.} {Vorm EInfügen von Inhalt müssen Sie ien Zelle wählen.}

### File: ../src/grids/grid.tcl
mcset de_de {Cut data} {Daten ausschneiden}

### File: ../src/grids/grid.tcl
mcset de_de {There are too many columns or rows to paste. Do you want to cut them and paste?} {Zu viele Felder oder Zeieln zum Einfügen. Wollen Sie diese ausschneiden und einfügen?}

### File: ../src/grids/data_grid.tcl
mcset de_de {Insert new row} {Neue Zeile einfügen}

### File: ../src/grids/data_grid.tcl
mcset de_de {Delete selected rows} {Markierte Zeilen löschen}

### File: ../src/grids/data_grid.tcl
mcset de_de {Edit cell value} {Zelleninhalt bearbeiten}

### File: ../src/grids/data_grid.tcl
mcset de_de {Edit cell value in BLOB editor} {Edit cell value in BLOB editor}

### File: ../src/grids/data_grid.tcl
mcset de_de {Duplicate row} {Zeile duplizieren}

### File: ../src/grids/data_grid.tcl
mcset de_de {Set NULL value} {NULL Wert festlegen}

### File: ../src/grids/data_grid.tcl
mcset de_de {Generate SELECT from selected cells} {Generate SELECT from selected cells}

### File: ../src/grids/data_grid.tcl
mcset de_de {Commit selected cells} {Commit selected cells}

### File: ../src/grids/data_grid.tcl
mcset de_de {Rollback selected cells} {Rollback selected cells}

### File: ../src/grids/data_grid.tcl
mcset de_de {Select all} {Select all}

### File: ../src/grids/data_grid.tcl
mcset de_de {Show ordinals} {Show ordinals}

### File: ../src/grids/data_grid.tcl
mcset de_de {Show ROWIDs} {Zeige ROWIDs}

### File: ../src/grids/data_grid.tcl
mcset de_de Type: Type:

### File: ../src/grids/data_grid.tcl
mcset de_de Constraints: Bedingungen:

### File: ../src/grids/data_grid.tcl
mcset de_de {%s column has NOT NULL constraint. You have to fill value for it.} {Feld %s hat eine NOT NULL Bedingung. Sie müssen eine Wert angeben.}

### File: ../src/grids/data_grid.tcl
mcset de_de {Error while adding new row:
%s} {Fehler beim Hinzufügen einer neuen Zeile:
%s}

### File: ../src/grids/data_grid.tcl
mcset de_de {Error while updating new row:
%s} {Error while updating new row:
%s}

### File: ../src/grids/data_grid.tcl
mcset de_de {Error while updating cell value:
%s

What would you like to do?} {Error while updating cell value:
%s

What would you like to do?}

### File: ../src/grids/data_grid.tcl
mcset de_de {Re-edit value} {Re-edit value}

### File: ../src/grids/data_grid.tcl
mcset de_de {Return to value before edition} {Return to value before edition}

### File: ../src/grids/data_grid.tcl
mcset de_de {Cannot delete row(s), because it violates constraint. Details:
%s} {Cannot delete row(s), because it violates constraint. Details:
%s}

### File: ../src/grids/data_grid.tcl
mcset de_de {Error while deleting selected rows:
%s} {Fehler beim Löschen der markierten Reihen:
%s}

### File: ../src/grids/data_grid.tcl
mcset de_de {SQL query generated at %s
using selected cells from window '%s'.} {SQL query generated at %s
using selected cells from window '%s'.}

### File: ../src/grids/result_grid.tcl
mcset de_de {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.} {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.}

### File: ../src/grids/result_grid.tcl
mcset de_de {Data type:} {Data type:}

### File: ../src/grids/result_grid.tcl
mcset de_de {No details are available on this cell.} {No details are available on this cell.}

### File: ../src/grids/result_grid.tcl
mcset de_de {Duplicated ROWID} {Duplizierter Zeilen ID}

### File: ../src/grids/result_grid.tcl
mcset de_de {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?} {Durch Einfügen sind mehr als eine Zeile mit Zeilen ID=%s vorhanden.
In diesem Fall können unvorhersehbare Ergebnisse entstehen. Fortfahren?}

### File: ../src/grids/result_grid.tcl
mcset de_de {Could not parse SQL while trying to generate requested query: %s} {Could not parse SQL while trying to generate requested query: %s}

### File: ../src/grids/result_grid.tcl
mcset de_de {Cannot use '%s' statement to generate requested query.} {Cannot use '%s' statement to generate requested query.}

### File: ../src/grids/result_grid.tcl
mcset de_de {Cannot determinate selected column with ID=%s.} {Cannot determinate selected column with ID=%s.}

### File: ../src/grids/result_grid.tcl
mcset de_de {Error occurred while trying to generate the query: %s} {Error occurred while trying to generate the query: %s}

### File: ../src/grids/result_grid.tcl
mcset de_de {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s} {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s}
