# SQLiteStudio 'en' localization file

# Unchanged translations

### File: ../src/win_assoc.tcl
mcset en {File associations} {File associations}

### File: ../src/win_assoc.tcl
mcset en {Following file extensions could not be associated to the current SQLiteStudio version:
%s} {Following file extensions could not be associated to the current SQLiteStudio version:
%s}

### File: ../src/win_assoc.tcl
mcset en {Click the link below to find out what is possible reason and solutions.} {Click the link below to find out what is possible reason and solutions.}

### File: ../src/cfg_win.tcl
mcset en Ok Ok

### File: ../src/cfg_win.tcl
mcset en Apply Apply

### File: ../src/cfg_win.tcl
mcset en Cancel Cancel

### File: ../src/cfg_win.tcl
mcset en Theme Theme

### File: ../src/cfg_win.tcl
mcset en {Select theme to use:} {Select theme to use:}

### File: ../src/cfg_win.tcl
mcset en {Theme version:} {Theme version:}

### File: ../src/cfg_win.tcl
mcset en Shortcuts Shortcuts

### File: ../src/cfg_win.tcl
mcset en {Global shortcuts} {Global shortcuts}

### File: ../src/cfg_win.tcl
mcset en {Open SQL editor} {Open SQL editor}

### File: ../src/cfg_win.tcl
mcset en {Opens SQL editor window.} {Opens SQL editor window.}

### File: ../src/cfg_win.tcl
mcset en {Close selected task} {Close selected task}

### File: ../src/cfg_win.tcl
mcset en {Closes active MDI window.} {Closes active MDI window.}

### File: ../src/cfg_win.tcl
mcset en {Restore last closed task} {Restore last closed task}

### File: ../src/cfg_win.tcl
mcset en {Restores last closed MDI window.} {Restores last closed MDI window.}

### File: ../src/cfg_win.tcl
mcset en {Open settings} {Open settings}

### File: ../src/cfg_win.tcl
mcset en {Opens SQLiteStudio settings window.} {Opens SQLiteStudio settings window.}

### File: ../src/cfg_win.tcl
mcset en {Next task} {Next task}

### File: ../src/cfg_win.tcl
mcset en {Switches task (window) to next, placed on the right from active task on taskbar.} {Switches task (window) to next, placed on the right from active task on taskbar.}

### File: ../src/cfg_win.tcl
mcset en {Next task (alternative)} {Next task (alternative)}

### File: ../src/cfg_win.tcl
mcset en {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.}

### File: ../src/cfg_win.tcl
mcset en {Previous task} {Previous task}

### File: ../src/cfg_win.tcl
mcset en {Switches task (window) to previous, placed on the left from active task on taskbar.} {Switches task (window) to previous, placed on the left from active task on taskbar.}

### File: ../src/cfg_win.tcl
mcset en {Previous task (alternative)} {Previous task (alternative)}

### File: ../src/cfg_win.tcl
mcset en {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.}

### File: ../src/cfg_win.tcl
mcset en {Editor and table window shortcuts} {Editor and table window shortcuts}

### File: ../src/cfg_win.tcl
mcset en {SQL editor completion} {SQL editor completion}

### File: ../src/cfg_win.tcl
mcset en {Invokes SQL completion in editor window.} {Invokes SQL completion in editor window.}

### File: ../src/cfg_win.tcl
mcset en {Execute SQL query} {Execute SQL query}

### File: ../src/cfg_win.tcl
mcset en {Executes SQL query typed in editor.} {Executes SQL query typed in editor.}

### File: ../src/cfg_win.tcl
mcset en {Explain SQL query} {Explain SQL query}

### File: ../src/cfg_win.tcl
mcset en {Calls EXPLAIN on SQL query typed in editor.} {Calls EXPLAIN on SQL query typed in editor.}

### File: ../src/cfg_win.tcl
mcset en {Format SQL code} {Format SQL code}

### File: ../src/cfg_win.tcl
mcset en {Formats SQL code typed in editor.} {Formats SQL code typed in editor.}

### File: ../src/cfg_win.tcl
mcset en {Load SQL from file} {Load SQL from file}

### File: ../src/cfg_win.tcl
mcset en {Loads SQL from file to the editor.} {Loads SQL from file to the editor.}

### File: ../src/cfg_win.tcl
mcset en {Save SQL to file} {Save SQL to file}

### File: ../src/cfg_win.tcl
mcset en {Saves contents of the editor into a file.} {Saves contents of the editor into a file.}

### File: ../src/cfg_win.tcl
mcset en {Execute SQL from file} {Execute SQL from file}

### File: ../src/cfg_win.tcl
mcset en {Executes SQL directly from file, without loading it to the editor.} {Executes SQL directly from file, without loading it to the editor.}

### File: ../src/cfg_win.tcl
mcset en {Next tab} {Next tab}

### File: ../src/cfg_win.tcl
mcset en {Switches to next tab of editor window (result or history).} {Switches to next tab of editor window (result or history).}

### File: ../src/cfg_win.tcl
mcset en {Previous tab} {Previous tab}

### File: ../src/cfg_win.tcl
mcset en {Switches to previous tab of editor window (query or result).} {Switches to previous tab of editor window (query or result).}

### File: ../src/cfg_win.tcl
mcset en {Next subtab} {Next subtab}

### File: ../src/cfg_win.tcl
mcset en {Switches to next subtab (form view in results tab).} {Switches to next subtab (form view in results tab).}

### File: ../src/cfg_win.tcl
mcset en {Previous subtab} {Previous subtab}

### File: ../src/cfg_win.tcl
mcset en {Switches to previous subtab (grid view in results tab).} {Switches to previous subtab (grid view in results tab).}

### File: ../src/cfg_win.tcl
mcset en Refresh Refresh

### File: ../src/cfg_win.tcl
mcset en {Re-executes SQL query so results data is refreshed.} {Re-executes SQL query so results data is refreshed.}

### File: ../src/cfg_win.tcl
mcset en {Delete selected row} {Delete selected row}

### File: ../src/cfg_win.tcl
mcset en {Deletes selected row.} {Deletes selected row.}

### File: ../src/cfg_win.tcl
mcset en {Add new row} {Add new row}

### File: ../src/cfg_win.tcl
mcset en {Adds new empty row without commiting it.} {Adds new empty row without commiting it.}

### File: ../src/cfg_win.tcl
mcset en {Erase cells data} {Erase cells data}

### File: ../src/cfg_win.tcl
mcset en {Erases data of selected cells.} {Erases data of selected cells.}

### File: ../src/cfg_win.tcl
mcset en {Next editor database in list} {Next editor database in list}

### File: ../src/cfg_win.tcl
mcset en {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)} {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)}

### File: ../src/cfg_win.tcl
mcset en {Previous editor database in list} {Previous editor database in list}

### File: ../src/cfg_win.tcl
mcset en {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)} {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)}

### File: ../src/cfg_win.tcl
mcset en {Commit edition in Form View} {Commit edition in Form View}

### File: ../src/cfg_win.tcl
mcset en {Commits edition in Form View of query results or table data preview.} {Commits edition in Form View of query results or table data preview.}

### File: ../src/cfg_win.tcl
mcset en {Rollback edition in Form View} {Rollback edition in Form View}

### File: ../src/cfg_win.tcl
mcset en {Rolls back edition in Form View of query results or table data preview.} {Rolls back edition in Form View of query results or table data preview.}

### File: ../src/cfg_win.tcl
mcset en {Jump to first row in Form View} {Jump to first row in Form View}

### File: ../src/cfg_win.tcl
mcset en {Jumps to first row of query results grid
or table data preview grid in Form View.} {Jumps to first row of query results grid
or table data preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset en {Go to previous row in Form View} {Go to previous row in Form View}

### File: ../src/cfg_win.tcl
mcset en {Goes to previous row of query results grid
or table data preview grid row in Form View.} {Goes to previous row of query results grid
or table data preview grid row in Form View.}

### File: ../src/cfg_win.tcl
mcset en {Go to next row in Form View} {Go to next row in Form View}

### File: ../src/cfg_win.tcl
mcset en {Goes to next row of query results grid
or table data preview grid row in Form View.} {Goes to next row of query results grid
or table data preview grid row in Form View.}

### File: ../src/cfg_win.tcl
mcset en {Jump to last row in Form View} {Jump to last row in Form View}

### File: ../src/cfg_win.tcl
mcset en {Jumps to last row of query results grid
or table data preview grid in Form View.} {Jumps to last row of query results grid
or table data preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset en {Switch NULL value in form edit field} {Switch NULL value in form edit field}

### File: ../src/cfg_win.tcl
mcset en {Sets or unsets NULL value in currently selected
column in form view data edit mode.} {Sets or unsets NULL value in currently selected
column in form view data edit mode.}

### File: ../src/cfg_win.tcl
mcset en Plugins Plugins

### File: ../src/cfg_win.tcl
mcset en {SQL formatter plugins} {SQL formatter plugins}

### File: ../src/cfg_win.tcl
mcset en {Use following SQL formatter plugin:} {Use following SQL formatter plugin:}

### File: ../src/cfg_win.tcl
mcset en {Configure formatter plugin} {Configure formatter plugin}

### File: ../src/cfg_win.tcl
mcset en Configure Configure

### File: ../src/cfg_win.tcl
mcset en {Populating plugins} {Populating plugins}

### File: ../src/cfg_win.tcl
mcset en {Default table populating plugin:} {Default table populating plugin:}

### File: ../src/cfg_win.tcl
mcset en Miscellaneous Miscellaneous

### File: ../src/cfg_win.tcl
mcset en {Restore session after next start} {Restore session after next start}

### File: ../src/cfg_win.tcl
mcset en {All windows and their contents (such as SQL code)
will be restored while next application startup.} {All windows and their contents (such as SQL code)
will be restored while next application startup.}

### File: ../src/cfg_win.tcl
mcset en {Show line numbers in SQL editor} {Show line numbers in SQL editor}

### File: ../src/cfg_win.tcl
mcset en {All SQL editor windows will contain line numbers on the left side of window.} {All SQL editor windows will contain line numbers on the left side of window.}

### File: ../src/cfg_win.tcl
mcset en {Underline syntax errors in SQL editor} {Underline syntax errors in SQL editor}

### File: ../src/cfg_win.tcl
mcset en {Makes errors to be marked with underline.
You can also define foreground and background color for errors.} {Makes errors to be marked with underline.
You can also define foreground and background color for errors.}

### File: ../src/cfg_win.tcl
mcset en {Show SQLite system tables and indexes in databases tree} {Show SQLite system tables and indexes in databases tree}

### File: ../src/cfg_win.tcl
mcset en {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.} {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.}

### File: ../src/cfg_win.tcl
mcset en {Open items with single mouse click in databases tree} {Open items with single mouse click in databases tree}

### File: ../src/cfg_win.tcl
mcset en {Items in database tree are open by double click by default.
This option switches it to single click.} {Items in database tree are open by double click by default.
This option switches it to single click.}

### File: ../src/cfg_win.tcl
mcset en {Show ROWID as default instead of row order number in table data view} {Show ROWID as default instead of row order number in table data view}

### File: ../src/cfg_win.tcl
mcset en {This option affects first column from the left on the data tab of the table window.} {This option affects first column from the left on the data tab of the table window.}

### File: ../src/cfg_win.tcl
mcset en {Do not show 'did you know that...' dialog at startup.} {Do not show 'did you know that...' dialog at startup.}

### File: ../src/cfg_win.tcl
mcset en {Uncheck this option to show the dialog.} {Uncheck this option to show the dialog.}

### File: ../src/cfg_win.tcl
mcset en {Check for updates at startup.} {Check for updates at startup.}

### File: ../src/cfg_win.tcl
mcset en {If enabled, application will will check
for new version available at startup.} {If enabled, application will will check
for new version available at startup.}

### File: ../src/cfg_win.tcl
mcset en {Sort custom SQL functions list by name} {Sort custom SQL functions list by name}

### File: ../src/cfg_win.tcl
mcset en {This list is placed in Custom SQL funcions dialog.} {This list is placed in Custom SQL funcions dialog.}

### File: ../src/cfg_win.tcl
mcset en {Select all contents when editing the table cell} {Select all contents when editing the table cell}

### File: ../src/cfg_win.tcl
mcset en {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.} {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.}

### File: ../src/cfg_win.tcl
mcset en {Ask if clipboard contents should be cut} {Ask if clipboard contents should be cut}

### File: ../src/cfg_win.tcl
mcset en {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.} {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.}

### File: ../src/cfg_win.tcl
mcset en {Rows per page in Table Window and Editor Results:} {Rows per page in Table Window and Editor Results:}

### File: ../src/cfg_win.tcl
mcset en {More results per page causes slower loading of single data page. Value 1000 should be right.} {More results per page causes slower loading of single data page. Value 1000 should be right.}

### File: ../src/cfg_win.tcl
mcset en {History entries limit:} {History entries limit:}

### File: ../src/cfg_win.tcl
mcset en {Number of rows to remember in SQL editor history.} {Number of rows to remember in SQL editor history.}

### File: ../src/cfg_win.tcl
mcset en {Insertion cursor blinking period (milliseconds):} {Insertion cursor blinking period (milliseconds):}

### File: ../src/cfg_win.tcl
mcset en {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.} {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.}

### File: ../src/cfg_win.tcl
mcset en {Web browser:} {Web browser:}

### File: ../src/cfg_win.tcl
mcset en {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.} {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.}

### File: ../src/cfg_win.tcl
mcset en Language: Language:

### File: ../src/cfg_win.tcl
mcset en {Tab in table window on open:} {Tab in table window on open:}

### File: ../src/cfg_win.tcl
mcset en {Table structure} {Table structure}

### File: ../src/cfg_win.tcl
mcset en {Table data} {Table data}

### File: ../src/cfg_win.tcl
mcset en {Select which tab should be opened for start in table window,
when you just opened that window.} {Select which tab should be opened for start in table window,
when you just opened that window.}

### File: ../src/cfg_win.tcl
mcset en {View default display mode:} {View default display mode:}

### File: ../src/cfg_win.tcl
mcset en {Edition dialog} {Edition dialog}

### File: ../src/cfg_win.tcl
mcset en {Data view} {Data view}

### File: ../src/cfg_win.tcl
mcset en {Defines what is displayed by default when user opens a view.} {Defines what is displayed by default when user opens a view.}

### File: ../src/cfg_win.tcl
mcset en {Editor window results layout} {Editor window results layout}

### File: ../src/cfg_win.tcl
mcset en {Show results in separated tab} {Show results in separated tab}

### File: ../src/cfg_win.tcl
mcset en {Show results in frame below query} {Show results in frame below query}

### File: ../src/cfg_win.tcl
mcset en {Database tree display mode} {Database tree display mode}

### File: ../src/cfg_win.tcl
mcset en {Show indexes and triggers linked under referenced table.} {Show indexes and triggers linked under referenced table.}

### File: ../src/cfg_win.tcl
mcset en {Show indexes and triggers in their own groups.} {Show indexes and triggers in their own groups.}

### File: ../src/cfg_win.tcl
mcset en {Show column names linked under the table.} {Show column names linked under the table.}

### File: ../src/cfg_win.tcl
mcset en {Plain text results} {Plain text results}

### File: ../src/cfg_win.tcl
mcset en {Display NULL values as:} {Display NULL values as:}

### File: ../src/cfg_win.tcl
mcset en {Maximum column width:} {Maximum column width:}

### File: ../src/cfg_win.tcl
mcset en {Values longer than specified here will be cut in plain text results.} {Values longer than specified here will be cut in plain text results.}

### File: ../src/cfg_win.tcl
mcset en Colors Colors

### File: ../src/cfg_win.tcl
mcset en {Global colors} {Global colors}

### File: ../src/cfg_win.tcl
mcset en {MDI windows title bar background color} {MDI windows title bar background color}

### File: ../src/cfg_win.tcl
mcset en {MDI windows title bar foreground color} {MDI windows title bar foreground color}

### File: ../src/cfg_win.tcl
mcset en {MDI windows title bar button background color} {MDI windows title bar button background color}

### File: ../src/cfg_win.tcl
mcset en {MDI windows title bar active button background color} {MDI windows title bar active button background color}

### File: ../src/cfg_win.tcl
mcset en {SQL Editor} {SQL Editor}

### File: ../src/cfg_win.tcl
mcset en {Editor standard font color} {Editor standard font color}

### File: ../src/cfg_win.tcl
mcset en {Editor background} {Editor background}

### File: ../src/cfg_win.tcl
mcset en {Selected foreground color} {Selected foreground color}

### File: ../src/cfg_win.tcl
mcset en {Selected background color} {Selected background color}

### File: ../src/cfg_win.tcl
mcset en {Disabled background color} {Disabled background color}

### File: ../src/cfg_win.tcl
mcset en {Tables color} {Tables color}

### File: ../src/cfg_win.tcl
mcset en {Brackets color} {Brackets color}

### File: ../src/cfg_win.tcl
mcset en {Square brackets color} {Square brackets color}

### File: ../src/cfg_win.tcl
mcset en {Keywords color} {Keywords color}

### File: ../src/cfg_win.tcl
mcset en {Variables color} {Variables color}

### File: ../src/cfg_win.tcl
mcset en {Strings color} {Strings color}

### File: ../src/cfg_win.tcl
mcset en {Comments color} {Comments color}

### File: ../src/cfg_win.tcl
mcset en {Matched brackets foreground color} {Matched brackets foreground color}

### File: ../src/cfg_win.tcl
mcset en {Matched brackets background color} {Matched brackets background color}

### File: ../src/cfg_win.tcl
mcset en {Syntax error color} {Syntax error color}

### File: ../src/cfg_win.tcl
mcset en {Tcl editor} {Tcl editor}

### File: ../src/cfg_win.tcl
mcset en {Options color} {Options color}

### File: ../src/cfg_win.tcl
mcset en {Quoted character color} {Quoted character color}

### File: ../src/cfg_win.tcl
mcset en {Trees colors} {Trees colors}

### File: ../src/cfg_win.tcl
mcset en {Tree background} {Tree background}

### File: ../src/cfg_win.tcl
mcset en {Tree standard font color} {Tree standard font color}

### File: ../src/cfg_win.tcl
mcset en {Tree selected background color} {Tree selected background color}

### File: ../src/cfg_win.tcl
mcset en {Tree selected foreground color} {Tree selected foreground color}

### File: ../src/cfg_win.tcl
mcset en {Color for number of objects in tree branch} {Color for number of objects in tree branch}

### File: ../src/cfg_win.tcl
mcset en {Grids colors} {Grids colors}

### File: ../src/cfg_win.tcl
mcset en {Grid background} {Grid background}

### File: ../src/cfg_win.tcl
mcset en {Grid standard font color} {Grid standard font color}

### File: ../src/cfg_win.tcl
mcset en {Grid selected background color} {Grid selected background color}

### File: ../src/cfg_win.tcl
mcset en {Grid selected foreground color} {Grid selected foreground color}

### File: ../src/cfg_win.tcl
mcset en {Grid base column background color} {Grid base column background color}

### File: ../src/cfg_win.tcl
mcset en {Foreground color for cells with NULL value} {Foreground color for cells with NULL value}

### File: ../src/cfg_win.tcl
mcset en {Status fields colors} {Status fields colors}

### File: ../src/cfg_win.tcl
mcset en {Background color} {Background color}

### File: ../src/cfg_win.tcl
mcset en {Foreground color} {Foreground color}

### File: ../src/cfg_win.tcl
mcset en {Error foreground color} {Error foreground color}

### File: ../src/cfg_win.tcl
mcset en {Information foreground color} {Information foreground color}

### File: ../src/cfg_win.tcl
mcset en {Information (second kind) foreground color} {Information (second kind) foreground color}

### File: ../src/cfg_win.tcl
mcset en {Miscellaneous colors} {Miscellaneous colors}

### File: ../src/cfg_win.tcl
mcset en {Context hints background color} {Context hints background color}

### File: ../src/cfg_win.tcl
mcset en {Context hints foreground color} {Context hints foreground color}

### File: ../src/cfg_win.tcl
mcset en Fonts Fonts

### File: ../src/cfg_win.tcl
mcset en {SQL editor font} {SQL editor font}

### File: ../src/cfg_win.tcl
mcset en {Status fields font} {Status fields font}

### File: ../src/cfg_win.tcl
mcset en {Grid font} {Grid font}

### File: ../src/cfg_win.tcl
mcset en {Tree font} {Tree font}

### File: ../src/cfg_win.tcl
mcset en {Tree additional labels font} {Tree additional labels font}

### File: ../src/cfg_win.tcl
mcset en {Context hints font} {Context hints font}

### File: ../src/cfg_win.tcl
mcset en {Changed language needs application to be restarted.} {Changed language needs application to be restarted.}

### File: ../src/cfg_win.tcl
mcset en {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.} {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.}

### File: ../src/cfg_win.tcl
mcset en {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.} {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.}

### File: ../src/cfg_win.tcl
mcset en {SQL formatter options} {SQL formatter options}

### File: ../src/db/db_file_types.tcl
mcset en {All SQLite Databases} {All SQLite Databases}

### File: ../src/db/db_file_types.tcl
mcset en {SQLite 3 Databases} {SQLite 3 Databases}

### File: ../src/db/db_file_types.tcl
mcset en {SQLite 2 Databases} {SQLite 2 Databases}

### File: ../src/db/db_file_types.tcl
mcset en {All files} {All files}

### File: ../src/db/query_executor.tcl
mcset en {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.} {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.}

### File: ../src/db/query_executor.tcl
mcset en {Invalid database name: %s} {Invalid database name: %s}

### File: ../src/db/query_executor.tcl
mcset en {Imbalanced 'BEGIN' ocurrence in query.} {Imbalanced 'BEGIN' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset en {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.} {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset en {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.} {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset en {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.} {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset en {Cannot use more than one 'BEGIN'.} {Cannot use more than one 'BEGIN'.}

### File: ../src/db/query_executor.tcl
mcset en {Imbalanced 'COMMIT' ocurrence in query.} {Imbalanced 'COMMIT' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset en {Imbalanced 'ROLLBACK' ocurrence in query.} {Imbalanced 'ROLLBACK' ocurrence in query.}

### File: ../src/db/sqlite2.tcl
mcset en {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)} {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)}

### File: ../src/db/db.tcl
mcset en {An internal logic error in SQLite} {An internal logic error in SQLite}

### File: ../src/db/db.tcl
mcset en {Access permission denied} {Access permission denied}

### File: ../src/db/db.tcl
mcset en {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.} {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.}

### File: ../src/db/db.tcl
mcset en {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.} {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.}

### File: ../src/db/db.tcl
mcset en {A malloc() failed} {A malloc() failed}

### File: ../src/db/db.tcl
mcset en {Attempt to write a readonly database} {Attempt to write a readonly database}

### File: ../src/db/db.tcl
mcset en {Disk I/O error occurred} {Disk I/O error occurred}

### File: ../src/db/db.tcl
mcset en {The database disk image is malformed} {The database disk image is malformed}

### File: ../src/db/db.tcl
mcset en {Database is full} {Database is full}

### File: ../src/db/db.tcl
mcset en {Unable to open the database file} {Unable to open the database file}

### File: ../src/db/db.tcl
mcset en {Database lock protocol error} {Database lock protocol error}

### File: ../src/db/db.tcl
mcset en {Database is empty} {Database is empty}

### File: ../src/db/db.tcl
mcset en {The database schema changed} {The database schema changed}

### File: ../src/db/db.tcl
mcset en {String or BLOB exceeds size limit} {String or BLOB exceeds size limit}

### File: ../src/db/db.tcl
mcset en {Library used incorrectly} {Library used incorrectly}

### File: ../src/db/db.tcl
mcset en {Uses OS features not supported on host} {Uses OS features not supported on host}

### File: ../src/db/db.tcl
mcset en {Authorization denied} {Authorization denied}

### File: ../src/db/db.tcl
mcset en {Auxiliary database format error} {Auxiliary database format error}

### File: ../src/db/db.tcl
mcset en {2nd parameter to sqlite3_bind out of range} {2nd parameter to sqlite3_bind out of range}

### File: ../src/db/db.tcl
mcset en {File opened that is not a database file} {File opened that is not a database file}

### File: ../src/db/db.tcl
mcset en {Error while opening %s database:
%s} {Error while opening %s database:
%s}

### File: ../src/db/db.tcl
mcset en {Not enough parameters passed to function '%s'.} {Not enough parameters passed to function '%s'.}

### File: ../src/db/db.tcl
mcset en {Cannot read file: %s} {Cannot read file: %s}

### File: ../src/db/db.tcl
mcset en {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.} {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.}

### File: ../src/db/db.tcl
mcset en {Could not attach database %s. Error message from SQLite:
%s} {Could not attach database %s. Error message from SQLite:
%s}

### File: ../src/db/db.tcl
mcset en {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.} {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.}

### File: ../src/db/sqlite3.tcl
mcset en {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)} {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)}

### File: ../src/completion_routines.tcl
mcset en {Problem with attaching database:
%s} {Problem with attaching database:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset en {Error from importing plugin:
%s} {Error from importing plugin:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset en {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset en {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset en {Error creating table '%s':
%s

Importing aborted.} {Error creating table '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset en {Error trying to import data to '%s':
%s

Importing aborted.} {Error trying to import data to '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset en Importing... Importing...

### File: ../src/plugins/import_plugin.tcl
mcset en {Importing to table '%s'.} {Importing to table '%s'.}

### File: ../src/plugins/import_plugin.tcl
mcset en {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?} {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset en {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?} {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset en {Problem occured while importing row number %s:
%s

What would you like to do?} {Problem occured while importing row number %s:
%s

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset en {Importing finished.} {Importing finished.}

### File: ../src/plugins/import_plugin.tcl
mcset en {Import problem} {Import problem}

### File: ../src/plugins/import_plugin.tcl
mcset en {Skip this data row} {Skip this data row}

### File: ../src/plugins/import_plugin.tcl
mcset en {Keep data rows imported so far (%s) and abort} {Keep data rows imported so far (%s) and abort}

### File: ../src/plugins/import_plugin.tcl
mcset en {Rollback data rows imported so far and abort} {Rollback data rows imported so far and abort}

### File: ../src/plugins/import_plugin.tcl
mcset en {Ignore it and proceed} {Ignore it and proceed}

### File: ../src/plugins/import_plugin.tcl
mcset en Abort Abort

### File: ../src/plugins/sql_formatting/enterprise/format_s.tcl
mcset en name name

### File: ../src/plugins/sql_formatting/basic.tcl
mcset en {Reduce group of whitespaces into one whitespace.} {Reduce group of whitespaces into one whitespace.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset en {Uppercase keywords.} {Uppercase keywords.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset en {Separate ")" and after contents with single whitespace.} {Separate ")" and after contents with single whitespace.}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {SQLite3 only} {SQLite3 only}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en Indentation Indentation

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {New lines} {New lines}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {White spaces} {White spaces}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en Names Names

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en Comments Comments

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Tab size:} {Tab size:}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Line up keywords in multi-line queries} {Line up keywords in multi-line queries}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Ident contents of parenthesis block} {Ident contents of parenthesis block}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Ident parenthesis block in new line} {Ident parenthesis block in new line}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Before opening parenthesis in column definitions} {Before opening parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After opening parenthesis in column definitions} {After opening parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Before closinging parenthesis in column definitions} {Before closinging parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After closinging parenthesis in column definitions} {After closinging parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Before opening parenthesis in expressions} {Before opening parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After opening parenthesis in expressions} {After opening parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Before closinging parenthesis in expressions} {Before closinging parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After closinging parenthesis in expressions} {After closinging parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After comma} {After comma}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After comma in function arguments list} {After comma in function arguments list}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After logical block of query} {After logical block of query}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After semicolon} {After semicolon}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Never before semicolon} {Never before semicolon}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Before comma in lists} {Before comma in lists}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After comma in lists} {After comma in lists}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Before opening parenthesis} {Before opening parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After opening parenthesis} {After opening parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Before closing parenthesis} {Before closing parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After closing parenthesis} {After closing parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Before dot operator (in path to database object)} {Before dot operator (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After dot operator (in path to database object)} {After dot operator (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Before mathematical operator} {Before mathematical operator}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {After mathematical operator} {After mathematical operator}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Uppercase keywords} {Uppercase keywords}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Uppercase datatype names} {Uppercase datatype names}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Always use name wrapping} {Always use name wrapping}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Preferred name wrapper} {Preferred name wrapper}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Expand one line comments (/* ... */) to multiline} {Expand one line comments (/* ... */) to multiline}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Indent multi line comments} {Indent multi line comments}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset en {Use "*" character for each line} {Use "*" character for each line}

### File: ../src/plugins/import/csv.tcl
mcset en {, (comma)} {, (comma)}

### File: ../src/plugins/import/csv.tcl
mcset en {; (semicolon)} {; (semicolon)}

### File: ../src/plugins/import/csv.tcl
mcset en {\t (tab)} {\t (tab)}

### File: ../src/plugins/import/csv.tcl
mcset en {  (white-space)} {  (white-space)}

### File: ../src/plugins/import/csv.tcl
mcset en Custom Custom

### File: ../src/plugins/import/csv.tcl
mcset en {Input file} {Input file}

### File: ../src/plugins/import/csv.tcl
mcset en Browse Browse

### File: ../src/plugins/import/csv.tcl
mcset en {Show options} {Show options}

### File: ../src/plugins/import/csv.tcl
mcset en {Column names} {Column names}

### File: ../src/plugins/import/csv.tcl
mcset en {Treat first row as column names} {Treat first row as column names}

### File: ../src/plugins/import/csv.tcl
mcset en {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.} {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.}

### File: ../src/plugins/import/csv.tcl
mcset en {Columns separator:} {Columns separator:}

### File: ../src/plugins/import/csv.tcl
mcset en {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.} {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.}

### File: ../src/plugins/import/csv.tcl
mcset en {NULL handling} {NULL handling}

### File: ../src/plugins/import/csv.tcl
mcset en {Treat following values as NULL:} {Treat following values as NULL:}

### File: ../src/plugins/import/csv.tcl
mcset en Workarounds Workarounds

### File: ../src/plugins/import/csv.tcl
mcset en {Expect Microsoft format of CSV} {Expect Microsoft format of CSV}

### File: ../src/plugins/import/csv.tcl
mcset en {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.} {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.}

### File: ../src/plugins/import/csv.tcl
mcset en Encoding Encoding

### File: ../src/plugins/import/csv.tcl
mcset en {Convert from encoding:} {Convert from encoding:}

### File: ../src/plugins/import/csv.tcl
mcset en {Input file cannot be empty.} {Input file cannot be empty.}

### File: ../src/plugins/import/csv.tcl
mcset en {Input file is not readable.} {Input file is not readable.}

### File: ../src/plugins/import/csv.tcl
mcset en {CSV separator cannot be empty.} {CSV separator cannot be empty.}

### File: ../src/plugins/import/csv.tcl
mcset en {CSV files} {CSV files}

### File: ../src/plugins/import/csv.tcl
mcset en {Text files} {Text files}

### File: ../src/plugins/import/csv.tcl
mcset en {File to import from} {File to import from}

### File: ../src/plugins/import/dbf.tcl
mcset en Auto-detect Auto-detect

### File: ../src/plugins/import/dbf.tcl
mcset en {dBase files} {dBase files}

### File: ../src/plugins/import/regexp.tcl
mcset en {Regular expression} {Regular expression}

### File: ../src/plugins/import/regexp.tcl
mcset en {Visual editor} {Visual editor}

### File: ../src/plugins/import/regexp.tcl
mcset en {Use Regular Expression Groups to identify columns.} {Use Regular Expression Groups to identify columns.}

### File: ../src/plugins/import/regexp.tcl
mcset en {Case insensitive} {Case insensitive}

### File: ../src/plugins/import/regexp.tcl
mcset en Help Help

### File: ../src/plugins/import/regexp.tcl
mcset en {RegExp error:
%s} {RegExp error:
%s}

### File: ../src/plugins/export/xls.tcl
mcset en {Column names as first row} {Column names as first row}

### File: ../src/plugins/export/xls.tcl
mcset en {If enabled, then first row of exported document will be a list of column names.} {If enabled, then first row of exported document will be a list of column names.}

### File: ../src/plugins/export/xls.tcl
mcset en Encoding: Encoding:

### File: ../src/plugins/export/plain.tcl
mcset en {Export NULL values as:} {Export NULL values as:}

### File: ../src/plugins/export/plain.tcl
mcset en {Fixed column width:} {Fixed column width:}

### File: ../src/plugins/export/plain.tcl
mcset en {Database: %s (%s, %s)} {Database: %s (%s, %s)}

### File: ../src/plugins/export/plain.tcl
mcset en {Table: %s} {Table: %s}

### File: ../src/plugins/export/plain.tcl
mcset en {Index: %s} {Index: %s}

### File: ../src/plugins/export/plain.tcl
mcset en {Trigger: %s} {Trigger: %s}

### File: ../src/plugins/export/plain.tcl
mcset en {View: %s} {View: %s}

### File: ../src/plugins/export/csv.tcl
mcset en {If enabled, then first row of exported CSV will be a list of column names.} {If enabled, then first row of exported CSV will be a list of column names.}

### File: ../src/plugins/export/csv.tcl
mcset en {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.} {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.}

### File: ../src/plugins/export/json.tcl
mcset en {Indented lines} {Indented lines}

### File: ../src/plugins/export/json.tcl
mcset en {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.} {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.}

### File: ../src/plugins/export/json.tcl
mcset en {Align lines} {Align lines}

### File: ../src/plugins/export/json.tcl
mcset en {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.} {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.}

### File: ../src/plugins/export/json.tcl
mcset en {Each row as object} {Each row as object}

### File: ../src/plugins/export/json.tcl
mcset en {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.} {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.}

### File: ../src/plugins/export/xml.tcl
mcset en {No extra white-spaces or new lines} {No extra white-spaces or new lines}

### File: ../src/plugins/export/xml.tcl
mcset en {XML tags will be places char-by-char, without any extra white-spaces.} {XML tags will be places char-by-char, without any extra white-spaces.}

### File: ../src/plugins/export/xml.tcl
mcset en {Format output to be human readable} {Format output to be human readable}

### File: ../src/plugins/export/xml.tcl
mcset en {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.} {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.}

### File: ../src/plugins/export/xml.tcl
mcset en {Generate XSD file} {Generate XSD file}

### File: ../src/plugins/export/xml.tcl
mcset en {Generates XML Schema Definition file using
export file name and extension *.xsd.} {Generates XML Schema Definition file using
export file name and extension *.xsd.}

### File: ../src/plugins/export/xml.tcl
mcset en {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s} {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s}

### File: ../src/plugins/export/html.tcl
mcset en {First row of exported data will be header
with names of columns, just like in results grid.} {First row of exported data will be header
with names of columns, just like in results grid.}

### File: ../src/plugins/export/html.tcl
mcset en {Row numbers as first column} {Row numbers as first column}

### File: ../src/plugins/export/html.tcl
mcset en {First column of exported data
will contain row order number.} {First column of exported data
will contain row order number.}

### File: ../src/plugins/export/html.tcl
mcset en {Full column names} {Full column names}

### File: ../src/plugins/export/html.tcl
mcset en {Column names in header will be prepended with "table_name." prefix.} {Column names in header will be prepended with "table_name." prefix.}

### File: ../src/plugins/export/html.tcl
mcset en {Show types} {Show types}

### File: ../src/plugins/export/html.tcl
mcset en {Column headers will contain data types.} {Column headers will contain data types.}

### File: ../src/plugins/export/html.tcl
mcset en {no type} {no type}

### File: ../src/plugins/export/html.tcl
mcset en {For table:} {For table:}

### File: ../src/plugins/export/html.tcl
mcset en Unique: Unique:

### File: ../src/plugins/export/html.tcl
mcset en Yes Yes

### File: ../src/plugins/export/html.tcl
mcset en No No

### File: ../src/plugins/export/html.tcl
mcset en Column Column

### File: ../src/plugins/export/html.tcl
mcset en Collating Collating

### File: ../src/plugins/export/html.tcl
mcset en {Sort order} {Sort order}

### File: ../src/plugins/export/html.tcl
mcset en Activated: Activated:

### File: ../src/plugins/export/html.tcl
mcset en Action: Action:

### File: ../src/plugins/export/html.tcl
mcset en {Activate condition:} {Activate condition:}

### File: ../src/plugins/export/html.tcl
mcset en {Code executed:} {Code executed:}

### File: ../src/plugins/export/html.tcl
mcset en {Exported database: %s} {Exported database: %s}

### File: ../src/plugins/export/html.tcl
mcset en {Generated on %s with %s} {Generated on %s with %s}

### File: ../src/plugins/export/html.tcl
mcset en {Exported table: %s} {Exported table: %s}

### File: ../src/plugins/export/html.tcl
mcset en {Results of SQL query} {Results of SQL query}

### File: ../src/plugins/export/dbf.tcl
mcset en {Cannot overwrite file '%s'.} {Cannot overwrite file '%s'.}

### File: ../src/plugins/export/sql.tcl
mcset en {Name of table for exported data:} {Name of table for exported data:}

### File: ../src/plugins/export/sql.tcl
mcset en {Include "CREATE TABLE" statement at the begining.} {Include "CREATE TABLE" statement at the begining.}

### File: ../src/plugins/export/sql.tcl
mcset en {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.} {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.}

### File: ../src/plugins/export/sql.tcl
mcset en {Include table declaration} {Include table declaration}

### File: ../src/plugins/export/sql.tcl
mcset en {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.} {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.}

### File: ../src/plugins/export/sql.tcl
mcset en {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.} {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.}

### File: ../src/plugins/export/pdf.tcl
mcset en Dimensions Dimensions

### File: ../src/plugins/export/pdf.tcl
mcset en {Paper size:} {Paper size:}

### File: ../src/plugins/export/pdf.tcl
mcset en {Margin size:} {Margin size:}

### File: ../src/plugins/export/pdf.tcl
mcset en {Cell padding:} {Cell padding:}

### File: ../src/plugins/export/pdf.tcl
mcset en {Limit amount of data bytes in single cell to:} {Limit amount of data bytes in single cell to:}

### File: ../src/plugins/export/pdf.tcl
mcset en {Font size:} {Font size:}

### File: ../src/plugins/export/pdf.tcl
mcset en {Built-in font} {Built-in font}

### File: ../src/plugins/export/pdf.tcl
mcset en Font: Font:

### File: ../src/plugins/export/pdf.tcl
mcset en {TrueType font} {TrueType font}

### File: ../src/plugins/export/pdf.tcl
mcset en {Font file:} {Font file:}

### File: ../src/plugins/export/pdf.tcl
mcset en {Font encoding:} {Font encoding:}

### File: ../src/plugins/export/pdf.tcl
mcset en {Columns and rows} {Columns and rows}

### File: ../src/plugins/export/pdf.tcl
mcset en {Header background} {Header background}

### File: ../src/plugins/export/pdf.tcl
mcset en {Empty space} {Empty space}

### File: ../src/plugins/export/pdf.tcl
mcset en {Fill empty space in cells} {Fill empty space in cells}

### File: ../src/plugins/export/pdf.tcl
mcset en {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.} {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.}

### File: ../src/plugins/export/pdf.tcl
mcset en {Minimum height of empty space to fill:} {Minimum height of empty space to fill:}

### File: ../src/plugins/export/pdf.tcl
mcset en {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.} {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.}

### File: ../src/plugins/export/pdf.tcl
mcset en {Empty space background} {Empty space background}

### File: ../src/plugins/export/pdf.tcl
mcset en {TTF Fonts} {TTF Fonts}

### File: ../src/plugins/export/pdf.tcl
mcset en {All Files} {All Files}

### File: ../src/plugins/export/pdf.tcl
mcset en {Open TTF font} {Open TTF font}

### File: ../src/plugins/populating/random.tcl
mcset en {Include alpha characters} {Include alpha characters}

### File: ../src/plugins/populating/random.tcl
mcset en {Include numeric characters} {Include numeric characters}

### File: ../src/plugins/populating/random.tcl
mcset en {Include whitespace characters} {Include whitespace characters}

### File: ../src/plugins/populating/random.tcl
mcset en {Include binary characters} {Include binary characters}

### File: ../src/plugins/populating/random.tcl
mcset en {Minimum length:} {Minimum length:}

### File: ../src/plugins/populating/random.tcl
mcset en {Maximum length:} {Maximum length:}

### File: ../src/plugins/populating/random_number.tcl
mcset en {Minimum value:} {Minimum value:}

### File: ../src/plugins/populating/random_number.tcl
mcset en {Maximum value:} {Maximum value:}

### File: ../src/plugins/populating/random_number.tcl
mcset en {Constant prefix:} {Constant prefix:}

### File: ../src/plugins/populating/random_number.tcl
mcset en {Constant suffix:} {Constant suffix:}

### File: ../src/plugins/populating/sql.tcl
mcset en {Initialisation code} {Initialisation code}

### File: ../src/plugins/populating/sql.tcl
mcset en {Per iteration code} {Per iteration code}

### File: ../src/plugins/populating/sql.tcl
mcset en {Closing code} {Closing code}

### File: ../src/plugins/populating/constant.tcl
mcset en {Value to use:} {Value to use:}

### File: ../src/plugins/populating/sequence.tcl
mcset en {Start from:} {Start from:}

### File: ../src/plugins/populating/dictionary.tcl
mcset en {Dictionary file:} {Dictionary file:}

### File: ../src/plugins/populating/dictionary.tcl
mcset en {Dictionary words separator:} {Dictionary words separator:}

### File: ../src/plugins/populating/dictionary.tcl
mcset en Whitespace Whitespace

### File: ../src/plugins/populating/dictionary.tcl
mcset en {Line break} {Line break}

### File: ../src/plugins/populating/dictionary.tcl
mcset en {Method of using words:} {Method of using words:}

### File: ../src/plugins/populating/dictionary.tcl
mcset en Randomly Randomly

### File: ../src/plugins/populating/dictionary.tcl
mcset en Consecutively Consecutively

### File: ../src/plugins/populating/dictionary.tcl
mcset en {Dictionary file doesn't exist, or unreadable.} {Dictionary file doesn't exist, or unreadable.}

### File: ../src/plugins/populating/dictionary.tcl
mcset en {Dictionary file is empty!} {Dictionary file is empty!}

### File: ../src/plugins/populating/dictionary.tcl
mcset en {Dictionary file} {Dictionary file}

### File: ../src/taskbar.tcl
mcset en Database: Database:

### File: ../src/taskbar.tcl
mcset en Table: Table:

### File: ../src/taskbar.tcl
mcset en {Type new name for a window} {Type new name for a window}

### File: ../src/taskbar.tcl
mcset en {Window with given name already exists. Please type other name.} {Window with given name already exists. Please type other name.}

### File: ../src/taskbar.tcl
mcset en {Type new name for a task} {Type new name for a task}

### File: ../src/taskbar.tcl
mcset en {Close selected window} {Close selected window}

### File: ../src/taskbar.tcl
mcset en {Close other windows} {Close other windows}

### File: ../src/taskbar.tcl
mcset en {Close all windows} {Close all windows}

### File: ../src/taskbar.tcl
mcset en {Restore last closed window} {Restore last closed window}

### File: ../src/taskbar.tcl
mcset en {Rename selected window} {Rename selected window}

### File: ../src/windows/table_win.tcl
mcset en Structure Structure

### File: ../src/windows/table_win.tcl
mcset en Data Data

### File: ../src/windows/table_win.tcl
mcset en Constraints Constraints

### File: ../src/windows/table_win.tcl
mcset en Indexes Indexes

### File: ../src/windows/table_win.tcl
mcset en Triggers Triggers

### File: ../src/windows/table_win.tcl
mcset en {Grid view} {Grid view}

### File: ../src/windows/table_win.tcl
mcset en {Form view} {Form view}

### File: ../src/windows/table_win.tcl
mcset en {Refresh table columns and DDL (%s)} {Refresh table columns and DDL (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Edit table (%s)} {Edit table (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Export table data (%s)} {Export table data (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Import data to table (%s)} {Import data to table (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Populate table (%s)} {Populate table (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Create similar table} {Create similar table}

### File: ../src/windows/table_win.tcl
mcset en {Refresh table data (%s)} {Refresh table data (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Add custom number of rows} {Add custom number of rows}

### File: ../src/windows/table_win.tcl
mcset en {Add new row (%s)} {Add new row (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Delete selected row (%s)} {Delete selected row (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Commit changes (%s)} {Commit changes (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Rollback new row (%s)} {Rollback new row (%s)}

### File: ../src/windows/table_win.tcl
mcset en {First %s rows} {First %s rows}

### File: ../src/windows/table_win.tcl
mcset en {Previous %s rows} {Previous %s rows}

### File: ../src/windows/table_win.tcl
mcset en {Next %s rows} {Next %s rows}

### File: ../src/windows/table_win.tcl
mcset en {Last %s rows} {Last %s rows}

### File: ../src/windows/table_win.tcl
mcset en {Export table data} {Export table data}

### File: ../src/windows/table_win.tcl
mcset en {Import data to table} {Import data to table}

### File: ../src/windows/table_win.tcl
mcset en {Populate table} {Populate table}

### File: ../src/windows/table_win.tcl
mcset en {Enter phrase you want to look for} {Enter phrase you want to look for}

### File: ../src/windows/table_win.tcl
mcset en {Apply data filter} {Apply data filter}

### File: ../src/windows/table_win.tcl
mcset en {Clear data filter} {Clear data filter}

### File: ../src/windows/table_win.tcl
mcset en {Total rows: %s} {Total rows: %s}

### File: ../src/windows/table_win.tcl
mcset en {Rollback changes (%s)} {Rollback changes (%s)}

### File: ../src/windows/table_win.tcl
mcset en {First row from data grid (%s)} {First row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Previous row from data grid (%s)} {Previous row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Next row from data grid (%s)} {Next row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Last row from data grid (%s)} {Last row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Field switching mode.

Click it to make <Tab> key to insert tab characters.} {Field switching mode.

Click it to make <Tab> key to insert tab characters.}

### File: ../src/windows/table_win.tcl
mcset en {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.} {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.}

### File: ../src/windows/table_win.tcl
mcset en {Refresh table indexes (%s)} {Refresh table indexes (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Create new index (%s)} {Create new index (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Edit index (%s)} {Edit index (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Delete index (%s)} {Delete index (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Refresh table triggers (%s)} {Refresh table triggers (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Create new trigger (%s)} {Create new trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Edit trigger (%s)} {Edit trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Delete trigger (%s)} {Delete trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset en {Constraint name} {Constraint name}

### File: ../src/windows/table_win.tcl
mcset en {Column name} {Column name}

### File: ../src/windows/table_win.tcl
mcset en Default Default

### File: ../src/windows/table_win.tcl
mcset en {Not NULL} {Not NULL}

### File: ../src/windows/table_win.tcl
mcset en {Primary key} {Primary key}

### File: ../src/windows/table_win.tcl
mcset en Unique Unique

### File: ../src/windows/table_win.tcl
mcset en Collate Collate

### File: ../src/windows/table_win.tcl
mcset en Check Check

### File: ../src/windows/table_win.tcl
mcset en {Foreign key} {Foreign key}

### File: ../src/windows/table_win.tcl
mcset en {Index name} {Index name}

### File: ../src/windows/table_win.tcl
mcset en {On column} {On column}

### File: ../src/windows/table_win.tcl
mcset en {SQL code} {SQL code}

### File: ../src/windows/table_win.tcl
mcset en {Trigger name} {Trigger name}

### File: ../src/windows/table_win.tcl
mcset en {On table} {On table}

### File: ../src/windows/table_win.tcl
mcset en Name Name

### File: ../src/windows/table_win.tcl
mcset en {Data type} {Data type}

### File: ../src/windows/table_win.tcl
mcset en {Default value} {Default value}

### File: ../src/windows/table_win.tcl
mcset en {Refreshing dependencies} {Refreshing dependencies}

### File: ../src/windows/table_win.tcl
mcset en {Refreshing table columns...} {Refreshing table columns...}

### File: ../src/windows/table_win.tcl
mcset en {Refreshing table data...} {Refreshing table data...}

### File: ../src/windows/table_win.tcl
mcset en {Refreshing table indexes...} {Refreshing table indexes...}

### File: ../src/windows/table_win.tcl
mcset en {Refreshing table triggers...} {Refreshing table triggers...}

### File: ../src/windows/table_win.tcl
mcset en {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.} {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.}

### File: ../src/windows/table_win.tcl
mcset en {Check condition} {Check condition}

### File: ../src/windows/table_win.tcl
mcset en {Total rows: %s (filtered)} {Total rows: %s (filtered)}

### File: ../src/windows/table_win.tcl
mcset en {Pending commits} {Pending commits}

### File: ../src/windows/table_win.tcl
mcset en {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?} {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?}

### File: ../src/windows/table_win.tcl
mcset en {Loading data...} {Loading data...}

### File: ../src/windows/table_win.tcl
mcset en {Loading table '%s'...} {Loading table '%s'...}

### File: ../src/windows/table_win.tcl
mcset en {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.} {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.}

### File: ../src/windows/table_win.tcl
mcset en {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.} {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.}

### File: ../src/windows/table_win.tcl
mcset en {Edit table} {Edit table}

### File: ../src/windows/table_win.tcl
mcset en {Enter number of rows to add:} {Enter number of rows to add:}

### File: ../src/windows/table_win.tcl
mcset en {Add rows} {Add rows}

### File: ../src/windows/table_win.tcl
mcset en {New index} {New index}

### File: ../src/windows/table_win.tcl
mcset en {Index '%s' has no DDL. Probably it's system index and should not be edited.} {Index '%s' has no DDL. Probably it's system index and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset en {Edit index} {Edit index}

### File: ../src/windows/table_win.tcl
mcset en {Delete index} {Delete index}

### File: ../src/windows/table_win.tcl
mcset en {Are you sure you want to delete '%s' index?} {Are you sure you want to delete '%s' index?}

### File: ../src/windows/table_win.tcl
mcset en {New trigger} {New trigger}

### File: ../src/windows/table_win.tcl
mcset en {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.} {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset en {Edit trigger} {Edit trigger}

### File: ../src/windows/table_win.tcl
mcset en {Delete trigger} {Delete trigger}

### File: ../src/windows/table_win.tcl
mcset en {Are you sure you want to delete '%s' trigger?} {Are you sure you want to delete '%s' trigger?}

### File: ../src/windows/table_win.tcl
mcset en {Export table} {Export table}

### File: ../src/windows/table_win.tcl
mcset en {Import data} {Import data}

### File: ../src/windows/editor_win.tcl
mcset en {SQL query} {SQL query}

### File: ../src/windows/editor_win.tcl
mcset en Results Results

### File: ../src/windows/editor_win.tcl
mcset en History History

### File: ../src/windows/editor_win.tcl
mcset en {Execute query (%s)} {Execute query (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Execute query with plain string results} {Execute query with plain string results}

### File: ../src/windows/editor_win.tcl
mcset en {Explain query (%s)} {Explain query (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Format SQL code (%s)} {Format SQL code (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Refresh syntax highlighting (%s)} {Refresh syntax highlighting (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Clear history} {Clear history}

### File: ../src/windows/editor_win.tcl
mcset en {Export results} {Export results}

### File: ../src/windows/editor_win.tcl
mcset en {Create view from query} {Create view from query}

### File: ../src/windows/editor_win.tcl
mcset en {Execute SQL from file (%s)} {Execute SQL from file (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Load SQL from file (%s)} {Load SQL from file (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Save SQL to file (%s)} {Save SQL to file (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Default database for SQL executing
(%s/%s)} {Default database for SQL executing
(%s/%s)}

### File: ../src/windows/editor_win.tcl
mcset en Database Database

### File: ../src/windows/editor_win.tcl
mcset en {Execution date} {Execution date}

### File: ../src/windows/editor_win.tcl
mcset en {Execution time (s)} {Execution time (s)}

### File: ../src/windows/editor_win.tcl
mcset en {Rows affected} {Rows affected}

### File: ../src/windows/editor_win.tcl
mcset en SQL SQL

### File: ../src/windows/editor_win.tcl
mcset en {Plain text view} {Plain text view}

### File: ../src/windows/editor_win.tcl
mcset en {Refresh results (%s)} {Refresh results (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Commit row (%s)} {Commit row (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Rollback row (%s)} {Rollback row (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Copy (%s)} {Copy (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Cut (%s)} {Cut (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Paste (%s)} {Paste (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Show line numbers} {Show line numbers}

### File: ../src/windows/editor_win.tcl
mcset en {Delete selected history entry (%s)} {Delete selected history entry (%s)}

### File: ../src/windows/editor_win.tcl
mcset en {Choose the database first.} {Choose the database first.}

### File: ../src/windows/editor_win.tcl
mcset en {Error while trying to collect completion list: %s} {Error while trying to collect completion list: %s}

### File: ../src/windows/editor_win.tcl
mcset en {Can't open %s file for reading.} {Can't open %s file for reading.}

### File: ../src/windows/editor_win.tcl
mcset en {Can't open %s file for writting.} {Can't open %s file for writting.}

### File: ../src/windows/editor_win.tcl
mcset en {SQL code saved in %s.} {SQL code saved in %s.}

### File: ../src/windows/editor_win.tcl
mcset en {Are you sure you want to clear queries history?} {Are you sure you want to clear queries history?}

### File: ../src/windows/editor_win.tcl
mcset en {Delete the history entry} {Delete the history entry}

### File: ../src/windows/editor_win.tcl
mcset en {Are you sure you want to delete selected queries history entry?} {Are you sure you want to delete selected queries history entry?}

### File: ../src/windows/editor_win.tcl
mcset en Processing... Processing...

### File: ../src/windows/editor_win.tcl
mcset en {Processing query...} {Processing query...}

### File: ../src/windows/editor_win.tcl
mcset en {No results to export.} {No results to export.}

### File: ../src/windows/editor_win.tcl
mcset en {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.} {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.}

### File: ../src/windows/editor_win.tcl
mcset en {Query execution...} {Query execution...}

### File: ../src/windows/editor_win.tcl
mcset en {Executing SQL query...} {Executing SQL query...}

### File: ../src/windows/editor_win.tcl
mcset en {Error while executing query: %s} {Error while executing query: %s}

### File: ../src/windows/editor_win.tcl
mcset en {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s} {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s}

### File: ../src/windows/editor_win.tcl
mcset en {%s row(s) read in %s second(s).} {%s row(s) read in %s second(s).}

### File: ../src/windows/editor_win.tcl
mcset en {%s row(s) affected in %s second(s).} {%s row(s) affected in %s second(s).}

### File: ../src/windows/editor_win.tcl
mcset en {No SELECT statements found in editor or in selected part of SQL code.} {No SELECT statements found in editor or in selected part of SQL code.}

### File: ../src/windows/editor_win.tcl
mcset en {More than one SELECT statements found. Please select the one you're interested in and then try again.} {More than one SELECT statements found. Please select the one you're interested in and then try again.}

### File: ../src/windows/editor_win.tcl
mcset en {New view} {New view}

### File: ../src/windows/editor_win.tcl
mcset en {Fill query parameters} {Fill query parameters}

### File: ../src/error.tcl
mcset en {Background error} {Background error}

### File: ../src/error.tcl
mcset en Close Close

### File: ../src/error.tcl
mcset en {Report the bug} {Report the bug}

### File: ../src/dialogs/about_dialog.tcl
mcset en About About

### File: ../src/dialogs/about_dialog.tcl
mcset en {Packages and plugins} {Packages and plugins}

### File: ../src/dialogs/about_dialog.tcl
mcset en Licence Licence

### File: ../src/dialogs/about_dialog.tcl
mcset en {Installed plugins:} {Installed plugins:}

### File: ../src/dialogs/about_dialog.tcl
mcset en {Used Tcl packages:} {Used Tcl packages:}

### File: ../src/dialogs/about_dialog.tcl
mcset en {SQLite3 engine version: %s} {SQLite3 engine version: %s}

### File: ../src/dialogs/searchdialog.tcl
mcset en {Global expression understeands '*', '?' and \[chars].} {Global expression understeands '*', '?' and \[chars].}

### File: ../src/dialogs/searchdialog.tcl
mcset en Find Find

### File: ../src/dialogs/searchdialog.tcl
mcset en Replace Replace

### File: ../src/dialogs/searchdialog.tcl
mcset en {Do you want to replace marked text?} {Do you want to replace marked text?}

### File: ../src/dialogs/searchdialog.tcl
mcset en {Replace all} {Replace all}

### File: ../src/dialogs/searchdialog.tcl
mcset en {Replacing finished.} {Replacing finished.}

### File: ../src/dialogs/searchdialog.tcl
mcset en {Cannot match the pattern!} {Cannot match the pattern!}

### File: ../src/dialogs/bind_param.tcl
mcset en {Query number %s} {Query number %s}

### File: ../src/dialogs/bind_param.tcl
mcset en {Parameter number %s (named: %s):} {Parameter number %s (named: %s):}

### File: ../src/dialogs/bind_param.tcl
mcset en {NULL value} {NULL value}

### File: ../src/dialogs/bind_param.tcl
mcset en {You can use '%s' keyboard shortcut to switch NULL value.} {You can use '%s' keyboard shortcut to switch NULL value.}

### File: ../src/dialogs/bind_param.tcl
mcset en {Copy value to other '%s' parameters (%s)} {Copy value to other '%s' parameters (%s)}

### File: ../src/dialogs/bind_param.tcl
mcset en {By enabling this all parameters with same name
will also have same value as this one.} {By enabling this all parameters with same name
will also have same value as this one.}

### File: ../src/dialogs/bind_param.tcl
mcset en {Execute query} {Execute query}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset en Collation Collation

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset en Sort Sort

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset en {Named constraint:} {Named constraint:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset en {On conflict:} {On conflict:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset en {Constraint is marked as being named, but there's no name filled in.} {Constraint is marked as being named, but there's no name filled in.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset en {Collation for column '%s' is enabled, but there's no collation name filled in.} {Collation for column '%s' is enabled, but there's no collation name filled in.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset en {No columns are selected.} {No columns are selected.}

### File: ../src/dialogs/populate_table.tcl
mcset en {Number of rows to insert:} {Number of rows to insert:}

### File: ../src/dialogs/populate_table.tcl
mcset en {On a constraint violation:} {On a constraint violation:}

### File: ../src/dialogs/populate_table.tcl
mcset en Mode Mode

### File: ../src/dialogs/populate_table.tcl
mcset en {Select table to display available columns} {Select table to display available columns}

### File: ../src/dialogs/populate_table.tcl
mcset en Populate Populate

### File: ../src/dialogs/populate_table.tcl
mcset en {Error occured while populating table:
%s} {Error occured while populating table:
%s}

### File: ../src/dialogs/populate_table.tcl
mcset en Configuration Configuration

### File: ../src/dialogs/populate_table.tcl
mcset en {You have to type valid number of rows to insert.} {You have to type valid number of rows to insert.}

### File: ../src/dialogs/populate_table.tcl
mcset en {You have to select at least one column to populate.} {You have to select at least one column to populate.}

### File: ../src/dialogs/populate_table.tcl
mcset en Populating... Populating...

### File: ../src/dialogs/populate_table.tcl
mcset en {Populating table '%s'.} {Populating table '%s'.}

### File: ../src/dialogs/populate_table.tcl
mcset en Stop Stop

### File: ../src/dialogs/table_dialog_fk.tcl
mcset en {Foreign table:} {Foreign table:}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset en {Local column} {Local column}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset en {Foreign column} {Foreign column}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset en Reactions Reactions

### File: ../src/dialogs/table_dialog_fk.tcl
mcset en {ON UPDATE} {ON UPDATE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset en {ON DELETE} {ON DELETE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset en MATCH MATCH

### File: ../src/dialogs/table_dialog_fk.tcl
mcset en {Deferred foreign key} {Deferred foreign key}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset en {No foreign table selected.} {No foreign table selected.}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset en {There's no foreign column assigned for local column '%s'.} {There's no foreign column assigned for local column '%s'.}

### File: ../src/dialogs/import_dialog.tcl
mcset en {Import from:} {Import from:}

### File: ../src/dialogs/import_dialog.tcl
mcset en {Import to:} {Import to:}

### File: ../src/dialogs/import_dialog.tcl
mcset en Table Table

### File: ../src/dialogs/import_dialog.tcl
mcset en Existing Existing

### File: ../src/dialogs/import_dialog.tcl
mcset en {Create new table} {Create new table}

### File: ../src/dialogs/import_dialog.tcl
mcset en Import Import

### File: ../src/dialogs/import_dialog.tcl
mcset en {Import method is not selected.} {Import method is not selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset en {You have to choose database.} {You have to choose database.}

### File: ../src/dialogs/import_dialog.tcl
mcset en {No existing table is selected.} {No existing table is selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset en {Table typed to create already exists. Please change table name.} {Table typed to create already exists. Please change table name.}

### File: ../src/dialogs/view_dialog.tcl
mcset en View View

### File: ../src/dialogs/view_dialog.tcl
mcset en {View name:} {View name:}

### File: ../src/dialogs/view_dialog.tcl
mcset en {Code executed to get view data:} {Code executed to get view data:}

### File: ../src/dialogs/view_dialog.tcl
mcset en Create Create

### File: ../src/dialogs/view_dialog.tcl
mcset en Change Change

### File: ../src/dialogs/view_dialog.tcl
mcset en {You have to specify database.} {You have to specify database.}

### File: ../src/dialogs/view_dialog.tcl
mcset en {You have to specify view name.} {You have to specify view name.}

### File: ../src/dialogs/view_dialog.tcl
mcset en {You havn't wrote a code for the view.} {You havn't wrote a code for the view.}

### File: ../src/dialogs/export_dialog.tcl
mcset en {Export data} {Export data}

### File: ../src/dialogs/export_dialog.tcl
mcset en {Only structure, without data} {Only structure, without data}

### File: ../src/dialogs/export_dialog.tcl
mcset en {Table or view} {Table or view}

### File: ../src/dialogs/export_dialog.tcl
mcset en {Output file} {Output file}

### File: ../src/dialogs/export_dialog.tcl
mcset en {Export format} {Export format}

### File: ../src/dialogs/export_dialog.tcl
mcset en Export Export

### File: ../src/dialogs/export_dialog.tcl
mcset en {You have to choose file.} {You have to choose file.}

### File: ../src/dialogs/export_dialog.tcl
mcset en {Can't write to file: %s} {Can't write to file: %s}

### File: ../src/dialogs/export_dialog.tcl
mcset en {You have to choose table.} {You have to choose table.}

### File: ../src/dialogs/export_dialog.tcl
mcset en {Exporting database '%s'.} {Exporting database '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset en {Exporting table '%s'.} {Exporting table '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset en {Exporting view '%s'.} {Exporting view '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset en {Exporting results.} {Exporting results.}

### File: ../src/dialogs/export_dialog.tcl
mcset en Exporting... Exporting...

### File: ../src/dialogs/export_dialog.tcl
mcset en {Cannot write to file: %s
Please select other file.} {Cannot write to file: %s
Please select other file.}

### File: ../src/dialogs/bug_report_login.tcl
mcset en {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.} {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.}

### File: ../src/dialogs/bug_report_login.tcl
mcset en Login: Login:

### File: ../src/dialogs/bug_report_login.tcl
mcset en Password: Password:

### File: ../src/dialogs/bug_report_login.tcl
mcset en Validate Validate

### File: ../src/dialogs/bug_report_login.tcl
mcset en {Validation result} {Validation result}

### File: ../src/dialogs/bug_report_login.tcl
mcset en {Not validated yet} {Not validated yet}

### File: ../src/dialogs/bug_report_login.tcl
mcset en Validating... Validating...

### File: ../src/dialogs/bug_report_login.tcl
mcset en {Validating login and password...} {Validating login and password...}

### File: ../src/dialogs/bug_report_login.tcl
mcset en {Invalid login or password.} {Invalid login or password.}

### File: ../src/dialogs/bug_report_login.tcl
mcset en {Login and password are correct.} {Login and password are correct.}

### File: ../src/dialogs/bug_report.tcl
mcset en {Your e-mail address or user (both optional)} {Your e-mail address or user (both optional)}

### File: ../src/dialogs/bug_report.tcl
mcset en or or

### File: ../src/dialogs/bug_report.tcl
mcset en {Log in} {Log in}

### File: ../src/dialogs/bug_report.tcl
mcset en {Logged in} {Logged in}

### File: ../src/dialogs/bug_report.tcl
mcset en {Log out} {Log out}

### File: ../src/dialogs/bug_report.tcl
mcset en {Brief description:} {Brief description:}

### File: ../src/dialogs/bug_report.tcl
mcset en {How to reproduce problem (if possible):} {How to reproduce problem (if possible):}

### File: ../src/dialogs/bug_report.tcl
mcset en {What is the problem:} {What is the problem:}

### File: ../src/dialogs/bug_report.tcl
mcset en {Show more (optional)} {Show more (optional)}

### File: ../src/dialogs/bug_report.tcl
mcset en {Operating system:} {Operating system:}

### File: ../src/dialogs/bug_report.tcl
mcset en {Take screenshots of all SQLiteStudio windows and attach them} {Take screenshots of all SQLiteStudio windows and attach them}

### File: ../src/dialogs/bug_report.tcl
mcset en Send Send

### File: ../src/dialogs/bug_report.tcl
mcset en {Describe your feature request:} {Describe your feature request:}

### File: ../src/dialogs/bug_report.tcl
mcset en Hide Hide

### File: ../src/dialogs/bug_report.tcl
mcset en {Please fill 'Brief' field.} {Please fill 'Brief' field.}

### File: ../src/dialogs/bug_report.tcl
mcset en {Please fill at least one of 'Description' or 'How to reproduce' fields.} {Please fill at least one of 'Description' or 'How to reproduce' fields.}

### File: ../src/dialogs/bug_report.tcl
mcset en {Please provide valid e-mail address or leave 'E-mail' empty.} {Please provide valid e-mail address or leave 'E-mail' empty.}

### File: ../src/dialogs/bug_report.tcl
mcset en {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.} {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.}

### File: ../src/dialogs/db_convert.tcl
mcset en {Database to convert:} {Database to convert:}

### File: ../src/dialogs/db_convert.tcl
mcset en {Converted database name:} {Converted database name:}

### File: ../src/dialogs/db_convert.tcl
mcset en {File to use for converted database:} {File to use for converted database:}

### File: ../src/dialogs/db_convert.tcl
mcset en {Choose new file for database} {Choose new file for database}

### File: ../src/dialogs/db_convert.tcl
mcset en {Database version:} {Database version:}

### File: ../src/dialogs/db_convert.tcl
mcset en Convert Convert

### File: ../src/dialogs/db_convert.tcl
mcset en {Convert database} {Convert database}

### File: ../src/dialogs/db_convert.tcl
mcset en {You chave to choose database to convert.} {You chave to choose database to convert.}

### File: ../src/dialogs/db_convert.tcl
mcset en {Error resolving database with name %s!} {Error resolving database with name %s!}

### File: ../src/dialogs/db_convert.tcl
mcset en {You have to specify new database file.} {You have to specify new database file.}

### File: ../src/dialogs/db_convert.tcl
mcset en {Cannot use existing file for converted database.} {Cannot use existing file for converted database.}

### File: ../src/dialogs/db_convert.tcl
mcset en {Cannot use existing name for converted database.} {Cannot use existing name for converted database.}

### File: ../src/dialogs/db_convert.tcl
mcset en {Cannot find handler for database labeled with: %s} {Cannot find handler for database labeled with: %s}

### File: ../src/dialogs/db_convert.tcl
mcset en {Error while trying to create database: %s} {Error while trying to create database: %s}

### File: ../src/dialogs/db_convert.tcl
mcset en {Database converting error} {Database converting error}

### File: ../src/dialogs/db_convert.tcl
mcset en {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s} {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s}

### File: ../src/dialogs/db_convert.tcl
mcset en {Choose file} {Choose file}

### File: ../src/dialogs/yesno.tcl
mcset en Question Question

### File: ../src/dialogs/yesno.tcl
mcset en Warning Warning

### File: ../src/dialogs/yesno.tcl
mcset en Error Error

### File: ../src/dialogs/yesno.tcl
mcset en Information Information

### File: ../src/dialogs/import_db.tcl
mcset en {Import from one of databases:} {Import from one of databases:}

### File: ../src/dialogs/import_db.tcl
mcset en {Choose database file to import:} {Choose database file to import:}

### File: ../src/dialogs/import_db.tcl
mcset en {No database chosen.} {No database chosen.}

### File: ../src/dialogs/import_db.tcl
mcset en {Cannot open specified database.} {Cannot open specified database.}

### File: ../src/dialogs/import_db.tcl
mcset en {Error while importing database:
%s} {Error while importing database:
%s}

### File: ../src/dialogs/import_db.tcl
mcset en {Select file} {Select file}

### File: ../src/dialogs/column_dialog.tcl
mcset en Column: Column:

### File: ../src/dialogs/column_dialog.tcl
mcset en {Column constraints:} {Column constraints:}

### File: ../src/dialogs/column_dialog.tcl
mcset en Add Add

### File: ../src/dialogs/column_dialog.tcl
mcset en Size Size

### File: ../src/dialogs/column_dialog.tcl
mcset en {Maximal length of value in column.} {Maximal length of value in column.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Primary key configuration} {Primary key configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset en Autoincrement Autoincrement

### File: ../src/dialogs/column_dialog.tcl
mcset en {Sort order:} {Sort order:}

### File: ../src/dialogs/column_dialog.tcl
mcset en {No foreign column selected.} {No foreign column selected.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Choose ON UPDATE action, or disable it.} {Choose ON UPDATE action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Choose ON DELETE action, or disable it.} {Choose ON DELETE action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Choose MATCH action, or disable it.} {Choose MATCH action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Foreign key configuration} {Foreign key configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Foreign column:} {Foreign column:}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Unique configuration} {Unique configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Fill in the condition expression.} {Fill in the condition expression.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Check condition configuration} {Check condition configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset en Condition: Condition:

### File: ../src/dialogs/column_dialog.tcl
mcset en {Not null configuration} {Not null configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Fill in the collation name.} {Fill in the collation name.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Collating configuration} {Collating configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Collation name:} {Collation name:}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Fill in the default value.} {Fill in the default value.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Default value configuration} {Default value configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Default value:} {Default value:}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Use value as:} {Use value as:}

### File: ../src/dialogs/column_dialog.tcl
mcset en {A literal value} {A literal value}

### File: ../src/dialogs/column_dialog.tcl
mcset en {An expression} {An expression}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Column primary key is not configured correctly.} {Column primary key is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {AUTOINCREMENT is allowed only with INTEGER type of column.} {AUTOINCREMENT is allowed only with INTEGER type of column.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Column foreign key is not configured correctly.} {Column foreign key is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Column 'unique' constraint is not configured correctly.} {Column 'unique' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Column 'check' constraint is not configured correctly.} {Column 'check' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Column 'notnull' constraint is not configured correctly.} {Column 'notnull' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Column 'default' constraint is not configured correctly.} {Column 'default' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Column 'collate' constraint is not configured correctly.} {Column 'collate' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {No column name is specified.} {No column name is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Column with name '%s' already exists in the table.} {Column with name '%s' already exists in the table.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Data type bounds are given, but no data type name is specified.} {Data type bounds are given, but no data type name is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Data type precision is given, but no data type size is specified.} {Data type precision is given, but no data type size is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Data type size has invalid format. Only integer value is allowed.} {Data type size has invalid format. Only integer value is allowed.}

### File: ../src/dialogs/column_dialog.tcl
mcset en {Data type precision has invalid format. Only integer value is allowed.} {Data type precision has invalid format. Only integer value is allowed.}

### File: ../src/dialogs/assoc_dialog.tcl
mcset en {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:} {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:}

### File: ../src/dialogs/assoc_dialog.tcl
mcset en {Current associations} {Current associations}

### File: ../src/dialogs/assoc_dialog.tcl
mcset en {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.} {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.}

### File: ../src/dialogs/db_edit.tcl
mcset en {Database file:} {Database file:}

### File: ../src/dialogs/db_edit.tcl
mcset en {Database name:} {Database name:}

### File: ../src/dialogs/db_edit.tcl
mcset en {Generate automatically} {Generate automatically}

### File: ../src/dialogs/db_edit.tcl
mcset en {Type name in field below:} {Type name in field below:}

### File: ../src/dialogs/db_edit.tcl
mcset en {Remember it permanently} {Remember it permanently}

### File: ../src/dialogs/db_edit.tcl
mcset en {If disabled, then the database will be registered only
for this single SQLiteStudio session.} {If disabled, then the database will be registered only
for this single SQLiteStudio session.}

### File: ../src/dialogs/db_edit.tcl
mcset en {Edit database} {Edit database}

### File: ../src/dialogs/db_edit.tcl
mcset en {Add database} {Add database}

### File: ../src/dialogs/db_edit.tcl
mcset en {File '%s' doesn't exist!} {File '%s' doesn't exist!}

### File: ../src/dialogs/db_edit.tcl
mcset en {You have to specify database file.} {You have to specify database file.}

### File: ../src/dialogs/db_edit.tcl
mcset en {Database named '%s' already exists on databases list. Please pick other name.} {Database named '%s' already exists on databases list. Please pick other name.}

### File: ../src/dialogs/db_edit.tcl
mcset en {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.} {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.}

### File: ../src/dialogs/db_edit.tcl
mcset en {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.} {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.}

### File: ../src/dialogs/db_edit.tcl
mcset en {Type not existing file for new database} {Type not existing file for new database}

### File: ../src/dialogs/db_edit.tcl
mcset en {Select existing database file} {Select existing database file}

### File: ../src/dialogs/db_edit.tcl
mcset en {%s is not supported database!} {%s is not supported database!}

### File: ../src/dialogs/table_dialog_pk.tcl
mcset en {Using autoincrement with more than one column at once is forbidden.} {Using autoincrement with more than one column at once is forbidden.}

### File: ../src/dialogs/tips_dialog.tcl
mcset en Previous Previous

### File: ../src/dialogs/tips_dialog.tcl
mcset en Next Next

### File: ../src/dialogs/tips_dialog.tcl
mcset en {Do not show this dialog at startup} {Do not show this dialog at startup}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		} {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			You can configure all SQL editor syntax colors in settings.
		} {
			You can configure all SQL editor syntax colors in settings.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		} {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		} {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		} {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		} {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		} {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		} {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		} {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		} {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		} {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		} {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		} {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		} {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		} {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		} {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		} {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		} {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset en {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		} {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		}

### File: ../src/dialogs/import_table.tcl
mcset en Separator: Separator:

### File: ../src/dialogs/import_table.tcl
mcset en {Common separator is \t (tab), but sometimes others can be met.} {Common separator is \t (tab), but sometimes others can be met.}

### File: ../src/dialogs/import_table.tcl
mcset en {Import data file for '%s' table:} {Import data file for '%s' table:}

### File: ../src/dialogs/import_table.tcl
mcset en {File '%s' isn't readable!} {File '%s' isn't readable!}

### File: ../src/dialogs/import_table.tcl
mcset en {Error while trying to copy data:
%s} {Error while trying to copy data:
%s}

### File: ../src/dialogs/release_notes_dialog.tcl
mcset en {Don't show this dialog after update.} {Don't show this dialog after update.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en Trigger Trigger

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {On action:} {On action:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {Trigger name:} {Trigger name:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en When: When:

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {On table:} {On table:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {Execute code for:} {Execute code for:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.} {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {Execute code only when:} {Execute code only when:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {Code executed for above configuration:} {Code executed for above configuration:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {You have to specify view.} {You have to specify view.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {You have to specify table.} {You have to specify table.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {You have to specify trigger name.} {You have to specify trigger name.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {You have to specify 'action' condition.} {You have to specify 'action' condition.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {You havn't wrote a code for the trigger.} {You havn't wrote a code for the trigger.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset en {On view:} {On view:}

### File: ../src/dialogs/table_dialog.tcl
mcset en Columns: Columns:

### File: ../src/dialogs/table_dialog.tcl
mcset en {Table constraints:} {Table constraints:}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Table name:} {Table name:}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Add column} {Add column}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Edit selected} {Edit selected}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Delete selected} {Delete selected}

### File: ../src/dialogs/table_dialog.tcl
mcset en Type Type

### File: ../src/dialogs/table_dialog.tcl
mcset en Details Details

### File: ../src/dialogs/table_dialog.tcl
mcset en {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.} {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Edit column} {Edit column}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Delete column} {Delete column}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Are you sure you want to delete column '%s'?} {Are you sure you want to delete column '%s'?}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Constraint change} {Constraint change}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Are you sure you want to change constraint type?
Current constraint configuration will be lost.} {Are you sure you want to change constraint type?
Current constraint configuration will be lost.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Table constraint number %s (%s) is not configured correctly.} {Table constraint number %s (%s) is not configured correctly.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {There's no column defined.} {There's no column defined.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {There is already a table with name '%s'. Please change the name of this table.} {There is already a table with name '%s'. Please change the name of this table.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {There is already an index with name '%s'. Please change the name of this index.} {There is already an index with name '%s'. Please change the name of this index.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {There is already a trigger with name '%s'. Please change the name of this trigger.} {There is already a trigger with name '%s'. Please change the name of this trigger.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {There is already a view with name '%s'. Please change the name of this view.} {There is already a view with name '%s'. Please change the name of this view.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Trigger parsing problem} {Trigger parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Index parsing problem} {Index parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset en {View parsing problem} {View parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.} {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {%s(%s) referencing %s(%s)} {%s(%s) referencing %s(%s)}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s} {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Do you want to continue anyway?} {Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?} {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Modifying table...} {Modifying table...}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Modifying table '%s'.} {Modifying table '%s'.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Could not recreate triggers for modified table.} {Could not recreate triggers for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Could not recreate indexes for modified table.} {Could not recreate indexes for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Could not recreate views for modified table.} {Could not recreate views for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Trigger recreation problem} {Trigger recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset en {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Index recreation problem} {Index recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset en {Could not recreate foreign keys for tables referencing modified table.} {Could not recreate foreign keys for tables referencing modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset en {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset en {View recreation problem} {View recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset en {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).} {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).}

### File: ../src/dialogs/table_dialog_chk.tcl
mcset en {Condition expression cannot be empty.} {Condition expression cannot be empty.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset en {What would you like to do?} {What would you like to do?}

### File: ../src/dialogs/new_version_dialog.tcl
mcset en {Install it automatically} {Install it automatically}

### File: ../src/dialogs/new_version_dialog.tcl
mcset en {Go to download page} {Go to download page}

### File: ../src/dialogs/new_version_dialog.tcl
mcset en {Package download} {Package download}

### File: ../src/dialogs/new_version_dialog.tcl
mcset en {Insufficient privileges to perform automatic update.} {Insufficient privileges to perform automatic update.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset en {Check for updates at startup} {Check for updates at startup}

### File: ../src/dialogs/new_version_dialog.tcl
mcset en {New version of SQLiteStudio is available: %s} {New version of SQLiteStudio is available: %s}

### File: ../src/dialogs/trigger_dialog_cols.tcl
mcset en {Trigger columns} {Trigger columns}

### File: ../src/dialogs/blob_edit.tcl
mcset en Commit Commit

### File: ../src/dialogs/bug_history.tcl
mcset en Clear Clear

### File: ../src/dialogs/bug_history.tcl
mcset en {Reported on} {Reported on}

### File: ../src/dialogs/bug_history.tcl
mcset en Brief Brief

### File: ../src/dialogs/bug_history.tcl
mcset en URL URL

### File: ../src/dialogs/bug_history.tcl
mcset en Discussion Discussion

### File: ../src/dialogs/bug_history.tcl
mcset en {Clear reports} {Clear reports}

### File: ../src/dialogs/bug_history.tcl
mcset en {Do you want to clear whole bug reports history?} {Do you want to clear whole bug reports history?}

### File: ../src/dialogs/index_dialog.tcl
mcset en Index Index

### File: ../src/dialogs/index_dialog.tcl
mcset en {Index name:} {Index name:}

### File: ../src/dialogs/index_dialog.tcl
mcset en Available Available

### File: ../src/dialogs/index_dialog.tcl
mcset en Indexed Indexed

### File: ../src/dialogs/index_dialog.tcl
mcset en {Modifying index} {Modifying index}

### File: ../src/dialogs/index_dialog.tcl
mcset en {Modifying index '%s'} {Modifying index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset en {Creating index} {Creating index}

### File: ../src/dialogs/index_dialog.tcl
mcset en {Creating index '%s'} {Creating index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset en {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?} {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?}

### File: ../src/dialogs/index_dialog.tcl
mcset en {Unique values} {Unique values}

### File: ../src/dialogs/index_dialog.tcl
mcset en {Same values for '%s'} {Same values for '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset en {You have to select at least one column.} {You have to select at least one column.}

### File: ../src/dialogs/index_dialog.tcl
mcset en {You have to specify index name.} {You have to specify index name.}

### File: ../src/dialogs/functions_dialog.tcl
mcset en Implementation: Implementation:

### File: ../src/dialogs/functions_dialog.tcl
mcset en Name: Name:

### File: ../src/dialogs/functions_dialog.tcl
mcset en {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.} {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.}

### File: ../src/dialogs/functions_dialog.tcl
mcset en {Cannot use two functions with same name! Change name for '%s'.} {Cannot use two functions with same name! Change name for '%s'.}

### File: ../src/dialogs/functions_dialog.tcl
mcset en {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! } {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! }

### File: ../src/dialogs/functions_dialog.tcl
mcset en {Function '%s' is not implemented!} {Function '%s' is not implemented!}

### File: ../src/dialogs/functions_dialog.tcl
mcset en {Delete function} {Delete function}

### File: ../src/dialogs/functions_dialog.tcl
mcset en {Are you sure you want to delete function '%s'?} {Are you sure you want to delete function '%s'?}

### File: ../src/mainwindow.tcl
mcset en {Connect to selected database} {Connect to selected database}

### File: ../src/mainwindow.tcl
mcset en {Disconnect from selected database} {Disconnect from selected database}

### File: ../src/mainwindow.tcl
mcset en {Remove selected database from list} {Remove selected database from list}

### File: ../src/mainwindow.tcl
mcset en {New table} {New table}

### File: ../src/mainwindow.tcl
mcset en {Drop table} {Drop table}

### File: ../src/mainwindow.tcl
mcset en {Drop index} {Drop index}

### File: ../src/mainwindow.tcl
mcset en {Drop trigger} {Drop trigger}

### File: ../src/mainwindow.tcl
mcset en {Edit view} {Edit view}

### File: ../src/mainwindow.tcl
mcset en {Drop view} {Drop view}

### File: ../src/mainwindow.tcl
mcset en {Arrange cascade windows layout} {Arrange cascade windows layout}

### File: ../src/mainwindow.tcl
mcset en {Arrange intelligent windows layout} {Arrange intelligent windows layout}

### File: ../src/mainwindow.tcl
mcset en {Refresh databases tree (%s)} {Refresh databases tree (%s)}

### File: ../src/mainwindow.tcl
mcset en {Open SQL query editor} {Open SQL query editor}

### File: ../src/mainwindow.tcl
mcset en {Settings (%s)} {Settings (%s)}

### File: ../src/mainwindow.tcl
mcset en {Open SQL functions editor} {Open SQL functions editor}

### File: ../src/mainwindow.tcl
mcset en {Clear objects filter} {Clear objects filter}

### File: ../src/mainwindow.tcl
mcset en {Enter object name you want to look for} {Enter object name you want to look for}

### File: ../src/mainwindow.tcl
mcset en Databases Databases

### File: ../src/mainwindow.tcl
mcset en Tools Tools

### File: ../src/mainwindow.tcl
mcset en Connect Connect

### File: ../src/mainwindow.tcl
mcset en Disconnect Disconnect

### File: ../src/mainwindow.tcl
mcset en {Remove from list} {Remove from list}

### File: ../src/mainwindow.tcl
mcset en {View main toolbar} {View main toolbar}

### File: ../src/mainwindow.tcl
mcset en {View structure toolbar} {View structure toolbar}

### File: ../src/mainwindow.tcl
mcset en {View windows toolbar} {View windows toolbar}

### File: ../src/mainwindow.tcl
mcset en {View tools toolbar} {View tools toolbar}

### File: ../src/mainwindow.tcl
mcset en {View configuration toolbar} {View configuration toolbar}

### File: ../src/mainwindow.tcl
mcset en {Refresh databases tree} {Refresh databases tree}

### File: ../src/mainwindow.tcl
mcset en {Custom SQL functions} {Custom SQL functions}

### File: ../src/mainwindow.tcl
mcset en {Export database} {Export database}

### File: ../src/mainwindow.tcl
mcset en {Export table or view} {Export table or view}

### File: ../src/mainwindow.tcl
mcset en {Import data to a table} {Import data to a table}

### File: ../src/mainwindow.tcl
mcset en {SQLiteStudio home page} {SQLiteStudio home page}

### File: ../src/mainwindow.tcl
mcset en {SQLiteStudio manual} {SQLiteStudio manual}

### File: ../src/mainwindow.tcl
mcset en {SQLite documentation} {SQLite documentation}

### File: ../src/mainwindow.tcl
mcset en {SQLiteStudio support forum} {SQLiteStudio support forum}

### File: ../src/mainwindow.tcl
mcset en {Report a bug} {Report a bug}

### File: ../src/mainwindow.tcl
mcset en {Send feature request} {Send feature request}

### File: ../src/mainwindow.tcl
mcset en {Show bug reports history} {Show bug reports history}

### File: ../src/mainwindow.tcl
mcset en {Show tips window} {Show tips window}

### File: ../src/mainwindow.tcl
mcset en ChangeLog ChangeLog

### File: ../src/mainwindow.tcl
mcset en Roadmap Roadmap

### File: ../src/mainwindow.tcl
mcset en {Check for new version} {Check for new version}

### File: ../src/mainwindow.tcl
mcset en Donate Donate

### File: ../src/mainwindow.tcl
mcset en {Did you know that...} {Did you know that...}

### File: ../src/mainwindow.tcl
mcset en {Editor %s} {Editor %s}

### File: ../src/mainwindow.tcl
mcset en Settings Settings

### File: ../src/mainwindow.tcl
mcset en {SQLiteStudio roadmap} {SQLiteStudio roadmap}

### File: ../src/mainwindow.tcl
mcset en {Can't start web browser, because:
%s} {Can't start web browser, because:
%s}

### File: ../src/mainwindow.tcl
mcset en {Can't start %s web browser, because:
%s} {Can't start %s web browser, because:
%s}

### File: ../src/mainwindow.tcl
mcset en {About SQLiteStudio} {About SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset en {SQLiteStudio ChangeLog} {SQLiteStudio ChangeLog}

### File: ../src/mainwindow.tcl
mcset en {There is no new version available.} {There is no new version available.}

### File: ../src/mainwindow.tcl
mcset en {New version} {New version}

### File: ../src/mainwindow.tcl
mcset en {Report bug} {Report bug}

### File: ../src/mainwindow.tcl
mcset en {Feature request} {Feature request}

### File: ../src/mainwindow.tcl
mcset en {Reports history} {Reports history}

### File: ../src/mainwindow.tcl
mcset en {Reporting bug} {Reporting bug}

### File: ../src/mainwindow.tcl
mcset en {Reporting bug to SQLiteStudio bugs database...} {Reporting bug to SQLiteStudio bugs database...}

### File: ../src/mainwindow.tcl
mcset en {Problem occurred while reporting bug. You can ignore it and get back to your work.} {Problem occurred while reporting bug. You can ignore it and get back to your work.}

### File: ../src/mainwindow.tcl
mcset en Ignore Ignore

### File: ../src/mainwindow.tcl
mcset en {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history} {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history}

### File: ../src/mainwindow.tcl
mcset en {A timeout occured while downloading new version. Try again, or download it manually.} {A timeout occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset en {An error occured while downloading new version. Try again, or download it manually.} {An error occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset en Downloading... Downloading...

### File: ../src/mainwindow.tcl
mcset en {Downloading SQLiteStudio v%s...} {Downloading SQLiteStudio v%s...}

### File: ../src/mainwindow.tcl
mcset en {Problem with saving new SQLiteStudio version to:
%s
Details:
%s} {Problem with saving new SQLiteStudio version to:
%s
Details:
%s}

### File: ../src/mainwindow.tcl
mcset en {Problem with getting new SQLiteStudio version
Details:
%s} {Problem with getting new SQLiteStudio version
Details:
%s}

### File: ../src/mainwindow.tcl
mcset en {This is unknown binary distribution. Cannot determinate binary file to download for update.} {This is unknown binary distribution. Cannot determinate binary file to download for update.}

### File: ../src/data_editor.tcl
mcset en {There are uncommited rows.
Are you sure you want to close '%s' window anywy?} {There are uncommited rows.
Are you sure you want to close '%s' window anywy?}

### File: ../src/common/ddl_dialog.tcl
mcset en {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s} {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s}

### File: ../src/common/color_picker.tcl
mcset en {Choose color} {Choose color}

### File: ../src/common/shortcut_edit.tcl
mcset en {Forbidden shortcut key combination: %s} {Forbidden shortcut key combination: %s}

### File: ../src/common/common.tcl
mcset en Copy Copy

### File: ../src/common/common.tcl
mcset en Cut Cut

### File: ../src/common/common.tcl
mcset en Paste Paste

### File: ../src/common/blob_edit_panel.tcl
mcset en {Text edit} {Text edit}

### File: ../src/common/blob_edit_panel.tcl
mcset en {Hexadecimal edit} {Hexadecimal edit}

### File: ../src/common/common_sql.tcl
mcset en {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
} {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
}

### File: ../src/common/hex_editor.tcl
mcset en {Overwrite characters,
instead of inserting} {Overwrite characters,
instead of inserting}

### File: ../src/common/hex_editor.tcl
mcset en Processing Processing

### File: ../src/common/hex_editor.tcl
mcset en {Processing data...} {Processing data...}

### File: ../src/sql_editor.tcl
mcset en {Replace dialog} {Replace dialog}

### File: ../src/sql_editor.tcl
mcset en {Search dialog} {Search dialog}

### File: ../src/trees/db_tree.tcl
mcset en Loading Loading

### File: ../src/trees/db_tree.tcl
mcset en {Loading database list} {Loading database list}

### File: ../src/trees/db_tree.tcl
mcset en {Given database file doesn't exist or is unreadable.} {Given database file doesn't exist or is unreadable.}

### File: ../src/trees/db_tree.tcl
mcset en Vacuum Vacuum

### File: ../src/trees/db_tree.tcl
mcset en {Integrity check} {Integrity check}

### File: ../src/trees/db_tree.tcl
mcset en {Import schema from other database} {Import schema from other database}

### File: ../src/trees/db_tree.tcl
mcset en {Reset autoincrement for '%s'} {Reset autoincrement for '%s'}

### File: ../src/trees/db_tree.tcl
mcset en {Erase table data} {Erase table data}

### File: ../src/trees/db_tree.tcl
mcset en {Create foreign key} {Create foreign key}

### File: ../src/trees/db_tree.tcl
mcset en {Show view data} {Show view data}

### File: ../src/trees/db_tree.tcl
mcset en {Export view} {Export view}

### File: ../src/trees/db_tree.tcl
mcset en {Sort databases alphabetically} {Sort databases alphabetically}

### File: ../src/trees/db_tree.tcl
mcset en {Given database is already on the list.} {Given database is already on the list.}

### File: ../src/trees/db_tree.tcl
mcset en {Given database name is already on the list.} {Given database name is already on the list.}

### File: ../src/trees/db_tree.tcl
mcset en Tables Tables

### File: ../src/trees/db_tree.tcl
mcset en Views Views

### File: ../src/trees/db_tree.tcl
mcset en {SQLite system table} {SQLite system table}

### File: ../src/trees/db_tree.tcl
mcset en Columns Columns

### File: ../src/trees/db_tree.tcl
mcset en {SQLite system index} {SQLite system index}

### File: ../src/trees/db_tree.tcl
mcset en {Remove database} {Remove database}

### File: ../src/trees/db_tree.tcl
mcset en {Are you sure you want to remove '%s' database from the list?} {Are you sure you want to remove '%s' database from the list?}

### File: ../src/trees/db_tree.tcl
mcset en {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.} {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.}

### File: ../src/trees/db_tree.tcl
mcset en {'%s' is a virtual table, therefore cannot be browsed in table window.} {'%s' is a virtual table, therefore cannot be browsed in table window.}

### File: ../src/trees/db_tree.tcl
mcset en {Table '%s' has no DDL. Probably it's system table and should not be edited.} {Table '%s' has no DDL. Probably it's system table and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset en {'%s' is a virtual table, therefore cannot be edited in table dialog.} {'%s' is a virtual table, therefore cannot be edited in table dialog.}

### File: ../src/trees/db_tree.tcl
mcset en {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.} {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.}

### File: ../src/trees/db_tree.tcl
mcset en {Integrity check (%s)} {Integrity check (%s)}

### File: ../src/trees/db_tree.tcl
mcset en {Are you sure you want to DROP '%s' table?} {Are you sure you want to DROP '%s' table?}

### File: ../src/trees/db_tree.tcl
mcset en {Dropping table} {Dropping table}

### File: ../src/trees/db_tree.tcl
mcset en {Dropping table '%s'} {Dropping table '%s'}

### File: ../src/trees/db_tree.tcl
mcset en {Dropping index} {Dropping index}

### File: ../src/trees/db_tree.tcl
mcset en {Dropping index '%s'} {Dropping index '%s'}

### File: ../src/trees/db_tree.tcl
mcset en {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?} {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset en {Fix trigger} {Fix trigger}

### File: ../src/trees/db_tree.tcl
mcset en {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.} {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset en {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?} {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset en {Fix view} {Fix view}

### File: ../src/trees/db_tree.tcl
mcset en {View '%s' has no DDL. Probably it's system view and should not be edited.} {View '%s' has no DDL. Probably it's system view and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset en {Delete view} {Delete view}

### File: ../src/trees/db_tree.tcl
mcset en {Are you sure you want to delete '%s' view?} {Are you sure you want to delete '%s' view?}

### File: ../src/trees/db_tree.tcl
mcset en {Erase data} {Erase data}

### File: ../src/trees/db_tree.tcl
mcset en {Are you sure you want to delete all data from table '%s'?} {Are you sure you want to delete all data from table '%s'?}

### File: ../src/trees/db_tree.tcl
mcset en {Deleting data} {Deleting data}

### File: ../src/trees/db_tree.tcl
mcset en {Deleting data from table '%s'} {Deleting data from table '%s'}

### File: ../src/trees/db_tree.tcl
mcset en {'%s' view data} {'%s' view data}

### File: ../src/trees/db_tree.tcl
mcset en {Are you sure you want to make a vacuum?} {Are you sure you want to make a vacuum?}

### File: ../src/trees/db_tree.tcl
mcset en Vacuuming Vacuuming

### File: ../src/trees/db_tree.tcl
mcset en {Vacuuming '%s'} {Vacuuming '%s'}

### File: ../src/trees/db_tree.tcl
mcset en {SQL files} {SQL files}

### File: ../src/trees/db_tree.tcl
mcset en {Select SQL file to be executed} {Select SQL file to be executed}

### File: ../src/trees/db_tree.tcl
mcset en {Error while executing SQL:
%s} {Error while executing SQL:
%s}

### File: ../src/trees/db_tree.tcl
mcset en {SQL executed sucessfly.} {SQL executed sucessfly.}

### File: ../src/trees/db_tree.tcl
mcset en {Import database schema} {Import database schema}

### File: ../src/trees/db_tree.tcl
mcset en {Database: %s} {Database: %s}

### File: ../src/trees/db_tree.tcl
mcset en URI: URI:

### File: ../src/trees/db_tree.tcl
mcset en Version: Version:

### File: ../src/trees/db_tree.tcl
mcset en {File size:} {File size:}

### File: ../src/trees/db_tree.tcl
mcset en {Schema version:} {Schema version:}

### File: ../src/trees/db_tree.tcl
mcset en {Virtual table} {Virtual table}

### File: ../src/trees/db_tree.tcl
mcset en Indexes: Indexes:

### File: ../src/trees/db_tree.tcl
mcset en Triggers: Triggers:

### File: ../src/trees/db_tree.tcl
mcset en {Column: %s} {Column: %s}

### File: ../src/trees/db_tree.tcl
mcset en {Not null} {Not null}

### File: ../src/trees/db_tree.tcl
mcset en {Indexed table:} {Indexed table:}

### File: ../src/trees/db_tree.tcl
mcset en {Copy index '%s' for table '%s'} {Copy index '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset en {Move index '%s' to table '%s'} {Move index '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset en {Copy trigger '%s' for table '%s'} {Copy trigger '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset en {Move trigger '%s' to table '%s'} {Move trigger '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset en {Copy view '%s' for database '%s'} {Copy view '%s' for database '%s'}

### File: ../src/trees/db_tree.tcl
mcset en {Move view '%s' to database '%s'} {Move view '%s' to database '%s'}

### File: ../src/trees/db_tree.tcl
mcset en {View '%s' has no DDL, therefore cannot be edited.} {View '%s' has no DDL, therefore cannot be edited.}

### File: ../src/trees/db_tree.tcl
mcset en {Copy view} {Copy view}

### File: ../src/trees/db_tree.tcl
mcset en {Move view} {Move view}

### File: ../src/trees/db_tree.tcl
mcset en Move Move

### File: ../src/trees/db_tree.tcl
mcset en {Copy index} {Copy index}

### File: ../src/trees/db_tree.tcl
mcset en {Move index} {Move index}

### File: ../src/trees/db_tree.tcl
mcset en {Copy trigger} {Copy trigger}

### File: ../src/trees/db_tree.tcl
mcset en {Move trigger} {Move trigger}

### File: ../src/trees/db_tree.tcl
mcset en {Copy table '%s' to database '%s' (include data, indexes and triggers)} {Copy table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset en {Copy table '%s' to database '%s' (include data)} {Copy table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset en {Copy table '%s' to database '%s' (include indexes and triggers)} {Copy table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset en {Copy table '%s' to database '%s' (skip data, indexes and triggers)} {Copy table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset en {Move table '%s' to database '%s' (include data, indexes and triggers)} {Move table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset en {Move table '%s' to database '%s' (include data)} {Move table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset en {Move table '%s' to database '%s' (include indexes and triggers)} {Move table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset en {Move table '%s' to database '%s' (skip data, indexes and triggers)} {Move table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset en {Copying table...} {Copying table...}

### File: ../src/trees/db_tree.tcl
mcset en {Copying table '%s' from '%s' to '%s'.} {Copying table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset en {Moving table...} {Moving table...}

### File: ../src/trees/db_tree.tcl
mcset en {Moving table '%s' from '%s' to '%s'.} {Moving table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset en {Could not create object in target database:
%s} {Could not create object in target database:
%s}

### File: ../src/trees/db_tree.tcl
mcset en {Could not copy data:
%s} {Could not copy data:
%s}

### File: ../src/trees/db_tree.tcl
mcset en {Could not copy table data from source database to target database. Details: %s} {Could not copy table data from source database to target database. Details: %s}

### File: ../src/trees/db_tree.tcl
mcset en {Could not delete object(s) from source database. Details: %s} {Could not delete object(s) from source database. Details: %s}

### File: ../src/grids/dbgrid.tcl
mcset en {Edit BLOB entry:} {Edit BLOB entry:}

### File: ../src/grids/dbgrid.tcl
mcset en {BLOB edit} {BLOB edit}

### File: ../src/grids/dbgrid.tcl
mcset en {Cannot commit. Details:
%s} {Cannot commit. Details:
%s}

### File: ../src/grids/grid.tcl
mcset en {You have to select a cell before paste any contents.} {You have to select a cell before paste any contents.}

### File: ../src/grids/grid.tcl
mcset en {Cut data} {Cut data}

### File: ../src/grids/grid.tcl
mcset en {There are too many columns or rows to paste. Do you want to cut them and paste?} {There are too many columns or rows to paste. Do you want to cut them and paste?}

### File: ../src/grids/data_grid.tcl
mcset en {Insert new row} {Insert new row}

### File: ../src/grids/data_grid.tcl
mcset en {Delete selected rows} {Delete selected rows}

### File: ../src/grids/data_grid.tcl
mcset en {Edit cell value} {Edit cell value}

### File: ../src/grids/data_grid.tcl
mcset en {Edit cell value in BLOB editor} {Edit cell value in BLOB editor}

### File: ../src/grids/data_grid.tcl
mcset en {Duplicate row} {Duplicate row}

### File: ../src/grids/data_grid.tcl
mcset en {Set NULL value} {Set NULL value}

### File: ../src/grids/data_grid.tcl
mcset en {Generate SELECT from selected cells} {Generate SELECT from selected cells}

### File: ../src/grids/data_grid.tcl
mcset en {Commit selected cells} {Commit selected cells}

### File: ../src/grids/data_grid.tcl
mcset en {Rollback selected cells} {Rollback selected cells}

### File: ../src/grids/data_grid.tcl
mcset en {Select all} {Select all}

### File: ../src/grids/data_grid.tcl
mcset en {Show ordinals} {Show ordinals}

### File: ../src/grids/data_grid.tcl
mcset en {Show ROWIDs} {Show ROWIDs}

### File: ../src/grids/data_grid.tcl
mcset en Type: Type:

### File: ../src/grids/data_grid.tcl
mcset en Constraints: Constraints:

### File: ../src/grids/data_grid.tcl
mcset en {%s column has NOT NULL constraint. You have to fill value for it.} {%s column has NOT NULL constraint. You have to fill value for it.}

### File: ../src/grids/data_grid.tcl
mcset en {Error while adding new row:
%s} {Error while adding new row:
%s}

### File: ../src/grids/data_grid.tcl
mcset en {Error while updating new row:
%s} {Error while updating new row:
%s}

### File: ../src/grids/data_grid.tcl
mcset en {Error while updating cell value:
%s

What would you like to do?} {Error while updating cell value:
%s

What would you like to do?}

### File: ../src/grids/data_grid.tcl
mcset en {Re-edit value} {Re-edit value}

### File: ../src/grids/data_grid.tcl
mcset en {Return to value before edition} {Return to value before edition}

### File: ../src/grids/data_grid.tcl
mcset en {Cannot delete row(s), because it violates constraint. Details:
%s} {Cannot delete row(s), because it violates constraint. Details:
%s}

### File: ../src/grids/data_grid.tcl
mcset en {Error while deleting selected rows:
%s} {Error while deleting selected rows:
%s}

### File: ../src/grids/data_grid.tcl
mcset en {SQL query generated at %s
using selected cells from window '%s'.} {SQL query generated at %s
using selected cells from window '%s'.}

### File: ../src/grids/result_grid.tcl
mcset en {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.} {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.}

### File: ../src/grids/result_grid.tcl
mcset en {Data type:} {Data type:}

### File: ../src/grids/result_grid.tcl
mcset en {No details are available on this cell.} {No details are available on this cell.}

### File: ../src/grids/result_grid.tcl
mcset en {Duplicated ROWID} {Duplicated ROWID}

### File: ../src/grids/result_grid.tcl
mcset en {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?} {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?}

### File: ../src/grids/result_grid.tcl
mcset en {Could not parse SQL while trying to generate requested query: %s} {Could not parse SQL while trying to generate requested query: %s}

### File: ../src/grids/result_grid.tcl
mcset en {Cannot use '%s' statement to generate requested query.} {Cannot use '%s' statement to generate requested query.}

### File: ../src/grids/result_grid.tcl
mcset en {Cannot determinate selected column with ID=%s.} {Cannot determinate selected column with ID=%s.}

### File: ../src/grids/result_grid.tcl
mcset en {Error occurred while trying to generate the query: %s} {Error occurred while trying to generate the query: %s}

### File: ../src/grids/result_grid.tcl
mcset en {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s} {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s}
