# SQLiteStudio 'es' localization file

# Unchanged translations

### File: ../src/win_assoc.tcl
mcset es {File associations} {File associations}

### File: ../src/win_assoc.tcl
mcset es {Following file extensions could not be associated to the current SQLiteStudio version:
%s} {Following file extensions could not be associated to the current SQLiteStudio version:
%s}

### File: ../src/win_assoc.tcl
mcset es {Click the link below to find out what is possible reason and solutions.} {Click the link below to find out what is possible reason and solutions.}

### File: ../src/cfg_win.tcl
mcset es Ok Ok

### File: ../src/cfg_win.tcl
mcset es Apply Aplicar

### File: ../src/cfg_win.tcl
mcset es Cancel Cancelar

### File: ../src/cfg_win.tcl
mcset es Theme Temas

### File: ../src/cfg_win.tcl
mcset es {Select theme to use:} {Elige tema a usar:}

### File: ../src/cfg_win.tcl
mcset es {Theme version:} {Versión del tema:}

### File: ../src/cfg_win.tcl
mcset es Shortcuts {Accesos directos de teclado}

### File: ../src/cfg_win.tcl
mcset es {Global shortcuts} {Accesos directos de teclado Globales}

### File: ../src/cfg_win.tcl
mcset es {Open SQL editor} {Abrir editor SQL}

### File: ../src/cfg_win.tcl
mcset es {Opens SQL editor window.} {Abrir ventana de editor SQL.}

### File: ../src/cfg_win.tcl
mcset es {Close selected task} {Cerrar tarea seleccionada}

### File: ../src/cfg_win.tcl
mcset es {Closes active MDI window.} {Cerrar ventana MDI activa.}

### File: ../src/cfg_win.tcl
mcset es {Restore last closed task} {Restore last closed task}

### File: ../src/cfg_win.tcl
mcset es {Restores last closed MDI window.} {Restores last closed MDI window.}

### File: ../src/cfg_win.tcl
mcset es {Open settings} {Abrir ajustes}

### File: ../src/cfg_win.tcl
mcset es {Opens SQLiteStudio settings window.} {Abrir ajustes de ventana de SQLiteStudio.}

### File: ../src/cfg_win.tcl
mcset es {Next task} {Nueva tarea}

### File: ../src/cfg_win.tcl
mcset es {Switches task (window) to next, placed on the right from active task on taskbar.} {Cambiar a la siguiente tarea (ventana), situada a la derecha de la tarea activa en la barra de tareas.}

### File: ../src/cfg_win.tcl
mcset es {Next task (alternative)} {Siguiente tarea (alternativa)}

### File: ../src/cfg_win.tcl
mcset es {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Cambia a la siguiente tarea (ventana), situada a la derecha de la tarea activa en la barra de tareas.
Este es un acceso directo de teclado alternativo. Hace lo mismo que el anterior.}

### File: ../src/cfg_win.tcl
mcset es {Previous task} {Tarea anterior}

### File: ../src/cfg_win.tcl
mcset es {Switches task (window) to previous, placed on the left from active task on taskbar.} {Cambiara a la anterior tarea (ventana), situada a la izquierda de la tarea activa en la barra de tareas.}

### File: ../src/cfg_win.tcl
mcset es {Previous task (alternative)} {Tarea anterior (alternativa)}

### File: ../src/cfg_win.tcl
mcset es {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Cambia a la tarea anterior (ventana), situada a la izquierda de la tarea activa en la barra de tareas.
Este es un acceso directo de teclado alternativo. Hace lo mismo que el anterior.}

### File: ../src/cfg_win.tcl
mcset es {Editor and table window shortcuts} {Accesos directos de teclado para el Editor y la ventana de Tabla}

### File: ../src/cfg_win.tcl
mcset es {SQL editor completion} {SQL editor completion}

### File: ../src/cfg_win.tcl
mcset es {Invokes SQL completion in editor window.} {Invokes SQL completion in editor window.}

### File: ../src/cfg_win.tcl
mcset es {Execute SQL query} {Ejecutar consulta SQL}

### File: ../src/cfg_win.tcl
mcset es {Executes SQL query typed in editor.} {Ejecutar consulta SQL query escrita en el editor.}

### File: ../src/cfg_win.tcl
mcset es {Explain SQL query} {Explicar consulta SQL}

### File: ../src/cfg_win.tcl
mcset es {Calls EXPLAIN on SQL query typed in editor.} {Explicar consulta SQL escrita en el editor.}

### File: ../src/cfg_win.tcl
mcset es {Format SQL code} {Dar formato al código SQL}

### File: ../src/cfg_win.tcl
mcset es {Formats SQL code typed in editor.} {Dar formato al código SQL escrito en el editor.}

### File: ../src/cfg_win.tcl
mcset es {Load SQL from file} {Cargar SQL desde archivo}

### File: ../src/cfg_win.tcl
mcset es {Loads SQL from file to the editor.} {Loads SQL from file to the editor.}

### File: ../src/cfg_win.tcl
mcset es {Save SQL to file} {Guardar SQL en archivo}

### File: ../src/cfg_win.tcl
mcset es {Saves contents of the editor into a file.} {Saves contents of the editor into a file.}

### File: ../src/cfg_win.tcl
mcset es {Execute SQL from file} {Ejecutar SQL desde archivo}

### File: ../src/cfg_win.tcl
mcset es {Executes SQL directly from file, without loading it to the editor.} {Executes SQL directly from file, without loading it to the editor.}

### File: ../src/cfg_win.tcl
mcset es {Next tab} {Siguiente Pestaña}

### File: ../src/cfg_win.tcl
mcset es {Switches to next tab of editor window (result or history).} {Cambiar a la siguiente pestaña de la ventana de editor (Resultado o historial).}

### File: ../src/cfg_win.tcl
mcset es {Previous tab} {Pestaña anterior}

### File: ../src/cfg_win.tcl
mcset es {Switches to previous tab of editor window (query or result).} {Cambiar a la pestaña anterior de la ventana de editor (Consulta o Resultado).}

### File: ../src/cfg_win.tcl
mcset es {Next subtab} {Siguiente sub-pestaña}

### File: ../src/cfg_win.tcl
mcset es {Switches to next subtab (form view in results tab).} {Cambiar a la siguiente sub-pestaña (vista de formulario en la pestaña de resultados).}

### File: ../src/cfg_win.tcl
mcset es {Previous subtab} {Sub-pestaña anterior}

### File: ../src/cfg_win.tcl
mcset es {Switches to previous subtab (grid view in results tab).} {Cambiar a la sub-pestaña anterior (vista de rejilla en la pestaña de resultados).}

### File: ../src/cfg_win.tcl
mcset es Refresh Actualizar

### File: ../src/cfg_win.tcl
mcset es {Re-executes SQL query so results data is refreshed.} {Re-ejecutar consulta SQL para actualizar los datos resultado.}

### File: ../src/cfg_win.tcl
mcset es {Delete selected row} {Eliminar fila seleccionada}

### File: ../src/cfg_win.tcl
mcset es {Deletes selected row.} {Eliminar la fila seleccionada.}

### File: ../src/cfg_win.tcl
mcset es {Add new row} {Añadir nueva fila}

### File: ../src/cfg_win.tcl
mcset es {Adds new empty row without commiting it.} {Añadir nueva fila vacía sin fijarla (commit).}

### File: ../src/cfg_win.tcl
mcset es {Erase cells data} {Erase cells data}

### File: ../src/cfg_win.tcl
mcset es {Erases data of selected cells.} {Erases data of selected cells.}

### File: ../src/cfg_win.tcl
mcset es {Next editor database in list} {Siguiente editor de Bases de Datos en la lista}

### File: ../src/cfg_win.tcl
mcset es {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)} {Cambia a la siguiente Base de Datos de la lista de Bases de Datos en el editor contextual
(Es una lista desplegable situada en la parte superior de la ventana de edición)}

### File: ../src/cfg_win.tcl
mcset es {Previous editor database in list} {Anterior editor de Bases de Datos en la lista}

### File: ../src/cfg_win.tcl
mcset es {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)} {Cambia a la Base de Datos anterior de la lista de Bases de Datos en la ventana de edición
(Es una lista desplegable situada en la parte superior de la ventana de edición)}

### File: ../src/cfg_win.tcl
mcset es {Commit edition in Form View} {Fijar (commit) edición en la Vista de Formulario}

### File: ../src/cfg_win.tcl
mcset es {Commits edition in Form View of query results or table data preview.} {Fijar (commit) edicion en la Vista de formulario de resultados de consulta o previsualización de datos de tabla.}

### File: ../src/cfg_win.tcl
mcset es {Rollback edition in Form View} {Revertir (rollback) edición en la Vista de Formulario}

### File: ../src/cfg_win.tcl
mcset es {Rolls back edition in Form View of query results or table data preview.} {Revertir (rollback) edición en la Vista de Formuario de resultados de consulta o previsualización de datos de tabla.}

### File: ../src/cfg_win.tcl
mcset es {Jump to first row in Form View} {Saltar a la primera fila de la Vista de Formulario}

### File: ../src/cfg_win.tcl
mcset es {Jumps to first row of query results grid
or table data preview grid in Form View.} {Salta a la primera fila de la rejilla de resultados de consulta
o de la rejilla de previsualización de datos en la Vista de Formulario.}

### File: ../src/cfg_win.tcl
mcset es {Go to previous row in Form View} {Ir a la fila previa en la Vista de Formulario}

### File: ../src/cfg_win.tcl
mcset es {Goes to previous row of query results grid
or table data preview grid row in Form View.} {Va a la fila anterior de la rejilla de resultados de consulta
o de la rejilla de previsualización de datos en la Vista de Formulario.}

### File: ../src/cfg_win.tcl
mcset es {Go to next row in Form View} {Ir a la siguiente fila en la Vista de Formulario}

### File: ../src/cfg_win.tcl
mcset es {Goes to next row of query results grid
or table data preview grid row in Form View.} {Va a la siguiente fila de la rejilla de resultados de consulta
o de la rejilla de previsualización de datos en la Vista de Formulario.}

### File: ../src/cfg_win.tcl
mcset es {Jump to last row in Form View} {Saltar a la última fila de la Vista de Formulario}

### File: ../src/cfg_win.tcl
mcset es {Jumps to last row of query results grid
or table data preview grid in Form View.} {Salta a la última fila de la rejilla de resultados de consulta
o de la rejilla de previsualización de datos en la Vista de Formulario.}

### File: ../src/cfg_win.tcl
mcset es {Switch NULL value in form edit field} {Switch NULL value in form edit field}

### File: ../src/cfg_win.tcl
mcset es {Sets or unsets NULL value in currently selected
column in form view data edit mode.} {Sets or unsets NULL value in currently selected
column in form view data edit mode.}

### File: ../src/cfg_win.tcl
mcset es Plugins Plugins

### File: ../src/cfg_win.tcl
mcset es {SQL formatter plugins} {SQL formatter plugins}

### File: ../src/cfg_win.tcl
mcset es {Use following SQL formatter plugin:} {Usar el siguiente complemento para dar formato al SQL:}

### File: ../src/cfg_win.tcl
mcset es {Configure formatter plugin} {Configurar el complemento para dar formato}

### File: ../src/cfg_win.tcl
mcset es Configure Configurar

### File: ../src/cfg_win.tcl
mcset es {Populating plugins} {Populating plugins}

### File: ../src/cfg_win.tcl
mcset es {Default table populating plugin:} {Complemento por defecto para rellenar tabla:}

### File: ../src/cfg_win.tcl
mcset es Miscellaneous Miscelánea

### File: ../src/cfg_win.tcl
mcset es {Restore session after next start} {Restaurar sesión después de la siguiente ejecución}

### File: ../src/cfg_win.tcl
mcset es {All windows and their contents (such as SQL code)
will be restored while next application startup.} {Todas las ventanas y su contenido (como código SQL)
serán restauradas en el siguiente inicio de la aplicación.}

### File: ../src/cfg_win.tcl
mcset es {Show line numbers in SQL editor} {Mostrar números de línea en el editor SQL}

### File: ../src/cfg_win.tcl
mcset es {All SQL editor windows will contain line numbers on the left side of window.} {Todas las ventanas del editor SQL contendrán los números de línea en la parte izquierda de la ventana.}

### File: ../src/cfg_win.tcl
mcset es {Underline syntax errors in SQL editor} {Underline syntax errors in SQL editor}

### File: ../src/cfg_win.tcl
mcset es {Makes errors to be marked with underline.
You can also define foreground and background color for errors.} {Makes errors to be marked with underline.
You can also define foreground and background color for errors.}

### File: ../src/cfg_win.tcl
mcset es {Show SQLite system tables and indexes in databases tree} {Show SQLite system tables and indexes in databases tree}

### File: ../src/cfg_win.tcl
mcset es {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.} {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.}

### File: ../src/cfg_win.tcl
mcset es {Open items with single mouse click in databases tree} {Open items with single mouse click in databases tree}

### File: ../src/cfg_win.tcl
mcset es {Items in database tree are open by double click by default.
This option switches it to single click.} {Items in database tree are open by double click by default.
This option switches it to single click.}

### File: ../src/cfg_win.tcl
mcset es {Show ROWID as default instead of row order number in table data view} {Show ROWID as default instead of row order number in table data view}

### File: ../src/cfg_win.tcl
mcset es {This option affects first column from the left on the data tab of the table window.} {This option affects first column from the left on the data tab of the table window.}

### File: ../src/cfg_win.tcl
mcset es {Do not show 'did you know that...' dialog at startup.} {No mostrar la ventana de 'Sugerencias y trucos' en el inicio.}

### File: ../src/cfg_win.tcl
mcset es {Uncheck this option to show the dialog.} {Desmarcar esta opción para mostrar la ventana.}

### File: ../src/cfg_win.tcl
mcset es {Check for updates at startup.} {Check for updates at startup.}

### File: ../src/cfg_win.tcl
mcset es {If enabled, application will will check
for new version available at startup.} {If enabled, application will will check
for new version available at startup.}

### File: ../src/cfg_win.tcl
mcset es {Sort custom SQL functions list by name} {Ordenar lista de funciones SQL personalizadas por nombre}

### File: ../src/cfg_win.tcl
mcset es {This list is placed in Custom SQL funcions dialog.} {Esta lista está situada en la ventana de Funciones SQL Personalizadas.}

### File: ../src/cfg_win.tcl
mcset es {Select all contents when editing the table cell} {Select all contents when editing the table cell}

### File: ../src/cfg_win.tcl
mcset es {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.} {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.}

### File: ../src/cfg_win.tcl
mcset es {Ask if clipboard contents should be cut} {Ask if clipboard contents should be cut}

### File: ../src/cfg_win.tcl
mcset es {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.} {Si se habilita, entonces la aplicación preguntará al usuario si desea
cortar el portapapeles al pegar,
en caso de no se ajuste a la rejilla.
Si no se habilita, entonces la aplicación cortará
los contenidos sin preguntar.}

### File: ../src/cfg_win.tcl
mcset es {Rows per page in Table Window and Editor Results:} {Rows per page in Table Window and Editor Results:}

### File: ../src/cfg_win.tcl
mcset es {More results per page causes slower loading of single data page. Value 1000 should be right.} {Más resultados por página provocarán mayor lentitud al cargar una única página de datos. Un valor de 1000 debería estar bien.}

### File: ../src/cfg_win.tcl
mcset es {History entries limit:} {Límite de entradas en el Historial:}

### File: ../src/cfg_win.tcl
mcset es {Number of rows to remember in SQL editor history.} {Número de filas a recordar en el historial del editor SQL.}

### File: ../src/cfg_win.tcl
mcset es {Insertion cursor blinking period (milliseconds):} {Insertion cursor blinking period (milliseconds):}

### File: ../src/cfg_win.tcl
mcset es {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.} {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.}

### File: ../src/cfg_win.tcl
mcset es {Web browser:} {Navegador Web:}

### File: ../src/cfg_win.tcl
mcset es {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.} {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.}

### File: ../src/cfg_win.tcl
mcset es Language: Idioma:

### File: ../src/cfg_win.tcl
mcset es {Tab in table window on open:} {Pestaña en la ventana de Tabla al abrir:}

### File: ../src/cfg_win.tcl
mcset es {Table structure} {Estructura de la Tabla}

### File: ../src/cfg_win.tcl
mcset es {Table data} {Datos de la Tabla}

### File: ../src/cfg_win.tcl
mcset es {Select which tab should be opened for start in table window,
when you just opened that window.} {Seleccionar que pestaña debe ser abierta en el inicio en la ventana de Tabla,
cuando sólo habras esa ventana.}

### File: ../src/cfg_win.tcl
mcset es {View default display mode:} {View default display mode:}

### File: ../src/cfg_win.tcl
mcset es {Edition dialog} {Edition dialog}

### File: ../src/cfg_win.tcl
mcset es {Data view} {Data view}

### File: ../src/cfg_win.tcl
mcset es {Defines what is displayed by default when user opens a view.} {Defines what is displayed by default when user opens a view.}

### File: ../src/cfg_win.tcl
mcset es {Editor window results layout} {Editor window results layout}

### File: ../src/cfg_win.tcl
mcset es {Show results in separated tab} {Show results in separated tab}

### File: ../src/cfg_win.tcl
mcset es {Show results in frame below query} {Show results in frame below query}

### File: ../src/cfg_win.tcl
mcset es {Database tree display mode} {Database tree display mode}

### File: ../src/cfg_win.tcl
mcset es {Show indexes and triggers linked under referenced table.} {Show indexes and triggers linked under referenced table.}

### File: ../src/cfg_win.tcl
mcset es {Show indexes and triggers in their own groups.} {Show indexes and triggers in their own groups.}

### File: ../src/cfg_win.tcl
mcset es {Show column names linked under the table.} {Show column names linked under the table.}

### File: ../src/cfg_win.tcl
mcset es {Plain text results} {Plain text results}

### File: ../src/cfg_win.tcl
mcset es {Display NULL values as:} {Display NULL values as:}

### File: ../src/cfg_win.tcl
mcset es {Maximum column width:} {Maximum column width:}

### File: ../src/cfg_win.tcl
mcset es {Values longer than specified here will be cut in plain text results.} {Values longer than specified here will be cut in plain text results.}

### File: ../src/cfg_win.tcl
mcset es Colors Colores

### File: ../src/cfg_win.tcl
mcset es {Global colors} {Colores globales}

### File: ../src/cfg_win.tcl
mcset es {MDI windows title bar background color} {Color de fondo de la barra de título de ventanas MDI}

### File: ../src/cfg_win.tcl
mcset es {MDI windows title bar foreground color} {Color de frente de la barra de título de las ventanas MDI}

### File: ../src/cfg_win.tcl
mcset es {MDI windows title bar button background color} {Color de fondo del botón de la barra de título de las ventanas MDI}

### File: ../src/cfg_win.tcl
mcset es {MDI windows title bar active button background color} {Color de frente del botón de la barra de titulo de las ventanas MDI}

### File: ../src/cfg_win.tcl
mcset es {SQL Editor} {Editor SQL}

### File: ../src/cfg_win.tcl
mcset es {Editor standard font color} {Color de tipografía estándar del Editor}

### File: ../src/cfg_win.tcl
mcset es {Editor background} {Color de fondo del Editor}

### File: ../src/cfg_win.tcl
mcset es {Selected foreground color} {Color de frente para selección}

### File: ../src/cfg_win.tcl
mcset es {Selected background color} {Color de fondo para selección}

### File: ../src/cfg_win.tcl
mcset es {Disabled background color} {Color de fondo para Inactivo}

### File: ../src/cfg_win.tcl
mcset es {Tables color} {Color para Tablas}

### File: ../src/cfg_win.tcl
mcset es {Brackets color} {Color para Paréntesis}

### File: ../src/cfg_win.tcl
mcset es {Square brackets color} {Color para paréntesis cuadrados}

### File: ../src/cfg_win.tcl
mcset es {Keywords color} {Color para palabras clave}

### File: ../src/cfg_win.tcl
mcset es {Variables color} {Color para Variables}

### File: ../src/cfg_win.tcl
mcset es {Strings color} {Color para cadenas}

### File: ../src/cfg_win.tcl
mcset es {Comments color} {Color para comentarios}

### File: ../src/cfg_win.tcl
mcset es {Matched brackets foreground color} {Color de frente para paréntesis coincidentes}

### File: ../src/cfg_win.tcl
mcset es {Matched brackets background color} {Color de fondo para paréntesis coincidentes}

### File: ../src/cfg_win.tcl
mcset es {Syntax error color} {Syntax error color}

### File: ../src/cfg_win.tcl
mcset es {Tcl editor} {Editor Tcl}

### File: ../src/cfg_win.tcl
mcset es {Options color} {Color para opciones}

### File: ../src/cfg_win.tcl
mcset es {Quoted character color} {Quoted character color}

### File: ../src/cfg_win.tcl
mcset es {Trees colors} {Color para árboles}

### File: ../src/cfg_win.tcl
mcset es {Tree background} {Color de fondo para árbol}

### File: ../src/cfg_win.tcl
mcset es {Tree standard font color} {Color de tipografía estandar para el Árbol}

### File: ../src/cfg_win.tcl
mcset es {Tree selected background color} {Color de fondo para árbol seleccionado}

### File: ../src/cfg_win.tcl
mcset es {Tree selected foreground color} {Color de frente para árbol seleccionado}

### File: ../src/cfg_win.tcl
mcset es {Color for number of objects in tree branch} {Color para número de objetos en la rama del árbol}

### File: ../src/cfg_win.tcl
mcset es {Grids colors} {Colores para Rejillas}

### File: ../src/cfg_win.tcl
mcset es {Grid background} {Fondo de la rejilla}

### File: ../src/cfg_win.tcl
mcset es {Grid standard font color} {Color de tipografía estandar para la Rejilla}

### File: ../src/cfg_win.tcl
mcset es {Grid selected background color} {Color de fondo para rejilla seleccionada}

### File: ../src/cfg_win.tcl
mcset es {Grid selected foreground color} {Color de frente para rejilla seleccionada}

### File: ../src/cfg_win.tcl
mcset es {Grid base column background color} {Color de fondo para la Columna base de la rejilla}

### File: ../src/cfg_win.tcl
mcset es {Foreground color for cells with NULL value} {Color de frente para las celdas con valor NULO}

### File: ../src/cfg_win.tcl
mcset es {Status fields colors} {Colores para campos de estado}

### File: ../src/cfg_win.tcl
mcset es {Background color} {Color de fondo}

### File: ../src/cfg_win.tcl
mcset es {Foreground color} {Color de frente}

### File: ../src/cfg_win.tcl
mcset es {Error foreground color} {Color de frente para Error}

### File: ../src/cfg_win.tcl
mcset es {Information foreground color} {Color de frente para información}

### File: ../src/cfg_win.tcl
mcset es {Information (second kind) foreground color} {Color de frente para información (segundo tipo)}

### File: ../src/cfg_win.tcl
mcset es {Miscellaneous colors} {Colores extra}

### File: ../src/cfg_win.tcl
mcset es {Context hints background color} {Color de fondo para Sugerencias de contexto}

### File: ../src/cfg_win.tcl
mcset es {Context hints foreground color} {Color de frente para Sugerencias de contexto}

### File: ../src/cfg_win.tcl
mcset es Fonts Tipografías

### File: ../src/cfg_win.tcl
mcset es {SQL editor font} {Tipografía para el editor SQL}

### File: ../src/cfg_win.tcl
mcset es {Status fields font} {Tipografía para los campos de estado}

### File: ../src/cfg_win.tcl
mcset es {Grid font} {Tipografía para la rejilla}

### File: ../src/cfg_win.tcl
mcset es {Tree font} {Tipografía para árboles}

### File: ../src/cfg_win.tcl
mcset es {Tree additional labels font} {Tipografía para etiquetas adicionales de árboles}

### File: ../src/cfg_win.tcl
mcset es {Context hints font} {Tipografía para Sugerencias de contexto}

### File: ../src/cfg_win.tcl
mcset es {Changed language needs application to be restarted.} {Cambiar el idioma requiere que la aplicación sea reiniciada.}

### File: ../src/cfg_win.tcl
mcset es {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.} {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.}

### File: ../src/cfg_win.tcl
mcset es {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.} {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.}

### File: ../src/cfg_win.tcl
mcset es {SQL formatter options} {Opciones para el formateador de SQL}

### File: ../src/db/db_file_types.tcl
mcset es {All SQLite Databases} {Todas las Bases de Datos SQLite}

### File: ../src/db/db_file_types.tcl
mcset es {SQLite 3 Databases} {Bases de Datos SQLite 3}

### File: ../src/db/db_file_types.tcl
mcset es {SQLite 2 Databases} {Bases de Datos SQLite 2}

### File: ../src/db/db_file_types.tcl
mcset es {All files} {Todos los archivos}

### File: ../src/db/query_executor.tcl
mcset es {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.} {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.}

### File: ../src/db/query_executor.tcl
mcset es {Invalid database name: %s} {Invalid database name: %s}

### File: ../src/db/query_executor.tcl
mcset es {Imbalanced 'BEGIN' ocurrence in query.} {Imbalanced 'BEGIN' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset es {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.} {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset es {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.} {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset es {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.} {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset es {Cannot use more than one 'BEGIN'.} {Cannot use more than one 'BEGIN'.}

### File: ../src/db/query_executor.tcl
mcset es {Imbalanced 'COMMIT' ocurrence in query.} {Imbalanced 'COMMIT' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset es {Imbalanced 'ROLLBACK' ocurrence in query.} {Imbalanced 'ROLLBACK' ocurrence in query.}

### File: ../src/db/sqlite2.tcl
mcset es {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)} {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)}

### File: ../src/db/db.tcl
mcset es {An internal logic error in SQLite} {An internal logic error in SQLite}

### File: ../src/db/db.tcl
mcset es {Access permission denied} {Access permission denied}

### File: ../src/db/db.tcl
mcset es {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.} {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.}

### File: ../src/db/db.tcl
mcset es {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.} {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.}

### File: ../src/db/db.tcl
mcset es {A malloc() failed} {A malloc() failed}

### File: ../src/db/db.tcl
mcset es {Attempt to write a readonly database} {Attempt to write a readonly database}

### File: ../src/db/db.tcl
mcset es {Disk I/O error occurred} {Disk I/O error occurred}

### File: ../src/db/db.tcl
mcset es {The database disk image is malformed} {The database disk image is malformed}

### File: ../src/db/db.tcl
mcset es {Database is full} {Database is full}

### File: ../src/db/db.tcl
mcset es {Unable to open the database file} {Unable to open the database file}

### File: ../src/db/db.tcl
mcset es {Database lock protocol error} {Database lock protocol error}

### File: ../src/db/db.tcl
mcset es {Database is empty} {Database is empty}

### File: ../src/db/db.tcl
mcset es {The database schema changed} {The database schema changed}

### File: ../src/db/db.tcl
mcset es {String or BLOB exceeds size limit} {String or BLOB exceeds size limit}

### File: ../src/db/db.tcl
mcset es {Library used incorrectly} {Library used incorrectly}

### File: ../src/db/db.tcl
mcset es {Uses OS features not supported on host} {Uses OS features not supported on host}

### File: ../src/db/db.tcl
mcset es {Authorization denied} {Authorization denied}

### File: ../src/db/db.tcl
mcset es {Auxiliary database format error} {Auxiliary database format error}

### File: ../src/db/db.tcl
mcset es {2nd parameter to sqlite3_bind out of range} {2nd parameter to sqlite3_bind out of range}

### File: ../src/db/db.tcl
mcset es {File opened that is not a database file} {File opened that is not a database file}

### File: ../src/db/db.tcl
mcset es {Error while opening %s database:
%s} {Error abriendo Base de Datos %s:
%s}

### File: ../src/db/db.tcl
mcset es {Not enough parameters passed to function '%s'.} {Parámetros insuficientes pasados a la función '%s'.}

### File: ../src/db/db.tcl
mcset es {Cannot read file: %s} {No se puede leer el archivo: %s}

### File: ../src/db/db.tcl
mcset es {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.} {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.}

### File: ../src/db/db.tcl
mcset es {Could not attach database %s. Error message from SQLite:
%s} {Could not attach database %s. Error message from SQLite:
%s}

### File: ../src/db/db.tcl
mcset es {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.} {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.}

### File: ../src/db/sqlite3.tcl
mcset es {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)} {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)}

### File: ../src/completion_routines.tcl
mcset es {Problem with attaching database:
%s} {Problem with attaching database:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset es {Error from importing plugin:
%s} {Error from importing plugin:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset es {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset es {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset es {Error creating table '%s':
%s

Importing aborted.} {Error creating table '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset es {Error trying to import data to '%s':
%s

Importing aborted.} {Error trying to import data to '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset es Importing... Importing...

### File: ../src/plugins/import_plugin.tcl
mcset es {Importing to table '%s'.} {Importing to table '%s'.}

### File: ../src/plugins/import_plugin.tcl
mcset es {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?} {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset es {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?} {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset es {Problem occured while importing row number %s:
%s

What would you like to do?} {Problem occured while importing row number %s:
%s

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset es {Importing finished.} {Importing finished.}

### File: ../src/plugins/import_plugin.tcl
mcset es {Import problem} {Import problem}

### File: ../src/plugins/import_plugin.tcl
mcset es {Skip this data row} {Skip this data row}

### File: ../src/plugins/import_plugin.tcl
mcset es {Keep data rows imported so far (%s) and abort} {Keep data rows imported so far (%s) and abort}

### File: ../src/plugins/import_plugin.tcl
mcset es {Rollback data rows imported so far and abort} {Rollback data rows imported so far and abort}

### File: ../src/plugins/import_plugin.tcl
mcset es {Ignore it and proceed} {Ignore it and proceed}

### File: ../src/plugins/import_plugin.tcl
mcset es Abort Abortar

### File: ../src/plugins/sql_formatting/enterprise/format_s.tcl
mcset es name name

### File: ../src/plugins/sql_formatting/basic.tcl
mcset es {Reduce group of whitespaces into one whitespace.} {Reducir grupo de espacios en blanco a un solo espacio en blanco.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset es {Uppercase keywords.} {Poner en Mayúsculas las palabras clave.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset es {Separate ")" and after contents with single whitespace.} {Separar ")" y después de contenidos con un solo espacio en blanco.}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {SQLite3 only} {SQLite3 only}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es Indentation Indentation

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {New lines} {New lines}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {White spaces} {White spaces}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es Names Names

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es Comments Comments

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Tab size:} {Tab size:}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Line up keywords in multi-line queries} {Line up keywords in multi-line queries}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Ident contents of parenthesis block} {Ident contents of parenthesis block}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Ident parenthesis block in new line} {Ident parenthesis block in new line}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Before opening parenthesis in column definitions} {Before opening parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After opening parenthesis in column definitions} {After opening parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Before closinging parenthesis in column definitions} {Before closinging parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After closinging parenthesis in column definitions} {After closinging parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Before opening parenthesis in expressions} {Before opening parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After opening parenthesis in expressions} {After opening parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Before closinging parenthesis in expressions} {Before closinging parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After closinging parenthesis in expressions} {After closinging parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After comma} {After comma}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After comma in function arguments list} {After comma in function arguments list}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After logical block of query} {After logical block of query}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After semicolon} {After semicolon}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Never before semicolon} {Never before semicolon}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Before comma in lists} {Before comma in lists}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After comma in lists} {After comma in lists}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Before opening parenthesis} {Before opening parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After opening parenthesis} {After opening parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Before closing parenthesis} {Before closing parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After closing parenthesis} {After closing parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Before dot operator (in path to database object)} {Before dot operator (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After dot operator (in path to database object)} {After dot operator (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Before mathematical operator} {Before mathematical operator}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {After mathematical operator} {After mathematical operator}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Uppercase keywords} {Uppercase keywords}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Uppercase datatype names} {Uppercase datatype names}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Always use name wrapping} {Always use name wrapping}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Preferred name wrapper} {Preferred name wrapper}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Expand one line comments (/* ... */) to multiline} {Expand one line comments (/* ... */) to multiline}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Indent multi line comments} {Indent multi line comments}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset es {Use "*" character for each line} {Use "*" character for each line}

### File: ../src/plugins/import/csv.tcl
mcset es {, (comma)} {, (coma)}

### File: ../src/plugins/import/csv.tcl
mcset es {; (semicolon)} {; (punto y coma)}

### File: ../src/plugins/import/csv.tcl
mcset es {\t (tab)} {\t (tabulador)}

### File: ../src/plugins/import/csv.tcl
mcset es {  (white-space)} {  (espacio-en-blanco)}

### File: ../src/plugins/import/csv.tcl
mcset es Custom Personalizar

### File: ../src/plugins/import/csv.tcl
mcset es {Input file} {Input file}

### File: ../src/plugins/import/csv.tcl
mcset es Browse Explorar

### File: ../src/plugins/import/csv.tcl
mcset es {Show options} {Show options}

### File: ../src/plugins/import/csv.tcl
mcset es {Column names} {Column names}

### File: ../src/plugins/import/csv.tcl
mcset es {Treat first row as column names} {Treat first row as column names}

### File: ../src/plugins/import/csv.tcl
mcset es {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.} {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.}

### File: ../src/plugins/import/csv.tcl
mcset es {Columns separator:} {Separador de columnas:}

### File: ../src/plugins/import/csv.tcl
mcset es {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.} {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.}

### File: ../src/plugins/import/csv.tcl
mcset es {NULL handling} {NULL handling}

### File: ../src/plugins/import/csv.tcl
mcset es {Treat following values as NULL:} {Treat following values as NULL:}

### File: ../src/plugins/import/csv.tcl
mcset es Workarounds Workarounds

### File: ../src/plugins/import/csv.tcl
mcset es {Expect Microsoft format of CSV} {Expect Microsoft format of CSV}

### File: ../src/plugins/import/csv.tcl
mcset es {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.} {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.}

### File: ../src/plugins/import/csv.tcl
mcset es Encoding Encoding

### File: ../src/plugins/import/csv.tcl
mcset es {Convert from encoding:} {Convert from encoding:}

### File: ../src/plugins/import/csv.tcl
mcset es {Input file cannot be empty.} {Input file cannot be empty.}

### File: ../src/plugins/import/csv.tcl
mcset es {Input file is not readable.} {Input file is not readable.}

### File: ../src/plugins/import/csv.tcl
mcset es {CSV separator cannot be empty.} {El separador CSV no puede estar vacío.}

### File: ../src/plugins/import/csv.tcl
mcset es {CSV files} {CSV files}

### File: ../src/plugins/import/csv.tcl
mcset es {Text files} {Text files}

### File: ../src/plugins/import/csv.tcl
mcset es {File to import from} {File to import from}

### File: ../src/plugins/import/dbf.tcl
mcset es Auto-detect Auto-detect

### File: ../src/plugins/import/dbf.tcl
mcset es {dBase files} {dBase files}

### File: ../src/plugins/import/regexp.tcl
mcset es {Regular expression} {Regular expression}

### File: ../src/plugins/import/regexp.tcl
mcset es {Visual editor} {Visual editor}

### File: ../src/plugins/import/regexp.tcl
mcset es {Use Regular Expression Groups to identify columns.} {Use Regular Expression Groups to identify columns.}

### File: ../src/plugins/import/regexp.tcl
mcset es {Case insensitive} {Case insensitive}

### File: ../src/plugins/import/regexp.tcl
mcset es Help Help

### File: ../src/plugins/import/regexp.tcl
mcset es {RegExp error:
%s} {RegExp error:
%s}

### File: ../src/plugins/export/xls.tcl
mcset es {Column names as first row} {Nombres de Columna como primera fila}

### File: ../src/plugins/export/xls.tcl
mcset es {If enabled, then first row of exported document will be a list of column names.} {If enabled, then first row of exported document will be a list of column names.}

### File: ../src/plugins/export/xls.tcl
mcset es Encoding: Encoding:

### File: ../src/plugins/export/plain.tcl
mcset es {Export NULL values as:} {Exportar valores NULOS como:}

### File: ../src/plugins/export/plain.tcl
mcset es {Fixed column width:} {Fixed column width:}

### File: ../src/plugins/export/plain.tcl
mcset es {Database: %s (%s, %s)} {Database: %s (%s, %s)}

### File: ../src/plugins/export/plain.tcl
mcset es {Table: %s} {Tabla: %s}

### File: ../src/plugins/export/plain.tcl
mcset es {Index: %s} {Índice: %s}

### File: ../src/plugins/export/plain.tcl
mcset es {Trigger: %s} {Disparador: %s}

### File: ../src/plugins/export/plain.tcl
mcset es {View: %s} {Vista: %s}

### File: ../src/plugins/export/csv.tcl
mcset es {If enabled, then first row of exported CSV will be a list of column names.} {If enabled, then first row of exported CSV will be a list of column names.}

### File: ../src/plugins/export/csv.tcl
mcset es {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.} {Carácter usado para separar cada columna de datos
de otra. Si el separador aparece en alguna columna de datos,
entonces el valor será encerrado entre comillas.
Cada valor de carácter de comillas será remplazado por dos comillas.}

### File: ../src/plugins/export/json.tcl
mcset es {Indented lines} {Indented lines}

### File: ../src/plugins/export/json.tcl
mcset es {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.} {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.}

### File: ../src/plugins/export/json.tcl
mcset es {Align lines} {Align lines}

### File: ../src/plugins/export/json.tcl
mcset es {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.} {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.}

### File: ../src/plugins/export/json.tcl
mcset es {Each row as object} {Each row as object}

### File: ../src/plugins/export/json.tcl
mcset es {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.} {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.}

### File: ../src/plugins/export/xml.tcl
mcset es {No extra white-spaces or new lines} {Sin espacios en blanco extras o nuevas líneas}

### File: ../src/plugins/export/xml.tcl
mcset es {XML tags will be places char-by-char, without any extra white-spaces.} {Las etiquetas XML serán colocadas carácter-a-carácter, sin ningún epacio en blanco extra.}

### File: ../src/plugins/export/xml.tcl
mcset es {Format output to be human readable} {Formato de salida legible para humanos}

### File: ../src/plugins/export/xml.tcl
mcset es {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.} {Cada etiqueta será colocada en una nueva línea y todo el documento será justificado para ser más legible en un editor de texto.}

### File: ../src/plugins/export/xml.tcl
mcset es {Generate XSD file} {Generate XSD file}

### File: ../src/plugins/export/xml.tcl
mcset es {Generates XML Schema Definition file using
export file name and extension *.xsd.} {Genera un archivo de definición de esquema XML usando
el nombre de archivo a exportar y la extensión *.xsd.}

### File: ../src/plugins/export/xml.tcl
mcset es {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s} {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s}

### File: ../src/plugins/export/html.tcl
mcset es {First row of exported data will be header
with names of columns, just like in results grid.} {La primera fila de los datos exportados será el encabezado
con los nombres de las columnas, justo como en la rejilla de resultados.}

### File: ../src/plugins/export/html.tcl
mcset es {Row numbers as first column} {Números de fila como primera Columna}

### File: ../src/plugins/export/html.tcl
mcset es {First column of exported data
will contain row order number.} {First column of exported data
will contain row order number.}

### File: ../src/plugins/export/html.tcl
mcset es {Full column names} {Nombres de Columna completos}

### File: ../src/plugins/export/html.tcl
mcset es {Column names in header will be prepended with "table_name." prefix.} {Column names in header will be prepended with "table_name." prefix.}

### File: ../src/plugins/export/html.tcl
mcset es {Show types} {Mostrar tipos}

### File: ../src/plugins/export/html.tcl
mcset es {Column headers will contain data types.} {Los encabezados de Columna contendrán el tipo de los datos.}

### File: ../src/plugins/export/html.tcl
mcset es {no type} {sin tipo}

### File: ../src/plugins/export/html.tcl
mcset es {For table:} {Para la Tabla:}

### File: ../src/plugins/export/html.tcl
mcset es Unique: Único:

### File: ../src/plugins/export/html.tcl
mcset es Yes Si

### File: ../src/plugins/export/html.tcl
mcset es No No

### File: ../src/plugins/export/html.tcl
mcset es Column Columna

### File: ../src/plugins/export/html.tcl
mcset es Collating Cotejar

### File: ../src/plugins/export/html.tcl
mcset es {Sort order} Orden

### File: ../src/plugins/export/html.tcl
mcset es Activated: Activada:

### File: ../src/plugins/export/html.tcl
mcset es Action: Acción:

### File: ../src/plugins/export/html.tcl
mcset es {Activate condition:} {Activar condición:}

### File: ../src/plugins/export/html.tcl
mcset es {Code executed:} {Código ejecutado:}

### File: ../src/plugins/export/html.tcl
mcset es {Exported database: %s} {Base de datos exportada: %s}

### File: ../src/plugins/export/html.tcl
mcset es {Generated on %s with %s} {Generados en %s con %s}

### File: ../src/plugins/export/html.tcl
mcset es {Exported table: %s} {Tabla exportada: %s}

### File: ../src/plugins/export/html.tcl
mcset es {Results of SQL query} {Resultados de la consulta SQL}

### File: ../src/plugins/export/dbf.tcl
mcset es {Cannot overwrite file '%s'.} {Cannot overwrite file '%s'.}

### File: ../src/plugins/export/sql.tcl
mcset es {Name of table for exported data:} {Nombre de la tabla para datos exportados:}

### File: ../src/plugins/export/sql.tcl
mcset es {Include "CREATE TABLE" statement at the begining.} {Include "CREATE TABLE" statement at the begining.}

### File: ../src/plugins/export/sql.tcl
mcset es {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.} {Los resultados de una consulta exportados a INSERTs de SQL deben estar definidos
para alguna tabla. Esto es el nombre de esa tabla.}

### File: ../src/plugins/export/sql.tcl
mcset es {Include table declaration} {Incluir declaración de tabla}

### File: ../src/plugins/export/sql.tcl
mcset es {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.} {Si se habilita, entonces DDL tabla (CREATE TABLE)
será incluido en el SQL exportado.}

### File: ../src/plugins/export/sql.tcl
mcset es {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.} {Necesitas configurar un nombre de tabla para exportar ls resultados de la consulta a SQL.
SQL INSERTs requieren un nombre de tabla en su sintaxis.}

### File: ../src/plugins/export/pdf.tcl
mcset es Dimensions Dimensions

### File: ../src/plugins/export/pdf.tcl
mcset es {Paper size:} {Paper size:}

### File: ../src/plugins/export/pdf.tcl
mcset es {Margin size:} {Margin size:}

### File: ../src/plugins/export/pdf.tcl
mcset es {Cell padding:} {Cell padding:}

### File: ../src/plugins/export/pdf.tcl
mcset es {Limit amount of data bytes in single cell to:} {Limit amount of data bytes in single cell to:}

### File: ../src/plugins/export/pdf.tcl
mcset es {Font size:} {Font size:}

### File: ../src/plugins/export/pdf.tcl
mcset es {Built-in font} {Built-in font}

### File: ../src/plugins/export/pdf.tcl
mcset es Font: Font:

### File: ../src/plugins/export/pdf.tcl
mcset es {TrueType font} {TrueType font}

### File: ../src/plugins/export/pdf.tcl
mcset es {Font file:} {Font file:}

### File: ../src/plugins/export/pdf.tcl
mcset es {Font encoding:} {Font encoding:}

### File: ../src/plugins/export/pdf.tcl
mcset es {Columns and rows} {Columns and rows}

### File: ../src/plugins/export/pdf.tcl
mcset es {Header background} {Header background}

### File: ../src/plugins/export/pdf.tcl
mcset es {Empty space} {Empty space}

### File: ../src/plugins/export/pdf.tcl
mcset es {Fill empty space in cells} {Fill empty space in cells}

### File: ../src/plugins/export/pdf.tcl
mcset es {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.} {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.}

### File: ../src/plugins/export/pdf.tcl
mcset es {Minimum height of empty space to fill:} {Minimum height of empty space to fill:}

### File: ../src/plugins/export/pdf.tcl
mcset es {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.} {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.}

### File: ../src/plugins/export/pdf.tcl
mcset es {Empty space background} {Empty space background}

### File: ../src/plugins/export/pdf.tcl
mcset es {TTF Fonts} {TTF Fonts}

### File: ../src/plugins/export/pdf.tcl
mcset es {All Files} {All Files}

### File: ../src/plugins/export/pdf.tcl
mcset es {Open TTF font} {Open TTF font}

### File: ../src/plugins/populating/random.tcl
mcset es {Include alpha characters} {Incluir caracteres alfabéticos}

### File: ../src/plugins/populating/random.tcl
mcset es {Include numeric characters} {Incluir caracteres numéricos}

### File: ../src/plugins/populating/random.tcl
mcset es {Include whitespace characters} {Incluir espacios en blanco}

### File: ../src/plugins/populating/random.tcl
mcset es {Include binary characters} {Incluir caracteres binarios}

### File: ../src/plugins/populating/random.tcl
mcset es {Minimum length:} {Longitud mínima:}

### File: ../src/plugins/populating/random.tcl
mcset es {Maximum length:} {Longitud máxima:}

### File: ../src/plugins/populating/random_number.tcl
mcset es {Minimum value:} {Valor mínimo:}

### File: ../src/plugins/populating/random_number.tcl
mcset es {Maximum value:} {Valor máximo:}

### File: ../src/plugins/populating/random_number.tcl
mcset es {Constant prefix:} {Prefijo para constante:}

### File: ../src/plugins/populating/random_number.tcl
mcset es {Constant suffix:} {Sufijo para constante:}

### File: ../src/plugins/populating/sql.tcl
mcset es {Initialisation code} {Initialisation code}

### File: ../src/plugins/populating/sql.tcl
mcset es {Per iteration code} {Per iteration code}

### File: ../src/plugins/populating/sql.tcl
mcset es {Closing code} {Closing code}

### File: ../src/plugins/populating/constant.tcl
mcset es {Value to use:} {Valor a usar:}

### File: ../src/plugins/populating/sequence.tcl
mcset es {Start from:} {Empezar en:}

### File: ../src/plugins/populating/dictionary.tcl
mcset es {Dictionary file:} {Archivo de Diccionario:}

### File: ../src/plugins/populating/dictionary.tcl
mcset es {Dictionary words separator:} {Separador de palabras de diccionario:}

### File: ../src/plugins/populating/dictionary.tcl
mcset es Whitespace {Espacio en blanco}

### File: ../src/plugins/populating/dictionary.tcl
mcset es {Line break} {Salto de Línea}

### File: ../src/plugins/populating/dictionary.tcl
mcset es {Method of using words:} {Método para usar palabras:}

### File: ../src/plugins/populating/dictionary.tcl
mcset es Randomly Aleatoriamente

### File: ../src/plugins/populating/dictionary.tcl
mcset es Consecutively Consecutivamente

### File: ../src/plugins/populating/dictionary.tcl
mcset es {Dictionary file doesn't exist, or unreadable.} {El archivo de Diccionario no existe o no se puede leer.}

### File: ../src/plugins/populating/dictionary.tcl
mcset es {Dictionary file is empty!} {¡El archivo de Diccionario está vacío!}

### File: ../src/plugins/populating/dictionary.tcl
mcset es {Dictionary file} {Archivo de Diccionario}

### File: ../src/taskbar.tcl
mcset es Database: {Base de Datos:}

### File: ../src/taskbar.tcl
mcset es Table: Tabla:

### File: ../src/taskbar.tcl
mcset es {Type new name for a window} {Type new name for a window}

### File: ../src/taskbar.tcl
mcset es {Window with given name already exists. Please type other name.} {Window with given name already exists. Please type other name.}

### File: ../src/taskbar.tcl
mcset es {Type new name for a task} {Type new name for a task}

### File: ../src/taskbar.tcl
mcset es {Close selected window} {Cerrar ventana seleccionada}

### File: ../src/taskbar.tcl
mcset es {Close other windows} {Cerrar las otras ventanas}

### File: ../src/taskbar.tcl
mcset es {Close all windows} {Cerrar todas las ventanas}

### File: ../src/taskbar.tcl
mcset es {Restore last closed window} {Restore last closed window}

### File: ../src/taskbar.tcl
mcset es {Rename selected window} {Rename selected window}

### File: ../src/windows/table_win.tcl
mcset es Structure Estructura

### File: ../src/windows/table_win.tcl
mcset es Data Datos

### File: ../src/windows/table_win.tcl
mcset es Constraints Restricciones

### File: ../src/windows/table_win.tcl
mcset es Indexes Índices

### File: ../src/windows/table_win.tcl
mcset es Triggers Disparadores

### File: ../src/windows/table_win.tcl
mcset es {Grid view} {Vista de Rejilla}

### File: ../src/windows/table_win.tcl
mcset es {Form view} {Vista de Formulario}

### File: ../src/windows/table_win.tcl
mcset es {Refresh table columns and DDL (%s)} {Actualizar las Columnas de la Tabla y DDL (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Edit table (%s)} {Edit table (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Export table data (%s)} {Export table data (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Import data to table (%s)} {Import data to table (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Populate table (%s)} {Populate table (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Create similar table} {Create similar table}

### File: ../src/windows/table_win.tcl
mcset es {Refresh table data (%s)} {Actualizar datos de la Tabla (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Add custom number of rows} {Add custom number of rows}

### File: ../src/windows/table_win.tcl
mcset es {Add new row (%s)} {Añadir nueva fila (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Delete selected row (%s)} {Eliminar fila seleccionada (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Commit changes (%s)} {Commit changes (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Rollback new row (%s)} {Rollback new row (%s)}

### File: ../src/windows/table_win.tcl
mcset es {First %s rows} {Primeras %s filas}

### File: ../src/windows/table_win.tcl
mcset es {Previous %s rows} {%s filas anteriores}

### File: ../src/windows/table_win.tcl
mcset es {Next %s rows} {%s filas siguientes}

### File: ../src/windows/table_win.tcl
mcset es {Last %s rows} {Últimas %s filas}

### File: ../src/windows/table_win.tcl
mcset es {Export table data} {Exportar datos de la Tabla}

### File: ../src/windows/table_win.tcl
mcset es {Import data to table} {Import data to table}

### File: ../src/windows/table_win.tcl
mcset es {Populate table} {Rellenar Tabla}

### File: ../src/windows/table_win.tcl
mcset es {Enter phrase you want to look for} {Introduce la frase que quieres buscar}

### File: ../src/windows/table_win.tcl
mcset es {Apply data filter} {Aplicar filtro de datos}

### File: ../src/windows/table_win.tcl
mcset es {Clear data filter} {Limpiar filtros de datos}

### File: ../src/windows/table_win.tcl
mcset es {Total rows: %s} {Filas totales: %s}

### File: ../src/windows/table_win.tcl
mcset es {Rollback changes (%s)} {Rollback changes (%s)}

### File: ../src/windows/table_win.tcl
mcset es {First row from data grid (%s)} {First row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Previous row from data grid (%s)} {Previous row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Next row from data grid (%s)} {Next row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Last row from data grid (%s)} {Last row from data grid (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Field switching mode.

Click it to make <Tab> key to insert tab characters.} {Field switching mode.

Click it to make <Tab> key to insert tab characters.}

### File: ../src/windows/table_win.tcl
mcset es {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.} {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.}

### File: ../src/windows/table_win.tcl
mcset es {Refresh table indexes (%s)} {Actualizar índices de la Tabla (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Create new index (%s)} {Crear nuevo índice (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Edit index (%s)} {Edit index (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Delete index (%s)} {Eliminar índice (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Refresh table triggers (%s)} {Actualizar Disparadores de la Tabla (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Create new trigger (%s)} {Crear nuevo Disparador (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Edit trigger (%s)} {Edit trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Delete trigger (%s)} {Eliminar Disparador (%s)}

### File: ../src/windows/table_win.tcl
mcset es {Constraint name} {Nombre de la restricción}

### File: ../src/windows/table_win.tcl
mcset es {Column name} {Nombre de la Columna}

### File: ../src/windows/table_win.tcl
mcset es Default {Por defecto}

### File: ../src/windows/table_win.tcl
mcset es {Not NULL} {No NULO}

### File: ../src/windows/table_win.tcl
mcset es {Primary key} {Clave Primaria}

### File: ../src/windows/table_win.tcl
mcset es Unique Único

### File: ../src/windows/table_win.tcl
mcset es Collate Cotejar

### File: ../src/windows/table_win.tcl
mcset es Check Comprobar

### File: ../src/windows/table_win.tcl
mcset es {Foreign key} {Clave foránea}

### File: ../src/windows/table_win.tcl
mcset es {Index name} {Nombre del índice}

### File: ../src/windows/table_win.tcl
mcset es {On column} {En Columna}

### File: ../src/windows/table_win.tcl
mcset es {SQL code} {Código SQL}

### File: ../src/windows/table_win.tcl
mcset es {Trigger name} {Nombre del Disparador}

### File: ../src/windows/table_win.tcl
mcset es {On table} {En Tabla}

### File: ../src/windows/table_win.tcl
mcset es Name Nombre

### File: ../src/windows/table_win.tcl
mcset es {Data type} {Tipo de Dato}

### File: ../src/windows/table_win.tcl
mcset es {Default value} {Valor por defecto}

### File: ../src/windows/table_win.tcl
mcset es {Refreshing dependencies} {Refreshing dependencies}

### File: ../src/windows/table_win.tcl
mcset es {Refreshing table columns...} {Refreshing table columns...}

### File: ../src/windows/table_win.tcl
mcset es {Refreshing table data...} {Refreshing table data...}

### File: ../src/windows/table_win.tcl
mcset es {Refreshing table indexes...} {Refreshing table indexes...}

### File: ../src/windows/table_win.tcl
mcset es {Refreshing table triggers...} {Refreshing table triggers...}

### File: ../src/windows/table_win.tcl
mcset es {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.} {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.}

### File: ../src/windows/table_win.tcl
mcset es {Check condition} {Comprobar condición}

### File: ../src/windows/table_win.tcl
mcset es {Total rows: %s (filtered)} {Total rows: %s (filtered)}

### File: ../src/windows/table_win.tcl
mcset es {Pending commits} {Pending commits}

### File: ../src/windows/table_win.tcl
mcset es {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?} {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?}

### File: ../src/windows/table_win.tcl
mcset es {Loading data...} {Loading data...}

### File: ../src/windows/table_win.tcl
mcset es {Loading table '%s'...} {Loading table '%s'...}

### File: ../src/windows/table_win.tcl
mcset es {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.} {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.}

### File: ../src/windows/table_win.tcl
mcset es {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.} {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.}

### File: ../src/windows/table_win.tcl
mcset es {Edit table} {Editar Tabla}

### File: ../src/windows/table_win.tcl
mcset es {Enter number of rows to add:} {Enter number of rows to add:}

### File: ../src/windows/table_win.tcl
mcset es {Add rows} {Add rows}

### File: ../src/windows/table_win.tcl
mcset es {New index} {Nuevo índice}

### File: ../src/windows/table_win.tcl
mcset es {Index '%s' has no DDL. Probably it's system index and should not be edited.} {Index '%s' has no DDL. Probably it's system index and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset es {Edit index} {Editar índice}

### File: ../src/windows/table_win.tcl
mcset es {Delete index} {Eliminar índice}

### File: ../src/windows/table_win.tcl
mcset es {Are you sure you want to delete '%s' index?} {¿Seguro que quieres eliminar el índice '%s'?}

### File: ../src/windows/table_win.tcl
mcset es {New trigger} {Nuevo Disparador}

### File: ../src/windows/table_win.tcl
mcset es {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.} {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset es {Edit trigger} {Editar Disparador}

### File: ../src/windows/table_win.tcl
mcset es {Delete trigger} {Eliminar Disparador}

### File: ../src/windows/table_win.tcl
mcset es {Are you sure you want to delete '%s' trigger?} {¿Seguro que quieres eliminar el Disparador '%s'?}

### File: ../src/windows/table_win.tcl
mcset es {Export table} {Exportar Tabla}

### File: ../src/windows/table_win.tcl
mcset es {Import data} {Import data}

### File: ../src/windows/editor_win.tcl
mcset es {SQL query} {Consulta SQL}

### File: ../src/windows/editor_win.tcl
mcset es Results Resultados

### File: ../src/windows/editor_win.tcl
mcset es History Historial

### File: ../src/windows/editor_win.tcl
mcset es {Execute query (%s)} {Ejecutar consulta (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Execute query with plain string results} {Ejecutar consulta con resultados como cadenas planas}

### File: ../src/windows/editor_win.tcl
mcset es {Explain query (%s)} {Explicar consulta (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Format SQL code (%s)} {Dar formato al código SQL (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Refresh syntax highlighting (%s)} {Actualizar resaltado de sintaxis (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Clear history} {Limpiar historial}

### File: ../src/windows/editor_win.tcl
mcset es {Export results} {Exportar resultados}

### File: ../src/windows/editor_win.tcl
mcset es {Create view from query} {Create view from query}

### File: ../src/windows/editor_win.tcl
mcset es {Execute SQL from file (%s)} {Execute SQL from file (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Load SQL from file (%s)} {Load SQL from file (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Save SQL to file (%s)} {Save SQL to file (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Default database for SQL executing
(%s/%s)} {Default database for SQL executing
(%s/%s)}

### File: ../src/windows/editor_win.tcl
mcset es Database {Base de Datos}

### File: ../src/windows/editor_win.tcl
mcset es {Execution date} {Fecha de ejecución}

### File: ../src/windows/editor_win.tcl
mcset es {Execution time (s)} {Tiempo de ejecución (s)}

### File: ../src/windows/editor_win.tcl
mcset es {Rows affected} {Filas afectadas}

### File: ../src/windows/editor_win.tcl
mcset es SQL SQL

### File: ../src/windows/editor_win.tcl
mcset es {Plain text view} {Plain text view}

### File: ../src/windows/editor_win.tcl
mcset es {Refresh results (%s)} {Refresh results (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Commit row (%s)} {Commit row (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Rollback row (%s)} {Rollback row (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Copy (%s)} {Copy (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Cut (%s)} {Cut (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Paste (%s)} {Paste (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Show line numbers} {Show line numbers}

### File: ../src/windows/editor_win.tcl
mcset es {Delete selected history entry (%s)} {Delete selected history entry (%s)}

### File: ../src/windows/editor_win.tcl
mcset es {Choose the database first.} {Selecciona primero la Base de Datos.}

### File: ../src/windows/editor_win.tcl
mcset es {Error while trying to collect completion list: %s} {Error while trying to collect completion list: %s}

### File: ../src/windows/editor_win.tcl
mcset es {Can't open %s file for reading.} {No se puede abrir el archivo %s para lectura.}

### File: ../src/windows/editor_win.tcl
mcset es {Can't open %s file for writting.} {No se puede abrir el archivo %s para escritura.}

### File: ../src/windows/editor_win.tcl
mcset es {SQL code saved in %s.} {Código SQL guardado en %s.}

### File: ../src/windows/editor_win.tcl
mcset es {Are you sure you want to clear queries history?} {¿Estás seguro de que quiere limpiar el historial de consultas?}

### File: ../src/windows/editor_win.tcl
mcset es {Delete the history entry} {Delete the history entry}

### File: ../src/windows/editor_win.tcl
mcset es {Are you sure you want to delete selected queries history entry?} {Are you sure you want to delete selected queries history entry?}

### File: ../src/windows/editor_win.tcl
mcset es Processing... Procesando...

### File: ../src/windows/editor_win.tcl
mcset es {Processing query...} {Procesando consulta...}

### File: ../src/windows/editor_win.tcl
mcset es {No results to export.} {No hay resultados a exportar.}

### File: ../src/windows/editor_win.tcl
mcset es {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.} {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.}

### File: ../src/windows/editor_win.tcl
mcset es {Query execution...} {Query execution...}

### File: ../src/windows/editor_win.tcl
mcset es {Executing SQL query...} {Executing SQL query...}

### File: ../src/windows/editor_win.tcl
mcset es {Error while executing query: %s} {Error ejecutando consulta: %s}

### File: ../src/windows/editor_win.tcl
mcset es {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s} {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s}

### File: ../src/windows/editor_win.tcl
mcset es {%s row(s) read in %s second(s).} {%s row(s) read in %s second(s).}

### File: ../src/windows/editor_win.tcl
mcset es {%s row(s) affected in %s second(s).} {%s Fila(s) afectadas en %s segundo(s).}

### File: ../src/windows/editor_win.tcl
mcset es {No SELECT statements found in editor or in selected part of SQL code.} {No SELECT statements found in editor or in selected part of SQL code.}

### File: ../src/windows/editor_win.tcl
mcset es {More than one SELECT statements found. Please select the one you're interested in and then try again.} {More than one SELECT statements found. Please select the one you're interested in and then try again.}

### File: ../src/windows/editor_win.tcl
mcset es {New view} {Nueva vista}

### File: ../src/windows/editor_win.tcl
mcset es {Fill query parameters} {Fill query parameters}

### File: ../src/error.tcl
mcset es {Background error} {Error en segundo plano}

### File: ../src/error.tcl
mcset es Close Cerrar

### File: ../src/error.tcl
mcset es {Report the bug} {Notificar el fallo}

### File: ../src/dialogs/about_dialog.tcl
mcset es About {Acerca de}

### File: ../src/dialogs/about_dialog.tcl
mcset es {Packages and plugins} {Packages and plugins}

### File: ../src/dialogs/about_dialog.tcl
mcset es Licence Licence

### File: ../src/dialogs/about_dialog.tcl
mcset es {Installed plugins:} {Installed plugins:}

### File: ../src/dialogs/about_dialog.tcl
mcset es {Used Tcl packages:} {Used Tcl packages:}

### File: ../src/dialogs/about_dialog.tcl
mcset es {SQLite3 engine version: %s} {Versión del motor SQLite3: %s}

### File: ../src/dialogs/searchdialog.tcl
mcset es {Global expression understeands '*', '?' and \[chars].} {Global expression understeands '*', '?' and \[chars].}

### File: ../src/dialogs/searchdialog.tcl
mcset es Find Encontrar

### File: ../src/dialogs/searchdialog.tcl
mcset es Replace Remplazar

### File: ../src/dialogs/searchdialog.tcl
mcset es {Do you want to replace marked text?} {¿Deseas remplazar el texto marcado?}

### File: ../src/dialogs/searchdialog.tcl
mcset es {Replace all} {Remplazar todo}

### File: ../src/dialogs/searchdialog.tcl
mcset es {Replacing finished.} {Remplazo concluido.}

### File: ../src/dialogs/searchdialog.tcl
mcset es {Cannot match the pattern!} {¡No se puede encontrar coincidencia con el patrón!}

### File: ../src/dialogs/bind_param.tcl
mcset es {Query number %s} {Query number %s}

### File: ../src/dialogs/bind_param.tcl
mcset es {Parameter number %s (named: %s):} {Parameter number %s (named: %s):}

### File: ../src/dialogs/bind_param.tcl
mcset es {NULL value} {NULL value}

### File: ../src/dialogs/bind_param.tcl
mcset es {You can use '%s' keyboard shortcut to switch NULL value.} {You can use '%s' keyboard shortcut to switch NULL value.}

### File: ../src/dialogs/bind_param.tcl
mcset es {Copy value to other '%s' parameters (%s)} {Copy value to other '%s' parameters (%s)}

### File: ../src/dialogs/bind_param.tcl
mcset es {By enabling this all parameters with same name
will also have same value as this one.} {By enabling this all parameters with same name
will also have same value as this one.}

### File: ../src/dialogs/bind_param.tcl
mcset es {Execute query} {Execute query}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset es Collation Collation

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset es Sort Ordenar

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset es {Named constraint:} {Named constraint:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset es {On conflict:} {En conflicto:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset es {Constraint is marked as being named, but there's no name filled in.} {Constraint is marked as being named, but there's no name filled in.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset es {Collation for column '%s' is enabled, but there's no collation name filled in.} {Collation for column '%s' is enabled, but there's no collation name filled in.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset es {No columns are selected.} {No columns are selected.}

### File: ../src/dialogs/populate_table.tcl
mcset es {Number of rows to insert:} {Número de filas a insertar:}

### File: ../src/dialogs/populate_table.tcl
mcset es {On a constraint violation:} {On a constraint violation:}

### File: ../src/dialogs/populate_table.tcl
mcset es Mode Modo

### File: ../src/dialogs/populate_table.tcl
mcset es {Select table to display available columns} {Seleccionar Tabla para mostrar Columnas disponibles}

### File: ../src/dialogs/populate_table.tcl
mcset es Populate Rellenar

### File: ../src/dialogs/populate_table.tcl
mcset es {Error occured while populating table:
%s} {Error al rellenar Tabla:
%s}

### File: ../src/dialogs/populate_table.tcl
mcset es Configuration Configuration

### File: ../src/dialogs/populate_table.tcl
mcset es {You have to type valid number of rows to insert.} {Tienes que introducir un número válido de filas a insertar.}

### File: ../src/dialogs/populate_table.tcl
mcset es {You have to select at least one column to populate.} {Debes seleccionar al menos una Columna para rellenar.}

### File: ../src/dialogs/populate_table.tcl
mcset es Populating... Populating...

### File: ../src/dialogs/populate_table.tcl
mcset es {Populating table '%s'.} {Populating table '%s'.}

### File: ../src/dialogs/populate_table.tcl
mcset es Stop Stop

### File: ../src/dialogs/table_dialog_fk.tcl
mcset es {Foreign table:} {Tabla foránea:}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset es {Local column} {Local column}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset es {Foreign column} {Foreign column}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset es Reactions Reactions

### File: ../src/dialogs/table_dialog_fk.tcl
mcset es {ON UPDATE} {ON UPDATE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset es {ON DELETE} {ON DELETE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset es MATCH MATCH

### File: ../src/dialogs/table_dialog_fk.tcl
mcset es {Deferred foreign key} {Deferred foreign key}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset es {No foreign table selected.} {No foreign table selected.}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset es {There's no foreign column assigned for local column '%s'.} {There's no foreign column assigned for local column '%s'.}

### File: ../src/dialogs/import_dialog.tcl
mcset es {Import from:} {Import from:}

### File: ../src/dialogs/import_dialog.tcl
mcset es {Import to:} {Import to:}

### File: ../src/dialogs/import_dialog.tcl
mcset es Table Tabla

### File: ../src/dialogs/import_dialog.tcl
mcset es Existing Existing

### File: ../src/dialogs/import_dialog.tcl
mcset es {Create new table} {Create new table}

### File: ../src/dialogs/import_dialog.tcl
mcset es Import Import

### File: ../src/dialogs/import_dialog.tcl
mcset es {Import method is not selected.} {Import method is not selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset es {You have to choose database.} {Debes seleccionar una Base de Datos.}

### File: ../src/dialogs/import_dialog.tcl
mcset es {No existing table is selected.} {No existing table is selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset es {Table typed to create already exists. Please change table name.} {Table typed to create already exists. Please change table name.}

### File: ../src/dialogs/view_dialog.tcl
mcset es View Ver

### File: ../src/dialogs/view_dialog.tcl
mcset es {View name:} {Nombre de la vista:}

### File: ../src/dialogs/view_dialog.tcl
mcset es {Code executed to get view data:} {Código ejecutado para obtener los datos de la vista:}

### File: ../src/dialogs/view_dialog.tcl
mcset es Create Crear

### File: ../src/dialogs/view_dialog.tcl
mcset es Change Cambiar

### File: ../src/dialogs/view_dialog.tcl
mcset es {You have to specify database.} {Debes especificar una Base de Datos.}

### File: ../src/dialogs/view_dialog.tcl
mcset es {You have to specify view name.} {Debes indicar el nombre de la vista.}

### File: ../src/dialogs/view_dialog.tcl
mcset es {You havn't wrote a code for the view.} {No has escrito el código para la vista.}

### File: ../src/dialogs/export_dialog.tcl
mcset es {Export data} {Exportar datos}

### File: ../src/dialogs/export_dialog.tcl
mcset es {Only structure, without data} {Sólo estructura, sin datos}

### File: ../src/dialogs/export_dialog.tcl
mcset es {Table or view} {Table or view}

### File: ../src/dialogs/export_dialog.tcl
mcset es {Output file} {Archivo de salida}

### File: ../src/dialogs/export_dialog.tcl
mcset es {Export format} {Formato de Exportación}

### File: ../src/dialogs/export_dialog.tcl
mcset es Export Exportar

### File: ../src/dialogs/export_dialog.tcl
mcset es {You have to choose file.} {Tienes que seleccionar un archivo.}

### File: ../src/dialogs/export_dialog.tcl
mcset es {Can't write to file: %s} {No se puede escribir en el archivo: %s}

### File: ../src/dialogs/export_dialog.tcl
mcset es {You have to choose table.} {Debes seleccionar una Tabla.}

### File: ../src/dialogs/export_dialog.tcl
mcset es {Exporting database '%s'.} {Exporting database '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset es {Exporting table '%s'.} {Exporting table '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset es {Exporting view '%s'.} {Exporting view '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset es {Exporting results.} {Exporting results.}

### File: ../src/dialogs/export_dialog.tcl
mcset es Exporting... Exporting...

### File: ../src/dialogs/export_dialog.tcl
mcset es {Cannot write to file: %s
Please select other file.} {No se puede escribir en el archivo: %s
Por favor, selecciona otro archivo.}

### File: ../src/dialogs/bug_report_login.tcl
mcset es {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.} {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.}

### File: ../src/dialogs/bug_report_login.tcl
mcset es Login: Login:

### File: ../src/dialogs/bug_report_login.tcl
mcset es Password: Password:

### File: ../src/dialogs/bug_report_login.tcl
mcset es Validate Validate

### File: ../src/dialogs/bug_report_login.tcl
mcset es {Validation result} {Validation result}

### File: ../src/dialogs/bug_report_login.tcl
mcset es {Not validated yet} {Not validated yet}

### File: ../src/dialogs/bug_report_login.tcl
mcset es Validating... Validating...

### File: ../src/dialogs/bug_report_login.tcl
mcset es {Validating login and password...} {Validating login and password...}

### File: ../src/dialogs/bug_report_login.tcl
mcset es {Invalid login or password.} {Invalid login or password.}

### File: ../src/dialogs/bug_report_login.tcl
mcset es {Login and password are correct.} {Login and password are correct.}

### File: ../src/dialogs/bug_report.tcl
mcset es {Your e-mail address or user (both optional)} {Your e-mail address or user (both optional)}

### File: ../src/dialogs/bug_report.tcl
mcset es or or

### File: ../src/dialogs/bug_report.tcl
mcset es {Log in} {Log in}

### File: ../src/dialogs/bug_report.tcl
mcset es {Logged in} {Logged in}

### File: ../src/dialogs/bug_report.tcl
mcset es {Log out} {Log out}

### File: ../src/dialogs/bug_report.tcl
mcset es {Brief description:} {Brief description:}

### File: ../src/dialogs/bug_report.tcl
mcset es {How to reproduce problem (if possible):} {How to reproduce problem (if possible):}

### File: ../src/dialogs/bug_report.tcl
mcset es {What is the problem:} {What is the problem:}

### File: ../src/dialogs/bug_report.tcl
mcset es {Show more (optional)} {Show more (optional)}

### File: ../src/dialogs/bug_report.tcl
mcset es {Operating system:} {Operating system:}

### File: ../src/dialogs/bug_report.tcl
mcset es {Take screenshots of all SQLiteStudio windows and attach them} {Take screenshots of all SQLiteStudio windows and attach them}

### File: ../src/dialogs/bug_report.tcl
mcset es Send Send

### File: ../src/dialogs/bug_report.tcl
mcset es {Describe your feature request:} {Describe your feature request:}

### File: ../src/dialogs/bug_report.tcl
mcset es Hide Hide

### File: ../src/dialogs/bug_report.tcl
mcset es {Please fill 'Brief' field.} {Please fill 'Brief' field.}

### File: ../src/dialogs/bug_report.tcl
mcset es {Please fill at least one of 'Description' or 'How to reproduce' fields.} {Please fill at least one of 'Description' or 'How to reproduce' fields.}

### File: ../src/dialogs/bug_report.tcl
mcset es {Please provide valid e-mail address or leave 'E-mail' empty.} {Please provide valid e-mail address or leave 'E-mail' empty.}

### File: ../src/dialogs/bug_report.tcl
mcset es {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.} {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.}

### File: ../src/dialogs/db_convert.tcl
mcset es {Database to convert:} {Base de Datos a convertir:}

### File: ../src/dialogs/db_convert.tcl
mcset es {Converted database name:} {Nombre de la Base de Datos convertida:}

### File: ../src/dialogs/db_convert.tcl
mcset es {File to use for converted database:} {Archivo a usar para la Base de Datos convertida:}

### File: ../src/dialogs/db_convert.tcl
mcset es {Choose new file for database} {Seleccionar un nuevo archivo para la Base de Datos}

### File: ../src/dialogs/db_convert.tcl
mcset es {Database version:} {Versión de la Base de Datos:}

### File: ../src/dialogs/db_convert.tcl
mcset es Convert Convertir

### File: ../src/dialogs/db_convert.tcl
mcset es {Convert database} {Convertir Base de Datos}

### File: ../src/dialogs/db_convert.tcl
mcset es {You chave to choose database to convert.} {Debes elegir una Base de Datos a convertir.}

### File: ../src/dialogs/db_convert.tcl
mcset es {Error resolving database with name %s!} {Error resolviendo Base de Datos con nombre %s!}

### File: ../src/dialogs/db_convert.tcl
mcset es {You have to specify new database file.} {Debes indicar un nuevo archivo de Base de Datos.}

### File: ../src/dialogs/db_convert.tcl
mcset es {Cannot use existing file for converted database.} {No se puede usar un archivo existente para la Base de Datos convertida.}

### File: ../src/dialogs/db_convert.tcl
mcset es {Cannot use existing name for converted database.} {No se puede usar un nombre existente para la Base de Datos convertida.}

### File: ../src/dialogs/db_convert.tcl
mcset es {Cannot find handler for database labeled with: %s} {No se puede encontrar manejador para la Base de Datos etiquetada con: %s}

### File: ../src/dialogs/db_convert.tcl
mcset es {Error while trying to create database: %s} {Error al crear la Base de Datos: %s}

### File: ../src/dialogs/db_convert.tcl
mcset es {Database converting error} {Database converting error}

### File: ../src/dialogs/db_convert.tcl
mcset es {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s} {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s}

### File: ../src/dialogs/db_convert.tcl
mcset es {Choose file} {Seleccionar Archivo}

### File: ../src/dialogs/yesno.tcl
mcset es Question Question

### File: ../src/dialogs/yesno.tcl
mcset es Warning Advertencia

### File: ../src/dialogs/yesno.tcl
mcset es Error Error

### File: ../src/dialogs/yesno.tcl
mcset es Information Información

### File: ../src/dialogs/import_db.tcl
mcset es {Import from one of databases:} {Importar desde una de las Bases de Datos:}

### File: ../src/dialogs/import_db.tcl
mcset es {Choose database file to import:} {Seleccionar archivo de Base de Datos a importar:}

### File: ../src/dialogs/import_db.tcl
mcset es {No database chosen.} {Ninguna Base de Datos seleccionada.}

### File: ../src/dialogs/import_db.tcl
mcset es {Cannot open specified database.} {No se puede abrir la Base de Datos especificada.}

### File: ../src/dialogs/import_db.tcl
mcset es {Error while importing database:
%s} {Error importando Base de Datos:
%s}

### File: ../src/dialogs/import_db.tcl
mcset es {Select file} {Seleccionar archivo}

### File: ../src/dialogs/column_dialog.tcl
mcset es Column: Columna:

### File: ../src/dialogs/column_dialog.tcl
mcset es {Column constraints:} {Column constraints:}

### File: ../src/dialogs/column_dialog.tcl
mcset es Add Añadir

### File: ../src/dialogs/column_dialog.tcl
mcset es Size Tamaño

### File: ../src/dialogs/column_dialog.tcl
mcset es {Maximal length of value in column.} {Longitud máxima del valor de la Columna.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Primary key configuration} {Primary key configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset es Autoincrement Autoincrement

### File: ../src/dialogs/column_dialog.tcl
mcset es {Sort order:} Orden:

### File: ../src/dialogs/column_dialog.tcl
mcset es {No foreign column selected.} {No foreign column selected.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Choose ON UPDATE action, or disable it.} {Choose ON UPDATE action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Choose ON DELETE action, or disable it.} {Choose ON DELETE action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Choose MATCH action, or disable it.} {Choose MATCH action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Foreign key configuration} {Foreign key configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Foreign column:} {Foreign column:}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Unique configuration} {Unique configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Fill in the condition expression.} {Fill in the condition expression.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Check condition configuration} {Check condition configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset es Condition: Condition:

### File: ../src/dialogs/column_dialog.tcl
mcset es {Not null configuration} {Not null configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Fill in the collation name.} {Fill in the collation name.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Collating configuration} {Collating configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Collation name:} {Collation name:}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Fill in the default value.} {Fill in the default value.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Default value configuration} {Default value configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Default value:} {Default value:}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Use value as:} {Use value as:}

### File: ../src/dialogs/column_dialog.tcl
mcset es {A literal value} {A literal value}

### File: ../src/dialogs/column_dialog.tcl
mcset es {An expression} {An expression}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Column primary key is not configured correctly.} {Column primary key is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {AUTOINCREMENT is allowed only with INTEGER type of column.} {AUTOINCREMENT is allowed only with INTEGER type of column.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Column foreign key is not configured correctly.} {Column foreign key is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Column 'unique' constraint is not configured correctly.} {Column 'unique' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Column 'check' constraint is not configured correctly.} {Column 'check' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Column 'notnull' constraint is not configured correctly.} {Column 'notnull' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Column 'default' constraint is not configured correctly.} {Column 'default' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Column 'collate' constraint is not configured correctly.} {Column 'collate' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {No column name is specified.} {No column name is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Column with name '%s' already exists in the table.} {Column with name '%s' already exists in the table.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Data type bounds are given, but no data type name is specified.} {Data type bounds are given, but no data type name is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Data type precision is given, but no data type size is specified.} {Data type precision is given, but no data type size is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Data type size has invalid format. Only integer value is allowed.} {Data type size has invalid format. Only integer value is allowed.}

### File: ../src/dialogs/column_dialog.tcl
mcset es {Data type precision has invalid format. Only integer value is allowed.} {Data type precision has invalid format. Only integer value is allowed.}

### File: ../src/dialogs/assoc_dialog.tcl
mcset es {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:} {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:}

### File: ../src/dialogs/assoc_dialog.tcl
mcset es {Current associations} {Current associations}

### File: ../src/dialogs/assoc_dialog.tcl
mcset es {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.} {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.}

### File: ../src/dialogs/db_edit.tcl
mcset es {Database file:} {Archivo de la Base de Datos:}

### File: ../src/dialogs/db_edit.tcl
mcset es {Database name:} {Nombre de la Base de Datos:}

### File: ../src/dialogs/db_edit.tcl
mcset es {Generate automatically} {Generate automatically}

### File: ../src/dialogs/db_edit.tcl
mcset es {Type name in field below:} {Type name in field below:}

### File: ../src/dialogs/db_edit.tcl
mcset es {Remember it permanently} {Remember it permanently}

### File: ../src/dialogs/db_edit.tcl
mcset es {If disabled, then the database will be registered only
for this single SQLiteStudio session.} {If disabled, then the database will be registered only
for this single SQLiteStudio session.}

### File: ../src/dialogs/db_edit.tcl
mcset es {Edit database} {Editar Base de Datos}

### File: ../src/dialogs/db_edit.tcl
mcset es {Add database} {Añadir Base de Datos}

### File: ../src/dialogs/db_edit.tcl
mcset es {File '%s' doesn't exist!} {File '%s' doesn't exist!}

### File: ../src/dialogs/db_edit.tcl
mcset es {You have to specify database file.} {Debes indicar el archivo de la Base de Datos.}

### File: ../src/dialogs/db_edit.tcl
mcset es {Database named '%s' already exists on databases list. Please pick other name.} {Database named '%s' already exists on databases list. Please pick other name.}

### File: ../src/dialogs/db_edit.tcl
mcset es {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.} {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.}

### File: ../src/dialogs/db_edit.tcl
mcset es {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.} {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.}

### File: ../src/dialogs/db_edit.tcl
mcset es {Type not existing file for new database} {Type not existing file for new database}

### File: ../src/dialogs/db_edit.tcl
mcset es {Select existing database file} {Select existing database file}

### File: ../src/dialogs/db_edit.tcl
mcset es {%s is not supported database!} {¡%s no es una Base de Datos soportada!}

### File: ../src/dialogs/table_dialog_pk.tcl
mcset es {Using autoincrement with more than one column at once is forbidden.} {Using autoincrement with more than one column at once is forbidden.}

### File: ../src/dialogs/tips_dialog.tcl
mcset es Previous Anterior

### File: ../src/dialogs/tips_dialog.tcl
mcset es Next Siguiente

### File: ../src/dialogs/tips_dialog.tcl
mcset es {Do not show this dialog at startup} {No mostrar esta ventana en el inicio}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		} {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			You can configure all SQL editor syntax colors in settings.
		} {
			You can configure all SQL editor syntax colors in settings.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		} {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		} {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		} {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		} {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		} {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		} {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		} {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		} {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		} {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		} {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		} {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		} {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		} {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		} {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		} {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		} {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset es {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		} {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		}

### File: ../src/dialogs/import_table.tcl
mcset es Separator: Separador:

### File: ../src/dialogs/import_table.tcl
mcset es {Common separator is \t (tab), but sometimes others can be met.} {El separador común es \t (tabulador), pero a veces pueden aparecer otros.}

### File: ../src/dialogs/import_table.tcl
mcset es {Import data file for '%s' table:} {Importar archivo de datos para la Tabla '%s':}

### File: ../src/dialogs/import_table.tcl
mcset es {File '%s' isn't readable!} {El archivo '%s' no se puede leer!}

### File: ../src/dialogs/import_table.tcl
mcset es {Error while trying to copy data:
%s} {Error al tratar de copiar datos:
%s}

### File: ../src/dialogs/release_notes_dialog.tcl
mcset es {Don't show this dialog after update.} {Don't show this dialog after update.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es Trigger Trigger

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {On action:} {On action:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {Trigger name:} {Nombre del Disparador:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es When: Cuando:

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {On table:} {On table:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {Execute code for:} {Ejecutar código para:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.} {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {Execute code only when:} {Ejecutar código sólo cuando:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {Code executed for above configuration:} {Código ejecutado para la configuración anterior:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {You have to specify view.} {Debes especificar una vista.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {You have to specify table.} {Debes especificar una Tabla.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {You have to specify trigger name.} {Debes especificar un nombre del Disparador.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {You have to specify 'action' condition.} {Debes especificar la condición 'action'.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {You havn't wrote a code for the trigger.} {No has escrito el código para el Disparador.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset es {On view:} {On view:}

### File: ../src/dialogs/table_dialog.tcl
mcset es Columns: Columnas:

### File: ../src/dialogs/table_dialog.tcl
mcset es {Table constraints:} {Table constraints:}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Table name:} {Nombre de la Tabla:}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Add column} {Añadir Columna}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Edit selected} {Editar seleccionada}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Delete selected} {Eliminar seleccionada}

### File: ../src/dialogs/table_dialog.tcl
mcset es Type Type

### File: ../src/dialogs/table_dialog.tcl
mcset es Details Details

### File: ../src/dialogs/table_dialog.tcl
mcset es {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.} {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Edit column} {Editar Columna}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Delete column} {Delete column}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Are you sure you want to delete column '%s'?} {Are you sure you want to delete column '%s'?}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Constraint change} {Constraint change}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Are you sure you want to change constraint type?
Current constraint configuration will be lost.} {Are you sure you want to change constraint type?
Current constraint configuration will be lost.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Table constraint number %s (%s) is not configured correctly.} {Table constraint number %s (%s) is not configured correctly.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {There's no column defined.} {There's no column defined.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {There is already a table with name '%s'. Please change the name of this table.} {There is already a table with name '%s'. Please change the name of this table.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {There is already an index with name '%s'. Please change the name of this index.} {There is already an index with name '%s'. Please change the name of this index.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {There is already a trigger with name '%s'. Please change the name of this trigger.} {There is already a trigger with name '%s'. Please change the name of this trigger.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {There is already a view with name '%s'. Please change the name of this view.} {There is already a view with name '%s'. Please change the name of this view.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Trigger parsing problem} {Trigger parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Index parsing problem} {Index parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset es {View parsing problem} {View parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.} {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {%s(%s) referencing %s(%s)} {%s(%s) referencing %s(%s)}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s} {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Do you want to continue anyway?} {Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?} {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Modifying table...} {Modifying table...}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Modifying table '%s'.} {Modifying table '%s'.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Could not recreate triggers for modified table.} {Could not recreate triggers for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Could not recreate indexes for modified table.} {Could not recreate indexes for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Could not recreate views for modified table.} {Could not recreate views for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Trigger recreation problem} {Trigger recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset es {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Index recreation problem} {Index recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset es {Could not recreate foreign keys for tables referencing modified table.} {Could not recreate foreign keys for tables referencing modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset es {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset es {View recreation problem} {View recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset es {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).} {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).}

### File: ../src/dialogs/table_dialog_chk.tcl
mcset es {Condition expression cannot be empty.} {Condition expression cannot be empty.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset es {What would you like to do?} {What would you like to do?}

### File: ../src/dialogs/new_version_dialog.tcl
mcset es {Install it automatically} {Install it automatically}

### File: ../src/dialogs/new_version_dialog.tcl
mcset es {Go to download page} {Go to download page}

### File: ../src/dialogs/new_version_dialog.tcl
mcset es {Package download} {Package download}

### File: ../src/dialogs/new_version_dialog.tcl
mcset es {Insufficient privileges to perform automatic update.} {Insufficient privileges to perform automatic update.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset es {Check for updates at startup} {Check for updates at startup}

### File: ../src/dialogs/new_version_dialog.tcl
mcset es {New version of SQLiteStudio is available: %s} {New version of SQLiteStudio is available: %s}

### File: ../src/dialogs/trigger_dialog_cols.tcl
mcset es {Trigger columns} {Trigger columns}

### File: ../src/dialogs/blob_edit.tcl
mcset es Commit {Fijar (Commit)}

### File: ../src/dialogs/bug_history.tcl
mcset es Clear Clear

### File: ../src/dialogs/bug_history.tcl
mcset es {Reported on} {Reported on}

### File: ../src/dialogs/bug_history.tcl
mcset es Brief Brief

### File: ../src/dialogs/bug_history.tcl
mcset es URL URL

### File: ../src/dialogs/bug_history.tcl
mcset es Discussion Discussion

### File: ../src/dialogs/bug_history.tcl
mcset es {Clear reports} {Clear reports}

### File: ../src/dialogs/bug_history.tcl
mcset es {Do you want to clear whole bug reports history?} {Do you want to clear whole bug reports history?}

### File: ../src/dialogs/index_dialog.tcl
mcset es Index Index

### File: ../src/dialogs/index_dialog.tcl
mcset es {Index name:} {Nombre del índice:}

### File: ../src/dialogs/index_dialog.tcl
mcset es Available Available

### File: ../src/dialogs/index_dialog.tcl
mcset es Indexed Indexed

### File: ../src/dialogs/index_dialog.tcl
mcset es {Modifying index} {Modifying index}

### File: ../src/dialogs/index_dialog.tcl
mcset es {Modifying index '%s'} {Modifying index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset es {Creating index} {Creating index}

### File: ../src/dialogs/index_dialog.tcl
mcset es {Creating index '%s'} {Creating index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset es {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?} {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?}

### File: ../src/dialogs/index_dialog.tcl
mcset es {Unique values} {Unique values}

### File: ../src/dialogs/index_dialog.tcl
mcset es {Same values for '%s'} {Same values for '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset es {You have to select at least one column.} {Debes seleccionar al menos una Columna.}

### File: ../src/dialogs/index_dialog.tcl
mcset es {You have to specify index name.} {Debes indicar el nombre del índice.}

### File: ../src/dialogs/functions_dialog.tcl
mcset es Implementation: Implementación:

### File: ../src/dialogs/functions_dialog.tcl
mcset es Name: Nombre:

### File: ../src/dialogs/functions_dialog.tcl
mcset es {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.} {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.}

### File: ../src/dialogs/functions_dialog.tcl
mcset es {Cannot use two functions with same name! Change name for '%s'.} {No se pueden usar dos funciones con el mismo nombre! Cambia el nombre para '%s'.}

### File: ../src/dialogs/functions_dialog.tcl
mcset es {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! } {No se puede usar 'tcl' o 'sqlfile' como nombre de función, estos nombres están reservados! }

### File: ../src/dialogs/functions_dialog.tcl
mcset es {Function '%s' is not implemented!} {La función '%s' no está implementada!}

### File: ../src/dialogs/functions_dialog.tcl
mcset es {Delete function} {Función Eliminar}

### File: ../src/dialogs/functions_dialog.tcl
mcset es {Are you sure you want to delete function '%s'?} {¿Estás seguro que deseas eliminar la función '%s'?}

### File: ../src/mainwindow.tcl
mcset es {Connect to selected database} {Conectar a la Base de Datos seleccionada}

### File: ../src/mainwindow.tcl
mcset es {Disconnect from selected database} {Desconectar de la Base de Datos seleccionada}

### File: ../src/mainwindow.tcl
mcset es {Remove selected database from list} {Eliminar Base de Datos seleccionada de la lista}

### File: ../src/mainwindow.tcl
mcset es {New table} {Nueva Tabla}

### File: ../src/mainwindow.tcl
mcset es {Drop table} {Eliminar Tabla}

### File: ../src/mainwindow.tcl
mcset es {Drop index} {Eliminar índice}

### File: ../src/mainwindow.tcl
mcset es {Drop trigger} {Eliminar Disparador}

### File: ../src/mainwindow.tcl
mcset es {Edit view} {Editar vista}

### File: ../src/mainwindow.tcl
mcset es {Drop view} {Eliminar vista}

### File: ../src/mainwindow.tcl
mcset es {Arrange cascade windows layout} {Organizar ventanas en cascada}

### File: ../src/mainwindow.tcl
mcset es {Arrange intelligent windows layout} {Organizar ventanas de forma inteligente}

### File: ../src/mainwindow.tcl
mcset es {Refresh databases tree (%s)} {Actualizar árbol de Bases de Datos (%s)}

### File: ../src/mainwindow.tcl
mcset es {Open SQL query editor} {Abrir editor de consultas SQL}

### File: ../src/mainwindow.tcl
mcset es {Settings (%s)} {Settings (%s)}

### File: ../src/mainwindow.tcl
mcset es {Open SQL functions editor} {Abrir editor de funciones SQL}

### File: ../src/mainwindow.tcl
mcset es {Clear objects filter} {Clear objects filter}

### File: ../src/mainwindow.tcl
mcset es {Enter object name you want to look for} {Enter object name you want to look for}

### File: ../src/mainwindow.tcl
mcset es Databases {Bases de datos}

### File: ../src/mainwindow.tcl
mcset es Tools Herramientas

### File: ../src/mainwindow.tcl
mcset es Connect Conectar

### File: ../src/mainwindow.tcl
mcset es Disconnect Desconectar

### File: ../src/mainwindow.tcl
mcset es {Remove from list} {Quitar de la lista}

### File: ../src/mainwindow.tcl
mcset es {View main toolbar} {Ver barra de herramientas principal}

### File: ../src/mainwindow.tcl
mcset es {View structure toolbar} {Ver barra de herramientas de estructura}

### File: ../src/mainwindow.tcl
mcset es {View windows toolbar} {Ver barra de herramientas de ventanas}

### File: ../src/mainwindow.tcl
mcset es {View tools toolbar} {Ver barra de herramientas de herramientas}

### File: ../src/mainwindow.tcl
mcset es {View configuration toolbar} {Ver barra de herramientas de configuración}

### File: ../src/mainwindow.tcl
mcset es {Refresh databases tree} {Actualizar árbol de Bases de Datos}

### File: ../src/mainwindow.tcl
mcset es {Custom SQL functions} {Funciones SQL personalizadas}

### File: ../src/mainwindow.tcl
mcset es {Export database} {Exportar Base de Datos}

### File: ../src/mainwindow.tcl
mcset es {Export table or view} {Export table or view}

### File: ../src/mainwindow.tcl
mcset es {Import data to a table} {Import data to a table}

### File: ../src/mainwindow.tcl
mcset es {SQLiteStudio home page} {SQLiteStudio home page}

### File: ../src/mainwindow.tcl
mcset es {SQLiteStudio manual} {Manual de SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset es {SQLite documentation} {Documentación de SQLite}

### File: ../src/mainwindow.tcl
mcset es {SQLiteStudio support forum} {SQLiteStudio support forum}

### File: ../src/mainwindow.tcl
mcset es {Report a bug} {Informar de fallo en SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset es {Send feature request} {Send feature request}

### File: ../src/mainwindow.tcl
mcset es {Show bug reports history} {Show bug reports history}

### File: ../src/mainwindow.tcl
mcset es {Show tips window} {Mostrar ventana de sugerencias y trucos}

### File: ../src/mainwindow.tcl
mcset es ChangeLog {Lista de cambios}

### File: ../src/mainwindow.tcl
mcset es Roadmap Futuro

### File: ../src/mainwindow.tcl
mcset es {Check for new version} {Check for new version}

### File: ../src/mainwindow.tcl
mcset es Donate Donate

### File: ../src/mainwindow.tcl
mcset es {Did you know that...} {Sabías que ...}

### File: ../src/mainwindow.tcl
mcset es {Editor %s} {Editor %s}

### File: ../src/mainwindow.tcl
mcset es Settings Ajustes

### File: ../src/mainwindow.tcl
mcset es {SQLiteStudio roadmap} {Futuro de SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset es {Can't start web browser, because:
%s} {Can't start web browser, because:
%s}

### File: ../src/mainwindow.tcl
mcset es {Can't start %s web browser, because:
%s} {No se puede iniciar el navegador web %s porque:
%s}

### File: ../src/mainwindow.tcl
mcset es {About SQLiteStudio} {Acerca de SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset es {SQLiteStudio ChangeLog} {SQLiteStudio lista de cambios}

### File: ../src/mainwindow.tcl
mcset es {There is no new version available.} {There is no new version available.}

### File: ../src/mainwindow.tcl
mcset es {New version} {New version}

### File: ../src/mainwindow.tcl
mcset es {Report bug} {Report bug}

### File: ../src/mainwindow.tcl
mcset es {Feature request} {Feature request}

### File: ../src/mainwindow.tcl
mcset es {Reports history} {Reports history}

### File: ../src/mainwindow.tcl
mcset es {Reporting bug} {Reporting bug}

### File: ../src/mainwindow.tcl
mcset es {Reporting bug to SQLiteStudio bugs database...} {Reporting bug to SQLiteStudio bugs database...}

### File: ../src/mainwindow.tcl
mcset es {Problem occurred while reporting bug. You can ignore it and get back to your work.} {Problem occurred while reporting bug. You can ignore it and get back to your work.}

### File: ../src/mainwindow.tcl
mcset es Ignore Ignore

### File: ../src/mainwindow.tcl
mcset es {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history} {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history}

### File: ../src/mainwindow.tcl
mcset es {A timeout occured while downloading new version. Try again, or download it manually.} {A timeout occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset es {An error occured while downloading new version. Try again, or download it manually.} {An error occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset es Downloading... Downloading...

### File: ../src/mainwindow.tcl
mcset es {Downloading SQLiteStudio v%s...} {Downloading SQLiteStudio v%s...}

### File: ../src/mainwindow.tcl
mcset es {Problem with saving new SQLiteStudio version to:
%s
Details:
%s} {Problem with saving new SQLiteStudio version to:
%s
Details:
%s}

### File: ../src/mainwindow.tcl
mcset es {Problem with getting new SQLiteStudio version
Details:
%s} {Problem with getting new SQLiteStudio version
Details:
%s}

### File: ../src/mainwindow.tcl
mcset es {This is unknown binary distribution. Cannot determinate binary file to download for update.} {This is unknown binary distribution. Cannot determinate binary file to download for update.}

### File: ../src/data_editor.tcl
mcset es {There are uncommited rows.
Are you sure you want to close '%s' window anywy?} {There are uncommited rows.
Are you sure you want to close '%s' window anywy?}

### File: ../src/common/ddl_dialog.tcl
mcset es {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s} {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s}

### File: ../src/common/color_picker.tcl
mcset es {Choose color} {Elije color}

### File: ../src/common/shortcut_edit.tcl
mcset es {Forbidden shortcut key combination: %s} {Combinación de teclas de acceso directo prohibidas: %s}

### File: ../src/common/common.tcl
mcset es Copy Copiar

### File: ../src/common/common.tcl
mcset es Cut Cut

### File: ../src/common/common.tcl
mcset es Paste Pegar

### File: ../src/common/blob_edit_panel.tcl
mcset es {Text edit} {Edición de texto}

### File: ../src/common/blob_edit_panel.tcl
mcset es {Hexadecimal edit} {Edición Hexadecimal}

### File: ../src/common/common_sql.tcl
mcset es {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
} {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
}

### File: ../src/common/hex_editor.tcl
mcset es {Overwrite characters,
instead of inserting} {Overwrite characters,
instead of inserting}

### File: ../src/common/hex_editor.tcl
mcset es Processing Procesando

### File: ../src/common/hex_editor.tcl
mcset es {Processing data...} {Procesando datos...}

### File: ../src/sql_editor.tcl
mcset es {Replace dialog} {Ventana de Remplazar}

### File: ../src/sql_editor.tcl
mcset es {Search dialog} {Ventana de Búsqueda}

### File: ../src/trees/db_tree.tcl
mcset es Loading Loading

### File: ../src/trees/db_tree.tcl
mcset es {Loading database list} {Loading database list}

### File: ../src/trees/db_tree.tcl
mcset es {Given database file doesn't exist or is unreadable.} {El archivo de la Base de Datos dada no existe o no se puede leer.}

### File: ../src/trees/db_tree.tcl
mcset es Vacuum {Copia de seguridad}

### File: ../src/trees/db_tree.tcl
mcset es {Integrity check} {Integrity check}

### File: ../src/trees/db_tree.tcl
mcset es {Import schema from other database} {Importar esquema desde otra Base de Datos}

### File: ../src/trees/db_tree.tcl
mcset es {Reset autoincrement for '%s'} {Reset autoincrement for '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {Erase table data} {Erase table data}

### File: ../src/trees/db_tree.tcl
mcset es {Create foreign key} {Crear clave foránea}

### File: ../src/trees/db_tree.tcl
mcset es {Show view data} {Mostrar vista de datos}

### File: ../src/trees/db_tree.tcl
mcset es {Export view} {Export view}

### File: ../src/trees/db_tree.tcl
mcset es {Sort databases alphabetically} {Sort databases alphabetically}

### File: ../src/trees/db_tree.tcl
mcset es {Given database is already on the list.} {La Base de Datos dada ya está en la lista.}

### File: ../src/trees/db_tree.tcl
mcset es {Given database name is already on the list.} {El nombre de la Base de Datos dada ya está en la lista.}

### File: ../src/trees/db_tree.tcl
mcset es Tables Tablas

### File: ../src/trees/db_tree.tcl
mcset es Views Vistas

### File: ../src/trees/db_tree.tcl
mcset es {SQLite system table} {Tabla del sistema SQLite}

### File: ../src/trees/db_tree.tcl
mcset es Columns Columnas

### File: ../src/trees/db_tree.tcl
mcset es {SQLite system index} {SQLite system index}

### File: ../src/trees/db_tree.tcl
mcset es {Remove database} {Eliminar Base de Datos}

### File: ../src/trees/db_tree.tcl
mcset es {Are you sure you want to remove '%s' database from the list?} {¿Seguro que quieres eliminar la Base de Datos '%s' de la lista?}

### File: ../src/trees/db_tree.tcl
mcset es {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.} {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.}

### File: ../src/trees/db_tree.tcl
mcset es {'%s' is a virtual table, therefore cannot be browsed in table window.} {'%s' is a virtual table, therefore cannot be browsed in table window.}

### File: ../src/trees/db_tree.tcl
mcset es {Table '%s' has no DDL. Probably it's system table and should not be edited.} {Table '%s' has no DDL. Probably it's system table and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset es {'%s' is a virtual table, therefore cannot be edited in table dialog.} {'%s' is a virtual table, therefore cannot be edited in table dialog.}

### File: ../src/trees/db_tree.tcl
mcset es {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.} {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.}

### File: ../src/trees/db_tree.tcl
mcset es {Integrity check (%s)} {Integrity check (%s)}

### File: ../src/trees/db_tree.tcl
mcset es {Are you sure you want to DROP '%s' table?} {¿Seguro que quieres eliminar la Tabla '%s'?}

### File: ../src/trees/db_tree.tcl
mcset es {Dropping table} {Dropping table}

### File: ../src/trees/db_tree.tcl
mcset es {Dropping table '%s'} {Dropping table '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {Dropping index} {Dropping index}

### File: ../src/trees/db_tree.tcl
mcset es {Dropping index '%s'} {Dropping index '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?} {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset es {Fix trigger} {Fix trigger}

### File: ../src/trees/db_tree.tcl
mcset es {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.} {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset es {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?} {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset es {Fix view} {Fix view}

### File: ../src/trees/db_tree.tcl
mcset es {View '%s' has no DDL. Probably it's system view and should not be edited.} {View '%s' has no DDL. Probably it's system view and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset es {Delete view} {Borrar vista}

### File: ../src/trees/db_tree.tcl
mcset es {Are you sure you want to delete '%s' view?} {¿Seguro que quieres borrar la vista '%s'?}

### File: ../src/trees/db_tree.tcl
mcset es {Erase data} {Erase data}

### File: ../src/trees/db_tree.tcl
mcset es {Are you sure you want to delete all data from table '%s'?} {Are you sure you want to delete all data from table '%s'?}

### File: ../src/trees/db_tree.tcl
mcset es {Deleting data} {Deleting data}

### File: ../src/trees/db_tree.tcl
mcset es {Deleting data from table '%s'} {Deleting data from table '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {'%s' view data} {Ver datos '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {Are you sure you want to make a vacuum?} {¿Seguro que quieres hacer una copia de seguridad?}

### File: ../src/trees/db_tree.tcl
mcset es Vacuuming Vacuuming

### File: ../src/trees/db_tree.tcl
mcset es {Vacuuming '%s'} {Vacuuming '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {SQL files} {Archivos SQL}

### File: ../src/trees/db_tree.tcl
mcset es {Select SQL file to be executed} {Select SQL file to be executed}

### File: ../src/trees/db_tree.tcl
mcset es {Error while executing SQL:
%s} {Error while executing SQL:
%s}

### File: ../src/trees/db_tree.tcl
mcset es {SQL executed sucessfly.} {SQL ejecutado satisfactoriamente.}

### File: ../src/trees/db_tree.tcl
mcset es {Import database schema} {Importar esquema de Base de Datos}

### File: ../src/trees/db_tree.tcl
mcset es {Database: %s} {Database: %s}

### File: ../src/trees/db_tree.tcl
mcset es URI: URI:

### File: ../src/trees/db_tree.tcl
mcset es Version: Version:

### File: ../src/trees/db_tree.tcl
mcset es {File size:} {File size:}

### File: ../src/trees/db_tree.tcl
mcset es {Schema version:} {Schema version:}

### File: ../src/trees/db_tree.tcl
mcset es {Virtual table} {Virtual table}

### File: ../src/trees/db_tree.tcl
mcset es Indexes: Indexes:

### File: ../src/trees/db_tree.tcl
mcset es Triggers: Triggers:

### File: ../src/trees/db_tree.tcl
mcset es {Column: %s} {Column: %s}

### File: ../src/trees/db_tree.tcl
mcset es {Not null} {Not null}

### File: ../src/trees/db_tree.tcl
mcset es {Indexed table:} {Indexed table:}

### File: ../src/trees/db_tree.tcl
mcset es {Copy index '%s' for table '%s'} {Copy index '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {Move index '%s' to table '%s'} {Move index '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {Copy trigger '%s' for table '%s'} {Copy trigger '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {Move trigger '%s' to table '%s'} {Move trigger '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {Copy view '%s' for database '%s'} {Copy view '%s' for database '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {Move view '%s' to database '%s'} {Move view '%s' to database '%s'}

### File: ../src/trees/db_tree.tcl
mcset es {View '%s' has no DDL, therefore cannot be edited.} {View '%s' has no DDL, therefore cannot be edited.}

### File: ../src/trees/db_tree.tcl
mcset es {Copy view} {Copy view}

### File: ../src/trees/db_tree.tcl
mcset es {Move view} {Move view}

### File: ../src/trees/db_tree.tcl
mcset es Move Move

### File: ../src/trees/db_tree.tcl
mcset es {Copy index} {Copy index}

### File: ../src/trees/db_tree.tcl
mcset es {Move index} {Move index}

### File: ../src/trees/db_tree.tcl
mcset es {Copy trigger} {Copy trigger}

### File: ../src/trees/db_tree.tcl
mcset es {Move trigger} {Move trigger}

### File: ../src/trees/db_tree.tcl
mcset es {Copy table '%s' to database '%s' (include data, indexes and triggers)} {Copy table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset es {Copy table '%s' to database '%s' (include data)} {Copy table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset es {Copy table '%s' to database '%s' (include indexes and triggers)} {Copy table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset es {Copy table '%s' to database '%s' (skip data, indexes and triggers)} {Copy table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset es {Move table '%s' to database '%s' (include data, indexes and triggers)} {Move table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset es {Move table '%s' to database '%s' (include data)} {Move table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset es {Move table '%s' to database '%s' (include indexes and triggers)} {Move table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset es {Move table '%s' to database '%s' (skip data, indexes and triggers)} {Move table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset es {Copying table...} {Copying table...}

### File: ../src/trees/db_tree.tcl
mcset es {Copying table '%s' from '%s' to '%s'.} {Copying table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset es {Moving table...} {Moving table...}

### File: ../src/trees/db_tree.tcl
mcset es {Moving table '%s' from '%s' to '%s'.} {Moving table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset es {Could not create object in target database:
%s} {Could not create object in target database:
%s}

### File: ../src/trees/db_tree.tcl
mcset es {Could not copy data:
%s} {Could not copy data:
%s}

### File: ../src/trees/db_tree.tcl
mcset es {Could not copy table data from source database to target database. Details: %s} {Could not copy table data from source database to target database. Details: %s}

### File: ../src/trees/db_tree.tcl
mcset es {Could not delete object(s) from source database. Details: %s} {Could not delete object(s) from source database. Details: %s}

### File: ../src/grids/dbgrid.tcl
mcset es {Edit BLOB entry:} {Editar entrada BLOB:}

### File: ../src/grids/dbgrid.tcl
mcset es {BLOB edit} {Editar BLOB}

### File: ../src/grids/dbgrid.tcl
mcset es {Cannot commit. Details:
%s} {Cannot commit. Details:
%s}

### File: ../src/grids/grid.tcl
mcset es {You have to select a cell before paste any contents.} {Debes seleccionar una celda antes de poder pegar cualquier contenido.}

### File: ../src/grids/grid.tcl
mcset es {Cut data} {Cortar datos}

### File: ../src/grids/grid.tcl
mcset es {There are too many columns or rows to paste. Do you want to cut them and paste?} {Hay demasiadas Columnas o filas para pegar. ¿Deseas cortarlos y pegarlos?}

### File: ../src/grids/data_grid.tcl
mcset es {Insert new row} {Insertar nueva fila}

### File: ../src/grids/data_grid.tcl
mcset es {Delete selected rows} {Eliminar filas seleccionadas}

### File: ../src/grids/data_grid.tcl
mcset es {Edit cell value} {Editar valor de la celda}

### File: ../src/grids/data_grid.tcl
mcset es {Edit cell value in BLOB editor} {Edit cell value in BLOB editor}

### File: ../src/grids/data_grid.tcl
mcset es {Duplicate row} {Duplicar fila}

### File: ../src/grids/data_grid.tcl
mcset es {Set NULL value} {Poner a NULO}

### File: ../src/grids/data_grid.tcl
mcset es {Generate SELECT from selected cells} {Generate SELECT from selected cells}

### File: ../src/grids/data_grid.tcl
mcset es {Commit selected cells} {Commit selected cells}

### File: ../src/grids/data_grid.tcl
mcset es {Rollback selected cells} {Rollback selected cells}

### File: ../src/grids/data_grid.tcl
mcset es {Select all} {Select all}

### File: ../src/grids/data_grid.tcl
mcset es {Show ordinals} {Show ordinals}

### File: ../src/grids/data_grid.tcl
mcset es {Show ROWIDs} {Show ROWIDs}

### File: ../src/grids/data_grid.tcl
mcset es Type: Type:

### File: ../src/grids/data_grid.tcl
mcset es Constraints: Restricciones:

### File: ../src/grids/data_grid.tcl
mcset es {%s column has NOT NULL constraint. You have to fill value for it.} {La Columna %s tiene la restricción NO NULO. Debes introducir un valor para ella.}

### File: ../src/grids/data_grid.tcl
mcset es {Error while adding new row:
%s} {Error al añadir nueva fila:
%s}

### File: ../src/grids/data_grid.tcl
mcset es {Error while updating new row:
%s} {Error while updating new row:
%s}

### File: ../src/grids/data_grid.tcl
mcset es {Error while updating cell value:
%s

What would you like to do?} {Error actualizando el valor de la celda:
%s

¿Qué quieres hacer?}

### File: ../src/grids/data_grid.tcl
mcset es {Re-edit value} {Re-editar valor}

### File: ../src/grids/data_grid.tcl
mcset es {Return to value before edition} {Revertir al valor anterior a la edición}

### File: ../src/grids/data_grid.tcl
mcset es {Cannot delete row(s), because it violates constraint. Details:
%s} {Cannot delete row(s), because it violates constraint. Details:
%s}

### File: ../src/grids/data_grid.tcl
mcset es {Error while deleting selected rows:
%s} {Error borrando las filas seleccionadas:
%s}

### File: ../src/grids/data_grid.tcl
mcset es {SQL query generated at %s
using selected cells from window '%s'.} {SQL query generated at %s
using selected cells from window '%s'.}

### File: ../src/grids/result_grid.tcl
mcset es {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.} {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.}

### File: ../src/grids/result_grid.tcl
mcset es {Data type:} {Data type:}

### File: ../src/grids/result_grid.tcl
mcset es {No details are available on this cell.} {No details are available on this cell.}

### File: ../src/grids/result_grid.tcl
mcset es {Duplicated ROWID} {ID de Fila \"ROWID\" Duplicado}

### File: ../src/grids/result_grid.tcl
mcset es {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?} {Hay más de una fila con ROWID=%s afectadas por la operación de pegado.
Esto puede ocasionar resultados impredecibles. ¿Proceder?}

### File: ../src/grids/result_grid.tcl
mcset es {Could not parse SQL while trying to generate requested query: %s} {Could not parse SQL while trying to generate requested query: %s}

### File: ../src/grids/result_grid.tcl
mcset es {Cannot use '%s' statement to generate requested query.} {Cannot use '%s' statement to generate requested query.}

### File: ../src/grids/result_grid.tcl
mcset es {Cannot determinate selected column with ID=%s.} {Cannot determinate selected column with ID=%s.}

### File: ../src/grids/result_grid.tcl
mcset es {Error occurred while trying to generate the query: %s} {Error occurred while trying to generate the query: %s}

### File: ../src/grids/result_grid.tcl
mcset es {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s} {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s}
