# SQLiteStudio 'fr_fr' localization file

# Unchanged translations

### File: ../src/win_assoc.tcl
mcset fr_fr {File associations} {File associations}

### File: ../src/win_assoc.tcl
mcset fr_fr {Following file extensions could not be associated to the current SQLiteStudio version:
%s} {Following file extensions could not be associated to the current SQLiteStudio version:
%s}

### File: ../src/win_assoc.tcl
mcset fr_fr {Click the link below to find out what is possible reason and solutions.} {Click the link below to find out what is possible reason and solutions.}

### File: ../src/cfg_win.tcl
mcset fr_fr Ok Ok

### File: ../src/cfg_win.tcl
mcset fr_fr Apply Appliquer

### File: ../src/cfg_win.tcl
mcset fr_fr Cancel Annuler

### File: ../src/cfg_win.tcl
mcset fr_fr Theme Thème

### File: ../src/cfg_win.tcl
mcset fr_fr {Select theme to use:} {Sélectionner le thème:}

### File: ../src/cfg_win.tcl
mcset fr_fr {Theme version:} {Version du thème:}

### File: ../src/cfg_win.tcl
mcset fr_fr Shortcuts Raccourcis

### File: ../src/cfg_win.tcl
mcset fr_fr {Global shortcuts} {Raccourcis globaux}

### File: ../src/cfg_win.tcl
mcset fr_fr {Open SQL editor} {Lancer d'éditeur SQL}

### File: ../src/cfg_win.tcl
mcset fr_fr {Opens SQL editor window.} {Lancer les éditeurs SQL}

### File: ../src/cfg_win.tcl
mcset fr_fr {Close selected task} {Fermer la tâche}

### File: ../src/cfg_win.tcl
mcset fr_fr {Closes active MDI window.} {Fermer la fenêtre MDI active}

### File: ../src/cfg_win.tcl
mcset fr_fr {Restore last closed task} {Restore last closed task}

### File: ../src/cfg_win.tcl
mcset fr_fr {Restores last closed MDI window.} {Restores last closed MDI window.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Open settings} {Ouvrir la configuration}

### File: ../src/cfg_win.tcl
mcset fr_fr {Opens SQLiteStudio settings window.} {Ouvrir les configurations SQLiteStudio}

### File: ../src/cfg_win.tcl
mcset fr_fr {Next task} {Prochaine tâche}

### File: ../src/cfg_win.tcl
mcset fr_fr {Switches task (window) to next, placed on the right from active task on taskbar.} {Basculer la prochaine tâche (window) , placée à doite de celle active sur la barre des tâches.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Next task (alternative)} {Prochaine tâche (alternative)}

### File: ../src/cfg_win.tcl
mcset fr_fr {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Basculer la prochaine tâche (window) , placée à doite de celle active sur la barre des tâches.
C'est un raccourci alternatif. Effectue la même action que ci-dessus.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Previous task} {Tâche précédante}

### File: ../src/cfg_win.tcl
mcset fr_fr {Switches task (window) to previous, placed on the left from active task on taskbar.} {Basculer la prochaine tâche (window) , placée à gauche de celle active sur la barre des tâches.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Previous task (alternative)} {Tâche précédante (alternatif)}

### File: ../src/cfg_win.tcl
mcset fr_fr {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Basculer la prochaine tâche (window) , placée à gauche de celle active sur la barre des tâches.
C'est un raccourci alternatif. Effectue la même action que ci-dessus.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Editor and table window shortcuts} {Raccourcis des fenêtres éditeur et table}

### File: ../src/cfg_win.tcl
mcset fr_fr {SQL editor completion} {Achévement de l'éditeur SQL}

### File: ../src/cfg_win.tcl
mcset fr_fr {Invokes SQL completion in editor window.} {Invoque l'achévement de fenêtre de l'éditeur SQL.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Execute SQL query} {Exécution d'une requête SQL}

### File: ../src/cfg_win.tcl
mcset fr_fr {Executes SQL query typed in editor.} {Exécuter la requête SQL saisie dans l'éditeur.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Explain SQL query} {Analyser la requête SQL}

### File: ../src/cfg_win.tcl
mcset fr_fr {Calls EXPLAIN on SQL query typed in editor.} {Appel du commentaire de la requête saisie dans l'éditeur.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Format SQL code} {Format code SQL}

### File: ../src/cfg_win.tcl
mcset fr_fr {Formats SQL code typed in editor.} {Formats des codes SQL saisis dans l'éditeur.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Load SQL from file} {Charger le SQL du fichier}

### File: ../src/cfg_win.tcl
mcset fr_fr {Loads SQL from file to the editor.} {Charger le SQL du fichier de l'éditeur.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Save SQL to file} {Enregistrer le SQL dans le fichier}

### File: ../src/cfg_win.tcl
mcset fr_fr {Saves contents of the editor into a file.} {Enregistrer le contenu de l'éditeur dans le fichier.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Execute SQL from file} {Exécute SQL du fichier}

### File: ../src/cfg_win.tcl
mcset fr_fr {Executes SQL directly from file, without loading it to the editor.} {Exécuter le SQL directement du fichier, sans le charger dans l'éditeur.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Next tab} {Onglet suivant}

### File: ../src/cfg_win.tcl
mcset fr_fr {Switches to next tab of editor window (result or history).} {Basculer sur l'onglet suivant (resultat ou historique).}

### File: ../src/cfg_win.tcl
mcset fr_fr {Previous tab} {Onglet précédant}

### File: ../src/cfg_win.tcl
mcset fr_fr {Switches to previous tab of editor window (query or result).} {Basculer vers l'onglet précédent de l'éditeur (requête ou résultats).}

### File: ../src/cfg_win.tcl
mcset fr_fr {Next subtab} {Sous-table suivante}

### File: ../src/cfg_win.tcl
mcset fr_fr {Switches to next subtab (form view in results tab).} {Switches to next subtab (form view in results tab).}

### File: ../src/cfg_win.tcl
mcset fr_fr {Previous subtab} {Sous onglet précédante}

### File: ../src/cfg_win.tcl
mcset fr_fr {Switches to previous subtab (grid view in results tab).} {Basculer vers le sous onglet précédent (Onglet résultat tableau vue).}

### File: ../src/cfg_win.tcl
mcset fr_fr Refresh Actualiser

### File: ../src/cfg_win.tcl
mcset fr_fr {Re-executes SQL query so results data is refreshed.} {Re-exécuter la requête SQL les résultats sont actualisés.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Delete selected row} {Supprimer la ligne sélectionnée}

### File: ../src/cfg_win.tcl
mcset fr_fr {Deletes selected row.} {Supprimer la ligne}

### File: ../src/cfg_win.tcl
mcset fr_fr {Add new row} {Ajout d'une ligne}

### File: ../src/cfg_win.tcl
mcset fr_fr {Adds new empty row without commiting it.} {Ajouter une nouvelle ligne sans la valider.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Erase cells data} {Supprimer les données}

### File: ../src/cfg_win.tcl
mcset fr_fr {Erases data of selected cells.} {Supprimer les données sélectionnées}

### File: ../src/cfg_win.tcl
mcset fr_fr {Next editor database in list} {Next editor database in list}

### File: ../src/cfg_win.tcl
mcset fr_fr {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)} {Basculer à la prochaine base de données 
(it's drop-down list on top of the editor window)}

### File: ../src/cfg_win.tcl
mcset fr_fr {Previous editor database in list} {Précedent éditeur de la liste de base de données}

### File: ../src/cfg_win.tcl
mcset fr_fr {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)} {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)}

### File: ../src/cfg_win.tcl
mcset fr_fr {Commit edition in Form View} {Valider la mise à jour du formulaire vue}

### File: ../src/cfg_win.tcl
mcset fr_fr {Commits edition in Form View of query results or table data preview.} {Commits edition in Form View of query results or table data preview.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Rollback edition in Form View} {Annuler la mise à jour dans le formulaire vue}

### File: ../src/cfg_win.tcl
mcset fr_fr {Rolls back edition in Form View of query results or table data preview.} {Rolls back edition in Form View of query results or table data preview.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Jump to first row in Form View} {Aller à la premiére ligne du formulaire vue}

### File: ../src/cfg_win.tcl
mcset fr_fr {Jumps to first row of query results grid
or table data preview grid in Form View.} {Jumps to first row of query results grid
or table data preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Go to previous row in Form View} {Aller à la ligne suivante du formulaire vue}

### File: ../src/cfg_win.tcl
mcset fr_fr {Goes to previous row of query results grid
or table data preview grid row in Form View.} {Goes to previous row of query results grid
or table data preview grid row in Form View.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Go to next row in Form View} {Aller à la prochaine ligne dans la vue}

### File: ../src/cfg_win.tcl
mcset fr_fr {Goes to next row of query results grid
or table data preview grid row in Form View.} {Aller à la prochaine ligne de la requête dans le tableau
ou la table de données en mode vue.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Jump to last row in Form View} {Va à la dernère ligne de la vue}

### File: ../src/cfg_win.tcl
mcset fr_fr {Jumps to last row of query results grid
or table data preview grid in Form View.} {Aller à la dernière ligne du tableau de la requête
or table data preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Switch NULL value in form edit field} {Switch NULL value in form edit field}

### File: ../src/cfg_win.tcl
mcset fr_fr {Sets or unsets NULL value in currently selected
column in form view data edit mode.} {Sets or unsets NULL value in currently selected
column in form view data edit mode.}

### File: ../src/cfg_win.tcl
mcset fr_fr Plugins Extensions

### File: ../src/cfg_win.tcl
mcset fr_fr {SQL formatter plugins} {Extensions de formatage SQL}

### File: ../src/cfg_win.tcl
mcset fr_fr {Use following SQL formatter plugin:} {Utiliser l'extension de format SQL suivant:}

### File: ../src/cfg_win.tcl
mcset fr_fr {Configure formatter plugin} {Configurer extension format}

### File: ../src/cfg_win.tcl
mcset fr_fr Configure Configuration

### File: ../src/cfg_win.tcl
mcset fr_fr {Populating plugins} {Remplir les extensions}

### File: ../src/cfg_win.tcl
mcset fr_fr {Default table populating plugin:} {Default table populating plugin:}

### File: ../src/cfg_win.tcl
mcset fr_fr Miscellaneous Divers

### File: ../src/cfg_win.tcl
mcset fr_fr {Restore session after next start} {Rétablir la session au prochain démarrage}

### File: ../src/cfg_win.tcl
mcset fr_fr {All windows and their contents (such as SQL code)
will be restored while next application startup.} {All windows and their contents (such as SQL code)
will be restored while next application startup.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Show line numbers in SQL editor} {Afficher les N° de lignes dans l'éditeur SQL}

### File: ../src/cfg_win.tcl
mcset fr_fr {All SQL editor windows will contain line numbers on the left side of window.} {Tous les fenêtres éditeur contiendront les N° de ligne coté gauche.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Underline syntax errors in SQL editor} {Souligner la synataxe erreur dans l'éditeur SQL}

### File: ../src/cfg_win.tcl
mcset fr_fr {Makes errors to be marked with underline.
You can also define foreground and background color for errors.} {Les erreurs sont marquées comme soulignées .
Vous pouver aussi définir la couleur du Premier et de l'arrière plan en erreur.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Show SQLite system tables and indexes in databases tree} {Afficher les tables et index système dans l'arbre de base de données}

### File: ../src/cfg_win.tcl
mcset fr_fr {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.} {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Open items with single mouse click in databases tree} {Ouvrir les objets de l'arbre par un simple clic}

### File: ../src/cfg_win.tcl
mcset fr_fr {Items in database tree are open by double click by default.
This option switches it to single click.} {Items in database tree are open by double click by default.
This option switches it to single click.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Show ROWID as default instead of row order number in table data view} {Show ROWID as default instead of row order number in table data view}

### File: ../src/cfg_win.tcl
mcset fr_fr {This option affects first column from the left on the data tab of the table window.} {This option affects first column from the left on the data tab of the table window.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Do not show 'did you know that...' dialog at startup.} {Ne pas afficher 'Savez-vous...' de la fenêtre de dialogue au démarrage.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Uncheck this option to show the dialog.} {Ne vérifie cette option pour montrer le dialogue.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Check for updates at startup.} {Vérification des mises à jour au démarrage.}

### File: ../src/cfg_win.tcl
mcset fr_fr {If enabled, application will will check
for new version available at startup.} {Si coché, l'application vérifira les nouvelles mises à jour 
au démarrage.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Sort custom SQL functions list by name} {Tri par nom la liste des fonctions SQL personnalisées}

### File: ../src/cfg_win.tcl
mcset fr_fr {This list is placed in Custom SQL funcions dialog.} {Cette liste est située dans la personnalisation de la fenêtre
de dialogue des fonctions SQL.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Select all contents when editing the table cell} {Select all contents when editing the table cell}

### File: ../src/cfg_win.tcl
mcset fr_fr {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.} {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Ask if clipboard contents should be cut} {Demandez si le contenu de presse-papiers doit être coupé}

### File: ../src/cfg_win.tcl
mcset fr_fr {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.} {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Rows per page in Table Window and Editor Results:} {Rows per page in Table Window and Editor Results:}

### File: ../src/cfg_win.tcl
mcset fr_fr {More results per page causes slower loading of single data page. Value 1000 should be right.} {Plus de résultats par page ralenti le système. La valeur correct est 1000.}

### File: ../src/cfg_win.tcl
mcset fr_fr {History entries limit:} {Limite des entrées d'historique:}

### File: ../src/cfg_win.tcl
mcset fr_fr {Number of rows to remember in SQL editor history.} {Nombre de lignes à garder dans l'éditeur d'historique.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Insertion cursor blinking period (milliseconds):} {Insertion cursor blinking period (milliseconds):}

### File: ../src/cfg_win.tcl
mcset fr_fr {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.} {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Web browser:} {Explorateur internet}

### File: ../src/cfg_win.tcl
mcset fr_fr {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.} {Vous pouvez saisir votre explorateur ici. Le chemin complet doit être saisi.
L'adresse à ouvrir sera passée à la commande en argument.}

### File: ../src/cfg_win.tcl
mcset fr_fr Language: Langage:

### File: ../src/cfg_win.tcl
mcset fr_fr {Tab in table window on open:} {Onglet actif à l'ouverture de la fenêtre table:}

### File: ../src/cfg_win.tcl
mcset fr_fr {Table structure} {Structure Table}

### File: ../src/cfg_win.tcl
mcset fr_fr {Table data} {Données Table}

### File: ../src/cfg_win.tcl
mcset fr_fr {Select which tab should be opened for start in table window,
when you just opened that window.} {Sélectionne quelle onglet sera ouvert .
au lancement de la fenêtre Table.}

### File: ../src/cfg_win.tcl
mcset fr_fr {View default display mode:} {View default display mode:}

### File: ../src/cfg_win.tcl
mcset fr_fr {Edition dialog} {Edition dialog}

### File: ../src/cfg_win.tcl
mcset fr_fr {Data view} {Data view}

### File: ../src/cfg_win.tcl
mcset fr_fr {Defines what is displayed by default when user opens a view.} {Defines what is displayed by default when user opens a view.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Editor window results layout} {Préférences de la fenêtre de l'éditeur de résultat}

### File: ../src/cfg_win.tcl
mcset fr_fr {Show results in separated tab} {Affiche les résultats dans un onglet séparé}

### File: ../src/cfg_win.tcl
mcset fr_fr {Show results in frame below query} {Affiche les résultats dans le cadre sous la requête }

### File: ../src/cfg_win.tcl
mcset fr_fr {Database tree display mode} {Database tree display mode}

### File: ../src/cfg_win.tcl
mcset fr_fr {Show indexes and triggers linked under referenced table.} {Show indexes and triggers linked under referenced table.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Show indexes and triggers in their own groups.} {Show indexes and triggers in their own groups.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Show column names linked under the table.} {Show column names linked under the table.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Plain text results} {Résultats texte tronqués}

### File: ../src/cfg_win.tcl
mcset fr_fr {Display NULL values as:} {Afficher les valeurs NULL comme:}

### File: ../src/cfg_win.tcl
mcset fr_fr {Maximum column width:} {Largeur maximale des colonnes:}

### File: ../src/cfg_win.tcl
mcset fr_fr {Values longer than specified here will be cut in plain text results.} {Les valeurs plus longues qu'indiquées ici seront tronquées.}

### File: ../src/cfg_win.tcl
mcset fr_fr Colors Couleurs

### File: ../src/cfg_win.tcl
mcset fr_fr {Global colors} {Couleur globale}

### File: ../src/cfg_win.tcl
mcset fr_fr {MDI windows title bar background color} {Couleur de l'arriére plan du titre de la fenêtre MDI}

### File: ../src/cfg_win.tcl
mcset fr_fr {MDI windows title bar foreground color} {Couleur du premier plan du titre de la fenêtre MDI}

### File: ../src/cfg_win.tcl
mcset fr_fr {MDI windows title bar button background color} {Couleur de l'arriére plan de la barre d'outil de la fenêtre MDI}

### File: ../src/cfg_win.tcl
mcset fr_fr {MDI windows title bar active button background color} {Couleur du premier plan de la barre d'outil de la fenêtre MDI}

### File: ../src/cfg_win.tcl
mcset fr_fr {SQL Editor} {Editeur SQL}

### File: ../src/cfg_win.tcl
mcset fr_fr {Editor standard font color} {Couleur standard de la police}

### File: ../src/cfg_win.tcl
mcset fr_fr {Editor background} {Arrière plan de l'éditeur}

### File: ../src/cfg_win.tcl
mcset fr_fr {Selected foreground color} {Sélectionner la couleur de premier plan}

### File: ../src/cfg_win.tcl
mcset fr_fr {Selected background color} {Sélectionner la couleur d'arrière plan}

### File: ../src/cfg_win.tcl
mcset fr_fr {Disabled background color} {Déastiver la couleur d'arrière plan}

### File: ../src/cfg_win.tcl
mcset fr_fr {Tables color} {Couleur tables}

### File: ../src/cfg_win.tcl
mcset fr_fr {Brackets color} {Couleur parenthèses}

### File: ../src/cfg_win.tcl
mcset fr_fr {Square brackets color} {Couleur crochets}

### File: ../src/cfg_win.tcl
mcset fr_fr {Keywords color} {Couleur mots clé}

### File: ../src/cfg_win.tcl
mcset fr_fr {Variables color} {Couleur variables}

### File: ../src/cfg_win.tcl
mcset fr_fr {Strings color} {Couleur texte}

### File: ../src/cfg_win.tcl
mcset fr_fr {Comments color} {Couleur commentaire}

### File: ../src/cfg_win.tcl
mcset fr_fr {Matched brackets foreground color} {Couleur de premier plan des parenthèses}

### File: ../src/cfg_win.tcl
mcset fr_fr {Matched brackets background color} {Couleur d'arrière plan des parenthèses}

### File: ../src/cfg_win.tcl
mcset fr_fr {Syntax error color} {Syntaxe couleur en erreur}

### File: ../src/cfg_win.tcl
mcset fr_fr {Tcl editor} {Editeur Tcl}

### File: ../src/cfg_win.tcl
mcset fr_fr {Options color} {Options couleur}

### File: ../src/cfg_win.tcl
mcset fr_fr {Quoted character color} {Couleur des caractéres entre quote}

### File: ../src/cfg_win.tcl
mcset fr_fr {Trees colors} Arbre

### File: ../src/cfg_win.tcl
mcset fr_fr {Tree background} {Couleur arrier plan Arbre}

### File: ../src/cfg_win.tcl
mcset fr_fr {Tree standard font color} {Couleur standard Arbre}

### File: ../src/cfg_win.tcl
mcset fr_fr {Tree selected background color} {Couleur d'arrière plan sélectionnée}

### File: ../src/cfg_win.tcl
mcset fr_fr {Tree selected foreground color} {Couleur de premier plan sélectionnée}

### File: ../src/cfg_win.tcl
mcset fr_fr {Color for number of objects in tree branch} {Couleur du nombre d'objets d'une branche d'arbre}

### File: ../src/cfg_win.tcl
mcset fr_fr {Grids colors} Tableaux

### File: ../src/cfg_win.tcl
mcset fr_fr {Grid background} {Arrière plan de tableau}

### File: ../src/cfg_win.tcl
mcset fr_fr {Grid standard font color} {Couleur standard de police de tableau}

### File: ../src/cfg_win.tcl
mcset fr_fr {Grid selected background color} {Couleur d'arrière plan sélectionnée}

### File: ../src/cfg_win.tcl
mcset fr_fr {Grid selected foreground color} {Couleur de premier plan sélectionnée}

### File: ../src/cfg_win.tcl
mcset fr_fr {Grid base column background color} {Couleur d'arrière plan de la base de colonne du tableau}

### File: ../src/cfg_win.tcl
mcset fr_fr {Foreground color for cells with NULL value} {Couleur de premier plan pour les cellule NULL}

### File: ../src/cfg_win.tcl
mcset fr_fr {Status fields colors} Status

### File: ../src/cfg_win.tcl
mcset fr_fr {Background color} {Couleur d'arrière plan}

### File: ../src/cfg_win.tcl
mcset fr_fr {Foreground color} {Couleur de premier plan}

### File: ../src/cfg_win.tcl
mcset fr_fr {Error foreground color} {Erreur couleur de l'arrière plan}

### File: ../src/cfg_win.tcl
mcset fr_fr {Information foreground color} {Couleur d'arrière plan d'information}

### File: ../src/cfg_win.tcl
mcset fr_fr {Information (second kind) foreground color} {Information (second kind) foreground color}

### File: ../src/cfg_win.tcl
mcset fr_fr {Miscellaneous colors} Divers

### File: ../src/cfg_win.tcl
mcset fr_fr {Context hints background color} {Couleur d'arrière plan des conseils}

### File: ../src/cfg_win.tcl
mcset fr_fr {Context hints foreground color} {Couleur de premier plan des conseils}

### File: ../src/cfg_win.tcl
mcset fr_fr Fonts Polices

### File: ../src/cfg_win.tcl
mcset fr_fr {SQL editor font} {Police de l'éditeur SQL}

### File: ../src/cfg_win.tcl
mcset fr_fr {Status fields font} {Police Status}

### File: ../src/cfg_win.tcl
mcset fr_fr {Grid font} {Police de tableau}

### File: ../src/cfg_win.tcl
mcset fr_fr {Tree font} {Police d'arbre}

### File: ../src/cfg_win.tcl
mcset fr_fr {Tree additional labels font} {Tree additional labels font}

### File: ../src/cfg_win.tcl
mcset fr_fr {Context hints font} {Police des conseils}

### File: ../src/cfg_win.tcl
mcset fr_fr {Changed language needs application to be restarted.} {Le changement de langage demande le redémarrage de l'application.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.} {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.}

### File: ../src/cfg_win.tcl
mcset fr_fr {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.} {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.}

### File: ../src/cfg_win.tcl
mcset fr_fr {SQL formatter options} {SQL formatter options}

### File: ../src/db/db_file_types.tcl
mcset fr_fr {All SQLite Databases} {Toutes les bases de données SQLite}

### File: ../src/db/db_file_types.tcl
mcset fr_fr {SQLite 3 Databases} {Base de données SQLite 3}

### File: ../src/db/db_file_types.tcl
mcset fr_fr {SQLite 2 Databases} {Base de donnéesSQLite 2}

### File: ../src/db/db_file_types.tcl
mcset fr_fr {All files} {Tous les fichiers}

### File: ../src/db/query_executor.tcl
mcset fr_fr {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.} {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.}

### File: ../src/db/query_executor.tcl
mcset fr_fr {Invalid database name: %s} {Nom de base de données invalide : %s}

### File: ../src/db/query_executor.tcl
mcset fr_fr {Imbalanced 'BEGIN' ocurrence in query.} {Imbalanced 'BEGIN' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset fr_fr {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.} {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset fr_fr {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.} {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset fr_fr {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.} {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset fr_fr {Cannot use more than one 'BEGIN'.} {Cannot use more than one 'BEGIN'.}

### File: ../src/db/query_executor.tcl
mcset fr_fr {Imbalanced 'COMMIT' ocurrence in query.} {Imbalanced 'COMMIT' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset fr_fr {Imbalanced 'ROLLBACK' ocurrence in query.} {Imbalanced 'ROLLBACK' ocurrence in query.}

### File: ../src/db/sqlite2.tcl
mcset fr_fr {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)} {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)}

### File: ../src/db/db.tcl
mcset fr_fr {An internal logic error in SQLite} {Erreur de logique interne dans SQLite}

### File: ../src/db/db.tcl
mcset fr_fr {Access permission denied} {Permission d'accès refusée}

### File: ../src/db/db.tcl
mcset fr_fr {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.} {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.}

### File: ../src/db/db.tcl
mcset fr_fr {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.} {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.}

### File: ../src/db/db.tcl
mcset fr_fr {A malloc() failed} {Ein malloc() ist fehlgeschlagen}

### File: ../src/db/db.tcl
mcset fr_fr {Attempt to write a readonly database} {Tentative d'écriture sur une base de données en lecture seule}

### File: ../src/db/db.tcl
mcset fr_fr {Disk I/O error occurred} {Erreur I/O disque}

### File: ../src/db/db.tcl
mcset fr_fr {The database disk image is malformed} {L'image disque de la base de données est male formatée}

### File: ../src/db/db.tcl
mcset fr_fr {Database is full} {La base de données est pleine}

### File: ../src/db/db.tcl
mcset fr_fr {Unable to open the database file} {Unable to open the database file}

### File: ../src/db/db.tcl
mcset fr_fr {Database lock protocol error} {Database lock protocol error}

### File: ../src/db/db.tcl
mcset fr_fr {Database is empty} {Base de données vide}

### File: ../src/db/db.tcl
mcset fr_fr {The database schema changed} {Schema de la base de données changé}

### File: ../src/db/db.tcl
mcset fr_fr {String or BLOB exceeds size limit} {String or BLOB exceeds size limit}

### File: ../src/db/db.tcl
mcset fr_fr {Library used incorrectly} {Library used incorrectly}

### File: ../src/db/db.tcl
mcset fr_fr {Uses OS features not supported on host} {Uses OS features not supported on host}

### File: ../src/db/db.tcl
mcset fr_fr {Authorization denied} {Authorization denied}

### File: ../src/db/db.tcl
mcset fr_fr {Auxiliary database format error} {Auxiliary database format error}

### File: ../src/db/db.tcl
mcset fr_fr {2nd parameter to sqlite3_bind out of range} {2nd parameter to sqlite3_bind out of range}

### File: ../src/db/db.tcl
mcset fr_fr {File opened that is not a database file} {Bei der geöffneten Datei handelt es sich nicht um eine Datenbank}

### File: ../src/db/db.tcl
mcset fr_fr {Error while opening %s database:
%s} {Erreur lors de l'ouverture de la base de données:
%s}

### File: ../src/db/db.tcl
mcset fr_fr {Not enough parameters passed to function '%s'.} {Nicht genug Parameter für Funktion '%s'.}

### File: ../src/db/db.tcl
mcset fr_fr {Cannot read file: %s} {Kann Datei %s nicht lesen}

### File: ../src/db/db.tcl
mcset fr_fr {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.} {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.}

### File: ../src/db/db.tcl
mcset fr_fr {Could not attach database %s. Error message from SQLite:
%s} {Could not attach database %s. Error message from SQLite:
%s}

### File: ../src/db/db.tcl
mcset fr_fr {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.} {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.}

### File: ../src/db/sqlite3.tcl
mcset fr_fr {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)} {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)}

### File: ../src/completion_routines.tcl
mcset fr_fr {Problem with attaching database:
%s} {Problem with attaching database:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Error from importing plugin:
%s} {Error from importing plugin:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Error creating table '%s':
%s

Importing aborted.} {Error creating table '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Error trying to import data to '%s':
%s

Importing aborted.} {Error trying to import data to '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr Importing... Importing...

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Importing to table '%s'.} {Importing to table '%s'.}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?} {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?} {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Problem occured while importing row number %s:
%s

What would you like to do?} {Problem occured while importing row number %s:
%s

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Importing finished.} {Importing finished.}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Import problem} {Import problem}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Skip this data row} {Skip this data row}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Keep data rows imported so far (%s) and abort} {Keep data rows imported so far (%s) and abort}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Rollback data rows imported so far and abort} {Rollback data rows imported so far and abort}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr {Ignore it and proceed} {Ignore it and proceed}

### File: ../src/plugins/import_plugin.tcl
mcset fr_fr Abort Abandonner

### File: ../src/plugins/sql_formatting/enterprise/format_s.tcl
mcset fr_fr name Nom

### File: ../src/plugins/sql_formatting/basic.tcl
mcset fr_fr {Reduce group of whitespaces into one whitespace.} {Reduce group of whitespaces into one whitespace.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset fr_fr {Uppercase keywords.} {Großgeschriebene Schlüsselwörter.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset fr_fr {Separate ")" and after contents with single whitespace.} {Separate ")" and after contents with single whitespace.}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {SQLite3 only} {Nur SQLite3}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr Indentation Einrückung

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {New lines} {Neue Linien}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {White spaces} Leerzeichen

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr Names Nom

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr Comments Kommentare

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Tab size:} Tabgröße:

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Line up keywords in multi-line queries} {Line up keywords in multi-line queries}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Ident contents of parenthesis block} {Ident contents of parenthesis block}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Ident parenthesis block in new line} {Ident parenthesis block in new line}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Before opening parenthesis in column definitions} {Before opening parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After opening parenthesis in column definitions} {After opening parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Before closinging parenthesis in column definitions} {Before closinging parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After closinging parenthesis in column definitions} {After closinging parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Before opening parenthesis in expressions} {Before opening parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After opening parenthesis in expressions} {After opening parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Before closinging parenthesis in expressions} {Before closinging parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After closinging parenthesis in expressions} {After closinging parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After comma} {Nach Komma}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After comma in function arguments list} {After comma in function arguments list}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After logical block of query} {After logical block of query}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After semicolon} {Nach Semikolon}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Never before semicolon} {Niemals vor Semikolon}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Before comma in lists} {Vor dem Komma in der Liste}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After comma in lists} {Nach dem Komma in der Liste}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Before opening parenthesis} {Before opening parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After opening parenthesis} {After opening parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Before closing parenthesis} {Before closing parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After closing parenthesis} {After closing parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Before dot operator (in path to database object)} {Before dot operator (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After dot operator (in path to database object)} {After dot operator (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Before mathematical operator} {Before mathematical operator}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {After mathematical operator} {After mathematical operator}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Uppercase keywords} {Großgeschriebene Schlüsselwörter}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Uppercase datatype names} {Noms de type de données en majuscules }

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Always use name wrapping} {Always use name wrapping}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Preferred name wrapper} {Preferred name wrapper}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Expand one line comments (/* ... */) to multiline} {Erweitere einzeilige Kommentare (/* ... */) zu mehrzeiligen Kommentaren}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Indent multi line comments} {Indent multi line comments}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset fr_fr {Use "*" character for each line} {Benutze das "*" Zeichen für jede Linie}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {, (comma)} {, (Komma)}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {; (semicolon)} {; (Semikolon)}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {\t (tab)} {\t (Tab)}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {  (white-space)} {  (Leerzeichen)}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr Custom Eigen

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Input file} {Input file}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr Browse ...

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Show options} {Show options}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Column names} {Column names}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Treat first row as column names} {Treat first row as column names}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.} {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Columns separator:} {Spalten Trennzeichen:}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.} {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {NULL handling} {NULL handling}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Treat following values as NULL:} {Treat following values as NULL:}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr Workarounds Workarounds

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Expect Microsoft format of CSV} {Expect Microsoft format of CSV}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.} {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr Encoding Encoding

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Convert from encoding:} {Convert from encoding:}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Input file cannot be empty.} {Input file cannot be empty.}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Input file is not readable.} {Input file is not readable.}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {CSV separator cannot be empty.} {CSV Trennzeichen darf nicht leer sein.}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {CSV files} {CSV files}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {Text files} {Text files}

### File: ../src/plugins/import/csv.tcl
mcset fr_fr {File to import from} {File to import from}

### File: ../src/plugins/import/dbf.tcl
mcset fr_fr Auto-detect Auto-detect

### File: ../src/plugins/import/dbf.tcl
mcset fr_fr {dBase files} {dBase files}

### File: ../src/plugins/import/regexp.tcl
mcset fr_fr {Regular expression} {Regular expression}

### File: ../src/plugins/import/regexp.tcl
mcset fr_fr {Visual editor} {Visual editor}

### File: ../src/plugins/import/regexp.tcl
mcset fr_fr {Use Regular Expression Groups to identify columns.} {Use Regular Expression Groups to identify columns.}

### File: ../src/plugins/import/regexp.tcl
mcset fr_fr {Case insensitive} {Case insensitive}

### File: ../src/plugins/import/regexp.tcl
mcset fr_fr Help Aide

### File: ../src/plugins/import/regexp.tcl
mcset fr_fr {RegExp error:
%s} {RegExp error:
%s}

### File: ../src/plugins/export/xls.tcl
mcset fr_fr {Column names as first row} {Nom de colonne comme première ligne}

### File: ../src/plugins/export/xls.tcl
mcset fr_fr {If enabled, then first row of exported document will be a list of column names.} {If enabled, then first row of exported document will be a list of column names.}

### File: ../src/plugins/export/xls.tcl
mcset fr_fr Encoding: Codage:

### File: ../src/plugins/export/plain.tcl
mcset fr_fr {Export NULL values as:} {NULL Werte exportieren als:}

### File: ../src/plugins/export/plain.tcl
mcset fr_fr {Fixed column width:} {Fixed column width:}

### File: ../src/plugins/export/plain.tcl
mcset fr_fr {Database: %s (%s, %s)} {Database: %s (%s, %s)}

### File: ../src/plugins/export/plain.tcl
mcset fr_fr {Table: %s} {Table: %s}

### File: ../src/plugins/export/plain.tcl
mcset fr_fr {Index: %s} {Indexe: %s}

### File: ../src/plugins/export/plain.tcl
mcset fr_fr {Trigger: %s} {Déclencheur: %s}

### File: ../src/plugins/export/plain.tcl
mcset fr_fr {View: %s} {Vues: %s}

### File: ../src/plugins/export/csv.tcl
mcset fr_fr {If enabled, then first row of exported CSV will be a list of column names.} {Si activée, alors la première ligne de CSV exportée sera la liste des noms de colonnes.}

### File: ../src/plugins/export/csv.tcl
mcset fr_fr {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.} {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.}

### File: ../src/plugins/export/json.tcl
mcset fr_fr {Indented lines} {Indented lines}

### File: ../src/plugins/export/json.tcl
mcset fr_fr {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.} {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.}

### File: ../src/plugins/export/json.tcl
mcset fr_fr {Align lines} {Align lines}

### File: ../src/plugins/export/json.tcl
mcset fr_fr {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.} {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.}

### File: ../src/plugins/export/json.tcl
mcset fr_fr {Each row as object} {Each row as object}

### File: ../src/plugins/export/json.tcl
mcset fr_fr {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.} {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.}

### File: ../src/plugins/export/xml.tcl
mcset fr_fr {No extra white-spaces or new lines} {Pas d'espace vides ou de lignes supplémentaires}

### File: ../src/plugins/export/xml.tcl
mcset fr_fr {XML tags will be places char-by-char, without any extra white-spaces.} {XML Tags werden ohne extra Leerzeichen exportiert.}

### File: ../src/plugins/export/xml.tcl
mcset fr_fr {Format output to be human readable} {Lesbare, formatierte Ausgabe}

### File: ../src/plugins/export/xml.tcl
mcset fr_fr {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.} {Sera justifié pour être plus lisible dans l'éditeur de texte.}

### File: ../src/plugins/export/xml.tcl
mcset fr_fr {Generate XSD file} {XSD Datei erstellen}

### File: ../src/plugins/export/xml.tcl
mcset fr_fr {Generates XML Schema Definition file using
export file name and extension *.xsd.} {La génération XML de schema utilise un fichier
export nom and extension *.xsd.}

### File: ../src/plugins/export/xml.tcl
mcset fr_fr {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s} {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {First row of exported data will be header
with names of columns, just like in results grid.} {La première ligne de l'exportation de données aura comme en-tête
le nom des colonnes, comme le résultat de tableau.}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Row numbers as first column} {N° de ligne comme première colonne}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {First column of exported data
will contain row order number.} {First column of exported data
will contain row order number.}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Full column names} {Noms de colonne complet}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Column names in header will be prepended with "table_name." prefix.} {Column names in header will be prepended with "table_name." prefix.}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Show types} {Affichage des types}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Column headers will contain data types.} {L'en-tête de colonnes sera des types de données.}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {no type} {Aucun type}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {For table:} {Pour la table:}

### File: ../src/plugins/export/html.tcl
mcset fr_fr Unique: Unique:

### File: ../src/plugins/export/html.tcl
mcset fr_fr Yes { Oui}

### File: ../src/plugins/export/html.tcl
mcset fr_fr No Non

### File: ../src/plugins/export/html.tcl
mcset fr_fr Column Colonne

### File: ../src/plugins/export/html.tcl
mcset fr_fr Collating Comparaison

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Sort order} {Ordre de tri}

### File: ../src/plugins/export/html.tcl
mcset fr_fr Activated: Activer:

### File: ../src/plugins/export/html.tcl
mcset fr_fr Action: Action:

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Activate condition:} {Condition d'activation:}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Code executed:} {Code exécuté:}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Exported database: %s} {EXport base de données: %s}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Generated on %s with %s} {Généré de %s avec %s}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Exported table: %s} {Export de la table: %s}

### File: ../src/plugins/export/html.tcl
mcset fr_fr {Results of SQL query} {Résultats de query SQL}

### File: ../src/plugins/export/dbf.tcl
mcset fr_fr {Cannot overwrite file '%s'.} {Cannot overwrite file '%s'.}

### File: ../src/plugins/export/sql.tcl
mcset fr_fr {Name of table for exported data:} {Nom de la table pour export des données:}

### File: ../src/plugins/export/sql.tcl
mcset fr_fr {Include "CREATE TABLE" statement at the begining.} {Inclure le mot clé "CREATE TABLE" au début.}

### File: ../src/plugins/export/sql.tcl
mcset fr_fr {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.} {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.}

### File: ../src/plugins/export/sql.tcl
mcset fr_fr {Include table declaration} {Include table declaration}

### File: ../src/plugins/export/sql.tcl
mcset fr_fr {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.} {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.}

### File: ../src/plugins/export/sql.tcl
mcset fr_fr {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.} {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr Dimensions Dimensions

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Paper size:} {Paper size:}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Margin size:} {Margin size:}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Cell padding:} {Cell padding:}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Limit amount of data bytes in single cell to:} {Limit amount of data bytes in single cell to:}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Font size:} {Font size:}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Built-in font} {Built-in font}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr Font: Font:

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {TrueType font} {TrueType font}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Font file:} {Font file:}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Font encoding:} {Font encoding:}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Columns and rows} {Columns and rows}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Header background} {Header background}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Empty space} {Empty space}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Fill empty space in cells} {Fill empty space in cells}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.} {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Minimum height of empty space to fill:} {Minimum height of empty space to fill:}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.} {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Empty space background} {Empty space background}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {TTF Fonts} {TTF Fonts}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {All Files} {All Files}

### File: ../src/plugins/export/pdf.tcl
mcset fr_fr {Open TTF font} {Open TTF font}

### File: ../src/plugins/populating/random.tcl
mcset fr_fr {Include alpha characters} {Inclus caractères alpha}

### File: ../src/plugins/populating/random.tcl
mcset fr_fr {Include numeric characters} {Inclus caractères numériques}

### File: ../src/plugins/populating/random.tcl
mcset fr_fr {Include whitespace characters} {Inclus espace}

### File: ../src/plugins/populating/random.tcl
mcset fr_fr {Include binary characters} {Include caractères binaire}

### File: ../src/plugins/populating/random.tcl
mcset fr_fr {Minimum length:} {Longueur minimale:}

### File: ../src/plugins/populating/random.tcl
mcset fr_fr {Maximum length:} {Longueur maximale:}

### File: ../src/plugins/populating/random_number.tcl
mcset fr_fr {Minimum value:} {Valeur minimale:}

### File: ../src/plugins/populating/random_number.tcl
mcset fr_fr {Maximum value:} {Valeur maximale:}

### File: ../src/plugins/populating/random_number.tcl
mcset fr_fr {Constant prefix:} {Prefix constant:}

### File: ../src/plugins/populating/random_number.tcl
mcset fr_fr {Constant suffix:} {Suffix constant:}

### File: ../src/plugins/populating/sql.tcl
mcset fr_fr {Initialisation code} {Initialisation code}

### File: ../src/plugins/populating/sql.tcl
mcset fr_fr {Per iteration code} {Per iteration code}

### File: ../src/plugins/populating/sql.tcl
mcset fr_fr {Closing code} {Closing code}

### File: ../src/plugins/populating/constant.tcl
mcset fr_fr {Value to use:} {Valeur à utiliser:}

### File: ../src/plugins/populating/sequence.tcl
mcset fr_fr {Start from:} De:

### File: ../src/plugins/populating/dictionary.tcl
mcset fr_fr {Dictionary file:} {Fichier dictionnaire:}

### File: ../src/plugins/populating/dictionary.tcl
mcset fr_fr {Dictionary words separator:} {Dictionnaire des séparateurs:}

### File: ../src/plugins/populating/dictionary.tcl
mcset fr_fr Whitespace Espace

### File: ../src/plugins/populating/dictionary.tcl
mcset fr_fr {Line break} Rupture

### File: ../src/plugins/populating/dictionary.tcl
mcset fr_fr {Method of using words:} Wörterverwendungsmethode:

### File: ../src/plugins/populating/dictionary.tcl
mcset fr_fr Randomly Aléatoire

### File: ../src/plugins/populating/dictionary.tcl
mcset fr_fr Consecutively Consécutivement

### File: ../src/plugins/populating/dictionary.tcl
mcset fr_fr {Dictionary file doesn't exist, or unreadable.} {Dictionary file doesn't exist, or unreadable.}

### File: ../src/plugins/populating/dictionary.tcl
mcset fr_fr {Dictionary file is empty!} {Fichier dictionnaire vide!}

### File: ../src/plugins/populating/dictionary.tcl
mcset fr_fr {Dictionary file} {Fichier dictionnaire}

### File: ../src/taskbar.tcl
mcset fr_fr Database: {Base de données:}

### File: ../src/taskbar.tcl
mcset fr_fr Table: Table:

### File: ../src/taskbar.tcl
mcset fr_fr {Type new name for a window} {Saisir un nouveau nom pour la fenêtre}

### File: ../src/taskbar.tcl
mcset fr_fr {Window with given name already exists. Please type other name.} {Window with given name already exists. Please type other name.}

### File: ../src/taskbar.tcl
mcset fr_fr {Type new name for a task} {TSaisir un nouveau de tâche}

### File: ../src/taskbar.tcl
mcset fr_fr {Close selected window} {Fermer la fenêtre}

### File: ../src/taskbar.tcl
mcset fr_fr {Close other windows} {Fermer les autres fenêtres}

### File: ../src/taskbar.tcl
mcset fr_fr {Close all windows} {Fermer toutes les fenêtres}

### File: ../src/taskbar.tcl
mcset fr_fr {Restore last closed window} {Restore last closed window}

### File: ../src/taskbar.tcl
mcset fr_fr {Rename selected window} {Renommer la fenêtre}

### File: ../src/windows/table_win.tcl
mcset fr_fr Structure Structure

### File: ../src/windows/table_win.tcl
mcset fr_fr Data Données

### File: ../src/windows/table_win.tcl
mcset fr_fr Constraints Contraintes

### File: ../src/windows/table_win.tcl
mcset fr_fr Indexes Index

### File: ../src/windows/table_win.tcl
mcset fr_fr Triggers Déclencheurs

### File: ../src/windows/table_win.tcl
mcset fr_fr {Grid view} Tableau

### File: ../src/windows/table_win.tcl
mcset fr_fr {Form view} Formulaire

### File: ../src/windows/table_win.tcl
mcset fr_fr {Refresh table columns and DDL (%s)} {Actualisation table, colonnes ,DDL (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Edit table (%s)} {Mise à jour table (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Export table data (%s)} {Export données de la table (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Import data to table (%s)} {Import data to table (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Populate table (%s)} {Remplissage de la table (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Create similar table} {Création d'une table similaire}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Refresh table data (%s)} {Actualisation des données (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Add custom number of rows} {Add custom number of rows}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Add new row (%s)} {Ajout d'une nouvelle colonne (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Delete selected row (%s)} {Suppression de la colonne (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Commit changes (%s)} {Commit changes (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Rollback new row (%s)} {Annuler la nouvelle lugne (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {First %s rows} {Première ligne %s}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Previous %s rows} {Ligne précédente %s}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Next %s rows} {Ligne suivante %s}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Last %s rows} {Dernière ligne %s}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Export table data} {Export des données de la table}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Import data to table} {Import data to table}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Populate table} {Remplir la table}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Enter phrase you want to look for} {Saisir le texte que vius voulez rechercher}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Apply data filter} {Appliquer le filtre}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Clear data filter} {Enlever le filtre}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Total rows: %s} {Total lignes: %s}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Rollback changes (%s)} {Annulation desmodification (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {First row from data grid (%s)} {Première ligne  de (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Previous row from data grid (%s)} {Ligne suivante de (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Next row from data grid (%s)} {Ligne suivante de (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Last row from data grid (%s)} {Dernière ligne de (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Field switching mode.

Click it to make <Tab> key to insert tab characters.} {Mode basculé.

le cliquer pour faire <Tab>  pour insérer des tabulations.}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.} {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Refresh table indexes (%s)} {Indizes akzualisieren (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Create new index (%s)} {Créer nouvel indexe (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Edit index (%s)} {Modifier l'indexe (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Delete index (%s)} {Supprimer l'indexe (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Refresh table triggers (%s)} {Actualiser les déclencheurs de la table (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Create new trigger (%s)} {Créer nouveau déclencheur (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Edit trigger (%s)} {Modifier le déclencheur (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Delete trigger (%s)} {Supprimer le déclencheur (%s)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Constraint name} {Nom de contrainte}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Column name} {Nom de colonne}

### File: ../src/windows/table_win.tcl
mcset fr_fr Default Standard

### File: ../src/windows/table_win.tcl
mcset fr_fr {Not NULL} {Non NULL}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Primary key} {Clé primaire}

### File: ../src/windows/table_win.tcl
mcset fr_fr Unique Unique

### File: ../src/windows/table_win.tcl
mcset fr_fr Collate Comparaison

### File: ../src/windows/table_win.tcl
mcset fr_fr Check Contrôle

### File: ../src/windows/table_win.tcl
mcset fr_fr {Foreign key} {Clé primaire}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Index name} {Nom de l'index}

### File: ../src/windows/table_win.tcl
mcset fr_fr {On column} {Sur colonne}

### File: ../src/windows/table_win.tcl
mcset fr_fr {SQL code} {Code SQL}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Trigger name} {Nom du déclencheur}

### File: ../src/windows/table_win.tcl
mcset fr_fr {On table} {Sur table}

### File: ../src/windows/table_win.tcl
mcset fr_fr Name Nom

### File: ../src/windows/table_win.tcl
mcset fr_fr {Data type} {Type données}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Default value} {Valeur par défaut}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Refreshing dependencies} {Actualisation des dépendances}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Refreshing table columns...} {Actualisation table colonnes...}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Refreshing table data...} {Actualisaion table données...}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Refreshing table indexes...} {Actualisation table index...}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Refreshing table triggers...} {Actualisation table déclencheurs...}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.} {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Check condition} {Contrôle de condition}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Total rows: %s (filtered)} {Gesammte Zeilen: %s (gefiltert)}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Pending commits} {Pending commits}

### File: ../src/windows/table_win.tcl
mcset fr_fr {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?} {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Loading data...} {Daten laden...}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Loading table '%s'...} {Tabelle laden '%s'...}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.} {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.} {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Edit table} {Mise à jour table}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Enter number of rows to add:} {Enter number of rows to add:}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Add rows} {Add rows}

### File: ../src/windows/table_win.tcl
mcset fr_fr {New index} {Nouvel Index}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Index '%s' has no DDL. Probably it's system index and should not be edited.} {Index '%s' has no DDL. Probably it's system index and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Edit index} {Mise à jour Index}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Delete index} {Suppression index}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Are you sure you want to delete '%s' index?} {Voulez-vous supprimerl'index '%s' ?}

### File: ../src/windows/table_win.tcl
mcset fr_fr {New trigger} {Nouveau déclencheur}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.} {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Edit trigger} {Mise à jour déclencheur}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Delete trigger} {Suppression déclencheur}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Are you sure you want to delete '%s' trigger?} {Voulez-vous supprimer le déclancheur '%s'?}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Export table} {Export table}

### File: ../src/windows/table_win.tcl
mcset fr_fr {Import data} {Import data}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {SQL query} {Requête SQL}

### File: ../src/windows/editor_win.tcl
mcset fr_fr Results Résultats

### File: ../src/windows/editor_win.tcl
mcset fr_fr History Historique

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Execute query (%s)} {Exécution de la requête (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Execute query with plain string results} {Exéction de la requête avec les résultats en texte}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Explain query (%s)} {Analyser la requête (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Format SQL code (%s)} {Format du code SQL (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Refresh syntax highlighting (%s)} {Actualiser la syntaxe en surbrillance (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Clear history} {Effacer l'historique}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Export results} {Export des résultats}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Create view from query} {Création d'une vue d'une requête}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Execute SQL from file (%s)} {Exécution SQL d'un fichier(%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Load SQL from file (%s)} {Charger un SQL du fichier(%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Save SQL to file (%s)} {Enregistrer un SQL dans le fichier (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Default database for SQL executing
(%s/%s)} {Base de données par défaut pour l'exécution du SQL
(%s/%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr Database {Base de données}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Execution date} {Date d'exécution}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Execution time (s)} {Heure d'exécution (s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Rows affected} {Lignes affectées}

### File: ../src/windows/editor_win.tcl
mcset fr_fr SQL SQL

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Plain text view} {Vue texte tronqué}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Refresh results (%s)} {Actualisation des résultats (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Commit row (%s)} {Commit row (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Rollback row (%s)} {Rollback row (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Copy (%s)} {Copier (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Cut (%s)} {Couper (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Paste (%s)} {Coller (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Show line numbers} {Afficher les N° de ligne}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Delete selected history entry (%s)} {Delete selected history entry (%s)}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Choose the database first.} {Choisir la base de données en premier.}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Error while trying to collect completion list: %s} {Erreur pendant l'actualisation de la liste: %s}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Can't open %s file for reading.} {Impossible d'ouvrir le fichier en lecture.}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Can't open %s file for writting.} {Impossible d'ouvrir le fichier en écriture.}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {SQL code saved in %s.} {Code SQL enregistré sous %s.}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Are you sure you want to clear queries history?} {Voulez-vous effacer l'historique des requêtes?}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Delete the history entry} {Suppression de la ligne d'historique}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Are you sure you want to delete selected queries history entry?} {Voulez-vous supprimer les requêtes sélectionnées}

### File: ../src/windows/editor_win.tcl
mcset fr_fr Processing... {En cours...}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Processing query...} {Requête en-cours...}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {No results to export.} {Aucun résultat à exporter.}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.} {L'utilisation du LIEN pour l'éditeur SQL n'est pas alloué. Dans ce cas enregistrer la base que vous voulez lier dans SQLiteStudio et utiliser l'alias dans la liste visible de l'arbre des bases de données. Le lien sera automatique pour les requêtes.}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Query execution...} {Exécution de la requête...}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Executing SQL query...} {Requête SQL en cours...}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Error while executing query: %s} {Erreur pendant l'exécution de la requête: %s}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s} {Erreur inconnue pendant l'exécution. Merci de repporter le Code=%s. Le requête était: %s}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {%s row(s) read in %s second(s).} {%s row(s) read in %s second(s).}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {%s row(s) affected in %s second(s).} {%s ligne(s) affectées en %s seconde(s).}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {No SELECT statements found in editor or in selected part of SQL code.} {No SELECT statements found in editor or in selected part of SQL code.}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {More than one SELECT statements found. Please select the one you're interested in and then try again.} {More than one SELECT statements found. Please select the one you're interested in and then try again.}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {New view} {Nouvelle vue}

### File: ../src/windows/editor_win.tcl
mcset fr_fr {Fill query parameters} {Completer les paramètres de la requête}

### File: ../src/error.tcl
mcset fr_fr {Background error} {Erreur en arrière pla}

### File: ../src/error.tcl
mcset fr_fr Close Fermer

### File: ../src/error.tcl
mcset fr_fr {Report the bug} {Signaler une erreur}

### File: ../src/dialogs/about_dialog.tcl
mcset fr_fr About {A propos}

### File: ../src/dialogs/about_dialog.tcl
mcset fr_fr {Packages and plugins} {Paquets et  Extensions}

### File: ../src/dialogs/about_dialog.tcl
mcset fr_fr Licence License

### File: ../src/dialogs/about_dialog.tcl
mcset fr_fr {Installed plugins:} {Extensions installées:}

### File: ../src/dialogs/about_dialog.tcl
mcset fr_fr {Used Tcl packages:} {Paquets Tcl utilisés:}

### File: ../src/dialogs/about_dialog.tcl
mcset fr_fr {SQLite3 engine version: %s} {Version du moteur SQLite3: %s}

### File: ../src/dialogs/searchdialog.tcl
mcset fr_fr {Global expression understeands '*', '?' and \[chars].} {Expression globale valide '*', '?' et \[chars].}

### File: ../src/dialogs/searchdialog.tcl
mcset fr_fr Find Rechercher

### File: ../src/dialogs/searchdialog.tcl
mcset fr_fr Replace Remplacer

### File: ../src/dialogs/searchdialog.tcl
mcset fr_fr {Do you want to replace marked text?} {Voulez-vous remplacer le texte sélectionné?}

### File: ../src/dialogs/searchdialog.tcl
mcset fr_fr {Replace all} {Tout remplacer}

### File: ../src/dialogs/searchdialog.tcl
mcset fr_fr {Replacing finished.} {Remplacement terminé.}

### File: ../src/dialogs/searchdialog.tcl
mcset fr_fr {Cannot match the pattern!} {Texte non trouvé!}

### File: ../src/dialogs/bind_param.tcl
mcset fr_fr {Query number %s} {Requête N° %s}

### File: ../src/dialogs/bind_param.tcl
mcset fr_fr {Parameter number %s (named: %s):} {Paramétre N° %s (nommé: %s):}

### File: ../src/dialogs/bind_param.tcl
mcset fr_fr {NULL value} {NULL value}

### File: ../src/dialogs/bind_param.tcl
mcset fr_fr {You can use '%s' keyboard shortcut to switch NULL value.} {You can use '%s' keyboard shortcut to switch NULL value.}

### File: ../src/dialogs/bind_param.tcl
mcset fr_fr {Copy value to other '%s' parameters (%s)} {Copy value to other '%s' parameters (%s)}

### File: ../src/dialogs/bind_param.tcl
mcset fr_fr {By enabling this all parameters with same name
will also have same value as this one.} {By enabling this all parameters with same name
will also have same value as this one.}

### File: ../src/dialogs/bind_param.tcl
mcset fr_fr {Execute query} {Exécution de la requête}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset fr_fr Collation Comparaison

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset fr_fr Sort Tri

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset fr_fr {Named constraint:} {Nom de la contrainte:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset fr_fr {On conflict:} {Sur conflit:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset fr_fr {Constraint is marked as being named, but there's no name filled in.} {Constraint is marked as being named, but there's no name filled in.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset fr_fr {Collation for column '%s' is enabled, but there's no collation name filled in.} {La comparaison pour la colonne '%s' est activée mais il n'y a pas de valeur de comparaison de saisie.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset fr_fr {No columns are selected.} {Aucune colonne n'est sélectionnée.}

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr {Number of rows to insert:} {Nombre de lignes à insérer:}

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr {On a constraint violation:} {On a constraint violation:}

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr Mode Méthode

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr {Select table to display available columns} {Sélection de la table pour afficher les colonnes valides}

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr Populate Remplir

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr {Error occured while populating table:
%s} {Erreur pendant le remplissage de la table:
%s}

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr Configuration Configuration

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr {You have to type valid number of rows to insert.} {Vous devez saisir un nombre valide de lignes à insérer.}

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr {You have to select at least one column to populate.} {Vous devez sélectionner au moins une colonne.}

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr Populating... Remplissage...

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr {Populating table '%s'.} {Remplissage de la table '%s'.}

### File: ../src/dialogs/populate_table.tcl
mcset fr_fr Stop Stop

### File: ../src/dialogs/table_dialog_fk.tcl
mcset fr_fr {Foreign table:} {Table clé étrangére:}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset fr_fr {Local column} {Colonne locale}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset fr_fr {Foreign column} {Colonne étrangére}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset fr_fr Reactions Réactions

### File: ../src/dialogs/table_dialog_fk.tcl
mcset fr_fr {ON UPDATE} {SUR MàJ}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset fr_fr {ON DELETE} {SUR SUPPRESSION}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset fr_fr MATCH MATCH

### File: ../src/dialogs/table_dialog_fk.tcl
mcset fr_fr {Deferred foreign key} {Clé étrangére différée}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset fr_fr {No foreign table selected.} {Pas de table étrangére sélectionnée.}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset fr_fr {There's no foreign column assigned for local column '%s'.} {Il n'y a pas de colonne étrangére d'assignée pour une colonne locale '%s'.}

### File: ../src/dialogs/import_dialog.tcl
mcset fr_fr {Import from:} {Import from:}

### File: ../src/dialogs/import_dialog.tcl
mcset fr_fr {Import to:} {Import to:}

### File: ../src/dialogs/import_dialog.tcl
mcset fr_fr Table Table

### File: ../src/dialogs/import_dialog.tcl
mcset fr_fr Existing Existing

### File: ../src/dialogs/import_dialog.tcl
mcset fr_fr {Create new table} {Create new table}

### File: ../src/dialogs/import_dialog.tcl
mcset fr_fr Import Import

### File: ../src/dialogs/import_dialog.tcl
mcset fr_fr {Import method is not selected.} {Import method is not selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset fr_fr {You have to choose database.} {Vous devez choisir la base de données.}

### File: ../src/dialogs/import_dialog.tcl
mcset fr_fr {No existing table is selected.} {No existing table is selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset fr_fr {Table typed to create already exists. Please change table name.} {Table typed to create already exists. Please change table name.}

### File: ../src/dialogs/view_dialog.tcl
mcset fr_fr View Affichage

### File: ../src/dialogs/view_dialog.tcl
mcset fr_fr {View name:} {Nom de la vue:}

### File: ../src/dialogs/view_dialog.tcl
mcset fr_fr {Code executed to get view data:} {Code exécuté pour obtenir la vue:}

### File: ../src/dialogs/view_dialog.tcl
mcset fr_fr Create Créer

### File: ../src/dialogs/view_dialog.tcl
mcset fr_fr Change Modifier

### File: ../src/dialogs/view_dialog.tcl
mcset fr_fr {You have to specify database.} {Vous devez spécifier la base de données.}

### File: ../src/dialogs/view_dialog.tcl
mcset fr_fr {You have to specify view name.} {Vous devez spécifier le nom de la vue.}

### File: ../src/dialogs/view_dialog.tcl
mcset fr_fr {You havn't wrote a code for the view.} {Vous n'avez pas écris de code pour la vue.}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {Export data} {Exporter données}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {Only structure, without data} {Seulement la structure, aucune données}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {Table or view} {Table or view}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {Output file} {Fichier de sortie}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {Export format} {Exporter le format}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr Export Exporter

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {You have to choose file.} {Vous devez choisir un fichier.}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {Can't write to file: %s} {Enregistrement du fichier: %s impossible}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {You have to choose table.} {Vous devez choisir une table.}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {Exporting database '%s'.} {Export de la base de données '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {Exporting table '%s'.} {Export de la table '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {Exporting view '%s'.} {Exporting view '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {Exporting results.} {Export des résultats.}

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr Exporting... Export...

### File: ../src/dialogs/export_dialog.tcl
mcset fr_fr {Cannot write to file: %s
Please select other file.} {Impossible d'enregistrer le fichier: %s
SVP sélectionner un autre fichier.}

### File: ../src/dialogs/bug_report_login.tcl
mcset fr_fr {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.} {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.}

### File: ../src/dialogs/bug_report_login.tcl
mcset fr_fr Login: Login:

### File: ../src/dialogs/bug_report_login.tcl
mcset fr_fr Password: Password:

### File: ../src/dialogs/bug_report_login.tcl
mcset fr_fr Validate Validate

### File: ../src/dialogs/bug_report_login.tcl
mcset fr_fr {Validation result} {Validation result}

### File: ../src/dialogs/bug_report_login.tcl
mcset fr_fr {Not validated yet} {Not validated yet}

### File: ../src/dialogs/bug_report_login.tcl
mcset fr_fr Validating... Validating...

### File: ../src/dialogs/bug_report_login.tcl
mcset fr_fr {Validating login and password...} {Validating login and password...}

### File: ../src/dialogs/bug_report_login.tcl
mcset fr_fr {Invalid login or password.} {Invalid login or password.}

### File: ../src/dialogs/bug_report_login.tcl
mcset fr_fr {Login and password are correct.} {Login and password are correct.}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Your e-mail address or user (both optional)} {Your e-mail address or user (both optional)}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr or ou

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Log in} {Log in}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Logged in} {Logged in}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Log out} {Log out}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Brief description:} {Bréve description:}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {How to reproduce problem (if possible):} {Comment reproduire l'erreur (si possible):}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {What is the problem:} {Quel est le problème:}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Show more (optional)} {Show more (optional)}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Operating system:} {Système de plateforme (OS):}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Take screenshots of all SQLiteStudio windows and attach them} {Prend une impression d'écran de toutes les fenêtres SQLiteStudio.}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr Send Envoyé

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Describe your feature request:} {Décrivez les caractéristiques de votre demande :}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr Hide Hide

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Please fill 'Brief' field.} {SVP Saisir le champ 'Brève'.}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Please fill at least one of 'Description' or 'How to reproduce' fields.} {SVP saisir les champs 'Description' ou  'Comment reproduire'.}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {Please provide valid e-mail address or leave 'E-mail' empty.} {SVP saississez une adresse e_mail valide , ou laissez la zone vide.}

### File: ../src/dialogs/bug_report.tcl
mcset fr_fr {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.} {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Database to convert:} {Base de données à convertir:}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Converted database name:} {Nom de la base de données convertie:}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {File to use for converted database:} {Nom de la base de données à convertir:}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Choose new file for database} {Choisir un nouveau nom pour la base}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Database version:} {Version de la base:}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr Convert Convertir

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Convert database} {Convertir la base de données}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {You chave to choose database to convert.} {Vous devez choisir une base de données à convertir.}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Error resolving database with name %s!} {Erreur de résolution de base de données avec le nom %s!}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {You have to specify new database file.} {Vous devez spécifier un nouveau fichier de base de données.}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Cannot use existing file for converted database.} {Impossible d'utiliser le fichier pour convertir la base.}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Cannot use existing name for converted database.} {Impossible d'utiliser un nom existant pour convertir la base.}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Cannot find handler for database labeled with: %s} {Impossible de trouver de descripteur d'objet de la base de données nommée : %s}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Error while trying to create database: %s} {Erreur en essayant de créer la base de données: %s}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Database converting error} {Erreur de conversion de la base de données}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s} {Quelquess problèmes sont appurus à la conversion, Mais la conversion était avec omission d'objets avec problèmes. Details:
%s}

### File: ../src/dialogs/db_convert.tcl
mcset fr_fr {Choose file} {Choisir un fichier}

### File: ../src/dialogs/yesno.tcl
mcset fr_fr Question Question

### File: ../src/dialogs/yesno.tcl
mcset fr_fr Warning Attention

### File: ../src/dialogs/yesno.tcl
mcset fr_fr Error Erreur

### File: ../src/dialogs/yesno.tcl
mcset fr_fr Information Information

### File: ../src/dialogs/import_db.tcl
mcset fr_fr {Import from one of databases:} {Import de l'une des bases de données:}

### File: ../src/dialogs/import_db.tcl
mcset fr_fr {Choose database file to import:} {Choisir le fichier de base de données à importer:}

### File: ../src/dialogs/import_db.tcl
mcset fr_fr {No database chosen.} {Aucune base de données choisie.}

### File: ../src/dialogs/import_db.tcl
mcset fr_fr {Cannot open specified database.} {Impossible d'ouvrir la base de données spécifiée.}

### File: ../src/dialogs/import_db.tcl
mcset fr_fr {Error while importing database:
%s} {erreur lors de l'importation de la base de données:
%s}

### File: ../src/dialogs/import_db.tcl
mcset fr_fr {Select file} {Sélectionner un fichier}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr Column: Colonne:

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Column constraints:} {Contrainte colonne:}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr Add Ajout

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr Size Dimension

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Maximal length of value in column.} {Longueur maximale de la valeur de la colonne}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Primary key configuration} {Configuration de la clé primaire}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr Autoincrement Auto-increment

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Sort order:} {Ordre de tri:}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {No foreign column selected.} {Pas de colonne étranger de sélectionné.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Choose ON UPDATE action, or disable it.} {Choisir l'action ON UPDATE, ou la désativée.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Choose ON DELETE action, or disable it.} {Choisir l'action ON DELETE, ou la désativé.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Choose MATCH action, or disable it.} {Choisir l'action MATCH, ou la désativé.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Foreign key configuration} {Configuration clé étrangére}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Foreign column:} {Colonne clé étrangére:}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Unique configuration} {Configuration Unique}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Fill in the condition expression.} {Saisir l'expression conditionnelle.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Check condition configuration} {Configuration du contrôle de condition}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr Condition: Condition:

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Not null configuration} {Configuration non Null}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Fill in the collation name.} {Remplir le nom de fusion.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Collating configuration} {Configuration fusion}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Collation name:} {Nom de fusion}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Fill in the default value.} {Rempli avec la valeur par défaut.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Default value configuration} {Valeur par défaut de la configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Default value:} {Valeur par défaut:}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Use value as:} {Use value as:}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {A literal value} {A literal value}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {An expression} {An expression}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Column primary key is not configured correctly.} {La colonne de clé primaire n'est configurée correctement.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {AUTOINCREMENT is allowed only with INTEGER type of column.} {AUTOINCREMENT is allowed only with INTEGER type of column.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Column foreign key is not configured correctly.} {La colonne de clé étrangère n'est pas configurée correctement.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Column 'unique' constraint is not configured correctly.} {La colonne avec la contrainte 'unique' n'est configurée correctement.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Column 'check' constraint is not configured correctly.} {La colonne avec la contrainte  'check' n'est configurée correctement.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Column 'notnull' constraint is not configured correctly.} {La colonne avec la contrainten 'notnull' n'est configurée correctement.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Column 'default' constraint is not configured correctly.} {La contrainte 'par défaut' n'est configurée correctement.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Column 'collate' constraint is not configured correctly.} {La colonne avec la contrainte 'collate' n'est configurée correctement.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {No column name is specified.} {N° de colonne est spécifié.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Column with name '%s' already exists in the table.} {La colonne nommée '%s' existe déjà dan la table.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Data type bounds are given, but no data type name is specified.} {Des données de limites sont données, mais aucun type de données n'est spécifié.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Data type precision is given, but no data type size is specified.} {Des type données avec précision sont données, mais aucune longueur n'est spécifiée.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Data type size has invalid format. Only integer value is allowed.} {Longueur detype de donnée invalide. Uniquement une valeur INTEGER.}

### File: ../src/dialogs/column_dialog.tcl
mcset fr_fr {Data type precision has invalid format. Only integer value is allowed.} {Data type precision has invalid format. Only integer value is allowed.}

### File: ../src/dialogs/assoc_dialog.tcl
mcset fr_fr {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:} {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:}

### File: ../src/dialogs/assoc_dialog.tcl
mcset fr_fr {Current associations} {Current associations}

### File: ../src/dialogs/assoc_dialog.tcl
mcset fr_fr {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.} {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {Database file:} {Fichier de la base de données:}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {Database name:} {Nom de la base de données:}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {Generate automatically} {Génération automatique}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {Type name in field below:} {Alias de la base de données:}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {Remember it permanently} {Conserver la base }

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {If disabled, then the database will be registered only
for this single SQLiteStudio session.} {Si décoché, alors la base de données ne sera active
que pour cette session de SQLiteStudio.}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {Edit database} {Mise à jour de la base de données}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {Add database} {Ajout d'une base de données}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {File '%s' doesn't exist!} {File '%s' doesn't exist!}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {You have to specify database file.} {Vous devez spécifier un fichier de base de données.}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {Database named '%s' already exists on databases list. Please pick other name.} {Database named '%s' already exists on databases list. Please pick other name.}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.} {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.} {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {Type not existing file for new database} {Type  de fichier non exitant pour une nouvelle base de données}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {Select existing database file} {SSélectionner un fichier de base de données existant}

### File: ../src/dialogs/db_edit.tcl
mcset fr_fr {%s is not supported database!} {%s n'accepte pas de base de données!}

### File: ../src/dialogs/table_dialog_pk.tcl
mcset fr_fr {Using autoincrement with more than one column at once is forbidden.} {Using autoincrement with more than one column at once is forbidden.}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr Previous Précédent

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr Next Suivant

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {Do not show this dialog at startup} {Ne pas afficher ce dialogue au démarrage}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		} {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			You can configure all SQL editor syntax colors in settings.
		} {
			Vous pouvez configurer les couleur de syntaxe de tous les éditeurs SQL dans la configuration.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		} {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		} {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		} {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		} {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		} {
			Si vous fermez SQLITESTUDIO avec des fenêtres MDI ouvertes, elles seront rétablies (incluant le code de SQL saisi dans les éditeurs),
au prochain redémarrage de l'application, sauf si vous décochez "la reconstitution de session" dans la configuration.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		} {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		} {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		} {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		} {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		} {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		} {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		} {
			Vous pouvez mettre les résultats de la requête à la suite de la requête actuelle, à la place d'un autre onglet. Choisir la disposition des fenêtres dans la configuration Fenêtre.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		} {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		} {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		} {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		} {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset fr_fr {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		} {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		}

### File: ../src/dialogs/import_table.tcl
mcset fr_fr Separator: Trennzeichen:

### File: ../src/dialogs/import_table.tcl
mcset fr_fr {Common separator is \t (tab), but sometimes others can be met.} {Le séparateur commun est \t (tab), mais parfois d'autres sont utilisés.}

### File: ../src/dialogs/import_table.tcl
mcset fr_fr {Import data file for '%s' table:} {Importation du fichier de données pour la table '%s':}

### File: ../src/dialogs/import_table.tcl
mcset fr_fr {File '%s' isn't readable!} {Le fichier '%s' n'est pas lisible!}

### File: ../src/dialogs/import_table.tcl
mcset fr_fr {Error while trying to copy data:
%s} {Erreur en essayant de copier les données:
%s}

### File: ../src/dialogs/release_notes_dialog.tcl
mcset fr_fr {Don't show this dialog after update.} {Don't show this dialog after update.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr Trigger Déclencheur

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {On action:} {Sur Action:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {Trigger name:} {Nom déclencheur:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr When: Quand:

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {On table:} {Sur table:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {Execute code for:} {Exécution du code pour:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.} {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {Execute code only when:} {Exécution du code seulement quand:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {Code executed for above configuration:} {Code exécuté pour la configuration ci-dessus:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {You have to specify view.} {Vous devez spécifier une vue.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {You have to specify table.} {Vous devez spécifier une table.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {You have to specify trigger name.} {Vous devez spécifier un déclencheur.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {You have to specify 'action' condition.} {Vous devez spécifier la condition  'on action'.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {You havn't wrote a code for the trigger.} {Vous n'avez pas écrit de code pour le déclencheur.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset fr_fr {On view:} {Sur vue:}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr Columns: Colonne:

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Table constraints:} {Contraintes table:}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Table name:} {Nom de la table:}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Add column} {Ajout colonne}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Edit selected} {Mise à jour sélectionné}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Delete selected} {Suppression sélectionnée}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr Type Saisir

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr Details Details

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.} {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Edit column} {Mise à jour colonne}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Delete column} {Supprimer colonne}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Are you sure you want to delete column '%s'?} {Etes-vous sure de vouloir supprimer la colonne '%s'?}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Constraint change} {Constraint change}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Are you sure you want to change constraint type?
Current constraint configuration will be lost.} {Are you sure you want to change constraint type?
Current constraint configuration will be lost.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Table constraint number %s (%s) is not configured correctly.} {Table constraint number %s (%s) is not configured correctly.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {There's no column defined.} {Aucune colonne définie.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {There is already a table with name '%s'. Please change the name of this table.} {There is already a table with name '%s'. Please change the name of this table.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {There is already an index with name '%s'. Please change the name of this index.} {There is already an index with name '%s'. Please change the name of this index.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {There is already a trigger with name '%s'. Please change the name of this trigger.} {There is already a trigger with name '%s'. Please change the name of this trigger.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {There is already a view with name '%s'. Please change the name of this view.} {There is already a view with name '%s'. Please change the name of this view.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Trigger parsing problem} {Trigger parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Index parsing problem} {Problème de syntaxe de l'index}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {View parsing problem} {View parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.} {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {%s(%s) referencing %s(%s)} {%s(%s) referencing %s(%s)}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s} {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Do you want to continue anyway?} {Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?} {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Modifying table...} {Modification de la table...}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Modifying table '%s'.} {Modification de la table '%s'.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Could not recreate triggers for modified table.} {Impossible de recréer des déclencheurs pour la table modofiée.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Could not recreate indexes for modified table.} {Impossible de recréer des index pour la table modofié.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Could not recreate views for modified table.} {Could not recreate views for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?} {Impossible de recréer le déclencheur '%s' après la modification de la table.
Voulez-vous continuer?}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Trigger recreation problem} {Problème de recréation du déclencheur}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?} {Impossible de recréer l'index '%s' après la modification de la table.
Voulez-vous continuer?}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Index recreation problem} {Problème de recréation de l'index}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {Could not recreate foreign keys for tables referencing modified table.} {Could not recreate foreign keys for tables referencing modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {View recreation problem} {View recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset fr_fr {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).} {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).}

### File: ../src/dialogs/table_dialog_chk.tcl
mcset fr_fr {Condition expression cannot be empty.} {La condition ne peut être vide.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset fr_fr {What would you like to do?} {Was möchten Sie tun?}

### File: ../src/dialogs/new_version_dialog.tcl
mcset fr_fr {Install it automatically} {Installation automatique}

### File: ../src/dialogs/new_version_dialog.tcl
mcset fr_fr {Go to download page} {Allez en bas de page}

### File: ../src/dialogs/new_version_dialog.tcl
mcset fr_fr {Package download} {Télécharger le paquet}

### File: ../src/dialogs/new_version_dialog.tcl
mcset fr_fr {Insufficient privileges to perform automatic update.} {Insufficient privileges to perform automatic update.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset fr_fr {Check for updates at startup} {Contrôle d'une mise à jour au démarrage}

### File: ../src/dialogs/new_version_dialog.tcl
mcset fr_fr {New version of SQLiteStudio is available: %s} {Une nouvelle version SQLiteStutio est disponible: %s}

### File: ../src/dialogs/trigger_dialog_cols.tcl
mcset fr_fr {Trigger columns} {Trigger columns}

### File: ../src/dialogs/blob_edit.tcl
mcset fr_fr Commit Annuler

### File: ../src/dialogs/bug_history.tcl
mcset fr_fr Clear Effacer

### File: ../src/dialogs/bug_history.tcl
mcset fr_fr {Reported on} {Rapporter le}

### File: ../src/dialogs/bug_history.tcl
mcset fr_fr Brief Bréve

### File: ../src/dialogs/bug_history.tcl
mcset fr_fr URL URL

### File: ../src/dialogs/bug_history.tcl
mcset fr_fr Discussion Discussion

### File: ../src/dialogs/bug_history.tcl
mcset fr_fr {Clear reports} {Effacer les rapports}

### File: ../src/dialogs/bug_history.tcl
mcset fr_fr {Do you want to clear whole bug reports history?} {Voulez-vous supprimer l'historique des rapports d'erreur entièrement?}

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr Index Index

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr {Index name:} {Nom index:}

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr Available Available

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr Indexed Indexed

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr {Modifying index} {Modifying index}

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr {Modifying index '%s'} {Modifying index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr {Creating index} {Creating index}

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr {Creating index '%s'} {Creating index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?} {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?}

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr {Unique values} {Valeur unique}

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr {Same values for '%s'} {Même valeurs pour '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr {You have to select at least one column.} {Vous devez sélectionner au moins une colonne.}

### File: ../src/dialogs/index_dialog.tcl
mcset fr_fr {You have to specify index name.} {Vous devez spécifier le nom de l'index.}

### File: ../src/dialogs/functions_dialog.tcl
mcset fr_fr Implementation: Implémentation:

### File: ../src/dialogs/functions_dialog.tcl
mcset fr_fr Name: Nom:

### File: ../src/dialogs/functions_dialog.tcl
mcset fr_fr {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.} {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.}

### File: ../src/dialogs/functions_dialog.tcl
mcset fr_fr {Cannot use two functions with same name! Change name for '%s'.} {Impossible d'utiliser deux fonctions avec le même nom! Modifier le nom pour '%s'.}

### File: ../src/dialogs/functions_dialog.tcl
mcset fr_fr {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! } {Impossible d'utiser les nom 'tcl' ou 'sqlfile' comme nom de fonction, Ceux-ci sont réservés! }

### File: ../src/dialogs/functions_dialog.tcl
mcset fr_fr {Function '%s' is not implemented!} {Fonction '%s' n'est pas complétée!}

### File: ../src/dialogs/functions_dialog.tcl
mcset fr_fr {Delete function} {Supprimer la fonction}

### File: ../src/dialogs/functions_dialog.tcl
mcset fr_fr {Are you sure you want to delete function '%s'?} {Voulez-vous supprimer la fonction '%s'?}

### File: ../src/mainwindow.tcl
mcset fr_fr {Connect to selected database} {Connexion à la base de données}

### File: ../src/mainwindow.tcl
mcset fr_fr {Disconnect from selected database} {Déconnexion de la base de données}

### File: ../src/mainwindow.tcl
mcset fr_fr {Remove selected database from list} {Suppression de la liste de la base de données}

### File: ../src/mainwindow.tcl
mcset fr_fr {New table} {Nouvelle table}

### File: ../src/mainwindow.tcl
mcset fr_fr {Drop table} {Suppression de la table}

### File: ../src/mainwindow.tcl
mcset fr_fr {Drop index} {Suppression de l'index}

### File: ../src/mainwindow.tcl
mcset fr_fr {Drop trigger} {Suppression du déclencheur}

### File: ../src/mainwindow.tcl
mcset fr_fr {Edit view} {Mise à jour de la vue}

### File: ../src/mainwindow.tcl
mcset fr_fr {Drop view} {Suppression View}

### File: ../src/mainwindow.tcl
mcset fr_fr {Arrange cascade windows layout} {Organiser les fenêtres en cascade}

### File: ../src/mainwindow.tcl
mcset fr_fr {Arrange intelligent windows layout} {Organisation juxtaposées des fenêtres}

### File: ../src/mainwindow.tcl
mcset fr_fr {Refresh databases tree (%s)} {Actualisation de l'arbre des bases de données (%s)}

### File: ../src/mainwindow.tcl
mcset fr_fr {Open SQL query editor} {Ouvrir l'éditeur de requête SQL}

### File: ../src/mainwindow.tcl
mcset fr_fr {Settings (%s)} {Settings (%s)}

### File: ../src/mainwindow.tcl
mcset fr_fr {Open SQL functions editor} {Ouvrir l'éditeur de fonctions}

### File: ../src/mainwindow.tcl
mcset fr_fr {Clear objects filter} {Clear objects filter}

### File: ../src/mainwindow.tcl
mcset fr_fr {Enter object name you want to look for} {Enter object name you want to look for}

### File: ../src/mainwindow.tcl
mcset fr_fr Databases {Bases de données}

### File: ../src/mainwindow.tcl
mcset fr_fr Tools Outils

### File: ../src/mainwindow.tcl
mcset fr_fr Connect Connecter

### File: ../src/mainwindow.tcl
mcset fr_fr Disconnect Déconnecter

### File: ../src/mainwindow.tcl
mcset fr_fr {Remove from list} {Retirer de la liste}

### File: ../src/mainwindow.tcl
mcset fr_fr {View main toolbar} {Affichage barre d'outils base de données}

### File: ../src/mainwindow.tcl
mcset fr_fr {View structure toolbar} {Affichage barre d'outils de structure}

### File: ../src/mainwindow.tcl
mcset fr_fr {View windows toolbar} {Affichage barre d'outils de fenêtres}

### File: ../src/mainwindow.tcl
mcset fr_fr {View tools toolbar} {Affichage barre d'outils des outils}

### File: ../src/mainwindow.tcl
mcset fr_fr {View configuration toolbar} {Affichage barre d'outils de configuration}

### File: ../src/mainwindow.tcl
mcset fr_fr {Refresh databases tree} {Actualiser l'arbre des bases de données}

### File: ../src/mainwindow.tcl
mcset fr_fr {Custom SQL functions} {Personnalisation fonctions SQL}

### File: ../src/mainwindow.tcl
mcset fr_fr {Export database} {Export de la base de données}

### File: ../src/mainwindow.tcl
mcset fr_fr {Export table or view} {Export table or view}

### File: ../src/mainwindow.tcl
mcset fr_fr {Import data to a table} {Import data to a table}

### File: ../src/mainwindow.tcl
mcset fr_fr {SQLiteStudio home page} {Accueil SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset fr_fr {SQLiteStudio manual} {Manuel SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset fr_fr {SQLite documentation} {Documentation SQLite}

### File: ../src/mainwindow.tcl
mcset fr_fr {SQLiteStudio support forum} {Forum SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset fr_fr {Report a bug} {Signaler une erreur}

### File: ../src/mainwindow.tcl
mcset fr_fr {Send feature request} {Envoyer une demande de futur développement}

### File: ../src/mainwindow.tcl
mcset fr_fr {Show bug reports history} {Afficher les rapports d'erreur}

### File: ../src/mainwindow.tcl
mcset fr_fr {Show tips window} {Afficher la fenêtre des astuces}

### File: ../src/mainwindow.tcl
mcset fr_fr ChangeLog {Historique des modifications}

### File: ../src/mainwindow.tcl
mcset fr_fr Roadmap {Feuille de route}

### File: ../src/mainwindow.tcl
mcset fr_fr {Check for new version} {Vérification d'une nouvelle version}

### File: ../src/mainwindow.tcl
mcset fr_fr Donate Donation

### File: ../src/mainwindow.tcl
mcset fr_fr {Did you know that...} {Savez-vous ceci...}

### File: ../src/mainwindow.tcl
mcset fr_fr {Editor %s} {Editeur %s}

### File: ../src/mainwindow.tcl
mcset fr_fr Settings Configuration

### File: ../src/mainwindow.tcl
mcset fr_fr {SQLiteStudio roadmap} {Feuille de route de SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset fr_fr {Can't start web browser, because:
%s} {Ouverture impossible de l'exploreur WEB:
%s}

### File: ../src/mainwindow.tcl
mcset fr_fr {Can't start %s web browser, because:
%s} {Impossible d'ouvrir  %s explorateur, car:
%s}

### File: ../src/mainwindow.tcl
mcset fr_fr {About SQLiteStudio} {A propos SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset fr_fr {SQLiteStudio ChangeLog} {Modification de SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset fr_fr {There is no new version available.} {Aucune nouvelle version}

### File: ../src/mainwindow.tcl
mcset fr_fr {New version} {Nouvelle version}

### File: ../src/mainwindow.tcl
mcset fr_fr {Report bug} {Rapport d'erreurs}

### File: ../src/mainwindow.tcl
mcset fr_fr {Feature request} {Demandes futures}

### File: ../src/mainwindow.tcl
mcset fr_fr {Reports history} {Historique des rapports}

### File: ../src/mainwindow.tcl
mcset fr_fr {Reporting bug} {Rapport d'erreurs}

### File: ../src/mainwindow.tcl
mcset fr_fr {Reporting bug to SQLiteStudio bugs database...} {Rapport d'erreurs de la base SQLiteStudio...}

### File: ../src/mainwindow.tcl
mcset fr_fr {Problem occurred while reporting bug. You can ignore it and get back to your work.} {Problem occurred while reporting bug. You can ignore it and get back to your work.}

### File: ../src/mainwindow.tcl
mcset fr_fr Ignore Ignorer

### File: ../src/mainwindow.tcl
mcset fr_fr {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history} {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history}

### File: ../src/mainwindow.tcl
mcset fr_fr {A timeout occured while downloading new version. Try again, or download it manually.} {A timeout occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset fr_fr {An error occured while downloading new version. Try again, or download it manually.} {An error occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset fr_fr Downloading... Téléchargement...

### File: ../src/mainwindow.tcl
mcset fr_fr {Downloading SQLiteStudio v%s...} {Téléchargement de  SQLiteStudio v%s...}

### File: ../src/mainwindow.tcl
mcset fr_fr {Problem with saving new SQLiteStudio version to:
%s
Details:
%s} {Problem with saving new SQLiteStudio version to:
%s
Details:
%s}

### File: ../src/mainwindow.tcl
mcset fr_fr {Problem with getting new SQLiteStudio version
Details:
%s} {Problem with getting new SQLiteStudio version
Details:
%s}

### File: ../src/mainwindow.tcl
mcset fr_fr {This is unknown binary distribution. Cannot determinate binary file to download for update.} {This is unknown binary distribution. Cannot determinate binary file to download for update.}

### File: ../src/data_editor.tcl
mcset fr_fr {There are uncommited rows.
Are you sure you want to close '%s' window anywy?} {Il y a des lignes de non validées.
Voulez-vous fermer la fenêtre '%s'?}

### File: ../src/common/ddl_dialog.tcl
mcset fr_fr {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s} {Impossible de préparer le DDL. Le dialogue de configuration est incomplet.
Détail du problème:
%s}

### File: ../src/common/color_picker.tcl
mcset fr_fr {Choose color} {Choisir la couleur}

### File: ../src/common/shortcut_edit.tcl
mcset fr_fr {Forbidden shortcut key combination: %s} {Combinaison de touches pour le raccourci: %s}

### File: ../src/common/common.tcl
mcset fr_fr Copy Copier

### File: ../src/common/common.tcl
mcset fr_fr Cut Couper

### File: ../src/common/common.tcl
mcset fr_fr Paste Coller

### File: ../src/common/blob_edit_panel.tcl
mcset fr_fr {Text edit} Texte

### File: ../src/common/blob_edit_panel.tcl
mcset fr_fr {Hexadecimal edit} Hexadecimal

### File: ../src/common/common_sql.tcl
mcset fr_fr {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
} {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
}

### File: ../src/common/hex_editor.tcl
mcset fr_fr {Overwrite characters,
instead of inserting} {Overwrite characters,
instead of inserting}

### File: ../src/common/hex_editor.tcl
mcset fr_fr Processing En-cours

### File: ../src/common/hex_editor.tcl
mcset fr_fr {Processing data...} {Données en-cours...}

### File: ../src/sql_editor.tcl
mcset fr_fr {Replace dialog} Remplace

### File: ../src/sql_editor.tcl
mcset fr_fr {Search dialog} Rechercher

### File: ../src/trees/db_tree.tcl
mcset fr_fr Loading Charger

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Loading database list} {Chargement de la liste}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Given database file doesn't exist or is unreadable.} {Le nom de la base de données n'existe pas ou n'est pas lisible.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr Vacuum {Effacer les données}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Integrity check} {Contrôle d'intégrité}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Import schema from other database} {Import schéma d'une autre base de données}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Reset autoincrement for '%s'} {Reset autoincrement for '%s'}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Erase table data} {Erase table data}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Create foreign key} {Création d'une clé étrangère}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Show view data} {Montrer les données d'une vue}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Export view} {Export view}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Sort databases alphabetically} {Tri alpha des bases de données}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Given database is already on the list.} {La base de données est déjà dans la liste.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Given database name is already on the list.} {Le nom de la base attribué est déjà dans la liste.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr Tables Tables

### File: ../src/trees/db_tree.tcl
mcset fr_fr Views Vues

### File: ../src/trees/db_tree.tcl
mcset fr_fr {SQLite system table} {Table système SQLite}

### File: ../src/trees/db_tree.tcl
mcset fr_fr Columns Columns

### File: ../src/trees/db_tree.tcl
mcset fr_fr {SQLite system index} {Index système SQLite}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Remove database} {Supprimer la base de données}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Are you sure you want to remove '%s' database from the list?} {Voulez-vous supprimer la base de données '%s'?}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.} {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {'%s' is a virtual table, therefore cannot be browsed in table window.} {'%s' est une table virtuelle, l'affiche dans la fenêtre de table n'est possible.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Table '%s' has no DDL. Probably it's system table and should not be edited.} {Table '%s' has no DDL. Probably it's system table and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {'%s' is a virtual table, therefore cannot be edited in table dialog.} {'%s' est une table virtuelle, La modification dans la fenêtre de table n'est possible.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.} {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Integrity check (%s)} {Contrôle d'intégrité (%s)}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Are you sure you want to DROP '%s' table?} {Voulez-vous supprimer la table '%s' ?}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Dropping table} {Dropping table}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Dropping table '%s'} {Dropping table '%s'}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Dropping index} {Dropping index}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Dropping index '%s'} {Dropping index '%s'}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?} {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Fix trigger} {Fix trigger}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.} {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?} {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Fix view} {Fix view}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {View '%s' has no DDL. Probably it's system view and should not be edited.} {View '%s' has no DDL. Probably it's system view and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Delete view} {Supprimer la vue}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Are you sure you want to delete '%s' view?} {Voulez-vous supprimer la Vue '%s'?}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Erase data} {Erase data}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Are you sure you want to delete all data from table '%s'?} {Are you sure you want to delete all data from table '%s'?}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Deleting data} {Deleting data}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Deleting data from table '%s'} {Deleting data from table '%s'}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {'%s' view data} {'%s' Vue données}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Are you sure you want to make a vacuum?} {Voulez-vous effacer toutes les données?}

### File: ../src/trees/db_tree.tcl
mcset fr_fr Vacuuming Vacuuming

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Vacuuming '%s'} {Vacuuming '%s'}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {SQL files} {Fichiers SQL}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Select SQL file to be executed} {Sélection du fichier SQL pour exécution}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Error while executing SQL:
%s} {Error while executing SQL:
%s}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {SQL executed sucessfly.} {SQL exécuté avec succès.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Import database schema} {Import du schéma de la base de données}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Database: %s} {Database: %s}

### File: ../src/trees/db_tree.tcl
mcset fr_fr URI: URI:

### File: ../src/trees/db_tree.tcl
mcset fr_fr Version: Version:

### File: ../src/trees/db_tree.tcl
mcset fr_fr {File size:} {File size:}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Schema version:} {Schema version:}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Virtual table} {Virtual table}

### File: ../src/trees/db_tree.tcl
mcset fr_fr Indexes: Indexes:

### File: ../src/trees/db_tree.tcl
mcset fr_fr Triggers: Triggers:

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Column: %s} {Colonne: %s}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Not null} {Not null}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Indexed table:} {Indexed table:}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copy index '%s' for table '%s'} {Copy index '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Move index '%s' to table '%s'} {Move index '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copy trigger '%s' for table '%s'} {Copy trigger '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Move trigger '%s' to table '%s'} {Move trigger '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copy view '%s' for database '%s'} {Copy view '%s' for database '%s'}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Move view '%s' to database '%s'} {Move view '%s' to database '%s'}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {View '%s' has no DDL, therefore cannot be edited.} {View '%s' has no DDL, therefore cannot be edited.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copy view} {Copy view}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Move view} {Move view}

### File: ../src/trees/db_tree.tcl
mcset fr_fr Move Move

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copy index} {Copy index}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Move index} {Move index}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copy trigger} {Copy trigger}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Move trigger} {Move trigger}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copy table '%s' to database '%s' (include data, indexes and triggers)} {Copy table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copy table '%s' to database '%s' (include data)} {Copy table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copy table '%s' to database '%s' (include indexes and triggers)} {Copy table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copy table '%s' to database '%s' (skip data, indexes and triggers)} {Copy table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Move table '%s' to database '%s' (include data, indexes and triggers)} {Move table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Move table '%s' to database '%s' (include data)} {Move table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Move table '%s' to database '%s' (include indexes and triggers)} {Move table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Move table '%s' to database '%s' (skip data, indexes and triggers)} {Move table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copying table...} {Copying table...}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Copying table '%s' from '%s' to '%s'.} {Copying table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Moving table...} {Moving table...}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Moving table '%s' from '%s' to '%s'.} {Moving table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Could not create object in target database:
%s} {Could not create object in target database:
%s}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Could not copy data:
%s} {Could not copy data:
%s}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Could not copy table data from source database to target database. Details: %s} {Could not copy table data from source database to target database. Details: %s}

### File: ../src/trees/db_tree.tcl
mcset fr_fr {Could not delete object(s) from source database. Details: %s} {Could not delete object(s) from source database. Details: %s}

### File: ../src/grids/dbgrid.tcl
mcset fr_fr {Edit BLOB entry:} {Modifier valeur BLOB:}

### File: ../src/grids/dbgrid.tcl
mcset fr_fr {BLOB edit} {Mise à jour BLOB}

### File: ../src/grids/dbgrid.tcl
mcset fr_fr {Cannot commit. Details:
%s} {Cannot commit. Details:
%s}

### File: ../src/grids/grid.tcl
mcset fr_fr {You have to select a cell before paste any contents.} {Vous devez sélectionner une cellule avant de coller un contenu.}

### File: ../src/grids/grid.tcl
mcset fr_fr {Cut data} {Couper la donnée}

### File: ../src/grids/grid.tcl
mcset fr_fr {There are too many columns or rows to paste. Do you want to cut them and paste?} {Zu viele Felder oder Zeilen zum Einfügen. Wollen Sie diese ausschneiden und einfügen?}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Insert new row} {Insérer une nouvelle ligne}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Delete selected rows} {Suppression des lignes sélectionnées}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Edit cell value} {Mise à jour de la valeur de la cellule}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Edit cell value in BLOB editor} {Edit cell value in BLOB editor}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Duplicate row} {colonne dupliqué}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Set NULL value} {Mettre la valeur à NULL}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Generate SELECT from selected cells} {Generate SELECT from selected cells}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Commit selected cells} {Valider des données des cellules sélectionnées}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Rollback selected cells} {Retour aux données antérieures des cellules sélectionnées}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Select all} {Select all}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Show ordinals} {Afficher ordinal}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Show ROWIDs} {Affichage lignes ID}

### File: ../src/grids/data_grid.tcl
mcset fr_fr Type: Type:

### File: ../src/grids/data_grid.tcl
mcset fr_fr Constraints: Contraintes:

### File: ../src/grids/data_grid.tcl
mcset fr_fr {%s column has NOT NULL constraint. You have to fill value for it.} {Colonne %s a une contrainte NOT NULL. Vous devez saisir une valeur.}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Error while adding new row:
%s} {Erreur pendant l'ajout d'une nouvelle ligne:
%s}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Error while updating new row:
%s} {Erreur pendant la sauvegarde de la ligne:
%s}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Error while updating cell value:
%s

What would you like to do?} {Erreur lors de la mise à jour de la cellule:
%s

Que voulez-vous faire?}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Re-edit value} {Re-edition de valeur}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Return to value before edition} {Retour à la valeur d'avant}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Cannot delete row(s), because it violates constraint. Details:
%s} {Cannot delete row(s), because it violates constraint. Details:
%s}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {Error while deleting selected rows:
%s} {Erreur lors de la suppression des lignes sélectionnées:
%s}

### File: ../src/grids/data_grid.tcl
mcset fr_fr {SQL query generated at %s
using selected cells from window '%s'.} {SQL query generated at %s
using selected cells from window '%s'.}

### File: ../src/grids/result_grid.tcl
mcset fr_fr {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.} {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.}

### File: ../src/grids/result_grid.tcl
mcset fr_fr {Data type:} {Data type:}

### File: ../src/grids/result_grid.tcl
mcset fr_fr {No details are available on this cell.} {Aucun détail n'est valide sur cette cellule.}

### File: ../src/grids/result_grid.tcl
mcset fr_fr {Duplicated ROWID} {ROWID dupliqué}

### File: ../src/grids/result_grid.tcl
mcset fr_fr {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?} {Il y a plus d'une ligne avec l'ID=%s affecté par l'opération coller.
Dans ce cas des résultats imprévisible peuvent arriver, validez?}

### File: ../src/grids/result_grid.tcl
mcset fr_fr {Could not parse SQL while trying to generate requested query: %s} {Could not parse SQL while trying to generate requested query: %s}

### File: ../src/grids/result_grid.tcl
mcset fr_fr {Cannot use '%s' statement to generate requested query.} {Cannot use '%s' statement to generate requested query.}

### File: ../src/grids/result_grid.tcl
mcset fr_fr {Cannot determinate selected column with ID=%s.} {Cannot determinate selected column with ID=%s.}

### File: ../src/grids/result_grid.tcl
mcset fr_fr {Error occurred while trying to generate the query: %s} {Error occurred while trying to generate the query: %s}

### File: ../src/grids/result_grid.tcl
mcset fr_fr {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s} {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s}
