# SQLiteStudio 'it' localization file

# Unchanged translations

### File: ../src/win_assoc.tcl
mcset it {File associations} {File associations}

### File: ../src/win_assoc.tcl
mcset it {Following file extensions could not be associated to the current SQLiteStudio version:
%s} {Following file extensions could not be associated to the current SQLiteStudio version:
%s}

### File: ../src/win_assoc.tcl
mcset it {Click the link below to find out what is possible reason and solutions.} {Click the link below to find out what is possible reason and solutions.}

### File: ../src/cfg_win.tcl
mcset it Ok Ok

### File: ../src/cfg_win.tcl
mcset it Apply Applica

### File: ../src/cfg_win.tcl
mcset it Cancel Cancella

### File: ../src/cfg_win.tcl
mcset it Theme Tema

### File: ../src/cfg_win.tcl
mcset it {Select theme to use:} {Seleziona tema da usare:}

### File: ../src/cfg_win.tcl
mcset it {Theme version:} {Versione tema:}

### File: ../src/cfg_win.tcl
mcset it Shortcuts Scorciatoie

### File: ../src/cfg_win.tcl
mcset it {Global shortcuts} {Scorciatoie Globali}

### File: ../src/cfg_win.tcl
mcset it {Open SQL editor} {Apri editor SQL}

### File: ../src/cfg_win.tcl
mcset it {Opens SQL editor window.} {Apri la finestra dell'editor SQL.}

### File: ../src/cfg_win.tcl
mcset it {Close selected task} {Chiudi attività selezionata}

### File: ../src/cfg_win.tcl
mcset it {Closes active MDI window.} {Chiudi finestra MDI attiva.}

### File: ../src/cfg_win.tcl
mcset it {Restore last closed task} {Restore last closed task}

### File: ../src/cfg_win.tcl
mcset it {Restores last closed MDI window.} {Restores last closed MDI window.}

### File: ../src/cfg_win.tcl
mcset it {Open settings} {Apri settaggi}

### File: ../src/cfg_win.tcl
mcset it {Opens SQLiteStudio settings window.} {Apri le finestra dei settaggi di SQLiteStudio.}

### File: ../src/cfg_win.tcl
mcset it {Next task} {Attività successiva}

### File: ../src/cfg_win.tcl
mcset it {Switches task (window) to next, placed on the right from active task on taskbar.} {Vai all'attività successiva (finestra), posizionata sulla destra dell'attività selezionata sulla barra attività.}

### File: ../src/cfg_win.tcl
mcset it {Next task (alternative)} {Attività successiva (alternativa)}

### File: ../src/cfg_win.tcl
mcset it {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Vai all'attività (finestra) successiva, posizionata sulla destra nella barra delle attività.
Questa è una scorciatoia alternativa. Fa la stessa cosa di quella sopra.}

### File: ../src/cfg_win.tcl
mcset it {Previous task} {Attività precedente}

### File: ../src/cfg_win.tcl
mcset it {Switches task (window) to previous, placed on the left from active task on taskbar.} {Vai all'attività precedente (finestra), posizionata alla sinistra sulla barra attività.}

### File: ../src/cfg_win.tcl
mcset it {Previous task (alternative)} {Attività precedente (alternativa)}

### File: ../src/cfg_win.tcl
mcset it {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Vai all'attività (finestra) precedente, posizionata sulla sinsitra nella barra delle attività.
Questa è una scorciatoia alternativa. Fa la stessa cosa di quella sopra.}

### File: ../src/cfg_win.tcl
mcset it {Editor and table window shortcuts} {Scorciatoie finestra editor e tabella}

### File: ../src/cfg_win.tcl
mcset it {SQL editor completion} {Suggerimenti codice SQL}

### File: ../src/cfg_win.tcl
mcset it {Invokes SQL completion in editor window.} {Invoca suggeritore codice SQL nella finestra dell'editor.}

### File: ../src/cfg_win.tcl
mcset it {Execute SQL query} {Esegui query SQL}

### File: ../src/cfg_win.tcl
mcset it {Executes SQL query typed in editor.} {Esegui query SQL digitata nell'editor.}

### File: ../src/cfg_win.tcl
mcset it {Explain SQL query} {Spiega query SQL}

### File: ../src/cfg_win.tcl
mcset it {Calls EXPLAIN on SQL query typed in editor.} {Chiama EXPLAIN nella query SQLdigitata nell'editor.}

### File: ../src/cfg_win.tcl
mcset it {Format SQL code} {Formatta codice SQL}

### File: ../src/cfg_win.tcl
mcset it {Formats SQL code typed in editor.} {Formatta codice SQL digitato nell'editor.}

### File: ../src/cfg_win.tcl
mcset it {Load SQL from file} {Carica SQL da file}

### File: ../src/cfg_win.tcl
mcset it {Loads SQL from file to the editor.} {Carica SQL da file nell'editor.}

### File: ../src/cfg_win.tcl
mcset it {Save SQL to file} {Salva SQL su file}

### File: ../src/cfg_win.tcl
mcset it {Saves contents of the editor into a file.} {Salva contenuto dell'editor in un file.}

### File: ../src/cfg_win.tcl
mcset it {Execute SQL from file} {Esegui SQL da file}

### File: ../src/cfg_win.tcl
mcset it {Executes SQL directly from file, without loading it to the editor.} {Esegui SQL direttamente da file, senza caricarlo nell'editor.}

### File: ../src/cfg_win.tcl
mcset it {Next tab} {Scheda successiva}

### File: ../src/cfg_win.tcl
mcset it {Switches to next tab of editor window (result or history).} {Vai alla prossima scheda della finestra dell'editor(risultato o cronologia).}

### File: ../src/cfg_win.tcl
mcset it {Previous tab} {Scheda precedente}

### File: ../src/cfg_win.tcl
mcset it {Switches to previous tab of editor window (query or result).} {Vai alla scheda precedente della finestra dell'editor(query o risultato).}

### File: ../src/cfg_win.tcl
mcset it {Next subtab} {Sotto-Scheda successiva}

### File: ../src/cfg_win.tcl
mcset it {Switches to next subtab (form view in results tab).} {Vai alla prossima sotto-scheda(visualizzazione maschera nella tab risultato).}

### File: ../src/cfg_win.tcl
mcset it {Previous subtab} {Sotto-scheda precedente}

### File: ../src/cfg_win.tcl
mcset it {Switches to previous subtab (grid view in results tab).} {Vai alla sotto-scheda precedente (visualizzazione griglia nella tab risultato).}

### File: ../src/cfg_win.tcl
mcset it Refresh Aggiorna

### File: ../src/cfg_win.tcl
mcset it {Re-executes SQL query so results data is refreshed.} {Ri-esegui query SQL così i risultati saranno aggiornati.}

### File: ../src/cfg_win.tcl
mcset it {Delete selected row} {Cancella riga selezionata}

### File: ../src/cfg_win.tcl
mcset it {Deletes selected row.} {Cancella righe selezionate.}

### File: ../src/cfg_win.tcl
mcset it {Add new row} {Aggiungi nuova riga}

### File: ../src/cfg_win.tcl
mcset it {Adds new empty row without commiting it.} {Aggiungi una nuova riga vuota senza assegnarla.}

### File: ../src/cfg_win.tcl
mcset it {Erase cells data} {Erase cells data}

### File: ../src/cfg_win.tcl
mcset it {Erases data of selected cells.} {Erases data of selected cells.}

### File: ../src/cfg_win.tcl
mcset it {Next editor database in list} {Database editor successivo nella lista}

### File: ../src/cfg_win.tcl
mcset it {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)} {Vai al database successivo nell'editor dei contenuti
(E' è una lista a tendina in alto nella finestra dell'editor)}

### File: ../src/cfg_win.tcl
mcset it {Previous editor database in list} {Database editor precedente nella lista}

### File: ../src/cfg_win.tcl
mcset it {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)} {Vai al database precedente nell'editor dei contenuti
(E' è una lista a tendina in alto nella finestra dell'editor)}

### File: ../src/cfg_win.tcl
mcset it {Commit edition in Form View} {Assegnare l'edizione in visualizzazione maschera}

### File: ../src/cfg_win.tcl
mcset it {Commits edition in Form View of query results or table data preview.} {Assegna edizione in visualizzazione maschera dei risultati della query o dell'anteprima dei dati della tabella.}

### File: ../src/cfg_win.tcl
mcset it {Rollback edition in Form View} {Ripristina (rollback) edizione nel formulario della vista}

### File: ../src/cfg_win.tcl
mcset it {Rolls back edition in Form View of query results or table data preview.} {Ripristina (rollback) edizione in visualizzazione maschera dei risultati della query o dell'anteprima dei dati della tabella.}

### File: ../src/cfg_win.tcl
mcset it {Jump to first row in Form View} {Vai alla prima riga in visualizzazione maschera}

### File: ../src/cfg_win.tcl
mcset it {Jumps to first row of query results grid
or table data preview grid in Form View.} {Vai alla prima riga della griglia dei risultati della query
o dell'anteprima dei dati della tabella in visualizzazione maschera.}

### File: ../src/cfg_win.tcl
mcset it {Go to previous row in Form View} {Vai alla riga precedente in visualizzazione maschera}

### File: ../src/cfg_win.tcl
mcset it {Goes to previous row of query results grid
or table data preview grid row in Form View.} {Vai alla riga precedente della griglia dei risultati della query
o dell'anteprima dei dati della tabella in visualizzazione maschera.}

### File: ../src/cfg_win.tcl
mcset it {Go to next row in Form View} {Vai alla riga successiva in visualizzazione maschera}

### File: ../src/cfg_win.tcl
mcset it {Goes to next row of query results grid
or table data preview grid row in Form View.} {Vai alla riga successiva della griglia dei risultati della query
o dell'anteprima dei dati della tabella in visualizzazione maschera.}

### File: ../src/cfg_win.tcl
mcset it {Jump to last row in Form View} {Vai all'ultima riga in visualizzazione maschera}

### File: ../src/cfg_win.tcl
mcset it {Jumps to last row of query results grid
or table data preview grid in Form View.} {Vai all'ultima riga della griglia dei risultati della query
o dell'anteprima dei dati della tabella in visualizzazione maschera.}

### File: ../src/cfg_win.tcl
mcset it {Switch NULL value in form edit field} {Switch NULL value in form edit field}

### File: ../src/cfg_win.tcl
mcset it {Sets or unsets NULL value in currently selected
column in form view data edit mode.} {Sets or unsets NULL value in currently selected
column in form view data edit mode.}

### File: ../src/cfg_win.tcl
mcset it Plugins Plugins

### File: ../src/cfg_win.tcl
mcset it {SQL formatter plugins} {Plugin per formattare codice SQL}

### File: ../src/cfg_win.tcl
mcset it {Use following SQL formatter plugin:} {Usa il seguente plug-in per formattare SQL:}

### File: ../src/cfg_win.tcl
mcset it {Configure formatter plugin} {Configura il plug-in per formattare}

### File: ../src/cfg_win.tcl
mcset it Configure Configura

### File: ../src/cfg_win.tcl
mcset it {Populating plugins} {Popolamento plugins}

### File: ../src/cfg_win.tcl
mcset it {Default table populating plugin:} {Plug-in predefinito per la popolazione della tabella:}

### File: ../src/cfg_win.tcl
mcset it Miscellaneous Varie

### File: ../src/cfg_win.tcl
mcset it {Restore session after next start} {Ripristina sessione dopo il prossimo avvio}

### File: ../src/cfg_win.tcl
mcset it {All windows and their contents (such as SQL code)
will be restored while next application startup.} {Tutte le finestre e i loro contenuti (come il codice SQL)
saranno ripristinati al prossimo riavvio.}

### File: ../src/cfg_win.tcl
mcset it {Show line numbers in SQL editor} {Mostra numero di riga nell'editor SQL}

### File: ../src/cfg_win.tcl
mcset it {All SQL editor windows will contain line numbers on the left side of window.} {Tutte le finestre dell'editor SQL conterranno il numero di riga sul lato sinistro della finestra.}

### File: ../src/cfg_win.tcl
mcset it {Underline syntax errors in SQL editor} {Sottolinea gli errori di sintassi nell'editor SQL}

### File: ../src/cfg_win.tcl
mcset it {Makes errors to be marked with underline.
You can also define foreground and background color for errors.} {Rendi gli errori riconoscibili sottolineandoli.
Puoi inoltre definire anche il colore del carattere e dello sfondo per gli errori.}

### File: ../src/cfg_win.tcl
mcset it {Show SQLite system tables and indexes in databases tree} {Mostra le tabelle di sistema e gli indici SQLite nell'albero dei database}

### File: ../src/cfg_win.tcl
mcset it {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.} {Se abilitato le tabelle SQLite di sistema ('sqlite_*')
e gli indici ('(*autoindex*)') verranno mostraati nell'albero dei database.}

### File: ../src/cfg_win.tcl
mcset it {Open items with single mouse click in databases tree} {Apri oggetti con un click nell'albero dei database.}

### File: ../src/cfg_win.tcl
mcset it {Items in database tree are open by double click by default.
This option switches it to single click.} {Gli oggetti nell'albero dei database si aprono con doppio click di default.
Questa opzione imposta il click singolo.}

### File: ../src/cfg_win.tcl
mcset it {Show ROWID as default instead of row order number in table data view} {Show ROWID as default instead of row order number in table data view}

### File: ../src/cfg_win.tcl
mcset it {This option affects first column from the left on the data tab of the table window.} {This option affects first column from the left on the data tab of the table window.}

### File: ../src/cfg_win.tcl
mcset it {Do not show 'did you know that...' dialog at startup.} {Non mostrare la finestra di dialogo 'Lo sapevi che...' all'avvio.}

### File: ../src/cfg_win.tcl
mcset it {Uncheck this option to show the dialog.} {Deseleziona questa opzione per mostrare la finestra di dialogo.}

### File: ../src/cfg_win.tcl
mcset it {Check for updates at startup.} {Verifica aggiornamenti all'avvio.}

### File: ../src/cfg_win.tcl
mcset it {If enabled, application will will check
for new version available at startup.} {Se abilitata, l'applicazione verificherà
all'avvio se è disponibile una nuova versione.}

### File: ../src/cfg_win.tcl
mcset it {Sort custom SQL functions list by name} {Ordina lista funzioni SQL personalizzate per nome}

### File: ../src/cfg_win.tcl
mcset it {This list is placed in Custom SQL funcions dialog.} {Questa lista è nella finestra delle funzioni SQL personalizzate.}

### File: ../src/cfg_win.tcl
mcset it {Select all contents when editing the table cell} {Select all contents when editing the table cell}

### File: ../src/cfg_win.tcl
mcset it {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.} {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.}

### File: ../src/cfg_win.tcl
mcset it {Ask if clipboard contents should be cut} {Chiedi se il contenuto degli appunti dovrebbe essere tagliato.}

### File: ../src/cfg_win.tcl
mcset it {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.} {Se selezionato l'applicazione chiederà all'utente se vuole
ridurre il contenuto degli appunti quando verranno incollati,
nel caso i dati non vengano contenuti per intero nella cella della griglia.
Altrimenti, il contenuto verrà ridotto alla dimensione corretta
senza alcune richiesta.}

### File: ../src/cfg_win.tcl
mcset it {Rows per page in Table Window and Editor Results:} {Rows per page in Table Window and Editor Results:}

### File: ../src/cfg_win.tcl
mcset it {More results per page causes slower loading of single data page. Value 1000 should be right.} {Più risultati per pagina può causare un caricamento più lento della singola pagina di dati. Valore di 1000 dovrebbe essere sufficiente.}

### File: ../src/cfg_win.tcl
mcset it {History entries limit:} {Limite elementi cronologia:}

### File: ../src/cfg_win.tcl
mcset it {Number of rows to remember in SQL editor history.} {Numero di righe nella cronologia dell'editor SQL da ricordare.}

### File: ../src/cfg_win.tcl
mcset it {Insertion cursor blinking period (milliseconds):} {Insertion cursor blinking period (milliseconds):}

### File: ../src/cfg_win.tcl
mcset it {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.} {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.}

### File: ../src/cfg_win.tcl
mcset it {Web browser:} Browser:

### File: ../src/cfg_win.tcl
mcset it {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.} {Puoi digirare comandi personalizzati per il tuo browser qui. Deve essere nel percorso della variabile.
Indirizzo da aprire verrà semplicemente passato come argomento a questo comando.}

### File: ../src/cfg_win.tcl
mcset it Language: Lingua:

### File: ../src/cfg_win.tcl
mcset it {Tab in table window on open:} {All'apertura scheda nella finestra della tabella:}

### File: ../src/cfg_win.tcl
mcset it {Table structure} {Struttura tabella}

### File: ../src/cfg_win.tcl
mcset it {Table data} {Dati tabella}

### File: ../src/cfg_win.tcl
mcset it {Select which tab should be opened for start in table window,
when you just opened that window.} {Selezionare quale scheda debba essere aperta per aprire la finestra della tabella,
quando viene aperta la finestra.}

### File: ../src/cfg_win.tcl
mcset it {View default display mode:} {View default display mode:}

### File: ../src/cfg_win.tcl
mcset it {Edition dialog} {Edition dialog}

### File: ../src/cfg_win.tcl
mcset it {Data view} {Data view}

### File: ../src/cfg_win.tcl
mcset it {Defines what is displayed by default when user opens a view.} {Defines what is displayed by default when user opens a view.}

### File: ../src/cfg_win.tcl
mcset it {Editor window results layout} {Impostazioni finestra dell'editor}

### File: ../src/cfg_win.tcl
mcset it {Show results in separated tab} {Mostra risultati in una scheda a parte}

### File: ../src/cfg_win.tcl
mcset it {Show results in frame below query} {Mostra i risultati in una cornice sotto la query}

### File: ../src/cfg_win.tcl
mcset it {Database tree display mode} {Database tree display mode}

### File: ../src/cfg_win.tcl
mcset it {Show indexes and triggers linked under referenced table.} {Show indexes and triggers linked under referenced table.}

### File: ../src/cfg_win.tcl
mcset it {Show indexes and triggers in their own groups.} {Show indexes and triggers in their own groups.}

### File: ../src/cfg_win.tcl
mcset it {Show column names linked under the table.} {Show column names linked under the table.}

### File: ../src/cfg_win.tcl
mcset it {Plain text results} {Risultati in forma testo}

### File: ../src/cfg_win.tcl
mcset it {Display NULL values as:} {Visualli valori NULL come:}

### File: ../src/cfg_win.tcl
mcset it {Maximum column width:} {Larghezza massima colonna:}

### File: ../src/cfg_win.tcl
mcset it {Values longer than specified here will be cut in plain text results.} {Valori più lunghi di quanto specificato qui verranno tagliati in visualizzazione testo piano.}

### File: ../src/cfg_win.tcl
mcset it Colors Colori

### File: ../src/cfg_win.tcl
mcset it {Global colors} {Colori globali}

### File: ../src/cfg_win.tcl
mcset it {MDI windows title bar background color} {Colore della barra del titolo della finestra MDI in secondo piano}

### File: ../src/cfg_win.tcl
mcset it {MDI windows title bar foreground color} {Colore della barra del titolo della finestra MDI in primo piano}

### File: ../src/cfg_win.tcl
mcset it {MDI windows title bar button background color} {Colore del bottone della barra del titolo della finestra MDI in secondo piano}

### File: ../src/cfg_win.tcl
mcset it {MDI windows title bar active button background color} {Colore del bottone attivo della barra del titolo della finestra MDI in secondo piano}

### File: ../src/cfg_win.tcl
mcset it {SQL Editor} {Editor SQL}

### File: ../src/cfg_win.tcl
mcset it {Editor standard font color} {Colore base dei caratteri dell'editor}

### File: ../src/cfg_win.tcl
mcset it {Editor background} {Sfondo editor}

### File: ../src/cfg_win.tcl
mcset it {Selected foreground color} {Colore selezionato in primo piano}

### File: ../src/cfg_win.tcl
mcset it {Selected background color} {Colore selezionato in secondo piano}

### File: ../src/cfg_win.tcl
mcset it {Disabled background color} {Colore disabilitato in secondo piano}

### File: ../src/cfg_win.tcl
mcset it {Tables color} {Colore tabelle}

### File: ../src/cfg_win.tcl
mcset it {Brackets color} {Colore parentesi}

### File: ../src/cfg_win.tcl
mcset it {Square brackets color} {Colore parentesi quadre}

### File: ../src/cfg_win.tcl
mcset it {Keywords color} {Colore parole chiave}

### File: ../src/cfg_win.tcl
mcset it {Variables color} {Colore variabili}

### File: ../src/cfg_win.tcl
mcset it {Strings color} {Colore stringhe}

### File: ../src/cfg_win.tcl
mcset it {Comments color} {Colore commenti}

### File: ../src/cfg_win.tcl
mcset it {Matched brackets foreground color} {Colore in primo piano in corrispondenza delle parentesi}

### File: ../src/cfg_win.tcl
mcset it {Matched brackets background color} {Colore di sfondo in corrispondenza delle parentesi}

### File: ../src/cfg_win.tcl
mcset it {Syntax error color} {Syntax error color}

### File: ../src/cfg_win.tcl
mcset it {Tcl editor} {Editor Tcl}

### File: ../src/cfg_win.tcl
mcset it {Options color} {Colore opzioni}

### File: ../src/cfg_win.tcl
mcset it {Quoted character color} {Quoted character color}

### File: ../src/cfg_win.tcl
mcset it {Trees colors} {Colori alberi}

### File: ../src/cfg_win.tcl
mcset it {Tree background} {Sfondo albero}

### File: ../src/cfg_win.tcl
mcset it {Tree standard font color} {Colore carattere base dell'albero}

### File: ../src/cfg_win.tcl
mcset it {Tree selected background color} {Colore carattere dell'albero selezionato in secondo piano}

### File: ../src/cfg_win.tcl
mcset it {Tree selected foreground color} {Colore carattere dell'albero selezionato in primo piano}

### File: ../src/cfg_win.tcl
mcset it {Color for number of objects in tree branch} {Colore del carattere dei numeri nel ramo dell'albero}

### File: ../src/cfg_win.tcl
mcset it {Grids colors} {Colori Griglia}

### File: ../src/cfg_win.tcl
mcset it {Grid background} {Sfondo griglia}

### File: ../src/cfg_win.tcl
mcset it {Grid standard font color} {Colore carattere base della griglia}

### File: ../src/cfg_win.tcl
mcset it {Grid selected background color} {Sfondo della cella della griglia selezionata}

### File: ../src/cfg_win.tcl
mcset it {Grid selected foreground color} {Colore carattere della cella selezionata}

### File: ../src/cfg_win.tcl
mcset it {Grid base column background color} {Colore dello sfondo della colonna del numero di riga della griglia}

### File: ../src/cfg_win.tcl
mcset it {Foreground color for cells with NULL value} {Colore carattere per le celle contenenti valore NULL}

### File: ../src/cfg_win.tcl
mcset it {Status fields colors} {Colori campi di stato}

### File: ../src/cfg_win.tcl
mcset it {Background color} {Colore di sfondo}

### File: ../src/cfg_win.tcl
mcset it {Foreground color} {Colore carattere}

### File: ../src/cfg_win.tcl
mcset it {Error foreground color} {Colore carattere d'errore}

### File: ../src/cfg_win.tcl
mcset it {Information foreground color} {Colore carattere d'informazione}

### File: ../src/cfg_win.tcl
mcset it {Information (second kind) foreground color} {Colore carattere d'informazione (secondo tipo)}

### File: ../src/cfg_win.tcl
mcset it {Miscellaneous colors} {Colori Vari}

### File: ../src/cfg_win.tcl
mcset it {Context hints background color} {Colore di sfondo dei suggerimenti}

### File: ../src/cfg_win.tcl
mcset it {Context hints foreground color} {Colore carattere dei suggerimenti}

### File: ../src/cfg_win.tcl
mcset it Fonts Caratteri

### File: ../src/cfg_win.tcl
mcset it {SQL editor font} {Carattere editor SQL}

### File: ../src/cfg_win.tcl
mcset it {Status fields font} {Carattere campi di stato}

### File: ../src/cfg_win.tcl
mcset it {Grid font} {Carattere griglia}

### File: ../src/cfg_win.tcl
mcset it {Tree font} {Carattere albero}

### File: ../src/cfg_win.tcl
mcset it {Tree additional labels font} {Carattere etichette aggiuntive dell'albero}

### File: ../src/cfg_win.tcl
mcset it {Context hints font} {Carattere dei suggerimenti}

### File: ../src/cfg_win.tcl
mcset it {Changed language needs application to be restarted.} {Il cambio lingua necessita il riavvio dell'applicazione.}

### File: ../src/cfg_win.tcl
mcset it {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.} {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.}

### File: ../src/cfg_win.tcl
mcset it {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.} {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.}

### File: ../src/cfg_win.tcl
mcset it {SQL formatter options} {Opzioni formattatore SQL}

### File: ../src/db/db_file_types.tcl
mcset it {All SQLite Databases} {Tutti i database SQLite}

### File: ../src/db/db_file_types.tcl
mcset it {SQLite 3 Databases} {Databases SQLite 3}

### File: ../src/db/db_file_types.tcl
mcset it {SQLite 2 Databases} {Databases SQLite 2}

### File: ../src/db/db_file_types.tcl
mcset it {All files} {Tutti i files}

### File: ../src/db/query_executor.tcl
mcset it {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.} {Query non possono essere eseguita correttamente dal parser interno di SQLiteStudio, quindi è stata passata direttamente a SQLite, senza alcuna sostituzione o la modifica.}

### File: ../src/db/query_executor.tcl
mcset it {Invalid database name: %s} {Nome database non valido: %s}

### File: ../src/db/query_executor.tcl
mcset it {Imbalanced 'BEGIN' ocurrence in query.} {Imbalanced 'BEGIN' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset it {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.} {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset it {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.} {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset it {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.} {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset it {Cannot use more than one 'BEGIN'.} {Cannot use more than one 'BEGIN'.}

### File: ../src/db/query_executor.tcl
mcset it {Imbalanced 'COMMIT' ocurrence in query.} {Imbalanced 'COMMIT' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset it {Imbalanced 'ROLLBACK' ocurrence in query.} {Imbalanced 'ROLLBACK' ocurrence in query.}

### File: ../src/db/sqlite2.tcl
mcset it {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)} {E' avvenuto un errore durante l'ottimizzazione VACUUM sul database:
%s
(Questo messaggio viene direttamente da SQLite2)}

### File: ../src/db/db.tcl
mcset it {An internal logic error in SQLite} {Errore logico interno a SQLite}

### File: ../src/db/db.tcl
mcset it {Access permission denied} {Permessi di accesso negati}

### File: ../src/db/db.tcl
mcset it {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.} {Impossibile procedere con l'operazione perchè il database è occupato.
Forse qualche altra applicazione lo sta usando.}

### File: ../src/db/db.tcl
mcset it {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.} {Impossibile procedere con l'operazione perchè il database è bloccato.
Forse qualche altra applicazione lo sta usando.}

### File: ../src/db/db.tcl
mcset it {A malloc() failed} {Fallimento malloc()}

### File: ../src/db/db.tcl
mcset it {Attempt to write a readonly database} {Tentivo di scrivere un database in sola-lettura}

### File: ../src/db/db.tcl
mcset it {Disk I/O error occurred} {Occorso errore I/O disco}

### File: ../src/db/db.tcl
mcset it {The database disk image is malformed} {L'immagine del database è rovinata.}

### File: ../src/db/db.tcl
mcset it {Database is full} {Database pieno}

### File: ../src/db/db.tcl
mcset it {Unable to open the database file} {Unable to open the database file}

### File: ../src/db/db.tcl
mcset it {Database lock protocol error} {Database blocca il protocollo errori}

### File: ../src/db/db.tcl
mcset it {Database is empty} {Database vuoto}

### File: ../src/db/db.tcl
mcset it {The database schema changed} {Schema database cambiato}

### File: ../src/db/db.tcl
mcset it {String or BLOB exceeds size limit} {Stringa o BLOB superano la dimensione limite}

### File: ../src/db/db.tcl
mcset it {Library used incorrectly} {Libreria usata non correttamente}

### File: ../src/db/db.tcl
mcset it {Uses OS features not supported on host} {L'uso di funzioni OS non supportate dal host}

### File: ../src/db/db.tcl
mcset it {Authorization denied} {Autorizzazione negata}

### File: ../src/db/db.tcl
mcset it {Auxiliary database format error} {Errore formato database ausiliario}

### File: ../src/db/db.tcl
mcset it {2nd parameter to sqlite3_bind out of range} {Secondo paramento di sqlite3_bind scorretto}

### File: ../src/db/db.tcl
mcset it {File opened that is not a database file} {Il file aperto non è un database}

### File: ../src/db/db.tcl
mcset it {Error while opening %s database:
%s} {Errore durante l'apertura del database %s:
%s}

### File: ../src/db/db.tcl
mcset it {Not enough parameters passed to function '%s'.} {Parametri passati alla funzione '%s' insufficienti.}

### File: ../src/db/db.tcl
mcset it {Cannot read file: %s} {Impossibile leggere il file: %s}

### File: ../src/db/db.tcl
mcset it {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.} {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.}

### File: ../src/db/db.tcl
mcset it {Could not attach database %s. Error message from SQLite:
%s} {Could not attach database %s. Error message from SQLite:
%s}

### File: ../src/db/db.tcl
mcset it {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.} {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.}

### File: ../src/db/sqlite3.tcl
mcset it {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)} {E' avvenuto un errore durante l'ottimizzazione VACUUM sul database:
%s
(Questo messaggio viene direttamente da SQLite3)}

### File: ../src/completion_routines.tcl
mcset it {Problem with attaching database:
%s} {Problem with attaching database:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset it {Error from importing plugin:
%s} {Error from importing plugin:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset it {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset it {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset it {Error creating table '%s':
%s

Importing aborted.} {Error creating table '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset it {Error trying to import data to '%s':
%s

Importing aborted.} {Error trying to import data to '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset it Importing... Importing...

### File: ../src/plugins/import_plugin.tcl
mcset it {Importing to table '%s'.} {Importing to table '%s'.}

### File: ../src/plugins/import_plugin.tcl
mcset it {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?} {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset it {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?} {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset it {Problem occured while importing row number %s:
%s

What would you like to do?} {Problem occured while importing row number %s:
%s

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset it {Importing finished.} {Importing finished.}

### File: ../src/plugins/import_plugin.tcl
mcset it {Import problem} {Import problem}

### File: ../src/plugins/import_plugin.tcl
mcset it {Skip this data row} {Skip this data row}

### File: ../src/plugins/import_plugin.tcl
mcset it {Keep data rows imported so far (%s) and abort} {Keep data rows imported so far (%s) and abort}

### File: ../src/plugins/import_plugin.tcl
mcset it {Rollback data rows imported so far and abort} {Rollback data rows imported so far and abort}

### File: ../src/plugins/import_plugin.tcl
mcset it {Ignore it and proceed} {Ignore it and proceed}

### File: ../src/plugins/import_plugin.tcl
mcset it Abort Annulla

### File: ../src/plugins/sql_formatting/enterprise/format_s.tcl
mcset it name nome

### File: ../src/plugins/sql_formatting/basic.tcl
mcset it {Reduce group of whitespaces into one whitespace.} {Riduci gruppo di spazi bianchi in un unico spazio bianco.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset it {Uppercase keywords.} {Parole chiave maiuscole.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset it {Separate ")" and after contents with single whitespace.} {Separare ")" dopo il contenuto con un singolo spazio bianco.}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {SQLite3 only} {Solo SQLite3}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it Indentation Indentazione

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {New lines} {Nuove linee}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {White spaces} {Spazi bianchi}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it Names Nomi

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it Comments Commenti

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Tab size:} {Dimensione scheda:}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Line up keywords in multi-line queries} {Allinea le parole chiave delle query su più linee}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Ident contents of parenthesis block} {Indenta il contenuto delle parentesi}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Ident parenthesis block in new line} {Indente i le parentesi in una nuova linea}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Before opening parenthesis in column definitions} {Prima di aprire le parentesi nella definizione della colonna}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After opening parenthesis in column definitions} {Dopo aver aperto le parentesi nella definizione della colonna}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Before closinging parenthesis in column definitions} {Prima di chiudere le parentesi nella definizione della colonna}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After closinging parenthesis in column definitions} {Dopo aver chiuso le parentesi nella definizione della colonna}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Before opening parenthesis in expressions} {Prima di aprire le parentesi nell\'espressione}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After opening parenthesis in expressions} {Dopo aver aperto le parentesi nell\'espressione}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Before closinging parenthesis in expressions} {Prima di chiudere le parentesi nell\'espressione}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After closinging parenthesis in expressions} {Dopo aver chiuso le parentesi nell\'espressione}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After comma} {Dopo la virgola}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After comma in function arguments list} {Dopo la virgola nella lista degli argomenti della funzione}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After logical block of query} {Dopo il blocco logico di query}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After semicolon} {Dopo il punto e , (virgola)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Never before semicolon} {Mai prima del ; (punto e virgola)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Before comma in lists} {Prima della , (virgola) nella lista}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After comma in lists} {Dopo la , (virgola) nella lista}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Before opening parenthesis} {Prima di aprire le parentesi}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After opening parenthesis} {Dopo aver aperto le parentesi}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Before closing parenthesis} {Prima di chiudere le parentesi}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After closing parenthesis} {Dopo aver chiuso le parentesi}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Before dot operator (in path to database object)} {Prima dell\'operatore . (punto) (nel percorso al database)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After dot operator (in path to database object)} {Dopo dell\'operatore . (punto) (nel percorso al database}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Before mathematical operator} {Prima dell\'operatore matematico}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {After mathematical operator} {Dopo l\'operatore matematico}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Uppercase keywords} {Parole chiave maiuscole}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Uppercase datatype names} {Nomi tipo di dati in maiuscolo}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Always use name wrapping} {Usa sempre il wrap per i nomi}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Preferred name wrapper} {Nome wrapper preferito}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Expand one line comments (/* ... */) to multiline} {Espandi i commenti su singola linea (/* ... */) su più linee}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Indent multi line comments} {Indenta i commenti multi linea}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset it {Use "*" character for each line} {Usa "*" per ogni linea}

### File: ../src/plugins/import/csv.tcl
mcset it {, (comma)} {, (virgola)}

### File: ../src/plugins/import/csv.tcl
mcset it {; (semicolon)} {; (punto e virgola)}

### File: ../src/plugins/import/csv.tcl
mcset it {\t (tab)} {\t (tab)}

### File: ../src/plugins/import/csv.tcl
mcset it {  (white-space)} {  (Spazio bianco)}

### File: ../src/plugins/import/csv.tcl
mcset it Custom Personalizzato

### File: ../src/plugins/import/csv.tcl
mcset it {Input file} {Input file}

### File: ../src/plugins/import/csv.tcl
mcset it Browse Sfoglia

### File: ../src/plugins/import/csv.tcl
mcset it {Show options} {Show options}

### File: ../src/plugins/import/csv.tcl
mcset it {Column names} {Column names}

### File: ../src/plugins/import/csv.tcl
mcset it {Treat first row as column names} {Treat first row as column names}

### File: ../src/plugins/import/csv.tcl
mcset it {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.} {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.}

### File: ../src/plugins/import/csv.tcl
mcset it {Columns separator:} {Separatore colonne:}

### File: ../src/plugins/import/csv.tcl
mcset it {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.} {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.}

### File: ../src/plugins/import/csv.tcl
mcset it {NULL handling} {NULL handling}

### File: ../src/plugins/import/csv.tcl
mcset it {Treat following values as NULL:} {Treat following values as NULL:}

### File: ../src/plugins/import/csv.tcl
mcset it Workarounds Workarounds

### File: ../src/plugins/import/csv.tcl
mcset it {Expect Microsoft format of CSV} {Expect Microsoft format of CSV}

### File: ../src/plugins/import/csv.tcl
mcset it {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.} {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.}

### File: ../src/plugins/import/csv.tcl
mcset it Encoding Encoding

### File: ../src/plugins/import/csv.tcl
mcset it {Convert from encoding:} {Convert from encoding:}

### File: ../src/plugins/import/csv.tcl
mcset it {Input file cannot be empty.} {Input file cannot be empty.}

### File: ../src/plugins/import/csv.tcl
mcset it {Input file is not readable.} {Input file is not readable.}

### File: ../src/plugins/import/csv.tcl
mcset it {CSV separator cannot be empty.} {Il separatore CSV non può essere vuoto.}

### File: ../src/plugins/import/csv.tcl
mcset it {CSV files} {CSV files}

### File: ../src/plugins/import/csv.tcl
mcset it {Text files} {Text files}

### File: ../src/plugins/import/csv.tcl
mcset it {File to import from} {File to import from}

### File: ../src/plugins/import/dbf.tcl
mcset it Auto-detect Auto-detect

### File: ../src/plugins/import/dbf.tcl
mcset it {dBase files} {dBase files}

### File: ../src/plugins/import/regexp.tcl
mcset it {Regular expression} {Regular expression}

### File: ../src/plugins/import/regexp.tcl
mcset it {Visual editor} {Visual editor}

### File: ../src/plugins/import/regexp.tcl
mcset it {Use Regular Expression Groups to identify columns.} {Use Regular Expression Groups to identify columns.}

### File: ../src/plugins/import/regexp.tcl
mcset it {Case insensitive} {Case insensitive}

### File: ../src/plugins/import/regexp.tcl
mcset it Help Aiuto

### File: ../src/plugins/import/regexp.tcl
mcset it {RegExp error:
%s} {RegExp error:
%s}

### File: ../src/plugins/export/xls.tcl
mcset it {Column names as first row} {Nome colonna come prima riga}

### File: ../src/plugins/export/xls.tcl
mcset it {If enabled, then first row of exported document will be a list of column names.} {If enabled, then first row of exported document will be a list of column names.}

### File: ../src/plugins/export/xls.tcl
mcset it Encoding: Codifica:

### File: ../src/plugins/export/plain.tcl
mcset it {Export NULL values as:} {Esporta valori NULL come:}

### File: ../src/plugins/export/plain.tcl
mcset it {Fixed column width:} {Fixed column width:}

### File: ../src/plugins/export/plain.tcl
mcset it {Database: %s (%s, %s)} {Database: %s (%s, %s)}

### File: ../src/plugins/export/plain.tcl
mcset it {Table: %s} {Tabella: %s}

### File: ../src/plugins/export/plain.tcl
mcset it {Index: %s} {Indice: %s}

### File: ../src/plugins/export/plain.tcl
mcset it {Trigger: %s} {Trigger: %s}

### File: ../src/plugins/export/plain.tcl
mcset it {View: %s} {Vista: %s}

### File: ../src/plugins/export/csv.tcl
mcset it {If enabled, then first row of exported CSV will be a list of column names.} {If enabled, then first row of exported CSV will be a list of column names.}

### File: ../src/plugins/export/csv.tcl
mcset it {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.} {Carattere usato per separare la colonna dei dati
dalle altre. Se il carattere separatore dovesse apparire in qualsiasi colonna dati,
verrà rinchiusa tra apici.
Ogni apice nei valori sarà sostituito dalle virgoletta.}

### File: ../src/plugins/export/json.tcl
mcset it {Indented lines} {Indented lines}

### File: ../src/plugins/export/json.tcl
mcset it {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.} {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.}

### File: ../src/plugins/export/json.tcl
mcset it {Align lines} {Align lines}

### File: ../src/plugins/export/json.tcl
mcset it {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.} {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.}

### File: ../src/plugins/export/json.tcl
mcset it {Each row as object} {Each row as object}

### File: ../src/plugins/export/json.tcl
mcset it {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.} {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.}

### File: ../src/plugins/export/xml.tcl
mcset it {No extra white-spaces or new lines} {Nessuno spazio bianco extra o nuove linee}

### File: ../src/plugins/export/xml.tcl
mcset it {XML tags will be places char-by-char, without any extra white-spaces.} {I tag XML saranno inseriti carattere per carattere, senza alcuno spazio bianco aggiuntivo.}

### File: ../src/plugins/export/xml.tcl
mcset it {Format output to be human readable} {Formattare per renderlo leggibile}

### File: ../src/plugins/export/xml.tcl
mcset it {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.} {Ogni tag sarà posizione in una nuova linea e tutto il documento
verrà giustificato per essere più leggibile con un editor di testo.}

### File: ../src/plugins/export/xml.tcl
mcset it {Generate XSD file} {Genera file XSD}

### File: ../src/plugins/export/xml.tcl
mcset it {Generates XML Schema Definition file using
export file name and extension *.xsd.} {Genera schema di definizione XML usando
nome del file ed estensione *.xsd.}

### File: ../src/plugins/export/xml.tcl
mcset it {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s} {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s}

### File: ../src/plugins/export/html.tcl
mcset it {First row of exported data will be header
with names of columns, just like in results grid.} {La prima riga dei dati esportati sarà l'intestazione
coi nomi delle colonne, come in una griglia dei risultati.}

### File: ../src/plugins/export/html.tcl
mcset it {Row numbers as first column} {Numeri di riga come prima colonna}

### File: ../src/plugins/export/html.tcl
mcset it {First column of exported data
will contain row order number.} {First column of exported data
will contain row order number.}

### File: ../src/plugins/export/html.tcl
mcset it {Full column names} {Nomi colonne}

### File: ../src/plugins/export/html.tcl
mcset it {Column names in header will be prepended with "table_name." prefix.} {Column names in header will be prepended with "table_name." prefix.}

### File: ../src/plugins/export/html.tcl
mcset it {Show types} {Mostra tipi}

### File: ../src/plugins/export/html.tcl
mcset it {Column headers will contain data types.} {L'intestazione della colonna conterrà il tipo di dati.}

### File: ../src/plugins/export/html.tcl
mcset it {no type} {Nessun tipo}

### File: ../src/plugins/export/html.tcl
mcset it {For table:} {Per tabella:}

### File: ../src/plugins/export/html.tcl
mcset it Unique: Unico:

### File: ../src/plugins/export/html.tcl
mcset it Yes Si

### File: ../src/plugins/export/html.tcl
mcset it No No

### File: ../src/plugins/export/html.tcl
mcset it Column Colonna

### File: ../src/plugins/export/html.tcl
mcset it Collating Collezione

### File: ../src/plugins/export/html.tcl
mcset it {Sort order} Ordina

### File: ../src/plugins/export/html.tcl
mcset it Activated: Attivato:

### File: ../src/plugins/export/html.tcl
mcset it Action: Azione:

### File: ../src/plugins/export/html.tcl
mcset it {Activate condition:} {Attiva condizione:}

### File: ../src/plugins/export/html.tcl
mcset it {Code executed:} {Codice eseguito:}

### File: ../src/plugins/export/html.tcl
mcset it {Exported database: %s} {Database esportato: %s}

### File: ../src/plugins/export/html.tcl
mcset it {Generated on %s with %s} {Generato su %s con %s}

### File: ../src/plugins/export/html.tcl
mcset it {Exported table: %s} {Tabella esportata: %s}

### File: ../src/plugins/export/html.tcl
mcset it {Results of SQL query} {Risultati della query SQL}

### File: ../src/plugins/export/dbf.tcl
mcset it {Cannot overwrite file '%s'.} {Cannot overwrite file '%s'.}

### File: ../src/plugins/export/sql.tcl
mcset it {Name of table for exported data:} {Nome della tabella per l\'esportazione dei dati:}

### File: ../src/plugins/export/sql.tcl
mcset it {Include "CREATE TABLE" statement at the begining.} {Inserisci \"CREATE TABLE\" all\'inizio.}

### File: ../src/plugins/export/sql.tcl
mcset it {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.} {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.}

### File: ../src/plugins/export/sql.tcl
mcset it {Include table declaration} {Includi dichiarazione tabella}

### File: ../src/plugins/export/sql.tcl
mcset it {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.} {Se abilitato, il DDL (CREATE TABLE)
sarà incluso nel sql esportato.}

### File: ../src/plugins/export/sql.tcl
mcset it {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.} {Devi configurare il nome della tabella per esportare i risultati della query SQL.
L\'INSERT SQL richiede il nome della tabella nella sua sintassi.}

### File: ../src/plugins/export/pdf.tcl
mcset it Dimensions Dimensions

### File: ../src/plugins/export/pdf.tcl
mcset it {Paper size:} {Paper size:}

### File: ../src/plugins/export/pdf.tcl
mcset it {Margin size:} {Margin size:}

### File: ../src/plugins/export/pdf.tcl
mcset it {Cell padding:} {Cell padding:}

### File: ../src/plugins/export/pdf.tcl
mcset it {Limit amount of data bytes in single cell to:} {Limit amount of data bytes in single cell to:}

### File: ../src/plugins/export/pdf.tcl
mcset it {Font size:} {Font size:}

### File: ../src/plugins/export/pdf.tcl
mcset it {Built-in font} {Built-in font}

### File: ../src/plugins/export/pdf.tcl
mcset it Font: Font:

### File: ../src/plugins/export/pdf.tcl
mcset it {TrueType font} {TrueType font}

### File: ../src/plugins/export/pdf.tcl
mcset it {Font file:} {Font file:}

### File: ../src/plugins/export/pdf.tcl
mcset it {Font encoding:} {Font encoding:}

### File: ../src/plugins/export/pdf.tcl
mcset it {Columns and rows} {Columns and rows}

### File: ../src/plugins/export/pdf.tcl
mcset it {Header background} {Header background}

### File: ../src/plugins/export/pdf.tcl
mcset it {Empty space} {Empty space}

### File: ../src/plugins/export/pdf.tcl
mcset it {Fill empty space in cells} {Fill empty space in cells}

### File: ../src/plugins/export/pdf.tcl
mcset it {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.} {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.}

### File: ../src/plugins/export/pdf.tcl
mcset it {Minimum height of empty space to fill:} {Minimum height of empty space to fill:}

### File: ../src/plugins/export/pdf.tcl
mcset it {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.} {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.}

### File: ../src/plugins/export/pdf.tcl
mcset it {Empty space background} {Empty space background}

### File: ../src/plugins/export/pdf.tcl
mcset it {TTF Fonts} {TTF Fonts}

### File: ../src/plugins/export/pdf.tcl
mcset it {All Files} {All Files}

### File: ../src/plugins/export/pdf.tcl
mcset it {Open TTF font} {Open TTF font}

### File: ../src/plugins/populating/random.tcl
mcset it {Include alpha characters} {Includi caratteri alfabetici}

### File: ../src/plugins/populating/random.tcl
mcset it {Include numeric characters} {Includi caratteri numerici}

### File: ../src/plugins/populating/random.tcl
mcset it {Include whitespace characters} {Includi spazio bianco}

### File: ../src/plugins/populating/random.tcl
mcset it {Include binary characters} {Includi caratteri binari}

### File: ../src/plugins/populating/random.tcl
mcset it {Minimum length:} {Lunghezza minima:}

### File: ../src/plugins/populating/random.tcl
mcset it {Maximum length:} {Lunghezza massima:}

### File: ../src/plugins/populating/random_number.tcl
mcset it {Minimum value:} {Valore minimo:}

### File: ../src/plugins/populating/random_number.tcl
mcset it {Maximum value:} {Valore massimo:}

### File: ../src/plugins/populating/random_number.tcl
mcset it {Constant prefix:} {Prefisso costante:}

### File: ../src/plugins/populating/random_number.tcl
mcset it {Constant suffix:} {Suffisso costante:}

### File: ../src/plugins/populating/sql.tcl
mcset it {Initialisation code} {Initialisation code}

### File: ../src/plugins/populating/sql.tcl
mcset it {Per iteration code} {Per iteration code}

### File: ../src/plugins/populating/sql.tcl
mcset it {Closing code} {Closing code}

### File: ../src/plugins/populating/constant.tcl
mcset it {Value to use:} {Valore da usare:}

### File: ../src/plugins/populating/sequence.tcl
mcset it {Start from:} {Inizia da:}

### File: ../src/plugins/populating/dictionary.tcl
mcset it {Dictionary file:} Dizionario:

### File: ../src/plugins/populating/dictionary.tcl
mcset it {Dictionary words separator:} {Dizionario dei separatori di parole:}

### File: ../src/plugins/populating/dictionary.tcl
mcset it Whitespace {Spazio bianco}

### File: ../src/plugins/populating/dictionary.tcl
mcset it {Line break} {Interruzione linea}

### File: ../src/plugins/populating/dictionary.tcl
mcset it {Method of using words:} {Metodo d'uso delle parole:}

### File: ../src/plugins/populating/dictionary.tcl
mcset it Randomly Casuale

### File: ../src/plugins/populating/dictionary.tcl
mcset it Consecutively Consecutivamente

### File: ../src/plugins/populating/dictionary.tcl
mcset it {Dictionary file doesn't exist, or unreadable.} {Il dizionario non esiste, o non è leggibile.}

### File: ../src/plugins/populating/dictionary.tcl
mcset it {Dictionary file is empty!} {Il dizionario è vuoto!}

### File: ../src/plugins/populating/dictionary.tcl
mcset it {Dictionary file} Dizionario

### File: ../src/taskbar.tcl
mcset it Database: Database:

### File: ../src/taskbar.tcl
mcset it Table: Tabella:

### File: ../src/taskbar.tcl
mcset it {Type new name for a window} {Digita il nuovo nome della finestra}

### File: ../src/taskbar.tcl
mcset it {Window with given name already exists. Please type other name.} {Window with given name already exists. Please type other name.}

### File: ../src/taskbar.tcl
mcset it {Type new name for a task} {Digita nuovo nome per un compito}

### File: ../src/taskbar.tcl
mcset it {Close selected window} {Chiudi finestra selezionata}

### File: ../src/taskbar.tcl
mcset it {Close other windows} {Chiudi altre finestre}

### File: ../src/taskbar.tcl
mcset it {Close all windows} {Chiudi tutte le finestre}

### File: ../src/taskbar.tcl
mcset it {Restore last closed window} {Restore last closed window}

### File: ../src/taskbar.tcl
mcset it {Rename selected window} {Rinomina finestra selezionata}

### File: ../src/windows/table_win.tcl
mcset it Structure Struttura

### File: ../src/windows/table_win.tcl
mcset it Data Dati

### File: ../src/windows/table_win.tcl
mcset it Constraints Restrizioni

### File: ../src/windows/table_win.tcl
mcset it Indexes Indici

### File: ../src/windows/table_win.tcl
mcset it Triggers Triggers

### File: ../src/windows/table_win.tcl
mcset it {Grid view} {Vedi griglia}

### File: ../src/windows/table_win.tcl
mcset it {Form view} {Visualizzazione maschera}

### File: ../src/windows/table_win.tcl
mcset it {Refresh table columns and DDL (%s)} {Aggiorna le colonne della tabella e il DDL (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Edit table (%s)} {Modifica tabella (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Export table data (%s)} {Esporta tabella dati (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Import data to table (%s)} {Import data to table (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Populate table (%s)} {Popola tabella (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Create similar table} {Crea tabella simile}

### File: ../src/windows/table_win.tcl
mcset it {Refresh table data (%s)} {Aggiorna dati tabella (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Add custom number of rows} {Add custom number of rows}

### File: ../src/windows/table_win.tcl
mcset it {Add new row (%s)} {Aggiungi nuova riga (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Delete selected row (%s)} {Cancella riga selezionata (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Commit changes (%s)} {Commit changes (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Rollback new row (%s)} {Rollback nuova riga (%s)}

### File: ../src/windows/table_win.tcl
mcset it {First %s rows} {Prime %s righe}

### File: ../src/windows/table_win.tcl
mcset it {Previous %s rows} {%s Righe precedente}

### File: ../src/windows/table_win.tcl
mcset it {Next %s rows} {%s Righe successive}

### File: ../src/windows/table_win.tcl
mcset it {Last %s rows} {Ultime %s righe}

### File: ../src/windows/table_win.tcl
mcset it {Export table data} {Esporta dati tabella}

### File: ../src/windows/table_win.tcl
mcset it {Import data to table} {Import data to table}

### File: ../src/windows/table_win.tcl
mcset it {Populate table} {Popola tabella}

### File: ../src/windows/table_win.tcl
mcset it {Enter phrase you want to look for} {Inserisci frase da ricercare}

### File: ../src/windows/table_win.tcl
mcset it {Apply data filter} {Applica filtro dati}

### File: ../src/windows/table_win.tcl
mcset it {Clear data filter} {Pulisci filtro dati}

### File: ../src/windows/table_win.tcl
mcset it {Total rows: %s} {Totale righe: %s}

### File: ../src/windows/table_win.tcl
mcset it {Rollback changes (%s)} {Annulla cambiamenti (%s)}

### File: ../src/windows/table_win.tcl
mcset it {First row from data grid (%s)} {Prima riga dei dati (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Previous row from data grid (%s)} {Riga dei dati precedente (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Next row from data grid (%s)} {Riga dei dati successiva (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Last row from data grid (%s)} {Ultima riga dei dati (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Field switching mode.

Click it to make <Tab> key to insert tab characters.} {Modalità scambio campo.

Clicca per far <Tab> inserire il carattere tab.}

### File: ../src/windows/table_win.tcl
mcset it {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.} {Modalità inserimento Tab.

Clicca per far <Tab> key cambio tra i campi di modifica.}

### File: ../src/windows/table_win.tcl
mcset it {Refresh table indexes (%s)} {Aggiorna indici tabella (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Create new index (%s)} {Crea nuovo indice (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Edit index (%s)} {Modifica indice (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Delete index (%s)} {Cancella indice (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Refresh table triggers (%s)} {Aggiorna trigger della tabella (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Create new trigger (%s)} {Crea nuovo trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Edit trigger (%s)} {Modifica trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Delete trigger (%s)} {Cancella trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset it {Constraint name} {Nome restrizione}

### File: ../src/windows/table_win.tcl
mcset it {Column name} {Nome colonna}

### File: ../src/windows/table_win.tcl
mcset it Default Predefinito

### File: ../src/windows/table_win.tcl
mcset it {Not NULL} {Non NULL}

### File: ../src/windows/table_win.tcl
mcset it {Primary key} {Chiave primaria}

### File: ../src/windows/table_win.tcl
mcset it Unique Unico

### File: ../src/windows/table_win.tcl
mcset it Collate Collezione

### File: ../src/windows/table_win.tcl
mcset it Check Controllo

### File: ../src/windows/table_win.tcl
mcset it {Foreign key} {Chiave esterna}

### File: ../src/windows/table_win.tcl
mcset it {Index name} {Nome indice}

### File: ../src/windows/table_win.tcl
mcset it {On column} {Sulla Colonna}

### File: ../src/windows/table_win.tcl
mcset it {SQL code} {Codice SQL}

### File: ../src/windows/table_win.tcl
mcset it {Trigger name} {Nome trigger}

### File: ../src/windows/table_win.tcl
mcset it {On table} {Sulla Tabella}

### File: ../src/windows/table_win.tcl
mcset it Name Nome

### File: ../src/windows/table_win.tcl
mcset it {Data type} {Tipo dati}

### File: ../src/windows/table_win.tcl
mcset it {Default value} {Valore predefinito}

### File: ../src/windows/table_win.tcl
mcset it {Refreshing dependencies} {Aggiornamento dipendenza}

### File: ../src/windows/table_win.tcl
mcset it {Refreshing table columns...} {Aggiornamento colonne tabella...}

### File: ../src/windows/table_win.tcl
mcset it {Refreshing table data...} {Aggiornamento dati tabella...}

### File: ../src/windows/table_win.tcl
mcset it {Refreshing table indexes...} {Aggiornamento indici tabella...}

### File: ../src/windows/table_win.tcl
mcset it {Refreshing table triggers...} {Aggiornamento triggers tabella...}

### File: ../src/windows/table_win.tcl
mcset it {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.} {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.}

### File: ../src/windows/table_win.tcl
mcset it {Check condition} {Verifica condizione}

### File: ../src/windows/table_win.tcl
mcset it {Total rows: %s (filtered)} {Totale righe: %s (filtrato)}

### File: ../src/windows/table_win.tcl
mcset it {Pending commits} {Commits in attesa}

### File: ../src/windows/table_win.tcl
mcset it {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?} {Ci sono delle modifiche non ancora salvate.
Aggiornare i dati le cancellerà.
Sicuro di voler continuare?}

### File: ../src/windows/table_win.tcl
mcset it {Loading data...} {Caricamento dati...}

### File: ../src/windows/table_win.tcl
mcset it {Loading table '%s'...} {Caricamento tabella '%s'...}

### File: ../src/windows/table_win.tcl
mcset it {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.} {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.}

### File: ../src/windows/table_win.tcl
mcset it {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.} {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.}

### File: ../src/windows/table_win.tcl
mcset it {Edit table} {Modifica tabella}

### File: ../src/windows/table_win.tcl
mcset it {Enter number of rows to add:} {Enter number of rows to add:}

### File: ../src/windows/table_win.tcl
mcset it {Add rows} {Add rows}

### File: ../src/windows/table_win.tcl
mcset it {New index} {Nuovo indice}

### File: ../src/windows/table_win.tcl
mcset it {Index '%s' has no DDL. Probably it's system index and should not be edited.} {Index '%s' has no DDL. Probably it's system index and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset it {Edit index} {Modifica indice}

### File: ../src/windows/table_win.tcl
mcset it {Delete index} {Cancella indice}

### File: ../src/windows/table_win.tcl
mcset it {Are you sure you want to delete '%s' index?} {Sei sicuro di voler cancellare l'indice '%s'?}

### File: ../src/windows/table_win.tcl
mcset it {New trigger} {Nuovo trigger}

### File: ../src/windows/table_win.tcl
mcset it {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.} {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset it {Edit trigger} {Modifica trigger}

### File: ../src/windows/table_win.tcl
mcset it {Delete trigger} {Cancella trigger}

### File: ../src/windows/table_win.tcl
mcset it {Are you sure you want to delete '%s' trigger?} {Sei sicuro di voler cancellare il trigger '%s'?}

### File: ../src/windows/table_win.tcl
mcset it {Export table} {Esporta tabella}

### File: ../src/windows/table_win.tcl
mcset it {Import data} {Import data}

### File: ../src/windows/editor_win.tcl
mcset it {SQL query} {Query SQL}

### File: ../src/windows/editor_win.tcl
mcset it Results Risultati

### File: ../src/windows/editor_win.tcl
mcset it History Cronologia

### File: ../src/windows/editor_win.tcl
mcset it {Execute query (%s)} {Esegui query (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Execute query with plain string results} {Esegui query con risultato come testo.}

### File: ../src/windows/editor_win.tcl
mcset it {Explain query (%s)} {Spiega query (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Format SQL code (%s)} {Formato codice SQL (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Refresh syntax highlighting (%s)} {Aggiorna evidenziazione sintassi (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Clear history} {Cancella cronologia}

### File: ../src/windows/editor_win.tcl
mcset it {Export results} {Esporta risultati}

### File: ../src/windows/editor_win.tcl
mcset it {Create view from query} {Crea vista da query}

### File: ../src/windows/editor_win.tcl
mcset it {Execute SQL from file (%s)} {Esegui SQL da file (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Load SQL from file (%s)} {Carica SQL da file (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Save SQL to file (%s)} {Salva SQL su file (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Default database for SQL executing
(%s/%s)} {Database di default per l'esecuzione di SQL
(%s/%s)}

### File: ../src/windows/editor_win.tcl
mcset it Database Database

### File: ../src/windows/editor_win.tcl
mcset it {Execution date} {Data esecuzione}

### File: ../src/windows/editor_win.tcl
mcset it {Execution time (s)} {Tempo d'esecuzione (s)}

### File: ../src/windows/editor_win.tcl
mcset it {Rows affected} {Righe coinvolte}

### File: ../src/windows/editor_win.tcl
mcset it SQL SQL

### File: ../src/windows/editor_win.tcl
mcset it {Plain text view} {Vista a testo}

### File: ../src/windows/editor_win.tcl
mcset it {Refresh results (%s)} {Aggiorna risultati (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Commit row (%s)} {Commit row (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Rollback row (%s)} {Rollback row (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Copy (%s)} Copia(%s)

### File: ../src/windows/editor_win.tcl
mcset it {Cut (%s)} {Taglia (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Paste (%s)} {Incolla (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Show line numbers} {Mostra numeri linee}

### File: ../src/windows/editor_win.tcl
mcset it {Delete selected history entry (%s)} {Delete selected history entry (%s)}

### File: ../src/windows/editor_win.tcl
mcset it {Choose the database first.} {Seleziona prima il database.}

### File: ../src/windows/editor_win.tcl
mcset it {Error while trying to collect completion list: %s} {Errure durante il caricamento della lista di suggerimento: %s}

### File: ../src/windows/editor_win.tcl
mcset it {Can't open %s file for reading.} {Impossibile aprire il file %s per la lettura.}

### File: ../src/windows/editor_win.tcl
mcset it {Can't open %s file for writting.} {Impossibile aprire il file %s per la scrittura.}

### File: ../src/windows/editor_win.tcl
mcset it {SQL code saved in %s.} {Codice SQL salvato in %s.}

### File: ../src/windows/editor_win.tcl
mcset it {Are you sure you want to clear queries history?} {Sei sicuro di voler cancellare la cronologia delle query?}

### File: ../src/windows/editor_win.tcl
mcset it {Delete the history entry} {Delete the history entry}

### File: ../src/windows/editor_win.tcl
mcset it {Are you sure you want to delete selected queries history entry?} {Are you sure you want to delete selected queries history entry?}

### File: ../src/windows/editor_win.tcl
mcset it Processing... Elaborazione...

### File: ../src/windows/editor_win.tcl
mcset it {Processing query...} {Elaborazione query...}

### File: ../src/windows/editor_win.tcl
mcset it {No results to export.} {Nessun risultato da esportare.}

### File: ../src/windows/editor_win.tcl
mcset it {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.} {Utilizzo di allegare da editor SQL non è permesso. Al contrario, registra il database che si desidera collegare in SQLiteStudio e utilizzare il suo nome visibile nella struttura ad albero dei database in qualsiasi istruzioni SQL necessarie. Essi saranno automaticamente iscritti su richiesta.}

### File: ../src/windows/editor_win.tcl
mcset it {Query execution...} {Esecuzione Query...}

### File: ../src/windows/editor_win.tcl
mcset it {Executing SQL query...} {Esecuzione query SQL...}

### File: ../src/windows/editor_win.tcl
mcset it {Error while executing query: %s} {Errore durante l'esecuzione della query: %s}

### File: ../src/windows/editor_win.tcl
mcset it {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s} {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s}

### File: ../src/windows/editor_win.tcl
mcset it {%s row(s) read in %s second(s).} {%s row(s) read in %s second(s).}

### File: ../src/windows/editor_win.tcl
mcset it {%s row(s) affected in %s second(s).} {%s riga(he) coinvolte in %s secondi.}

### File: ../src/windows/editor_win.tcl
mcset it {No SELECT statements found in editor or in selected part of SQL code.} {No SELECT statements found in editor or in selected part of SQL code.}

### File: ../src/windows/editor_win.tcl
mcset it {More than one SELECT statements found. Please select the one you're interested in and then try again.} {More than one SELECT statements found. Please select the one you're interested in and then try again.}

### File: ../src/windows/editor_win.tcl
mcset it {New view} {Nuova vista}

### File: ../src/windows/editor_win.tcl
mcset it {Fill query parameters} {Riempi parametri query}

### File: ../src/error.tcl
mcset it {Background error} Errore

### File: ../src/error.tcl
mcset it Close Chiudi

### File: ../src/error.tcl
mcset it {Report the bug} {Riporta un problema}

### File: ../src/dialogs/about_dialog.tcl
mcset it About {A Proposito...}

### File: ../src/dialogs/about_dialog.tcl
mcset it {Packages and plugins} {Pacchetti e plugins}

### File: ../src/dialogs/about_dialog.tcl
mcset it Licence Licenza

### File: ../src/dialogs/about_dialog.tcl
mcset it {Installed plugins:} {Plug-in installati:}

### File: ../src/dialogs/about_dialog.tcl
mcset it {Used Tcl packages:} {Pacchetto Tcl usato:}

### File: ../src/dialogs/about_dialog.tcl
mcset it {SQLite3 engine version: %s} {Versione SQLite3: %s}

### File: ../src/dialogs/searchdialog.tcl
mcset it {Global expression understeands '*', '?' and \[chars].} {Comprensione espressione globale '*', '?' and \[chars].}

### File: ../src/dialogs/searchdialog.tcl
mcset it Find Cerca

### File: ../src/dialogs/searchdialog.tcl
mcset it Replace Sostituisci

### File: ../src/dialogs/searchdialog.tcl
mcset it {Do you want to replace marked text?} {Vuoi sostituire il testo selezionato?}

### File: ../src/dialogs/searchdialog.tcl
mcset it {Replace all} {Sostituisci tutto}

### File: ../src/dialogs/searchdialog.tcl
mcset it {Replacing finished.} {Sostituzione finita.}

### File: ../src/dialogs/searchdialog.tcl
mcset it {Cannot match the pattern!} {Impossibile trovare il testo!}

### File: ../src/dialogs/bind_param.tcl
mcset it {Query number %s} {Query numero %s}

### File: ../src/dialogs/bind_param.tcl
mcset it {Parameter number %s (named: %s):} {Parametro numero %s (chiamato: %s):}

### File: ../src/dialogs/bind_param.tcl
mcset it {NULL value} {NULL value}

### File: ../src/dialogs/bind_param.tcl
mcset it {You can use '%s' keyboard shortcut to switch NULL value.} {You can use '%s' keyboard shortcut to switch NULL value.}

### File: ../src/dialogs/bind_param.tcl
mcset it {Copy value to other '%s' parameters (%s)} {Copy value to other '%s' parameters (%s)}

### File: ../src/dialogs/bind_param.tcl
mcset it {By enabling this all parameters with same name
will also have same value as this one.} {By enabling this all parameters with same name
will also have same value as this one.}

### File: ../src/dialogs/bind_param.tcl
mcset it {Execute query} {Esegui query}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset it Collation Collezione

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset it Sort Ordina

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset it {Named constraint:} {Nome vincolo:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset it {On conflict:} {In conflitto:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset it {Constraint is marked as being named, but there's no name filled in.} {Vincolo segnato con nome, ma nessun nome assegnato.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset it {Collation for column '%s' is enabled, but there's no collation name filled in.} {Collezione per colonna '%s' è abilitata, ma nessuna collezione è stata assegnata.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset it {No columns are selected.} {Nessuna colonna selezionata.}

### File: ../src/dialogs/populate_table.tcl
mcset it {Number of rows to insert:} {Numero di righe inserite:}

### File: ../src/dialogs/populate_table.tcl
mcset it {On a constraint violation:} {On a constraint violation:}

### File: ../src/dialogs/populate_table.tcl
mcset it Mode Modalità

### File: ../src/dialogs/populate_table.tcl
mcset it {Select table to display available columns} {Selezionare la tabella di cui mostrare le colonne disponibili}

### File: ../src/dialogs/populate_table.tcl
mcset it Populate Popola

### File: ../src/dialogs/populate_table.tcl
mcset it {Error occured while populating table:
%s} {E' occorso un errore durante il popolamente della tabella:
%s}

### File: ../src/dialogs/populate_table.tcl
mcset it Configuration Configuration

### File: ../src/dialogs/populate_table.tcl
mcset it {You have to type valid number of rows to insert.} {Devi digitare un numero valido di riga da inserire.}

### File: ../src/dialogs/populate_table.tcl
mcset it {You have to select at least one column to populate.} {Devi inserire almeno una colonna da popolare.}

### File: ../src/dialogs/populate_table.tcl
mcset it Populating... Popolamento...

### File: ../src/dialogs/populate_table.tcl
mcset it {Populating table '%s'.} {Popolamento tabella '%s'.}

### File: ../src/dialogs/populate_table.tcl
mcset it Stop Stop

### File: ../src/dialogs/table_dialog_fk.tcl
mcset it {Foreign table:} {Tabella esterna:}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset it {Local column} {Colonna locale}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset it {Foreign column} {Colonna esterna}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset it Reactions Reazioni

### File: ../src/dialogs/table_dialog_fk.tcl
mcset it {ON UPDATE} {ON UPDATE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset it {ON DELETE} {ON DELETE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset it MATCH MATCH

### File: ../src/dialogs/table_dialog_fk.tcl
mcset it {Deferred foreign key} {Chiave esterna differita}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset it {No foreign table selected.} {Nessuna tabella esterna selezionata.}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset it {There's no foreign column assigned for local column '%s'.} {Non c'è alcuna colonna esterna assegnata per la colonna locale '%s'.}

### File: ../src/dialogs/import_dialog.tcl
mcset it {Import from:} {Import from:}

### File: ../src/dialogs/import_dialog.tcl
mcset it {Import to:} {Import to:}

### File: ../src/dialogs/import_dialog.tcl
mcset it Table Tabella

### File: ../src/dialogs/import_dialog.tcl
mcset it Existing Existing

### File: ../src/dialogs/import_dialog.tcl
mcset it {Create new table} {Create new table}

### File: ../src/dialogs/import_dialog.tcl
mcset it Import Import

### File: ../src/dialogs/import_dialog.tcl
mcset it {Import method is not selected.} {Import method is not selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset it {You have to choose database.} {Devi selezionare un database.}

### File: ../src/dialogs/import_dialog.tcl
mcset it {No existing table is selected.} {No existing table is selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset it {Table typed to create already exists. Please change table name.} {Table typed to create already exists. Please change table name.}

### File: ../src/dialogs/view_dialog.tcl
mcset it View Viste

### File: ../src/dialogs/view_dialog.tcl
mcset it {View name:} {Nome Vista:}

### File: ../src/dialogs/view_dialog.tcl
mcset it {Code executed to get view data:} {Codice eseguito per ottenere i dati della vista:}

### File: ../src/dialogs/view_dialog.tcl
mcset it Create Crea

### File: ../src/dialogs/view_dialog.tcl
mcset it Change Cambia

### File: ../src/dialogs/view_dialog.tcl
mcset it {You have to specify database.} {Devi specificare un database.}

### File: ../src/dialogs/view_dialog.tcl
mcset it {You have to specify view name.} {Devi specificare il nome della vista.}

### File: ../src/dialogs/view_dialog.tcl
mcset it {You havn't wrote a code for the view.} {Non è stato scritto il codice per la vista.}

### File: ../src/dialogs/export_dialog.tcl
mcset it {Export data} {Esporta dati}

### File: ../src/dialogs/export_dialog.tcl
mcset it {Only structure, without data} {Solo struttura, senza dati}

### File: ../src/dialogs/export_dialog.tcl
mcset it {Table or view} {Table or view}

### File: ../src/dialogs/export_dialog.tcl
mcset it {Output file} {File esportazione}

### File: ../src/dialogs/export_dialog.tcl
mcset it {Export format} {Formato esportazione}

### File: ../src/dialogs/export_dialog.tcl
mcset it Export Esporta

### File: ../src/dialogs/export_dialog.tcl
mcset it {You have to choose file.} {Devi selezionare il file.}

### File: ../src/dialogs/export_dialog.tcl
mcset it {Can't write to file: %s} {Impossibile salvare il file: %s}

### File: ../src/dialogs/export_dialog.tcl
mcset it {You have to choose table.} {Devi selezionare una tabella.}

### File: ../src/dialogs/export_dialog.tcl
mcset it {Exporting database '%s'.} {Esportazione database '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset it {Exporting table '%s'.} {Esportazione tabella '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset it {Exporting view '%s'.} {Exporting view '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset it {Exporting results.} {Esportazioen risultati.}

### File: ../src/dialogs/export_dialog.tcl
mcset it Exporting... Esportazione...

### File: ../src/dialogs/export_dialog.tcl
mcset it {Cannot write to file: %s
Please select other file.} {Impossibile scrivere il file: %s
Per favore selezionare un'altro file.}

### File: ../src/dialogs/bug_report_login.tcl
mcset it {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.} {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.}

### File: ../src/dialogs/bug_report_login.tcl
mcset it Login: Login:

### File: ../src/dialogs/bug_report_login.tcl
mcset it Password: Password:

### File: ../src/dialogs/bug_report_login.tcl
mcset it Validate Validate

### File: ../src/dialogs/bug_report_login.tcl
mcset it {Validation result} {Validation result}

### File: ../src/dialogs/bug_report_login.tcl
mcset it {Not validated yet} {Not validated yet}

### File: ../src/dialogs/bug_report_login.tcl
mcset it Validating... Validating...

### File: ../src/dialogs/bug_report_login.tcl
mcset it {Validating login and password...} {Validating login and password...}

### File: ../src/dialogs/bug_report_login.tcl
mcset it {Invalid login or password.} {Invalid login or password.}

### File: ../src/dialogs/bug_report_login.tcl
mcset it {Login and password are correct.} {Login and password are correct.}

### File: ../src/dialogs/bug_report.tcl
mcset it {Your e-mail address or user (both optional)} {Your e-mail address or user (both optional)}

### File: ../src/dialogs/bug_report.tcl
mcset it or o

### File: ../src/dialogs/bug_report.tcl
mcset it {Log in} {Log in}

### File: ../src/dialogs/bug_report.tcl
mcset it {Logged in} {Logged in}

### File: ../src/dialogs/bug_report.tcl
mcset it {Log out} {Log out}

### File: ../src/dialogs/bug_report.tcl
mcset it {Brief description:} {Descrizione riassunto:}

### File: ../src/dialogs/bug_report.tcl
mcset it {How to reproduce problem (if possible):} {Come riprodurre il problema (se possibile):}

### File: ../src/dialogs/bug_report.tcl
mcset it {What is the problem:} {Qual'è il problema:}

### File: ../src/dialogs/bug_report.tcl
mcset it {Show more (optional)} {Show more (optional)}

### File: ../src/dialogs/bug_report.tcl
mcset it {Operating system:} {Sistema operativo:}

### File: ../src/dialogs/bug_report.tcl
mcset it {Take screenshots of all SQLiteStudio windows and attach them} {Prendi una schermata di tutte le finestre di SQLiteStudio e allegale}

### File: ../src/dialogs/bug_report.tcl
mcset it Send Invia

### File: ../src/dialogs/bug_report.tcl
mcset it {Describe your feature request:} {Descrivi la funzione richiesta:}

### File: ../src/dialogs/bug_report.tcl
mcset it Hide Hide

### File: ../src/dialogs/bug_report.tcl
mcset it {Please fill 'Brief' field.} {Per favore compila il campo 'Riassunto'.}

### File: ../src/dialogs/bug_report.tcl
mcset it {Please fill at least one of 'Description' or 'How to reproduce' fields.} {Si prega di compilare almeno uno dei campi 'Descrizione' o 'come riprodurre'.}

### File: ../src/dialogs/bug_report.tcl
mcset it {Please provide valid e-mail address or leave 'E-mail' empty.} {Please provide valid e-mail address or leave 'E-mail' empty.}

### File: ../src/dialogs/bug_report.tcl
mcset it {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.} {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.}

### File: ../src/dialogs/db_convert.tcl
mcset it {Database to convert:} {Database da convertire:}

### File: ../src/dialogs/db_convert.tcl
mcset it {Converted database name:} {Nome database convertito:}

### File: ../src/dialogs/db_convert.tcl
mcset it {File to use for converted database:} {File da usare per il database convertito:}

### File: ../src/dialogs/db_convert.tcl
mcset it {Choose new file for database} {Seleziona nuovo file per il database}

### File: ../src/dialogs/db_convert.tcl
mcset it {Database version:} {Versione Database:}

### File: ../src/dialogs/db_convert.tcl
mcset it Convert Converti

### File: ../src/dialogs/db_convert.tcl
mcset it {Convert database} {Converti database}

### File: ../src/dialogs/db_convert.tcl
mcset it {You chave to choose database to convert.} {Devi selezionare un database da convertire.}

### File: ../src/dialogs/db_convert.tcl
mcset it {Error resolving database with name %s!} {Errore nella conversione del database con nome %s!}

### File: ../src/dialogs/db_convert.tcl
mcset it {You have to specify new database file.} {Devi specificare un nuovo file del database.}

### File: ../src/dialogs/db_convert.tcl
mcset it {Cannot use existing file for converted database.} {Non è possibile usare una file esistente per un database convertito.}

### File: ../src/dialogs/db_convert.tcl
mcset it {Cannot use existing name for converted database.} {Non è possibile usare un nome esistente per il database convertito.}

### File: ../src/dialogs/db_convert.tcl
mcset it {Cannot find handler for database labeled with: %s} {Impossibile trovare un gestore del database con etichetta %s}

### File: ../src/dialogs/db_convert.tcl
mcset it {Error while trying to create database: %s} {Errore nella creazione del database: %s}

### File: ../src/dialogs/db_convert.tcl
mcset it {Database converting error} {Database converting error}

### File: ../src/dialogs/db_convert.tcl
mcset it {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s} {E' occorso qualche problema durante la conversione del database, ma è stato convertito omettendo degli oggetti causando il problema. Dettagli:
%s}

### File: ../src/dialogs/db_convert.tcl
mcset it {Choose file} {Seleziona file}

### File: ../src/dialogs/yesno.tcl
mcset it Question Question

### File: ../src/dialogs/yesno.tcl
mcset it Warning Avvisi

### File: ../src/dialogs/yesno.tcl
mcset it Error Errore

### File: ../src/dialogs/yesno.tcl
mcset it Information Informazioni

### File: ../src/dialogs/import_db.tcl
mcset it {Import from one of databases:} {Importa da uno dei databases:}

### File: ../src/dialogs/import_db.tcl
mcset it {Choose database file to import:} {Seleziona database da importare:}

### File: ../src/dialogs/import_db.tcl
mcset it {No database chosen.} {Nessun database selezionato.}

### File: ../src/dialogs/import_db.tcl
mcset it {Cannot open specified database.} {Impossibile aprire database selezionato.}

### File: ../src/dialogs/import_db.tcl
mcset it {Error while importing database:
%s} {Errore nell'importazione del database:
%s}

### File: ../src/dialogs/import_db.tcl
mcset it {Select file} {Seleziona file}

### File: ../src/dialogs/column_dialog.tcl
mcset it Column: Colonna:

### File: ../src/dialogs/column_dialog.tcl
mcset it {Column constraints:} {Vincoli colonna:}

### File: ../src/dialogs/column_dialog.tcl
mcset it Add Aggiungi

### File: ../src/dialogs/column_dialog.tcl
mcset it Size Dimensione

### File: ../src/dialogs/column_dialog.tcl
mcset it {Maximal length of value in column.} {Lunghezza massima del valore per la colonna.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Primary key configuration} {Configura chiave primaria}

### File: ../src/dialogs/column_dialog.tcl
mcset it Autoincrement Autoincrement

### File: ../src/dialogs/column_dialog.tcl
mcset it {Sort order:} {Ordina per:}

### File: ../src/dialogs/column_dialog.tcl
mcset it {No foreign column selected.} {Nessuna chiave esterna selezionata.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Choose ON UPDATE action, or disable it.} {Scegli ON UPDATE, o disabilitala.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Choose ON DELETE action, or disable it.} {Scegli ON DELETE, o disabilitala.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Choose MATCH action, or disable it.} {Scegli MATCH, o disabilitala.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Foreign key configuration} {Configurazione chiave esterna}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Foreign column:} {Colonna esterna:}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Unique configuration} {Configurazione UNICO}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Fill in the condition expression.} {Riempi l'espressione di condizione.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Check condition configuration} {Verifica configurazione condizioni}

### File: ../src/dialogs/column_dialog.tcl
mcset it Condition: Condizione:

### File: ../src/dialogs/column_dialog.tcl
mcset it {Not null configuration} {Configurazione non null}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Fill in the collation name.} {Riempi il nome della collezione.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Collating configuration} {Configurazione collezione}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Collation name:} {Nome Collezione:}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Fill in the default value.} {Inserisci il valore di default.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Default value configuration} {Configurazione valore di default}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Default value:} {Valore di Default:}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Use value as:} {Use value as:}

### File: ../src/dialogs/column_dialog.tcl
mcset it {A literal value} {A literal value}

### File: ../src/dialogs/column_dialog.tcl
mcset it {An expression} {An expression}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Column primary key is not configured correctly.} {Chiave primaria della colonna non configurata correttamente.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {AUTOINCREMENT is allowed only with INTEGER type of column.} {AUTOINCREMENT is allowed only with INTEGER type of column.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Column foreign key is not configured correctly.} {Chiave esterna della colonna non configurata correttamente.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Column 'unique' constraint is not configured correctly.} {Colonna con vincolo UNICO non configurata correttamente.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Column 'check' constraint is not configured correctly.} {Colonna con vincolo CHECK non configurata correttamente.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Column 'notnull' constraint is not configured correctly.} {Colonna con vincolo NOTNULL non configurata correttamente.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Column 'default' constraint is not configured correctly.} {Colonna con vincolo DEFAULT non configurata correttamente.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Column 'collate' constraint is not configured correctly.} {Colonna con vincolo COLLATE non configurata correttamente.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {No column name is specified.} {Nessun nome colonna specificato.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Column with name '%s' already exists in the table.} {Colonna con nome '%s' esiste già nella tabella.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Data type bounds are given, but no data type name is specified.} {Limiti dei tipi di dati impostati, ma nessun nome è specificato per il tipo di dati.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Data type precision is given, but no data type size is specified.} {Limiti della precisione dei dati impostati, ma nessun nome è specificato per il tipo di dati.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Data type size has invalid format. Only integer value is allowed.} {Formato dati non valido. Solo numeri interi sono permessi.}

### File: ../src/dialogs/column_dialog.tcl
mcset it {Data type precision has invalid format. Only integer value is allowed.} {Precisione dei dati con formato non corretto. Solo numeri interi permessi.}

### File: ../src/dialogs/assoc_dialog.tcl
mcset it {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:} {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:}

### File: ../src/dialogs/assoc_dialog.tcl
mcset it {Current associations} {Current associations}

### File: ../src/dialogs/assoc_dialog.tcl
mcset it {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.} {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.}

### File: ../src/dialogs/db_edit.tcl
mcset it {Database file:} {File database:}

### File: ../src/dialogs/db_edit.tcl
mcset it {Database name:} {Nome database:}

### File: ../src/dialogs/db_edit.tcl
mcset it {Generate automatically} {Genera automaticamente}

### File: ../src/dialogs/db_edit.tcl
mcset it {Type name in field below:} {Digita il nome nel campo qui sotto:}

### File: ../src/dialogs/db_edit.tcl
mcset it {Remember it permanently} {Remember it permanently}

### File: ../src/dialogs/db_edit.tcl
mcset it {If disabled, then the database will be registered only
for this single SQLiteStudio session.} {Se disabilitata, il database verrà registrato solo per questa sessione.}

### File: ../src/dialogs/db_edit.tcl
mcset it {Edit database} {Modifica database}

### File: ../src/dialogs/db_edit.tcl
mcset it {Add database} {Aggiungi database}

### File: ../src/dialogs/db_edit.tcl
mcset it {File '%s' doesn't exist!} {File '%s' doesn't exist!}

### File: ../src/dialogs/db_edit.tcl
mcset it {You have to specify database file.} {Devi specificare il file del database.}

### File: ../src/dialogs/db_edit.tcl
mcset it {Database named '%s' already exists on databases list. Please pick other name.} {Database named '%s' already exists on databases list. Please pick other name.}

### File: ../src/dialogs/db_edit.tcl
mcset it {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.} {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.}

### File: ../src/dialogs/db_edit.tcl
mcset it {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.} {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.}

### File: ../src/dialogs/db_edit.tcl
mcset it {Type not existing file for new database} {Digita un file non esistente per il nuovo database}

### File: ../src/dialogs/db_edit.tcl
mcset it {Select existing database file} {Seleziona database esistente}

### File: ../src/dialogs/db_edit.tcl
mcset it {%s is not supported database!} {%s non è un database supportato!}

### File: ../src/dialogs/table_dialog_pk.tcl
mcset it {Using autoincrement with more than one column at once is forbidden.} {Using autoincrement with more than one column at once is forbidden.}

### File: ../src/dialogs/tips_dialog.tcl
mcset it Previous Precedente

### File: ../src/dialogs/tips_dialog.tcl
mcset it Next Successivo

### File: ../src/dialogs/tips_dialog.tcl
mcset it {Do not show this dialog at startup} {Non mostrare questa finestra all'avvio}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		} {
			Se non ti piace aprire più editor SQL, puoi usare un solo editor,
			per scrivere un sacco di SQL e poi selezionare solo la parte di codice che vuoi eseguire,
			poi premi Esegui SQL.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			You can configure all SQL editor syntax colors in settings.
		} {
			Puoi impostare tutti i colori della sintassi SQL nei settaggi.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		} {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		} {
			Puoi usare CTRL+Spazio (Configurabile) per completare quello che hai iniziato a scrivere nell'editor.
			Il motore di completamente può anche indovinare la parola successiva in un contesto SQL e mostrare un elenco di parole corrispondenti quel contesto.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		} {
			Ci sono varie scorciatoie (tutte configurabili) che possono rendere molto più semplice
			e veloce l'utilizzo di SQLiteStudio.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		} {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		} {
			Se si chiude SQLiteStudio con tutte le finestre MDI aperti, tutte saranno ripristinate (incluso il codice SQL digitato nell'editor),
			col prossimo avvio dell'applicazione, a meno che non si disattiva "il ripristino della sessione" nelle impostazioni.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		} {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		} {
			È possibile definire le proprie funzioni SQL che saranno disponibili nel database durante la modifica con SQLiteStudio.
			Aiuta a emulare funzioni implementate in applicazione destinate all'uso del database. <br>
			Per implementare la nuova funzione di dialogo vai in Funzioni SQL Personalizzate e premi sul pulsante Aggiungi (una con l'icona più),
			quindi immettere il suo nome e scegliere la lingua che si desidera utilizzare per implementare la funzione (Tcl o SQL). <br>
			Codice di attuazione può contenere $0, $1, $2 e così via - sono parametri posizionali passati alla funzione quando viene invocata <br>.
			Ecco l'esempio di attuazione del codice funzione mediante SQL: <br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		} {
			Se siete alla ricerca di qualche parola nella tabella dati, ma non volete scrivere SQL per essa, o semplicemente non ricordate
			la colonna che contiene questa parola, andate sulla tabella che mostra i dati, digitare la parola nella voce del filtro e premere "Applica filtro".
			Troverà così tutte le occorrenze della parola (anche con prefissi o suffissi) in qualsiasi
			colonna e tabella i dati verranno filtrati a solo per queste voci.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		} {
			È possibile modificare i valori nella griglia dei risultati, ma siate consapevoli che le colonne che non viengono da una direttamente tabella (per esempio perchè sono il risultato di operazioni matematiche su colonna) - non possono essere modificato.
			Tali celle non modificabili sono anche omesse quando alcuni dati sono stati incollati in griglia.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		} {
			Se volete vedere il ROWID di qualche riga specifica, si può semplicemente lasciare il puntatore del mouse sopra la riga che interessa al momento.
			La fumetto si aprirà con il ROWID (e altre informazioni) per quella riga. <br>
			Griglia dei dati della tabella è possibile cambiare la visualizzazione ROWID Invece del numero di ordine nella prima colonna. Questa opzione è disponibile dal menu contestuale di vista griglia.}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		} {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		} {
			È possibile inserire i risultati della query eseguita sotto la query attuale, invece di passare alla scheda successiva. Basta cambiare layout delle finestre di SQL Editor nella finestra di configurazione.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		} {
			È sempre possibile tornare alle query che hai eseguito prima, passando alla scheda Cronologia nella finestra di SQL Editor. <br>
			Numero di voci tenute nella storia è configurabile, ma essere consapevoli che, se tale valore è troppo alto, quindi ogni volta che si aprirà nuovo Editor SQL
			tutta la storia verrà letto e che potrebbe rallentare il processo di apertura.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		} {
			La finestra dell'editor SQL può aiutare a scrivere le query - premere Ctrl + Spazio (o qualsiasi collegamento che avete configurato) nella finestra di dialogo per attivare il completamento del codice.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		} {
			E' possibile usare più nomi di database in un unica query SQL senza preoccuparsi di collegarle al database corrente.
			SQLiteStudio lo farà per te.<br><br>
			Usa i nomi dei database com mostrato nell'albero del database alla vostra sinistra. Un esempio:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		} {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset it {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		} {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		}

### File: ../src/dialogs/import_table.tcl
mcset it Separator: Separatore:

### File: ../src/dialogs/import_table.tcl
mcset it {Common separator is \t (tab), but sometimes others can be met.} {Separatore comune è \t (tab), ma in alcuni casi possono esserne usati altri.}

### File: ../src/dialogs/import_table.tcl
mcset it {Import data file for '%s' table:} {Importa dati da file per la tabella '%s':}

### File: ../src/dialogs/import_table.tcl
mcset it {File '%s' isn't readable!} {Il file '%s' non è leggibile!}

### File: ../src/dialogs/import_table.tcl
mcset it {Error while trying to copy data:
%s} {Errore nella copia dei dati:
%s}

### File: ../src/dialogs/release_notes_dialog.tcl
mcset it {Don't show this dialog after update.} {Don't show this dialog after update.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it Trigger Trigger

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {On action:} {Su azione:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {Trigger name:} {Nome trigger:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it When: Quando:

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {On table:} {Sulla tabella:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {Execute code for:} {Esegui codice per:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.} {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {Execute code only when:} {Esegui codice solo quando:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {Code executed for above configuration:} {Codice eseguito per la configurazione superiore:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {You have to specify view.} {Devi specificare una vista.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {You have to specify table.} {Devi specificare una tabella.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {You have to specify trigger name.} {Devi specificare il nome del trigger.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {You have to specify 'action' condition.} {Devi specificare la condizione 'azione'.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {You havn't wrote a code for the trigger.} {Non è stato scritto il codice per il trigger.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset it {On view:} {Sulla vista:}

### File: ../src/dialogs/table_dialog.tcl
mcset it Columns: Colonne:

### File: ../src/dialogs/table_dialog.tcl
mcset it {Table constraints:} {Vincoli tabella:}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Table name:} {Nome tabella:}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Add column} {Aggiungi colonna}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Edit selected} {Modifica selezionato}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Delete selected} {Cancella selezionato}

### File: ../src/dialogs/table_dialog.tcl
mcset it Type Tipo

### File: ../src/dialogs/table_dialog.tcl
mcset it Details Details

### File: ../src/dialogs/table_dialog.tcl
mcset it {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.} {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Edit column} {Modifica colonna}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Delete column} {Cancella colonna}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Are you sure you want to delete column '%s'?} {Sei sicuro di voler cancellare la colonna '%s'?}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Constraint change} {Constraint change}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Are you sure you want to change constraint type?
Current constraint configuration will be lost.} {Are you sure you want to change constraint type?
Current constraint configuration will be lost.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Table constraint number %s (%s) is not configured correctly.} {Table constraint number %s (%s) is not configured correctly.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {There's no column defined.} {Nessuna colonna definita.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {There is already a table with name '%s'. Please change the name of this table.} {There is already a table with name '%s'. Please change the name of this table.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {There is already an index with name '%s'. Please change the name of this index.} {There is already an index with name '%s'. Please change the name of this index.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {There is already a trigger with name '%s'. Please change the name of this trigger.} {There is already a trigger with name '%s'. Please change the name of this trigger.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {There is already a view with name '%s'. Please change the name of this view.} {There is already a view with name '%s'. Please change the name of this view.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Impossibile eseguire DDL per il trigger '%s',
percui non è possibile recrearlo dopo aver modificato la tabella.
Vuoi continuare?}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Trigger parsing problem} {Problema esecuzione Trigger}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Impossibile leggere il DDL per l'indice '%s',
quindi non è possibile ricrearlo dopo aver modificato la tabella.
Vuoi continuare?}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Index parsing problem} {Problema di letture indice}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset it {View parsing problem} {View parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.} {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {%s(%s) referencing %s(%s)} {%s(%s) referencing %s(%s)}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s} {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Do you want to continue anyway?} {Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?} {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Modifying table...} {Modifica tabella...}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Modifying table '%s'.} {Modifica tabella '%s'.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Could not recreate triggers for modified table.} {Impossibile ricreare i trigger per la tabella modificata.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Could not recreate indexes for modified table.} {Impossibile ricreare gli indici per la tabella modificata.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Could not recreate views for modified table.} {Could not recreate views for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?} {Non sarà possibile recreare il trigger '%s' dopo aver modificato la tabella.
Vuoi continuare comunque?}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Trigger recreation problem} {Problema ricreazione Trigger}

### File: ../src/dialogs/table_dialog.tcl
mcset it {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?} {Non sarà possibile ricreare l'indice '%s' dopo la modifica alla tabella.
Vuoi continuare comunque?}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Index recreation problem} {Problema ri-creazione indice}

### File: ../src/dialogs/table_dialog.tcl
mcset it {Could not recreate foreign keys for tables referencing modified table.} {Could not recreate foreign keys for tables referencing modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset it {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset it {View recreation problem} {View recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset it {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).} {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).}

### File: ../src/dialogs/table_dialog_chk.tcl
mcset it {Condition expression cannot be empty.} {Espressione condizione non può essere vuoto.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset it {What would you like to do?} {Vuoi farlo?}

### File: ../src/dialogs/new_version_dialog.tcl
mcset it {Install it automatically} {Installa automaticamente}

### File: ../src/dialogs/new_version_dialog.tcl
mcset it {Go to download page} {Vai alla pagina di download}

### File: ../src/dialogs/new_version_dialog.tcl
mcset it {Package download} {Scarica pacchetto}

### File: ../src/dialogs/new_version_dialog.tcl
mcset it {Insufficient privileges to perform automatic update.} {Insufficient privileges to perform automatic update.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset it {Check for updates at startup} {Verifica aggiornamenti all'avvio}

### File: ../src/dialogs/new_version_dialog.tcl
mcset it {New version of SQLiteStudio is available: %s} {Nuova versione di SQLiteStudio disponibile: %s}

### File: ../src/dialogs/trigger_dialog_cols.tcl
mcset it {Trigger columns} {Trigger columns}

### File: ../src/dialogs/blob_edit.tcl
mcset it Commit Ripara

### File: ../src/dialogs/bug_history.tcl
mcset it Clear Pulisci

### File: ../src/dialogs/bug_history.tcl
mcset it {Reported on} {Segnalato su}

### File: ../src/dialogs/bug_history.tcl
mcset it Brief Riassunto

### File: ../src/dialogs/bug_history.tcl
mcset it URL URL

### File: ../src/dialogs/bug_history.tcl
mcset it Discussion Discussione

### File: ../src/dialogs/bug_history.tcl
mcset it {Clear reports} {Pulisci rapporto}

### File: ../src/dialogs/bug_history.tcl
mcset it {Do you want to clear whole bug reports history?} {Vuoi pulire l'intera cronologia dei bug?}

### File: ../src/dialogs/index_dialog.tcl
mcset it Index Index

### File: ../src/dialogs/index_dialog.tcl
mcset it {Index name:} {Nome Indice:}

### File: ../src/dialogs/index_dialog.tcl
mcset it Available Available

### File: ../src/dialogs/index_dialog.tcl
mcset it Indexed Indexed

### File: ../src/dialogs/index_dialog.tcl
mcset it {Modifying index} {Modifying index}

### File: ../src/dialogs/index_dialog.tcl
mcset it {Modifying index '%s'} {Modifying index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset it {Creating index} {Creating index}

### File: ../src/dialogs/index_dialog.tcl
mcset it {Creating index '%s'} {Creating index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset it {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?} {Impossibile creare Unique index,
perchè la colonna selezionata contiene duplicati.
Vuoi vedere questi valori?}

### File: ../src/dialogs/index_dialog.tcl
mcset it {Unique values} {Valore UNICO}

### File: ../src/dialogs/index_dialog.tcl
mcset it {Same values for '%s'} {Alcuni valori per '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset it {You have to select at least one column.} {Devi selezionare almeno una colonna.}

### File: ../src/dialogs/index_dialog.tcl
mcset it {You have to specify index name.} {Devi specificare il nome dell'indice.}

### File: ../src/dialogs/functions_dialog.tcl
mcset it Implementation: Implementazione:

### File: ../src/dialogs/functions_dialog.tcl
mcset it Name: Nome:

### File: ../src/dialogs/functions_dialog.tcl
mcset it {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.} {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.}

### File: ../src/dialogs/functions_dialog.tcl
mcset it {Cannot use two functions with same name! Change name for '%s'.} {Impossibile usare due funzioni con lo stesso nome! Cambia nome a '%s'.}

### File: ../src/dialogs/functions_dialog.tcl
mcset it {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! } {Impossibile usare 'tcl' o 'sqlfile' come nome di funzione, questi nomei sono riservati! }

### File: ../src/dialogs/functions_dialog.tcl
mcset it {Function '%s' is not implemented!} {La funzione '%s' non è implementata!}

### File: ../src/dialogs/functions_dialog.tcl
mcset it {Delete function} {Cancella funzione}

### File: ../src/dialogs/functions_dialog.tcl
mcset it {Are you sure you want to delete function '%s'?} {Sei sicuro di voler cancellare la funzione '%s'?}

### File: ../src/mainwindow.tcl
mcset it {Connect to selected database} {Connetti al database selezionato}

### File: ../src/mainwindow.tcl
mcset it {Disconnect from selected database} {Disconnetti database selezionato}

### File: ../src/mainwindow.tcl
mcset it {Remove selected database from list} {Rimuovi il database selezionato dalla lista}

### File: ../src/mainwindow.tcl
mcset it {New table} {Nuova tabella}

### File: ../src/mainwindow.tcl
mcset it {Drop table} {Cancella (Drop) tabella}

### File: ../src/mainwindow.tcl
mcset it {Drop index} {Cancella (Drop) indice}

### File: ../src/mainwindow.tcl
mcset it {Drop trigger} {Cancella (Drop) trigger}

### File: ../src/mainwindow.tcl
mcset it {Edit view} {Modifica vista}

### File: ../src/mainwindow.tcl
mcset it {Drop view} {Cancella (Drop) vista}

### File: ../src/mainwindow.tcl
mcset it {Arrange cascade windows layout} {Organizza le finestre a cascata}

### File: ../src/mainwindow.tcl
mcset it {Arrange intelligent windows layout} {Organizzazione intelligente delle finestre}

### File: ../src/mainwindow.tcl
mcset it {Refresh databases tree (%s)} {Aggiorna albero del database (%s)}

### File: ../src/mainwindow.tcl
mcset it {Open SQL query editor} {Apri editor query SQL}

### File: ../src/mainwindow.tcl
mcset it {Settings (%s)} {Settings (%s)}

### File: ../src/mainwindow.tcl
mcset it {Open SQL functions editor} {Apri editor funzioni SQL}

### File: ../src/mainwindow.tcl
mcset it {Clear objects filter} {Clear objects filter}

### File: ../src/mainwindow.tcl
mcset it {Enter object name you want to look for} {Enter object name you want to look for}

### File: ../src/mainwindow.tcl
mcset it Databases Databases

### File: ../src/mainwindow.tcl
mcset it Tools Strumenti

### File: ../src/mainwindow.tcl
mcset it Connect Connetti

### File: ../src/mainwindow.tcl
mcset it Disconnect Disconnetti

### File: ../src/mainwindow.tcl
mcset it {Remove from list} {Rimuovi dalla lista}

### File: ../src/mainwindow.tcl
mcset it {View main toolbar} {Visualizza barra degli strumenti principale}

### File: ../src/mainwindow.tcl
mcset it {View structure toolbar} {Visualizza barra degli strumenti struttura}

### File: ../src/mainwindow.tcl
mcset it {View windows toolbar} {Visualizza barra degli strumenti finestra}

### File: ../src/mainwindow.tcl
mcset it {View tools toolbar} {Visualizza barra degli strumenti}

### File: ../src/mainwindow.tcl
mcset it {View configuration toolbar} {Visualizza barra degli strumenti di configurazione}

### File: ../src/mainwindow.tcl
mcset it {Refresh databases tree} {Aggiorna albero del database}

### File: ../src/mainwindow.tcl
mcset it {Custom SQL functions} {Funzioni SQL personalizzate}

### File: ../src/mainwindow.tcl
mcset it {Export database} {Esporta database}

### File: ../src/mainwindow.tcl
mcset it {Export table or view} {Export table or view}

### File: ../src/mainwindow.tcl
mcset it {Import data to a table} {Import data to a table}

### File: ../src/mainwindow.tcl
mcset it {SQLiteStudio home page} {SQLiteStudio home page}

### File: ../src/mainwindow.tcl
mcset it {SQLiteStudio manual} {Manuale SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset it {SQLite documentation} {Documentazione SQLite}

### File: ../src/mainwindow.tcl
mcset it {SQLiteStudio support forum} {SQLiteStudio forum di supporto}

### File: ../src/mainwindow.tcl
mcset it {Report a bug} {Riporta un problema}

### File: ../src/mainwindow.tcl
mcset it {Send feature request} {Invia la richiesta per una nuova funzione}

### File: ../src/mainwindow.tcl
mcset it {Show bug reports history} {Mostra cronologia di invio dei rapporti dei bug}

### File: ../src/mainwindow.tcl
mcset it {Show tips window} {Mostra finestra suggerimenti}

### File: ../src/mainwindow.tcl
mcset it ChangeLog ChangeLog

### File: ../src/mainwindow.tcl
mcset it Roadmap Roadmap

### File: ../src/mainwindow.tcl
mcset it {Check for new version} {Verifica nuova versione}

### File: ../src/mainwindow.tcl
mcset it Donate Donate

### File: ../src/mainwindow.tcl
mcset it {Did you know that...} {Lo sapevi che...}

### File: ../src/mainwindow.tcl
mcset it {Editor %s} {Editor %s}

### File: ../src/mainwindow.tcl
mcset it Settings Impostazioni

### File: ../src/mainwindow.tcl
mcset it {SQLiteStudio roadmap} {SQLiteStudio roadmap}

### File: ../src/mainwindow.tcl
mcset it {Can't start web browser, because:
%s} {Impossibile avviare il browser, perchè:
%s}

### File: ../src/mainwindow.tcl
mcset it {Can't start %s web browser, because:
%s} {Impossibile avviare il browser %s, perchè:
%s}

### File: ../src/mainwindow.tcl
mcset it {About SQLiteStudio} {A proposito di SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset it {SQLiteStudio ChangeLog} {SQLiteStudio ChangeLog}

### File: ../src/mainwindow.tcl
mcset it {There is no new version available.} {Nessuna nuova versione disponibile.}

### File: ../src/mainwindow.tcl
mcset it {New version} {Nuova versione}

### File: ../src/mainwindow.tcl
mcset it {Report bug} {Rapporta bug}

### File: ../src/mainwindow.tcl
mcset it {Feature request} {Richiedi funzione}

### File: ../src/mainwindow.tcl
mcset it {Reports history} {Cronologia rapporti}

### File: ../src/mainwindow.tcl
mcset it {Reporting bug} {Rapporto bug}

### File: ../src/mainwindow.tcl
mcset it {Reporting bug to SQLiteStudio bugs database...} {Invio rapport bug al database di SQLiteStudio...}

### File: ../src/mainwindow.tcl
mcset it {Problem occurred while reporting bug. You can ignore it and get back to your work.} {Problem occurred while reporting bug. You can ignore it and get back to your work.}

### File: ../src/mainwindow.tcl
mcset it Ignore Ignora

### File: ../src/mainwindow.tcl
mcset it {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history} {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history}

### File: ../src/mainwindow.tcl
mcset it {A timeout occured while downloading new version. Try again, or download it manually.} {A timeout occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset it {An error occured while downloading new version. Try again, or download it manually.} {An error occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset it Downloading... {Scaricamento in corso...}

### File: ../src/mainwindow.tcl
mcset it {Downloading SQLiteStudio v%s...} {Scaricamento SQLiteStudio v%s...}

### File: ../src/mainwindow.tcl
mcset it {Problem with saving new SQLiteStudio version to:
%s
Details:
%s} {Problem with saving new SQLiteStudio version to:
%s
Details:
%s}

### File: ../src/mainwindow.tcl
mcset it {Problem with getting new SQLiteStudio version
Details:
%s} {Problem with getting new SQLiteStudio version
Details:
%s}

### File: ../src/mainwindow.tcl
mcset it {This is unknown binary distribution. Cannot determinate binary file to download for update.} {This is unknown binary distribution. Cannot determinate binary file to download for update.}

### File: ../src/data_editor.tcl
mcset it {There are uncommited rows.
Are you sure you want to close '%s' window anywy?} {Ci sono righe non salvate.
Sicuro di voler chiudere la finestra '%s' in ogni caso?}

### File: ../src/common/ddl_dialog.tcl
mcset it {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s} {Impossibile preparare il DDL. Configurazione di dialogo incompleta.
Dettagli problema:
%s}

### File: ../src/common/color_picker.tcl
mcset it {Choose color} {Seleziona colore}

### File: ../src/common/shortcut_edit.tcl
mcset it {Forbidden shortcut key combination: %s} {Combinazione di tasti proibita: %s}

### File: ../src/common/common.tcl
mcset it Copy Copia

### File: ../src/common/common.tcl
mcset it Cut Taglia

### File: ../src/common/common.tcl
mcset it Paste Incolla

### File: ../src/common/blob_edit_panel.tcl
mcset it {Text edit} {Editor di testo}

### File: ../src/common/blob_edit_panel.tcl
mcset it {Hexadecimal edit} {Editor esadecimale}

### File: ../src/common/common_sql.tcl
mcset it {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
} {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
}

### File: ../src/common/hex_editor.tcl
mcset it {Overwrite characters,
instead of inserting} {Overwrite characters,
instead of inserting}

### File: ../src/common/hex_editor.tcl
mcset it Processing Eleborazione

### File: ../src/common/hex_editor.tcl
mcset it {Processing data...} {Elaborazione dati...}

### File: ../src/sql_editor.tcl
mcset it {Replace dialog} {Finestra di Sostituzione}

### File: ../src/sql_editor.tcl
mcset it {Search dialog} {Finestra di Ricerca}

### File: ../src/trees/db_tree.tcl
mcset it Loading Loading

### File: ../src/trees/db_tree.tcl
mcset it {Loading database list} {Loading database list}

### File: ../src/trees/db_tree.tcl
mcset it {Given database file doesn't exist or is unreadable.} {Il file del database non esiste o non è leggibile.}

### File: ../src/trees/db_tree.tcl
mcset it Vacuum {Ottimizza (Vacuum)}

### File: ../src/trees/db_tree.tcl
mcset it {Integrity check} {Verificà integrità}

### File: ../src/trees/db_tree.tcl
mcset it {Import schema from other database} {Importa schema da un altro database}

### File: ../src/trees/db_tree.tcl
mcset it {Reset autoincrement for '%s'} {Reset autoincrement for '%s'}

### File: ../src/trees/db_tree.tcl
mcset it {Erase table data} {Erase table data}

### File: ../src/trees/db_tree.tcl
mcset it {Create foreign key} {Crea Chiave esterna}

### File: ../src/trees/db_tree.tcl
mcset it {Show view data} {Mostra dati della vista}

### File: ../src/trees/db_tree.tcl
mcset it {Export view} {Export view}

### File: ../src/trees/db_tree.tcl
mcset it {Sort databases alphabetically} {Ordina database alfabeticamente}

### File: ../src/trees/db_tree.tcl
mcset it {Given database is already on the list.} {Il database è già in lista.}

### File: ../src/trees/db_tree.tcl
mcset it {Given database name is already on the list.} {Il nome del database è già in lista.}

### File: ../src/trees/db_tree.tcl
mcset it Tables Tabelle

### File: ../src/trees/db_tree.tcl
mcset it Views Viste

### File: ../src/trees/db_tree.tcl
mcset it {SQLite system table} {Tabella di sistema SQLite}

### File: ../src/trees/db_tree.tcl
mcset it Columns Colonne

### File: ../src/trees/db_tree.tcl
mcset it {SQLite system index} {Indice SQLite di sistema}

### File: ../src/trees/db_tree.tcl
mcset it {Remove database} {Rimuovi database}

### File: ../src/trees/db_tree.tcl
mcset it {Are you sure you want to remove '%s' database from the list?} {Sei sicuro di voler rimuovere il database '%s' dalla lista?}

### File: ../src/trees/db_tree.tcl
mcset it {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.} {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.}

### File: ../src/trees/db_tree.tcl
mcset it {'%s' is a virtual table, therefore cannot be browsed in table window.} {'%s' è una tabella virtuale, quindi non può essere sfogliata nella finestra delle tabelle.}

### File: ../src/trees/db_tree.tcl
mcset it {Table '%s' has no DDL. Probably it's system table and should not be edited.} {Table '%s' has no DDL. Probably it's system table and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset it {'%s' is a virtual table, therefore cannot be edited in table dialog.} {'%s' è una tabella virtuale e non può essere modificata.}

### File: ../src/trees/db_tree.tcl
mcset it {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.} {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.}

### File: ../src/trees/db_tree.tcl
mcset it {Integrity check (%s)} {Verificà integrità (%s)}

### File: ../src/trees/db_tree.tcl
mcset it {Are you sure you want to DROP '%s' table?} {Sei sicuro di voler cancellare (DROP) '%s' tabelle?}

### File: ../src/trees/db_tree.tcl
mcset it {Dropping table} {Dropping table}

### File: ../src/trees/db_tree.tcl
mcset it {Dropping table '%s'} {Dropping table '%s'}

### File: ../src/trees/db_tree.tcl
mcset it {Dropping index} {Dropping index}

### File: ../src/trees/db_tree.tcl
mcset it {Dropping index '%s'} {Dropping index '%s'}

### File: ../src/trees/db_tree.tcl
mcset it {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?} {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset it {Fix trigger} {Fix trigger}

### File: ../src/trees/db_tree.tcl
mcset it {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.} {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset it {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?} {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset it {Fix view} {Fix view}

### File: ../src/trees/db_tree.tcl
mcset it {View '%s' has no DDL. Probably it's system view and should not be edited.} {View '%s' has no DDL. Probably it's system view and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset it {Delete view} {Cancella vista}

### File: ../src/trees/db_tree.tcl
mcset it {Are you sure you want to delete '%s' view?} {Sei sicuro di voler cancellare la vista '%s'?}

### File: ../src/trees/db_tree.tcl
mcset it {Erase data} {Erase data}

### File: ../src/trees/db_tree.tcl
mcset it {Are you sure you want to delete all data from table '%s'?} {Are you sure you want to delete all data from table '%s'?}

### File: ../src/trees/db_tree.tcl
mcset it {Deleting data} {Deleting data}

### File: ../src/trees/db_tree.tcl
mcset it {Deleting data from table '%s'} {Deleting data from table '%s'}

### File: ../src/trees/db_tree.tcl
mcset it {'%s' view data} {'%s' dati della vista}

### File: ../src/trees/db_tree.tcl
mcset it {Are you sure you want to make a vacuum?} {Sei sicuro di voler eseguire un ottimizzazione (Vacuum)?}

### File: ../src/trees/db_tree.tcl
mcset it Vacuuming Vacuuming

### File: ../src/trees/db_tree.tcl
mcset it {Vacuuming '%s'} {Vacuuming '%s'}

### File: ../src/trees/db_tree.tcl
mcset it {SQL files} {File SQL}

### File: ../src/trees/db_tree.tcl
mcset it {Select SQL file to be executed} {Select SQL file to be executed}

### File: ../src/trees/db_tree.tcl
mcset it {Error while executing SQL:
%s} {Error while executing SQL:
%s}

### File: ../src/trees/db_tree.tcl
mcset it {SQL executed sucessfly.} {SQL eseguito con successo.}

### File: ../src/trees/db_tree.tcl
mcset it {Import database schema} {Importa schema del database}

### File: ../src/trees/db_tree.tcl
mcset it {Database: %s} {Database: %s}

### File: ../src/trees/db_tree.tcl
mcset it URI: URI:

### File: ../src/trees/db_tree.tcl
mcset it Version: Version:

### File: ../src/trees/db_tree.tcl
mcset it {File size:} {File size:}

### File: ../src/trees/db_tree.tcl
mcset it {Schema version:} {Schema version:}

### File: ../src/trees/db_tree.tcl
mcset it {Virtual table} {Virtual table}

### File: ../src/trees/db_tree.tcl
mcset it Indexes: Indexes:

### File: ../src/trees/db_tree.tcl
mcset it Triggers: Triggers:

### File: ../src/trees/db_tree.tcl
mcset it {Column: %s} {Colonna: %s}

### File: ../src/trees/db_tree.tcl
mcset it {Not null} {Not null}

### File: ../src/trees/db_tree.tcl
mcset it {Indexed table:} {Indexed table:}

### File: ../src/trees/db_tree.tcl
mcset it {Copy index '%s' for table '%s'} {Copy index '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset it {Move index '%s' to table '%s'} {Move index '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset it {Copy trigger '%s' for table '%s'} {Copy trigger '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset it {Move trigger '%s' to table '%s'} {Move trigger '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset it {Copy view '%s' for database '%s'} {Copy view '%s' for database '%s'}

### File: ../src/trees/db_tree.tcl
mcset it {Move view '%s' to database '%s'} {Move view '%s' to database '%s'}

### File: ../src/trees/db_tree.tcl
mcset it {View '%s' has no DDL, therefore cannot be edited.} {View '%s' has no DDL, therefore cannot be edited.}

### File: ../src/trees/db_tree.tcl
mcset it {Copy view} {Copy view}

### File: ../src/trees/db_tree.tcl
mcset it {Move view} {Move view}

### File: ../src/trees/db_tree.tcl
mcset it Move Move

### File: ../src/trees/db_tree.tcl
mcset it {Copy index} {Copy index}

### File: ../src/trees/db_tree.tcl
mcset it {Move index} {Move index}

### File: ../src/trees/db_tree.tcl
mcset it {Copy trigger} {Copy trigger}

### File: ../src/trees/db_tree.tcl
mcset it {Move trigger} {Move trigger}

### File: ../src/trees/db_tree.tcl
mcset it {Copy table '%s' to database '%s' (include data, indexes and triggers)} {Copy table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset it {Copy table '%s' to database '%s' (include data)} {Copy table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset it {Copy table '%s' to database '%s' (include indexes and triggers)} {Copy table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset it {Copy table '%s' to database '%s' (skip data, indexes and triggers)} {Copy table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset it {Move table '%s' to database '%s' (include data, indexes and triggers)} {Move table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset it {Move table '%s' to database '%s' (include data)} {Move table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset it {Move table '%s' to database '%s' (include indexes and triggers)} {Move table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset it {Move table '%s' to database '%s' (skip data, indexes and triggers)} {Move table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset it {Copying table...} {Copying table...}

### File: ../src/trees/db_tree.tcl
mcset it {Copying table '%s' from '%s' to '%s'.} {Copying table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset it {Moving table...} {Moving table...}

### File: ../src/trees/db_tree.tcl
mcset it {Moving table '%s' from '%s' to '%s'.} {Moving table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset it {Could not create object in target database:
%s} {Could not create object in target database:
%s}

### File: ../src/trees/db_tree.tcl
mcset it {Could not copy data:
%s} {Could not copy data:
%s}

### File: ../src/trees/db_tree.tcl
mcset it {Could not copy table data from source database to target database. Details: %s} {Could not copy table data from source database to target database. Details: %s}

### File: ../src/trees/db_tree.tcl
mcset it {Could not delete object(s) from source database. Details: %s} {Could not delete object(s) from source database. Details: %s}

### File: ../src/grids/dbgrid.tcl
mcset it {Edit BLOB entry:} {Modifica contenuto campo BLOB:}

### File: ../src/grids/dbgrid.tcl
mcset it {BLOB edit} {Modifica campo BLOB}

### File: ../src/grids/dbgrid.tcl
mcset it {Cannot commit. Details:
%s} {Cannot commit. Details:
%s}

### File: ../src/grids/grid.tcl
mcset it {You have to select a cell before paste any contents.} {Devi selezionare una cella prima di incollare un qualsiasi contenuto.}

### File: ../src/grids/grid.tcl
mcset it {Cut data} Taglia

### File: ../src/grids/grid.tcl
mcset it {There are too many columns or rows to paste. Do you want to cut them and paste?} {Ci sono troppe colonne o righe da incollare. Vuoi tagliarle o incollarle?}

### File: ../src/grids/data_grid.tcl
mcset it {Insert new row} {Inserisci nuova riga}

### File: ../src/grids/data_grid.tcl
mcset it {Delete selected rows} {Cancella riga selezionata}

### File: ../src/grids/data_grid.tcl
mcset it {Edit cell value} {Modifica valore cella}

### File: ../src/grids/data_grid.tcl
mcset it {Edit cell value in BLOB editor} {Edit cell value in BLOB editor}

### File: ../src/grids/data_grid.tcl
mcset it {Duplicate row} {Duplica riga}

### File: ../src/grids/data_grid.tcl
mcset it {Set NULL value} {Imposta il valore a NULL}

### File: ../src/grids/data_grid.tcl
mcset it {Generate SELECT from selected cells} {Generate SELECT from selected cells}

### File: ../src/grids/data_grid.tcl
mcset it {Commit selected cells} {Salva celle selezionate}

### File: ../src/grids/data_grid.tcl
mcset it {Rollback selected cells} {Rollback celle selezionate}

### File: ../src/grids/data_grid.tcl
mcset it {Select all} {Select all}

### File: ../src/grids/data_grid.tcl
mcset it {Show ordinals} {Mostra ordinate}

### File: ../src/grids/data_grid.tcl
mcset it {Show ROWIDs} {Mostra ROWIDs}

### File: ../src/grids/data_grid.tcl
mcset it Type: Type:

### File: ../src/grids/data_grid.tcl
mcset it Constraints: Restrizioni:

### File: ../src/grids/data_grid.tcl
mcset it {%s column has NOT NULL constraint. You have to fill value for it.} {La colonna %s ha la restrizione NOT NULL. Devi inserire un valore in essa.}

### File: ../src/grids/data_grid.tcl
mcset it {Error while adding new row:
%s} {Errore nell'aggiunta di una nuova riga:
%s}

### File: ../src/grids/data_grid.tcl
mcset it {Error while updating new row:
%s} {Error while updating new row:
%s}

### File: ../src/grids/data_grid.tcl
mcset it {Error while updating cell value:
%s

What would you like to do?} {Errore durante l'aggiornamento del valore della cella:
%s

Cosa vorresti fare??}

### File: ../src/grids/data_grid.tcl
mcset it {Re-edit value} {Ri-Modifica valore}

### File: ../src/grids/data_grid.tcl
mcset it {Return to value before edition} {Ritorna al valore prima della modifica}

### File: ../src/grids/data_grid.tcl
mcset it {Cannot delete row(s), because it violates constraint. Details:
%s} {Cannot delete row(s), because it violates constraint. Details:
%s}

### File: ../src/grids/data_grid.tcl
mcset it {Error while deleting selected rows:
%s} {Errore nell'eliminazione delle righe selezionate:
%s}

### File: ../src/grids/data_grid.tcl
mcset it {SQL query generated at %s
using selected cells from window '%s'.} {SQL query generated at %s
using selected cells from window '%s'.}

### File: ../src/grids/result_grid.tcl
mcset it {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.} {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.}

### File: ../src/grids/result_grid.tcl
mcset it {Data type:} {Data type:}

### File: ../src/grids/result_grid.tcl
mcset it {No details are available on this cell.} {Nessun dettaglio disponibile per questa cella.}

### File: ../src/grids/result_grid.tcl
mcset it {Duplicated ROWID} {ROWID duplicato}

### File: ../src/grids/result_grid.tcl
mcset it {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?} {C'è più di una riga con ROWID=%s coinvolte nell'operazione di incolla.
Potrebbero verificarsi risultati non voluti. Procedi?}

### File: ../src/grids/result_grid.tcl
mcset it {Could not parse SQL while trying to generate requested query: %s} {Could not parse SQL while trying to generate requested query: %s}

### File: ../src/grids/result_grid.tcl
mcset it {Cannot use '%s' statement to generate requested query.} {Cannot use '%s' statement to generate requested query.}

### File: ../src/grids/result_grid.tcl
mcset it {Cannot determinate selected column with ID=%s.} {Cannot determinate selected column with ID=%s.}

### File: ../src/grids/result_grid.tcl
mcset it {Error occurred while trying to generate the query: %s} {Error occurred while trying to generate the query: %s}

### File: ../src/grids/result_grid.tcl
mcset it {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s} {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s}
