# SQLiteStudio 'ja_jp' localization file

# Unchanged translations

### File: ../src/win_assoc.tcl
mcset ja_jp {File associations} {File associations}

### File: ../src/win_assoc.tcl
mcset ja_jp {Following file extensions could not be associated to the current SQLiteStudio version:
%s} {Following file extensions could not be associated to the current SQLiteStudio version:
%s}

### File: ../src/win_assoc.tcl
mcset ja_jp {Click the link below to find out what is possible reason and solutions.} {Click the link below to find out what is possible reason and solutions.}

### File: ../src/cfg_win.tcl
mcset ja_jp Ok OK

### File: ../src/cfg_win.tcl
mcset ja_jp Apply 適用

### File: ../src/cfg_win.tcl
mcset ja_jp Cancel キャンセル

### File: ../src/cfg_win.tcl
mcset ja_jp Theme テーマ

### File: ../src/cfg_win.tcl
mcset ja_jp {Select theme to use:} 使用するテーマを選択してください:

### File: ../src/cfg_win.tcl
mcset ja_jp {Theme version:} テーマのバージョン:

### File: ../src/cfg_win.tcl
mcset ja_jp Shortcuts ショートカット

### File: ../src/cfg_win.tcl
mcset ja_jp {Global shortcuts} 共通ショートカット

### File: ../src/cfg_win.tcl
mcset ja_jp {Open SQL editor} SQLクエリエディタを開く

### File: ../src/cfg_win.tcl
mcset ja_jp {Opens SQL editor window.} SQLクエリエディタのウィンドウを開きます

### File: ../src/cfg_win.tcl
mcset ja_jp {Close selected task} 選択されたタスクを閉じる

### File: ../src/cfg_win.tcl
mcset ja_jp {Closes active MDI window.} 選択されているMDIウィンドウを閉じます

### File: ../src/cfg_win.tcl
mcset ja_jp {Restore last closed task} {Restore last closed task}

### File: ../src/cfg_win.tcl
mcset ja_jp {Restores last closed MDI window.} {Restores last closed MDI window.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Open settings} 設定ウィンドウ

### File: ../src/cfg_win.tcl
mcset ja_jp {Opens SQLiteStudio settings window.} SQLiteStudioの設定ウィンドウを開きます

### File: ../src/cfg_win.tcl
mcset ja_jp {Next task} 次のタスク

### File: ../src/cfg_win.tcl
mcset ja_jp {Switches task (window) to next, placed on the right from active task on taskbar.} 次のタスク（ウィンドウ）に切り替えます。タスク一覧の右のタスクがアクティブになります。

### File: ../src/cfg_win.tcl
mcset ja_jp {Next task (alternative)} 次のタスク（代替）

### File: ../src/cfg_win.tcl
mcset ja_jp {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {次のタスク（ウィンドウ）に切り替えます。タスク一覧の右のタスクがアクティブになります。
これは代替ショートカットです。一つ手前と同じ動作をします。}

### File: ../src/cfg_win.tcl
mcset ja_jp {Previous task} 前のタスク

### File: ../src/cfg_win.tcl
mcset ja_jp {Switches task (window) to previous, placed on the left from active task on taskbar.} 前のタスク（ウィンドウ）に切り替えます。タスク一覧の左のタスクがアクティブになります。

### File: ../src/cfg_win.tcl
mcset ja_jp {Previous task (alternative)} 前のタスク（代替）

### File: ../src/cfg_win.tcl
mcset ja_jp {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {前のタスク（ウィンドウ）に切り替えます。タスク一覧の左のタスクがアクティブになります。
これは代替ショートカットです。一つ手前と同じ動作をします。}

### File: ../src/cfg_win.tcl
mcset ja_jp {Editor and table window shortcuts} エディタとテーブルのショートカット

### File: ../src/cfg_win.tcl
mcset ja_jp {SQL editor completion} SQLコード補完

### File: ../src/cfg_win.tcl
mcset ja_jp {Invokes SQL completion in editor window.} {Invokes SQL completion in editor window.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Execute SQL query} SQLクエリ実行

### File: ../src/cfg_win.tcl
mcset ja_jp {Executes SQL query typed in editor.} {Executes SQL query typed in editor.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Explain SQL query} {Explain SQLクエリ}

### File: ../src/cfg_win.tcl
mcset ja_jp {Calls EXPLAIN on SQL query typed in editor.} {Calls EXPLAIN on SQL query typed in editor.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Format SQL code} SQLコードのフォーマット

### File: ../src/cfg_win.tcl
mcset ja_jp {Formats SQL code typed in editor.} {Formats SQL code typed in editor.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Load SQL from file} SQLファイルを読み込む

### File: ../src/cfg_win.tcl
mcset ja_jp {Loads SQL from file to the editor.} {Loads SQL from file to the editor.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Save SQL to file} SQLをファイルに保存

### File: ../src/cfg_win.tcl
mcset ja_jp {Saves contents of the editor into a file.} {Saves contents of the editor into a file.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Execute SQL from file} {Execute SQL from file}

### File: ../src/cfg_win.tcl
mcset ja_jp {Executes SQL directly from file, without loading it to the editor.} {Executes SQL directly from file, without loading it to the editor.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Next tab} 次のタブ

### File: ../src/cfg_win.tcl
mcset ja_jp {Switches to next tab of editor window (result or history).} エディタウィンドウを次のタブに切り替えます（実行結果または実行履歴）

### File: ../src/cfg_win.tcl
mcset ja_jp {Previous tab} 前のタブ

### File: ../src/cfg_win.tcl
mcset ja_jp {Switches to previous tab of editor window (query or result).} エディタウィンドウを前のタブに切り替えます（実行結果または実行履歴）

### File: ../src/cfg_win.tcl
mcset ja_jp {Next subtab} 次のサブタブ

### File: ../src/cfg_win.tcl
mcset ja_jp {Switches to next subtab (form view in results tab).} 次のサブタブに切り替えます（実行結果のフォーム表示）

### File: ../src/cfg_win.tcl
mcset ja_jp {Previous subtab} 前のサブタブ

### File: ../src/cfg_win.tcl
mcset ja_jp {Switches to previous subtab (grid view in results tab).} 前のサブタブに切り替えます（実行結果のフォーム表示）

### File: ../src/cfg_win.tcl
mcset ja_jp Refresh 更新

### File: ../src/cfg_win.tcl
mcset ja_jp {Re-executes SQL query so results data is refreshed.} {Re-executes SQL query so results data is refreshed.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Delete selected row} ラインの削除

### File: ../src/cfg_win.tcl
mcset ja_jp {Deletes selected row.} 選択されたラインを削除します

### File: ../src/cfg_win.tcl
mcset ja_jp {Add new row} ラインの追加

### File: ../src/cfg_win.tcl
mcset ja_jp {Adds new empty row without commiting it.} 空のライン（未確定）を追加します。

### File: ../src/cfg_win.tcl
mcset ja_jp {Erase cells data} {Erase cells data}

### File: ../src/cfg_win.tcl
mcset ja_jp {Erases data of selected cells.} {Erases data of selected cells.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Next editor database in list} {Next editor database in list}

### File: ../src/cfg_win.tcl
mcset ja_jp {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)} {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)}

### File: ../src/cfg_win.tcl
mcset ja_jp {Previous editor database in list} {Previous editor database in list}

### File: ../src/cfg_win.tcl
mcset ja_jp {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)} {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)}

### File: ../src/cfg_win.tcl
mcset ja_jp {Commit edition in Form View} 変更を確定（フォーム表示）

### File: ../src/cfg_win.tcl
mcset ja_jp {Commits edition in Form View of query results or table data preview.} フォーム表示において、クエリ実行結果またはテープルデータの変更を確定します。

### File: ../src/cfg_win.tcl
mcset ja_jp {Rollback edition in Form View} 変更を元に戻す（フォーム表示）

### File: ../src/cfg_win.tcl
mcset ja_jp {Rolls back edition in Form View of query results or table data preview.} フォーム表示において、クエリ実行結果またはテープルデータの確定されていない変更を元に戻します。

### File: ../src/cfg_win.tcl
mcset ja_jp {Jump to first row in Form View} 先頭のラインに移動（フォーム表示）

### File: ../src/cfg_win.tcl
mcset ja_jp {Jumps to first row of query results grid
or table data preview grid in Form View.} {フォーム表示において、
クエリ実行結果またはテープルデータの先頭のラインに移動します。}

### File: ../src/cfg_win.tcl
mcset ja_jp {Go to previous row in Form View} 前のラインに移動（フォーム表示）

### File: ../src/cfg_win.tcl
mcset ja_jp {Goes to previous row of query results grid
or table data preview grid row in Form View.} {フォーム表示において、
クエリ実行結果またはテープルデータの前のラインに移動します。}

### File: ../src/cfg_win.tcl
mcset ja_jp {Go to next row in Form View} 次のラインに移動（フォーム表示）

### File: ../src/cfg_win.tcl
mcset ja_jp {Goes to next row of query results grid
or table data preview grid row in Form View.} {フォーム表示において、
クエリ実行結果またはテープルデータの次のラインに移動します。}

### File: ../src/cfg_win.tcl
mcset ja_jp {Jump to last row in Form View} 最後のラインに移動（フォーム表示）

### File: ../src/cfg_win.tcl
mcset ja_jp {Jumps to last row of query results grid
or table data preview grid in Form View.} {フォーム表示において、
クエリ実行結果またはテープルデータの最後のラインに移動します。}

### File: ../src/cfg_win.tcl
mcset ja_jp {Switch NULL value in form edit field} {Switch NULL value in form edit field}

### File: ../src/cfg_win.tcl
mcset ja_jp {Sets or unsets NULL value in currently selected
column in form view data edit mode.} {Sets or unsets NULL value in currently selected
column in form view data edit mode.}

### File: ../src/cfg_win.tcl
mcset ja_jp Plugins プラグイン

### File: ../src/cfg_win.tcl
mcset ja_jp {SQL formatter plugins} SQLフォーマットプラグイン

### File: ../src/cfg_win.tcl
mcset ja_jp {Use following SQL formatter plugin:} 使用するSQLフォーマットプラグイン:

### File: ../src/cfg_win.tcl
mcset ja_jp {Configure formatter plugin} プラグインの設定

### File: ../src/cfg_win.tcl
mcset ja_jp Configure 設定

### File: ../src/cfg_win.tcl
mcset ja_jp {Populating plugins} テストデータプラグイン

### File: ../src/cfg_win.tcl
mcset ja_jp {Default table populating plugin:} 選択状態にするテストデータ追加のプラグイン:

### File: ../src/cfg_win.tcl
mcset ja_jp Miscellaneous その他

### File: ../src/cfg_win.tcl
mcset ja_jp {Restore session after next start} 前回のセッションを再現する。

### File: ../src/cfg_win.tcl
mcset ja_jp {All windows and their contents (such as SQL code)
will be restored while next application startup.} {すべてのウィンドウといくつかのコンテンツ（SQLエディタなど）を
起動時に再現します。}

### File: ../src/cfg_win.tcl
mcset ja_jp {Show line numbers in SQL editor} SQLエディタに行番号を表示する。

### File: ../src/cfg_win.tcl
mcset ja_jp {All SQL editor windows will contain line numbers on the left side of window.} すべてのSQLエディタの左サイドに行番号を表示します

### File: ../src/cfg_win.tcl
mcset ja_jp {Underline syntax errors in SQL editor} SQLエディタでの構文エラーに下線を表示

### File: ../src/cfg_win.tcl
mcset ja_jp {Makes errors to be marked with underline.
You can also define foreground and background color for errors.} {エラーが発生した箇所に下線を引きます。
エラー部分の文字色を設定することが可能です。}

### File: ../src/cfg_win.tcl
mcset ja_jp {Show SQLite system tables and indexes in databases tree} データベースツリーにSQLシステムテーブルとSQLシステムインデックスを表示する

### File: ../src/cfg_win.tcl
mcset ja_jp {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.} {SQLiteのシステムテーブル(テーブル名 'sqlite_*')
とシステムインデックス(インデックス名'(*autoindex*)')がデータベースツリーに表示されるようになります}

### File: ../src/cfg_win.tcl
mcset ja_jp {Open items with single mouse click in databases tree} ツリーアイテムをシングルクリックで開く

### File: ../src/cfg_win.tcl
mcset ja_jp {Items in database tree are open by double click by default.
This option switches it to single click.} {データベースツリーのアイテムは通常ダブルクリックで開くようになっていますが、
このオプションを設定するとシングルクリックで開くようになります。}

### File: ../src/cfg_win.tcl
mcset ja_jp {Show ROWID as default instead of row order number in table data view} {Show ROWID as default instead of row order number in table data view}

### File: ../src/cfg_win.tcl
mcset ja_jp {This option affects first column from the left on the data tab of the table window.} {This option affects first column from the left on the data tab of the table window.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Do not show 'did you know that...' dialog at startup.} 起動時にTIPSを表示しない。

### File: ../src/cfg_win.tcl
mcset ja_jp {Uncheck this option to show the dialog.} チェックを外すとTIPSが再び表示されます。

### File: ../src/cfg_win.tcl
mcset ja_jp {Check for updates at startup.} 起動時にバージョン更新チェックをする。

### File: ../src/cfg_win.tcl
mcset ja_jp {If enabled, application will will check
for new version available at startup.} {この項目をチェックするとアプリケーションの
起動時に新しいバージョンがないかを確認します。}

### File: ../src/cfg_win.tcl
mcset ja_jp {Sort custom SQL functions list by name} ユーザー定義関数リストを名前順でソートする

### File: ../src/cfg_win.tcl
mcset ja_jp {This list is placed in Custom SQL funcions dialog.} {This list is placed in Custom SQL funcions dialog.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Select all contents when editing the table cell} {Select all contents when editing the table cell}

### File: ../src/cfg_win.tcl
mcset ja_jp {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.} {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Ask if clipboard contents should be cut} {たずねる if clipboard contents should be cut}

### File: ../src/cfg_win.tcl
mcset ja_jp {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.} {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Rows per page in Table Window and Editor Results:} {Rows per page in Table Window and Editor Results:}

### File: ../src/cfg_win.tcl
mcset ja_jp {More results per page causes slower loading of single data page. Value 1000 should be right.} {More results per page causes slower loading of single data page. Value 1000 should be right.}

### File: ../src/cfg_win.tcl
mcset ja_jp {History entries limit:} {History entries limit:}

### File: ../src/cfg_win.tcl
mcset ja_jp {Number of rows to remember in SQL editor history.} {Number of rows to remember in SQL editor history.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Insertion cursor blinking period (milliseconds):} {Insertion cursor blinking period (milliseconds):}

### File: ../src/cfg_win.tcl
mcset ja_jp {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.} {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Web browser:} WEBブラウザ:

### File: ../src/cfg_win.tcl
mcset ja_jp {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.} {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.}

### File: ../src/cfg_win.tcl
mcset ja_jp Language: 言語:

### File: ../src/cfg_win.tcl
mcset ja_jp {Tab in table window on open:} テーブル選択時に表示するタブ:

### File: ../src/cfg_win.tcl
mcset ja_jp {Table structure} テーブル構成

### File: ../src/cfg_win.tcl
mcset ja_jp {Table data} テーブルデータ

### File: ../src/cfg_win.tcl
mcset ja_jp {Select which tab should be opened for start in table window,
when you just opened that window.} テーブルが表示されたときにどちらを前にするか選べます。

### File: ../src/cfg_win.tcl
mcset ja_jp {View default display mode:} {View default display mode:}

### File: ../src/cfg_win.tcl
mcset ja_jp {Edition dialog} {Edition dialog}

### File: ../src/cfg_win.tcl
mcset ja_jp {Data view} {Data view}

### File: ../src/cfg_win.tcl
mcset ja_jp {Defines what is displayed by default when user opens a view.} {Defines what is displayed by default when user opens a view.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Editor window results layout} 実行結果の表示方法

### File: ../src/cfg_win.tcl
mcset ja_jp {Show results in separated tab} 新しいタブで表示

### File: ../src/cfg_win.tcl
mcset ja_jp {Show results in frame below query} エディタの下に表示

### File: ../src/cfg_win.tcl
mcset ja_jp {Database tree display mode} {Database tree display mode}

### File: ../src/cfg_win.tcl
mcset ja_jp {Show indexes and triggers linked under referenced table.} {Show indexes and triggers linked under referenced table.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Show indexes and triggers in their own groups.} {Show indexes and triggers in their own groups.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Show column names linked under the table.} {Show column names linked under the table.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Plain text results} プレーンテキストの結果:

### File: ../src/cfg_win.tcl
mcset ja_jp {Display NULL values as:} NULL値の表示:

### File: ../src/cfg_win.tcl
mcset ja_jp {Maximum column width:} {Maximum column width:}

### File: ../src/cfg_win.tcl
mcset ja_jp {Values longer than specified here will be cut in plain text results.} {Values longer than specified here will be cut in plain text results.}

### File: ../src/cfg_win.tcl
mcset ja_jp Colors 色

### File: ../src/cfg_win.tcl
mcset ja_jp {Global colors} 共通色

### File: ../src/cfg_win.tcl
mcset ja_jp {MDI windows title bar background color} MDIウィンドウのタイトルバー背景色

### File: ../src/cfg_win.tcl
mcset ja_jp {MDI windows title bar foreground color} MDIウィンドウのタイトルバー文字色

### File: ../src/cfg_win.tcl
mcset ja_jp {MDI windows title bar button background color} MDIウィンドウのタイトルバーのボタン背景色

### File: ../src/cfg_win.tcl
mcset ja_jp {MDI windows title bar active button background color} アクティブなMDIウィンドウのタイトルバーのボタン背景色

### File: ../src/cfg_win.tcl
mcset ja_jp {SQL Editor} SQLエディタ

### File: ../src/cfg_win.tcl
mcset ja_jp {Editor standard font color} 文字色

### File: ../src/cfg_win.tcl
mcset ja_jp {Editor background} エディタ背景色

### File: ../src/cfg_win.tcl
mcset ja_jp {Selected foreground color} 選択範囲前景色

### File: ../src/cfg_win.tcl
mcset ja_jp {Selected background color} 選択範囲背景色

### File: ../src/cfg_win.tcl
mcset ja_jp {Disabled background color} {Disabled background color}

### File: ../src/cfg_win.tcl
mcset ja_jp {Tables color} テーブル色

### File: ../src/cfg_win.tcl
mcset ja_jp {Brackets color} 括弧色

### File: ../src/cfg_win.tcl
mcset ja_jp {Square brackets color} {Square brackets color}

### File: ../src/cfg_win.tcl
mcset ja_jp {Keywords color} キーワード色

### File: ../src/cfg_win.tcl
mcset ja_jp {Variables color} 変数色

### File: ../src/cfg_win.tcl
mcset ja_jp {Strings color} ストリング色

### File: ../src/cfg_win.tcl
mcset ja_jp {Comments color} コメント色

### File: ../src/cfg_win.tcl
mcset ja_jp {Matched brackets foreground color} {Matched brackets foreground color}

### File: ../src/cfg_win.tcl
mcset ja_jp {Matched brackets background color} {Matched brackets background color}

### File: ../src/cfg_win.tcl
mcset ja_jp {Syntax error color} 構文エラー色

### File: ../src/cfg_win.tcl
mcset ja_jp {Tcl editor} Tclエディタ

### File: ../src/cfg_win.tcl
mcset ja_jp {Options color} {Options color}

### File: ../src/cfg_win.tcl
mcset ja_jp {Quoted character color} 引用色

### File: ../src/cfg_win.tcl
mcset ja_jp {Trees colors} ツリービュー

### File: ../src/cfg_win.tcl
mcset ja_jp {Tree background} ツリービュー背景色

### File: ../src/cfg_win.tcl
mcset ja_jp {Tree standard font color} ツリービュー文字色

### File: ../src/cfg_win.tcl
mcset ja_jp {Tree selected background color} 選択された背景色

### File: ../src/cfg_win.tcl
mcset ja_jp {Tree selected foreground color} 選択された文字色

### File: ../src/cfg_win.tcl
mcset ja_jp {Color for number of objects in tree branch} ツリー要素数色

### File: ../src/cfg_win.tcl
mcset ja_jp {Grids colors} グリッド色

### File: ../src/cfg_win.tcl
mcset ja_jp {Grid background} グリッド背景

### File: ../src/cfg_win.tcl
mcset ja_jp {Grid standard font color} グリッド文字色

### File: ../src/cfg_win.tcl
mcset ja_jp {Grid selected background color} 選択グリッド背景色

### File: ../src/cfg_win.tcl
mcset ja_jp {Grid selected foreground color} 選択グリッド文字色

### File: ../src/cfg_win.tcl
mcset ja_jp {Grid base column background color} グリッド番号カラム背景色

### File: ../src/cfg_win.tcl
mcset ja_jp {Foreground color for cells with NULL value} NULL文字色

### File: ../src/cfg_win.tcl
mcset ja_jp {Status fields colors} ステータスフィールド色

### File: ../src/cfg_win.tcl
mcset ja_jp {Background color} 背景色

### File: ../src/cfg_win.tcl
mcset ja_jp {Foreground color} 前景色

### File: ../src/cfg_win.tcl
mcset ja_jp {Error foreground color} エラー文字色

### File: ../src/cfg_win.tcl
mcset ja_jp {Information foreground color} 情報文字色

### File: ../src/cfg_win.tcl
mcset ja_jp {Information (second kind) foreground color} 情報（サブ）文字色

### File: ../src/cfg_win.tcl
mcset ja_jp {Miscellaneous colors} その他色

### File: ../src/cfg_win.tcl
mcset ja_jp {Context hints background color} ツールチップ背景色

### File: ../src/cfg_win.tcl
mcset ja_jp {Context hints foreground color} ツールチップ文字色

### File: ../src/cfg_win.tcl
mcset ja_jp Fonts フォント

### File: ../src/cfg_win.tcl
mcset ja_jp {SQL editor font} SQLエディタフォント

### File: ../src/cfg_win.tcl
mcset ja_jp {Status fields font} ステータスフィールドのフォント

### File: ../src/cfg_win.tcl
mcset ja_jp {Grid font} グリッドフォント

### File: ../src/cfg_win.tcl
mcset ja_jp {Tree font} ツリーフォント

### File: ../src/cfg_win.tcl
mcset ja_jp {Tree additional labels font} ツリーの要素数のフォント

### File: ../src/cfg_win.tcl
mcset ja_jp {Context hints font} ツールチップフォント

### File: ../src/cfg_win.tcl
mcset ja_jp {Changed language needs application to be restarted.} 言語の変更にはアプリケーションを再起動する必要があります。

### File: ../src/cfg_win.tcl
mcset ja_jp {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.} {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.}

### File: ../src/cfg_win.tcl
mcset ja_jp {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.} {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.}

### File: ../src/cfg_win.tcl
mcset ja_jp {SQL formatter options} SQLフォーマットの設定

### File: ../src/db/db_file_types.tcl
mcset ja_jp {All SQLite Databases} すべてのSQLiteデータベース

### File: ../src/db/db_file_types.tcl
mcset ja_jp {SQLite 3 Databases} {SQLite 3 データベース}

### File: ../src/db/db_file_types.tcl
mcset ja_jp {SQLite 2 Databases} {SQLite 2 データベース}

### File: ../src/db/db_file_types.tcl
mcset ja_jp {All files} すべてのファイル

### File: ../src/db/query_executor.tcl
mcset ja_jp {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.} {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.}

### File: ../src/db/query_executor.tcl
mcset ja_jp {Invalid database name: %s} {Invalid database name: %s}

### File: ../src/db/query_executor.tcl
mcset ja_jp {Imbalanced 'BEGIN' ocurrence in query.} {Imbalanced 'BEGIN' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset ja_jp {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.} {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset ja_jp {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.} {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset ja_jp {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.} {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset ja_jp {Cannot use more than one 'BEGIN'.} {Cannot use more than one 'BEGIN'.}

### File: ../src/db/query_executor.tcl
mcset ja_jp {Imbalanced 'COMMIT' ocurrence in query.} {Imbalanced 'COMMIT' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset ja_jp {Imbalanced 'ROLLBACK' ocurrence in query.} {Imbalanced 'ROLLBACK' ocurrence in query.}

### File: ../src/db/sqlite2.tcl
mcset ja_jp {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)} {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)}

### File: ../src/db/db.tcl
mcset ja_jp {An internal logic error in SQLite} {An internal logic error in SQLite}

### File: ../src/db/db.tcl
mcset ja_jp {Access permission denied} {Access permission denied}

### File: ../src/db/db.tcl
mcset ja_jp {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.} {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.}

### File: ../src/db/db.tcl
mcset ja_jp {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.} {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.}

### File: ../src/db/db.tcl
mcset ja_jp {A malloc() failed} {A malloc() failed}

### File: ../src/db/db.tcl
mcset ja_jp {Attempt to write a readonly database} {Attempt to write a readonly database}

### File: ../src/db/db.tcl
mcset ja_jp {Disk I/O error occurred} {Disk I/O error occurred}

### File: ../src/db/db.tcl
mcset ja_jp {The database disk image is malformed} {The database disk image is malformed}

### File: ../src/db/db.tcl
mcset ja_jp {Database is full} {Database is full}

### File: ../src/db/db.tcl
mcset ja_jp {Unable to open the database file} {Unable to open the database file}

### File: ../src/db/db.tcl
mcset ja_jp {Database lock protocol error} {Database lock protocol error}

### File: ../src/db/db.tcl
mcset ja_jp {Database is empty} {Database is empty}

### File: ../src/db/db.tcl
mcset ja_jp {The database schema changed} {The database schema changed}

### File: ../src/db/db.tcl
mcset ja_jp {String or BLOB exceeds size limit} {String or BLOB exceeds size limit}

### File: ../src/db/db.tcl
mcset ja_jp {Library used incorrectly} {Library used incorrectly}

### File: ../src/db/db.tcl
mcset ja_jp {Uses OS features not supported on host} {Uses OS features not supported on host}

### File: ../src/db/db.tcl
mcset ja_jp {Authorization denied} {Authorization denied}

### File: ../src/db/db.tcl
mcset ja_jp {Auxiliary database format error} {Auxiliary database format error}

### File: ../src/db/db.tcl
mcset ja_jp {2nd parameter to sqlite3_bind out of range} {2nd parameter to sqlite3_bind out of range}

### File: ../src/db/db.tcl
mcset ja_jp {File opened that is not a database file} {File opened that is not a database file}

### File: ../src/db/db.tcl
mcset ja_jp {Error while opening %s database:
%s} {エラー：データベース”%s ”のオープンに失敗しました。:
%s}

### File: ../src/db/db.tcl
mcset ja_jp {Not enough parameters passed to function '%s'.} {Not enough parameters passed to function '%s'.}

### File: ../src/db/db.tcl
mcset ja_jp {Cannot read file: %s} {ファイルを読み込めません。: %s}

### File: ../src/db/db.tcl
mcset ja_jp {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.} {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.}

### File: ../src/db/db.tcl
mcset ja_jp {Could not attach database %s. Error message from SQLite:
%s} {Could not attach database %s. Error message from SQLite:
%s}

### File: ../src/db/db.tcl
mcset ja_jp {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.} {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.}

### File: ../src/db/sqlite3.tcl
mcset ja_jp {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)} {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)}

### File: ../src/completion_routines.tcl
mcset ja_jp {Problem with attaching database:
%s} {Problem with attaching database:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Error from importing plugin:
%s} {Error from importing plugin:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Error creating table '%s':
%s

Importing aborted.} {Error creating table '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Error trying to import data to '%s':
%s

Importing aborted.} {Error trying to import data to '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp Importing... Importing...

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Importing to table '%s'.} {Importing to table '%s'.}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?} {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?} {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Problem occured while importing row number %s:
%s

What would you like to do?} {Problem occured while importing row number %s:
%s

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Importing finished.} {Importing finished.}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Import problem} {Import problem}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Skip this data row} {Skip this data row}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Keep data rows imported so far (%s) and abort} {Keep data rows imported so far (%s) and abort}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Rollback data rows imported so far and abort} {Rollback data rows imported so far and abort}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp {Ignore it and proceed} {Ignore it and proceed}

### File: ../src/plugins/import_plugin.tcl
mcset ja_jp Abort 中止

### File: ../src/plugins/sql_formatting/enterprise/format_s.tcl
mcset ja_jp name 名前

### File: ../src/plugins/sql_formatting/basic.tcl
mcset ja_jp {Reduce group of whitespaces into one whitespace.} {Reduce group of whitespaces into one whitespace.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset ja_jp {Uppercase keywords.} コマンドを大文字にする

### File: ../src/plugins/sql_formatting/basic.tcl
mcset ja_jp {Separate ")" and after contents with single whitespace.} {Separate ")" and after contents with single whitespace.}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {SQLite3 only} SQLite3のみ

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp Indentation 字下げ

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {New lines} 新しい行にする

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {White spaces} 半角スペースの挿入

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp Names 名前

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp Comments コメント

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Tab size:} タブサイズ:

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Line up keywords in multi-line queries} {Line up keywords in multi-line queries}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Ident contents of parenthesis block} {Ident contents of parenthesis block}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Ident parenthesis block in new line} {Ident parenthesis block in new line}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Before opening parenthesis in column definitions} {( [括弧開き] の前 （カラム定義）}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After opening parenthesis in column definitions} {( [括弧開き] の後ろ（カラム定義）}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Before closinging parenthesis in column definitions} {) [閉じ括弧] の前 （カラム定義）}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After closinging parenthesis in column definitions} {) [閉じ括弧] の後ろ（カラム定義）}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Before opening parenthesis in expressions} {( [括弧開き] の前 （式）}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After opening parenthesis in expressions} {( [括弧開き] の後ろ （式）}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Before closinging parenthesis in expressions} {) [閉じ括弧] の前 （式）}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After closinging parenthesis in expressions} {) [閉じ括弧] の後ろ （式）}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After comma} コンマの後

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After comma in function arguments list} {After comma in function arguments list}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After logical block of query} {After logical block of query}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After semicolon} セミコロンの後

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Never before semicolon} {Never before セミコロン}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Before comma in lists} コンマの前

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After comma in lists} コンマの後ろ

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Before opening parenthesis} { ( の前}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After opening parenthesis} { ( の後ろ}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Before closing parenthesis} { ) [閉じ括弧] の前}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After closing parenthesis} { ) [閉じ括弧] の後ろ}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Before dot operator (in path to database object)} {区切り？ドットの前 (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After dot operator (in path to database object)} {区切り？ドットの後ろ (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Before mathematical operator} {演算子[=<>]の前}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {After mathematical operator} {演算子[=<>]の後ろ}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Uppercase keywords} コマンドを大文字にする

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Uppercase datatype names} データタイプを大文字にする

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Always use name wrapping} 常に名前をラップする

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Preferred name wrapper} ラップ方法

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Expand one line comments (/* ... */) to multiline} {一行コメント (/* ... */) も複数行表示にする}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Indent multi line comments} 複数行コメントを字下げする。

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ja_jp {Use "*" character for each line} { "*" を使うはコメントの最初と最後だけにする}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {, (comma)} {, (カンマ)}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {; (semicolon)} {; (セミコロン)}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {\t (tab)} {\t (タブ)}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {  (white-space)} {  (半角スペース)}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp Custom カスタム

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Input file} {Input file}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp Browse ファイルの選択

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Show options} {Show options}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Column names} {Column names}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Treat first row as column names} {Treat first row as column names}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.} {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Columns separator:} 区切り文字:

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.} {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {NULL handling} {NULL handling}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Treat following values as NULL:} {Treat following values as NULL:}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp Workarounds Workarounds

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Expect Microsoft format of CSV} {Expect Microsoft format of CSV}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.} {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp Encoding Encoding

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Convert from encoding:} {Convert from encoding:}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Input file cannot be empty.} {Input file cannot be empty.}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Input file is not readable.} {Input file is not readable.}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {CSV separator cannot be empty.} CSVの区切り文字が入力されていません

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {CSV files} {CSV files}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {Text files} {Text files}

### File: ../src/plugins/import/csv.tcl
mcset ja_jp {File to import from} {File to import from}

### File: ../src/plugins/import/dbf.tcl
mcset ja_jp Auto-detect Auto-detect

### File: ../src/plugins/import/dbf.tcl
mcset ja_jp {dBase files} {dBase files}

### File: ../src/plugins/import/regexp.tcl
mcset ja_jp {Regular expression} {Regular expression}

### File: ../src/plugins/import/regexp.tcl
mcset ja_jp {Visual editor} {Visual editor}

### File: ../src/plugins/import/regexp.tcl
mcset ja_jp {Use Regular Expression Groups to identify columns.} {Use Regular Expression Groups to identify columns.}

### File: ../src/plugins/import/regexp.tcl
mcset ja_jp {Case insensitive} {Case insensitive}

### File: ../src/plugins/import/regexp.tcl
mcset ja_jp Help ヘルプ

### File: ../src/plugins/import/regexp.tcl
mcset ja_jp {RegExp error:
%s} {RegExp error:
%s}

### File: ../src/plugins/export/xls.tcl
mcset ja_jp {Column names as first row} カラム名を一行目にする

### File: ../src/plugins/export/xls.tcl
mcset ja_jp {If enabled, then first row of exported document will be a list of column names.} {If enabled, then first row of exported document will be a list of column names.}

### File: ../src/plugins/export/xls.tcl
mcset ja_jp Encoding: Encoding:

### File: ../src/plugins/export/plain.tcl
mcset ja_jp {Export NULL values as:} NULL文字のエクスポート:

### File: ../src/plugins/export/plain.tcl
mcset ja_jp {Fixed column width:} {Fixed column width:}

### File: ../src/plugins/export/plain.tcl
mcset ja_jp {Database: %s (%s, %s)} {Database: %s (%s, %s)}

### File: ../src/plugins/export/plain.tcl
mcset ja_jp {Table: %s} {テーブル: %s}

### File: ../src/plugins/export/plain.tcl
mcset ja_jp {Index: %s} {インデックス: %s}

### File: ../src/plugins/export/plain.tcl
mcset ja_jp {Trigger: %s} {トリガー: %s}

### File: ../src/plugins/export/plain.tcl
mcset ja_jp {View: %s} {ビュー: %s}

### File: ../src/plugins/export/csv.tcl
mcset ja_jp {If enabled, then first row of exported CSV will be a list of column names.} {If enabled, then first row of exported CSV will be a list of column names.}

### File: ../src/plugins/export/csv.tcl
mcset ja_jp {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.} {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.}

### File: ../src/plugins/export/json.tcl
mcset ja_jp {Indented lines} {Indented lines}

### File: ../src/plugins/export/json.tcl
mcset ja_jp {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.} {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.}

### File: ../src/plugins/export/json.tcl
mcset ja_jp {Align lines} {Align lines}

### File: ../src/plugins/export/json.tcl
mcset ja_jp {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.} {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.}

### File: ../src/plugins/export/json.tcl
mcset ja_jp {Each row as object} {Each row as object}

### File: ../src/plugins/export/json.tcl
mcset ja_jp {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.} {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.}

### File: ../src/plugins/export/xml.tcl
mcset ja_jp {No extra white-spaces or new lines} {No extra white-spaces or new lines}

### File: ../src/plugins/export/xml.tcl
mcset ja_jp {XML tags will be places char-by-char, without any extra white-spaces.} {XML tags will be places char-by-char, without any extra white-spaces.}

### File: ../src/plugins/export/xml.tcl
mcset ja_jp {Format output to be human readable} {Format output to be human readable}

### File: ../src/plugins/export/xml.tcl
mcset ja_jp {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.} {Each tag will be placed in new line and whole document
will be justified to be more readable in テキストエディタ.}

### File: ../src/plugins/export/xml.tcl
mcset ja_jp {Generate XSD file} XSDファイル（スキーマ）の生成

### File: ../src/plugins/export/xml.tcl
mcset ja_jp {Generates XML Schema Definition file using
export file name and extension *.xsd.} {Generates XMLスキーマ Definition file using
export file name and extension *.xsd.}

### File: ../src/plugins/export/xml.tcl
mcset ja_jp {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s} {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s}

### File: ../src/plugins/export/html.tcl
mcset ja_jp {First row of exported data will be header
with names of columns, just like in results grid.} {カラム名を表の１ライン目にします。
実行結果のグリッドのようになります。}

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Row numbers as first column} ライン番号を一カラム目に挿入

### File: ../src/plugins/export/html.tcl
mcset ja_jp {First column of exported data
will contain row order number.} {First column of exported data
will contain row order number.}

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Full column names} カラム名をフル表示

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Column names in header will be prepended with "table_name." prefix.} {Column names in header will be prepended with "table_name." prefix.}

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Show types} データタイプを表示

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Column headers will contain data types.} ヘッダカラムにデータタイプを追加します

### File: ../src/plugins/export/html.tcl
mcset ja_jp {no type} タイプ未指定

### File: ../src/plugins/export/html.tcl
mcset ja_jp {For table:} {For table:}

### File: ../src/plugins/export/html.tcl
mcset ja_jp Unique: ユニーク:

### File: ../src/plugins/export/html.tcl
mcset ja_jp Yes はい

### File: ../src/plugins/export/html.tcl
mcset ja_jp No いいえ

### File: ../src/plugins/export/html.tcl
mcset ja_jp Column カラム

### File: ../src/plugins/export/html.tcl
mcset ja_jp Collating 定義

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Sort order} {Sort order}

### File: ../src/plugins/export/html.tcl
mcset ja_jp Activated: Activated:

### File: ../src/plugins/export/html.tcl
mcset ja_jp Action: Action:

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Activate condition:} {Activate condition:}

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Code executed:} {Code executed:}

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Exported database: %s} {データベースのエクスポート: %s}

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Generated on %s with %s} {Generated on %s with %s}

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Exported table: %s} {テーブルのエクスポート: %s}

### File: ../src/plugins/export/html.tcl
mcset ja_jp {Results of SQL query} SQLクエリの実行結果

### File: ../src/plugins/export/dbf.tcl
mcset ja_jp {Cannot overwrite file '%s'.} {Cannot overwrite file '%s'.}

### File: ../src/plugins/export/sql.tcl
mcset ja_jp {Name of table for exported data:} {Name of テーブル for exported data:}

### File: ../src/plugins/export/sql.tcl
mcset ja_jp {Include "CREATE TABLE" statement at the begining.} {Include "CREATE テーブル" statement at the begining.}

### File: ../src/plugins/export/sql.tcl
mcset ja_jp {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.} {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this テーブル.}

### File: ../src/plugins/export/sql.tcl
mcset ja_jp {Include table declaration} テーブル宣言を含める

### File: ../src/plugins/export/sql.tcl
mcset ja_jp {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.} {If enabled, then table DDL (テーブルの作成)
will be included in exported SQL.}

### File: ../src/plugins/export/sql.tcl
mcset ja_jp {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.} {You need to configure table name to export query results to SQL.
SQL INSERTs require テーブル in their syntax.}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp Dimensions Dimensions

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Paper size:} {Paper size:}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Margin size:} {Margin size:}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Cell padding:} {Cell padding:}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Limit amount of data bytes in single cell to:} {Limit amount of data bytes in single cell to:}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Font size:} {Font size:}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Built-in font} {Built-in font}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp Font: Font:

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {TrueType font} {TrueType font}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Font file:} {Font file:}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Font encoding:} {Font encoding:}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Columns and rows} {Columns and rows}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Header background} {Header background}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Empty space} {Empty space}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Fill empty space in cells} {Fill empty space in cells}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.} {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Minimum height of empty space to fill:} {Minimum height of empty space to fill:}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.} {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Empty space background} {Empty space background}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {TTF Fonts} {TTF Fonts}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {All Files} {All Files}

### File: ../src/plugins/export/pdf.tcl
mcset ja_jp {Open TTF font} {Open TTF font}

### File: ../src/plugins/populating/random.tcl
mcset ja_jp {Include alpha characters} 英字を含む

### File: ../src/plugins/populating/random.tcl
mcset ja_jp {Include numeric characters} 数字を含む

### File: ../src/plugins/populating/random.tcl
mcset ja_jp {Include whitespace characters} 半角スペースを含む

### File: ../src/plugins/populating/random.tcl
mcset ja_jp {Include binary characters} バイナリ文字を含む

### File: ../src/plugins/populating/random.tcl
mcset ja_jp {Minimum length:} 最小文字数:

### File: ../src/plugins/populating/random.tcl
mcset ja_jp {Maximum length:} 最大文字数:

### File: ../src/plugins/populating/random_number.tcl
mcset ja_jp {Minimum value:} 最小値:

### File: ../src/plugins/populating/random_number.tcl
mcset ja_jp {Maximum value:} 最大値:

### File: ../src/plugins/populating/random_number.tcl
mcset ja_jp {Constant prefix:} 先頭につける文字列:

### File: ../src/plugins/populating/random_number.tcl
mcset ja_jp {Constant suffix:} 末尾につける文字列:

### File: ../src/plugins/populating/sql.tcl
mcset ja_jp {Initialisation code} {Initialisation code}

### File: ../src/plugins/populating/sql.tcl
mcset ja_jp {Per iteration code} {Per iteration code}

### File: ../src/plugins/populating/sql.tcl
mcset ja_jp {Closing code} {Closing code}

### File: ../src/plugins/populating/constant.tcl
mcset ja_jp {Value to use:} 値:

### File: ../src/plugins/populating/sequence.tcl
mcset ja_jp {Start from:} 開始番号:

### File: ../src/plugins/populating/dictionary.tcl
mcset ja_jp {Dictionary file:} 辞書ファイル:

### File: ../src/plugins/populating/dictionary.tcl
mcset ja_jp {Dictionary words separator:} 辞書ファイルの区切り:

### File: ../src/plugins/populating/dictionary.tcl
mcset ja_jp Whitespace 半角スペース

### File: ../src/plugins/populating/dictionary.tcl
mcset ja_jp {Line break} 改行

### File: ../src/plugins/populating/dictionary.tcl
mcset ja_jp {Method of using words:} 文字列の使用メソッド:

### File: ../src/plugins/populating/dictionary.tcl
mcset ja_jp Randomly ランダム

### File: ../src/plugins/populating/dictionary.tcl
mcset ja_jp Consecutively 上から順に均等配置

### File: ../src/plugins/populating/dictionary.tcl
mcset ja_jp {Dictionary file doesn't exist, or unreadable.} 辞書ファイルが存在しないか読み取れません

### File: ../src/plugins/populating/dictionary.tcl
mcset ja_jp {Dictionary file is empty!} 辞書ファイルが空です。

### File: ../src/plugins/populating/dictionary.tcl
mcset ja_jp {Dictionary file} 辞書ファイル

### File: ../src/taskbar.tcl
mcset ja_jp Database: データベース:

### File: ../src/taskbar.tcl
mcset ja_jp Table: テーブル:

### File: ../src/taskbar.tcl
mcset ja_jp {Type new name for a window} 新しいウィンドウ名を入力してください

### File: ../src/taskbar.tcl
mcset ja_jp {Window with given name already exists. Please type other name.} {Window with given name already exists. Please type other name.}

### File: ../src/taskbar.tcl
mcset ja_jp {Type new name for a task} {Type new name for a task}

### File: ../src/taskbar.tcl
mcset ja_jp {Close selected window} 選択されたウィンドウを閉じる

### File: ../src/taskbar.tcl
mcset ja_jp {Close other windows} 他のウィンドウを閉じる

### File: ../src/taskbar.tcl
mcset ja_jp {Close all windows} すべてのウィンドウを閉じる

### File: ../src/taskbar.tcl
mcset ja_jp {Restore last closed window} {Restore last closed window}

### File: ../src/taskbar.tcl
mcset ja_jp {Rename selected window} 選択されたウィンドウの名前を変更

### File: ../src/windows/table_win.tcl
mcset ja_jp Structure 構造

### File: ../src/windows/table_win.tcl
mcset ja_jp Data データ

### File: ../src/windows/table_win.tcl
mcset ja_jp Constraints 制限

### File: ../src/windows/table_win.tcl
mcset ja_jp Indexes インデックス

### File: ../src/windows/table_win.tcl
mcset ja_jp Triggers トリガー

### File: ../src/windows/table_win.tcl
mcset ja_jp {Grid view} グリッド表示

### File: ../src/windows/table_win.tcl
mcset ja_jp {Form view} フォーム

### File: ../src/windows/table_win.tcl
mcset ja_jp {Refresh table columns and DDL (%s)} {テーブルカラムとDDLの更新 (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Edit table (%s)} テーブルの編集(%s)

### File: ../src/windows/table_win.tcl
mcset ja_jp {Export table data (%s)} テーブルデータのエクスポート(%s)

### File: ../src/windows/table_win.tcl
mcset ja_jp {Import data to table (%s)} {Import data to table (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Populate table (%s)} {Populate table (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Create similar table} 同じ構造のテーブルの作成

### File: ../src/windows/table_win.tcl
mcset ja_jp {Refresh table data (%s)} {テーブルデータの更新 (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Add custom number of rows} {Add custom number of rows}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Add new row (%s)} {新規ラインの挿入 (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Delete selected row (%s)} {ラインの削除 (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Commit changes (%s)} {Commit changes (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Rollback new row (%s)} {変更を元に戻す (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {First %s rows} {First %s rows}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Previous %s rows} {前の %s ライン}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Next %s rows} {次の %s ライン}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Last %s rows} {Last %s rows}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Export table data} テーブルデータのエクスポート

### File: ../src/windows/table_win.tcl
mcset ja_jp {Import data to table} {Import data to table}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Populate table} テストデータの追加

### File: ../src/windows/table_win.tcl
mcset ja_jp {Enter phrase you want to look for} 探したいフレーズを入力してください

### File: ../src/windows/table_win.tcl
mcset ja_jp {Apply data filter} 単語抽出

### File: ../src/windows/table_win.tcl
mcset ja_jp {Clear data filter} リセット

### File: ../src/windows/table_win.tcl
mcset ja_jp {Total rows: %s} {総ライン数: %s}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Rollback changes (%s)} 変更を元に戻す

### File: ../src/windows/table_win.tcl
mcset ja_jp {First row from data grid (%s)} {最初のライン (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Previous row from data grid (%s)} {前のライン (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Next row from data grid (%s)} {次のライン (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Last row from data grid (%s)} {最後のライン (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Field switching mode.

Click it to make <Tab> key to insert tab characters.} {フィールドタブモード

タブキーでフォームを移動できます。}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.} {タブ挿入モード

タブを直接入力できます。}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Refresh table indexes (%s)} {テーブルインデックスの更新 (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Create new index (%s)} {新規インデックス (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Edit index (%s)} {インデックスの編集 (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Delete index (%s)} {インデックスの削除 (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Refresh table triggers (%s)} {テーブルトリガーの更新 (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Create new trigger (%s)} {新規トリガー (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Edit trigger (%s)} {トリガーの編集 (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Delete trigger (%s)} {トリガーの削除 (%s)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Constraint name} 制限名

### File: ../src/windows/table_win.tcl
mcset ja_jp {Column name} カラム名

### File: ../src/windows/table_win.tcl
mcset ja_jp Default デフォルト

### File: ../src/windows/table_win.tcl
mcset ja_jp {Not NULL} NULL禁止

### File: ../src/windows/table_win.tcl
mcset ja_jp {Primary key} 主キー

### File: ../src/windows/table_win.tcl
mcset ja_jp Unique ユニークキー

### File: ../src/windows/table_win.tcl
mcset ja_jp Collate 定義

### File: ../src/windows/table_win.tcl
mcset ja_jp Check 選択

### File: ../src/windows/table_win.tcl
mcset ja_jp {Foreign key} 外部キー

### File: ../src/windows/table_win.tcl
mcset ja_jp {Index name} インデックス名

### File: ../src/windows/table_win.tcl
mcset ja_jp {On column} 対象カラム

### File: ../src/windows/table_win.tcl
mcset ja_jp {SQL code} SQLコード

### File: ../src/windows/table_win.tcl
mcset ja_jp {Trigger name} トリガー名

### File: ../src/windows/table_win.tcl
mcset ja_jp {On table} {On table}

### File: ../src/windows/table_win.tcl
mcset ja_jp Name 名前

### File: ../src/windows/table_win.tcl
mcset ja_jp {Data type} データタイプ

### File: ../src/windows/table_win.tcl
mcset ja_jp {Default value} デフォルト値

### File: ../src/windows/table_win.tcl
mcset ja_jp {Refreshing dependencies} 更新

### File: ../src/windows/table_win.tcl
mcset ja_jp {Refreshing table columns...} テーブルカラムを更新中です。

### File: ../src/windows/table_win.tcl
mcset ja_jp {Refreshing table data...} テーブルデータの更新中です。

### File: ../src/windows/table_win.tcl
mcset ja_jp {Refreshing table indexes...} テーブルインデックスの更新中です。

### File: ../src/windows/table_win.tcl
mcset ja_jp {Refreshing table triggers...} テーブルトリガーの更新中です。

### File: ../src/windows/table_win.tcl
mcset ja_jp {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.} {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Check condition} {Check condition}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Total rows: %s (filtered)} {全ライン数: %s (フィルタ)}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Pending commits} 未確定

### File: ../src/windows/table_win.tcl
mcset ja_jp {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?} {確定されていないデータがあります。
データは元に戻ってしまいます。続けますか？}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Loading data...} 読み込み：データの読み込み中です。

### File: ../src/windows/table_win.tcl
mcset ja_jp {Loading table '%s'...} {読み込み：テーブル '%s' を読み込んでいます。}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.} {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.} {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Edit table} テーブルの編集

### File: ../src/windows/table_win.tcl
mcset ja_jp {Enter number of rows to add:} {Enter number of rows to add:}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Add rows} {Add rows}

### File: ../src/windows/table_win.tcl
mcset ja_jp {New index} 新規インデックス

### File: ../src/windows/table_win.tcl
mcset ja_jp {Index '%s' has no DDL. Probably it's system index and should not be edited.} {Index '%s' has no DDL. Probably it's system index and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Edit index} インデックスの編集

### File: ../src/windows/table_win.tcl
mcset ja_jp {Delete index} インデックスの削除

### File: ../src/windows/table_win.tcl
mcset ja_jp {Are you sure you want to delete '%s' index?} {インデックス '%s' を削除してもよろしいですか？}

### File: ../src/windows/table_win.tcl
mcset ja_jp {New trigger} 新規トリガー

### File: ../src/windows/table_win.tcl
mcset ja_jp {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.} {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Edit trigger} トリガーの編集

### File: ../src/windows/table_win.tcl
mcset ja_jp {Delete trigger} トリガーの削除

### File: ../src/windows/table_win.tcl
mcset ja_jp {Are you sure you want to delete '%s' trigger?} {トリガー '%s' を削除してもよろしいですか？}

### File: ../src/windows/table_win.tcl
mcset ja_jp {Export table} テーブルのエクスポート

### File: ../src/windows/table_win.tcl
mcset ja_jp {Import data} {Import data}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {SQL query} SQLクエリ

### File: ../src/windows/editor_win.tcl
mcset ja_jp Results 実行結果

### File: ../src/windows/editor_win.tcl
mcset ja_jp History 実行履歴

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Execute query (%s)} {クエリ実行 (%s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Execute query with plain string results} {Execute query with plain string results}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Explain query (%s)} クエリの実行計画(%s)

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Format SQL code (%s)} {SQLコードのフォーマット (%s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Refresh syntax highlighting (%s)} {Refresh syntax highlighting (%s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Clear history} 履歴のクリア

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Export results} 実行結果のエクスポート

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Create view from query} クエリからビューを作成

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Execute SQL from file (%s)} {Execute SQL from file (%s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Load SQL from file (%s)} {SQLをファイルから読み込む (%s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Save SQL to file (%s)} SQLをファイルに保存(%s)

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Default database for SQL executing
(%s/%s)} デフォルトでSQLを実行するデータベース(%s/%s)

### File: ../src/windows/editor_win.tcl
mcset ja_jp Database データベース

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Execution date} 実行日

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Execution time (s)} {実行時間 (s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Rows affected} {Rows affected}

### File: ../src/windows/editor_win.tcl
mcset ja_jp SQL SQL

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Plain text view} プレーンテキストビュー

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Refresh results (%s)} 実行結果の更新(%s)

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Commit row (%s)} {Commit row (%s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Rollback row (%s)} {Rollback row (%s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Copy (%s)} {Copy (%s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Cut (%s)} {Cut (%s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Paste (%s)} {Paste (%s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Show line numbers} 行番号を表示

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Delete selected history entry (%s)} {Delete selected history entry (%s)}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Choose the database first.} {Choose the database first.}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Error while trying to collect completion list: %s} {Error while trying to collect completion list: %s}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Can't open %s file for reading.} {%s を開けませんでした。ファイルの読み込みに失敗しました。}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Can't open %s file for writting.} {%s を開けませんでした。ファイルの書き込みに失敗しました。}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {SQL code saved in %s.} {SQLコードをファイルに保存しました: %s}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Are you sure you want to clear queries history?} クエリの実行履歴を削除してよろしいですか？

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Delete the history entry} {Delete the history entry}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Are you sure you want to delete selected queries history entry?} {Are you sure you want to delete selected queries history entry?}

### File: ../src/windows/editor_win.tcl
mcset ja_jp Processing... Processing...

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Processing query...} {Processing query...}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {No results to export.} 実行結果が存在しません。

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.} {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Query execution...} クエリを実行してます。

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Executing SQL query...} SQLクエリを実行してます。

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Error while executing query: %s} {エラー クエリ実行に失敗しました: %s}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s} {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {%s row(s) read in %s second(s).} {%s row(s) read in %s second(s).}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {%s row(s) affected in %s second(s).} {%s row(s) affected in %s second(s).}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {No SELECT statements found in editor or in selected part of SQL code.} {No SELECT statements found in editor or in selected part of SQL code.}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {More than one SELECT statements found. Please select the one you're interested in and then try again.} {More than one SELECT statements found. Please select the one you're interested in and then try again.}

### File: ../src/windows/editor_win.tcl
mcset ja_jp {New view} 新規ビュー

### File: ../src/windows/editor_win.tcl
mcset ja_jp {Fill query parameters} {Fill query parameters}

### File: ../src/error.tcl
mcset ja_jp {Background error} {Background error}

### File: ../src/error.tcl
mcset ja_jp Close 閉じる

### File: ../src/error.tcl
mcset ja_jp {Report the bug} バグレポート

### File: ../src/dialogs/about_dialog.tcl
mcset ja_jp About ソフトについて

### File: ../src/dialogs/about_dialog.tcl
mcset ja_jp {Packages and plugins} パッケージとプラグイン

### File: ../src/dialogs/about_dialog.tcl
mcset ja_jp Licence ライセンス

### File: ../src/dialogs/about_dialog.tcl
mcset ja_jp {Installed plugins:} インストールされているプラグイン:

### File: ../src/dialogs/about_dialog.tcl
mcset ja_jp {Used Tcl packages:} 使用中のTclパッケージ:

### File: ../src/dialogs/about_dialog.tcl
mcset ja_jp {SQLite3 engine version: %s} {SQLite3エンジンのバージョン: %s}

### File: ../src/dialogs/searchdialog.tcl
mcset ja_jp {Global expression understeands '*', '?' and \[chars].} {Global expression understeands '*', '?' and \[chars].}

### File: ../src/dialogs/searchdialog.tcl
mcset ja_jp Find 検索

### File: ../src/dialogs/searchdialog.tcl
mcset ja_jp Replace 置換

### File: ../src/dialogs/searchdialog.tcl
mcset ja_jp {Do you want to replace marked text?} 置き換えますか？

### File: ../src/dialogs/searchdialog.tcl
mcset ja_jp {Replace all} すべて置換

### File: ../src/dialogs/searchdialog.tcl
mcset ja_jp {Replacing finished.} {Replacing finished.}

### File: ../src/dialogs/searchdialog.tcl
mcset ja_jp {Cannot match the pattern!} 見つかりませんでした

### File: ../src/dialogs/bind_param.tcl
mcset ja_jp {Query number %s} {Query number %s}

### File: ../src/dialogs/bind_param.tcl
mcset ja_jp {Parameter number %s (named: %s):} {Parameter number %s (named: %s):}

### File: ../src/dialogs/bind_param.tcl
mcset ja_jp {NULL value} {NULL value}

### File: ../src/dialogs/bind_param.tcl
mcset ja_jp {You can use '%s' keyboard shortcut to switch NULL value.} {You can use '%s' keyboard shortcut to switch NULL value.}

### File: ../src/dialogs/bind_param.tcl
mcset ja_jp {Copy value to other '%s' parameters (%s)} {Copy value to other '%s' parameters (%s)}

### File: ../src/dialogs/bind_param.tcl
mcset ja_jp {By enabling this all parameters with same name
will also have same value as this one.} {By enabling this all parameters with same name
will also have same value as this one.}

### File: ../src/dialogs/bind_param.tcl
mcset ja_jp {Execute query} クエリ実行

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ja_jp Collation Collation

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ja_jp Sort ソート

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ja_jp {Named constraint:} 制約名:

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ja_jp {On conflict:} 競合:

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ja_jp {Constraint is marked as being named, but there's no name filled in.} {Constraint is marked as being named, but there's no name filled in.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ja_jp {Collation for column '%s' is enabled, but there's no collation name filled in.} {Collation for column '%s' is enabled, but there's no collation name filled in.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ja_jp {No columns are selected.} カラムが選択されていません

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp {Number of rows to insert:} 追加するライン数:

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp {On a constraint violation:} {On a constraint violation:}

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp Mode モード

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp {Select table to display available columns} {Select table to display available columns}

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp Populate テストデータを追加

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp {Error occured while populating table:
%s} {テストデータの追加でエラーが発生しました。:
%s}

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp Configuration 設定

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp {You have to type valid number of rows to insert.} {You have to type valid number of rows to insert.}

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp {You have to select at least one column to populate.} {You have to select at least one column to populate.}

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp Populating... テストデータを追加しています

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp {Populating table '%s'.} テーブル'%s'にテストデータを追加

### File: ../src/dialogs/populate_table.tcl
mcset ja_jp Stop 停止

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ja_jp {Foreign table:} 外部テーブル:

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ja_jp {Local column} ローカルカラム

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ja_jp {Foreign column} 外部カラム

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ja_jp Reactions リアクション

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ja_jp {ON UPDATE} 更新時

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ja_jp {ON DELETE} 削除時

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ja_jp MATCH 一致

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ja_jp {Deferred foreign key} {Deferred 外部キー}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ja_jp {No foreign table selected.} 外部テーブルが選択されていません

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ja_jp {There's no foreign column assigned for local column '%s'.} {There's no外部カラム assigned for local column '%s'.}

### File: ../src/dialogs/import_dialog.tcl
mcset ja_jp {Import from:} {Import from:}

### File: ../src/dialogs/import_dialog.tcl
mcset ja_jp {Import to:} {Import to:}

### File: ../src/dialogs/import_dialog.tcl
mcset ja_jp Table テーブル

### File: ../src/dialogs/import_dialog.tcl
mcset ja_jp Existing Existing

### File: ../src/dialogs/import_dialog.tcl
mcset ja_jp {Create new table} {Create new table}

### File: ../src/dialogs/import_dialog.tcl
mcset ja_jp Import Import

### File: ../src/dialogs/import_dialog.tcl
mcset ja_jp {Import method is not selected.} {Import method is not selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset ja_jp {You have to choose database.} データベースを選択してください

### File: ../src/dialogs/import_dialog.tcl
mcset ja_jp {No existing table is selected.} {No existing table is selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset ja_jp {Table typed to create already exists. Please change table name.} {Table typed to create already exists. Please change table name.}

### File: ../src/dialogs/view_dialog.tcl
mcset ja_jp View 表示

### File: ../src/dialogs/view_dialog.tcl
mcset ja_jp {View name:} ビュー名:

### File: ../src/dialogs/view_dialog.tcl
mcset ja_jp {Code executed to get view data:} ビューデータの作成コード:

### File: ../src/dialogs/view_dialog.tcl
mcset ja_jp Create 作成

### File: ../src/dialogs/view_dialog.tcl
mcset ja_jp Change 変更

### File: ../src/dialogs/view_dialog.tcl
mcset ja_jp {You have to specify database.} データベースを選択してください

### File: ../src/dialogs/view_dialog.tcl
mcset ja_jp {You have to specify view name.} ビュー名を入力してください

### File: ../src/dialogs/view_dialog.tcl
mcset ja_jp {You havn't wrote a code for the view.} ビューのコードが記入されていません。

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {Export data} エクスポート

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {Only structure, without data} {Only structure, without data}

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {Table or view} {Table or view}

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {Output file} {Output file}

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {Export format} エクスポート形式

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp Export エクスポート

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {You have to choose file.} ファイルを選択してください

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {Can't write to file: %s} {ファイル '%s'の書き込みが失敗しました}

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {You have to choose table.} テーブルを選択してください

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {Exporting database '%s'.} {データベース '%s' をエクスポートしています}

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {Exporting table '%s'.} {テーブル '%s' をエクスポートしています}

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {Exporting view '%s'.} {Exporting view '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {Exporting results.} 実行結果のエクスポート

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp Exporting... エクスポートしています

### File: ../src/dialogs/export_dialog.tcl
mcset ja_jp {Cannot write to file: %s
Please select other file.} {Cannot write to file: %s
他のファイルを選択してください。}

### File: ../src/dialogs/bug_report_login.tcl
mcset ja_jp {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.} {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.}

### File: ../src/dialogs/bug_report_login.tcl
mcset ja_jp Login: Login:

### File: ../src/dialogs/bug_report_login.tcl
mcset ja_jp Password: Password:

### File: ../src/dialogs/bug_report_login.tcl
mcset ja_jp Validate Validate

### File: ../src/dialogs/bug_report_login.tcl
mcset ja_jp {Validation result} {Validation result}

### File: ../src/dialogs/bug_report_login.tcl
mcset ja_jp {Not validated yet} {Not validated yet}

### File: ../src/dialogs/bug_report_login.tcl
mcset ja_jp Validating... Validating...

### File: ../src/dialogs/bug_report_login.tcl
mcset ja_jp {Validating login and password...} {Validating login and password...}

### File: ../src/dialogs/bug_report_login.tcl
mcset ja_jp {Invalid login or password.} {Invalid login or password.}

### File: ../src/dialogs/bug_report_login.tcl
mcset ja_jp {Login and password are correct.} {Login and password are correct.}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Your e-mail address or user (both optional)} {Your e-mail address or user (both optional)}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp or または

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Log in} {Log in}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Logged in} {Logged in}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Log out} {Log out}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Brief description:} 簡単な説明:

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {How to reproduce problem (if possible):} {再現方法 (できれば):}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {What is the problem:} 問題はなんですか？:

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Show more (optional)} {Show more (optional)}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Operating system:} オペレーティングシステム:

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Take screenshots of all SQLiteStudio windows and attach them} {Take screenshots of all SQLiteStudio windows and attach them}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp Send 送る

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Describe your feature request:} {Describe your feature request:}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp Hide Hide

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Please fill 'Brief' field.} {Please fill 'Brief' field.}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Please fill at least one of 'Description' or 'How to reproduce' fields.} {Please fill at least one of 'Description' or 'How to reproduce' fields.}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {Please provide valid e-mail address or leave 'E-mail' empty.} {Please provide valid e-mail address or leave 'E-mail' empty.}

### File: ../src/dialogs/bug_report.tcl
mcset ja_jp {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.} {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.}

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Database to convert:} データベースのコンバート:

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Converted database name:} コンバートするデータベース名:

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {File to use for converted database:} {File to use for converted database:}

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Choose new file for database} {Choose new file for database}

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Database version:} データベースバージョン:

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp Convert コンバート

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Convert database} データベースのコンバート

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {You chave to choose database to convert.} {You chave to choose database to convert.}

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Error resolving database with name %s!} {Error resolving database with name %s!}

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {You have to specify new database file.} データベースファイル名を入力してください

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Cannot use existing file for converted database.} {Cannot use existing file for converted database.}

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Cannot use existing name for converted database.} {Cannot use existing name for converted database.}

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Cannot find handler for database labeled with: %s} {Cannot find handler for database labeled with: %s}

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Error while trying to create database: %s} {Error while trying to create database: %s}

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Database converting error} データベースコンバートのエラー

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s} {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s}

### File: ../src/dialogs/db_convert.tcl
mcset ja_jp {Choose file} ファイル選択

### File: ../src/dialogs/yesno.tcl
mcset ja_jp Question Question

### File: ../src/dialogs/yesno.tcl
mcset ja_jp Warning 警告

### File: ../src/dialogs/yesno.tcl
mcset ja_jp Error エラー

### File: ../src/dialogs/yesno.tcl
mcset ja_jp Information 情報

### File: ../src/dialogs/import_db.tcl
mcset ja_jp {Import from one of databases:} インポートするデータベースファイル選択:

### File: ../src/dialogs/import_db.tcl
mcset ja_jp {Choose database file to import:} データベースが選択されていません

### File: ../src/dialogs/import_db.tcl
mcset ja_jp {No database chosen.} データベースが選択されていません

### File: ../src/dialogs/import_db.tcl
mcset ja_jp {Cannot open specified database.} データベースファイルが指定されていません

### File: ../src/dialogs/import_db.tcl
mcset ja_jp {Error while importing database:
%s} {データベースのインポートでエラーが発生しました:
%s}

### File: ../src/dialogs/import_db.tcl
mcset ja_jp {Select file} ファイルの選択

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp Column: カラム:

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Column constraints:} カラム制限:

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp Add 追加

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp Size サイズ

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Maximal length of value in column.} {Maximal length of value in column.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Primary key configuration} 主キーの設定

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp Autoincrement Autoincrement

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Sort order:} {Sort order:}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {No foreign column selected.} 外部カラムが選択されていません

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Choose ON UPDATE action, or disable it.} {Choose ON UPDATE action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Choose ON DELETE action, or disable it.} {Choose ON DELETE action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Choose MATCH action, or disable it.} {Choose MATCH action, or disable it.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Foreign key configuration} 外部キーの設定

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Foreign column:} 外部カラム:

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Unique configuration} ユニークキー設定

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Fill in the condition expression.} {Fill in the condition expression.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Check condition configuration} {Check condition configuration}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp Condition: 状態:

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Not null configuration} NULL禁止の設定

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Fill in the collation name.} {Fill in the collation name.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Collating configuration} 定義の設定

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Collation name:} 定義名:

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Fill in the default value.} {Fill in the デフォルト値}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Default value configuration} デフォルト値の設定

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Default value:} デフォルト値:

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Use value as:} {Use value as:}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {A literal value} {A literal value}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {An expression} {An expression}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Column primary key is not configured correctly.} カラムの主キーは正しく設定されていません

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {AUTOINCREMENT is allowed only with INTEGER type of column.} {AUTOINCREMENT is allowed only with INTEGER type of column.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Column foreign key is not configured correctly.} カラムの外部キーは正しく設定されていません

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Column 'unique' constraint is not configured correctly.} {Column 'unique' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Column 'check' constraint is not configured correctly.} {Column 'check' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Column 'notnull' constraint is not configured correctly.} {Column 'notnull' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Column 'default' constraint is not configured correctly.} {Column 'default' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Column 'collate' constraint is not configured correctly.} {Column 'collate' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {No column name is specified.} {No column name is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Column with name '%s' already exists in the table.} {Column with name '%s' already exists in the table.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Data type bounds are given, but no data type name is specified.} {Data type bounds are given, but no data type name is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Data type precision is given, but no data type size is specified.} {Data type precision is given, but no data type size is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Data type size has invalid format. Only integer value is allowed.} {Data type size has invalid format. Only integer value is allowed.}

### File: ../src/dialogs/column_dialog.tcl
mcset ja_jp {Data type precision has invalid format. Only integer value is allowed.} {Data type precision has invalid format. Only integer value is allowed.}

### File: ../src/dialogs/assoc_dialog.tcl
mcset ja_jp {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:} {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:}

### File: ../src/dialogs/assoc_dialog.tcl
mcset ja_jp {Current associations} {Current associations}

### File: ../src/dialogs/assoc_dialog.tcl
mcset ja_jp {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.} {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.}

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {Database file:} データベースファイル:

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {Database name:} データベース名:

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {Generate automatically} ファイル名から自動生成

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {Type name in field below:} 手動で入力

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {Remember it permanently} 設定を保存する

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {If disabled, then the database will be registered only
for this single SQLiteStudio session.} {If disabled, then the database will be registered only
for this single SQLiteStudio session.}

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {Edit database} データベースの編集

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {Add database} データベースの追加

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {File '%s' doesn't exist!} {File '%s' doesn't exist!}

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {You have to specify database file.} データベースファイルが選択されていません

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {Database named '%s' already exists on databases list. Please pick other name.} {Database named '%s' already exists on databases list. Please pick other name.}

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.} {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.}

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.} {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.}

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {Type not existing file for new database} {Type not existing file for new database}

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {Select existing database file} {Select existing database file}

### File: ../src/dialogs/db_edit.tcl
mcset ja_jp {%s is not supported database!} {%s この形式のファイルはサポートしていません。}

### File: ../src/dialogs/table_dialog_pk.tcl
mcset ja_jp {Using autoincrement with more than one column at once is forbidden.} {Using autoincrement with more than one column at once is forbidden.}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp Previous 前

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp Next 次

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {Do not show this dialog at startup} 起動時にTIPSを表示させない

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		} {
			If you dislike to open multiple SQLエディタ, you can use single エディタ,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			You can configure all SQL editor syntax colors in settings.
		} {
			設定ウィンドウでSQLエディタのすべての色を変更できます。
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		} {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		} {
			SQLエディタでControl+Space（設定で変更可能）を押すとコード補完機能を使用できます。
			また文脈から推測されたコマンドの一覧からの選択もできます。
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		} {
			たくさんのショートカット (すべてカスタマイズ可能)でSQLiteStudioを簡単に素早く使うことができます。
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		} {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		} {
			あなたがMDIウィンドウを開いたままSQLiteStudioを閉じた場合、すべてのウィンドウは次の起動時に復元されます（SQLエディタと書きかけの内容も含めて）。
			設定でセッションの再現を無効にしている場合は復元されません。
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		} {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		} {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		} {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		} {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		} {
			ROWIDを確認したいならそのラインにマウスを置いてしばらく待ってみてください。
			ROWID（そしてその他の情報）がポップアップされるでしょう。
			ROWIDを最初のカラムとして表示しておくこともできます（このオプションはグリッドの右クリックメニューで設定することができます。）
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		} {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		} {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in 設定ウィンドウ.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		} {
			SQLエディタの実行履歴タブであなたはいつでも過去のクエリ実行履歴を確認することができます<br><br>
			保存する履歴の数は設定ウィンドウで設定できます。しかし、注意してください。
			設定した履歴の数があまりにも多いと、新しいSQLエディタを開くたびにすべての履歴を読み込むので動作が遅くなる可能性があります。
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		} {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		} {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		} {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ja_jp {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		} {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		}

### File: ../src/dialogs/import_table.tcl
mcset ja_jp Separator: 区切り文字:

### File: ../src/dialogs/import_table.tcl
mcset ja_jp {Common separator is \t (tab), but sometimes others can be met.} {Common separator is \t (tab), but sometimes others can be met.}

### File: ../src/dialogs/import_table.tcl
mcset ja_jp {Import data file for '%s' table:} {Import data file for '%s' table:}

### File: ../src/dialogs/import_table.tcl
mcset ja_jp {File '%s' isn't readable!} {File '%s' isn't readable!}

### File: ../src/dialogs/import_table.tcl
mcset ja_jp {Error while trying to copy data:
%s} {データのコピーでエラーが発生しました:
%s}

### File: ../src/dialogs/release_notes_dialog.tcl
mcset ja_jp {Don't show this dialog after update.} {Don't show this dialog after update.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp Trigger トリガー

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {On action:} {On action:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {Trigger name:} トリガー名:

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp When: When:

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {On table:} 対象テーブル:

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {Execute code for:} {Execute code for:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.} {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {Execute code only when:} {Execute code only when:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {Code executed for above configuration:} {Code executed for above configuration:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {You have to specify view.} ビューを選択してください

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {You have to specify table.} テーブルを選択してください

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {You have to specify trigger name.} トリガー名を入力してください

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {You have to specify 'action' condition.} {You have to specify 'action' condition.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {You havn't wrote a code for the trigger.} トリガーのコードが記入されていません。

### File: ../src/dialogs/trigger_dialog.tcl
mcset ja_jp {On view:} {On view:}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp Columns: カラム:

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Table constraints:} テーブル制限:

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Table name:} テーブル名:

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Add column} カラムの追加

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Edit selected} カラムの編集

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Delete selected} カラムの削除

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp Type タイプ

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp Details Details

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.} {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Edit column} カラムの編集

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Delete column} カラムの削除

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Are you sure you want to delete column '%s'?} {カラム '%s' を削除してよろしいですか？}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Constraint change} {Constraint change}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Are you sure you want to change constraint type?
Current constraint configuration will be lost.} {Are you sure you want to change constraint type?
Current constraint configuration will be lost.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Table constraint number %s (%s) is not configured correctly.} {Table constraint number %s (%s) is not configured correctly.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {There's no column defined.} {There's no column defined.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {There is already a table with name '%s'. Please change the name of this table.} {There is already a table with name '%s'. Please change the name of this table.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {There is already an index with name '%s'. Please change the name of this index.} {There is already an index with name '%s'. Please change the name of this index.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {There is already a trigger with name '%s'. Please change the name of this trigger.} {There is already a trigger with name '%s'. Please change the name of this trigger.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {There is already a view with name '%s'. Please change the name of this view.} {There is already a view with name '%s'. Please change the name of this view.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Trigger parsing problem} {Trigger parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Index parsing problem} {Index parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {View parsing problem} {View parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.} {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {%s(%s) referencing %s(%s)} {%s(%s) referencing %s(%s)}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s} {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Do you want to continue anyway?} {Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?} {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Modifying table...} テーブルを変更しています。

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Modifying table '%s'.} {テーブル '%s' を変更しています}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Could not recreate triggers for modified table.} {Could not recreate triggers for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Could not recreate indexes for modified table.} {Could not recreate indexes for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Could not recreate views for modified table.} {Could not recreate views for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Trigger recreation problem} {Trigger recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Index recreation problem} {Index recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {Could not recreate foreign keys for tables referencing modified table.} {Could not recreate foreign keys for tables referencing modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {View recreation problem} {View recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset ja_jp {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).} {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).}

### File: ../src/dialogs/table_dialog_chk.tcl
mcset ja_jp {Condition expression cannot be empty.} {Condition expression cannot be empty.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset ja_jp {What would you like to do?} どうしますか？

### File: ../src/dialogs/new_version_dialog.tcl
mcset ja_jp {Install it automatically} 自動でインストール

### File: ../src/dialogs/new_version_dialog.tcl
mcset ja_jp {Go to download page} ダウンロードページを開く

### File: ../src/dialogs/new_version_dialog.tcl
mcset ja_jp {Package download} パッケージをダウンロード

### File: ../src/dialogs/new_version_dialog.tcl
mcset ja_jp {Insufficient privileges to perform automatic update.} {Insufficient privileges to perform automatic update.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset ja_jp {Check for updates at startup} {Check for updates at startup}

### File: ../src/dialogs/new_version_dialog.tcl
mcset ja_jp {New version of SQLiteStudio is available: %s} {New version of SQLiteStudio is available: %s}

### File: ../src/dialogs/trigger_dialog_cols.tcl
mcset ja_jp {Trigger columns} {Trigger columns}

### File: ../src/dialogs/blob_edit.tcl
mcset ja_jp Commit Commit

### File: ../src/dialogs/bug_history.tcl
mcset ja_jp Clear 消去

### File: ../src/dialogs/bug_history.tcl
mcset ja_jp {Reported on} {Reported on}

### File: ../src/dialogs/bug_history.tcl
mcset ja_jp Brief 要約

### File: ../src/dialogs/bug_history.tcl
mcset ja_jp URL URL

### File: ../src/dialogs/bug_history.tcl
mcset ja_jp Discussion Discussion

### File: ../src/dialogs/bug_history.tcl
mcset ja_jp {Clear reports} レポートの削除

### File: ../src/dialogs/bug_history.tcl
mcset ja_jp {Do you want to clear whole bug reports history?} これらのバグレポートヒストリーを消去しますか？

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp Index インデックス

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp {Index name:} インデックス名:

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp Available Available

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp Indexed Indexed

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp {Modifying index} {Modifying index}

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp {Modifying index '%s'} {Modifying index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp {Creating index} {Creating index}

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp {Creating index '%s'} {Creating index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?} {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?}

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp {Unique values} ユニーク値

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp {Same values for '%s'} {Same values for '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp {You have to select at least one column.} 一つ以上のカラムを選択してください

### File: ../src/dialogs/index_dialog.tcl
mcset ja_jp {You have to specify index name.} インデックス名を入力してください

### File: ../src/dialogs/functions_dialog.tcl
mcset ja_jp Implementation: 実装:

### File: ../src/dialogs/functions_dialog.tcl
mcset ja_jp Name: 名前:

### File: ../src/dialogs/functions_dialog.tcl
mcset ja_jp {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.} {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.}

### File: ../src/dialogs/functions_dialog.tcl
mcset ja_jp {Cannot use two functions with same name! Change name for '%s'.} 同じ名前の関数が存在しています。'%s'　の名前を変更してください

### File: ../src/dialogs/functions_dialog.tcl
mcset ja_jp {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! } {関数名には 'tcl' または 'sqlfile' は使用できません。これらの名前は予約されています}

### File: ../src/dialogs/functions_dialog.tcl
mcset ja_jp {Function '%s' is not implemented!} {Function '%s' is not implemented!}

### File: ../src/dialogs/functions_dialog.tcl
mcset ja_jp {Delete function} 関数の削除

### File: ../src/dialogs/functions_dialog.tcl
mcset ja_jp {Are you sure you want to delete function '%s'?} {関数 '%s' を削除してよろしいですか？}

### File: ../src/mainwindow.tcl
mcset ja_jp {Connect to selected database} 選択されたデータベースと接続

### File: ../src/mainwindow.tcl
mcset ja_jp {Disconnect from selected database} 選択されたデータベースを切断

### File: ../src/mainwindow.tcl
mcset ja_jp {Remove selected database from list} 選択されたデータベースをリストから削除

### File: ../src/mainwindow.tcl
mcset ja_jp {New table} 新規テーブル

### File: ../src/mainwindow.tcl
mcset ja_jp {Drop table} テーブルの削除

### File: ../src/mainwindow.tcl
mcset ja_jp {Drop index} インデックスの削除

### File: ../src/mainwindow.tcl
mcset ja_jp {Drop trigger} トリガーの削除

### File: ../src/mainwindow.tcl
mcset ja_jp {Edit view} ビューの編集

### File: ../src/mainwindow.tcl
mcset ja_jp {Drop view} ビューの削除

### File: ../src/mainwindow.tcl
mcset ja_jp {Arrange cascade windows layout} 重ねて表示

### File: ../src/mainwindow.tcl
mcset ja_jp {Arrange intelligent windows layout} ならべて表示

### File: ../src/mainwindow.tcl
mcset ja_jp {Refresh databases tree (%s)} {データベースツリーの更新 (%s)}

### File: ../src/mainwindow.tcl
mcset ja_jp {Open SQL query editor} SQLクエリエディタを開く

### File: ../src/mainwindow.tcl
mcset ja_jp {Settings (%s)} {Settings (%s)}

### File: ../src/mainwindow.tcl
mcset ja_jp {Open SQL functions editor} {Open SQL functions editor}

### File: ../src/mainwindow.tcl
mcset ja_jp {Clear objects filter} {Clear objects filter}

### File: ../src/mainwindow.tcl
mcset ja_jp {Enter object name you want to look for} {Enter object name you want to look for}

### File: ../src/mainwindow.tcl
mcset ja_jp Databases データベース

### File: ../src/mainwindow.tcl
mcset ja_jp Tools ツール

### File: ../src/mainwindow.tcl
mcset ja_jp Connect 接続

### File: ../src/mainwindow.tcl
mcset ja_jp Disconnect 切断

### File: ../src/mainwindow.tcl
mcset ja_jp {Remove from list} データベースをリストから削除

### File: ../src/mainwindow.tcl
mcset ja_jp {View main toolbar} メインツールバー

### File: ../src/mainwindow.tcl
mcset ja_jp {View structure toolbar} 構造ツールバー

### File: ../src/mainwindow.tcl
mcset ja_jp {View windows toolbar} ウィンドウツールバー

### File: ../src/mainwindow.tcl
mcset ja_jp {View tools toolbar} ツールズツールバー

### File: ../src/mainwindow.tcl
mcset ja_jp {View configuration toolbar} 設定ツールバー

### File: ../src/mainwindow.tcl
mcset ja_jp {Refresh databases tree} データベースツリーの更新

### File: ../src/mainwindow.tcl
mcset ja_jp {Custom SQL functions} ユーザー定義関数

### File: ../src/mainwindow.tcl
mcset ja_jp {Export database} データベースのエクスポート

### File: ../src/mainwindow.tcl
mcset ja_jp {Export table or view} {Export table or view}

### File: ../src/mainwindow.tcl
mcset ja_jp {Import data to a table} {Import data to a table}

### File: ../src/mainwindow.tcl
mcset ja_jp {SQLiteStudio home page} {SQLiteStudio home page}

### File: ../src/mainwindow.tcl
mcset ja_jp {SQLiteStudio manual} SQLiteStudioオンラインマニュアル(PDF)

### File: ../src/mainwindow.tcl
mcset ja_jp {SQLite documentation} SQLiteドキュメント

### File: ../src/mainwindow.tcl
mcset ja_jp {SQLiteStudio support forum} {SQLiteStudio サポートフォーラム}

### File: ../src/mainwindow.tcl
mcset ja_jp {Report a bug} バグレポート

### File: ../src/mainwindow.tcl
mcset ja_jp {Send feature request} 要望

### File: ../src/mainwindow.tcl
mcset ja_jp {Show bug reports history} バグレポートヒストリー

### File: ../src/mainwindow.tcl
mcset ja_jp {Show tips window} TIPS

### File: ../src/mainwindow.tcl
mcset ja_jp ChangeLog ChangeLog(更新履歴)

### File: ../src/mainwindow.tcl
mcset ja_jp Roadmap ロードマップ

### File: ../src/mainwindow.tcl
mcset ja_jp {Check for new version} 最新バージョンの確認

### File: ../src/mainwindow.tcl
mcset ja_jp Donate Donate

### File: ../src/mainwindow.tcl
mcset ja_jp {Did you know that...} TIPS

### File: ../src/mainwindow.tcl
mcset ja_jp {Editor %s} {エディタ %s}

### File: ../src/mainwindow.tcl
mcset ja_jp Settings 設定

### File: ../src/mainwindow.tcl
mcset ja_jp {SQLiteStudio roadmap} {SQLiteStudio ロードマップ}

### File: ../src/mainwindow.tcl
mcset ja_jp {Can't start web browser, because:
%s} {WEBブラウザを開けませんでした
原因:%s}

### File: ../src/mainwindow.tcl
mcset ja_jp {Can't start %s web browser, because:
%s} {WEBブラウザ(%s)を開けませんでした
原因:%s}

### File: ../src/mainwindow.tcl
mcset ja_jp {About SQLiteStudio} SQLiteStudioについて

### File: ../src/mainwindow.tcl
mcset ja_jp {SQLiteStudio ChangeLog} SQLiteStudioのChangeLog

### File: ../src/mainwindow.tcl
mcset ja_jp {There is no new version available.} 使用しているバージョンが最新です

### File: ../src/mainwindow.tcl
mcset ja_jp {New version} 最新バージョン

### File: ../src/mainwindow.tcl
mcset ja_jp {Report bug} バグレポート

### File: ../src/mainwindow.tcl
mcset ja_jp {Feature request} 要望

### File: ../src/mainwindow.tcl
mcset ja_jp {Reports history} バグレポートヒストリー

### File: ../src/mainwindow.tcl
mcset ja_jp {Reporting bug} バグレポート

### File: ../src/mainwindow.tcl
mcset ja_jp {Reporting bug to SQLiteStudio bugs database...} SQLiteStudioバグデータベースに送信しています

### File: ../src/mainwindow.tcl
mcset ja_jp {Problem occurred while reporting bug. You can ignore it and get back to your work.} {Problem occurred while reporting bug. You can ignore it and get back to your work.}

### File: ../src/mainwindow.tcl
mcset ja_jp Ignore Ignore

### File: ../src/mainwindow.tcl
mcset ja_jp {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history} {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history}

### File: ../src/mainwindow.tcl
mcset ja_jp {A timeout occured while downloading new version. Try again, or download it manually.} {A timeout occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset ja_jp {An error occured while downloading new version. Try again, or download it manually.} {An error occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset ja_jp Downloading... ダウンロード中...

### File: ../src/mainwindow.tcl
mcset ja_jp {Downloading SQLiteStudio v%s...} {SQLiteStudio version %sをダウンロードしています}

### File: ../src/mainwindow.tcl
mcset ja_jp {Problem with saving new SQLiteStudio version to:
%s
Details:
%s} {Problem with saving new SQLiteStudio version to:
%s
Details:
%s}

### File: ../src/mainwindow.tcl
mcset ja_jp {Problem with getting new SQLiteStudio version
Details:
%s} {Problem with getting new SQLiteStudio version
Details:
%s}

### File: ../src/mainwindow.tcl
mcset ja_jp {This is unknown binary distribution. Cannot determinate binary file to download for update.} {This is unknown binary distribution. Cannot determinate binary file to download for update.}

### File: ../src/data_editor.tcl
mcset ja_jp {There are uncommited rows.
Are you sure you want to close '%s' window anywy?} {確定されていないラインがあります。
ウィンドウ '%s' を閉じますか？}

### File: ../src/common/ddl_dialog.tcl
mcset ja_jp {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s} {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s}

### File: ../src/common/color_picker.tcl
mcset ja_jp {Choose color} 色選択

### File: ../src/common/shortcut_edit.tcl
mcset ja_jp {Forbidden shortcut key combination: %s} {Forbidden shortcut key combination: %s}

### File: ../src/common/common.tcl
mcset ja_jp Copy コピー

### File: ../src/common/common.tcl
mcset ja_jp Cut Cut

### File: ../src/common/common.tcl
mcset ja_jp Paste 貼り付け

### File: ../src/common/blob_edit_panel.tcl
mcset ja_jp {Text edit} {Text edit}

### File: ../src/common/blob_edit_panel.tcl
mcset ja_jp {Hexadecimal edit} {Hexadecimal edit}

### File: ../src/common/common_sql.tcl
mcset ja_jp {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
} {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
}

### File: ../src/common/hex_editor.tcl
mcset ja_jp {Overwrite characters,
instead of inserting} {Overwrite characters,
instead of inserting}

### File: ../src/common/hex_editor.tcl
mcset ja_jp Processing Processing

### File: ../src/common/hex_editor.tcl
mcset ja_jp {Processing data...} {Processing data...}

### File: ../src/sql_editor.tcl
mcset ja_jp {Replace dialog} 置換ダイアログ

### File: ../src/sql_editor.tcl
mcset ja_jp {Search dialog} 検索ダイアログ

### File: ../src/trees/db_tree.tcl
mcset ja_jp Loading Loading

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Loading database list} {Loading database list}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Given database file doesn't exist or is unreadable.} {Given database file doesn't exist or is unreadable.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp Vacuum 整理

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Integrity check} {Integrity check}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Import schema from other database} 他のデータベースからスキーマをインポート

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Reset autoincrement for '%s'} {Reset autoincrement for '%s'}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Erase table data} {Erase table data}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Create foreign key} 外部キーの作成

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Show view data} ビューを表示

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Export view} {Export view}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Sort databases alphabetically} データベースをアルファベット順にソート

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Given database is already on the list.} {Given database is already on the list.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Given database name is already on the list.} {Given database name is already on the list.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp Tables テーブル

### File: ../src/trees/db_tree.tcl
mcset ja_jp Views ビュー

### File: ../src/trees/db_tree.tcl
mcset ja_jp {SQLite system table} SQLiteシステムテーブル

### File: ../src/trees/db_tree.tcl
mcset ja_jp Columns カラム

### File: ../src/trees/db_tree.tcl
mcset ja_jp {SQLite system index} {SQLite system index}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Remove database} データベース

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Are you sure you want to remove '%s' database from the list?} {データベース'%s' をリストから削除しますか？}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.} {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {'%s' is a virtual table, therefore cannot be browsed in table window.} {'%s' is a virtual table, therefore cannot be browsed in table window.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Table '%s' has no DDL. Probably it's system table and should not be edited.} {Table '%s' has no DDL. Probably it's system table and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {'%s' is a virtual table, therefore cannot be edited in table dialog.} {'%s' is a virtual table, therefore cannot be edited in table dialog.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.} {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Integrity check (%s)} {Integrity check (%s)}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Are you sure you want to DROP '%s' table?} {テーブル '%s' を削除してよろしいですか？}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Dropping table} {Dropping table}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Dropping table '%s'} {Dropping table '%s'}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Dropping index} {Dropping index}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Dropping index '%s'} {Dropping index '%s'}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?} {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Fix trigger} {Fix trigger}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.} {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?} {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Fix view} {Fix view}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {View '%s' has no DDL. Probably it's system view and should not be edited.} {View '%s' has no DDL. Probably it's system view and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Delete view} ビューの削除

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Are you sure you want to delete '%s' view?} {ビュー '%s' を削除してもよろしいですか？}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Erase data} {Erase data}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Are you sure you want to delete all data from table '%s'?} {Are you sure you want to delete all data from table '%s'?}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Deleting data} {Deleting data}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Deleting data from table '%s'} {Deleting data from table '%s'}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {'%s' view data} '%s'のビュー

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Are you sure you want to make a vacuum?} 整理してよろしいですか？

### File: ../src/trees/db_tree.tcl
mcset ja_jp Vacuuming Vacuuming

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Vacuuming '%s'} {Vacuuming '%s'}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {SQL files} SQLファイル

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Select SQL file to be executed} {Select SQL file to be executed}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Error while executing SQL:
%s} {Error while executing SQL:
%s}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {SQL executed sucessfly.} SQLの実行計画が成功しました。

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Import database schema} データベーススキーマのインポート

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Database: %s} {Database: %s}

### File: ../src/trees/db_tree.tcl
mcset ja_jp URI: URI:

### File: ../src/trees/db_tree.tcl
mcset ja_jp Version: Version:

### File: ../src/trees/db_tree.tcl
mcset ja_jp {File size:} {File size:}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Schema version:} {Schema version:}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Virtual table} {Virtual table}

### File: ../src/trees/db_tree.tcl
mcset ja_jp Indexes: Indexes:

### File: ../src/trees/db_tree.tcl
mcset ja_jp Triggers: Triggers:

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Column: %s} {カラム: %s}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Not null} {Not null}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Indexed table:} {Indexed table:}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copy index '%s' for table '%s'} {Copy index '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Move index '%s' to table '%s'} {Move index '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copy trigger '%s' for table '%s'} {Copy trigger '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Move trigger '%s' to table '%s'} {Move trigger '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copy view '%s' for database '%s'} {Copy view '%s' for database '%s'}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Move view '%s' to database '%s'} {Move view '%s' to database '%s'}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {View '%s' has no DDL, therefore cannot be edited.} {View '%s' has no DDL, therefore cannot be edited.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copy view} {Copy view}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Move view} {Move view}

### File: ../src/trees/db_tree.tcl
mcset ja_jp Move Move

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copy index} {Copy index}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Move index} {Move index}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copy trigger} {Copy trigger}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Move trigger} {Move trigger}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copy table '%s' to database '%s' (include data, indexes and triggers)} {Copy table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copy table '%s' to database '%s' (include data)} {Copy table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copy table '%s' to database '%s' (include indexes and triggers)} {Copy table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copy table '%s' to database '%s' (skip data, indexes and triggers)} {Copy table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Move table '%s' to database '%s' (include data, indexes and triggers)} {Move table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Move table '%s' to database '%s' (include data)} {Move table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Move table '%s' to database '%s' (include indexes and triggers)} {Move table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Move table '%s' to database '%s' (skip data, indexes and triggers)} {Move table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copying table...} {Copying table...}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Copying table '%s' from '%s' to '%s'.} {Copying table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Moving table...} {Moving table...}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Moving table '%s' from '%s' to '%s'.} {Moving table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Could not create object in target database:
%s} {Could not create object in target database:
%s}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Could not copy data:
%s} {Could not copy data:
%s}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Could not copy table data from source database to target database. Details: %s} {Could not copy table data from source database to target database. Details: %s}

### File: ../src/trees/db_tree.tcl
mcset ja_jp {Could not delete object(s) from source database. Details: %s} {Could not delete object(s) from source database. Details: %s}

### File: ../src/grids/dbgrid.tcl
mcset ja_jp {Edit BLOB entry:} {Edit BLOB entry:}

### File: ../src/grids/dbgrid.tcl
mcset ja_jp {BLOB edit} {BLOB edit}

### File: ../src/grids/dbgrid.tcl
mcset ja_jp {Cannot commit. Details:
%s} {Cannot commit. Details:
%s}

### File: ../src/grids/grid.tcl
mcset ja_jp {You have to select a cell before paste any contents.} {You have to select a cell before paste any contents.}

### File: ../src/grids/grid.tcl
mcset ja_jp {Cut data} {Cut data}

### File: ../src/grids/grid.tcl
mcset ja_jp {There are too many columns or rows to paste. Do you want to cut them and paste?} {There are too many columns or rows to paste. Do you want to cut them and paste?}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Insert new row} 新規ラインの挿入

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Delete selected rows} ラインの削除

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Edit cell value} セルの編集

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Edit cell value in BLOB editor} {Edit cell value in BLOB editor}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Duplicate row} ラインの複製

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Set NULL value} NULL値

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Generate SELECT from selected cells} {Generate SELECT from selected cells}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Commit selected cells} 選択されたセルを確定する。

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Rollback selected cells} 選択されたセルを元に戻す。

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Select all} {Select all}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Show ordinals} {Show ordinals}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Show ROWIDs} ROWIDを表示

### File: ../src/grids/data_grid.tcl
mcset ja_jp Type: Type:

### File: ../src/grids/data_grid.tcl
mcset ja_jp Constraints: 制限:

### File: ../src/grids/data_grid.tcl
mcset ja_jp {%s column has NOT NULL constraint. You have to fill value for it.} {%s column has NOT NULL constraint. You have to fill value for it.}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Error while adding new row:
%s} {Error while adding new row:
%s}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Error while updating new row:
%s} {Error while updating new row:
%s}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Error while updating cell value:
%s

What would you like to do?} {Error while updating cell value:
%s

What would you like to do?}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Re-edit value} {Re-edit value}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Return to value before edition} {Return to value before edition}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Cannot delete row(s), because it violates constraint. Details:
%s} {Cannot delete row(s), because it violates constraint. Details:
%s}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {Error while deleting selected rows:
%s} {Error while deleting selected rows:
%s}

### File: ../src/grids/data_grid.tcl
mcset ja_jp {SQL query generated at %s
using selected cells from window '%s'.} {SQL query generated at %s
using selected cells from window '%s'.}

### File: ../src/grids/result_grid.tcl
mcset ja_jp {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.} {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.}

### File: ../src/grids/result_grid.tcl
mcset ja_jp {Data type:} {Data type:}

### File: ../src/grids/result_grid.tcl
mcset ja_jp {No details are available on this cell.} {No details are available on this cell.}

### File: ../src/grids/result_grid.tcl
mcset ja_jp {Duplicated ROWID} {Duplicated ROWID}

### File: ../src/grids/result_grid.tcl
mcset ja_jp {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?} {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?}

### File: ../src/grids/result_grid.tcl
mcset ja_jp {Could not parse SQL while trying to generate requested query: %s} {Could not parse SQL while trying to generate requested query: %s}

### File: ../src/grids/result_grid.tcl
mcset ja_jp {Cannot use '%s' statement to generate requested query.} {Cannot use '%s' statement to generate requested query.}

### File: ../src/grids/result_grid.tcl
mcset ja_jp {Cannot determinate selected column with ID=%s.} {Cannot determinate selected column with ID=%s.}

### File: ../src/grids/result_grid.tcl
mcset ja_jp {Error occurred while trying to generate the query: %s} {Error occurred while trying to generate the query: %s}

### File: ../src/grids/result_grid.tcl
mcset ja_jp {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s} {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s}
