# SQLiteStudio 'nl' localization file

# Unchanged translations

### File: ../src/win_assoc.tcl
mcset nl {File associations} {File associations}

### File: ../src/win_assoc.tcl
mcset nl {Following file extensions could not be associated to the current SQLiteStudio version:
%s} {Following file extensions could not be associated to the current SQLiteStudio version:
%s}

### File: ../src/win_assoc.tcl
mcset nl {Click the link below to find out what is possible reason and solutions.} {Click the link below to find out what is possible reason and solutions.}

### File: ../src/cfg_win.tcl
mcset nl Ok Ok

### File: ../src/cfg_win.tcl
mcset nl Apply Toepassen

### File: ../src/cfg_win.tcl
mcset nl Cancel Annuleren

### File: ../src/cfg_win.tcl
mcset nl Theme Thema

### File: ../src/cfg_win.tcl
mcset nl {Select theme to use:} {Selecteer te gebruiken thema:}

### File: ../src/cfg_win.tcl
mcset nl {Theme version:} {Thema versie:}

### File: ../src/cfg_win.tcl
mcset nl Shortcuts sneltoetsen

### File: ../src/cfg_win.tcl
mcset nl {Global shortcuts} {Globale sneltoetsen}

### File: ../src/cfg_win.tcl
mcset nl {Open SQL editor} {SQL editor openen}

### File: ../src/cfg_win.tcl
mcset nl {Opens SQL editor window.} {Opent het SQL editor venster.}

### File: ../src/cfg_win.tcl
mcset nl {Close selected task} {Sluit geselecteerde taak}

### File: ../src/cfg_win.tcl
mcset nl {Closes active MDI window.} {Sluit actieve MDI venster.}

### File: ../src/cfg_win.tcl
mcset nl {Restore last closed task} {Restore last closed task}

### File: ../src/cfg_win.tcl
mcset nl {Restores last closed MDI window.} {Restores last closed MDI window.}

### File: ../src/cfg_win.tcl
mcset nl {Open settings} {Open instellingen}

### File: ../src/cfg_win.tcl
mcset nl {Opens SQLiteStudio settings window.} {Opent SQLiteStudio instellingen venster.}

### File: ../src/cfg_win.tcl
mcset nl {Next task} {Nieuwe taak}

### File: ../src/cfg_win.tcl
mcset nl {Switches task (window) to next, placed on the right from active task on taskbar.} {Schakelt taak(venster) naar volgende, en plaats deze rechts van de actieve taak in de taakbalk.}

### File: ../src/cfg_win.tcl
mcset nl {Next task (alternative)} {Volgende taak (alternatief)}

### File: ../src/cfg_win.tcl
mcset nl {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Schakelt taak(venster) naar de volgende, en plaats deze rechts van de active taak in de taakbalk.
Dit is een alternatieve sneltoets. Functioneert hetzelfde als hierboven.}

### File: ../src/cfg_win.tcl
mcset nl {Previous task} {Vorige taak}

### File: ../src/cfg_win.tcl
mcset nl {Switches task (window) to previous, placed on the left from active task on taskbar.} {Schakelt taak(venster) naar vorige, en plaats deze links van de actieve taak in de taakbalk.}

### File: ../src/cfg_win.tcl
mcset nl {Previous task (alternative)} {Vorige taak (alternatief)}

### File: ../src/cfg_win.tcl
mcset nl {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Schakelt taak(venster) naar de vorige, en plaats deze links van de active taak in de taakbalk.
Dit is een alternatieve sneltoets. Functioneert hetzelfde als hierboven.}

### File: ../src/cfg_win.tcl
mcset nl {Editor and table window shortcuts} {Editor and tabel venster sneltoetsen}

### File: ../src/cfg_win.tcl
mcset nl {SQL editor completion} {SQL editor aanvulling}

### File: ../src/cfg_win.tcl
mcset nl {Invokes SQL completion in editor window.} {Roept de SQL aanvulling in het editor venster aan.}

### File: ../src/cfg_win.tcl
mcset nl {Execute SQL query} {SQL query uitvoeren}

### File: ../src/cfg_win.tcl
mcset nl {Executes SQL query typed in editor.} {Voert SQL query uit vanuit editor.}

### File: ../src/cfg_win.tcl
mcset nl {Explain SQL query} {SQL query uitleggen}

### File: ../src/cfg_win.tcl
mcset nl {Calls EXPLAIN on SQL query typed in editor.} {Roept EXPLAIN op de SQL query in editor aan.}

### File: ../src/cfg_win.tcl
mcset nl {Format SQL code} {Formatteer SQL code}

### File: ../src/cfg_win.tcl
mcset nl {Formats SQL code typed in editor.} {Formatteert SQL code uit de editor.}

### File: ../src/cfg_win.tcl
mcset nl {Load SQL from file} {Laadt SQL van bestand}

### File: ../src/cfg_win.tcl
mcset nl {Loads SQL from file to the editor.} {Laadt SQL vanuit bestand in de editor.}

### File: ../src/cfg_win.tcl
mcset nl {Save SQL to file} {SQL opslaan naar bestand}

### File: ../src/cfg_win.tcl
mcset nl {Saves contents of the editor into a file.} {Slaat inhoud van editor op naar bestand.}

### File: ../src/cfg_win.tcl
mcset nl {Execute SQL from file} {SQL uitvoeren van bestand}

### File: ../src/cfg_win.tcl
mcset nl {Executes SQL directly from file, without loading it to the editor.} {Voert SQL direct uit vanaf bestand, zonder deze in de editor te laden.}

### File: ../src/cfg_win.tcl
mcset nl {Next tab} {Volgende tab}

### File: ../src/cfg_win.tcl
mcset nl {Switches to next tab of editor window (result or history).} {Schakelt naar het volgende tabblad van het editor venster (resultaat of geschiedenis).}

### File: ../src/cfg_win.tcl
mcset nl {Previous tab} {Vorige tab}

### File: ../src/cfg_win.tcl
mcset nl {Switches to previous tab of editor window (query or result).} {Schakelt naar het vorige tabblad van het editor venster (query oof resultaat).}

### File: ../src/cfg_win.tcl
mcset nl {Next subtab} {Volgende subtab}

### File: ../src/cfg_win.tcl
mcset nl {Switches to next subtab (form view in results tab).} {Schakelt naar volgende subtabblad (form view in results tab).}

### File: ../src/cfg_win.tcl
mcset nl {Previous subtab} {Vorige subtab}

### File: ../src/cfg_win.tcl
mcset nl {Switches to previous subtab (grid view in results tab).} {Schakelt naar vorige subtabblad (grid view in results tab).}

### File: ../src/cfg_win.tcl
mcset nl Refresh Verversen

### File: ../src/cfg_win.tcl
mcset nl {Re-executes SQL query so results data is refreshed.} {Voert SQL query opnieuw uit zodat gegevens ververst worden.}

### File: ../src/cfg_win.tcl
mcset nl {Delete selected row} {Verwijder geselecteerde rij}

### File: ../src/cfg_win.tcl
mcset nl {Deletes selected row.} {Verwijdert geselecteerde rij.}

### File: ../src/cfg_win.tcl
mcset nl {Add new row} {Nieuwe rij invoegen}

### File: ../src/cfg_win.tcl
mcset nl {Adds new empty row without commiting it.} {Voegt een nieuwe lege rij toe zonder deze te committen.}

### File: ../src/cfg_win.tcl
mcset nl {Erase cells data} {Erase cells data}

### File: ../src/cfg_win.tcl
mcset nl {Erases data of selected cells.} {Erases data of selected cells.}

### File: ../src/cfg_win.tcl
mcset nl {Next editor database in list} {Volgende editor database in lijst}

### File: ../src/cfg_win.tcl
mcset nl {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)} {Schakelt naar volgende database in editor context databases lijst
(de keuzelijst bovenaan het editor venster)}

### File: ../src/cfg_win.tcl
mcset nl {Previous editor database in list} {Vorige editor database in lijst}

### File: ../src/cfg_win.tcl
mcset nl {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)} {Schakelt naar vorige database in editor context databases lijst
(de keuzelijst bovenaan het editor venster)}

### File: ../src/cfg_win.tcl
mcset nl {Commit edition in Form View} {Commit editie in Form View}

### File: ../src/cfg_win.tcl
mcset nl {Commits edition in Form View of query results or table data preview.} {Voert de wijzigingen door in deze editie in de Form View van query resultaten of tabelgegevens preview.}

### File: ../src/cfg_win.tcl
mcset nl {Rollback edition in Form View} {Rollback editie in Form View}

### File: ../src/cfg_win.tcl
mcset nl {Rolls back edition in Form View of query results or table data preview.} {Maakt de wijzigingen ongedaan in deze editie in de Form View van query resultaten of tabelgegevens preview.}

### File: ../src/cfg_win.tcl
mcset nl {Jump to first row in Form View} {Ga naar eerste rij in Form View}

### File: ../src/cfg_win.tcl
mcset nl {Jumps to first row of query results grid
or table data preview grid in Form View.} {Spring naar eerste rij binnen het query resultaat grid
of tabelgegevens preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset nl {Go to previous row in Form View} {Ga naar vorige rij in Form View}

### File: ../src/cfg_win.tcl
mcset nl {Goes to previous row of query results grid
or table data preview grid row in Form View.} {Ga naar vorige rij binnen het query resultaat grid
of tabelgegevens preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset nl {Go to next row in Form View} {Ga naar volgende rij in Form View}

### File: ../src/cfg_win.tcl
mcset nl {Goes to next row of query results grid
or table data preview grid row in Form View.} {Ga naar volgende rij binnen het query resultaat grid
of tabelgegevens preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset nl {Jump to last row in Form View} {Spring naar laatste rij in Form View}

### File: ../src/cfg_win.tcl
mcset nl {Jumps to last row of query results grid
or table data preview grid in Form View.} {Spring naar laatste rij binnen het query resultaat grid
of tabelgegevens preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset nl {Switch NULL value in form edit field} {Switch NULL value in form edit field}

### File: ../src/cfg_win.tcl
mcset nl {Sets or unsets NULL value in currently selected
column in form view data edit mode.} {Sets or unsets NULL value in currently selected
column in form view data edit mode.}

### File: ../src/cfg_win.tcl
mcset nl Plugins Plugins

### File: ../src/cfg_win.tcl
mcset nl {SQL formatter plugins} {SQL formatter plugins}

### File: ../src/cfg_win.tcl
mcset nl {Use following SQL formatter plugin:} {Gebruik deze SQL formatter plugin:}

### File: ../src/cfg_win.tcl
mcset nl {Configure formatter plugin} {Configureer formatter plugin}

### File: ../src/cfg_win.tcl
mcset nl Configure Configureren

### File: ../src/cfg_win.tcl
mcset nl {Populating plugins} Bevolkingsplugins

### File: ../src/cfg_win.tcl
mcset nl {Default table populating plugin:} {Standaard tabel-bevolkende-plugin:}

### File: ../src/cfg_win.tcl
mcset nl Miscellaneous Diversen

### File: ../src/cfg_win.tcl
mcset nl {Restore session after next start} {Vorige sessie bij opstarten herstellen}

### File: ../src/cfg_win.tcl
mcset nl {All windows and their contents (such as SQL code)
will be restored while next application startup.} {Alle vensters en hun inhoud (zoals SQL code)
zullen bij de volgende start worden hersteld.}

### File: ../src/cfg_win.tcl
mcset nl {Show line numbers in SQL editor} {Toon regelnummers in SQL editor}

### File: ../src/cfg_win.tcl
mcset nl {All SQL editor windows will contain line numbers on the left side of window.} {Alle SQL editor vensters hebben regelnummers links in het venster.}

### File: ../src/cfg_win.tcl
mcset nl {Underline syntax errors in SQL editor} {Onderstreep syntaxfouten in SQL editor}

### File: ../src/cfg_win.tcl
mcset nl {Makes errors to be marked with underline.
You can also define foreground and background color for errors.} {Markeer fouten door onderstreping.
U kunt tevens de voor- en achtergrondkleuren van fouten configureren.}

### File: ../src/cfg_win.tcl
mcset nl {Show SQLite system tables and indexes in databases tree} {SQLite systeemtabellen en indexes tonen in de databases tree}

### File: ../src/cfg_win.tcl
mcset nl {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.} {Indien ingeschakeld worden SQLite systeemtabellen (beginnend met 'sqlite_*')
en indexen ('(*autoindex*)') getoond in de databases tree.}

### File: ../src/cfg_win.tcl
mcset nl {Open items with single mouse click in databases tree} {Items in de databases tree openen met een enkele muisklik}

### File: ../src/cfg_win.tcl
mcset nl {Items in database tree are open by double click by default.
This option switches it to single click.} {Items in de database tree worden standaard geopend met een dubbele muisklik.
Deze optie schakelt dit om naar een enkele muisklik.}

### File: ../src/cfg_win.tcl
mcset nl {Show ROWID as default instead of row order number in table data view} {Show ROWID as default instead of row order number in table data view}

### File: ../src/cfg_win.tcl
mcset nl {This option affects first column from the left on the data tab of the table window.} {This option affects first column from the left on the data tab of the table window.}

### File: ../src/cfg_win.tcl
mcset nl {Do not show 'did you know that...' dialog at startup.} {'Wist u dat...' dialoogvenster niet tonen bij opstarten.}

### File: ../src/cfg_win.tcl
mcset nl {Uncheck this option to show the dialog.} {Vink deze optie uit om venster te tonen.}

### File: ../src/cfg_win.tcl
mcset nl {Check for updates at startup.} {Controleer op updates bij opstarten.}

### File: ../src/cfg_win.tcl
mcset nl {If enabled, application will will check
for new version available at startup.} {Indien ingeschakeld zal de applicatie bij opstarten controleren
of een nieuwere versie beschikbaar is.}

### File: ../src/cfg_win.tcl
mcset nl {Sort custom SQL functions list by name} {Sorteer 'custom SQL functielijst' op naam}

### File: ../src/cfg_win.tcl
mcset nl {This list is placed in Custom SQL funcions dialog.} {Deze lijst wordt geplaatst in het 'Custom SQL functie' venster.}

### File: ../src/cfg_win.tcl
mcset nl {Select all contents when editing the table cell} {Select all contents when editing the table cell}

### File: ../src/cfg_win.tcl
mcset nl {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.} {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.}

### File: ../src/cfg_win.tcl
mcset nl {Ask if clipboard contents should be cut} {Vragen of clipboard inhoud mag worden geknipt}

### File: ../src/cfg_win.tcl
mcset nl {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.} {Indien ingeschakeld zal de applicatie de gebruikers vragen of de
te plakken gegevens ingekort mogen worden
wanneer de te plakken gegevens te lang zijn.
Indien uitgeschakeld worden gegevens automatisch ingeknipt.}

### File: ../src/cfg_win.tcl
mcset nl {Rows per page in Table Window and Editor Results:} {Rows per page in Table Window and Editor Results:}

### File: ../src/cfg_win.tcl
mcset nl {More results per page causes slower loading of single data page. Value 1000 should be right.} {Meer resultaten per pagina zorgt voor langere laadtijden per pagina. De waarde 1000 zou voldoende moeten zijn.}

### File: ../src/cfg_win.tcl
mcset nl {History entries limit:} {Maximum aantal geschiedenis items:}

### File: ../src/cfg_win.tcl
mcset nl {Number of rows to remember in SQL editor history.} {Aantal te onthouden rijen in SQL editor geschiedenis.}

### File: ../src/cfg_win.tcl
mcset nl {Insertion cursor blinking period (milliseconds):} {Insertion cursor blinking period (milliseconds):}

### File: ../src/cfg_win.tcl
mcset nl {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.} {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.}

### File: ../src/cfg_win.tcl
mcset nl {Web browser:} {Web browser:}

### File: ../src/cfg_win.tcl
mcset nl {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.} {U kunt hier uw eigen webbrowser commando opgeven. Het moet wel binnen de PATH variabele te vinden zijn.
Het te openen adres wordt simpelweg als parameter aan dit commando meegegeven.}

### File: ../src/cfg_win.tcl
mcset nl Language: Taal:

### File: ../src/cfg_win.tcl
mcset nl {Tab in table window on open:} {Tabblad in tabelvenster bij openen:}

### File: ../src/cfg_win.tcl
mcset nl {Table structure} Tabelstructuur

### File: ../src/cfg_win.tcl
mcset nl {Table data} Tabelgegevens

### File: ../src/cfg_win.tcl
mcset nl {Select which tab should be opened for start in table window,
when you just opened that window.} {Selecteer welk tabblad in aanvang geopend moet worden start in het tabelvenster,
op het moment dat u deze opent.}

### File: ../src/cfg_win.tcl
mcset nl {View default display mode:} {View default display mode:}

### File: ../src/cfg_win.tcl
mcset nl {Edition dialog} {Edition dialog}

### File: ../src/cfg_win.tcl
mcset nl {Data view} {Data view}

### File: ../src/cfg_win.tcl
mcset nl {Defines what is displayed by default when user opens a view.} {Defines what is displayed by default when user opens a view.}

### File: ../src/cfg_win.tcl
mcset nl {Editor window results layout} {Layout Editor venster resultaten}

### File: ../src/cfg_win.tcl
mcset nl {Show results in separated tab} {Resultaten in nieuwe tab tonen}

### File: ../src/cfg_win.tcl
mcset nl {Show results in frame below query} {Resultaten in frame beneden query tonen}

### File: ../src/cfg_win.tcl
mcset nl {Database tree display mode} {Database tree display mode}

### File: ../src/cfg_win.tcl
mcset nl {Show indexes and triggers linked under referenced table.} {Show indexes and triggers linked under referenced table.}

### File: ../src/cfg_win.tcl
mcset nl {Show indexes and triggers in their own groups.} {Show indexes and triggers in their own groups.}

### File: ../src/cfg_win.tcl
mcset nl {Show column names linked under the table.} {Show column names linked under the table.}

### File: ../src/cfg_win.tcl
mcset nl {Plain text results} {Plain text resultaat}

### File: ../src/cfg_win.tcl
mcset nl {Display NULL values as:} {Toon 'NULL'-waarden als:}

### File: ../src/cfg_win.tcl
mcset nl {Maximum column width:} {Maximum kolombreedte:}

### File: ../src/cfg_win.tcl
mcset nl {Values longer than specified here will be cut in plain text results.} {Veldwaarden langer dan hier gespecificeerd worden ingeknipt naar plain-text resultaten.}

### File: ../src/cfg_win.tcl
mcset nl Colors Kleuren

### File: ../src/cfg_win.tcl
mcset nl {Global colors} {Globale kleuren}

### File: ../src/cfg_win.tcl
mcset nl {MDI windows title bar background color} {MDI venster: achtergrondkleur titelbalk}

### File: ../src/cfg_win.tcl
mcset nl {MDI windows title bar foreground color} {MDI venster: voorgrondkleur titelbalk}

### File: ../src/cfg_win.tcl
mcset nl {MDI windows title bar button background color} {MDI venster: achtergrondkleur knop titelbalk }

### File: ../src/cfg_win.tcl
mcset nl {MDI windows title bar active button background color} {MDI venster: achtergrondkleur actieve knop titelbalk}

### File: ../src/cfg_win.tcl
mcset nl {SQL Editor} {SQL Editor}

### File: ../src/cfg_win.tcl
mcset nl {Editor standard font color} {Lettertype editor standaardkleur}

### File: ../src/cfg_win.tcl
mcset nl {Editor background} {Editor achtergrond}

### File: ../src/cfg_win.tcl
mcset nl {Selected foreground color} {Selectie: voorgrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Selected background color} {Selectie: achtergrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Disabled background color} {Uitgeschakeld: achtergrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Tables color} Tabelkleur

### File: ../src/cfg_win.tcl
mcset nl {Brackets color} {Brackets kleur}

### File: ../src/cfg_win.tcl
mcset nl {Square brackets color} {Square brackets kleur}

### File: ../src/cfg_win.tcl
mcset nl {Keywords color} {Kleur sleutelwoorden}

### File: ../src/cfg_win.tcl
mcset nl {Variables color} {Kleur variabelen}

### File: ../src/cfg_win.tcl
mcset nl {Strings color} {Kleur tekenreeks (string)}

### File: ../src/cfg_win.tcl
mcset nl {Comments color} {Kleur commentaar}

### File: ../src/cfg_win.tcl
mcset nl {Matched brackets foreground color} {Matched brackets voorgrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Matched brackets background color} {Matched brackets achtergrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Syntax error color} {Kleur syntaxfout}

### File: ../src/cfg_win.tcl
mcset nl {Tcl editor} {Tcl editor}

### File: ../src/cfg_win.tcl
mcset nl {Options color} {Kleur opties}

### File: ../src/cfg_win.tcl
mcset nl {Quoted character color} {Quoted karakter kleur}

### File: ../src/cfg_win.tcl
mcset nl {Trees colors} {Trees kleuren}

### File: ../src/cfg_win.tcl
mcset nl {Tree background} {Tree achtergrond}

### File: ../src/cfg_win.tcl
mcset nl {Tree standard font color} {Tree kleur standaard lettertype}

### File: ../src/cfg_win.tcl
mcset nl {Tree selected background color} {Tree selectie: achtergrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Tree selected foreground color} {Tree selectie: voorgrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Color for number of objects in tree branch} {Kleur voor aantal objecten in tree branch}

### File: ../src/cfg_win.tcl
mcset nl {Grids colors} {Grids kleuren}

### File: ../src/cfg_win.tcl
mcset nl {Grid background} {Grid achtergrond}

### File: ../src/cfg_win.tcl
mcset nl {Grid standard font color} {Grid standard font kleur}

### File: ../src/cfg_win.tcl
mcset nl {Grid selected background color} {Grid selectie: achtergrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Grid selected foreground color} {Grid selectie: voorgrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Grid base column background color} {Grid basis kolom achtergrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Foreground color for cells with NULL value} {Voorgrondkleur voor cellen met een NULL-waarde}

### File: ../src/cfg_win.tcl
mcset nl {Status fields colors} {Status velden kleuren}

### File: ../src/cfg_win.tcl
mcset nl {Background color} Achtergrondkleur

### File: ../src/cfg_win.tcl
mcset nl {Foreground color} Voorgrondkleur

### File: ../src/cfg_win.tcl
mcset nl {Error foreground color} {Error voorgrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Information foreground color} {Informatie voorgrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Information (second kind) foreground color} {Informatie (tweede type) voorgrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Miscellaneous colors} {Diversen kleuren}

### File: ../src/cfg_win.tcl
mcset nl {Context hints background color} {Contextuele hints: achtergrondkleur}

### File: ../src/cfg_win.tcl
mcset nl {Context hints foreground color} {Contextuele hints: voorgrondkleur}

### File: ../src/cfg_win.tcl
mcset nl Fonts Lettertypen

### File: ../src/cfg_win.tcl
mcset nl {SQL editor font} {Lettertype SQL editor}

### File: ../src/cfg_win.tcl
mcset nl {Status fields font} {Lettertype statusvelden}

### File: ../src/cfg_win.tcl
mcset nl {Grid font} {Lettertype grid}

### File: ../src/cfg_win.tcl
mcset nl {Tree font} {Lettertype tree}

### File: ../src/cfg_win.tcl
mcset nl {Tree additional labels font} {Lettertype tree extra labels}

### File: ../src/cfg_win.tcl
mcset nl {Context hints font} {Lettertype contextuele hints}

### File: ../src/cfg_win.tcl
mcset nl {Changed language needs application to be restarted.} {Veranderde taalinstellingen vereisen een herstart van het programma.}

### File: ../src/cfg_win.tcl
mcset nl {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.} {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.}

### File: ../src/cfg_win.tcl
mcset nl {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.} {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.}

### File: ../src/cfg_win.tcl
mcset nl {SQL formatter options} {SQL formatter opties}

### File: ../src/db/db_file_types.tcl
mcset nl {All SQLite Databases} {Alle SQLite Databases}

### File: ../src/db/db_file_types.tcl
mcset nl {SQLite 3 Databases} {SQLite 3 Databases}

### File: ../src/db/db_file_types.tcl
mcset nl {SQLite 2 Databases} {SQLite 2 Databases}

### File: ../src/db/db_file_types.tcl
mcset nl {All files} {Alle bestanden}

### File: ../src/db/query_executor.tcl
mcset nl {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.} {Query kon niet ontleed worden met behulp van de interne SQLiteStudio parser, dus is als zodanig doorgegeven aan SQLite, zonder enige substitutie of andere modificatie.}

### File: ../src/db/query_executor.tcl
mcset nl {Invalid database name: %s} {Ongeldige database naam: %s}

### File: ../src/db/query_executor.tcl
mcset nl {Imbalanced 'BEGIN' ocurrence in query.} {Imbalanced 'BEGIN' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset nl {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.} {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset nl {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.} {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset nl {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.} {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset nl {Cannot use more than one 'BEGIN'.} {Cannot use more than one 'BEGIN'.}

### File: ../src/db/query_executor.tcl
mcset nl {Imbalanced 'COMMIT' ocurrence in query.} {Imbalanced 'COMMIT' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset nl {Imbalanced 'ROLLBACK' ocurrence in query.} {Imbalanced 'ROLLBACK' ocurrence in query.}

### File: ../src/db/sqlite2.tcl
mcset nl {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)} {Er is een fout opgetreden tijdens aanroep van VACUUM op de database:
%s
(Dit bericht komt rechtstreeks uit SQLite2)}

### File: ../src/db/db.tcl
mcset nl {An internal logic error in SQLite} {Er is een interne fout opgetreden in SQLite}

### File: ../src/db/db.tcl
mcset nl {Access permission denied} {Toegangspermissie niet verleend}

### File: ../src/db/db.tcl
mcset nl {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.} {Kan operatie niet uitvoeren omdat de database bezig is.
Misschien is een andere applicatie bezig met een bewerking.}

### File: ../src/db/db.tcl
mcset nl {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.} {Kan operatie niet uitvoeren omdat de database gelocked is.
Misschien is een andere applicatie bezig met een bewerking.}

### File: ../src/db/db.tcl
mcset nl {A malloc() failed} {Een malloc() heeft gefaald}

### File: ../src/db/db.tcl
mcset nl {Attempt to write a readonly database} {Schrijfgebeurtenis naar een read-only database}

### File: ../src/db/db.tcl
mcset nl {Disk I/O error occurred} {Er is een disk I/O fout opgetreden}

### File: ../src/db/db.tcl
mcset nl {The database disk image is malformed} {De database disk image is corrupt}

### File: ../src/db/db.tcl
mcset nl {Database is full} {Database is vol}

### File: ../src/db/db.tcl
mcset nl {Unable to open the database file} {Unable to open the database file}

### File: ../src/db/db.tcl
mcset nl {Database lock protocol error} {Database lock protocol foutmelding}

### File: ../src/db/db.tcl
mcset nl {Database is empty} {Database is leeg}

### File: ../src/db/db.tcl
mcset nl {The database schema changed} {Het database schema is veranderd}

### File: ../src/db/db.tcl
mcset nl {String or BLOB exceeds size limit} {Tekenreeks of BLOB overstijgt maximum grootte}

### File: ../src/db/db.tcl
mcset nl {Library used incorrectly} {Bibliotheek onjuist gebruikt}

### File: ../src/db/db.tcl
mcset nl {Uses OS features not supported on host} {Gebruikt OS features die niet op dit systeem ondersteund zijn}

### File: ../src/db/db.tcl
mcset nl {Authorization denied} {Authorizatie niet verleend}

### File: ../src/db/db.tcl
mcset nl {Auxiliary database format error} {Auxiliary database format foutmelding}

### File: ../src/db/db.tcl
mcset nl {2nd parameter to sqlite3_bind out of range} {2e parameter naar sqlite3_bind niet binnen toegestane grenzen}

### File: ../src/db/db.tcl
mcset nl {File opened that is not a database file} {Bestand geopend dat geen database bestand is}

### File: ../src/db/db.tcl
mcset nl {Error while opening %s database:
%s} {Fout tijdens openen van %s database:
%s}

### File: ../src/db/db.tcl
mcset nl {Not enough parameters passed to function '%s'.} {Te weinig parameters opgegeven voor functie '%s'.}

### File: ../src/db/db.tcl
mcset nl {Cannot read file: %s} {Kan bestand niet lezen: %s}

### File: ../src/db/db.tcl
mcset nl {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.} {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.}

### File: ../src/db/db.tcl
mcset nl {Could not attach database %s. Error message from SQLite:
%s} {Could not attach database %s. Error message from SQLite:
%s}

### File: ../src/db/db.tcl
mcset nl {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.} {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.}

### File: ../src/db/sqlite3.tcl
mcset nl {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)} {Er is een fout opgetreden tijdens de VACUUM operatie in de database:
%s
(Dit bericht komt rechtstreeks uit SQLite3)}

### File: ../src/completion_routines.tcl
mcset nl {Problem with attaching database:
%s} {Problem with attaching database:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Error from importing plugin:
%s} {Error from importing plugin:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Error creating table '%s':
%s

Importing aborted.} {Error creating table '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Error trying to import data to '%s':
%s

Importing aborted.} {Error trying to import data to '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset nl Importing... Importing...

### File: ../src/plugins/import_plugin.tcl
mcset nl {Importing to table '%s'.} {Importing to table '%s'.}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?} {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?} {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Problem occured while importing row number %s:
%s

What would you like to do?} {Problem occured while importing row number %s:
%s

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Importing finished.} {Importing finished.}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Import problem} {Import problem}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Skip this data row} {Skip this data row}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Keep data rows imported so far (%s) and abort} {Keep data rows imported so far (%s) and abort}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Rollback data rows imported so far and abort} {Rollback data rows imported so far and abort}

### File: ../src/plugins/import_plugin.tcl
mcset nl {Ignore it and proceed} {Ignore it and proceed}

### File: ../src/plugins/import_plugin.tcl
mcset nl Abort Afbreken

### File: ../src/plugins/sql_formatting/enterprise/format_s.tcl
mcset nl name naam

### File: ../src/plugins/sql_formatting/basic.tcl
mcset nl {Reduce group of whitespaces into one whitespace.} {Reduceer groepen witruimte tot een enkele witruimte (spatie).}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset nl {Uppercase keywords.} {Hoofdletters voor alle sleutelwoorden.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset nl {Separate ")" and after contents with single whitespace.} {Scheidt ")" en na gegevens met een enkele witruimte.}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {SQLite3 only} {Enkel SQLite3}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl Indentation Inspringing

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {New lines} {Nieuwe regels}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {White spaces} Witruimte

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl Names Namen

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl Comments Commentaar

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Tab size:} {Tab grootte:}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Line up keywords in multi-line queries} {Sleutelwoorden intelligent uitlijnen bij meerregelige queries}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Ident contents of parenthesis block} {Inhoud van parentese-blok ('(', ')') laten inspringen}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Ident parenthesis block in new line} {Parentese-blok ('(', ')') op nieuwe regel laten inspringen}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Before opening parenthesis in column definitions} {Voor openings-parentese '(' in kolomdefinities}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After opening parenthesis in column definitions} {Na openings-parentese '(' in kolomdefinities}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Before closinging parenthesis in column definitions} {Voor sluitende parentese ')' in kolomdefinities}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After closinging parenthesis in column definitions} {Na sluitende parentese ')' in kolomdefinities}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Before opening parenthesis in expressions} {Voor openings-parentese '(' in expressies}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After opening parenthesis in expressions} {Na openings-parentese '(' in expressies}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Before closinging parenthesis in expressions} {Voor sluitende parentesen ')' in expressies}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After closinging parenthesis in expressions} {Na sluitende parentese ')' in expressies}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After comma} {Na komma}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After comma in function arguments list} {Na komma in lijst van functieargumenten}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After logical block of query} {Na logisch query-blok}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After semicolon} {Na puntkomma}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Never before semicolon} {Nooit voor puntkomma}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Before comma in lists} {Voor komma in lijsten}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After comma in lists} {Na komma in lijsten}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Before opening parenthesis} {Voor openings-parentese '('}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After opening parenthesis} {Na openings-parentese '('}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Before closing parenthesis} {Voor sluitende parentese ')'}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After closing parenthesis} {Na sluitende parentese ')'}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Before dot operator (in path to database object)} {Voor punt-operator (.) (in pad naar database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After dot operator (in path to database object)} {Na punt-operator (.) (in pad naar database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Before mathematical operator} {Voor mathematische operator}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {After mathematical operator} {Na mathematische operator}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Uppercase keywords} {Sleutelwoorden capitalizeren}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Uppercase datatype names} {Datatype namen capitalizeren}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Always use name wrapping} {'Naamomwikkeling' altijd toepassen}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Preferred name wrapper} {Gewenste 'naamomwikkelaar'}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Expand one line comments (/* ... */) to multiline} {Enkelregelig commentaar (/* ... */) converteren naar meerregelig}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Indent multi line comments} {Meerregelig commentaar laten inspringen}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset nl {Use "*" character for each line} {Gebruik "*" karakter voor elke regel}

### File: ../src/plugins/import/csv.tcl
mcset nl {, (comma)} {, (komma)}

### File: ../src/plugins/import/csv.tcl
mcset nl {; (semicolon)} {; (puntkomma)}

### File: ../src/plugins/import/csv.tcl
mcset nl {\t (tab)} {\t (tab)}

### File: ../src/plugins/import/csv.tcl
mcset nl {  (white-space)} {  (white-space)}

### File: ../src/plugins/import/csv.tcl
mcset nl Custom Aangepast

### File: ../src/plugins/import/csv.tcl
mcset nl {Input file} {Input file}

### File: ../src/plugins/import/csv.tcl
mcset nl Browse Bladeren

### File: ../src/plugins/import/csv.tcl
mcset nl {Show options} {Show options}

### File: ../src/plugins/import/csv.tcl
mcset nl {Column names} {Column names}

### File: ../src/plugins/import/csv.tcl
mcset nl {Treat first row as column names} {Treat first row as column names}

### File: ../src/plugins/import/csv.tcl
mcset nl {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.} {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.}

### File: ../src/plugins/import/csv.tcl
mcset nl {Columns separator:} {Kolom scheidingsteken:}

### File: ../src/plugins/import/csv.tcl
mcset nl {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.} {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.}

### File: ../src/plugins/import/csv.tcl
mcset nl {NULL handling} {NULL handling}

### File: ../src/plugins/import/csv.tcl
mcset nl {Treat following values as NULL:} {Treat following values as NULL:}

### File: ../src/plugins/import/csv.tcl
mcset nl Workarounds Workarounds

### File: ../src/plugins/import/csv.tcl
mcset nl {Expect Microsoft format of CSV} {Expect Microsoft format of CSV}

### File: ../src/plugins/import/csv.tcl
mcset nl {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.} {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.}

### File: ../src/plugins/import/csv.tcl
mcset nl Encoding Encoding

### File: ../src/plugins/import/csv.tcl
mcset nl {Convert from encoding:} {Convert from encoding:}

### File: ../src/plugins/import/csv.tcl
mcset nl {Input file cannot be empty.} {Input file cannot be empty.}

### File: ../src/plugins/import/csv.tcl
mcset nl {Input file is not readable.} {Input file is not readable.}

### File: ../src/plugins/import/csv.tcl
mcset nl {CSV separator cannot be empty.} {CSV scheidingteken mag niet leeg zijn.}

### File: ../src/plugins/import/csv.tcl
mcset nl {CSV files} {CSV files}

### File: ../src/plugins/import/csv.tcl
mcset nl {Text files} {Text files}

### File: ../src/plugins/import/csv.tcl
mcset nl {File to import from} {File to import from}

### File: ../src/plugins/import/dbf.tcl
mcset nl Auto-detect Auto-detect

### File: ../src/plugins/import/dbf.tcl
mcset nl {dBase files} {dBase files}

### File: ../src/plugins/import/regexp.tcl
mcset nl {Regular expression} {Regular expression}

### File: ../src/plugins/import/regexp.tcl
mcset nl {Visual editor} {Visual editor}

### File: ../src/plugins/import/regexp.tcl
mcset nl {Use Regular Expression Groups to identify columns.} {Use Regular Expression Groups to identify columns.}

### File: ../src/plugins/import/regexp.tcl
mcset nl {Case insensitive} {Case insensitive}

### File: ../src/plugins/import/regexp.tcl
mcset nl Help Help

### File: ../src/plugins/import/regexp.tcl
mcset nl {RegExp error:
%s} {RegExp error:
%s}

### File: ../src/plugins/export/xls.tcl
mcset nl {Column names as first row} {Kolomnamen als eerste rij}

### File: ../src/plugins/export/xls.tcl
mcset nl {If enabled, then first row of exported document will be a list of column names.} {If enabled, then first row of exported document will be a list of column names.}

### File: ../src/plugins/export/xls.tcl
mcset nl Encoding: Encoding:

### File: ../src/plugins/export/plain.tcl
mcset nl {Export NULL values as:} {Exporteer NULL waarden als:}

### File: ../src/plugins/export/plain.tcl
mcset nl {Fixed column width:} {Fixed column width:}

### File: ../src/plugins/export/plain.tcl
mcset nl {Database: %s (%s, %s)} {Database: %s (%s, %s)}

### File: ../src/plugins/export/plain.tcl
mcset nl {Table: %s} {Tabel: %s}

### File: ../src/plugins/export/plain.tcl
mcset nl {Index: %s} {Index: %s}

### File: ../src/plugins/export/plain.tcl
mcset nl {Trigger: %s} {Trigger: %s}

### File: ../src/plugins/export/plain.tcl
mcset nl {View: %s} {View: %s}

### File: ../src/plugins/export/csv.tcl
mcset nl {If enabled, then first row of exported CSV will be a list of column names.} {If enabled, then first row of exported CSV will be a list of column names.}

### File: ../src/plugins/export/csv.tcl
mcset nl {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.} {Karakter dat gebruikt wordt om een kolom van een
andere te scheiden. Indien het scheidingsteken binnen een kolomwaarde voorkomt,
wordt deze omsloten door quote karakters.
Alle quote karakters in een kolomwaarde wordt vervangen door twee quote karakters.}

### File: ../src/plugins/export/json.tcl
mcset nl {Indented lines} {Indented lines}

### File: ../src/plugins/export/json.tcl
mcset nl {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.} {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.}

### File: ../src/plugins/export/json.tcl
mcset nl {Align lines} {Align lines}

### File: ../src/plugins/export/json.tcl
mcset nl {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.} {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.}

### File: ../src/plugins/export/json.tcl
mcset nl {Each row as object} {Each row as object}

### File: ../src/plugins/export/json.tcl
mcset nl {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.} {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.}

### File: ../src/plugins/export/xml.tcl
mcset nl {No extra white-spaces or new lines} {Geen extra witruimte of nieuwe regels}

### File: ../src/plugins/export/xml.tcl
mcset nl {XML tags will be places char-by-char, without any extra white-spaces.} {XML tags zullen karakter-voor-karakter worden geplaatst, zonder extra witruimte.}

### File: ../src/plugins/export/xml.tcl
mcset nl {Format output to be human readable} {Formatteer resultaat in menselijk leesbare vorm}

### File: ../src/plugins/export/xml.tcl
mcset nl {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.} {Elke tag wordt op een nieuwe regel geplaatst en het hele document
wordt uitgelijnd om beter leesbaar te zijn in een text editor.}

### File: ../src/plugins/export/xml.tcl
mcset nl {Generate XSD file} {Genereer XSD bestand}

### File: ../src/plugins/export/xml.tcl
mcset nl {Generates XML Schema Definition file using
export file name and extension *.xsd.} {Genereert het XML Schema Definitie bestand gebruikmakend van de
export bestandsnaam en de extensie *.xsd.}

### File: ../src/plugins/export/xml.tcl
mcset nl {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s} {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s}

### File: ../src/plugins/export/html.tcl
mcset nl {First row of exported data will be header
with names of columns, just like in results grid.} {Eerste rij van de geexporteerde gegevens zal bestaan uit
namen van de kolommen, net als in het resultaat grid.}

### File: ../src/plugins/export/html.tcl
mcset nl {Row numbers as first column} {Rijnummers als eerste kolom}

### File: ../src/plugins/export/html.tcl
mcset nl {First column of exported data
will contain row order number.} {First column of exported data
will contain row order number.}

### File: ../src/plugins/export/html.tcl
mcset nl {Full column names} {Volledige kolomnamen}

### File: ../src/plugins/export/html.tcl
mcset nl {Column names in header will be prepended with "table_name." prefix.} {Column names in header will be prepended with "table_name." prefix.}

### File: ../src/plugins/export/html.tcl
mcset nl {Show types} {Typen tonen}

### File: ../src/plugins/export/html.tcl
mcset nl {Column headers will contain data types.} {Kolomheaders bevatten data typen.}

### File: ../src/plugins/export/html.tcl
mcset nl {no type} {geen type}

### File: ../src/plugins/export/html.tcl
mcset nl {For table:} {Voor tabel:}

### File: ../src/plugins/export/html.tcl
mcset nl Unique: Uniek:

### File: ../src/plugins/export/html.tcl
mcset nl Yes Ja

### File: ../src/plugins/export/html.tcl
mcset nl No Nee

### File: ../src/plugins/export/html.tcl
mcset nl Column Kolom

### File: ../src/plugins/export/html.tcl
mcset nl Collating Collationneren

### File: ../src/plugins/export/html.tcl
mcset nl {Sort order} Sorteervolgorde

### File: ../src/plugins/export/html.tcl
mcset nl Activated: Geactiveerd:

### File: ../src/plugins/export/html.tcl
mcset nl Action: Actie:

### File: ../src/plugins/export/html.tcl
mcset nl {Activate condition:} Activatie-conditie:

### File: ../src/plugins/export/html.tcl
mcset nl {Code executed:} {Code uitgevoerd:}

### File: ../src/plugins/export/html.tcl
mcset nl {Exported database: %s} {Geexporteerde database: %s}

### File: ../src/plugins/export/html.tcl
mcset nl {Generated on %s with %s} {Genenereerd op %s met %s}

### File: ../src/plugins/export/html.tcl
mcset nl {Exported table: %s} {Geexporteerde tabel: %s}

### File: ../src/plugins/export/html.tcl
mcset nl {Results of SQL query} {Resultaten van SQL-query}

### File: ../src/plugins/export/dbf.tcl
mcset nl {Cannot overwrite file '%s'.} {Cannot overwrite file '%s'.}

### File: ../src/plugins/export/sql.tcl
mcset nl {Name of table for exported data:} {Naam van de tabel voor geëxporteerde gegevens:}

### File: ../src/plugins/export/sql.tcl
mcset nl {Include "CREATE TABLE" statement at the begining.} {"CREATE TABLE" statement invoegen aan het begin.}

### File: ../src/plugins/export/sql.tcl
mcset nl {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.} {Query resultaten die geexporteerd worden naar SQL INSERTs moeten gedefinieerd
worden voor een tabel. Het is de naam van deze tabel.}

### File: ../src/plugins/export/sql.tcl
mcset nl {Include table declaration} {Tabeldeclaratie invoegen}

### File: ../src/plugins/export/sql.tcl
mcset nl {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.} {Indien ingeschakeld zal de tabel DDL (CREATE TABLE)
worden toegevoegd aan de geexporteerde SQL.}

### File: ../src/plugins/export/sql.tcl
mcset nl {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.} {U dient een tabelnaam te configureren om query resultaten te kunnen exporteren naar SQL.
SQL INSERTs vereisen een tabel in de syntax.}

### File: ../src/plugins/export/pdf.tcl
mcset nl Dimensions Dimensions

### File: ../src/plugins/export/pdf.tcl
mcset nl {Paper size:} {Paper size:}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Margin size:} {Margin size:}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Cell padding:} {Cell padding:}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Limit amount of data bytes in single cell to:} {Limit amount of data bytes in single cell to:}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Font size:} {Font size:}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Built-in font} {Built-in font}

### File: ../src/plugins/export/pdf.tcl
mcset nl Font: Font:

### File: ../src/plugins/export/pdf.tcl
mcset nl {TrueType font} {TrueType font}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Font file:} {Font file:}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Font encoding:} {Font encoding:}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Columns and rows} {Columns and rows}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Header background} {Header background}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Empty space} {Empty space}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Fill empty space in cells} {Fill empty space in cells}

### File: ../src/plugins/export/pdf.tcl
mcset nl {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.} {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Minimum height of empty space to fill:} {Minimum height of empty space to fill:}

### File: ../src/plugins/export/pdf.tcl
mcset nl {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.} {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Empty space background} {Empty space background}

### File: ../src/plugins/export/pdf.tcl
mcset nl {TTF Fonts} {TTF Fonts}

### File: ../src/plugins/export/pdf.tcl
mcset nl {All Files} {All Files}

### File: ../src/plugins/export/pdf.tcl
mcset nl {Open TTF font} {Open TTF font}

### File: ../src/plugins/populating/random.tcl
mcset nl {Include alpha characters} {Alpha-numerieke karakters gebruiken}

### File: ../src/plugins/populating/random.tcl
mcset nl {Include numeric characters} {Numerieke karakters gebruiken}

### File: ../src/plugins/populating/random.tcl
mcset nl {Include whitespace characters} {Whitespace karakters gebruiken}

### File: ../src/plugins/populating/random.tcl
mcset nl {Include binary characters} {Binaire karakters gebruiken}

### File: ../src/plugins/populating/random.tcl
mcset nl {Minimum length:} {Minimum lengte:}

### File: ../src/plugins/populating/random.tcl
mcset nl {Maximum length:} {Maximum lengte:}

### File: ../src/plugins/populating/random_number.tcl
mcset nl {Minimum value:} {Minimum waarde:}

### File: ../src/plugins/populating/random_number.tcl
mcset nl {Maximum value:} {Maximum waarde:}

### File: ../src/plugins/populating/random_number.tcl
mcset nl {Constant prefix:} {Constant voorvoegsel:}

### File: ../src/plugins/populating/random_number.tcl
mcset nl {Constant suffix:} {Constant achtervoegsel:}

### File: ../src/plugins/populating/sql.tcl
mcset nl {Initialisation code} {Initialisation code}

### File: ../src/plugins/populating/sql.tcl
mcset nl {Per iteration code} {Per iteration code}

### File: ../src/plugins/populating/sql.tcl
mcset nl {Closing code} {Closing code}

### File: ../src/plugins/populating/constant.tcl
mcset nl {Value to use:} {Waarde om te gebruiken:}

### File: ../src/plugins/populating/sequence.tcl
mcset nl {Start from:} {Starten bij:}

### File: ../src/plugins/populating/dictionary.tcl
mcset nl {Dictionary file:} {Woordenboek bestand:}

### File: ../src/plugins/populating/dictionary.tcl
mcset nl {Dictionary words separator:} {Woordenboek woord-scheidingsteken:}

### File: ../src/plugins/populating/dictionary.tcl
mcset nl Whitespace Witruimte

### File: ../src/plugins/populating/dictionary.tcl
mcset nl {Line break} Regeleinde

### File: ../src/plugins/populating/dictionary.tcl
mcset nl {Method of using words:} {Methode van woordgebruik:}

### File: ../src/plugins/populating/dictionary.tcl
mcset nl Randomly Willekeurig

### File: ../src/plugins/populating/dictionary.tcl
mcset nl Consecutively Aaneengesloten

### File: ../src/plugins/populating/dictionary.tcl
mcset nl {Dictionary file doesn't exist, or unreadable.} {Woordenboek bestaat niet of is onleesbaar.}

### File: ../src/plugins/populating/dictionary.tcl
mcset nl {Dictionary file is empty!} {Woordenboek is leeg!}

### File: ../src/plugins/populating/dictionary.tcl
mcset nl {Dictionary file} {Woordenboek bestand}

### File: ../src/taskbar.tcl
mcset nl Database: Database:

### File: ../src/taskbar.tcl
mcset nl Table: Tabel:

### File: ../src/taskbar.tcl
mcset nl {Type new name for a window} {Type een nieuwe naam voor het venster}

### File: ../src/taskbar.tcl
mcset nl {Window with given name already exists. Please type other name.} {Window with given name already exists. Please type other name.}

### File: ../src/taskbar.tcl
mcset nl {Type new name for a task} {Geef een nieuwe naam voor een taak}

### File: ../src/taskbar.tcl
mcset nl {Close selected window} {Sluit geselecteerd venster}

### File: ../src/taskbar.tcl
mcset nl {Close other windows} {Sluit andere vensters}

### File: ../src/taskbar.tcl
mcset nl {Close all windows} {Sluit alle vensters}

### File: ../src/taskbar.tcl
mcset nl {Restore last closed window} {Restore last closed window}

### File: ../src/taskbar.tcl
mcset nl {Rename selected window} {Hernoem geselecteerd venster}

### File: ../src/windows/table_win.tcl
mcset nl Structure Structuur

### File: ../src/windows/table_win.tcl
mcset nl Data Data

### File: ../src/windows/table_win.tcl
mcset nl Constraints Constraints

### File: ../src/windows/table_win.tcl
mcset nl Indexes Indexen

### File: ../src/windows/table_win.tcl
mcset nl Triggers Triggers

### File: ../src/windows/table_win.tcl
mcset nl {Grid view} Gridweergave

### File: ../src/windows/table_win.tcl
mcset nl {Form view} Formulierweergave

### File: ../src/windows/table_win.tcl
mcset nl {Refresh table columns and DDL (%s)} {Tabelkolommen en DDL verversen (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Edit table (%s)} {Bewerk tabel (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Export table data (%s)} {Exporteer tabelgegevens (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Import data to table (%s)} {Import data to table (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Populate table (%s)} {Vul tabel (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Create similar table} {Gelijkwaardige tabel maken}

### File: ../src/windows/table_win.tcl
mcset nl {Refresh table data (%s)} {Ververs tabelgegevens (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Add custom number of rows} {Add custom number of rows}

### File: ../src/windows/table_win.tcl
mcset nl {Add new row (%s)} {Nieuwe rij toevoegen (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Delete selected row (%s)} {Verwijder geselecteerde rij (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Commit changes (%s)} {Commit changes (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Rollback new row (%s)} {Rollback nieuwe rij (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {First %s rows} {Eerste %s rijen}

### File: ../src/windows/table_win.tcl
mcset nl {Previous %s rows} {Vorige %s rijen}

### File: ../src/windows/table_win.tcl
mcset nl {Next %s rows} {Volgende %s rijen}

### File: ../src/windows/table_win.tcl
mcset nl {Last %s rows} {Laatste %s rijen}

### File: ../src/windows/table_win.tcl
mcset nl {Export table data} {Exporteer tabelgegevens}

### File: ../src/windows/table_win.tcl
mcset nl {Import data to table} {Import data to table}

### File: ../src/windows/table_win.tcl
mcset nl {Populate table} {Tabel vullen}

### File: ../src/windows/table_win.tcl
mcset nl {Enter phrase you want to look for} {Geef tekenreeks die u wilt zoeken}

### File: ../src/windows/table_win.tcl
mcset nl {Apply data filter} {Gegevensfilter toepassen}

### File: ../src/windows/table_win.tcl
mcset nl {Clear data filter} {Gegevensfilter wissen}

### File: ../src/windows/table_win.tcl
mcset nl {Total rows: %s} {Totaal: %s rijen}

### File: ../src/windows/table_win.tcl
mcset nl {Rollback changes (%s)} {Wijzigingen terugdraaien (Rollback) (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {First row from data grid (%s)} {Eerste rij van het datagrid (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Previous row from data grid (%s)} {Vorige rij van het datagrid (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Next row from data grid (%s)} {Volgende rij van het datagrid (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Last row from data grid (%s)} {Laatste rij van het datagrid (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Field switching mode.

Click it to make <Tab> key to insert tab characters.} {Veld schakelmodus.

Klik hier om de <Tab> toets tab karakters te laten invoegen.}

### File: ../src/windows/table_win.tcl
mcset nl {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.} {Tab toevoegingsmode.

Klik hier om de <Tab> toets te laten schakelen tussen formulier edit velden.}

### File: ../src/windows/table_win.tcl
mcset nl {Refresh table indexes (%s)} {Tabelindexen verversen (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Create new index (%s)} {Nieuwe index toevoegen (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Edit index (%s)} {Bewerk index (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Delete index (%s)} {Verwijder index (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Refresh table triggers (%s)} {Triggers tabel verversen (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Create new trigger (%s)} {Nieuwe trigger creeren (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Edit trigger (%s)} {Bewerk trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Delete trigger (%s)} {Verwijder trigger (%s)}

### File: ../src/windows/table_win.tcl
mcset nl {Constraint name} {Constraint naam}

### File: ../src/windows/table_win.tcl
mcset nl {Column name} Kolomnaam

### File: ../src/windows/table_win.tcl
mcset nl Default Standaard

### File: ../src/windows/table_win.tcl
mcset nl {Not NULL} {Niet NULL}

### File: ../src/windows/table_win.tcl
mcset nl {Primary key} {Primary key}

### File: ../src/windows/table_win.tcl
mcset nl Unique Uniek

### File: ../src/windows/table_win.tcl
mcset nl Collate Collationneren

### File: ../src/windows/table_win.tcl
mcset nl Check Controle

### File: ../src/windows/table_win.tcl
mcset nl {Foreign key} {Vreemde sleutel}

### File: ../src/windows/table_win.tcl
mcset nl {Index name} {Index naam}

### File: ../src/windows/table_win.tcl
mcset nl {On column} {Op kolom}

### File: ../src/windows/table_win.tcl
mcset nl {SQL code} {SQL code}

### File: ../src/windows/table_win.tcl
mcset nl {Trigger name} {Trigger naam}

### File: ../src/windows/table_win.tcl
mcset nl {On table} {Op tabel}

### File: ../src/windows/table_win.tcl
mcset nl Name Naam

### File: ../src/windows/table_win.tcl
mcset nl {Data type} {Data type}

### File: ../src/windows/table_win.tcl
mcset nl {Default value} Standaardwaarde

### File: ../src/windows/table_win.tcl
mcset nl {Refreshing dependencies} {Afhankelijkheden verversen}

### File: ../src/windows/table_win.tcl
mcset nl {Refreshing table columns...} {Tabelkolommen verversen...}

### File: ../src/windows/table_win.tcl
mcset nl {Refreshing table data...} {Tabelgegevens verversen...}

### File: ../src/windows/table_win.tcl
mcset nl {Refreshing table indexes...} {Tabel indexen verversen...}

### File: ../src/windows/table_win.tcl
mcset nl {Refreshing table triggers...} {Tabel triggers verversen...}

### File: ../src/windows/table_win.tcl
mcset nl {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.} {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.}

### File: ../src/windows/table_win.tcl
mcset nl {Check condition} {Check conditie}

### File: ../src/windows/table_win.tcl
mcset nl {Total rows: %s (filtered)} {Total: %s rijen (gefilterd)}

### File: ../src/windows/table_win.tcl
mcset nl {Pending commits} {Wachtende commits}

### File: ../src/windows/table_win.tcl
mcset nl {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?} {Er zijn niet doorgevoerde wijzigingen.
Het herladen van de gegevens zal de wijzigingen verloren laten gaan.
Weet u zeker dat u wilt doorgaan?}

### File: ../src/windows/table_win.tcl
mcset nl {Loading data...} {Gegevens laden...}

### File: ../src/windows/table_win.tcl
mcset nl {Loading table '%s'...} {Tabel '%s' laden...}

### File: ../src/windows/table_win.tcl
mcset nl {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.} {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.}

### File: ../src/windows/table_win.tcl
mcset nl {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.} {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.}

### File: ../src/windows/table_win.tcl
mcset nl {Edit table} {Bewerk tabel}

### File: ../src/windows/table_win.tcl
mcset nl {Enter number of rows to add:} {Enter number of rows to add:}

### File: ../src/windows/table_win.tcl
mcset nl {Add rows} {Add rows}

### File: ../src/windows/table_win.tcl
mcset nl {New index} {Nieuwe index}

### File: ../src/windows/table_win.tcl
mcset nl {Index '%s' has no DDL. Probably it's system index and should not be edited.} {Index '%s' has no DDL. Probably it's system index and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset nl {Edit index} {Bewerk index}

### File: ../src/windows/table_win.tcl
mcset nl {Delete index} {Verwijder index}

### File: ../src/windows/table_win.tcl
mcset nl {Are you sure you want to delete '%s' index?} {Weet u zeker dat u index '%s' wilt verwijderen?}

### File: ../src/windows/table_win.tcl
mcset nl {New trigger} {Nieuwe trigger}

### File: ../src/windows/table_win.tcl
mcset nl {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.} {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset nl {Edit trigger} {Bewerk trigger}

### File: ../src/windows/table_win.tcl
mcset nl {Delete trigger} {Verwijder trigger}

### File: ../src/windows/table_win.tcl
mcset nl {Are you sure you want to delete '%s' trigger?} {Weet u zeker dat u trigger '%s' wilt verwijderen?}

### File: ../src/windows/table_win.tcl
mcset nl {Export table} {Tabel exporteren}

### File: ../src/windows/table_win.tcl
mcset nl {Import data} {Import data}

### File: ../src/windows/editor_win.tcl
mcset nl {SQL query} {SQL query}

### File: ../src/windows/editor_win.tcl
mcset nl Results Resultaten

### File: ../src/windows/editor_win.tcl
mcset nl History Geschiedenis

### File: ../src/windows/editor_win.tcl
mcset nl {Execute query (%s)} {Query uitvoeren (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Execute query with plain string results} {Voer query uit met plain-text resultaat}

### File: ../src/windows/editor_win.tcl
mcset nl {Explain query (%s)} {Query uitleggen (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Format SQL code (%s)} {SQL code formatteren (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Refresh syntax highlighting (%s)} {Syntax highlighting verversen(%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Clear history} {Geschiedenis wissen}

### File: ../src/windows/editor_win.tcl
mcset nl {Export results} {Exporteer resultaten}

### File: ../src/windows/editor_win.tcl
mcset nl {Create view from query} {View genereren met gegeven query}

### File: ../src/windows/editor_win.tcl
mcset nl {Execute SQL from file (%s)} {SQL uitvoeren vanaf bestand (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Load SQL from file (%s)} {SQL vanuit bestand laden (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Save SQL to file (%s)} {SQL naar bestand exporteren (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Default database for SQL executing
(%s/%s)} {Standaard database voor SQL uitvoer
(%s/%s)}

### File: ../src/windows/editor_win.tcl
mcset nl Database Database

### File: ../src/windows/editor_win.tcl
mcset nl {Execution date} Uitvoerdatum

### File: ../src/windows/editor_win.tcl
mcset nl {Execution time (s)} {Uitvoertijd (s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Rows affected} {Getroffen rijen}

### File: ../src/windows/editor_win.tcl
mcset nl SQL SQL

### File: ../src/windows/editor_win.tcl
mcset nl {Plain text view} {Plain-text weergave}

### File: ../src/windows/editor_win.tcl
mcset nl {Refresh results (%s)} {Ververs resultaten (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Commit row (%s)} {Commit row (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Rollback row (%s)} {Rollback row (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Copy (%s)} {Kopieren (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Cut (%s)} {Knippen (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Paste (%s)} {Plakken (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Show line numbers} {Toon regelnummers}

### File: ../src/windows/editor_win.tcl
mcset nl {Delete selected history entry (%s)} {Delete selected history entry (%s)}

### File: ../src/windows/editor_win.tcl
mcset nl {Choose the database first.} {Kies de database eerst.}

### File: ../src/windows/editor_win.tcl
mcset nl {Error while trying to collect completion list: %s} {Fout tijdens verzamelen van de aanvullingslijst: %s}

### File: ../src/windows/editor_win.tcl
mcset nl {Can't open %s file for reading.} {Kan bestand %s niet openen om te lezen.}

### File: ../src/windows/editor_win.tcl
mcset nl {Can't open %s file for writting.} {Kan bestand %s niet openen voor schrijven.}

### File: ../src/windows/editor_win.tcl
mcset nl {SQL code saved in %s.} {SQL code opgeslagen in %s.}

### File: ../src/windows/editor_win.tcl
mcset nl {Are you sure you want to clear queries history?} {Weet u zeker dat u de query geschiedenis wilt wissen?}

### File: ../src/windows/editor_win.tcl
mcset nl {Delete the history entry} {Delete the history entry}

### File: ../src/windows/editor_win.tcl
mcset nl {Are you sure you want to delete selected queries history entry?} {Are you sure you want to delete selected queries history entry?}

### File: ../src/windows/editor_win.tcl
mcset nl Processing... Bezig...

### File: ../src/windows/editor_win.tcl
mcset nl {Processing query...} {Query uitvoeren...}

### File: ../src/windows/editor_win.tcl
mcset nl {No results to export.} {Geen exporteerbaar resultaat.}

### File: ../src/windows/editor_win.tcl
mcset nl {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.} {Gebruikmaken van ATTACH vanuit SQL editor is niet toegestaan. Registreer in plaats daarvan de database die u wilt koppelen in SQLiteStudio en gebruik de zichtbare naam in de lijst voor SQL statements die u gebruikt of nodig hebt. Deze zullen automatisch weer worden gekoppeld bij een verzoek.}

### File: ../src/windows/editor_win.tcl
mcset nl {Query execution...} {Query uitvoer...}

### File: ../src/windows/editor_win.tcl
mcset nl {Executing SQL query...} {SQL query uitvoeren...}

### File: ../src/windows/editor_win.tcl
mcset nl {Error while executing query: %s} {Fout tijdens uitvoeren query: %s}

### File: ../src/windows/editor_win.tcl
mcset nl {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s} {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s}

### File: ../src/windows/editor_win.tcl
mcset nl {%s row(s) read in %s second(s).} {%s row(s) read in %s second(s).}

### File: ../src/windows/editor_win.tcl
mcset nl {%s row(s) affected in %s second(s).} {%s rijen(s) getroffen in %s second(en).}

### File: ../src/windows/editor_win.tcl
mcset nl {No SELECT statements found in editor or in selected part of SQL code.} {No SELECT statements found in editor or in selected part of SQL code.}

### File: ../src/windows/editor_win.tcl
mcset nl {More than one SELECT statements found. Please select the one you're interested in and then try again.} {More than one SELECT statements found. Please select the one you're interested in and then try again.}

### File: ../src/windows/editor_win.tcl
mcset nl {New view} {Nieuwe view}

### File: ../src/windows/editor_win.tcl
mcset nl {Fill query parameters} {Vul query parameters}

### File: ../src/error.tcl
mcset nl {Background error} {Fout op de achtergrond}

### File: ../src/error.tcl
mcset nl Close Sluiten

### File: ../src/error.tcl
mcset nl {Report the bug} {Rapporteer de bug}

### File: ../src/dialogs/about_dialog.tcl
mcset nl About Over

### File: ../src/dialogs/about_dialog.tcl
mcset nl {Packages and plugins} {Packages en plugins}

### File: ../src/dialogs/about_dialog.tcl
mcset nl Licence Licentie

### File: ../src/dialogs/about_dialog.tcl
mcset nl {Installed plugins:} {Geinstalleerde plugins:}

### File: ../src/dialogs/about_dialog.tcl
mcset nl {Used Tcl packages:} {Gebruikte Tcl packages:}

### File: ../src/dialogs/about_dialog.tcl
mcset nl {SQLite3 engine version: %s} {SQLite3 engine versie: %s}

### File: ../src/dialogs/searchdialog.tcl
mcset nl {Global expression understeands '*', '?' and \[chars].} {Globale expressie begrijpt '*', '?' and \[chars].}

### File: ../src/dialogs/searchdialog.tcl
mcset nl Find Vinden

### File: ../src/dialogs/searchdialog.tcl
mcset nl Replace Vervangen

### File: ../src/dialogs/searchdialog.tcl
mcset nl {Do you want to replace marked text?} {Wilt u de gemarkeerde tekst vervangen?}

### File: ../src/dialogs/searchdialog.tcl
mcset nl {Replace all} {Alles vervangen}

### File: ../src/dialogs/searchdialog.tcl
mcset nl {Replacing finished.} {Vervangen gereed.}

### File: ../src/dialogs/searchdialog.tcl
mcset nl {Cannot match the pattern!} {Geen overeenkomsten gevonden voor patroon!}

### File: ../src/dialogs/bind_param.tcl
mcset nl {Query number %s} {Query nummer %s}

### File: ../src/dialogs/bind_param.tcl
mcset nl {Parameter number %s (named: %s):} {Parameter nummer %s (naam: %s):}

### File: ../src/dialogs/bind_param.tcl
mcset nl {NULL value} {NULL value}

### File: ../src/dialogs/bind_param.tcl
mcset nl {You can use '%s' keyboard shortcut to switch NULL value.} {You can use '%s' keyboard shortcut to switch NULL value.}

### File: ../src/dialogs/bind_param.tcl
mcset nl {Copy value to other '%s' parameters (%s)} {Copy value to other '%s' parameters (%s)}

### File: ../src/dialogs/bind_param.tcl
mcset nl {By enabling this all parameters with same name
will also have same value as this one.} {By enabling this all parameters with same name
will also have same value as this one.}

### File: ../src/dialogs/bind_param.tcl
mcset nl {Execute query} {Query uitvoeren}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset nl Collation Collatie

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset nl Sort Sorteren

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset nl {Named constraint:} {Benoemde constraint:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset nl {On conflict:} {On conflict:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset nl {Constraint is marked as being named, but there's no name filled in.} {Constraint is gemarkeerd als benoemd, maar er is geen naam ingevuld.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset nl {Collation for column '%s' is enabled, but there's no collation name filled in.} {Collatie voor kolom '%s' is ingeschakeld, maar er is geen collatie-naam ingevuld.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset nl {No columns are selected.} {Geen kolommen geselecteerd.}

### File: ../src/dialogs/populate_table.tcl
mcset nl {Number of rows to insert:} {Aantal in te voegen rijen:}

### File: ../src/dialogs/populate_table.tcl
mcset nl {On a constraint violation:} {On a constraint violation:}

### File: ../src/dialogs/populate_table.tcl
mcset nl Mode Mode

### File: ../src/dialogs/populate_table.tcl
mcset nl {Select table to display available columns} {Selecteer tabel om beschikbare kolommen te tonen}

### File: ../src/dialogs/populate_table.tcl
mcset nl Populate Bevolken

### File: ../src/dialogs/populate_table.tcl
mcset nl {Error occured while populating table:
%s} {Er is een fout opgetreden tijdens het bevolken van de tabel:
%s}

### File: ../src/dialogs/populate_table.tcl
mcset nl Configuration Configuratie

### File: ../src/dialogs/populate_table.tcl
mcset nl {You have to type valid number of rows to insert.} {U dient een geldig aantal in te voegen rijen op te geven.}

### File: ../src/dialogs/populate_table.tcl
mcset nl {You have to select at least one column to populate.} {U dient minimaal een kolom te selecteren voor bevolking.}

### File: ../src/dialogs/populate_table.tcl
mcset nl Populating... Bevolken...

### File: ../src/dialogs/populate_table.tcl
mcset nl {Populating table '%s'.} {Tabel '%s' bevolken.}

### File: ../src/dialogs/populate_table.tcl
mcset nl Stop Stop

### File: ../src/dialogs/table_dialog_fk.tcl
mcset nl {Foreign table:} {Externe|vreemde tabel:}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset nl {Local column} {Lokale kolom}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset nl {Foreign column} {Externe|vreemde kolom}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset nl Reactions Reacties

### File: ../src/dialogs/table_dialog_fk.tcl
mcset nl {ON UPDATE} {ON UPDATE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset nl {ON DELETE} {ON DELETE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset nl MATCH MATCH

### File: ../src/dialogs/table_dialog_fk.tcl
mcset nl {Deferred foreign key} {Deferred foreign key}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset nl {No foreign table selected.} {Geen externe|vreemde tabel geselecteerd.}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset nl {There's no foreign column assigned for local column '%s'.} {Er is geen externe|vreemde kolom toegewezen voor lokale kolom '%s'.}

### File: ../src/dialogs/import_dialog.tcl
mcset nl {Import from:} {Import from:}

### File: ../src/dialogs/import_dialog.tcl
mcset nl {Import to:} {Import to:}

### File: ../src/dialogs/import_dialog.tcl
mcset nl Table Tabel

### File: ../src/dialogs/import_dialog.tcl
mcset nl Existing Existing

### File: ../src/dialogs/import_dialog.tcl
mcset nl {Create new table} {Create new table}

### File: ../src/dialogs/import_dialog.tcl
mcset nl Import Import

### File: ../src/dialogs/import_dialog.tcl
mcset nl {Import method is not selected.} {Import method is not selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset nl {You have to choose database.} {U dient een database te selecteren.}

### File: ../src/dialogs/import_dialog.tcl
mcset nl {No existing table is selected.} {No existing table is selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset nl {Table typed to create already exists. Please change table name.} {Table typed to create already exists. Please change table name.}

### File: ../src/dialogs/view_dialog.tcl
mcset nl View View

### File: ../src/dialogs/view_dialog.tcl
mcset nl {View name:} {View naam:}

### File: ../src/dialogs/view_dialog.tcl
mcset nl {Code executed to get view data:} {Uitgevoerde code om view data te verkrijgen:}

### File: ../src/dialogs/view_dialog.tcl
mcset nl Create Creeren

### File: ../src/dialogs/view_dialog.tcl
mcset nl Change Aanpassen

### File: ../src/dialogs/view_dialog.tcl
mcset nl {You have to specify database.} {U dient een database te specificeren.}

### File: ../src/dialogs/view_dialog.tcl
mcset nl {You have to specify view name.} {U moet een naam voor de view specificeren.}

### File: ../src/dialogs/view_dialog.tcl
mcset nl {You havn't wrote a code for the view.} {U heeft geen code geschreven voor de view.}

### File: ../src/dialogs/export_dialog.tcl
mcset nl {Export data} {Exporteer data}

### File: ../src/dialogs/export_dialog.tcl
mcset nl {Only structure, without data} {Enkel structuur, geen data}

### File: ../src/dialogs/export_dialog.tcl
mcset nl {Table or view} {Table or view}

### File: ../src/dialogs/export_dialog.tcl
mcset nl {Output file} Uitvoerbestand

### File: ../src/dialogs/export_dialog.tcl
mcset nl {Export format} Exportformaat

### File: ../src/dialogs/export_dialog.tcl
mcset nl Export Exporteren

### File: ../src/dialogs/export_dialog.tcl
mcset nl {You have to choose file.} {U dient een bestand te selecteren.}

### File: ../src/dialogs/export_dialog.tcl
mcset nl {Can't write to file: %s} {Kan niet naar bestand schrijven: %s}

### File: ../src/dialogs/export_dialog.tcl
mcset nl {You have to choose table.} {U dient een tabel te selecteren.}

### File: ../src/dialogs/export_dialog.tcl
mcset nl {Exporting database '%s'.} {Database '%s' exporteren.}

### File: ../src/dialogs/export_dialog.tcl
mcset nl {Exporting table '%s'.} {Tabel '%s' exporteren.}

### File: ../src/dialogs/export_dialog.tcl
mcset nl {Exporting view '%s'.} {Exporting view '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset nl {Exporting results.} {Resultaten exporteren.}

### File: ../src/dialogs/export_dialog.tcl
mcset nl Exporting... Exporteren...

### File: ../src/dialogs/export_dialog.tcl
mcset nl {Cannot write to file: %s
Please select other file.} {Kan niet naar bestand schrijven: %s
Selecteer aub een ander bestand.}

### File: ../src/dialogs/bug_report_login.tcl
mcset nl {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.} {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.}

### File: ../src/dialogs/bug_report_login.tcl
mcset nl Login: Login:

### File: ../src/dialogs/bug_report_login.tcl
mcset nl Password: Password:

### File: ../src/dialogs/bug_report_login.tcl
mcset nl Validate Validate

### File: ../src/dialogs/bug_report_login.tcl
mcset nl {Validation result} {Validation result}

### File: ../src/dialogs/bug_report_login.tcl
mcset nl {Not validated yet} {Not validated yet}

### File: ../src/dialogs/bug_report_login.tcl
mcset nl Validating... Validating...

### File: ../src/dialogs/bug_report_login.tcl
mcset nl {Validating login and password...} {Validating login and password...}

### File: ../src/dialogs/bug_report_login.tcl
mcset nl {Invalid login or password.} {Invalid login or password.}

### File: ../src/dialogs/bug_report_login.tcl
mcset nl {Login and password are correct.} {Login and password are correct.}

### File: ../src/dialogs/bug_report.tcl
mcset nl {Your e-mail address or user (both optional)} {Your e-mail address or user (both optional)}

### File: ../src/dialogs/bug_report.tcl
mcset nl or of

### File: ../src/dialogs/bug_report.tcl
mcset nl {Log in} {Log in}

### File: ../src/dialogs/bug_report.tcl
mcset nl {Logged in} {Logged in}

### File: ../src/dialogs/bug_report.tcl
mcset nl {Log out} {Log out}

### File: ../src/dialogs/bug_report.tcl
mcset nl {Brief description:} {Korte beschrijving:}

### File: ../src/dialogs/bug_report.tcl
mcset nl {How to reproduce problem (if possible):} {Stappen om het probleem te reproduceren (indien mogelijk):}

### File: ../src/dialogs/bug_report.tcl
mcset nl {What is the problem:} {Wat is het probleem:}

### File: ../src/dialogs/bug_report.tcl
mcset nl {Show more (optional)} {Show more (optional)}

### File: ../src/dialogs/bug_report.tcl
mcset nl {Operating system:} Besturingssysteem:

### File: ../src/dialogs/bug_report.tcl
mcset nl {Take screenshots of all SQLiteStudio windows and attach them} {Maak screenshots van alle SQLiteStudio vensters en voeg deze toe}

### File: ../src/dialogs/bug_report.tcl
mcset nl Send Verzenden

### File: ../src/dialogs/bug_report.tcl
mcset nl {Describe your feature request:} {Omschrijf uw 'feature request':}

### File: ../src/dialogs/bug_report.tcl
mcset nl Hide Hide

### File: ../src/dialogs/bug_report.tcl
mcset nl {Please fill 'Brief' field.} {Vul aub het 'Brief' veld in.}

### File: ../src/dialogs/bug_report.tcl
mcset nl {Please fill at least one of 'Description' or 'How to reproduce' fields.} {Vul aub een van de velden 'Description' of 'How to reproduce' in.}

### File: ../src/dialogs/bug_report.tcl
mcset nl {Please provide valid e-mail address or leave 'E-mail' empty.} {Please provide valid e-mail address or leave 'E-mail' empty.}

### File: ../src/dialogs/bug_report.tcl
mcset nl {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.} {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Database to convert:} {Database om te converteren:}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Converted database name:} {Geconverteerde database naam:}

### File: ../src/dialogs/db_convert.tcl
mcset nl {File to use for converted database:} {Bestand om te gebruiken voor geconverteerde database:}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Choose new file for database} {Kies nieuwe bestandsnaam voor database}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Database version:} {Database versie:}

### File: ../src/dialogs/db_convert.tcl
mcset nl Convert Converteren

### File: ../src/dialogs/db_convert.tcl
mcset nl {Convert database} {Database converteren}

### File: ../src/dialogs/db_convert.tcl
mcset nl {You chave to choose database to convert.} {U dient een te converteren database op te geven.}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Error resolving database with name %s!} {Fout bij bepalen van database met naam %s!}

### File: ../src/dialogs/db_convert.tcl
mcset nl {You have to specify new database file.} {U dient een nieuwe database bestandsnaam op te geven.}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Cannot use existing file for converted database.} {Kan bestaand bestand niet gebruiken voor geconverteerde database.}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Cannot use existing name for converted database.} {Kan bestaande naam niet gebruiken voor geconverteerde database.}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Cannot find handler for database labeled with: %s} {Kan geen handler vinden voor de database met label: %s}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Error while trying to create database: %s} {Fout tijdens aanmaken database: %s}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Database converting error} {Database conversiefout}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s} {Er waren problemen tijdens het converteren van de database, maar is geconverteerd met weglating van objecten die problemen gaven. Details:
%s}

### File: ../src/dialogs/db_convert.tcl
mcset nl {Choose file} {Kies bestand}

### File: ../src/dialogs/yesno.tcl
mcset nl Question Question

### File: ../src/dialogs/yesno.tcl
mcset nl Warning Waarschuwing

### File: ../src/dialogs/yesno.tcl
mcset nl Error Fout

### File: ../src/dialogs/yesno.tcl
mcset nl Information Informatie

### File: ../src/dialogs/import_db.tcl
mcset nl {Import from one of databases:} {Importeren uit een van de databases:}

### File: ../src/dialogs/import_db.tcl
mcset nl {Choose database file to import:} {Kies database bestand om te importeren:}

### File: ../src/dialogs/import_db.tcl
mcset nl {No database chosen.} {Geen database gekozen.}

### File: ../src/dialogs/import_db.tcl
mcset nl {Cannot open specified database.} {Kan gespecificeerde database niet openen.}

### File: ../src/dialogs/import_db.tcl
mcset nl {Error while importing database:
%s} {Fout tijdens importeren database:
%s}

### File: ../src/dialogs/import_db.tcl
mcset nl {Select file} {Selecteer bestand}

### File: ../src/dialogs/column_dialog.tcl
mcset nl Column: Kolom:

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Column constraints:} {Kolom beperkingen:}

### File: ../src/dialogs/column_dialog.tcl
mcset nl Add Toevoegen

### File: ../src/dialogs/column_dialog.tcl
mcset nl Size Grootte

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Maximal length of value in column.} {Maximale lengte van kolomwaarde.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Primary key configuration} {Primary key configuratie}

### File: ../src/dialogs/column_dialog.tcl
mcset nl Autoincrement Autoincrement

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Sort order:} Sorteervolgorde:

### File: ../src/dialogs/column_dialog.tcl
mcset nl {No foreign column selected.} {Geen externe|vreemde kolom geselecteerd.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Choose ON UPDATE action, or disable it.} {Kies ON UPDATE actie, of schakel deze uit.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Choose ON DELETE action, or disable it.} {Kies ON DELETE actie, of schakel deze uit.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Choose MATCH action, or disable it.} {Kies MATCH actie, of schakel deze uit.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Foreign key configuration} {Foreign Key configuratie}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Foreign column:} {Externe|vreemde kolom:}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Unique configuration} Uniciteitsconfiguratie

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Fill in the condition expression.} {Vul de conditie expressie in.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Check condition configuration} {Check conditie configuratie}

### File: ../src/dialogs/column_dialog.tcl
mcset nl Condition: Conditie:

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Not null configuration} {Niet null configuratie}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Fill in the collation name.} {Vul collatienaam in.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Collating configuration} {Collatie configuratie}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Collation name:} {Collatie naam:}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Fill in the default value.} {Vul de standaardwaarde in.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Default value configuration} {Standaarwaarde configuratie}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Default value:} Standaardwaarde:

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Use value as:} {Use value as:}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {A literal value} {A literal value}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {An expression} {An expression}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Column primary key is not configured correctly.} {Primary key van de kolom is incorrect geconfigureerd.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {AUTOINCREMENT is allowed only with INTEGER type of column.} {AUTOINCREMENT is allowed only with INTEGER type of column.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Column foreign key is not configured correctly.} {Foreign key van de kolom is incorrect geconfigureerd.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Column 'unique' constraint is not configured correctly.} {'unique' constraint van de kolom is incorrect geconfigureerd.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Column 'check' constraint is not configured correctly.} {'check' constraint van de kolom is incorrect geconfigureerd.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Column 'notnull' constraint is not configured correctly.} {'notnull' constraint van de kolom is incorrect geconfigureerd.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Column 'default' constraint is not configured correctly.} {'default' constraint van de kolom is incorrect geconfigureerd.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Column 'collate' constraint is not configured correctly.} {'collate' constraint van de kolom is incorrect geconfigureerd.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {No column name is specified.} {Er is geen kolomnaam gespecificeerd.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Column with name '%s' already exists in the table.} {Kolom met naam '%s' bestaat reeds in de tabel.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Data type bounds are given, but no data type name is specified.} {Datatype grenzen zijn gegeven, maar geen datatype naam is gegeven.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Data type precision is given, but no data type size is specified.} {Datatype precisie is gegeven, maar grootte van datatype is niet gegeven.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Data type size has invalid format. Only integer value is allowed.} {Datatype grootte heeft een ongeldig formaat. Alleen integer waarden zijn toegestaan.}

### File: ../src/dialogs/column_dialog.tcl
mcset nl {Data type precision has invalid format. Only integer value is allowed.} {Datatype precisie heeft een ongeldig formaat. Alleen integer waarden zijn toegestaan.}

### File: ../src/dialogs/assoc_dialog.tcl
mcset nl {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:} {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:}

### File: ../src/dialogs/assoc_dialog.tcl
mcset nl {Current associations} {Current associations}

### File: ../src/dialogs/assoc_dialog.tcl
mcset nl {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.} {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.}

### File: ../src/dialogs/db_edit.tcl
mcset nl {Database file:} {Database bestand:}

### File: ../src/dialogs/db_edit.tcl
mcset nl {Database name:} {Database naam:}

### File: ../src/dialogs/db_edit.tcl
mcset nl {Generate automatically} {Genereer automatisch}

### File: ../src/dialogs/db_edit.tcl
mcset nl {Type name in field below:} {Voer naam in onderstaand veld in:}

### File: ../src/dialogs/db_edit.tcl
mcset nl {Remember it permanently} {Onthoud permanent}

### File: ../src/dialogs/db_edit.tcl
mcset nl {If disabled, then the database will be registered only
for this single SQLiteStudio session.} {Indien uitgeschakeld, wordt de database enkel onthouden voor enkel
de huidige SQLiteStudio sessie.}

### File: ../src/dialogs/db_edit.tcl
mcset nl {Edit database} {Database bewerken}

### File: ../src/dialogs/db_edit.tcl
mcset nl {Add database} {Database toevoegen}

### File: ../src/dialogs/db_edit.tcl
mcset nl {File '%s' doesn't exist!} {File '%s' doesn't exist!}

### File: ../src/dialogs/db_edit.tcl
mcset nl {You have to specify database file.} {U dient een database bestand te specificeren.}

### File: ../src/dialogs/db_edit.tcl
mcset nl {Database named '%s' already exists on databases list. Please pick other name.} {Database named '%s' already exists on databases list. Please pick other name.}

### File: ../src/dialogs/db_edit.tcl
mcset nl {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.} {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.}

### File: ../src/dialogs/db_edit.tcl
mcset nl {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.} {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.}

### File: ../src/dialogs/db_edit.tcl
mcset nl {Type not existing file for new database} {Voer naam in voor niet bestaande database}

### File: ../src/dialogs/db_edit.tcl
mcset nl {Select existing database file} {Selecteer bestaand database bestand}

### File: ../src/dialogs/db_edit.tcl
mcset nl {%s is not supported database!} {%s is geen ondersteunde database!}

### File: ../src/dialogs/table_dialog_pk.tcl
mcset nl {Using autoincrement with more than one column at once is forbidden.} {Using autoincrement with more than one column at once is forbidden.}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl Previous Vorige

### File: ../src/dialogs/tips_dialog.tcl
mcset nl Next Volgende

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {Do not show this dialog at startup} {Dit dialoogvenster niet tonen na opstarten}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		} {
			Als u er niet van houdt meerdere SQL editors te openen, kunt u een enkele editor gebruiken,
			en daar grote stukken code in schrijve. Door markering kunt u alleen dat gedeelte van de SQL selecteren die u wilt uitvoeren,
			en op 'SQL uitvoeren' te drukken.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			You can configure all SQL editor syntax colors in settings.
		} {
			U kunt alle SQL editor syntax kleuren configureren in de instellingen.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		} {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		} {
			U kunt de Control+Spatie sneltoets (configureerbaar) gebruiken om woorden te completeren dat u in de SQL editor aan het typen bent.
			De aanvullings-engine is tevens in staat een gok te doen over het volgende woord binnen de SQL context en u een lijst te tonen met woorden binnen deze context.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		} {
			Er zijn verscheidene sneltoetsen (allemaal configureerbaar) beschikbaar die het werken met SQLiteStudio zo eenvoudig
			en zo snel mogelijk maken.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		} {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		} {
			Wanneer u uw SQLiteStudio applicatie sluit met nog openstaande MDI vensters, worden deze bij de volgende start hersteld (inclusief getypte code in editors),
			tenzij in de instellingen de optie "sessie onthouden" is uitgeschakeld.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		} {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		} {
			U kunt uw eigen SQL functies definieren die beschikbaar zijn in een database terwijl u deze bewerkt met SQLiteStudio.
			Dit kan u helpen functionaliteit te emuleren die mogelijk in de applicatie die gebruikmaakt van de database is geimplementeerd.<br>
			Om een nieuwe functie de implementeren, gaat u naar het 'Custom SQL functies' venster en voeg de functie daarin toe(klik op het icoon met het plusteken).
			Voeg vervolgens de naam van de functie toe en kies de taal waarin de functie is geschreven (Tcl of SQL).<br>
			Implementatie code kan tekens als $0, $1, $2 etc bevatten - dit zin positionele parameters die doorgegeven worden aan de functie bij aanroep.<br><br>
			Hier is een voorbeeld geimplementeerd in SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			Hier is een voorbeeld geimplementeerd in Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		} {
			Wanneer u wilt zoeken naar een woord in tabelgegevens, maar dit niet door middel van een SQL wilt doen, of u weet
			niet in welke kolom het woord in voorkomt, gaat u naar de gridweergave, typed het woord in het invoervak 'filter' en kiest voor "Filter toepassen".
			Dit zal alle instanties vinden waarin het woord voorkomt, zelfs die met voorvoegsels of achtervoegsels, in alle
			kolommen en tabelgegevens worden gefilterd om enkel deze resultaten weer te geven.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		} {
			U kunt waarden in de gridweergave bewerken, maar onthoudt dat kolommen die niet per definitie direct van een tabel afkomstig zijn (bijvoorbeeld als resultaat van mathematisch operaties op kolommen) - ook NIET bewerkt kunnen worden.
			Zulke onbewerkbare cellen worden tevens weggelaten indien gegevens in de gridweergave worden geplakt!
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		} {
			Wanneer u het ROWID van een specifieke rij (tupel) wilt weten, beweegt u simpelweg de muis over de pointer over de rij waarin u geinteresseerd bent.
			Een hulpballon met het ROWID (en overige informatie) zal dan voor de rij getoond worden.<br><br>
			In de gridweergave of het tabelvenster kunt u het ROWID in plaats van het 'normale' rijnummer tonen. Deze optie is beschikbaar vanuit het context-menu van de gridweergave.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		} {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		} {
			U kunt de resultaten van een SQL query beneden de query weergeven, in plaats van het switchen naar het volgende tabblad. Wissel hiervoor van SQL Editor layout in het Configuratievenster.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		} {
			U kunt altijd terug naar de queries die u reeds heeft uitgevoerd door naar het tablad Geschiedenis in het SQL Editor venster.<br><br>
			Het aantal te onthouden items is configureerbaar. Onthoudt echter dat de geschiedenis elke keer opnieuw ingelezen wordt wanneer u deze opent. Indien de waarde (te) hoog is, kan dat het inleesproces ernstig vertragen.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		} {
			Het SQL Editor venster kan u helpen bij het schrijven van queries - druk op Control+Spatie (of welke sneltoets hiervoor geconfigureerd is) in het venster om de auto-aanvullingslijst te openen.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		} {
			U kunt meerdere database namen gebruiken in queries zonder deze databases aan de huidige te hoeven koppelen.
			SQLiteStudio zal dit automatisch voor u realiseren.<br><br>
			Gebruik hiertoe databasenamen zoals deze in de databases tree links worden aangegeven. Een voorbeeld:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN andere_database.table2 t2 ON (t1.id = t2.id);
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		} {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset nl {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		} {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		}

### File: ../src/dialogs/import_table.tcl
mcset nl Separator: Scheidingsteken:

### File: ../src/dialogs/import_table.tcl
mcset nl {Common separator is \t (tab), but sometimes others can be met.} {Gemeenschappelijk scheidingsteken is \t (tab), maar soms kunnen anderen worden gevonden.}

### File: ../src/dialogs/import_table.tcl
mcset nl {Import data file for '%s' table:} {Importeer databestand voor tabel '%s':}

### File: ../src/dialogs/import_table.tcl
mcset nl {File '%s' isn't readable!} {Bestand '%s' is onleesbaar!}

### File: ../src/dialogs/import_table.tcl
mcset nl {Error while trying to copy data:
%s} {Fout tijdens kopieren van gegevens:
%s}

### File: ../src/dialogs/release_notes_dialog.tcl
mcset nl {Don't show this dialog after update.} {Don't show this dialog after update.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl Trigger Trigger

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {On action:} {Voor actie:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {Trigger name:} {Trigger naam:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl When: Indien:

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {On table:} {Voor tabel:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {Execute code for:} {Code uitvoeren voor:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.} {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {Execute code only when:} {Code alleen uitvoeren indien:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {Code executed for above configuration:} {Code uitvoeren voor bovenstaande configuratie:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {You have to specify view.} {U dient een view te specificeren.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {You have to specify table.} {U dient een tabel te specificeren.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {You have to specify trigger name.} {U dient een triggernaam te specificeren.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {You have to specify 'action' condition.} {U dient een 'actie' ('action') conditie te specificeren..}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {You havn't wrote a code for the trigger.} {U heeft geen code geschreven voor de trigger.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset nl {On view:} {Voor view:}

### File: ../src/dialogs/table_dialog.tcl
mcset nl Columns: Kolommen:

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Table constraints:} {Tabel constraints:}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Table name:} Tabelnaam:

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Add column} {Kolom toevoegen}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Edit selected} {Bewerk selectie}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Delete selected} {Verwijder selectie}

### File: ../src/dialogs/table_dialog.tcl
mcset nl Type Type

### File: ../src/dialogs/table_dialog.tcl
mcset nl Details Details

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.} {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Edit column} {Bewerk kolom}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Delete column} {Verwijder kolom}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Are you sure you want to delete column '%s'?} {Weet u zeker dat u kolom '%s' wilt verwijderen?}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Constraint change} {Constraint change}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Are you sure you want to change constraint type?
Current constraint configuration will be lost.} {Are you sure you want to change constraint type?
Current constraint configuration will be lost.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Table constraint number %s (%s) is not configured correctly.} {Table constraint number %s (%s) is not configured correctly.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {There's no column defined.} {Er is geen kolom gedefinieerd.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {There is already a table with name '%s'. Please change the name of this table.} {There is already a table with name '%s'. Please change the name of this table.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {There is already an index with name '%s'. Please change the name of this index.} {There is already an index with name '%s'. Please change the name of this index.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {There is already a trigger with name '%s'. Please change the name of this trigger.} {There is already a trigger with name '%s'. Please change the name of this trigger.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {There is already a view with name '%s'. Please change the name of this view.} {There is already a view with name '%s'. Please change the name of this view.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Kan DDL voor trigger '%s' niet bepalen,
dus kan deze ook niet creeren na modificatie van de tabel.
Wilt u echt doorgaan?}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Trigger parsing problem} {Probleem met bepalen van trigger}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Kan DDL voor index '%s' niet interpreteren,
dus kan deze niet recreeren na tabelmodificatie.
Wilt u doorgaan?}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Index parsing problem} {Index bepalingsprobleem}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {View parsing problem} {View parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.} {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {%s(%s) referencing %s(%s)} {%s(%s) referencing %s(%s)}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s} {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Do you want to continue anyway?} {Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?} {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Modifying table...} {Tabel aanpassen...}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Modifying table '%s'.} {Tabel '%s' aanpassen.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Could not recreate triggers for modified table.} {Kon triggers niet recreeren voor veranderde tabel.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Could not recreate indexes for modified table.} {Kon indexen niet recreeren voor veranderde tabel.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Could not recreate views for modified table.} {Could not recreate views for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?} {Het is noet mogelijk de trigger '%s' na modificatie van de tabel te recreeren.
Wilt u toch doorgaan?}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Trigger recreation problem} {Trigger recreatie probleem}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?} {Het is nmogelijk de index '%s' na tabelmodificatie te recreeren.
Wilt u toch doorgaan?}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Index recreation problem} {Index hercreatie probleem}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {Could not recreate foreign keys for tables referencing modified table.} {Could not recreate foreign keys for tables referencing modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {View recreation problem} {View recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset nl {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).} {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).}

### File: ../src/dialogs/table_dialog_chk.tcl
mcset nl {Condition expression cannot be empty.} {Conditie expressie kan niet leeg zijn.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset nl {What would you like to do?} {Wat wilt u doen?}

### File: ../src/dialogs/new_version_dialog.tcl
mcset nl {Install it automatically} {Automatisch installeren}

### File: ../src/dialogs/new_version_dialog.tcl
mcset nl {Go to download page} {Ga naar download pagina}

### File: ../src/dialogs/new_version_dialog.tcl
mcset nl {Package download} {Package download}

### File: ../src/dialogs/new_version_dialog.tcl
mcset nl {Insufficient privileges to perform automatic update.} {Insufficient privileges to perform automatic update.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset nl {Check for updates at startup} {Controleer op updates bij opstarten}

### File: ../src/dialogs/new_version_dialog.tcl
mcset nl {New version of SQLiteStudio is available: %s} {Er is een nieuwe versie van SQLiteStudio beschikbaar: %s}

### File: ../src/dialogs/trigger_dialog_cols.tcl
mcset nl {Trigger columns} {Trigger columns}

### File: ../src/dialogs/blob_edit.tcl
mcset nl Commit Commit

### File: ../src/dialogs/bug_history.tcl
mcset nl Clear Wissen

### File: ../src/dialogs/bug_history.tcl
mcset nl {Reported on} {Gerapporteerd op}

### File: ../src/dialogs/bug_history.tcl
mcset nl Brief Brief

### File: ../src/dialogs/bug_history.tcl
mcset nl URL URL

### File: ../src/dialogs/bug_history.tcl
mcset nl Discussion Discussie

### File: ../src/dialogs/bug_history.tcl
mcset nl {Clear reports} {Rapporten opschonen}

### File: ../src/dialogs/bug_history.tcl
mcset nl {Do you want to clear whole bug reports history?} {Wilt u de gehele bug-rapport geschiedenis opschonen?}

### File: ../src/dialogs/index_dialog.tcl
mcset nl Index Index

### File: ../src/dialogs/index_dialog.tcl
mcset nl {Index name:} {Index naam:}

### File: ../src/dialogs/index_dialog.tcl
mcset nl Available Available

### File: ../src/dialogs/index_dialog.tcl
mcset nl Indexed Indexed

### File: ../src/dialogs/index_dialog.tcl
mcset nl {Modifying index} {Modifying index}

### File: ../src/dialogs/index_dialog.tcl
mcset nl {Modifying index '%s'} {Modifying index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset nl {Creating index} {Creating index}

### File: ../src/dialogs/index_dialog.tcl
mcset nl {Creating index '%s'} {Creating index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset nl {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?} {Unieke index kan niet gemaakt worden,
de geselecteerde kolommen bevatten duplicaten.
Wilt u deze waarden inzien?}

### File: ../src/dialogs/index_dialog.tcl
mcset nl {Unique values} {Unieke waarden}

### File: ../src/dialogs/index_dialog.tcl
mcset nl {Same values for '%s'} {Zelfde waarden voor '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset nl {You have to select at least one column.} {U dient minimaal een kolom te selecteren.}

### File: ../src/dialogs/index_dialog.tcl
mcset nl {You have to specify index name.} {U dient een indexnaam op te geven.}

### File: ../src/dialogs/functions_dialog.tcl
mcset nl Implementation: Implementatie:

### File: ../src/dialogs/functions_dialog.tcl
mcset nl Name: Naam:

### File: ../src/dialogs/functions_dialog.tcl
mcset nl {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.} {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.}

### File: ../src/dialogs/functions_dialog.tcl
mcset nl {Cannot use two functions with same name! Change name for '%s'.} {Kan geen twee functies met dezelfde naam gebruiken! Pas naamgeving aan voor '%s'.}

### File: ../src/dialogs/functions_dialog.tcl
mcset nl {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! } {Kan geen 'tcl' of 'sqlfile' gebruiken als functienaam; deze zijn gereserveerd! }

### File: ../src/dialogs/functions_dialog.tcl
mcset nl {Function '%s' is not implemented!} {Functie '%s' is niet geimplementeerd!}

### File: ../src/dialogs/functions_dialog.tcl
mcset nl {Delete function} {Verwijder functie}

### File: ../src/dialogs/functions_dialog.tcl
mcset nl {Are you sure you want to delete function '%s'?} {Weet u zeker dat u functie '%s' wilt verwijderen?}

### File: ../src/mainwindow.tcl
mcset nl {Connect to selected database} {Verbind met geselecteerde database}

### File: ../src/mainwindow.tcl
mcset nl {Disconnect from selected database} {Verbreek verbinding met geselecteerde database}

### File: ../src/mainwindow.tcl
mcset nl {Remove selected database from list} {Verwijder geselecteerde database uit lijst}

### File: ../src/mainwindow.tcl
mcset nl {New table} {Nieuwe tabel}

### File: ../src/mainwindow.tcl
mcset nl {Drop table} {Dump tabel (DROP)}

### File: ../src/mainwindow.tcl
mcset nl {Drop index} {Dump index (DROP)}

### File: ../src/mainwindow.tcl
mcset nl {Drop trigger} {Dump trigger (DROP)}

### File: ../src/mainwindow.tcl
mcset nl {Edit view} {Bewerk view}

### File: ../src/mainwindow.tcl
mcset nl {Drop view} {Dump view (DROP)}

### File: ../src/mainwindow.tcl
mcset nl {Arrange cascade windows layout} {Cascade venster layout}

### File: ../src/mainwindow.tcl
mcset nl {Arrange intelligent windows layout} {Intelligente venster layout}

### File: ../src/mainwindow.tcl
mcset nl {Refresh databases tree (%s)} {Databases tree verversen (%s)}

### File: ../src/mainwindow.tcl
mcset nl {Open SQL query editor} {SQL query editor openen}

### File: ../src/mainwindow.tcl
mcset nl {Settings (%s)} {Settings (%s)}

### File: ../src/mainwindow.tcl
mcset nl {Open SQL functions editor} {Open SQL functies editor}

### File: ../src/mainwindow.tcl
mcset nl {Clear objects filter} {Clear objects filter}

### File: ../src/mainwindow.tcl
mcset nl {Enter object name you want to look for} {Enter object name you want to look for}

### File: ../src/mainwindow.tcl
mcset nl Databases Databases

### File: ../src/mainwindow.tcl
mcset nl Tools Tools

### File: ../src/mainwindow.tcl
mcset nl Connect Verbinden

### File: ../src/mainwindow.tcl
mcset nl Disconnect {Verbinding verbreken}

### File: ../src/mainwindow.tcl
mcset nl {Remove from list} {Database verwijderen uit lijst}

### File: ../src/mainwindow.tcl
mcset nl {View main toolbar} {Toon main toolbar}

### File: ../src/mainwindow.tcl
mcset nl {View structure toolbar} {Toon structuur toolbar}

### File: ../src/mainwindow.tcl
mcset nl {View windows toolbar} {Toon vensters toolbar}

### File: ../src/mainwindow.tcl
mcset nl {View tools toolbar} {Toon tools toolbar}

### File: ../src/mainwindow.tcl
mcset nl {View configuration toolbar} {Toon configuratie toolbar}

### File: ../src/mainwindow.tcl
mcset nl {Refresh databases tree} {Ververs databases lijst}

### File: ../src/mainwindow.tcl
mcset nl {Custom SQL functions} {Custom SQL functies}

### File: ../src/mainwindow.tcl
mcset nl {Export database} {Database exporteren}

### File: ../src/mainwindow.tcl
mcset nl {Export table or view} {Export table or view}

### File: ../src/mainwindow.tcl
mcset nl {Import data to a table} {Import data to a table}

### File: ../src/mainwindow.tcl
mcset nl {SQLiteStudio home page} {SQLiteStudio home page}

### File: ../src/mainwindow.tcl
mcset nl {SQLiteStudio manual} {SQLiteStudio gebruikershandleiding}

### File: ../src/mainwindow.tcl
mcset nl {SQLite documentation} {SQLite documentatie}

### File: ../src/mainwindow.tcl
mcset nl {SQLiteStudio support forum} {SQLiteStudio support forum}

### File: ../src/mainwindow.tcl
mcset nl {Report a bug} {Een bug melden}

### File: ../src/mainwindow.tcl
mcset nl {Send feature request} {Feature request versturen}

### File: ../src/mainwindow.tcl
mcset nl {Show bug reports history} {Bugreport geschiedenis tonen}

### File: ../src/mainwindow.tcl
mcset nl {Show tips window} {Tips tonen}

### File: ../src/mainwindow.tcl
mcset nl ChangeLog ChangeLog

### File: ../src/mainwindow.tcl
mcset nl Roadmap Roadmap

### File: ../src/mainwindow.tcl
mcset nl {Check for new version} {Controleer op nieuwe versie}

### File: ../src/mainwindow.tcl
mcset nl Donate Donate

### File: ../src/mainwindow.tcl
mcset nl {Did you know that...} {Wist u dat...}

### File: ../src/mainwindow.tcl
mcset nl {Editor %s} {Editor %s}

### File: ../src/mainwindow.tcl
mcset nl Settings Instellingen

### File: ../src/mainwindow.tcl
mcset nl {SQLiteStudio roadmap} {SQLiteStudio roadmap}

### File: ../src/mainwindow.tcl
mcset nl {Can't start web browser, because:
%s} {Kan web browser niet starten, omdat:
%s}

### File: ../src/mainwindow.tcl
mcset nl {Can't start %s web browser, because:
%s} {Kan web browser niet starten, omdat:
%s}

### File: ../src/mainwindow.tcl
mcset nl {About SQLiteStudio} {Over SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset nl {SQLiteStudio ChangeLog} {SQLiteStudio ChangeLog}

### File: ../src/mainwindow.tcl
mcset nl {There is no new version available.} {Er is geen nieuwere versie beschikbaar.}

### File: ../src/mainwindow.tcl
mcset nl {New version} {Nieuwe versie}

### File: ../src/mainwindow.tcl
mcset nl {Report bug} {Bug melden}

### File: ../src/mainwindow.tcl
mcset nl {Feature request} {Feature request}

### File: ../src/mainwindow.tcl
mcset nl {Reports history} {Verzonden rapporten}

### File: ../src/mainwindow.tcl
mcset nl {Reporting bug} {Bug rapporteren}

### File: ../src/mainwindow.tcl
mcset nl {Reporting bug to SQLiteStudio bugs database...} {Bug aan de SQLiteStudio bugs database rapporteren...}

### File: ../src/mainwindow.tcl
mcset nl {Problem occurred while reporting bug. You can ignore it and get back to your work.} {Problem occurred while reporting bug. You can ignore it and get back to your work.}

### File: ../src/mainwindow.tcl
mcset nl Ignore Negeren

### File: ../src/mainwindow.tcl
mcset nl {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history} {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history}

### File: ../src/mainwindow.tcl
mcset nl {A timeout occured while downloading new version. Try again, or download it manually.} {A timeout occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset nl {An error occured while downloading new version. Try again, or download it manually.} {An error occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset nl Downloading... Downloaden...

### File: ../src/mainwindow.tcl
mcset nl {Downloading SQLiteStudio v%s...} {Downloaden SQLiteStudio v%s...}

### File: ../src/mainwindow.tcl
mcset nl {Problem with saving new SQLiteStudio version to:
%s
Details:
%s} {Problem with saving new SQLiteStudio version to:
%s
Details:
%s}

### File: ../src/mainwindow.tcl
mcset nl {Problem with getting new SQLiteStudio version
Details:
%s} {Problem with getting new SQLiteStudio version
Details:
%s}

### File: ../src/mainwindow.tcl
mcset nl {This is unknown binary distribution. Cannot determinate binary file to download for update.} {This is unknown binary distribution. Cannot determinate binary file to download for update.}

### File: ../src/data_editor.tcl
mcset nl {There are uncommited rows.
Are you sure you want to close '%s' window anywy?} {Er zijn uncommited rijen.
Weet u zeker dat u venster '%s' toch wilt sluiten?}

### File: ../src/common/ddl_dialog.tcl
mcset nl {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s} {Kan DDL niet prepareren. Dialoogconfiguratie is incompleet.
Probleem details:
%s}

### File: ../src/common/color_picker.tcl
mcset nl {Choose color} {Kies kleur}

### File: ../src/common/shortcut_edit.tcl
mcset nl {Forbidden shortcut key combination: %s} {Ongeldige sneltoets of toetscombinatie: %s}

### File: ../src/common/common.tcl
mcset nl Copy Kopieren

### File: ../src/common/common.tcl
mcset nl Cut Knippen

### File: ../src/common/common.tcl
mcset nl Paste Plakken

### File: ../src/common/blob_edit_panel.tcl
mcset nl {Text edit} {Tekst bewerken}

### File: ../src/common/blob_edit_panel.tcl
mcset nl {Hexadecimal edit} {Hexadecimaal bewerken}

### File: ../src/common/common_sql.tcl
mcset nl {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
} {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
}

### File: ../src/common/hex_editor.tcl
mcset nl {Overwrite characters,
instead of inserting} {Overwrite characters,
instead of inserting}

### File: ../src/common/hex_editor.tcl
mcset nl Processing Bezig

### File: ../src/common/hex_editor.tcl
mcset nl {Processing data...} {Data verwerken...}

### File: ../src/sql_editor.tcl
mcset nl {Replace dialog} {Vervangen dialoogvenster}

### File: ../src/sql_editor.tcl
mcset nl {Search dialog} {Zoeken dialoogvenster}

### File: ../src/trees/db_tree.tcl
mcset nl Loading Loading

### File: ../src/trees/db_tree.tcl
mcset nl {Loading database list} {Loading database list}

### File: ../src/trees/db_tree.tcl
mcset nl {Given database file doesn't exist or is unreadable.} {Opgegeven database bestand bestaat niet of is onleesbaar.}

### File: ../src/trees/db_tree.tcl
mcset nl Vacuum Vacuum

### File: ../src/trees/db_tree.tcl
mcset nl {Integrity check} Integriteitscontrole

### File: ../src/trees/db_tree.tcl
mcset nl {Import schema from other database} {Schema importeren uit andere database}

### File: ../src/trees/db_tree.tcl
mcset nl {Reset autoincrement for '%s'} {Reset autoincrement for '%s'}

### File: ../src/trees/db_tree.tcl
mcset nl {Erase table data} {Erase table data}

### File: ../src/trees/db_tree.tcl
mcset nl {Create foreign key} {Vreemde sleutel aanmaken}

### File: ../src/trees/db_tree.tcl
mcset nl {Show view data} {Toon view data}

### File: ../src/trees/db_tree.tcl
mcset nl {Export view} {Export view}

### File: ../src/trees/db_tree.tcl
mcset nl {Sort databases alphabetically} {Sorteer databases op alfabet}

### File: ../src/trees/db_tree.tcl
mcset nl {Given database is already on the list.} {Gegeven database bestaat reeds in de lijst.}

### File: ../src/trees/db_tree.tcl
mcset nl {Given database name is already on the list.} {Gegeven database naam bestaat reeds in de lijst.}

### File: ../src/trees/db_tree.tcl
mcset nl Tables Tabellen

### File: ../src/trees/db_tree.tcl
mcset nl Views Views

### File: ../src/trees/db_tree.tcl
mcset nl {SQLite system table} {SQLite systeemtabel}

### File: ../src/trees/db_tree.tcl
mcset nl Columns Columns

### File: ../src/trees/db_tree.tcl
mcset nl {SQLite system index} {SQLite systeem index}

### File: ../src/trees/db_tree.tcl
mcset nl {Remove database} {Verwijder database}

### File: ../src/trees/db_tree.tcl
mcset nl {Are you sure you want to remove '%s' database from the list?} {Weet u zeker dat u database '%s' uit de lijst wil verwijderen?}

### File: ../src/trees/db_tree.tcl
mcset nl {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.} {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.}

### File: ../src/trees/db_tree.tcl
mcset nl {'%s' is a virtual table, therefore cannot be browsed in table window.} {'%s' is een virtuele tabel, en kan daarom niet worden getoond in het tabelvenster.}

### File: ../src/trees/db_tree.tcl
mcset nl {Table '%s' has no DDL. Probably it's system table and should not be edited.} {Table '%s' has no DDL. Probably it's system table and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset nl {'%s' is a virtual table, therefore cannot be edited in table dialog.} {'%s' is een virtuele tabel, en kan daarom niet worden bewerkt in het tabelvenster.}

### File: ../src/trees/db_tree.tcl
mcset nl {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.} {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.}

### File: ../src/trees/db_tree.tcl
mcset nl {Integrity check (%s)} {Integriteits-controle (%s)}

### File: ../src/trees/db_tree.tcl
mcset nl {Are you sure you want to DROP '%s' table?} {Weet u zeker dat u DROP '%s' tabel wilt uitvoeren?}

### File: ../src/trees/db_tree.tcl
mcset nl {Dropping table} {Dropping table}

### File: ../src/trees/db_tree.tcl
mcset nl {Dropping table '%s'} {Dropping table '%s'}

### File: ../src/trees/db_tree.tcl
mcset nl {Dropping index} {Dropping index}

### File: ../src/trees/db_tree.tcl
mcset nl {Dropping index '%s'} {Dropping index '%s'}

### File: ../src/trees/db_tree.tcl
mcset nl {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?} {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset nl {Fix trigger} {Fix trigger}

### File: ../src/trees/db_tree.tcl
mcset nl {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.} {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset nl {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?} {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset nl {Fix view} {Fix view}

### File: ../src/trees/db_tree.tcl
mcset nl {View '%s' has no DDL. Probably it's system view and should not be edited.} {View '%s' has no DDL. Probably it's system view and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset nl {Delete view} {Verwijder view}

### File: ../src/trees/db_tree.tcl
mcset nl {Are you sure you want to delete '%s' view?} {Weet u zeker dat u view '%s' wilt verwijderen?}

### File: ../src/trees/db_tree.tcl
mcset nl {Erase data} {Erase data}

### File: ../src/trees/db_tree.tcl
mcset nl {Are you sure you want to delete all data from table '%s'?} {Are you sure you want to delete all data from table '%s'?}

### File: ../src/trees/db_tree.tcl
mcset nl {Deleting data} {Deleting data}

### File: ../src/trees/db_tree.tcl
mcset nl {Deleting data from table '%s'} {Deleting data from table '%s'}

### File: ../src/trees/db_tree.tcl
mcset nl {'%s' view data} {'%s' view data}

### File: ../src/trees/db_tree.tcl
mcset nl {Are you sure you want to make a vacuum?} {Weet u zeker dat u een vacuum wilt maken?}

### File: ../src/trees/db_tree.tcl
mcset nl Vacuuming Vacuuming

### File: ../src/trees/db_tree.tcl
mcset nl {Vacuuming '%s'} {Vacuuming '%s'}

### File: ../src/trees/db_tree.tcl
mcset nl {SQL files} {SQL bestanden}

### File: ../src/trees/db_tree.tcl
mcset nl {Select SQL file to be executed} {Selecteer SQL bestand voor uitvoering}

### File: ../src/trees/db_tree.tcl
mcset nl {Error while executing SQL:
%s} {Error while executing SQL:
%s}

### File: ../src/trees/db_tree.tcl
mcset nl {SQL executed sucessfly.} {SQL succesvol uitgevoerd.}

### File: ../src/trees/db_tree.tcl
mcset nl {Import database schema} {Importeer database schema}

### File: ../src/trees/db_tree.tcl
mcset nl {Database: %s} {Database: %s}

### File: ../src/trees/db_tree.tcl
mcset nl URI: URI:

### File: ../src/trees/db_tree.tcl
mcset nl Version: Version:

### File: ../src/trees/db_tree.tcl
mcset nl {File size:} {File size:}

### File: ../src/trees/db_tree.tcl
mcset nl {Schema version:} {Schema version:}

### File: ../src/trees/db_tree.tcl
mcset nl {Virtual table} {Virtual table}

### File: ../src/trees/db_tree.tcl
mcset nl Indexes: Indexes:

### File: ../src/trees/db_tree.tcl
mcset nl Triggers: Triggers:

### File: ../src/trees/db_tree.tcl
mcset nl {Column: %s} {Kolom: %s}

### File: ../src/trees/db_tree.tcl
mcset nl {Not null} {Not null}

### File: ../src/trees/db_tree.tcl
mcset nl {Indexed table:} {Indexed table:}

### File: ../src/trees/db_tree.tcl
mcset nl {Copy index '%s' for table '%s'} {Copy index '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset nl {Move index '%s' to table '%s'} {Move index '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset nl {Copy trigger '%s' for table '%s'} {Copy trigger '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset nl {Move trigger '%s' to table '%s'} {Move trigger '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset nl {Copy view '%s' for database '%s'} {Copy view '%s' for database '%s'}

### File: ../src/trees/db_tree.tcl
mcset nl {Move view '%s' to database '%s'} {Move view '%s' to database '%s'}

### File: ../src/trees/db_tree.tcl
mcset nl {View '%s' has no DDL, therefore cannot be edited.} {View '%s' has no DDL, therefore cannot be edited.}

### File: ../src/trees/db_tree.tcl
mcset nl {Copy view} {Copy view}

### File: ../src/trees/db_tree.tcl
mcset nl {Move view} {Move view}

### File: ../src/trees/db_tree.tcl
mcset nl Move Move

### File: ../src/trees/db_tree.tcl
mcset nl {Copy index} {Copy index}

### File: ../src/trees/db_tree.tcl
mcset nl {Move index} {Move index}

### File: ../src/trees/db_tree.tcl
mcset nl {Copy trigger} {Copy trigger}

### File: ../src/trees/db_tree.tcl
mcset nl {Move trigger} {Move trigger}

### File: ../src/trees/db_tree.tcl
mcset nl {Copy table '%s' to database '%s' (include data, indexes and triggers)} {Copy table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset nl {Copy table '%s' to database '%s' (include data)} {Copy table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset nl {Copy table '%s' to database '%s' (include indexes and triggers)} {Copy table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset nl {Copy table '%s' to database '%s' (skip data, indexes and triggers)} {Copy table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset nl {Move table '%s' to database '%s' (include data, indexes and triggers)} {Move table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset nl {Move table '%s' to database '%s' (include data)} {Move table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset nl {Move table '%s' to database '%s' (include indexes and triggers)} {Move table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset nl {Move table '%s' to database '%s' (skip data, indexes and triggers)} {Move table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset nl {Copying table...} {Copying table...}

### File: ../src/trees/db_tree.tcl
mcset nl {Copying table '%s' from '%s' to '%s'.} {Copying table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset nl {Moving table...} {Moving table...}

### File: ../src/trees/db_tree.tcl
mcset nl {Moving table '%s' from '%s' to '%s'.} {Moving table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset nl {Could not create object in target database:
%s} {Could not create object in target database:
%s}

### File: ../src/trees/db_tree.tcl
mcset nl {Could not copy data:
%s} {Could not copy data:
%s}

### File: ../src/trees/db_tree.tcl
mcset nl {Could not copy table data from source database to target database. Details: %s} {Could not copy table data from source database to target database. Details: %s}

### File: ../src/trees/db_tree.tcl
mcset nl {Could not delete object(s) from source database. Details: %s} {Could not delete object(s) from source database. Details: %s}

### File: ../src/grids/dbgrid.tcl
mcset nl {Edit BLOB entry:} {Bewerk BLOB entry:}

### File: ../src/grids/dbgrid.tcl
mcset nl {BLOB edit} {bewerk BLOB}

### File: ../src/grids/dbgrid.tcl
mcset nl {Cannot commit. Details:
%s} {Cannot commit. Details:
%s}

### File: ../src/grids/grid.tcl
mcset nl {You have to select a cell before paste any contents.} {U dient een cel te selecteren voordat u gegevens plakt.}

### File: ../src/grids/grid.tcl
mcset nl {Cut data} {Gegevens knippen}

### File: ../src/grids/grid.tcl
mcset nl {There are too many columns or rows to paste. Do you want to cut them and paste?} {Er zijn teveel rijen of kolommen om te plakken. Wilt u deze inknippwn en toch plakken?}

### File: ../src/grids/data_grid.tcl
mcset nl {Insert new row} {Nieuwe rij invoegen}

### File: ../src/grids/data_grid.tcl
mcset nl {Delete selected rows} {Geselecteerde rijen verwijderen}

### File: ../src/grids/data_grid.tcl
mcset nl {Edit cell value} {Celwaarde bewerken}

### File: ../src/grids/data_grid.tcl
mcset nl {Edit cell value in BLOB editor} {Edit cell value in BLOB editor}

### File: ../src/grids/data_grid.tcl
mcset nl {Duplicate row} {Rij dupliceren}

### File: ../src/grids/data_grid.tcl
mcset nl {Set NULL value} {Zet NULL waarde}

### File: ../src/grids/data_grid.tcl
mcset nl {Generate SELECT from selected cells} {Generate SELECT from selected cells}

### File: ../src/grids/data_grid.tcl
mcset nl {Commit selected cells} {Commit geselecteerde cellen}

### File: ../src/grids/data_grid.tcl
mcset nl {Rollback selected cells} {Rollback geselecteerde cellen}

### File: ../src/grids/data_grid.tcl
mcset nl {Select all} {Select all}

### File: ../src/grids/data_grid.tcl
mcset nl {Show ordinals} {Rijnummers tonen}

### File: ../src/grids/data_grid.tcl
mcset nl {Show ROWIDs} {ROWIDs tonen}

### File: ../src/grids/data_grid.tcl
mcset nl Type: Type:

### File: ../src/grids/data_grid.tcl
mcset nl Constraints: Beperkingen:

### File: ../src/grids/data_grid.tcl
mcset nl {%s column has NOT NULL constraint. You have to fill value for it.} {%s kolom heeft een NOT NULL beperking. U moet een waarde opgeven.}

### File: ../src/grids/data_grid.tcl
mcset nl {Error while adding new row:
%s} {Fout tijdens toevoegen nieuwe rij:
%s}

### File: ../src/grids/data_grid.tcl
mcset nl {Error while updating new row:
%s} {Error while updating new row:
%s}

### File: ../src/grids/data_grid.tcl
mcset nl {Error while updating cell value:
%s

What would you like to do?} {Fout tijdens updaten celwaarde:
%s

Wat wilt u doen?}

### File: ../src/grids/data_grid.tcl
mcset nl {Re-edit value} {Waarde opnieuw bewerken}

### File: ../src/grids/data_grid.tcl
mcset nl {Return to value before edition} {Terugkeren naar waarde voor toevoeging}

### File: ../src/grids/data_grid.tcl
mcset nl {Cannot delete row(s), because it violates constraint. Details:
%s} {Cannot delete row(s), because it violates constraint. Details:
%s}

### File: ../src/grids/data_grid.tcl
mcset nl {Error while deleting selected rows:
%s} {Fout tijdens verwijderen geselecteerde rijen:
%s}

### File: ../src/grids/data_grid.tcl
mcset nl {SQL query generated at %s
using selected cells from window '%s'.} {SQL query generated at %s
using selected cells from window '%s'.}

### File: ../src/grids/result_grid.tcl
mcset nl {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.} {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.}

### File: ../src/grids/result_grid.tcl
mcset nl {Data type:} {Data type:}

### File: ../src/grids/result_grid.tcl
mcset nl {No details are available on this cell.} {Er zijn geen details beschikbaar voor deze cel.}

### File: ../src/grids/result_grid.tcl
mcset nl {Duplicated ROWID} {Gedupliceerd ROWID}

### File: ../src/grids/result_grid.tcl
mcset nl {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?} {Er zal meer dan een rij met ROWID=%s worden getroffen met deze plak operatie.
In dit geval kan dat leiden tot onvoorspelbare resultaten. Doorgaan?}

### File: ../src/grids/result_grid.tcl
mcset nl {Could not parse SQL while trying to generate requested query: %s} {Could not parse SQL while trying to generate requested query: %s}

### File: ../src/grids/result_grid.tcl
mcset nl {Cannot use '%s' statement to generate requested query.} {Cannot use '%s' statement to generate requested query.}

### File: ../src/grids/result_grid.tcl
mcset nl {Cannot determinate selected column with ID=%s.} {Cannot determinate selected column with ID=%s.}

### File: ../src/grids/result_grid.tcl
mcset nl {Error occurred while trying to generate the query: %s} {Error occurred while trying to generate the query: %s}

### File: ../src/grids/result_grid.tcl
mcset nl {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s} {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s}
