# SQLiteStudio 'pl_pl' localization file

# Unchanged translations

### File: ../src/win_assoc.tcl
mcset pl_pl {File associations} {Skojarzenia plików}

### File: ../src/win_assoc.tcl
mcset pl_pl {Following file extensions could not be associated to the current SQLiteStudio version:
%s} {Następujące rozszerzenia plików nie mogły zostać skojarzone z aktualną wersją SQLiteStudio:
%s}

### File: ../src/win_assoc.tcl
mcset pl_pl {Click the link below to find out what is possible reason and solutions.} {Kliknij poniższy odnośnik, aby dowiedzieć się jakie są możliwe przyczyny i rozwiązania.}

### File: ../src/cfg_win.tcl
mcset pl_pl Ok Ok

### File: ../src/cfg_win.tcl
mcset pl_pl Apply Zastosuj

### File: ../src/cfg_win.tcl
mcset pl_pl Cancel Anuluj

### File: ../src/cfg_win.tcl
mcset pl_pl Theme Styl

### File: ../src/cfg_win.tcl
mcset pl_pl {Select theme to use:} {Wybierz styl, którego chcesz używać}

### File: ../src/cfg_win.tcl
mcset pl_pl {Theme version:} {Wersja stylu:}

### File: ../src/cfg_win.tcl
mcset pl_pl Shortcuts Skróty

### File: ../src/cfg_win.tcl
mcset pl_pl {Global shortcuts} {Skróty globalne}

### File: ../src/cfg_win.tcl
mcset pl_pl {Open SQL editor} {Otwórz edytor SQL}

### File: ../src/cfg_win.tcl
mcset pl_pl {Opens SQL editor window.} {Otwiera okno edytora SQL.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Close selected task} {Zamknij wybrane zadanie}

### File: ../src/cfg_win.tcl
mcset pl_pl {Closes active MDI window.} {Zamyka aktywne okno MDI.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Restore last closed task} {Przywróć ostatnio zamknięte zadanie}

### File: ../src/cfg_win.tcl
mcset pl_pl {Restores last closed MDI window.} {Przywróć ostatnio zamknięte okno MDI.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Open settings} {Otwórz okno ustawień}

### File: ../src/cfg_win.tcl
mcset pl_pl {Opens SQLiteStudio settings window.} {Otwiera okno ustawień SQLiteStudio.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Next task} {Następne zadanie}

### File: ../src/cfg_win.tcl
mcset pl_pl {Switches task (window) to next, placed on the right from active task on taskbar.} {Przełącza do następnego zadania (okna), położonego na prawo od aktywnego zadania na pasku zadań.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Next task (alternative)} {Następne zadanie (alternatywny)}

### File: ../src/cfg_win.tcl
mcset pl_pl {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Przełącza do następnego zadania (okna), położonego na prawo od aktywnego zadania na pasku zadań.
To jest skrót alternatywny. Robi dokładnie to samo co ten powyższy.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Previous task} {Poprzednie zadanie}

### File: ../src/cfg_win.tcl
mcset pl_pl {Switches task (window) to previous, placed on the left from active task on taskbar.} {Przełącza do poprzedniego zadania (okna), położonego na lewo od aktywnego zadania na pasku zadań.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Previous task (alternative)} {Poprzednie zadanie (alternatywny)}

### File: ../src/cfg_win.tcl
mcset pl_pl {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Przełącza do poprzedniego zadania (okna), położonego na lewo od aktywnego zadania na pasku zadań.
To jest skrót alternatywny. Robi dokładnie to samo co ten powyższy.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Editor and table window shortcuts} {Skróty okna tabeli i edytora}

### File: ../src/cfg_win.tcl
mcset pl_pl {SQL editor completion} {Dopełenianie edytora SQL}

### File: ../src/cfg_win.tcl
mcset pl_pl {Invokes SQL completion in editor window.} {Wywołuje dopełnianie SQLa w oknie edytora}

### File: ../src/cfg_win.tcl
mcset pl_pl {Execute SQL query} {Wykonaj zapytanie SQL}

### File: ../src/cfg_win.tcl
mcset pl_pl {Executes SQL query typed in editor.} {Wykonuje zapytanie SQL wypisane w edytorze.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Explain SQL query} {Rozpisz zapytanie SQL}

### File: ../src/cfg_win.tcl
mcset pl_pl {Calls EXPLAIN on SQL query typed in editor.} {Wykonuje EXPLAIN dla zapytania SQL wpisanego w edytorze.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Format SQL code} {Formatuj kod SQL}

### File: ../src/cfg_win.tcl
mcset pl_pl {Formats SQL code typed in editor.} {Formatuje kod SQL wpisany w edytorze.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Load SQL from file} {Wczytaj SQL z pliku}

### File: ../src/cfg_win.tcl
mcset pl_pl {Loads SQL from file to the editor.} {Wczytuje SQL z pliku do edytora.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Save SQL to file} {Zapisz SQL w pliku}

### File: ../src/cfg_win.tcl
mcset pl_pl {Saves contents of the editor into a file.} {Zapisuje zawartość edytora do pliku.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Execute SQL from file} {Wykonaj SQL z pliku}

### File: ../src/cfg_win.tcl
mcset pl_pl {Executes SQL directly from file, without loading it to the editor.} {Wykonuje SQL wprost z pliku, bez wczytywania go do edytora.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Next tab} {Następna zakładka}

### File: ../src/cfg_win.tcl
mcset pl_pl {Switches to next tab of editor window (result or history).} {Przełącza do następnej zakładki w oknie edytora (wyniki lub historia).}

### File: ../src/cfg_win.tcl
mcset pl_pl {Previous tab} {Poprzednia zakładka}

### File: ../src/cfg_win.tcl
mcset pl_pl {Switches to previous tab of editor window (query or result).} {Przełącza do poprzedniej zakładki w oknie edytora (zapytanie lub wyniki).}

### File: ../src/cfg_win.tcl
mcset pl_pl {Next subtab} {Następna podzakładka}

### File: ../src/cfg_win.tcl
mcset pl_pl {Switches to next subtab (form view in results tab).} {Przełącza do następnej podzakładki (widok formularza w zakładce wyników).}

### File: ../src/cfg_win.tcl
mcset pl_pl {Previous subtab} {Poprzednia podzakładka}

### File: ../src/cfg_win.tcl
mcset pl_pl {Switches to previous subtab (grid view in results tab).} {Przełącza do poprzedniej podzakładki (widok tabeli w zakładce wyników).}

### File: ../src/cfg_win.tcl
mcset pl_pl Refresh Odśwież

### File: ../src/cfg_win.tcl
mcset pl_pl {Re-executes SQL query so results data is refreshed.} {Wykonuj zapytanie SQL ponownie aby odświeżyć dane.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Delete selected row} {Usuń wybrany wiersz}

### File: ../src/cfg_win.tcl
mcset pl_pl {Deletes selected row.} {Usuwa wybrany wiersz.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Add new row} {Dodaj nowy wiersz}

### File: ../src/cfg_win.tcl
mcset pl_pl {Adds new empty row without commiting it.} {Dodaje nowy pusty wiersz bez zatwierdzania go.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Erase cells data} {Wyczyść dane komórek}

### File: ../src/cfg_win.tcl
mcset pl_pl {Erases data of selected cells.} {Czyści dane z zaznaczonych komórek}

### File: ../src/cfg_win.tcl
mcset pl_pl {Next editor database in list} {Następna baza na liście edytora}

### File: ../src/cfg_win.tcl
mcset pl_pl {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)} {Przełącza bazę danych na następną w liście baz danych kontekstu edytora
(to jest rozwijana lista na górze okna edytora)}

### File: ../src/cfg_win.tcl
mcset pl_pl {Previous editor database in list} {Poprzednia baza na liście edytora}

### File: ../src/cfg_win.tcl
mcset pl_pl {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)} {Przełącza bazę danych na poprzednią w liście baz danych kontekstu edytora
(to jest rozwijana lista na górze okna edytora)}

### File: ../src/cfg_win.tcl
mcset pl_pl {Commit edition in Form View} {Zatwierdź edycję z widoku formularza}

### File: ../src/cfg_win.tcl
mcset pl_pl {Commits edition in Form View of query results or table data preview.} {Zatwierdza edycję z widoku formularza dla wyników zapytania lub przeglądanych danych tabeli.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Rollback edition in Form View} {Wycofaj edycję z widoku formularza}

### File: ../src/cfg_win.tcl
mcset pl_pl {Rolls back edition in Form View of query results or table data preview.} {Wycofuje edycję z widoku formularza dla wyników zapytania lub przeglądanych danych tabeli.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Jump to first row in Form View} {Skocz do pierwszego wiersza w widoku formularza}

### File: ../src/cfg_win.tcl
mcset pl_pl {Jumps to first row of query results grid
or table data preview grid in Form View.} {Skacze do pierwszego wiersza w widoku formularza dla
tabeli wyników zapytania lub tabeli przeglądanych danych tabeli.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Go to previous row in Form View} {Idź do poprzedniego wiersza w widoku formularza}

### File: ../src/cfg_win.tcl
mcset pl_pl {Goes to previous row of query results grid
or table data preview grid row in Form View.} {Idzie do poprzedniego wiersza w widoku formularza dla
tabeli wyników zapytania lub tabeli przeglądanych danych tabeli.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Go to next row in Form View} {Idź do następnego wiersza w widoku formularza}

### File: ../src/cfg_win.tcl
mcset pl_pl {Goes to next row of query results grid
or table data preview grid row in Form View.} {Idzie do następnego wiersza w widoku formularza dla
tabeli wyników zapytania lub tabeli przeglądanych danych tabeli.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Jump to last row in Form View} {Skocz do ostatniego wiersza w widoku formularza}

### File: ../src/cfg_win.tcl
mcset pl_pl {Jumps to last row of query results grid
or table data preview grid in Form View.} {Skacze do ostatniego wiersza w widoku formularza dla
tabeli wyników zapytania lub tabeli przeglądanych danych tabeli.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Switch NULL value in form edit field} {Przełącz wartość NULL w polu edycji formularza}

### File: ../src/cfg_win.tcl
mcset pl_pl {Sets or unsets NULL value in currently selected
column in form view data edit mode.} {Ustawia bądź usuwa wartość NULL na danej kolumnie
w trybie edycji danych w formularzu.}

### File: ../src/cfg_win.tcl
mcset pl_pl Plugins Wtyczki

### File: ../src/cfg_win.tcl
mcset pl_pl {SQL formatter plugins} {Wtyczki formatowania SQL}

### File: ../src/cfg_win.tcl
mcset pl_pl {Use following SQL formatter plugin:} {Użyj następującej wtyczki formatowania SQL:}

### File: ../src/cfg_win.tcl
mcset pl_pl {Configure formatter plugin} {Konfiguruj wtyczkę formatowania}

### File: ../src/cfg_win.tcl
mcset pl_pl Configure Konfiguruj

### File: ../src/cfg_win.tcl
mcset pl_pl {Populating plugins} {Wtyczki zaludniania}

### File: ../src/cfg_win.tcl
mcset pl_pl {Default table populating plugin:} {Domyślna wtyczka zaludniania tabel:}

### File: ../src/cfg_win.tcl
mcset pl_pl Miscellaneous Różne

### File: ../src/cfg_win.tcl
mcset pl_pl {Restore session after next start} {Przywracaj sesję przy następnym starcie}

### File: ../src/cfg_win.tcl
mcset pl_pl {All windows and their contents (such as SQL code)
will be restored while next application startup.} {Wszystkie okna i ich zawartość (jak kod SQL)
będą przywrócone podczas następnego startu aplikacji.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Show line numbers in SQL editor} {Pokazuj numery linii w edytorze SQL}

### File: ../src/cfg_win.tcl
mcset pl_pl {All SQL editor windows will contain line numbers on the left side of window.} {Wszystkie edytory SQL będą miały numery linii po lewej stronie tych okien.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Underline syntax errors in SQL editor} {Podkreślaj błędy skłądni w edytorze SQL}

### File: ../src/cfg_win.tcl
mcset pl_pl {Makes errors to be marked with underline.
You can also define foreground and background color for errors.} {Powoduje zaznaczanie błędów przez podkreślenie.
Możesz także zdefiniować kolor czicionki i tła dla błędów.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Show SQLite system tables and indexes in databases tree} {Pokazuj tabele i indeksy systemowe w drzewie baz danych}

### File: ../src/cfg_win.tcl
mcset pl_pl {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.} {Kied włączone, to tabele systemowe SQLite (pasujące do 'sqlite_*')
i indeksy (pasujące do '(*autoindex*)') są wyświetlane w drzewie baz danych.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Open items with single mouse click in databases tree} {Otwieraj pozycje pojedynczym kliknięciem w drzewie baz danych.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Items in database tree are open by double click by default.
This option switches it to single click.} {Pozycje w drzewie baz danych sa otwierane domyślnie przez podwójne kliknięcie.
Ta opcja przełącza to na pojedyncze kliknięcie.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Show ROWID as default instead of row order number in table data view} {Pokazuj ROWID domyślnie zamiast numeru wiersza w widoku danych tabeli}

### File: ../src/cfg_win.tcl
mcset pl_pl {This option affects first column from the left on the data tab of the table window.} {Ta opcja dotyczy pierwszej kolumny od lewej na zakładce danych w oknie tabeli.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Do not show 'did you know that...' dialog at startup.} {Nie pokazuj okna 'czy wiesz że...' przy starcie.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Uncheck this option to show the dialog.} {Odznacz tą opcję aby pokazać to okno.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Check for updates at startup.} {Sprawdzaj dostępność aktualizacji przy starcie.}

### File: ../src/cfg_win.tcl
mcset pl_pl {If enabled, application will will check
for new version available at startup.} {Kiedy włączone, aplikacja będzie sprawdzać
dostępność nowych wersji przy starcie.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Sort custom SQL functions list by name} {Sortuj własne funkcje SQL po nazwie}

### File: ../src/cfg_win.tcl
mcset pl_pl {This list is placed in Custom SQL funcions dialog.} {Ta lista znajduje się w oknie Własnych funkcji SQL.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Select all contents when editing the table cell} {Zaznacz całą zawartiść podczas edycji komórki tabeli}

### File: ../src/cfg_win.tcl
mcset pl_pl {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.} {Jeśli włączysz tą opcję, to za każdym razem gdy edytujesz komórkę tabeli,
cała zawartość tej komórki będzie domyślnie zaznaczona.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Ask if clipboard contents should be cut} {Pytaj czy zawartość schowka powinna być obcinana.}

### File: ../src/cfg_win.tcl
mcset pl_pl {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.} {Gdy zaznaczone, aplikacja będzie pytać, czy użytkownik
chce obcinać zawartość schowka podczas wklejania,
w przypadku, gdy ta zawartość nie mieści się w tabeli.
Gdy nie zaznaczone, aplikacja będzie obcinać zawartość
bez pytania.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Rows per page in Table Window and Editor Results:} {Liczba wierszy na stronę w Oknie Tabeli i Wynikach Edytora:}

### File: ../src/cfg_win.tcl
mcset pl_pl {More results per page causes slower loading of single data page. Value 1000 should be right.} {Więcej wyników na stronie powoduje spowolnienie ładowania pojedynczej strony.}

### File: ../src/cfg_win.tcl
mcset pl_pl {History entries limit:} {Limit wpisów w historii:}

### File: ../src/cfg_win.tcl
mcset pl_pl {Number of rows to remember in SQL editor history.} {Liczba wierszy do zapamiętania w historii edytor SQL.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Insertion cursor blinking period (milliseconds):} {Okres migania kursora klawiatury (w milisekundach):}

### File: ../src/cfg_win.tcl
mcset pl_pl {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.} {Liczba milisekund w ciągu których kursor klawiatury w edytorze SQL ma migać. Ustaw 0 aby wyłączyć miganie.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Web browser:} {Przegldarka internetowa:}

### File: ../src/cfg_win.tcl
mcset pl_pl {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.} {Możesz tutaj podać swoją włąsną przeglądarkę. Musi się ona znajdować w zmiennej PATH.
Adres do otwarcia będzie po prostu przekazany jako argument do tej komendy.}

### File: ../src/cfg_win.tcl
mcset pl_pl Language: Język:

### File: ../src/cfg_win.tcl
mcset pl_pl {Tab in table window on open:} {Zakładka w oknie tabeli przy otwieraniu:}

### File: ../src/cfg_win.tcl
mcset pl_pl {Table structure} {Struktura tabeli}

### File: ../src/cfg_win.tcl
mcset pl_pl {Table data} {Dane tabeli}

### File: ../src/cfg_win.tcl
mcset pl_pl {Select which tab should be opened for start in table window,
when you just opened that window.} {Wybierz która zakładka będzie aktywna
tuż po otwarciu okna tabeli.}

### File: ../src/cfg_win.tcl
mcset pl_pl {View default display mode:} {Domyślny tryb wyświetlania widoku:}

### File: ../src/cfg_win.tcl
mcset pl_pl {Edition dialog} {Dialog edycji}

### File: ../src/cfg_win.tcl
mcset pl_pl {Data view} {Widok danych}

### File: ../src/cfg_win.tcl
mcset pl_pl {Defines what is displayed by default when user opens a view.} {Definiuje co jest wyświetlane jako domyślna operacja, gdy użytkownik otwiera widok.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Editor window results layout} {Układ wyników okna edytora}

### File: ../src/cfg_win.tcl
mcset pl_pl {Show results in separated tab} {Pokazuj wyniki w osobnej zakładce}

### File: ../src/cfg_win.tcl
mcset pl_pl {Show results in frame below query} {Pokazuj wyniki w ramce pod zapytaniem}

### File: ../src/cfg_win.tcl
mcset pl_pl {Database tree display mode} {Tryb wyświetlania drzewa baz danych}

### File: ../src/cfg_win.tcl
mcset pl_pl {Show indexes and triggers linked under referenced table.} {Pokazuj indeksy i wyzwalacze podłączone pod tabelą.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Show indexes and triggers in their own groups.} {Pokazuj indeksy i wyzwalacze w oddzielnych grupach.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Show column names linked under the table.} {Pokazuj nazwy kolumn podłączone pod tabelą.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Plain text results} {Wyniki tekstowe}

### File: ../src/cfg_win.tcl
mcset pl_pl {Display NULL values as:} {Wyświetlaj wartości NULL jako:}

### File: ../src/cfg_win.tcl
mcset pl_pl {Maximum column width:} {Maksymalna szerokość kolumny:}

### File: ../src/cfg_win.tcl
mcset pl_pl {Values longer than specified here will be cut in plain text results.} {Wartości dłuższe niż podane tutaj będa ucięte w wynikach tekstowych.}

### File: ../src/cfg_win.tcl
mcset pl_pl Colors Kolory

### File: ../src/cfg_win.tcl
mcset pl_pl {Global colors} {Kolory ogólne:}

### File: ../src/cfg_win.tcl
mcset pl_pl {MDI windows title bar background color} {Kolor tła paska tytułu okna MDI}

### File: ../src/cfg_win.tcl
mcset pl_pl {MDI windows title bar foreground color} {Kolor tekstu na pasku tytułu okna MDI}

### File: ../src/cfg_win.tcl
mcset pl_pl {MDI windows title bar button background color} {Kolor tła przycisków na pasku tytułu okna MDI}

### File: ../src/cfg_win.tcl
mcset pl_pl {MDI windows title bar active button background color} {Kolor tła aktywnych przycisków na pasku tytułu okna MDI}

### File: ../src/cfg_win.tcl
mcset pl_pl {SQL Editor} {Editor SQL}

### File: ../src/cfg_win.tcl
mcset pl_pl {Editor standard font color} {Standardowy kolor tesktu edytora}

### File: ../src/cfg_win.tcl
mcset pl_pl {Editor background} {Tło edytora}

### File: ../src/cfg_win.tcl
mcset pl_pl {Selected foreground color} {Kolor zaznaczonego tekstu}

### File: ../src/cfg_win.tcl
mcset pl_pl {Selected background color} {Kolor tła zaznaczonego tekstu}

### File: ../src/cfg_win.tcl
mcset pl_pl {Disabled background color} {Kolor tła edytora w stanie wyłączonym}

### File: ../src/cfg_win.tcl
mcset pl_pl {Tables color} {Kolor oznaczający tabele}

### File: ../src/cfg_win.tcl
mcset pl_pl {Brackets color} {Kolor nawiasów klamrowych}

### File: ../src/cfg_win.tcl
mcset pl_pl {Square brackets color} {Kolor nawiasów kwadratowych}

### File: ../src/cfg_win.tcl
mcset pl_pl {Keywords color} {Kolor słów kluczowych}

### File: ../src/cfg_win.tcl
mcset pl_pl {Variables color} {Kolor zmiennych}

### File: ../src/cfg_win.tcl
mcset pl_pl {Strings color} {Kolor tekstów}

### File: ../src/cfg_win.tcl
mcset pl_pl {Comments color} {Kolor komentarzy}

### File: ../src/cfg_win.tcl
mcset pl_pl {Matched brackets foreground color} {Kolor tekstu dopasowanych par nawiasów}

### File: ../src/cfg_win.tcl
mcset pl_pl {Matched brackets background color} {Kolor tła dopasowanych par nawiasów}

### File: ../src/cfg_win.tcl
mcset pl_pl {Syntax error color} {Kolor błędu składni}

### File: ../src/cfg_win.tcl
mcset pl_pl {Tcl editor} {Edytor Tcl}

### File: ../src/cfg_win.tcl
mcset pl_pl {Options color} {Kolor opcji}

### File: ../src/cfg_win.tcl
mcset pl_pl {Quoted character color} {Kolor zacytowanego znaku}

### File: ../src/cfg_win.tcl
mcset pl_pl {Trees colors} {Kolory drzew}

### File: ../src/cfg_win.tcl
mcset pl_pl {Tree background} {Kolor tła drzewa}

### File: ../src/cfg_win.tcl
mcset pl_pl {Tree standard font color} {Standardowy kolor tekstu drzewa}

### File: ../src/cfg_win.tcl
mcset pl_pl {Tree selected background color} {Kolor tła zaznaczonego elementu w drzewie}

### File: ../src/cfg_win.tcl
mcset pl_pl {Tree selected foreground color} {Kolor tekstu zaznaczonego elementu w drzewie}

### File: ../src/cfg_win.tcl
mcset pl_pl {Color for number of objects in tree branch} {Kolor tekstu dla liczby obiektów w danej gałęzi drzewa}

### File: ../src/cfg_win.tcl
mcset pl_pl {Grids colors} {Kolory tabel}

### File: ../src/cfg_win.tcl
mcset pl_pl {Grid background} {Tło tabeli}

### File: ../src/cfg_win.tcl
mcset pl_pl {Grid standard font color} {Standardowy kolor tekstu w tabeli}

### File: ../src/cfg_win.tcl
mcset pl_pl {Grid selected background color} {Kolor tła zaznaczonegej komórki}

### File: ../src/cfg_win.tcl
mcset pl_pl {Grid selected foreground color} {Kolor tekstu w zaznaczonej komórce}

### File: ../src/cfg_win.tcl
mcset pl_pl {Grid base column background color} {Kolor tła głównej kolumny (z numerami wierszy)}

### File: ../src/cfg_win.tcl
mcset pl_pl {Foreground color for cells with NULL value} {Kolor czcionki dla wartości NULL w komórkach}

### File: ../src/cfg_win.tcl
mcset pl_pl {Status fields colors} {Kolory pola statusu}

### File: ../src/cfg_win.tcl
mcset pl_pl {Background color} {Kolor tła}

### File: ../src/cfg_win.tcl
mcset pl_pl {Foreground color} {Kolor tekstu}

### File: ../src/cfg_win.tcl
mcset pl_pl {Error foreground color} {Kolor tekstu dla błędu}

### File: ../src/cfg_win.tcl
mcset pl_pl {Information foreground color} {Kolor tekstu dla informacji}

### File: ../src/cfg_win.tcl
mcset pl_pl {Information (second kind) foreground color} {Alternatywny kolor dla tekstu informacji}

### File: ../src/cfg_win.tcl
mcset pl_pl {Miscellaneous colors} {Różne kolory}

### File: ../src/cfg_win.tcl
mcset pl_pl {Context hints background color} {Kolor tła podpowiedzi kontekstowych}

### File: ../src/cfg_win.tcl
mcset pl_pl {Context hints foreground color} {Kolor tekstu podpowiedzi kontekstowych}

### File: ../src/cfg_win.tcl
mcset pl_pl Fonts Czcionki

### File: ../src/cfg_win.tcl
mcset pl_pl {SQL editor font} {Czcionka w edytorze SQL}

### File: ../src/cfg_win.tcl
mcset pl_pl {Status fields font} {Czcionka pola statusu}

### File: ../src/cfg_win.tcl
mcset pl_pl {Grid font} {Czcionka tabel}

### File: ../src/cfg_win.tcl
mcset pl_pl {Tree font} {Czcionka drzewa}

### File: ../src/cfg_win.tcl
mcset pl_pl {Tree additional labels font} {Czcionka dodatkowych etykiet drzewa}

### File: ../src/cfg_win.tcl
mcset pl_pl {Context hints font} {Czcionka podpowiedzi kontekstowych}

### File: ../src/cfg_win.tcl
mcset pl_pl {Changed language needs application to be restarted.} {Zmieniony język wymaga zrestartowania aplikacji.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.} {Wystąpił problem podczas próby otwarcia pliku ustawień: %s. Wygląda na to, że katalog %s został usunięty lub jego nazwa została zmieniona. Ustawienia SQLiteStudio nie zostaną zapisane.}

### File: ../src/cfg_win.tcl
mcset pl_pl {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.} {Nie można zapisać pliku konfiguracyjnego. Niektóre ustawienia mogą zostać utracone. Proszę sprawdzić czy masz prawa zapisu do pliku '%s'.}

### File: ../src/cfg_win.tcl
mcset pl_pl {SQL formatter options} {Opcje formatowania SQL}

### File: ../src/db/db_file_types.tcl
mcset pl_pl {All SQLite Databases} {Wszystkie bazy SQLite}

### File: ../src/db/db_file_types.tcl
mcset pl_pl {SQLite 3 Databases} {Bazy SQLite 3}

### File: ../src/db/db_file_types.tcl
mcset pl_pl {SQLite 2 Databases} {Baza SQLite 2}

### File: ../src/db/db_file_types.tcl
mcset pl_pl {All files} {Wszystkie pliki}

### File: ../src/db/query_executor.tcl
mcset pl_pl {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.} {Zapytanie nie mogło być poprawnie zanalizowane przez wewnętrzny parser SQLiteStudio, więc zostało przekazane bezpośrednio do SQLite, bez podmian lub jakichkolwiek innych modyfikacji.}

### File: ../src/db/query_executor.tcl
mcset pl_pl {Invalid database name: %s} {Niepoprawna nazwa bazy danych: %s}

### File: ../src/db/query_executor.tcl
mcset pl_pl {Imbalanced 'BEGIN' ocurrence in query.} {Niezbalansowane wystąpienie 'BEGIN' w zapytaniu.}

### File: ../src/db/query_executor.tcl
mcset pl_pl {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.} {Nie można edytować wyników, ponieważ użyto zapytania wiązanego. Więcej szczegółów znajdziesz w paragrafie %s podręcznika użytkownika.}

### File: ../src/db/query_executor.tcl
mcset pl_pl {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.} {Nie można edytować wyników, ponieważ użyto słowa kluczowego DISTINCT. Więcej szczegółów znajdziesz w paragrafie %s podręcznika użytkownika.}

### File: ../src/db/query_executor.tcl
mcset pl_pl {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.} {Nie można edytować wyników, ponieważ użyto klauzuli GROUP BY. Więcej szczegółów znajdziesz w paragrafie %s podręcznika użytkownika.}

### File: ../src/db/query_executor.tcl
mcset pl_pl {Cannot use more than one 'BEGIN'.} {Nie można użyć więcej niż jednego 'BEGIN'.}

### File: ../src/db/query_executor.tcl
mcset pl_pl {Imbalanced 'COMMIT' ocurrence in query.} {Niezbalansowane wystąpienie 'COMMIT' w zapytaniu.}

### File: ../src/db/query_executor.tcl
mcset pl_pl {Imbalanced 'ROLLBACK' ocurrence in query.} {Niezbalansowane wystąpienie 'ROLLBACK' w zapytaniu.}

### File: ../src/db/sqlite2.tcl
mcset pl_pl {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)} {Wystąpił błąd podczas odwołania do VACUUM na bazie danych:
%s
(to jest wiadomość bezpośrednio z SQLite2)}

### File: ../src/db/db.tcl
mcset pl_pl {An internal logic error in SQLite} {Wewnętrzny błąd logiczny w SQLite}

### File: ../src/db/db.tcl
mcset pl_pl {Access permission denied} {Brak uprawnień}

### File: ../src/db/db.tcl
mcset pl_pl {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.} {Nie można przeprowadzić operacji, ponieważ baza jest zajęta.
Być może inna aplikacja używa tej bazy.}

### File: ../src/db/db.tcl
mcset pl_pl {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.} {Nie można przeprowadzić operacji, ponieważ baza jest zablokowana.
Być może inna aplikacja używa tej bazy.}

### File: ../src/db/db.tcl
mcset pl_pl {A malloc() failed} {malloc() nie powiódł się}

### File: ../src/db/db.tcl
mcset pl_pl {Attempt to write a readonly database} {Próba zapisu do bazy, podczas gdy jest ona tylko do odczytu}

### File: ../src/db/db.tcl
mcset pl_pl {Disk I/O error occurred} {Błąd wejścia wyjścia nośnika danych}

### File: ../src/db/db.tcl
mcset pl_pl {The database disk image is malformed} {Plik obrazu bazy danych jest zdeformowany.}

### File: ../src/db/db.tcl
mcset pl_pl {Database is full} {Baza danych jest pełna.}

### File: ../src/db/db.tcl
mcset pl_pl {Unable to open the database file} {Nie można otworzyć pliku bazy danych}

### File: ../src/db/db.tcl
mcset pl_pl {Database lock protocol error} {Błąd protokołu blokowania bazy danych}

### File: ../src/db/db.tcl
mcset pl_pl {Database is empty} {Baza danych jest pusta}

### File: ../src/db/db.tcl
mcset pl_pl {The database schema changed} {Schemat bazy danych został zmieniony}

### File: ../src/db/db.tcl
mcset pl_pl {String or BLOB exceeds size limit} {Limit długości tekstu lub pola BLOB został przekroczony}

### File: ../src/db/db.tcl
mcset pl_pl {Library used incorrectly} {Biblioteka użyta niepoprawnie}

### File: ../src/db/db.tcl
mcset pl_pl {Uses OS features not supported on host} {Użyto własności niedostępnych w tym systemie operacyjnym}

### File: ../src/db/db.tcl
mcset pl_pl {Authorization denied} {Autoryzacja się nie powiodła}

### File: ../src/db/db.tcl
mcset pl_pl {Auxiliary database format error} {Błąd pomocniczego formatu bazy danych}

### File: ../src/db/db.tcl
mcset pl_pl {2nd parameter to sqlite3_bind out of range} {Drugi parametr do sqlite3_bind jest poza zasięgiem}

### File: ../src/db/db.tcl
mcset pl_pl {File opened that is not a database file} {Otwarto plik, który nie jest bazą danych}

### File: ../src/db/db.tcl
mcset pl_pl {Error while opening %s database:
%s} {Błąd podczas otwierania bazy %s:
%s}

### File: ../src/db/db.tcl
mcset pl_pl {Not enough parameters passed to function '%s'.} {Zbyt mało parametrów podanych do funkcji '%s'.}

### File: ../src/db/db.tcl
mcset pl_pl {Cannot read file: %s} {Nie można czytać pliku: %s}

### File: ../src/db/db.tcl
mcset pl_pl {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.} {Nie można podłączyć bazy %s. Plik nie istnieje, lub jego wersja jest niekompatybilna, lub format pliku jest nieprawidłowy.}

### File: ../src/db/db.tcl
mcset pl_pl {Could not attach database %s. Error message from SQLite:
%s} {Nie można podłączyć bazy %s. Treść błędu z SQLite:
%s}

### File: ../src/db/db.tcl
mcset pl_pl {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.} {Nie można otrzymać SQL dla podłączenia bazy %s. Baza nie istnieje, lub jej wersja jest niekompatybilna, lub format pliku jest nieprawidłowy.}

### File: ../src/db/sqlite3.tcl
mcset pl_pl {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)} {Wystąpił błąd podczas wywołania VACUUM na bazie:
%s
(to jest wiadomość prosto z SQLite3)}

### File: ../src/completion_routines.tcl
mcset pl_pl {Problem with attaching database:
%s} {Problem podczas podłączania bazy danych:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Error from importing plugin:
%s} {Błąd od wtyczki importowania:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?} {Liczba kolumn w docelowej tabeli '%s' jest mniejsza, niż liczba kolumn w importowanych danych. Co chcesz zrobić?}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?} {Liczba kolumn w docelowej tabeli '%s' jest większa, niż liczba kolumn w importowanych danych. Co chcesz zrobić?}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Error creating table '%s':
%s

Importing aborted.} {Bład podczas tworzenia tabeli '%s':
%s

Przerwano importowanie.}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Error trying to import data to '%s':
%s

Importing aborted.} {Błąd podczas próby importowania danych do '%s':
%s

Przerwano importowanie.}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl Importing... Importowanie...

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Importing to table '%s'.} {Importowanie do tabeli '%s'.}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?} {Wtyczka importowania zwróciła błąd, gdy została poproszona o wiersz %s. Szczegóły błędu:
%s.

Co chcesz zrobić?}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?} {Liczba kolumn w danych z wiersza %s jest inna niż liczba kolumn zadeklarowana przez wtyczkę importowania. Co chcesz zrobić?}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Problem occured while importing row number %s:
%s

What would you like to do?} {Wystąpił problem podczas importowania wiersza numer %s:
%s

Co chcesz zrobić??}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Importing finished.} {Importowanie zakończone.}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Import problem} {Problem importowania}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Skip this data row} {Pomiń ten wiersz}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Keep data rows imported so far (%s) and abort} {Zachowaj dane zaimportowane dotychczas (%s) i przerwij}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Rollback data rows imported so far and abort} {Wycofaj zaimportowane dane i przerwij}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl {Ignore it and proceed} {Zignoruj i kontunuuj}

### File: ../src/plugins/import_plugin.tcl
mcset pl_pl Abort Zaniechaj

### File: ../src/plugins/sql_formatting/enterprise/format_s.tcl
mcset pl_pl name nazwa

### File: ../src/plugins/sql_formatting/basic.tcl
mcset pl_pl {Reduce group of whitespaces into one whitespace.} {Redukuj grupę białych znaków do jednego znaku białego.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset pl_pl {Uppercase keywords.} {Zmień litery słów kluczowych na duże.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset pl_pl {Separate ")" and after contents with single whitespace.} {Oddziel ")" i zawartość po nim następującą pojedynczym znakiem białym.}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {SQLite3 only} {Tylko SQLite3}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl Indentation Wcięcie

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {New lines} {Nowe linie}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {White spaces} {Znaki białe}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl Names Nazwy

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl Comments Komentarze

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Tab size:} {Szerokość tabulacji:}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Line up keywords in multi-line queries} {Wyrównaj słowa kluczowe w zapytaniach wielolinijkowych.}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Ident contents of parenthesis block} {Wcinaj zawartość bloków w nawiasach}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Ident parenthesis block in new line} {Wcinaj blok nawiasów gdy są w nowej linii}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Before opening parenthesis in column definitions} {Przed nawiasem otwierającym w definicjach kolumn}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After opening parenthesis in column definitions} {Po nawiasie otwierającym w definicjach kolumn}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Before closinging parenthesis in column definitions} {Przed nawiasem zamykającym w definicjach kolumn}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After closinging parenthesis in column definitions} {Po nawiasie zamykającym w definicjach kolumn}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Before opening parenthesis in expressions} {Przed nawiasem otwierającym w wyrażeniach}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After opening parenthesis in expressions} {Po nawiasie otwierającym w wyrażeniach}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Before closinging parenthesis in expressions} {Przed nawiasem zamykającym w wyrażeniach}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After closinging parenthesis in expressions} {Po nawiasie zamykającym w wyrażeniach}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After comma} {Po przecinku}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After comma in function arguments list} {Po przecinku w liście argumentów funkcji}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After logical block of query} {Po logicznym bloku zapytania}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After semicolon} {Po średniku}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Never before semicolon} {Nigdy przed średnikiem}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Before comma in lists} {Przed przecinkiem w listach}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After comma in lists} {Po przecinku w listach}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Before opening parenthesis} {Przed nawiasem otwierającym}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After opening parenthesis} {Po nawiasie otwierającym}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Before closing parenthesis} {Przed nawiasem zamykającym}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After closing parenthesis} {Po nawiasie zamykającym}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Before dot operator (in path to database object)} {Przed operatorem kropki (w ścieżce do obiektu bazodanowego)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After dot operator (in path to database object)} {Po operatorze kropki (w ścieżce do obiektu bazodanowego)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Before mathematical operator} {Przed operatorem matematycznym}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {After mathematical operator} {Po operatorze matematycznym}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Uppercase keywords} {Słowa kluczowe wielkimi lieterami}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Uppercase datatype names} {Typy danych wielkimi literami}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Always use name wrapping} {Zawsze opakowywuj nazwy}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Preferred name wrapper} {Preferowane opakowanie nazwy}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Expand one line comments (/* ... */) to multiline} {Rozwijaj jednoliniowe komentarz (/* ... */) do wieloliniowych}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Indent multi line comments} {Wcięcia w komentarzach wieloliniowych}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset pl_pl {Use "*" character for each line} {Użyj znaku "*" dla każdej linii}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {, (comma)} {, (przecinek)}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {; (semicolon)} {; (średnik)}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {\t (tab)} {\t (tab)}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {  (white-space)} {  (spacja)}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl Custom Własny

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Input file} {Plik wejściowy}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl Browse Przeglądaj

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Show options} {Pokaż opcje}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Column names} {Nazwy kolumn}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Treat first row as column names} {Traktuj pierwszy wiersz jako nazwy kolumn}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.} {Jeśli włączone, to pierwszy wierdz pliku CSV będzie zinterpretowany jako nazwy kolumn.
Są one ignorowane jeśli dane są importowane do istniejącej już tabeli.}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Columns separator:} {Separator kolumny:}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.} {Znak używany do oddzielania danych w kolumnach.
Separator może być częścią wartości kolumny, jeśli tylko zostanie
zamknięty między znakami cudzysłowia.}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {NULL handling} {Obsługa NULL}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Treat following values as NULL:} {Traktuj następującą wartość jako NULL:}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl Workarounds Obejścia

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Expect Microsoft format of CSV} {Spodziewaj się formatu Microsoft dla CSV}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.} {Microsoft używa nieco innego formatu CSV.
Jeśli importujesz dane z aplikacji tej firmy, użyj tej opcji.}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl Encoding Kodowanie

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Convert from encoding:} {Konwertuj z kodowania:}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Input file cannot be empty.} {Plik wejściowy nie może być pusty.}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Input file is not readable.} {Nie można czytać pliku wejściowego.}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {CSV separator cannot be empty.} {Separator CSV nie może być pusty.}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {CSV files} {Pliki CSV}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {Text files} {Pliki tekstowe}

### File: ../src/plugins/import/csv.tcl
mcset pl_pl {File to import from} {Plik z którego należy importować}

### File: ../src/plugins/import/dbf.tcl
mcset pl_pl Auto-detect {Wykryj automatycznie}

### File: ../src/plugins/import/dbf.tcl
mcset pl_pl {dBase files} {Pliki dBase}

### File: ../src/plugins/import/regexp.tcl
mcset pl_pl {Regular expression} {Wyrażenie regularne}

### File: ../src/plugins/import/regexp.tcl
mcset pl_pl {Visual editor} {Edytor wizualny}

### File: ../src/plugins/import/regexp.tcl
mcset pl_pl {Use Regular Expression Groups to identify columns.} {Użyj Grup Wyrażeń Regularnych w celu identyfikacji kolumn.}

### File: ../src/plugins/import/regexp.tcl
mcset pl_pl {Case insensitive} {Uwzględniaj wielkość liter}

### File: ../src/plugins/import/regexp.tcl
mcset pl_pl Help Pomoc

### File: ../src/plugins/import/regexp.tcl
mcset pl_pl {RegExp error:
%s} {Błąd RegExp:
%s}

### File: ../src/plugins/export/xls.tcl
mcset pl_pl {Column names as first row} {Nazwy kolumn jako pierwszy wiersz}

### File: ../src/plugins/export/xls.tcl
mcset pl_pl {If enabled, then first row of exported document will be a list of column names.} {Jeśli włączone, to pierwszy wiersz wyeksportowanego dokumentu będzie listą nazw kolumn.}

### File: ../src/plugins/export/xls.tcl
mcset pl_pl Encoding: Kodowanie:

### File: ../src/plugins/export/plain.tcl
mcset pl_pl {Export NULL values as:} {Eksportuj wartości NULL jako:}

### File: ../src/plugins/export/plain.tcl
mcset pl_pl {Fixed column width:} {Stała szerokość kolumn:}

### File: ../src/plugins/export/plain.tcl
mcset pl_pl {Database: %s (%s, %s)} {Baza danych: %s (%s, %s)}

### File: ../src/plugins/export/plain.tcl
mcset pl_pl {Table: %s} {Tabela: %s}

### File: ../src/plugins/export/plain.tcl
mcset pl_pl {Index: %s} {Indeks: %s}

### File: ../src/plugins/export/plain.tcl
mcset pl_pl {Trigger: %s} {Wyzwalacz: %s}

### File: ../src/plugins/export/plain.tcl
mcset pl_pl {View: %s} {Widok: %s}

### File: ../src/plugins/export/csv.tcl
mcset pl_pl {If enabled, then first row of exported CSV will be a list of column names.} {Jeśli włączone, to pierwszy wiersz wyekrportowanego CSV będzie listą nazw kolumn.}

### File: ../src/plugins/export/csv.tcl
mcset pl_pl {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.} {Znak używany do oddzielenia poszczególnych kolumn danych
od siebie. Jeśli separator występuje w którejkolwiek z column z danumi,
to wartość ta zostanie zamknięta w znakach cudzysłowia.
Dowolny znak cudzysłowia zostanie zastąpiony dwoma znakami cudzysłowia.}

### File: ../src/plugins/export/json.tcl
mcset pl_pl {Indented lines} {Wcięcia w liniach}

### File: ../src/plugins/export/json.tcl
mcset pl_pl {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.} {SQLiteStudio rozbije wygenerowany kod JSON na wiele linii
i doda wcięcia w odpowiednich dla jego struktury miejscach,
ustawiając każdy klucz obiektu w osobnej linii.}

### File: ../src/plugins/export/json.tcl
mcset pl_pl {Align lines} {Wyrównaj linie}

### File: ../src/plugins/export/json.tcl
mcset pl_pl {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.} {SQLiteStudio ustawi wartości dla kluczy w obiekcie
wyrównane w pionie, dając czytelny efekt tabeli.}

### File: ../src/plugins/export/json.tcl
mcset pl_pl {Each row as object} {Każdy wiersz jako obiekt}

### File: ../src/plugins/export/json.tcl
mcset pl_pl {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.} {Jeśli wyłączone, to każdy wiersz będzie wyeksportowany jako tablica JSON.
Jeśli włączone, to każdy wiersz będzie wyekrpotowany jako obiekt JSON
z nazwami kolumn jako kluczami obiektu.}

### File: ../src/plugins/export/xml.tcl
mcset pl_pl {No extra white-spaces or new lines} {Bez dodatkowych spacji lub znaków nowych linii}

### File: ../src/plugins/export/xml.tcl
mcset pl_pl {XML tags will be places char-by-char, without any extra white-spaces.} {Taki XML będą ułożone znak za znakiem, bez jakichkolwiek dodatkowych znaków \"pustych\".}

### File: ../src/plugins/export/xml.tcl
mcset pl_pl {Format output to be human readable} {Formatuj wyjście, aby było czytelne dla człowieka}

### File: ../src/plugins/export/xml.tcl
mcset pl_pl {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.} {Każdy tag będzie położony w nowej linii, a cały dokument
będzie wyjustowany, aby był bardziej czytelny w edytorze tekstowym.}

### File: ../src/plugins/export/xml.tcl
mcset pl_pl {Generate XSD file} {Generuj plik XSD}

### File: ../src/plugins/export/xml.tcl
mcset pl_pl {Generates XML Schema Definition file using
export file name and extension *.xsd.} {Generuje plik Definicji Schematu XML używając
nazwy pliku eksportu i rozszerzenia *.xsd.}

### File: ../src/plugins/export/xml.tcl
mcset pl_pl {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s} {Wystąpił problem podczas tworzenia pliku XSD, ale wszystkie dane zostały wyeksportowane do pliku XML. Szczegóły:
%s}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {First row of exported data will be header
with names of columns, just like in results grid.} {Pierwszy wiersz wyeksportowanych danych będzie nagłówkiem
z nazwami kolumn, tak jak w tabeli wyników.}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Row numbers as first column} {Numery wierszy jako pierwsza kolumna}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {First column of exported data
will contain row order number.} {Pierwsza kolumna wyeksportowanych danych
będzie zawierać kolejny numer wiersza.}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Full column names} {Pełne nazwy kolumn}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Column names in header will be prepended with "table_name." prefix.} {Nazwy kolumn w nagłówku będą poprzedzone prefiksem "nazwa_tabeli.".}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Show types} {Pokaż typy}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Column headers will contain data types.} {Nagłówki kolumn będą zawierały typy danych.}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {no type} {brak typu}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {For table:} {Dla tabeli:}

### File: ../src/plugins/export/html.tcl
mcset pl_pl Unique: Unikalny:

### File: ../src/plugins/export/html.tcl
mcset pl_pl Yes Tak

### File: ../src/plugins/export/html.tcl
mcset pl_pl No Nie

### File: ../src/plugins/export/html.tcl
mcset pl_pl Column Kolumna

### File: ../src/plugins/export/html.tcl
mcset pl_pl Collating Porównywanie

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Sort order} {Porządek sortowania}

### File: ../src/plugins/export/html.tcl
mcset pl_pl Activated: Aktywowany:

### File: ../src/plugins/export/html.tcl
mcset pl_pl Action: Zdarzenie:

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Activate condition:} {Warunek zdarzenia:}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Code executed:} {Wykonywany kod:}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Exported database: %s} {Wyeksportowana baza danych: %s}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Generated on %s with %s} {Wygenerowano dnia %s przez %s}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Exported table: %s} {Wyeksportowana tabela: %s}

### File: ../src/plugins/export/html.tcl
mcset pl_pl {Results of SQL query} {Wyniki zapytania SQL}

### File: ../src/plugins/export/dbf.tcl
mcset pl_pl {Cannot overwrite file '%s'.} {Nie można nadpisać '%s'.}

### File: ../src/plugins/export/sql.tcl
mcset pl_pl {Name of table for exported data:} {Nazwa tabeli dla eksportowanych danych:}

### File: ../src/plugins/export/sql.tcl
mcset pl_pl {Include "CREATE TABLE" statement at the begining.} {Uwzględnij deklarację "CREATE TABLE" na początku.}

### File: ../src/plugins/export/sql.tcl
mcset pl_pl {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.} {Wyniki zapytania eksportowane do INSERTów SQL muszą być
zdefiniowane dla danej tabeli. To jest nazwa tej tabeli.}

### File: ../src/plugins/export/sql.tcl
mcset pl_pl {Include table declaration} {Dołącz deklarację tabeli}

### File: ../src/plugins/export/sql.tcl
mcset pl_pl {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.} {Jeśli włączone, to DDL tabeli (CREATE TABLE)
będzie dołączone do wyeksportowanego SQLa.}

### File: ../src/plugins/export/sql.tcl
mcset pl_pl {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.} {Musisz skonigurować nazwę tabeli, aby wyeksportować wyniki zapytania do SQL.
INSERTy SQL wymagają tabeli w swojej składni.}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl Dimensions Wymiary

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Paper size:} {Rozmiar kartki:}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Margin size:} {Szerokość marginesu:}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Cell padding:} {Dopełnianie komórek:}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Limit amount of data bytes in single cell to:} {Ograniczaj liczbę bajtów w pojedynczej komórce do:}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Font size:} {Rozmiar czcionki:}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Built-in font} {Wbudowana czcionka}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl Font: Czcionka:

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {TrueType font} {Czcionka TrueType}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Font file:} {Plik czcionki:}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Font encoding:} {Kodowanie czcionki:}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Columns and rows} {Kolumny i wiersze}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Header background} {Tło nagłówka}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Empty space} {Pusta przestrzeń}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Fill empty space in cells} {Wypełnij pustą przestrzeń w komórkach}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.} {Jeśli dana kolumna w wierszu ma bardzo długą warość,
a druga kolumna na krótką wartość, to ta opcja spowoduje wypełnienie
pustej przestrzeni pod krótką wartością kolorowym tłem.}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Minimum height of empty space to fill:} {Minimalna wysokość pustej przestrzeni, która zostanie wypełniona:}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.} {Jeśli wysokość pustej przestrzeni w komórce jest mniejsza
niż wartość tu podana, to dodatkowe tło nie będzie rysowane.}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Empty space background} {Tło pustej przestrzeni}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {TTF Fonts} {Czcionki TTF}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {All Files} {Wszystki pliki}

### File: ../src/plugins/export/pdf.tcl
mcset pl_pl {Open TTF font} {Czcionka Open TTF}

### File: ../src/plugins/populating/random.tcl
mcset pl_pl {Include alpha characters} {Użyj znaków alfabetu}

### File: ../src/plugins/populating/random.tcl
mcset pl_pl {Include numeric characters} {Użyj cyfr}

### File: ../src/plugins/populating/random.tcl
mcset pl_pl {Include whitespace characters} {Użyj białych znaków}

### File: ../src/plugins/populating/random.tcl
mcset pl_pl {Include binary characters} {Użyj znaków binarnych}

### File: ../src/plugins/populating/random.tcl
mcset pl_pl {Minimum length:} {Minimalna długość:}

### File: ../src/plugins/populating/random.tcl
mcset pl_pl {Maximum length:} {Maksymalna długość:}

### File: ../src/plugins/populating/random_number.tcl
mcset pl_pl {Minimum value:} {Minimalna wartość:}

### File: ../src/plugins/populating/random_number.tcl
mcset pl_pl {Maximum value:} {Maksymalna wartość:}

### File: ../src/plugins/populating/random_number.tcl
mcset pl_pl {Constant prefix:} {Stały przedrostek:}

### File: ../src/plugins/populating/random_number.tcl
mcset pl_pl {Constant suffix:} {Stały przyrostek:}

### File: ../src/plugins/populating/sql.tcl
mcset pl_pl {Initialisation code} {Kod inicjalizujący}

### File: ../src/plugins/populating/sql.tcl
mcset pl_pl {Per iteration code} {Kod dla każdej iteracji}

### File: ../src/plugins/populating/sql.tcl
mcset pl_pl {Closing code} {Kod zamykający}

### File: ../src/plugins/populating/constant.tcl
mcset pl_pl {Value to use:} {Używaj wartości:}

### File: ../src/plugins/populating/sequence.tcl
mcset pl_pl {Start from:} {Zacznij od:}

### File: ../src/plugins/populating/dictionary.tcl
mcset pl_pl {Dictionary file:} {Plik słownika:}

### File: ../src/plugins/populating/dictionary.tcl
mcset pl_pl {Dictionary words separator:} {Separator słów słownika:}

### File: ../src/plugins/populating/dictionary.tcl
mcset pl_pl Whitespace {Biały znak}

### File: ../src/plugins/populating/dictionary.tcl
mcset pl_pl {Line break} {Znak końca linii}

### File: ../src/plugins/populating/dictionary.tcl
mcset pl_pl {Method of using words:} {Metoda używania słów:}

### File: ../src/plugins/populating/dictionary.tcl
mcset pl_pl Randomly Losowo

### File: ../src/plugins/populating/dictionary.tcl
mcset pl_pl Consecutively Kolejno

### File: ../src/plugins/populating/dictionary.tcl
mcset pl_pl {Dictionary file doesn't exist, or unreadable.} {Plik słownika nie istnieje lub jest nieczytelny.}

### File: ../src/plugins/populating/dictionary.tcl
mcset pl_pl {Dictionary file is empty!} {Plik słownika jest pusty!}

### File: ../src/plugins/populating/dictionary.tcl
mcset pl_pl {Dictionary file} {Plik słownika}

### File: ../src/taskbar.tcl
mcset pl_pl Database: {Baza danych:}

### File: ../src/taskbar.tcl
mcset pl_pl Table: Tabela:

### File: ../src/taskbar.tcl
mcset pl_pl {Type new name for a window} {Wpisz nową nazwę dla okna}

### File: ../src/taskbar.tcl
mcset pl_pl {Window with given name already exists. Please type other name.} {Okno o podanej nazwie już istnieje. Proszę wybrać inną nazwę.}

### File: ../src/taskbar.tcl
mcset pl_pl {Type new name for a task} {Wpisz nową nazwę dla zadania}

### File: ../src/taskbar.tcl
mcset pl_pl {Close selected window} {Zamknij wybrane okno}

### File: ../src/taskbar.tcl
mcset pl_pl {Close other windows} {Zamknij pozostałe okna}

### File: ../src/taskbar.tcl
mcset pl_pl {Close all windows} {Zamknij wszystkie okna}

### File: ../src/taskbar.tcl
mcset pl_pl {Restore last closed window} {Przywróć ostatnio zamknięte okno}

### File: ../src/taskbar.tcl
mcset pl_pl {Rename selected window} {Zmień nazwę wybranego okna}

### File: ../src/windows/table_win.tcl
mcset pl_pl Structure Struktura

### File: ../src/windows/table_win.tcl
mcset pl_pl Data Dane

### File: ../src/windows/table_win.tcl
mcset pl_pl Constraints Ograniczenia

### File: ../src/windows/table_win.tcl
mcset pl_pl Indexes Indeksy

### File: ../src/windows/table_win.tcl
mcset pl_pl Triggers Wyzwalacze

### File: ../src/windows/table_win.tcl
mcset pl_pl {Grid view} {Widok tabeli}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Form view} {Widok formularza}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Refresh table columns and DDL (%s)} {Odśwież kolumny tabeli i DDL (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Edit table (%s)} {Edytuj tabelę (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Export table data (%s)} {Eksportuj dane tabeli (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Import data to table (%s)} {Importuj dane do tabeli (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Populate table (%s)} {Zaludnij tabelę (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Create similar table} {Utwórz podobną tabelę}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Refresh table data (%s)} {Odśwież dane tabeli (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Add custom number of rows} {Dodaj dowolną liczbę wierszy}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Add new row (%s)} {Dodaj nowy wiersz (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Delete selected row (%s)} {Usuń wybrany wiersz (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Commit changes (%s)} {Zatwierdź zmiany (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Rollback new row (%s)} {Wycofaj nowy wiersz (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {First %s rows} {Pierwsze %s wiersze(y)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Previous %s rows} {Poprzednie %s wiersze(y)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Next %s rows} {Następne %s wiersze(y)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Last %s rows} {Ostatnie %s wiersze(y)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Export table data} {Eksportuj dane tabeli}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Import data to table} {Importuj dane do tabeli}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Populate table} {Zaludnij tabelę}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Enter phrase you want to look for} {Wpisz frazę której szukasz}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Apply data filter} {Zastosuj filtr danych}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Clear data filter} {Wyczyść filtr danych}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Total rows: %s} {Wierszy ogółem: %s}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Rollback changes (%s)} {Wycofaj zmiany (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {First row from data grid (%s)} {Pierwszy wiersz z tabeli danych (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Previous row from data grid (%s)} {Poprzedni wiersz z tabeli danych (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Next row from data grid (%s)} {Następny wiersz z tabeli danych (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Last row from data grid (%s)} {Ostatni wiersz z tabeli danych (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Field switching mode.

Click it to make <Tab> key to insert tab characters.} {Tryb zmieniania pól.

Kliknij aby zmienić działanie klawisza <Tab> na wstawianie znaku tabulacji.}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.} {Tryb wstawianie tabulacji.

Kliknij aby zmienić działanie klawisza <Tab> na przechodzenie pomiędzy polami edycji formularza.}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Refresh table indexes (%s)} {Odśwież indeksy tabeli (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Create new index (%s)} {Dodaj nowy indeks (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Edit index (%s)} {Edytuj indeks (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Delete index (%s)} {Usuń indeks (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Refresh table triggers (%s)} {Odśwież wyzwalacze tabeli (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Create new trigger (%s)} {Dodaj nowy wyzwalacz (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Edit trigger (%s)} {Edytuj wyzwalacz (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Delete trigger (%s)} {Usuń wyzwalacz (%s)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Constraint name} {Nazwa ograniczenia}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Column name} {Nazwa kolumny}

### File: ../src/windows/table_win.tcl
mcset pl_pl Default Domyślnie

### File: ../src/windows/table_win.tcl
mcset pl_pl {Not NULL} {Nie NULL}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Primary key} {Klucz główny}

### File: ../src/windows/table_win.tcl
mcset pl_pl Unique Unikalny

### File: ../src/windows/table_win.tcl
mcset pl_pl Collate Zestawianie

### File: ../src/windows/table_win.tcl
mcset pl_pl Check Sprawdź

### File: ../src/windows/table_win.tcl
mcset pl_pl {Foreign key} {Klucz obcy}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Index name} {Nazwa indeksu}

### File: ../src/windows/table_win.tcl
mcset pl_pl {On column} {Dla kolumn}

### File: ../src/windows/table_win.tcl
mcset pl_pl {SQL code} {Kod SQL}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Trigger name} {Nazwa wyzwalacza}

### File: ../src/windows/table_win.tcl
mcset pl_pl {On table} {Dla tabeli}

### File: ../src/windows/table_win.tcl
mcset pl_pl Name Nazwa

### File: ../src/windows/table_win.tcl
mcset pl_pl {Data type} {Typ danych}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Default value} {Domyślna wartość}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Refreshing dependencies} {Odświeżanie zależności}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Refreshing table columns...} {Odświeżanie kolumn tabeli...}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Refreshing table data...} {Odświeżanie danych tabeli...}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Refreshing table indexes...} {Odświeżanie indeksów tabeli...}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Refreshing table triggers...} {Odświeżanie wyzwalaczy tabeli...}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.} {Tabela '%s' nie ma DDL w tabeli sqlite_master lub nie istnieje już w bazie danych. To okno tabeli zostanie teraz zamknięte.}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Check condition} {Sprawdzaj warunek}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Total rows: %s (filtered)} {Razem wierszy: %s (przefiltrowane)}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Pending commits} {Oczekujące potwierdzenia}

### File: ../src/windows/table_win.tcl
mcset pl_pl {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?} {Modyfikacje danych są nie zatwierdzone.
Przeładowanie danych je wycofa.
Czy na pewno chcesz kontynuować?}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Loading data...} {Ładowanie danych...}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Loading table '%s'...} {Ładowanie tabeli '%s'...}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.} {Użycie wszystkich znaków %s, %s, oraz %s w nazwie jednej kolumny jest szczególnie odradzane i powinno być unikane za wszelką cenę. Dlatego też zalecana jest zmiana nazwy dla kolumny %s w tabeli %s. Dane tabeli nie zostaną załadowane.}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.} {Tabela '%s' nie ma DDL. Prawdopodobnie nie istnieje lub jest tabelą systemową.}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Edit table} {Edytuj tabelę}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Enter number of rows to add:} {Podaj liczbę wierszy do dodania:}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Add rows} {Dodaj wiersze}

### File: ../src/windows/table_win.tcl
mcset pl_pl {New index} {Nowy indeks}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Index '%s' has no DDL. Probably it's system index and should not be edited.} {Indeks '%s' nie ma DDL. Prawdopodobnie jest to indeks systemowy i nie powinien być edytowany.}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Edit index} {Edytuj indeks}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Delete index} {Usuń indeks}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Are you sure you want to delete '%s' index?} {Czy na pewno chcesz usunąć indeks '%s'?}

### File: ../src/windows/table_win.tcl
mcset pl_pl {New trigger} {Nowy wyzwalacz}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.} {Wyzwalacz '%s' nie ma DDL. Prawdopodobnie jest to wyzwalacz systemowy i nie powinien być edytowany.}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Edit trigger} {Edytuj wyzwalacz}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Delete trigger} {Usuń wyzwalacz}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Are you sure you want to delete '%s' trigger?} {Czy na pewno chcesz usunąć wyzwalacz '%s'?}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Export table} {Eksportuj tablę}

### File: ../src/windows/table_win.tcl
mcset pl_pl {Import data} {Importuj dane}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {SQL query} {Zapytanie SQL}

### File: ../src/windows/editor_win.tcl
mcset pl_pl Results Wyniki

### File: ../src/windows/editor_win.tcl
mcset pl_pl History Historia

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Execute query (%s)} {Wykonaj zapytanie (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Execute query with plain string results} {Wykonaj zapytanie i zwróć wyniki w postaci tekstu.}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Explain query (%s)} {Rozpisz zapytanie (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Format SQL code (%s)} {Formatuj kod SQL (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Refresh syntax highlighting (%s)} {Odśwież podświetlanie składni (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Clear history} {Wyczyść historię}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Export results} {Eksportuj wyniki}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Create view from query} {Stwórz widok z zapytania}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Execute SQL from file (%s)} {Wykonaj SQL z pliku (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Load SQL from file (%s)} {Wczytaj SQL z pliku (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Save SQL to file (%s)} {Zapisz SQL do pliku (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Default database for SQL executing
(%s/%s)} {Domyślna baza danych dla wykonywania SQL
(%s/%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl Database {Baza danych}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Execution date} {Data wykonania}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Execution time (s)} {Czas wykonywania (s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Rows affected} {Przetworzonych wierszy}

### File: ../src/windows/editor_win.tcl
mcset pl_pl SQL SQL

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Plain text view} {Widok tesktu}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Refresh results (%s)} {Odśwież wyniki (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Commit row (%s)} {Zatwierdź wiersz (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Rollback row (%s)} {Wycofaj wiersz (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Copy (%s)} {Kopiuj (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Cut (%s)} {Wytnij (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Paste (%s)} {Wklej (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Show line numbers} {Pokaż numery linii}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Delete selected history entry (%s)} {Usuń wybrany wpis z historii (%s)}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Choose the database first.} {Najpierw wybierz bazę danych.}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Error while trying to collect completion list: %s} {Bład podczas próby zebrania listy dopełniania: %s}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Can't open %s file for reading.} {Nie można odczytać pliku %s.}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Can't open %s file for writting.} {Nie można zapisać pliku %s.}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {SQL code saved in %s.} {Kod SQL zapisany w %s.}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Are you sure you want to clear queries history?} {Czy na pewno chcesz wyczyścić historię zapytań?}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Delete the history entry} {Usuń wpis z historii}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Are you sure you want to delete selected queries history entry?} {Czy na pewno chcesz usunąć wybrane zapytania z historii?}

### File: ../src/windows/editor_win.tcl
mcset pl_pl Processing... Przetwarzanie...

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Processing query...} {Przetwarzanie zapytania...}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {No results to export.} {Brak wyników do wyeksportowania.}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.} {Używanie ATTACH z edytora SQL nie jest dozwolone. Zamiast tego zarejestruj bazę danych którą chcesz podłączyć w SQLiteStudio i użyj jej nazwy widocznej w drzewie baz danych w dowolnym zapytaniu SQL. Zostaną one automatycznie podłączone na rządanie}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Query execution...} {Wykonywanie zapytania...}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Executing SQL query...} {Wykonywanie zapytania SQL...}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Error while executing query: %s} {Błąd podczas wykonywania zapytania: %s}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s} {Nieznany błąd podczas wykonywania zapytania. Proszę to zgłosić! ReturnCode=%s. Zapytanie do wykonania: %s}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {%s row(s) read in %s second(s).} {Odczytano %s wierszy w %s sekund(y).}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {%s row(s) affected in %s second(s).} {%s wierszy przetworzonych w %s sekund(y).}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {No SELECT statements found in editor or in selected part of SQL code.} {Nie znaleziono deklaracji SELECT w edytorze, lub wybranej części kodu SQL.}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {More than one SELECT statements found. Please select the one you're interested in and then try again.} {Znaleziono więcej niż jedna deklaracja SELECT. Zaznacz tą, która cię interesuje i spróbuj ponownie.}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {New view} {Nowy widok}

### File: ../src/windows/editor_win.tcl
mcset pl_pl {Fill query parameters} {Wypełnij parametry zapytania}

### File: ../src/error.tcl
mcset pl_pl {Background error} {Błąd w tle}

### File: ../src/error.tcl
mcset pl_pl Close Zamknij

### File: ../src/error.tcl
mcset pl_pl {Report the bug} {Zgłoś błąd}

### File: ../src/dialogs/about_dialog.tcl
mcset pl_pl About {O programie}

### File: ../src/dialogs/about_dialog.tcl
mcset pl_pl {Packages and plugins} {Pakiety i wtyczki}

### File: ../src/dialogs/about_dialog.tcl
mcset pl_pl Licence Licencja

### File: ../src/dialogs/about_dialog.tcl
mcset pl_pl {Installed plugins:} {Zainstalowane wtyczki:}

### File: ../src/dialogs/about_dialog.tcl
mcset pl_pl {Used Tcl packages:} {Użyte pakiety Tcl:}

### File: ../src/dialogs/about_dialog.tcl
mcset pl_pl {SQLite3 engine version: %s} {Wersja silnika SQLite3: %s}

### File: ../src/dialogs/searchdialog.tcl
mcset pl_pl {Global expression understeands '*', '?' and \[chars].} {Wyrażenia globale obsługują '*', '?', oraz \[znaki].}

### File: ../src/dialogs/searchdialog.tcl
mcset pl_pl Find Znajdź

### File: ../src/dialogs/searchdialog.tcl
mcset pl_pl Replace Zmień

### File: ../src/dialogs/searchdialog.tcl
mcset pl_pl {Do you want to replace marked text?} {Czy chcesz zmienić zaznaczony tekst?}

### File: ../src/dialogs/searchdialog.tcl
mcset pl_pl {Replace all} {Zmień wszystkie}

### File: ../src/dialogs/searchdialog.tcl
mcset pl_pl {Replacing finished.} {Zmienianie zakończone.}

### File: ../src/dialogs/searchdialog.tcl
mcset pl_pl {Cannot match the pattern!} {Nie można dopasować frazy!}

### File: ../src/dialogs/bind_param.tcl
mcset pl_pl {Query number %s} {Numer zapytania %s}

### File: ../src/dialogs/bind_param.tcl
mcset pl_pl {Parameter number %s (named: %s):} {Parametr numer %s (nazwa: %s):}

### File: ../src/dialogs/bind_param.tcl
mcset pl_pl {NULL value} {Wartość NULL}

### File: ../src/dialogs/bind_param.tcl
mcset pl_pl {You can use '%s' keyboard shortcut to switch NULL value.} {Możesz użyć skrótu klawiszowego '%s', aby przełączyć wartość NULL.}

### File: ../src/dialogs/bind_param.tcl
mcset pl_pl {Copy value to other '%s' parameters (%s)} {Skopiuj wartość do innych parametrów '%s' (%s)}

### File: ../src/dialogs/bind_param.tcl
mcset pl_pl {By enabling this all parameters with same name
will also have same value as this one.} {Włączając to wszystkie parametry o tej samej nazwie
będą mieć również tą samą wartość jak ta.}

### File: ../src/dialogs/bind_param.tcl
mcset pl_pl {Execute query} {Wykonaj zapytanie}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset pl_pl Collation Zestawianie

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset pl_pl Sort Sortuj

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset pl_pl {Named constraint:} {Nazwane ograniczenie:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset pl_pl {On conflict:} {W przypadku konfliktu:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset pl_pl {Constraint is marked as being named, but there's no name filled in.} {Ograniczenie jest oznaczone jako nazwane, ale nie ma podanej nazwy.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset pl_pl {Collation for column '%s' is enabled, but there's no collation name filled in.} {Zestawianie dla kolumny '%s' jest włączone, ale nie ma nazwy podanej zestawiania.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset pl_pl {No columns are selected.} {Brak wybranej kolumny.}

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl {Number of rows to insert:} {Liczba wierszy do dodania:}

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl {On a constraint violation:} {W przypadku złamania ograniczenia:}

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl Mode Tryb

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl {Select table to display available columns} {Wybierz tabelę aby wyświetlić dostępne kolumny}

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl Populate Zaludnianie

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl {Error occured while populating table:
%s} {Błąd podczas zaludniania tabeli:
%s}

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl Configuration Konfiguracja

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl {You have to type valid number of rows to insert.} {Należy wprowadzić poprawną liczbę wierszy do dodania.}

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl {You have to select at least one column to populate.} {Musisz wybrać przynajmniej jedną kolumnę do zaludnienia.}

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl Populating... Zaludnianie...

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl {Populating table '%s'.} {Zaludnianie tabeli '%s'.}

### File: ../src/dialogs/populate_table.tcl
mcset pl_pl Stop Zatrzymaj

### File: ../src/dialogs/table_dialog_fk.tcl
mcset pl_pl {Foreign table:} {Obca tabela:}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset pl_pl {Local column} {Kolumna lokalna}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset pl_pl {Foreign column} {Kolumna obca}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset pl_pl Reactions Reakcje

### File: ../src/dialogs/table_dialog_fk.tcl
mcset pl_pl {ON UPDATE} {ON UPDATE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset pl_pl {ON DELETE} {ON DELETE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset pl_pl MATCH MATCH

### File: ../src/dialogs/table_dialog_fk.tcl
mcset pl_pl {Deferred foreign key} {Klucz obcy odroczony}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset pl_pl {No foreign table selected.} {Nie wybrano obcej tabeli.}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset pl_pl {There's no foreign column assigned for local column '%s'.} {Nie ma przypisanej kolumny obcej dla kolumny lokalnej '%s'.}

### File: ../src/dialogs/import_dialog.tcl
mcset pl_pl {Import from:} {Importuj z:}

### File: ../src/dialogs/import_dialog.tcl
mcset pl_pl {Import to:} {Importuj do:}

### File: ../src/dialogs/import_dialog.tcl
mcset pl_pl Table Tabela

### File: ../src/dialogs/import_dialog.tcl
mcset pl_pl Existing Istniejąca

### File: ../src/dialogs/import_dialog.tcl
mcset pl_pl {Create new table} {Utwórz nową tabelę}

### File: ../src/dialogs/import_dialog.tcl
mcset pl_pl Import Importuj

### File: ../src/dialogs/import_dialog.tcl
mcset pl_pl {Import method is not selected.} {Nie wybrano metody importowania.}

### File: ../src/dialogs/import_dialog.tcl
mcset pl_pl {You have to choose database.} {Musisz wybrac bazę danych.}

### File: ../src/dialogs/import_dialog.tcl
mcset pl_pl {No existing table is selected.} {Nie wybrano istniejącej tabeli.}

### File: ../src/dialogs/import_dialog.tcl
mcset pl_pl {Table typed to create already exists. Please change table name.} {Podana tabela już istnieje. Proszę zmienić nazwę tabeli.}

### File: ../src/dialogs/view_dialog.tcl
mcset pl_pl View Widok

### File: ../src/dialogs/view_dialog.tcl
mcset pl_pl {View name:} {Nazwa widoku:}

### File: ../src/dialogs/view_dialog.tcl
mcset pl_pl {Code executed to get view data:} {Kod wykonywany do pobrania danych dla widoku:}

### File: ../src/dialogs/view_dialog.tcl
mcset pl_pl Create Utwórz

### File: ../src/dialogs/view_dialog.tcl
mcset pl_pl Change Zmień

### File: ../src/dialogs/view_dialog.tcl
mcset pl_pl {You have to specify database.} {Musisz wybrać bazę danych.}

### File: ../src/dialogs/view_dialog.tcl
mcset pl_pl {You have to specify view name.} {Musisz podać nazwę widoku.}

### File: ../src/dialogs/view_dialog.tcl
mcset pl_pl {You havn't wrote a code for the view.} {Nie podano kodu dla widoku.}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {Export data} {Eksportuj dane}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {Only structure, without data} {Tylko struktura, bez danych}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {Table or view} {Tabela lub widok}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {Output file} {Plik wynikowy}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {Export format} {Format eksportu}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl Export Eksportuj

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {You have to choose file.} {Musisz wybrać plik.}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {Can't write to file: %s} {Nie można pisać do pliku: %s}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {You have to choose table.} {Musisz wybrać tabelę.}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {Exporting database '%s'.} {Eksportowanie bazy danych '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {Exporting table '%s'.} {Eksportowanie tabeli '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {Exporting view '%s'.} {Eksportowanie widoku '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {Exporting results.} {Eksportowanie wyników.}

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl Exporting... Eksportowanie...

### File: ../src/dialogs/export_dialog.tcl
mcset pl_pl {Cannot write to file: %s
Please select other file.} {Nie można pisać do pliku: %s
Proszę wybrać inny plik.}

### File: ../src/dialogs/bug_report_login.tcl
mcset pl_pl {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.} {Proszę podać nazwę użytkownika i hasło, które będzie używane do zgłaszania błędów i nowych pomysłów. Jeśli jeszcze nie masz konta, możesz je założyć przez odnośnik poniżej. Zgłaszanie z użyciem twojej nazwy użytkownika pozwoli ci na łatwe śledzenie twoich zgłoszeń. Hasło będzie zachowane w formie zaszyfrowanej.}

### File: ../src/dialogs/bug_report_login.tcl
mcset pl_pl Login: Login:

### File: ../src/dialogs/bug_report_login.tcl
mcset pl_pl Password: Hasło:

### File: ../src/dialogs/bug_report_login.tcl
mcset pl_pl Validate Sprawdź

### File: ../src/dialogs/bug_report_login.tcl
mcset pl_pl {Validation result} {Wynik sprawdzenia}

### File: ../src/dialogs/bug_report_login.tcl
mcset pl_pl {Not validated yet} {Jeszcze nie sprawdzono}

### File: ../src/dialogs/bug_report_login.tcl
mcset pl_pl Validating... Sprawdzanie...

### File: ../src/dialogs/bug_report_login.tcl
mcset pl_pl {Validating login and password...} {Sprawdzanie loginu i hasła...}

### File: ../src/dialogs/bug_report_login.tcl
mcset pl_pl {Invalid login or password.} {Niepoprawny login lub hadło.}

### File: ../src/dialogs/bug_report_login.tcl
mcset pl_pl {Login and password are correct.} {Login i hasło są poprawne..}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Your e-mail address or user (both optional)} {Twój adres e-mail lub nazwa użytkownika (oba są opcjonalne)}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl or lub

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Log in} Zaloguj

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Logged in} Zalogowano

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Log out} Wyloguj

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Brief description:} {Krótki opis:}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {How to reproduce problem (if possible):} {Jak powtórzyć problem (jeśli się da):}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {What is the problem:} {Na czym polega problem:}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Show more (optional)} {Pokaż więcej (opcjonalne)}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Operating system:} {System operacyjny:}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Take screenshots of all SQLiteStudio windows and attach them} {Zrób zrzut ekranu wszystkich okien SQLiteStudio i załącz je}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl Send Wyślij

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Describe your feature request:} {Opisz swoją propozycję zmiany:}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl Hide Uryj

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Please fill 'Brief' field.} {Proszę wypełnić pole 'Krótki opis'.}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Please fill at least one of 'Description' or 'How to reproduce' fields.} {Proszę wypełnić przynajmniej jedno z pól: 'Opis' lub 'Jak powtórzyć'.}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {Please provide valid e-mail address or leave 'E-mail' empty.} {Proszę podać poprawny adres e-mail, lub zostawić pole 'E-Mail' puste.}

### File: ../src/dialogs/bug_report.tcl
mcset pl_pl {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.} {Ten adres e-mail NIE będzie udostępniony komukolwiek,
ani użyty w jakimkolwiek innym celu niż opisano nizej.
Nie zostanie on gdziekolwiek upubliczniony.
Będzie on używany jedynie przez dewelopera SQLiteStudio
w celu ewentualnego kontaktu jeśli niezbędne będą
dodatkowe detale odnośnie zgłoszenia.

Jest to opcjonalne. Możesz zostawić to pole puste.}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Database to convert:} {Baza do konwersji:}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Converted database name:} {Nazwa skonwertowanej bazy:}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {File to use for converted database:} {Plik dla skonwertowanej bazy:}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Choose new file for database} {Wybierz nowy plik dla bazy danych}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Database version:} {Wersja bazy:}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl Convert Konwertuj

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Convert database} {Konwertuj bazę}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {You chave to choose database to convert.} {Musisz wybrać bazę do konwersji.}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Error resolving database with name %s!} {Błąd podczas szukania bazy o nazwie %s!}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {You have to specify new database file.} {Musisz podać plik nowej bazy danych.}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Cannot use existing file for converted database.} {Nie można użyć istniejącego pliku dla skonwertowanej bazy.}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Cannot use existing name for converted database.} {Nie można użyć istniejącej nazwy dla skonwertowanej bazy.}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Cannot find handler for database labeled with: %s} {Nie można znaleźć silnika obsługującego bazę danych oznaczoną jako: %s}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Error while trying to create database: %s} {Błąd podczas próby utworzenia bazy danych: %s}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Database converting error} {Błąd konwersji bazy danych}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s} {Wystąpiły pewne problemy podczas konwersji bazy danych, ale została ona i tak przekonwertowana, pomijając obiekty powodujące problemy. Szczegóły:
%s}

### File: ../src/dialogs/db_convert.tcl
mcset pl_pl {Choose file} {Wybierz plik}

### File: ../src/dialogs/yesno.tcl
mcset pl_pl Question Pytanie

### File: ../src/dialogs/yesno.tcl
mcset pl_pl Warning Uwaga

### File: ../src/dialogs/yesno.tcl
mcset pl_pl Error Błąd

### File: ../src/dialogs/yesno.tcl
mcset pl_pl Information Informacja

### File: ../src/dialogs/import_db.tcl
mcset pl_pl {Import from one of databases:} {Importuj z jednej z baz danych:}

### File: ../src/dialogs/import_db.tcl
mcset pl_pl {Choose database file to import:} {Wybierz plik bazy danych do zaimportowania:}

### File: ../src/dialogs/import_db.tcl
mcset pl_pl {No database chosen.} {Nie wybrano bazy.}

### File: ../src/dialogs/import_db.tcl
mcset pl_pl {Cannot open specified database.} {Nie można otworzyć wybranej bazy.}

### File: ../src/dialogs/import_db.tcl
mcset pl_pl {Error while importing database:
%s} {Błąd podczas importowania bazy:
%s}

### File: ../src/dialogs/import_db.tcl
mcset pl_pl {Select file} {Wybierz plik}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl Column: Kolumna:

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Column constraints:} {Ograniczenia kolumny:}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl Add Dodaj

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl Size Rozmiar

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Maximal length of value in column.} {Maksymalna długość danych w kolumnie.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Primary key configuration} {Konfiguracja klucza głównego}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl Autoincrement Autoinkrementacja

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Sort order:} {Kierunek sortowania:}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {No foreign column selected.} {Nie wybrano obcej kolumny.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Choose ON UPDATE action, or disable it.} {Wybierz akcję ON UPDATE, lub wyłącz ją.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Choose ON DELETE action, or disable it.} {Wybierz akcję ON DELETE, lub wyłącz ją.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Choose MATCH action, or disable it.} {Wybierz akcję MATCH, lub wyłącz ją.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Foreign key configuration} {Konfiguracja klucza obcego}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Foreign column:} {Obca kolumna:}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Unique configuration} {Konfiguracja wartości unikatowych}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Fill in the condition expression.} {Podaj wyrażenie warunkowe.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Check condition configuration} {Konfiguracja warunku do sparwdzania}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl Condition: Warunek:

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Not null configuration} {Konfiguracja nie NULL}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Fill in the collation name.} {Podaj nazwę zestawiania.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Collating configuration} {Konfiguracja zestawiania}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Collation name:} {Nazwa zestawiania:}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Fill in the default value.} {Wpisz wartość domyślną.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Default value configuration} {Konfiguracja wartości domyślnej}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Default value:} {Wartość domyślna:}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Use value as:} {Użyj wartości jako:}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {A literal value} {Dosłowna wartość}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {An expression} Wyrażenie

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Column primary key is not configured correctly.} {Klucz główny kolumny nie jest skonfigurowany poprawnie.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {AUTOINCREMENT is allowed only with INTEGER type of column.} {AUTOINCREMENT jest dozwolone tylko z typem kolumny INTEGER.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Column foreign key is not configured correctly.} {Klucz obcy kolumny nie jest skonfigurowany poprawnie.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Column 'unique' constraint is not configured correctly.} {Ograniczenie kolumny 'unique' nie jest skonfigurowane poprawnie.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Column 'check' constraint is not configured correctly.} {Ograniczenie kolumny 'warunek' nie jest skonfigurowane poprawnie.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Column 'notnull' constraint is not configured correctly.} {Ograniczenie kolumny 'notnull' nie jest skonfigurowane poprawnie.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Column 'default' constraint is not configured correctly.} {Ograniczenie kolumny 'wartość domyślna' nie jest skonfigurowane poprawnie.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Column 'collate' constraint is not configured correctly.} {Ograniczenie kolumny 'zestawianie' nie jest skonfigurowane poprawnie.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {No column name is specified.} {Nie podano nazwy kolumny.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Column with name '%s' already exists in the table.} {Kolumna o nazwie '%s' już istnieje w tabeli.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Data type bounds are given, but no data type name is specified.} {Granice typu danych są podane, ale nie podano nazwy typu danych.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Data type precision is given, but no data type size is specified.} {Precyzja typu danych jest podana, ale rozmiar typu danych nie jest podany.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Data type size has invalid format. Only integer value is allowed.} {Rozmiar typu danych ma niepoprawny format. Dozwolona jest tylko liczba całkowita.}

### File: ../src/dialogs/column_dialog.tcl
mcset pl_pl {Data type precision has invalid format. Only integer value is allowed.} {Precyzja typu danych ma niepoprawny format. Dozwolona jest tylko liczba całkowita.}

### File: ../src/dialogs/assoc_dialog.tcl
mcset pl_pl {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:} {SQLiteStudio wykryło że następujące rozszerzenia plików są skojarzone z poprzednią instalacją SQLiteStudio:}

### File: ../src/dialogs/assoc_dialog.tcl
mcset pl_pl {Current associations} {Aktualne skojarzenia}

### File: ../src/dialogs/assoc_dialog.tcl
mcset pl_pl {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.} {Proszę wybrać rozszerzenia plików, które chcesz skojarzyć z aktualnie uruchomioną wersją SQLiteStudio i kliknij OK.}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {Database file:} {Plik bazy danych:}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {Database name:} {Nazwa bazy danych:}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {Generate automatically} {Wygeneruj automatycznie}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {Type name in field below:} {Podaj nazwę w polu poniżej:}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {Remember it permanently} {Zapamiętaj na stałe}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {If disabled, then the database will be registered only
for this single SQLiteStudio session.} {Jeśli wyłączone, to baza danych będzie zarejestrowana
tylko na tą pojedynczą sesję SQLiteStudio.}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {Edit database} {Edytuj bazę danych}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {Add database} {Dodaj bazę danych}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {File '%s' doesn't exist!} {Plik '%s' nie istnieje!}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {You have to specify database file.} {Musisz podać plik bazy danych.}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {Database named '%s' already exists on databases list. Please pick other name.} {Baza danych o nazwie '%s' już istnieje na liście baz. Proszę wybrać inną nazwę.}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.} {Baza danych '%s' już istnieje na liście pod nazwą '%s'. Proszę wybrać inny plik bazy lub zaniechać.}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.} {Sterownik SQLite2 nie radzi sobie z nazwami plików zawierającymi znaki spoza zakresu ASCII w nazwach plików. Proszę nie używać znaków narodowych, użyj nazwy pliku ze znakami z zakresu ASCII.}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {Type not existing file for new database} {Podaj nieistniejący plik dla nowej bazy danych}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {Select existing database file} {Wybierz istniejący plik bazy danych}

### File: ../src/dialogs/db_edit.tcl
mcset pl_pl {%s is not supported database!} {%s nie jest obsługiwana bazą danych!}

### File: ../src/dialogs/table_dialog_pk.tcl
mcset pl_pl {Using autoincrement with more than one column at once is forbidden.} {Używanie autoinkrementacji dla więcej niż jednek kolumny naraz jest zabronione.}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl Previous Poprzedni

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl Next Następny

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {Do not show this dialog at startup} {Nie pokazuj tego okna przy starcie}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		} {

			Jeśli nie podoba Ci się otiweranie wielu edytorów SQL, możesz użyć pojedynczego edytora,
			napisać wiele SQLi i ostatecznie zaznaczyć tylko tą część kodu, którą chcesz wykonać
			i wtedy wcisnąć Wykonaj SQL.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			You can configure all SQL editor syntax colors in settings.
		} {
			Możesz configurować wszystkie kolory składni edytora SQL w ustawieniach.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		} {
			Poprawne nazwy kolumn w edytorze SQL są podświetlone na niebiesko (konfigurowalne).
			Jeśli tabela, o której spodziewasz się że powinna być podświetlona - nie jest, to oznacza to, że popełniłeś
			błąd w nazwie, lub wybrałeś inną bazę kontekstową w edytorze SQL (na górze okna edytora), w której ta tabela
			nie istnieje.<br><br>
			Możesz również wcisnąć i przytrzymać klawisz Control, aby poprawne tabele zostały podkreślone - staną się one
			odnośnikami do szybkiego otwierania adekwatnych okien tabeli.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		} {
			Możesz użyć skrótu Ctrl+Spacja (można to konfigurować), aby dokończyć słowo, które zacząłeś pisać w edytorze SQL.
			Silnik dopełniania może również zgadywać następne słowo po kontekście SQL i pokazać przefiltrowaną listę słów padujących do tego kontektu.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		} {
			Jest wiele skrótów klawiszowych (wszystkie są konfigurowalne), które mogą uczynić pracę z SQLiteStudio o wiele prosztszą i szybszą.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		} {
			Nie musisz zatwierdzać każdej edycji w tabeli danych przez wciskanie Entera lub przycisku "Zatwierdź"
			na pasku narzędziowym. Możesz po prostu kliknąć na innej komórce (lub gdziekolwiek indziej),
			aby edytowane zostały zatwierdzone automatycznie. Aby wycofać zmiany dokonane podczas edycji komórki
			naciśnij Escape.<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		} {
			Jeśli zamkniesz SQLiteStudio z otwartym dowolnymi oknami MDI, to wszystkie one zostaną przywrócone (wraz z zawartością kodu SQL wpisanego w edytory),
			podczas następnego startu aplikacji, chyba że wyłączysz "przywracanie sesji" w ustawieniach.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		} {
			SQLiteStudio dostarcza trochę dodatkowych funkcji SQLite, które możesz użyć w edytorze SQL. Oto one:
			tcl() - uruchamia dowolny kod Tcl w nowym, odizolowanym interpreterze Tcl,<br>
			sqlfile() - wykonuje SQL z podanego pliku w aktualnej bazie danych,<br>
			md5() - oblicza sumę MD5 dla podanego argumentu,<br>
			base64_encode() - koduje dany argument algorytmem BASE64,<br>
			base64_decode() - dekoduje dany argument algorytmem BASE64,<br>
			więcej funkcji znajdziesz w Podręczniku Użytkownika.<br>
			Przykłady:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		} {
			Możesz definiować swoje własne funkcje SQL, które będą dostępne w bazie danych podczas edytowania ich w SQLiteStudio.
			Pomaga to emulować funkcje zaimplementowane w aplikacjach docelowych, które używają tej bazy.<br>
			Aby zaimplementować nową funkcję, przejdź do okna Własnych funkcji SQL i naciśnij przycisk dodawania,
			wtedy wprowadź nazwę i wybierz język, w którym chcesz zaimplementować funkcję (Tcl lub SQL).<br>
			Kod implementacji może zawierać $0, $1, $2, itd - są to paametry pozycyjne przekazane do funkcji, gdy jest ona wywołana.<br><br>
			Oto przykład implementacji funkcji w SQLu:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			A tutaj przykład w Tclu:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		} {
			Jeśli szukasz jakiegoś słowa w danych tabeli, ale nie chcesz pisać dla niego zapytania SQL, lub nie pamiętasz
			która kolumna zawiera to słowo, przejdź do widoku danych tabeli, wpisz to słowo w polu filtra i wciśnij "Zastosuj filtr".
			Wszystkie wystąpienia danego słowa (nawet z przedrostkami i przyrostkami) w dowolnej kolumnie zostaną znalezione
			i dane tabeli zostaną przefiltrowane do tych znalezionych wpisów.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		} {
			Możesz edytować wartości w tabeli wyników, ale wiedz, że kolumny które nie pochodzą wprost z tabeli (na przykład są wynikiem operacji matematycznej na kolumnie) - nie mogą być edytowane.
			Takie nieedytowalne komórki są także pomijane gdy do tabeli są wklejane jakieś dane.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		} {
			Jeśli chcesz zobaczyć ROWID pewnego konkretnego wiersza, możesz zostawić kursor myszy nad tym wierszem na chwilę.
			Pojawi się podpowiedź z ROWID (oraz innymi informacjami) dla tego wiersza.<br><br>
			W widoku tabeli danych okna tabeli możesz przełączać się pomiędzy wyświetlaniem ROWID zamiast liczby porząkowej. Ta opcja jest dostępna z menu kontekstowego widoku tabeli.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		} {
			Aby ustawić wartość NULL w komórce (a nie tylko wartość pustą) musisz użyć albo klawisza Backspace, gdy komórka jest zaznaczona, lub wybrać "Ustaw wartość NULL" z menu kontekstowego widoku tabeli.<br>
			Możesz zrobić to mając zaznaczone wiele komórek.<br><br>
			Widok Formularza pozwala na ustawianie wartości NULL dla każdej komórki osobno używając przełącznika, lub skrótu Alt-n (który jest konfigurowalny).<br><br>
			Pamiętaj, że zawsze możesz ustawić wartość NULL ręcznie używając zapytania SQL.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		} {
			Możesz umieścić wyniki wykonanego zapytania poniżej samego zapytania, zamiast przełączać się na następną zakładkę.
			Po prostu zmień układ okna edytora SQL w oknie konfiguracji.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		} {
			Zawsze możesz wrócić do zapytań które wcześniej wykonałeś przez przejście do zakładki historii w oknie edytora SQL.<br><br>
			Liczba wpisów trzymanych w historii jest konfigurowalna, ale wiedz, że jeśli wartość ta jest zbyt duża, to każdorazowe otwarcie okna edytora SQL
			spowoduje wczytanie całej historii i może to zwolnić nieco cały ten proces.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		} {
			Okno edytora SQL może pomóc ci pisać zapytania - wciśnij Ctrl+Spację (lub jakikolwiek skrót masz skonfigurowany) w oknie, aby wyświetlić okno dopełniania zapytania.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		} {
			Możesz użyć wielu nazw baz danych w pojedynczym zapytaniu SQL bez przejmowania się podłączaniem ich do bieżącej bazy danych.
			SQLiteStudio zajmie się tym za ciebie.<br><br>
			Używaj nazw baz danych tak jak są wyświetlone w drzewie baz danych po lewej stronie. Przykład:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		} {
			Możesz przytrzymać klawisz "Control" i kliknąć na komórkach danych, aby wybrać cały wiersz zamiast pojedynczych kolumn.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset pl_pl {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		} {
			W oknie edytora SQL możesz wybrać tylko część zapytania SQL i kliknąć "Wykona" (lub nacisnąć %s)
			aby wykonać tylko wybraną część kodu.
		}

### File: ../src/dialogs/import_table.tcl
mcset pl_pl Separator: Separator:

### File: ../src/dialogs/import_table.tcl
mcset pl_pl {Common separator is \t (tab), but sometimes others can be met.} {Typowym separatorem jest \t (tab), ale czasami inne są spotykane.}

### File: ../src/dialogs/import_table.tcl
mcset pl_pl {Import data file for '%s' table:} {Importuj plik danych dla tabeli '%s':}

### File: ../src/dialogs/import_table.tcl
mcset pl_pl {File '%s' isn't readable!} {Nie można odczytać pliku '%s'!}

### File: ../src/dialogs/import_table.tcl
mcset pl_pl {Error while trying to copy data:
%s} {Błąd podczas próby skopiowania danych:
%s}

### File: ../src/dialogs/release_notes_dialog.tcl
mcset pl_pl {Don't show this dialog after update.} {Nie pokazduj tego okna po aktualizacji.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl Trigger Wyzwalacz

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {On action:} {Dla zdarzenia:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {Trigger name:} {Nazwa wyzwalacza:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl When: Kiedy:

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {On table:} {Na tabeli:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {Execute code for:} {Wykonaj kod dla:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.} {Definiuje listę akcji dla 'UPDATE OF'.
Tabela wyzwalacza musi być już wybrana.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {Execute code only when:} {Wykonaj kod tylko wtedy, gdy:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {Code executed for above configuration:} {Kod wykonywany dla powyższej konfiguracji:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {You have to specify view.} {Musisz wybrać widok.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {You have to specify table.} {Musisz wybrać tabelę.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {You have to specify trigger name.} {Musisz podać nazwę wyzwalacza.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {You have to specify 'action' condition.} {Musisz wypełnić warunek 'zdarzenie'.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {You havn't wrote a code for the trigger.} {Nie napisano kodu dla wyzwalacza.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset pl_pl {On view:} {Na widoku:}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl Columns: Kolumny:

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Table constraints:} {Ograniczenia tabeli:}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Table name:} {Nazwa tabeli:}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Add column} {Dodaj kolumnę}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Edit selected} {Edytuj wybraną}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Delete selected} {Usuń wybraną}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl Type Typ

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl Details Szczegóły

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.} {Kolumna '%s' nie jest już w tabeli '%s', więc nie możesz jej edytować. Tabela została prawdopodobnie zmodyfikowana przez inną aplikację.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Edit column} {Edytuj kolumnę}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Delete column} {Usuń kolumnę}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Are you sure you want to delete column '%s'?} {Czy na pewno chcesz usunąć kolumnę '%s'?}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Constraint change} {Zmiana ograniczenia}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Are you sure you want to change constraint type?
Current constraint configuration will be lost.} {Czy na pewno chcesz zmienić typ ograniczenia?
Aktualna konfiguracja ograniczenia zostanie utracona.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Table constraint number %s (%s) is not configured correctly.} {Ograniczenie tabeli numer %s (%s) nie jest skonfigurowane poprawnie.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {There's no column defined.} {Brak zdefiniowanej kolumny.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {There is already a table with name '%s'. Please change the name of this table.} {Istnieje już tabela o nazwie '%s'. Proszę wybrać inną nazwę dla tej tabeli.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {There is already an index with name '%s'. Please change the name of this index.} {Istnieje już indeks o nazwie '%s'. Proszę wybrać inną nazwę dla tego indeksu.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {There is already a trigger with name '%s'. Please change the name of this trigger.} {Istnieje już wyzwalacz o nazwie '%s'. Proszę wybrać inną nazwę dla tego wyzwalacza.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {There is already a view with name '%s'. Please change the name of this view.} {Istnieje już widok o nazwie '%s'. Proszę wybrać inną nazwę dla tego widoku.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Nie można zanalizować DDLa dla wyzwalacza '%s',
więc nie można go odtworzyć po modyfikacji tabeli.
Chcesz kontynuować?}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Trigger parsing problem} {Problem analizy wyzwalacza.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Nie można zanalizować DDLa dla indeksu '%s',
więc nie będzie go można odtworzyć po modyfikacji tabeli.
Czy chcesz kontynuować?}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Index parsing problem} {Problem analizy indeksu}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Nie można zanalizować DDL dla widoku '%s',
więc nie będzie go można odtworzyć po modyfikacji tabeli.
Czy chcesz kontynuować?}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {View parsing problem} {Problem analizy widoku}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.} {Nie można było zanalizować DDL dla następujących tabeli, dlatego też żaden z kluczy obcych odwołujących się do tabeli '%s' nie będzie odtworzony::

%s.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {%s(%s) referencing %s(%s)} {%s(%s) nawiązujący do %s(%s)}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s} {Następujące klucze obce nie zostaną odtworzone, ponieważ nie byłyby one poprawne:

%s}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Do you want to continue anyway?} {Czy mimo to chcesz kontynuować?}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?} {Następujące tabele nie zostaną odtworzone z odpowiednimi kluczami obcymi w związku z błędami bazy danych:

%s

Czy mimo to chcesz kontynuować?}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Modifying table...} {Modyfikowanie tabeli...}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Modifying table '%s'.} {Modyfikowanie tabeli '%s'.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Could not recreate triggers for modified table.} {Nie można odtworzyć wyzwalaczy dla zmodyfikowanej tabeli.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Could not recreate indexes for modified table.} {Nie można odtworzyć indeksów dla zmodyfikowanej tabeli.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Could not recreate views for modified table.} {Nie można odtworzyć widoków dla zmodyfikowanej tabeli.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?} {Nie będzie możliwe odtworzenie wyzwalacza '%s' po modyfikacji tabeli.
Czy chcesz kontynuować mimo to?}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Trigger recreation problem} {Problem odtworzenia wyzwalacza}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?} {Nie będzie można odtworzyć indeksu '%s' po modyfikacji tabeli.
Czy chcesz kontynuować mimo tego?}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Index recreation problem} {Problem odtworzenia indeksu}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {Could not recreate foreign keys for tables referencing modified table.} {Nie można odtworzyć kluczy obcych dla tabel odwołujących się do zmodyfikowanej tabeli.}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?} {Nie będzie możliwe odtworzenie widoku '%s' po modyfikacji tabeli.
Czy mimo to chcesz kontynuować?}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {View recreation problem} {Problem odtwarzania widoku}

### File: ../src/dialogs/table_dialog.tcl
mcset pl_pl {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).} {Nie możesz użyć wszystkich czterech znaków cytowania SQL (%s, %s, %s, oraz %s) w nazwie jednego obiektu (którym jest: %s).}

### File: ../src/dialogs/table_dialog_chk.tcl
mcset pl_pl {Condition expression cannot be empty.} {Wyrażenie warunkowe nie może być puste.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset pl_pl {What would you like to do?} {Co chcesz zrobić?}

### File: ../src/dialogs/new_version_dialog.tcl
mcset pl_pl {Install it automatically} {Zainstaluj automatycznie}

### File: ../src/dialogs/new_version_dialog.tcl
mcset pl_pl {Go to download page} {Przejdź do strony pobierania}

### File: ../src/dialogs/new_version_dialog.tcl
mcset pl_pl {Package download} {Pobieranie paczki}

### File: ../src/dialogs/new_version_dialog.tcl
mcset pl_pl {Insufficient privileges to perform automatic update.} {Niewystarczające uprawnienia, aby przeprowadzić automatyczną aktualizację.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset pl_pl {Check for updates at startup} {Sprawdzaj dostępność aktualizacji na starcie}

### File: ../src/dialogs/new_version_dialog.tcl
mcset pl_pl {New version of SQLiteStudio is available: %s} {Nowa wersja SQLiteStudio jest dostępna: %s}

### File: ../src/dialogs/trigger_dialog_cols.tcl
mcset pl_pl {Trigger columns} {Kolumny wyzwalacza}

### File: ../src/dialogs/blob_edit.tcl
mcset pl_pl Commit Zatwierdź

### File: ../src/dialogs/bug_history.tcl
mcset pl_pl Clear Wyczyść

### File: ../src/dialogs/bug_history.tcl
mcset pl_pl {Reported on} {Zgłoszony dnia}

### File: ../src/dialogs/bug_history.tcl
mcset pl_pl Brief Opis

### File: ../src/dialogs/bug_history.tcl
mcset pl_pl URL URL

### File: ../src/dialogs/bug_history.tcl
mcset pl_pl Discussion Dyskusja

### File: ../src/dialogs/bug_history.tcl
mcset pl_pl {Clear reports} {Wyczyść reporty}

### File: ../src/dialogs/bug_history.tcl
mcset pl_pl {Do you want to clear whole bug reports history?} {Czy chcesz wyczyścić całą historię raportów błędów?}

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl Index Indeks

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl {Index name:} {Nazwa indeksu:}

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl Available Dostępne

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl Indexed Indeksowane

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl {Modifying index} {Modyfikowanie indeksu}

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl {Modifying index '%s'} {Modyfikowanie indeksu '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl {Creating index} {Tworzenie indeksu}

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl {Creating index '%s'} {Tworzenie indeksu '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?} {Unikatowy indeks nie może być stworzony,
ponieważ wybrane kolumny zawierają duplikaty.
Chcesz zobaczyć te wartości?}

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl {Unique values} {Wartości unikatowe}

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl {Same values for '%s'} {Takie same wartości dla '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl {You have to select at least one column.} {Musisz wybrać przynajmniej jedną kolumnę.}

### File: ../src/dialogs/index_dialog.tcl
mcset pl_pl {You have to specify index name.} {Musisz podać nazwę indeksu.}

### File: ../src/dialogs/functions_dialog.tcl
mcset pl_pl Implementation: Implementacja:

### File: ../src/dialogs/functions_dialog.tcl
mcset pl_pl Name: Nazwa:

### File: ../src/dialogs/functions_dialog.tcl
mcset pl_pl {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.} {Używaj $0, $1, $2, $3, ... - jako parametrów pozycyjnych,
które będą przekazane do funkcji.
Na przykład wywołanie my_function('x',5) wywoła
my_function z parametrami 'x' jako $0, oraz 5 jako $1.}

### File: ../src/dialogs/functions_dialog.tcl
mcset pl_pl {Cannot use two functions with same name! Change name for '%s'.} {Nie można użyć dwóch funkcji o tej samej nazwie! Zmień nazwę dla '%s'.}

### File: ../src/dialogs/functions_dialog.tcl
mcset pl_pl {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! } {Nie można używać 'tcl' lub 'sqlfile' dla nazw funkcji, te nazwy są zarezerwowane.! }

### File: ../src/dialogs/functions_dialog.tcl
mcset pl_pl {Function '%s' is not implemented!} {Funkcja '%s' nie jest zaimplementowana!}

### File: ../src/dialogs/functions_dialog.tcl
mcset pl_pl {Delete function} {Usuń funkcję}

### File: ../src/dialogs/functions_dialog.tcl
mcset pl_pl {Are you sure you want to delete function '%s'?} {Czy na pewno chcesz usunąć funkcję '%s'?}

### File: ../src/mainwindow.tcl
mcset pl_pl {Connect to selected database} {Podłącz do wybranej bazy}

### File: ../src/mainwindow.tcl
mcset pl_pl {Disconnect from selected database} {Odłącz od wybranej bazy}

### File: ../src/mainwindow.tcl
mcset pl_pl {Remove selected database from list} {Usuń wybraną bazę z listy}

### File: ../src/mainwindow.tcl
mcset pl_pl {New table} {Nowa tabela}

### File: ../src/mainwindow.tcl
mcset pl_pl {Drop table} {Porzuć tabelę}

### File: ../src/mainwindow.tcl
mcset pl_pl {Drop index} {Porzuć indeks}

### File: ../src/mainwindow.tcl
mcset pl_pl {Drop trigger} {Porzuć wyzwalacz}

### File: ../src/mainwindow.tcl
mcset pl_pl {Edit view} {Edytuj widok}

### File: ../src/mainwindow.tcl
mcset pl_pl {Drop view} {Porzuć widok}

### File: ../src/mainwindow.tcl
mcset pl_pl {Arrange cascade windows layout} {Ustaw okna kaskadowo}

### File: ../src/mainwindow.tcl
mcset pl_pl {Arrange intelligent windows layout} {Rozstaw okna inteligentnie}

### File: ../src/mainwindow.tcl
mcset pl_pl {Refresh databases tree (%s)} {Odśwież drzewo baz danych (%s)}

### File: ../src/mainwindow.tcl
mcset pl_pl {Open SQL query editor} {Otwórz edytor zapytań SQL}

### File: ../src/mainwindow.tcl
mcset pl_pl {Settings (%s)} {Ustawienia (%s)}

### File: ../src/mainwindow.tcl
mcset pl_pl {Open SQL functions editor} {Otwórz edytor funkcji SQL}

### File: ../src/mainwindow.tcl
mcset pl_pl {Clear objects filter} {Wyczyść filtr obiektów}

### File: ../src/mainwindow.tcl
mcset pl_pl {Enter object name you want to look for} {Wpisz nazwę obiektu którego szukasz}

### File: ../src/mainwindow.tcl
mcset pl_pl Databases {Bazy danych}

### File: ../src/mainwindow.tcl
mcset pl_pl Tools Narzędzia

### File: ../src/mainwindow.tcl
mcset pl_pl Connect Podłącz

### File: ../src/mainwindow.tcl
mcset pl_pl Disconnect Odłącz

### File: ../src/mainwindow.tcl
mcset pl_pl {Remove from list} {Usuń z listy}

### File: ../src/mainwindow.tcl
mcset pl_pl {View main toolbar} {Pokaż główny pasek}

### File: ../src/mainwindow.tcl
mcset pl_pl {View structure toolbar} {Pokaż pasek struktury}

### File: ../src/mainwindow.tcl
mcset pl_pl {View windows toolbar} {Pokaż pasek okien}

### File: ../src/mainwindow.tcl
mcset pl_pl {View tools toolbar} {Pokaż pasek narzędzi}

### File: ../src/mainwindow.tcl
mcset pl_pl {View configuration toolbar} {Pokaż pasek konfiguracji}

### File: ../src/mainwindow.tcl
mcset pl_pl {Refresh databases tree} {Odśwież drzewo baz danych}

### File: ../src/mainwindow.tcl
mcset pl_pl {Custom SQL functions} {Własne funkcje SQL}

### File: ../src/mainwindow.tcl
mcset pl_pl {Export database} {Eksportuj bazę}

### File: ../src/mainwindow.tcl
mcset pl_pl {Export table or view} {Eksportuj tabelę lub widok}

### File: ../src/mainwindow.tcl
mcset pl_pl {Import data to a table} {Importuj dane do tabeli}

### File: ../src/mainwindow.tcl
mcset pl_pl {SQLiteStudio home page} {Strona domowa SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset pl_pl {SQLiteStudio manual} {Podręcznik SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset pl_pl {SQLite documentation} {Dokumentacja SQLite}

### File: ../src/mainwindow.tcl
mcset pl_pl {SQLiteStudio support forum} {Forum pomocy SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset pl_pl {Report a bug} {Zgłoś błąd}

### File: ../src/mainwindow.tcl
mcset pl_pl {Send feature request} {Wyślij propozycję nowej funkcjonalności}

### File: ../src/mainwindow.tcl
mcset pl_pl {Show bug reports history} {Pokaż historię raportów błędów}

### File: ../src/mainwindow.tcl
mcset pl_pl {Show tips window} {Pokaż okno wskazówek}

### File: ../src/mainwindow.tcl
mcset pl_pl ChangeLog {Lista zmian}

### File: ../src/mainwindow.tcl
mcset pl_pl Roadmap {Plan zmian}

### File: ../src/mainwindow.tcl
mcset pl_pl {Check for new version} {Sprawdź czy jest nowa wersja}

### File: ../src/mainwindow.tcl
mcset pl_pl Donate Wspomóż

### File: ../src/mainwindow.tcl
mcset pl_pl {Did you know that...} {Czy wiesz że...}

### File: ../src/mainwindow.tcl
mcset pl_pl {Editor %s} {Edytor %s}

### File: ../src/mainwindow.tcl
mcset pl_pl Settings Ustawienia

### File: ../src/mainwindow.tcl
mcset pl_pl {SQLiteStudio roadmap} {Plany zmian w SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset pl_pl {Can't start web browser, because:
%s} {Nie można uruchomić przeglądarki, ponieważ:
%s}

### File: ../src/mainwindow.tcl
mcset pl_pl {Can't start %s web browser, because:
%s} {Nie można uruchomić przeglądarki %s, ponieważ:
%s}

### File: ../src/mainwindow.tcl
mcset pl_pl {About SQLiteStudio} {O programie SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset pl_pl {SQLiteStudio ChangeLog} {SQLiteStudio lista zmian}

### File: ../src/mainwindow.tcl
mcset pl_pl {There is no new version available.} {Nie ma dostępnej nowej wersji.}

### File: ../src/mainwindow.tcl
mcset pl_pl {New version} {Nowa wersja}

### File: ../src/mainwindow.tcl
mcset pl_pl {Report bug} {Raportuj błąd}

### File: ../src/mainwindow.tcl
mcset pl_pl {Feature request} {Nowa funkcjonalność}

### File: ../src/mainwindow.tcl
mcset pl_pl {Reports history} {Historia raportów}

### File: ../src/mainwindow.tcl
mcset pl_pl {Reporting bug} {Raportowanie błędu}

### File: ../src/mainwindow.tcl
mcset pl_pl {Reporting bug to SQLiteStudio bugs database...} {Raportowanie błędu do bazy błędów SQLiteStudio...}

### File: ../src/mainwindow.tcl
mcset pl_pl {Problem occurred while reporting bug. You can ignore it and get back to your work.} {Wystąpił problem podczas zgłaszania błędu. Możesz to zignorować i wracać do swoich zajęć.}

### File: ../src/mainwindow.tcl
mcset pl_pl Ignore Ignoruj

### File: ../src/mainwindow.tcl
mcset pl_pl {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history} {Błąd został zgłoszony. Dziękuję! Zawsze możesz spojrzeć na dyskusję dotyczącą twojego zgłoszenia używając menu SQLiteStudio -> Pokaż historię raportów błędów}

### File: ../src/mainwindow.tcl
mcset pl_pl {A timeout occured while downloading new version. Try again, or download it manually.} {Minął maksymalny czas ściągania nowej wersji. Spróbuj ponownie lub ściągnij ją ręcznie.}

### File: ../src/mainwindow.tcl
mcset pl_pl {An error occured while downloading new version. Try again, or download it manually.} {Wystąpił błąd podczas ściągania nowej wersji. Spróbuj ponownie lub ściągnij ją ręcznie.}

### File: ../src/mainwindow.tcl
mcset pl_pl Downloading... Ściąganie...

### File: ../src/mainwindow.tcl
mcset pl_pl {Downloading SQLiteStudio v%s...} {Ściąganie SQLiteStudio v%s...}

### File: ../src/mainwindow.tcl
mcset pl_pl {Problem with saving new SQLiteStudio version to:
%s
Details:
%s} {Problem podczas zapisywania nowej wersji SQLiteStudio do:
%s
Szczegóły:
%s}

### File: ../src/mainwindow.tcl
mcset pl_pl {Problem with getting new SQLiteStudio version
Details:
%s} {Wystąpił problem podczas pobierania nowej wersji SQLiteStudio:
Szczegóły:
%s}

### File: ../src/mainwindow.tcl
mcset pl_pl {This is unknown binary distribution. Cannot determinate binary file to download for update.} {To jest nieznana dystrybucja binarna. Nie można określić pliku binarnego do ściągnięcia w celu aktualizacji.}

### File: ../src/data_editor.tcl
mcset pl_pl {There are uncommited rows.
Are you sure you want to close '%s' window anywy?} {Niektóre wiersze nie są zatwierdzone.
Czy na pewno chcesz zamknąć okno '%s'?}

### File: ../src/common/ddl_dialog.tcl
mcset pl_pl {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s} {Nie można przygotować DDLa. Konfiguracja jest niekompletna.
Szczegóły:
%s}

### File: ../src/common/color_picker.tcl
mcset pl_pl {Choose color} {Wybierz kolor}

### File: ../src/common/shortcut_edit.tcl
mcset pl_pl {Forbidden shortcut key combination: %s} {Zabroniona kombinacja klawiszy: %s}

### File: ../src/common/common.tcl
mcset pl_pl Copy Kopiuj

### File: ../src/common/common.tcl
mcset pl_pl Cut Wytnij

### File: ../src/common/common.tcl
mcset pl_pl Paste Wklej

### File: ../src/common/blob_edit_panel.tcl
mcset pl_pl {Text edit} {Edycja tekstowa}

### File: ../src/common/blob_edit_panel.tcl
mcset pl_pl {Hexadecimal edit} {Edycja heksadecymalna}

### File: ../src/common/common_sql.tcl
mcset pl_pl {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
} {Nie można otworzyć okna, ponieważ kod DDL żądanego obiektu nie jest obsługiwany przez tą wersję SQLiteStudio. Szczegóły:
}

### File: ../src/common/hex_editor.tcl
mcset pl_pl {Overwrite characters,
instead of inserting} {Nadpisuj znaki,
zamiast wstawiać}

### File: ../src/common/hex_editor.tcl
mcset pl_pl Processing Przetwarzanie

### File: ../src/common/hex_editor.tcl
mcset pl_pl {Processing data...} {Przetwarzanie danych...}

### File: ../src/sql_editor.tcl
mcset pl_pl {Replace dialog} {Okno zmiany}

### File: ../src/sql_editor.tcl
mcset pl_pl {Search dialog} {Okno wyszukiwania}

### File: ../src/trees/db_tree.tcl
mcset pl_pl Loading Ładowanie

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Loading database list} {Ładowanie listy baz danych}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Given database file doesn't exist or is unreadable.} {Podany plik bazy danych nie istnieje lub jest nieczytelny.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl Vacuum Odkurz

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Integrity check} {Sprawdzanie spójności}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Import schema from other database} {Importuj schemat z innej bazy}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Reset autoincrement for '%s'} {Zresetuj autoinkrementację dla '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Erase table data} {Wyczyść dane tabeli}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Create foreign key} {Utwórz klucz obcy}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Show view data} {Pokaż dane z widoku}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Export view} {Eksportuj widok}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Sort databases alphabetically} {Sortuj bazy alfabetycznie}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Given database is already on the list.} {Podana baza danych jest już na liście.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Given database name is already on the list.} {Podana nazwa bazy danych jest już na liście.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl Tables Tabele

### File: ../src/trees/db_tree.tcl
mcset pl_pl Views Widoki

### File: ../src/trees/db_tree.tcl
mcset pl_pl {SQLite system table} {Tabela systemowa SQLite}

### File: ../src/trees/db_tree.tcl
mcset pl_pl Columns Kolumny

### File: ../src/trees/db_tree.tcl
mcset pl_pl {SQLite system index} {Indeks systemowy SQLite}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Remove database} {Usuń bazę danych z listy}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Are you sure you want to remove '%s' database from the list?} {Czy na pewno chcesz usunąć bazę '%s' z listy?}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.} {Tabela '%s' nie ma DDL. Prawdopodobnie jest to tabela systemowa i nie można jej otworzyć w oknie tabeli.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {'%s' is a virtual table, therefore cannot be browsed in table window.} {'%s' jest tabelą wirtualną, dlatego nie może być przedlądana w oknie tabeli.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Table '%s' has no DDL. Probably it's system table and should not be edited.} {Tabla '%s' nie ma DDL. Prawdopodobnie jest to tabela systemowa i nie może być edytowana.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {'%s' is a virtual table, therefore cannot be edited in table dialog.} {'%s' jest tabelą wirtualną, dlatego nie może być edytowana w oknie edycji tabeli.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.} {'%s' jest tabelą wirtualną. Tworzenie podobnej tabeli jest możliwe tylko dla zwykłych tabel SQLite.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Integrity check (%s)} {Sprawdzanie spójności (%s)}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Are you sure you want to DROP '%s' table?} {Czy na pewno chcesz porzucić tabelę '%s'?}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Dropping table} {Porzucanie tabeli}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Dropping table '%s'} {Porzucanie tabeli '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Dropping index} {Porzucanie indeksu}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Dropping index '%s'} {Porzucanie indeksu '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?} {Wyzwalacz '%s' ma nieprawidłową deklarację DDL. Nie możesz go edytować w oknie dialogowym. Musisz go porzucić i odtworzyć używając poprawnej składni.

SQLiteStudio może wstawić DDL tego wyzwalacza do nowego edytora SQL, aby zobaczyć co jest niepoprawne i naprawić to. Czy chcesz aby SQLiteStudio tak zrobiło?}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Fix trigger} {Napraw wyzwalacz}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.} {Wyzwalacz '%s' nie ma DDLa.
Prawdopodobnie jest to indeks systemowy i nie powinien być edytowany.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?} {Widok '%s' ma niepoprawną deklarację DDL. Nie można go edytować w oknie dialogowym. Musisz go porzucić i odtworzyć używając poprawnej składni.

SQLiteStudio może wstawić DDL tego widoku do nowego edytora SQL, aby zobaczyć co jest niepoprawne i naprawić to. Czy chcesz aby SQLiteStudio tak zrobiło?}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Fix view} {Napraw widok}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {View '%s' has no DDL. Probably it's system view and should not be edited.} {Widok '%s' nie ma DDL. Prawdopodobnie jest to widok systemowy i nie powinien być edytowany.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Delete view} {Usuń widok}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Are you sure you want to delete '%s' view?} {Czy na pewno chcesz usunąć widok '%s'?}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Erase data} {Wymaż dane}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Are you sure you want to delete all data from table '%s'?} {Czy na pewno chcesz usunąć wszystkie dane z tabeli '%s'?}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Deleting data} {Usuwanie danych}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Deleting data from table '%s'} {Usuwanie danych z tabeli '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {'%s' view data} {Dane z widoku '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Are you sure you want to make a vacuum?} {Czy na pewno chcesz wykonać vacuum?}

### File: ../src/trees/db_tree.tcl
mcset pl_pl Vacuuming Odkurzanie

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Vacuuming '%s'} {Odkurzanie '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {SQL files} {Pliki SQL}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Select SQL file to be executed} {Wybierz SQL do wykonania}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Error while executing SQL:
%s} {Błąd podczas wykonywania SQL:
%s}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {SQL executed sucessfly.} {SQL wykonany poprawnie.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Import database schema} {Importuj schemat bazy danych}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Database: %s} {Baza danych: %s}

### File: ../src/trees/db_tree.tcl
mcset pl_pl URI: URI:

### File: ../src/trees/db_tree.tcl
mcset pl_pl Version: Wersja:

### File: ../src/trees/db_tree.tcl
mcset pl_pl {File size:} {Rozmiar pliku:}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Schema version:} {Wersja schematu:}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Virtual table} {Tabela wirtualna}

### File: ../src/trees/db_tree.tcl
mcset pl_pl Indexes: Indeksy:

### File: ../src/trees/db_tree.tcl
mcset pl_pl Triggers: Wyzwalacze:

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Column: %s} {Kolumna: %s}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Not null} {Nie null}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Indexed table:} {Indeksowana tabela:}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copy index '%s' for table '%s'} {Skopiuj indeks '%s' do tabeli '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Move index '%s' to table '%s'} {Przenieś indeks '%s' do tabeli '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copy trigger '%s' for table '%s'} {Skopiuj wyzwalacz '%s' do tabeli '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Move trigger '%s' to table '%s'} {Przenieś wyzwalacz '%s' do tabeli '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copy view '%s' for database '%s'} {Skopiuj widok '%s' do bazy '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Move view '%s' to database '%s'} {Przenieś widok '%s' do bazy '%s'}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {View '%s' has no DDL, therefore cannot be edited.} {Widok '%s' nie ma DDL, w związku z czym nie może być edytowany.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copy view} {Skopiuj widok}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Move view} {Przenieś widok}

### File: ../src/trees/db_tree.tcl
mcset pl_pl Move Przenieś

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copy index} {Skopiuj indeks}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Move index} {Przenieś indeks}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copy trigger} {Skopiuj wyzwalacz}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Move trigger} {Przenieś wyzwalacz}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copy table '%s' to database '%s' (include data, indexes and triggers)} {Skopiuj tabelę '%s' do bazy '%s' (włącznie z danymi, indeksami i wyzwalaczami)}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copy table '%s' to database '%s' (include data)} {Skopiuj tabelę '%s' do bazy '%s' (włącznie z danymi)}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copy table '%s' to database '%s' (include indexes and triggers)} {Skopiuj tabelę '%s' do bazy '%s' (włącznie z indeksami i wyzwalaczami)}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copy table '%s' to database '%s' (skip data, indexes and triggers)} {Skopiuj tabelę '%s' do bazy '%s' (pomin dane, indeksy i wyzwalacze)}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Move table '%s' to database '%s' (include data, indexes and triggers)} {Przenieś tabelę '%s' do bazy '%s' (włącznie z danymi, indeksami i wyzwalaczami)}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Move table '%s' to database '%s' (include data)} {Przenieś tabelę '%s' do bazy '%s' (włącznie z danymi)}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Move table '%s' to database '%s' (include indexes and triggers)} {Przenieś tabelę '%s' do bazy '%s' (włącznie z indeksami i wyzwalaczami)}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Move table '%s' to database '%s' (skip data, indexes and triggers)} {Przenieś tabelę '%s' do bazy '%s' (pomin dane, indeksy i wyzwalacze)}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copying table...} {Kopiowanie tabeli...}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Copying table '%s' from '%s' to '%s'.} {Kopiowanie tabeli '%s' z '%s' do '%s'.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Moving table...} {Przenoszenie tabeli...}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Moving table '%s' from '%s' to '%s'.} {Przenoszenie tabeli '%s' z '%s' do '%s'.}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Could not create object in target database:
%s} {Nie powiodło się tworzenie obiektu w bazie docelowej:
%s}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Could not copy data:
%s} {Nie powiodło się kopiowanie danych:
%s}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Could not copy table data from source database to target database. Details: %s} {Nie powiodło się kopiowanie danych tabeli z bazy źródłowej do bazy docelowej. Szczegóły: %s}

### File: ../src/trees/db_tree.tcl
mcset pl_pl {Could not delete object(s) from source database. Details: %s} {Nie powiodło się usuwanie obiektu(ów) z bazy źródłowej. Szczegóły: %s}

### File: ../src/grids/dbgrid.tcl
mcset pl_pl {Edit BLOB entry:} {Edytuj wpis typu BLOB:}

### File: ../src/grids/dbgrid.tcl
mcset pl_pl {BLOB edit} {Edycja BLOB}

### File: ../src/grids/dbgrid.tcl
mcset pl_pl {Cannot commit. Details:
%s} {Nie można zatwierdzić. Szczegóły:
%s}

### File: ../src/grids/grid.tcl
mcset pl_pl {You have to select a cell before paste any contents.} {Musisz wybrać komórkę, aby wkleić zawartość.}

### File: ../src/grids/grid.tcl
mcset pl_pl {Cut data} {Wytnij dane}

### File: ../src/grids/grid.tcl
mcset pl_pl {There are too many columns or rows to paste. Do you want to cut them and paste?} {Jest zbyt wiele kolumn lub wierszy do wklejenia. Czy chcesz je obciąć przed wklejeniem?}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Insert new row} {Dodaj nowy wiersz}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Delete selected rows} {Usuń zaznaczone wiersze}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Edit cell value} {Edytuj warość komórki}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Edit cell value in BLOB editor} {Edytuj wartość komórki w edytorze BLOB}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Duplicate row} {Zduplikuj wiersz}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Set NULL value} {Ustaw wartość NULL}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Generate SELECT from selected cells} {Wygeneruj SELECT z wybranych komórek}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Commit selected cells} {Zatwiedź wybrane komórki}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Rollback selected cells} {Wycofaj wybrane komórki}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Select all} {Zaznacz wszystko}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Show ordinals} {Pokaż liczbę porządkową}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Show ROWIDs} {Pokaż ROWID}

### File: ../src/grids/data_grid.tcl
mcset pl_pl Type: Typ:

### File: ../src/grids/data_grid.tcl
mcset pl_pl Constraints: Ograniczenia:

### File: ../src/grids/data_grid.tcl
mcset pl_pl {%s column has NOT NULL constraint. You have to fill value for it.} {Kolumna %s ma ograniczenie NOT NULL. Musisz podać dla niej wartość.}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Error while adding new row:
%s} {Błąd podczas dodawania nowego wiersza:
%s}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Error while updating new row:
%s} {Błąd podczas aktualizowania nowego wiersza:
%s}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Error while updating cell value:
%s

What would you like to do?} {Błąd podczas aktualizacji wartości komórki:
%s

Co chcesz zrobić?}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Re-edit value} {Edytować ponownie}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Return to value before edition} {Powrócić do poprzedniej wartości}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Cannot delete row(s), because it violates constraint. Details:
%s} {Nie można usunąć wiersza(y), ponieważ ta operacja narusza ograniczenie. Szczegóły:
%s}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {Error while deleting selected rows:
%s} {Błąd podczas usuwania wybranych wierszy:
%s}

### File: ../src/grids/data_grid.tcl
mcset pl_pl {SQL query generated at %s
using selected cells from window '%s'.} {Zapytanie SQL wygenerowane dnia %s
używając zaznaczonych komórek z okna '%s'.}

### File: ../src/grids/result_grid.tcl
mcset pl_pl {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.} {Nie można edytować kolumny '%s'. Tylko kolumny z odpowiednim ROWID w tabeli mogą być edytowane, lub zapytanie SQL było zbyt skomplikowane.}

### File: ../src/grids/result_grid.tcl
mcset pl_pl {Data type:} {Typ danych:}

### File: ../src/grids/result_grid.tcl
mcset pl_pl {No details are available on this cell.} {Brak detali dla tej komórki.}

### File: ../src/grids/result_grid.tcl
mcset pl_pl {Duplicated ROWID} {Zduplikowane ROWID}

### File: ../src/grids/result_grid.tcl
mcset pl_pl {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?} {Występuje więcej niż jeden wiersz z ROWID=%s biorący udział w operacji wklejania.
W tej sytuacji mogą nastąpić nieprzewidywalne skutki. Kontynuować?}

### File: ../src/grids/result_grid.tcl
mcset pl_pl {Could not parse SQL while trying to generate requested query: %s} {Nie można zanalizować SQLa, gdy próbowano wygenerować żądane zapytanie: %s}

### File: ../src/grids/result_grid.tcl
mcset pl_pl {Cannot use '%s' statement to generate requested query.} {Nie można użyć deklaracji '%s' do wygenerowania żądanego zapytania.}

### File: ../src/grids/result_grid.tcl
mcset pl_pl {Cannot determinate selected column with ID=%s.} {Nie można określić wybranej kolumny z ID=%s.}

### File: ../src/grids/result_grid.tcl
mcset pl_pl {Error occurred while trying to generate the query: %s} {Wystąpił błąd podczas próby wygenerowania zapytania:: %s}

### File: ../src/grids/result_grid.tcl
mcset pl_pl {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s} {Zapytanie SQL zostało wygenerowane dnia %s
z użyciem zaznaczonych wyników z okna '%s'.
Oryginalne zapytanie wyglądało następująco:
%s}
