# SQLiteStudio 'ru' localization file

# Unchanged translations

### File: ../src/cfg_win.tcl
mcset ru Ok ОК

### File: ../src/cfg_win.tcl
mcset ru Apply Применить

### File: ../src/cfg_win.tcl
mcset ru Cancel Отмена

### File: ../src/cfg_win.tcl
mcset ru Theme Тема

### File: ../src/cfg_win.tcl
mcset ru {Select theme to use:} {Выберите тему:}

### File: ../src/cfg_win.tcl
mcset ru {Theme version:} {Версия темы:}

### File: ../src/cfg_win.tcl
mcset ru Shortcuts {Сочетания клавиш}

### File: ../src/cfg_win.tcl
mcset ru {Global shortcuts} Общие

### File: ../src/cfg_win.tcl
mcset ru {Open SQL editor} {Открыть редактор SQL}

### File: ../src/cfg_win.tcl
mcset ru {Opens SQL editor window.} {Открывает окно редактора SQL.}

### File: ../src/cfg_win.tcl
mcset ru {Close selected task} Закрыть

### File: ../src/cfg_win.tcl
mcset ru {Closes active MDI window.} {Закрывает активное окно.}

### File: ../src/cfg_win.tcl
mcset ru {Open settings} Настройки

### File: ../src/cfg_win.tcl
mcset ru {Opens SQLiteStudio settings window.} {Открывает окно настроек SQLiteStudio.}

### File: ../src/cfg_win.tcl
mcset ru {Next task} {Следующее окно}

### File: ../src/cfg_win.tcl
mcset ru {Switches task (window) to next, placed on the right from active task on taskbar.} {Переключается на следующее окно, расположенное на панели задач справа от активного окна.}

### File: ../src/cfg_win.tcl
mcset ru {Next task (alternative)} {Следующее окно (альтернатива)}

### File: ../src/cfg_win.tcl
mcset ru {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Переключается на следующее окно, расположенное на панели задач справа от активного окна.
Альтернативное сочетание клавиш.}

### File: ../src/cfg_win.tcl
mcset ru {Previous task} {Предыдущее окно}

### File: ../src/cfg_win.tcl
mcset ru {Switches task (window) to previous, placed on the left from active task on taskbar.} {Переключается на предыдущее окно, расположенное на панели задач справа от активного окна.}

### File: ../src/cfg_win.tcl
mcset ru {Previous task (alternative)} {Предыдущее окно (альтернатива)}

### File: ../src/cfg_win.tcl
mcset ru {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Переключается на предыдущее окно, расположенное на панели задач слева от активного окна.
Альтернативное сочетание клавиш.}

### File: ../src/cfg_win.tcl
mcset ru {Editor and table window shortcuts} {Редактор и таблицы}

### File: ../src/cfg_win.tcl
mcset ru {SQL editor completion} {Автодополнение SQL-кода в редакторе}

### File: ../src/cfg_win.tcl
mcset ru {Invokes SQL completion in editor window.} {Вызывает автодополнение SQL-кода в окне редактора.}

### File: ../src/cfg_win.tcl
mcset ru {Execute SQL query} {Выполнить SQL-запрос}

### File: ../src/cfg_win.tcl
mcset ru {Executes SQL query typed in editor.} {Выполнение SQL-запроса, набранного в редакторе.}

### File: ../src/cfg_win.tcl
mcset ru {Explain SQL query} {План запроса SQL}

### File: ../src/cfg_win.tcl
mcset ru {Calls EXPLAIN on SQL query typed in editor.} {Показывает план выполнения SQL-запроса, набранного в редакторе.}

### File: ../src/cfg_win.tcl
mcset ru {Format SQL code} {Форматировать код SQL}

### File: ../src/cfg_win.tcl
mcset ru {Formats SQL code typed in editor.} {Форматирует код SQL, набранный в редакторе.}

### File: ../src/cfg_win.tcl
mcset ru {Load SQL from file} {Загрузить код SQL из файла}

### File: ../src/cfg_win.tcl
mcset ru {Loads SQL from file to the editor.} {Загружает код SQL из файла в редактор.}

### File: ../src/cfg_win.tcl
mcset ru {Save SQL to file} {Сохранить код SQL в файл}

### File: ../src/cfg_win.tcl
mcset ru {Saves contents of the editor into a file.} {Сохраняет содержимое редактора в файл.}

### File: ../src/cfg_win.tcl
mcset ru {Execute SQL from file} {Выполнить SQL-запрос из файла}

### File: ../src/cfg_win.tcl
mcset ru {Executes SQL directly from file, without loading it to the editor.} {Выполняет SQL-запрос напрямую из файла, не загружая его в редактор.}

### File: ../src/cfg_win.tcl
mcset ru {Next tab} {Следующая вкладка}

### File: ../src/cfg_win.tcl
mcset ru {Switches to next tab of editor window (result or history).} {Переключается на следующую вкладку редактора.}

### File: ../src/cfg_win.tcl
mcset ru {Previous tab} {Предыдущая вкладка}

### File: ../src/cfg_win.tcl
mcset ru {Switches to previous tab of editor window (query or result).} {Переключается на предыдущую вкладку редактора.}

### File: ../src/cfg_win.tcl
mcset ru {Next subtab} {Следующая подвкладка}

### File: ../src/cfg_win.tcl
mcset ru {Switches to next subtab (form view in results tab).} {Переключается на следующую подвкладку (режим формы на вкладке результатов).}

### File: ../src/cfg_win.tcl
mcset ru {Previous subtab} {Предыдущая подвкладка}

### File: ../src/cfg_win.tcl
mcset ru {Switches to previous subtab (grid view in results tab).} {Переключается на предыдущую подвкладку (режим таблицы на вкладке результатов).}

### File: ../src/cfg_win.tcl
mcset ru Refresh Обновить

### File: ../src/cfg_win.tcl
mcset ru {Re-executes SQL query so results data is refreshed.} {Повторно выполняет SQL-запрос для обновления результатов.}

### File: ../src/cfg_win.tcl
mcset ru {Delete selected row} {Удалить выбранную строку}

### File: ../src/cfg_win.tcl
mcset ru {Deletes selected row.} {Удаляет выбранную строку.}

### File: ../src/cfg_win.tcl
mcset ru {Add new row} {Добавить новую строку}

### File: ../src/cfg_win.tcl
mcset ru {Adds new empty row without commiting it.} {Добавляет пустую строку без фиксации транзакции.}

### File: ../src/cfg_win.tcl
mcset ru {Erase cells data} {Удалить данные из ячеек}

### File: ../src/cfg_win.tcl
mcset ru {Erases data of selected cells.} {Удаляет данные из выделенных ячеек.}

### File: ../src/cfg_win.tcl
mcset ru {Next editor database in list} {Следующая база данных в списке}

### File: ../src/cfg_win.tcl
mcset ru {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)} {Переключается на следующую базу данных в списке
(выпадающий список в верхней части окна редактора)}

### File: ../src/cfg_win.tcl
mcset ru {Previous editor database in list} {Предыдущая база данных в списке}

### File: ../src/cfg_win.tcl
mcset ru {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)} {Переключается на предыдущую базу данных в списке
(выпадающий список в верхней части окна редактора)}

### File: ../src/cfg_win.tcl
mcset ru {Jump to first row in Form View} {Перейти к первой строке в режиме формы}

### File: ../src/cfg_win.tcl
mcset ru {Jumps to first row of query results grid
or table data preview grid in Form View.} {Переходит к первой строке результатов запроса
или таблицы в режиме формы.}

### File: ../src/cfg_win.tcl
mcset ru {Go to previous row in Form View} {Перейти к предыдущей строке в режиме формы}

### File: ../src/cfg_win.tcl
mcset ru {Goes to previous row of query results grid
or table data preview grid row in Form View.} {Переходит к предыдущей строке результатов запроса
или табличных данных в режиме формы.}

### File: ../src/cfg_win.tcl
mcset ru {Go to next row in Form View} {Перейти к следующей строке в режиме формы}

### File: ../src/cfg_win.tcl
mcset ru {Goes to next row of query results grid
or table data preview grid row in Form View.} {Переходит к следующей строке результатов запроса
или табличных данных в режиме формы.}

### File: ../src/cfg_win.tcl
mcset ru {Jump to last row in Form View} {Перейти к последней строке в режиме формы}

### File: ../src/cfg_win.tcl
mcset ru {Jumps to last row of query results grid
or table data preview grid in Form View.} {Переходит к последней строке результатов запроса
или табличных данных в режиме формы.}

### File: ../src/cfg_win.tcl
mcset ru Plugins Плагины

### File: ../src/cfg_win.tcl
mcset ru {SQL formatter plugins} {Модули форматирования SQL}

### File: ../src/cfg_win.tcl
mcset ru {Use following SQL formatter plugin:} {Использовать следующий модуль форматирования SQL:}

### File: ../src/cfg_win.tcl
mcset ru {Configure formatter plugin} {Настроить модуль форматирования}

### File: ../src/cfg_win.tcl
mcset ru Configure Настроить

### File: ../src/cfg_win.tcl
mcset ru {Populating plugins} {Механизмы заполнения таблиц}

### File: ../src/cfg_win.tcl
mcset ru {Default table populating plugin:} {Механизм заполнения таблиц по умолчанию:}

### File: ../src/cfg_win.tcl
mcset ru Miscellaneous Разное

### File: ../src/cfg_win.tcl
mcset ru {Restore session after next start} {Восстанавливать предыдущее состояние при запуске}

### File: ../src/cfg_win.tcl
mcset ru {All windows and their contents (such as SQL code)
will be restored while next application startup.} {Все окна, а также их содержимое (например, SQL-запросы)
будут восстановлены при следующем запуске программы.}

### File: ../src/cfg_win.tcl
mcset ru {Show line numbers in SQL editor} {Номера строк в редакторе SQL}

### File: ../src/cfg_win.tcl
mcset ru {All SQL editor windows will contain line numbers on the left side of window.} {В каждом окне редактора SQL слева будут отображаться номера строк.}

### File: ../src/cfg_win.tcl
mcset ru {Underline syntax errors in SQL editor} {Подчёркивать синтаксические ошибки в редакторе SQL}

### File: ../src/cfg_win.tcl
mcset ru {Makes errors to be marked with underline.
You can also define foreground and background color for errors.} {Активирует пометку ошибок подчёркиванием.
Также можно выбрать цвет текста и фона ошибок.}

### File: ../src/cfg_win.tcl
mcset ru {Show SQLite system tables and indexes in databases tree} {Показывать системные таблицы и индексы SQLite в дереве баз данных}

### File: ../src/cfg_win.tcl
mcset ru {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.} {Если опция активирована, системные таблицы SQLite (с названиями вида 'sqlite_*')
и индексы (с названиями вида '(*autoindex*)') отображаюся в дереве баз данных.}

### File: ../src/cfg_win.tcl
mcset ru {Open items with single mouse click in databases tree} {Открывать объекты в дереве баз данных по одинарному щелчку}

### File: ../src/cfg_win.tcl
mcset ru {Items in database tree are open by double click by default.
This option switches it to single click.} {По умолчанию объекты в дереве баз данных открываются по двойному щелчку.
Эта опция активирует открытие по одинарному щелчку.}

### File: ../src/cfg_win.tcl
mcset ru {Do not show 'did you know that...' dialog at startup.} {Не показывать 'Советы' при запуске.}

### File: ../src/cfg_win.tcl
mcset ru {Uncheck this option to show the dialog.} {Отключите эту настройку для отображения окна советов.}

### File: ../src/cfg_win.tcl
mcset ru {Check for updates at startup.} {Проверять обновления при запуске.}

### File: ../src/cfg_win.tcl
mcset ru {If enabled, application will will check
for new version available at startup.} {Если опция активирована, приложение будет проверять наличие
новой версии при запуске.}

### File: ../src/cfg_win.tcl
mcset ru {Sort custom SQL functions list by name} {Сортировать список функций SQL по названиям}

### File: ../src/cfg_win.tcl
mcset ru {This list is placed in Custom SQL funcions dialog.} {Список в окне пользовательских функций SQL.}

### File: ../src/cfg_win.tcl
mcset ru {Ask if clipboard contents should be cut} {Подтверждать обрезку данных из буфера обмена}

### File: ../src/cfg_win.tcl
mcset ru {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.} {Если включена данная настройка, программа будет спрашивать,
надо ли вырезать содержимое буфера обмена при вставке,
в случае несовпадения формата данных в буфере обмена и таблице.
Если настройка отключена, программа будет вырезать
содержимое без подтверждения.}

### File: ../src/cfg_win.tcl
mcset ru {More results per page causes slower loading of single data page. Value 1000 should be right.} {Значения  свыше 1000 приведут к замедлению загрузки страницы данных.}

### File: ../src/cfg_win.tcl
mcset ru {History entries limit:} {Количество строк в истории:}

### File: ../src/cfg_win.tcl
mcset ru {Number of rows to remember in SQL editor history.} {Количество строк в истории редактора SQL.}

### File: ../src/cfg_win.tcl
mcset ru {Web browser:} Браузер:

### File: ../src/cfg_win.tcl
mcset ru {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.} {Вы можете просто ввести команду запуска браузера. Путь должен быть прописан в переменной PATH.
Открываемый адрес будет передан как аргумент указанной команды.}

### File: ../src/cfg_win.tcl
mcset ru Language: Язык:

### File: ../src/cfg_win.tcl
mcset ru {Tab in table window on open:} {При открытии таблицы отображать:}

### File: ../src/cfg_win.tcl
mcset ru {Table structure} {Структуру таблицы}

### File: ../src/cfg_win.tcl
mcset ru {Table data} {Данные таблицы}

### File: ../src/cfg_win.tcl
mcset ru {Select which tab should be opened for start in table window,
when you just opened that window.} {Выберите вкладку, которая будет отображаться при открытии таблицы}

### File: ../src/cfg_win.tcl
mcset ru {Editor window results layout} {Расположение окна с результатами выполнения запросов в редакторе}

### File: ../src/cfg_win.tcl
mcset ru {Show results in separated tab} {Отображать результаты в отдельной вкладке}

### File: ../src/cfg_win.tcl
mcset ru {Show results in frame below query} {Отображать результаты во фрейме внизу запроса}

### File: ../src/cfg_win.tcl
mcset ru {Plain text results} {Результаты в текстовом виде}

### File: ../src/cfg_win.tcl
mcset ru {Display NULL values as:} {Отображать NULL-значения как:}

### File: ../src/cfg_win.tcl
mcset ru {Maximum column width:} {Максимальная ширина столбца:}

### File: ../src/cfg_win.tcl
mcset ru {Values longer than specified here will be cut in plain text results.} {Значения, длина которых превышает указанную,
будут обрезаны при отображении в текстовом виде.}

### File: ../src/cfg_win.tcl
mcset ru Colors Цвета

### File: ../src/cfg_win.tcl
mcset ru {Global colors} Основные

### File: ../src/cfg_win.tcl
mcset ru {MDI windows title bar background color} {Заголовок окна}

### File: ../src/cfg_win.tcl
mcset ru {MDI windows title bar foreground color} {Текст заголовка окна}

### File: ../src/cfg_win.tcl
mcset ru {MDI windows title bar button background color} {Фон кнопки заголовка окна}

### File: ../src/cfg_win.tcl
mcset ru {MDI windows title bar active button background color} {Фон кнопки заголовка окна при нажатии}

### File: ../src/cfg_win.tcl
mcset ru {SQL Editor} {Редактор SQL}

### File: ../src/cfg_win.tcl
mcset ru {Editor standard font color} {Шрифт редактора}

### File: ../src/cfg_win.tcl
mcset ru {Editor background} {Фон редактора}

### File: ../src/cfg_win.tcl
mcset ru {Selected foreground color} {Выбранные элементы}

### File: ../src/cfg_win.tcl
mcset ru {Selected background color} {Фон выбранных элементов}

### File: ../src/cfg_win.tcl
mcset ru {Disabled background color} {Фон заблокированных элементов}

### File: ../src/cfg_win.tcl
mcset ru {Tables color} {Названия таблиц}

### File: ../src/cfg_win.tcl
mcset ru {Brackets color} Скобки

### File: ../src/cfg_win.tcl
mcset ru {Square brackets color} {Квадратные скобки}

### File: ../src/cfg_win.tcl
mcset ru {Keywords color} {Ключевые слова}

### File: ../src/cfg_win.tcl
mcset ru {Variables color} Переменные

### File: ../src/cfg_win.tcl
mcset ru {Strings color} Строки

### File: ../src/cfg_win.tcl
mcset ru {Comments color} Комментарии

### File: ../src/cfg_win.tcl
mcset ru {Matched brackets foreground color} {Подсвечиваемые скобки}

### File: ../src/cfg_win.tcl
mcset ru {Matched brackets background color} {Фон подсвечиваемых скобок}

### File: ../src/cfg_win.tcl
mcset ru {Syntax error color} {Синтаксические ошибки}

### File: ../src/cfg_win.tcl
mcset ru {Tcl editor} {Редактор Tcl}

### File: ../src/cfg_win.tcl
mcset ru {Options color} Опции

### File: ../src/cfg_win.tcl
mcset ru {Quoted character color} {Текст в кавычках}

### File: ../src/cfg_win.tcl
mcset ru {Trees colors} Дерево

### File: ../src/cfg_win.tcl
mcset ru {Tree background} Фон

### File: ../src/cfg_win.tcl
mcset ru {Tree standard font color} {Стандартный шрифт}

### File: ../src/cfg_win.tcl
mcset ru {Tree selected background color} {Фон выделенного элемента}

### File: ../src/cfg_win.tcl
mcset ru {Tree selected foreground color} {Выделенный элемент}

### File: ../src/cfg_win.tcl
mcset ru {Color for number of objects in tree branch} {Индикатор количества элементов}

### File: ../src/cfg_win.tcl
mcset ru {Grids colors} Таблицы

### File: ../src/cfg_win.tcl
mcset ru {Grid background} Фон

### File: ../src/cfg_win.tcl
mcset ru {Grid standard font color} {Стандартный шрифт}

### File: ../src/cfg_win.tcl
mcset ru {Grid selected background color} {Фон выбранных ячеек}

### File: ../src/cfg_win.tcl
mcset ru {Grid selected foreground color} {Выбранные ячейки}

### File: ../src/cfg_win.tcl
mcset ru {Grid base column background color} {Фон базового столбца}

### File: ../src/cfg_win.tcl
mcset ru {Foreground color for cells with NULL value} {Ячейки с NULL-значениями}

### File: ../src/cfg_win.tcl
mcset ru {Status fields colors} {Поля состояния}

### File: ../src/cfg_win.tcl
mcset ru {Background color} Фон

### File: ../src/cfg_win.tcl
mcset ru {Foreground color} Текст

### File: ../src/cfg_win.tcl
mcset ru {Error foreground color} {Текст ошибки}

### File: ../src/cfg_win.tcl
mcset ru {Information foreground color} {Текст информационного сообщения}

### File: ../src/cfg_win.tcl
mcset ru {Information (second kind) foreground color} {Текст информационного сообщения (второй вид)}

### File: ../src/cfg_win.tcl
mcset ru {Miscellaneous colors} Прочее

### File: ../src/cfg_win.tcl
mcset ru {Context hints background color} {Фон подсказок}

### File: ../src/cfg_win.tcl
mcset ru {Context hints foreground color} {Текст подсказок}

### File: ../src/cfg_win.tcl
mcset ru Fonts Шрифты

### File: ../src/cfg_win.tcl
mcset ru {SQL editor font} {Редактор SQL}

### File: ../src/cfg_win.tcl
mcset ru {Status fields font} {Поля статуса}

### File: ../src/cfg_win.tcl
mcset ru {Grid font} Таблица

### File: ../src/cfg_win.tcl
mcset ru {Tree font} Дерево

### File: ../src/cfg_win.tcl
mcset ru {Tree additional labels font} {Дополнительные метки дерева}

### File: ../src/cfg_win.tcl
mcset ru {Context hints font} {Контекстные подсказки}

### File: ../src/cfg_win.tcl
mcset ru {Changed language needs application to be restarted.} {Для смены языка необходимо перезапустить программу.}

### File: ../src/cfg_win.tcl
mcset ru {SQL formatter options} {Параметры форматирования кода SQL}

### File: ../src/db/db_file_types.tcl
mcset ru {All SQLite Databases} {Все базы данных SQLite}

### File: ../src/db/db_file_types.tcl
mcset ru {SQLite 3 Databases} {Базы данных SQLite 3}

### File: ../src/db/db_file_types.tcl
mcset ru {SQLite 2 Databases} {Базы данных SQLite 2}

### File: ../src/db/db_file_types.tcl
mcset ru {All files} {Все файлы}

### File: ../src/db/query_executor.tcl
mcset ru {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.} {Встроенный парсер SQLiteStudio не смог корректно проанализировать запрос, поэтому он был передан в SQLite без каких-либо подстановок и иных модификаций.}

### File: ../src/db/query_executor.tcl
mcset ru {Invalid database name: %s} {Некорректное имя базы данных: %s}

### File: ../src/db/sqlite2.tcl
mcset ru {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)} {Произошла ошибка при вызове функции VACUUM для базы данных:
%s
(это сообщение напрямую из SQLite2)}

### File: ../src/db/db.tcl
mcset ru {An internal logic error in SQLite} {Внутренняя ошибка логики SQLite}

### File: ../src/db/db.tcl
mcset ru {Access permission denied} {Доступ запрещён}

### File: ../src/db/db.tcl
mcset ru {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.} {Невозможно продолжить операцию, т.к. база данных занята.
Возможно её использует другое приложение.}

### File: ../src/db/db.tcl
mcset ru {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.} {Невозможно продолжить операцию, т.к. объект базы данных заблокирован.
Возможно его использует другое приложение.}

### File: ../src/db/db.tcl
mcset ru {A malloc() failed} {Ошибка при вызове malloc()}

### File: ../src/db/db.tcl
mcset ru {Attempt to write a readonly database} {Попытка записи в базу данных, открытую только для чтения}

### File: ../src/db/db.tcl
mcset ru {Disk I/O error occurred} {Произошла ошибка дискового ввода/вывода}

### File: ../src/db/db.tcl
mcset ru {The database disk image is malformed} {Файл базы данных повреждён}

### File: ../src/db/db.tcl
mcset ru {Database is full} {База данных заполнена}

### File: ../src/db/db.tcl
mcset ru {Database lock protocol error} {Ошибка при блокировке базы данных}

### File: ../src/db/db.tcl
mcset ru {Database is empty} {База данных пуста}

### File: ../src/db/db.tcl
mcset ru {The database schema changed} {Структура базы данных изменилась}

### File: ../src/db/db.tcl
mcset ru {String or BLOB exceeds size limit} {Размер строки или BLOB превысил лимит}

### File: ../src/db/db.tcl
mcset ru {Library used incorrectly} {Некорректное использование библиотеки}

### File: ../src/db/db.tcl
mcset ru {Uses OS features not supported on host} {Использует функции ОС, недоступные на хосте}

### File: ../src/db/db.tcl
mcset ru {Authorization denied} {Ошибка авторизации}

### File: ../src/db/db.tcl
mcset ru {Auxiliary database format error} {Ошибка формата вспомогательной базы данных}

### File: ../src/db/db.tcl
mcset ru {2nd parameter to sqlite3_bind out of range} {Второй параметр в sqlite3_bind находится вне допустимых границ}

### File: ../src/db/db.tcl
mcset ru {File opened that is not a database file} {Открытый файл не является файлом базы данных}

### File: ../src/db/db.tcl
mcset ru {Error while opening %s database:
%s} {Ошибка открытия базы данных %s:
%s}

### File: ../src/db/db.tcl
mcset ru {Not enough parameters passed to function '%s'.} {Недостаточно параметров для функции '%s'.}

### File: ../src/db/db.tcl
mcset ru {Cannot read file: %s} {Не удалось прочитать файл: %s}

### File: ../src/db/sqlite3.tcl
mcset ru {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)} {Произошла ошибка при вызове функции VACUUM для базы данных:
%s
(это сообщение напрямую из SQLite3)}

### File: ../src/completion_routines.tcl
mcset ru {Problem with attaching database:
%s} {Проблема при присоединении базы данных:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset ru Abort Прервать

### File: ../src/plugins/sql_formatting/enterprise/format_s.tcl
mcset ru name Имя

### File: ../src/plugins/sql_formatting/basic.tcl
mcset ru {Reduce group of whitespaces into one whitespace.} {Заменить группу пробелов на один.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset ru {Uppercase keywords.} {Отображать ключевые слова заглавными буквами.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset ru {Separate ")" and after contents with single whitespace.} {Вставлять один пробел после закрывающей скобки.}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {SQLite3 only} {только SQLite3}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru Indentation Отступы

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {New lines} {Переносы строк}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {White spaces} Пробелы

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru Names Имена

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru Comments Комментарии

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Tab size:} {Шаг табуляции:}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Line up keywords in multi-line queries} {Выравнивать ключевые слова в многострочных запросах}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Ident contents of parenthesis block} {Отступы у содержимого блока в скобках}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Ident parenthesis block in new line} {Отступы у блока скобок на новой строке}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Before opening parenthesis in column definitions} {Перед открывающей скобкой в объявлении столбцов}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After opening parenthesis in column definitions} {После открывающей скобки в объявлении столбцов}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Before closinging parenthesis in column definitions} {Перед закрывающей скобкой в объявлении столбцов}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After closinging parenthesis in column definitions} {После закрывающей скобки в объявлении столбцов}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Before opening parenthesis in expressions} {Перед открывающей скобкой в выражениях}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After opening parenthesis in expressions} {После открывающей скобки в выражениях}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Before closinging parenthesis in expressions} {Перед закрывающей скобкой в выражениях}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After closinging parenthesis in expressions} {После закрывающей скобки в выражениях}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After comma} {После запятой}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After comma in function arguments list} {После запятой в списке аргументов функции}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After logical block of query} {После логического блока запроса}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After semicolon} {После точки с запятой}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Never before semicolon} {Не вставлять перед точкой с запятой}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Before comma in lists} {Перед запятой в списках}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After comma in lists} {После запятой в списках}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Before opening parenthesis} {Перед открывающей скобкой}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After opening parenthesis} {После открывающей скобки}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Before closing parenthesis} {Перед закрывающей скобкой}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After closing parenthesis} {После закрывающей скобки}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Before dot operator (in path to database object)} {Перед точкой (в путях к объектам базы данных)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After dot operator (in path to database object)} {После точки (в путях к объектам базы данных)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Before mathematical operator} {Перед математическим оператором}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {After mathematical operator} {После математического оператора}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Uppercase keywords} {Ключевые слова заглавными буквами}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Uppercase datatype names} {Типы данных заглавными буквами}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Always use name wrapping} {Всегда обрамлять имена}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Preferred name wrapper} {Предпочитаемое обрамление имён}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Expand one line comments (/* ... */) to multiline} {Преобразовывать однострочные комментарии (/* ... */) в многострочные}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Indent multi line comments} {Отступы перед многострочными комментариями}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset ru {Use "*" character for each line} {Вставлять символ "*" в начало каждой строки}

### File: ../src/plugins/import/csv.tcl
mcset ru {, (comma)} {, (запятая)}

### File: ../src/plugins/import/csv.tcl
mcset ru {; (semicolon)} {; (точка с запятой)}

### File: ../src/plugins/import/csv.tcl
mcset ru {\t (tab)} {\t (табуляция)}

### File: ../src/plugins/import/csv.tcl
mcset ru {  (white-space)} {  (пробел)}

### File: ../src/plugins/import/csv.tcl
mcset ru Custom Другой

### File: ../src/plugins/import/csv.tcl
mcset ru Browse Обзор...

### File: ../src/plugins/import/csv.tcl
mcset ru {Columns separator:} {Разделитель столбцов:}

### File: ../src/plugins/import/csv.tcl
mcset ru {CSV separator cannot be empty.} {Разделитель в CSV не может быть пустым.}

### File: ../src/plugins/import/regexp.tcl
mcset ru Help Справка

### File: ../src/plugins/export/xls.tcl
mcset ru {Column names as first row} {Названия столбцов в первой строке}

### File: ../src/plugins/export/xls.tcl
mcset ru Encoding: Кодировка:

### File: ../src/plugins/export/plain.tcl
mcset ru {Export NULL values as:} {Заменить NULL-значения на:}

### File: ../src/plugins/export/plain.tcl
mcset ru {Table: %s} {Таблица: %s}

### File: ../src/plugins/export/plain.tcl
mcset ru {Index: %s} {Индекс: %s}

### File: ../src/plugins/export/plain.tcl
mcset ru {Trigger: %s} {Триггер: %s}

### File: ../src/plugins/export/plain.tcl
mcset ru {View: %s} {Представление: %s}

### File: ../src/plugins/export/csv.tcl
mcset ru {If enabled, then first row of exported CSV will be a list of column names.} {Если опция активирована, в первой строке CSV-файла будет список имён столбцов.}

### File: ../src/plugins/export/csv.tcl
mcset ru {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.} {Символ, используемый для отделения каждого значения столбца
от других. Если символ встречается в значении любого столбца,
то это значение заключается в кавычки.
Все символы кавычек в значениях столбцов заменяются двумя кавычками.}

### File: ../src/plugins/export/xml.tcl
mcset ru {No extra white-spaces or new lines} {Удалить лишние пробелы или пустые строки}

### File: ../src/plugins/export/xml.tcl
mcset ru {XML tags will be places char-by-char, without any extra white-spaces.} {Тэги XML будут размещены непосредственно друг за другом.}

### File: ../src/plugins/export/xml.tcl
mcset ru {Format output to be human readable} {Оформить в пригодном для чтения виде}

### File: ../src/plugins/export/xml.tcl
mcset ru {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.} {Каждый тэг будет помещен в отдельной строке, а документ
будет оптимизирован для чтения в текстовом редакторе.}

### File: ../src/plugins/export/xml.tcl
mcset ru {Generate XSD file} {Сгенерировать файл XSD}

### File: ../src/plugins/export/xml.tcl
mcset ru {Generates XML Schema Definition file using
export file name and extension *.xsd.} {Генерирует файл XML Schema Definition (описание схемы XML-документа), 
используя имя экспортированного файла и расширение *.xsd.}

### File: ../src/plugins/export/html.tcl
mcset ru {First row of exported data will be header
with names of columns, just like in results grid.} {Первая строка экспортированных данных будет содержать заголовок
с именами столбцов, как в таблице результатов.}

### File: ../src/plugins/export/html.tcl
mcset ru {Row numbers as first column} {Номера строк в первом столбце}

### File: ../src/plugins/export/html.tcl
mcset ru {Full column names} {Полные названия столбцов}

### File: ../src/plugins/export/html.tcl
mcset ru {Show types} {Сведения о типах данных}

### File: ../src/plugins/export/html.tcl
mcset ru {Column headers will contain data types.} {Сведения о типах данных будут включены в заголовки столбцов.}

### File: ../src/plugins/export/html.tcl
mcset ru {no type} {без типа}

### File: ../src/plugins/export/html.tcl
mcset ru {For table:} {Для таблицы:}

### File: ../src/plugins/export/html.tcl
mcset ru Unique: Уникальность:

### File: ../src/plugins/export/html.tcl
mcset ru Yes Да

### File: ../src/plugins/export/html.tcl
mcset ru No Нет

### File: ../src/plugins/export/html.tcl
mcset ru Column Столбец

### File: ../src/plugins/export/html.tcl
mcset ru Collating Сравнение

### File: ../src/plugins/export/html.tcl
mcset ru {Sort order} {Порядок сортировки}

### File: ../src/plugins/export/html.tcl
mcset ru Activated: Активирован:

### File: ../src/plugins/export/html.tcl
mcset ru Action: Действие:

### File: ../src/plugins/export/html.tcl
mcset ru {Activate condition:} {Условие активации:}

### File: ../src/plugins/export/html.tcl
mcset ru {Code executed:} {Выполненный код:}

### File: ../src/plugins/export/html.tcl
mcset ru {Exported database: %s} {Экспортированная база данных: %s}

### File: ../src/plugins/export/html.tcl
mcset ru {Generated on %s with %s} {Сгенерировано %s при помощи %s}

### File: ../src/plugins/export/html.tcl
mcset ru {Exported table: %s} {Экспортированная таблица: %s}

### File: ../src/plugins/export/html.tcl
mcset ru {Results of SQL query} {Результаты SQL-запроса}

### File: ../src/plugins/export/sql.tcl
mcset ru {Name of table for exported data:} {Имя таблицы для экспортированных данных:}

### File: ../src/plugins/export/sql.tcl
mcset ru {Include "CREATE TABLE" statement at the begining.} {Вставить выражение "CREATE TABLE" в начало.}

### File: ../src/plugins/export/sql.tcl
mcset ru {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.} {Результаты запроса, экспортированные в виде выражений SQL INSERT,
должны содержать ссылку на таблицу для вставки. Укажите имя этой таблицы.}

### File: ../src/plugins/export/sql.tcl
mcset ru {Include table declaration} {Вставить объявление таблицы}

### File: ../src/plugins/export/sql.tcl
mcset ru {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.} {Если опция активирована, DDL-код (CREATE TABLE)
будет включен в экспортированный SQL.}

### File: ../src/plugins/export/sql.tcl
mcset ru {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.} {Необходимо указать имя таблицы для экспорта результатов запроса в SQL.
Синтаксис выражений SQL INSERT требует наличия имени таблицы.}

### File: ../src/plugins/populating/random.tcl
mcset ru {Include alpha characters} Буквы

### File: ../src/plugins/populating/random.tcl
mcset ru {Include numeric characters} Цифры

### File: ../src/plugins/populating/random.tcl
mcset ru {Include whitespace characters} {Пробел, табуляция и т.п.}

### File: ../src/plugins/populating/random.tcl
mcset ru {Include binary characters} {Двоичные символы}

### File: ../src/plugins/populating/random.tcl
mcset ru {Minimum length:} {Минимальная длина:}

### File: ../src/plugins/populating/random.tcl
mcset ru {Maximum length:} {Максимальная длина:}

### File: ../src/plugins/populating/random_number.tcl
mcset ru {Minimum value:} {Минимальное значение:}

### File: ../src/plugins/populating/random_number.tcl
mcset ru {Maximum value:} {Максимальное значение:}

### File: ../src/plugins/populating/random_number.tcl
mcset ru {Constant prefix:} Префикс:

### File: ../src/plugins/populating/random_number.tcl
mcset ru {Constant suffix:} Суффикс:

### File: ../src/plugins/populating/constant.tcl
mcset ru {Value to use:} {Используемое значение:}

### File: ../src/plugins/populating/sequence.tcl
mcset ru {Start from:} {Начальное значение:}

### File: ../src/plugins/populating/dictionary.tcl
mcset ru {Dictionary file:} {Файл словаря:}

### File: ../src/plugins/populating/dictionary.tcl
mcset ru {Dictionary words separator:} {Разделитель слов:}

### File: ../src/plugins/populating/dictionary.tcl
mcset ru Whitespace {Пробел, табуляция и т.п.}

### File: ../src/plugins/populating/dictionary.tcl
mcset ru {Line break} {Разрыв строки}

### File: ../src/plugins/populating/dictionary.tcl
mcset ru {Method of using words:} {Порядок использования слов:}

### File: ../src/plugins/populating/dictionary.tcl
mcset ru Randomly Случайный

### File: ../src/plugins/populating/dictionary.tcl
mcset ru Consecutively Последовательный

### File: ../src/plugins/populating/dictionary.tcl
mcset ru {Dictionary file doesn't exist, or unreadable.} {Файл словаря не существует или не читается.}

### File: ../src/plugins/populating/dictionary.tcl
mcset ru {Dictionary file is empty!} {Файл словаря пустой!}

### File: ../src/plugins/populating/dictionary.tcl
mcset ru {Dictionary file} {Файл словаря}

### File: ../src/taskbar.tcl
mcset ru Database: {База данных:}

### File: ../src/taskbar.tcl
mcset ru Table: Таблица:

### File: ../src/taskbar.tcl
mcset ru {Type new name for a window} {Введите новое имя для окна}

### File: ../src/taskbar.tcl
mcset ru {Type new name for a task} {Введите новое имя для задачи}

### File: ../src/taskbar.tcl
mcset ru {Close selected window} {Закрыть выбранное окно}

### File: ../src/taskbar.tcl
mcset ru {Close other windows} {Закрыть все окна, кроме этого}

### File: ../src/taskbar.tcl
mcset ru {Close all windows} {Закрыть все окна}

### File: ../src/taskbar.tcl
mcset ru {Rename selected window} {Переименовать выбранное окно}

### File: ../src/windows/table_win.tcl
mcset ru Structure Структура

### File: ../src/windows/table_win.tcl
mcset ru Data Данные

### File: ../src/windows/table_win.tcl
mcset ru Constraints Ограничения

### File: ../src/windows/table_win.tcl
mcset ru Indexes Индексы

### File: ../src/windows/table_win.tcl
mcset ru Triggers Триггеры

### File: ../src/windows/table_win.tcl
mcset ru {Grid view} {Режим таблицы}

### File: ../src/windows/table_win.tcl
mcset ru {Form view} {Режим формы}

### File: ../src/windows/table_win.tcl
mcset ru {Refresh table columns and DDL (%s)} {Обновить (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Edit table (%s)} {Редактировать таблицу (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Export table data (%s)} {Экспорт данных таблицы (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Populate table (%s)} {Заполнить таблицу (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Create similar table} {Клонировать таблицу}

### File: ../src/windows/table_win.tcl
mcset ru {Refresh table data (%s)} {Обновить данные таблицы (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Add new row (%s)} {Добавить новую строку (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Delete selected row (%s)} {Удалить выделенную строку (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Rollback new row (%s)} {Откатить добавление новой строки (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {First %s rows} {Первые %s строк}

### File: ../src/windows/table_win.tcl
mcset ru {Previous %s rows} {Предыдущие %s строк}

### File: ../src/windows/table_win.tcl
mcset ru {Next %s rows} {Следующие %s строк}

### File: ../src/windows/table_win.tcl
mcset ru {Last %s rows} {Последние %s строк}

### File: ../src/windows/table_win.tcl
mcset ru {Export table data} {Экспорт данных таблицы}

### File: ../src/windows/table_win.tcl
mcset ru {Populate table} {Заполнить таблицу}

### File: ../src/windows/table_win.tcl
mcset ru {Enter phrase you want to look for} {Введите строку для поиска}

### File: ../src/windows/table_win.tcl
mcset ru {Apply data filter} {Применить фильтр}

### File: ../src/windows/table_win.tcl
mcset ru {Clear data filter} {Очистить фильтр}

### File: ../src/windows/table_win.tcl
mcset ru {Total rows: %s} {Всего строк: %s}

### File: ../src/windows/table_win.tcl
mcset ru {Rollback changes (%s)} {Отменить изменения (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {First row from data grid (%s)} {Первая строка данных (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Previous row from data grid (%s)} {Предыдущая строка данных (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Next row from data grid (%s)} {Следующя строка данных (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Last row from data grid (%s)} {Последняя строка данных (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Field switching mode.

Click it to make <Tab> key to insert tab characters.} {Режим переключения полей формы.

Нажмите, чтобы при нажатии клавиши <Tab> вставлялся символ табуляции.}

### File: ../src/windows/table_win.tcl
mcset ru {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.} {Режим вставки символов табуляции.

Нажмите, чтобы при нажатии клавиши <Tab> происходил переход между полями формы.}

### File: ../src/windows/table_win.tcl
mcset ru {Refresh table indexes (%s)} {Обновить (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Create new index (%s)} {Создать новый индекс (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Edit index (%s)} {Редактировать индекс (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Delete index (%s)} {Удалить индекс (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Refresh table triggers (%s)} {Обновить (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Create new trigger (%s)} {Создать новый триггер (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Edit trigger (%s)} {Редактировать триггер (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Delete trigger (%s)} {Удалить триггер (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Constraint name} {Название ограничения}

### File: ../src/windows/table_win.tcl
mcset ru {Column name} {Название столбца}

### File: ../src/windows/table_win.tcl
mcset ru Default {Значение по умолчанию}

### File: ../src/windows/table_win.tcl
mcset ru {Not NULL} {Не NULL}

### File: ../src/windows/table_win.tcl
mcset ru {Primary key} {Первичный ключ}

### File: ../src/windows/table_win.tcl
mcset ru Unique Уникальность

### File: ../src/windows/table_win.tcl
mcset ru Collate Сравнение

### File: ../src/windows/table_win.tcl
mcset ru Check Проверка

### File: ../src/windows/table_win.tcl
mcset ru {Foreign key} {Внешний ключ}

### File: ../src/windows/table_win.tcl
mcset ru {Index name} {Название индекса}

### File: ../src/windows/table_win.tcl
mcset ru {On column} Столбец

### File: ../src/windows/table_win.tcl
mcset ru {SQL code} {Код SQL}

### File: ../src/windows/table_win.tcl
mcset ru {Trigger name} {Название триггера}

### File: ../src/windows/table_win.tcl
mcset ru {On table} Таблица

### File: ../src/windows/table_win.tcl
mcset ru Name Название

### File: ../src/windows/table_win.tcl
mcset ru {Data type} {Тип данных}

### File: ../src/windows/table_win.tcl
mcset ru {Default value} {Значение по умолчанию}

### File: ../src/windows/table_win.tcl
mcset ru {Refreshing dependencies} {Обновление зависимостей}

### File: ../src/windows/table_win.tcl
mcset ru {Refreshing table columns...} {Обновление столбцов таблицы...}

### File: ../src/windows/table_win.tcl
mcset ru {Refreshing table data...} {Обновление данных таблицы...}

### File: ../src/windows/table_win.tcl
mcset ru {Refreshing table indexes...} {Обновление индексов таблицы...}

### File: ../src/windows/table_win.tcl
mcset ru {Refreshing table triggers...} {Обновление триггеров таблицы...}

### File: ../src/windows/table_win.tcl
mcset ru {Check condition} {Проверка условия}

### File: ../src/windows/table_win.tcl
mcset ru {Total rows: %s (filtered)} {Всего строк: %s (с учётом фильтра)}

### File: ../src/windows/table_win.tcl
mcset ru {Pending commits} {Ожидающие транзакции}

### File: ../src/windows/table_win.tcl
mcset ru {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?} {Имеются неподтверждённые изменения данных.
Перезагрузка данных отменит их.
Вы действительно хотите продолжить?}

### File: ../src/windows/table_win.tcl
mcset ru {Loading data...} {Загрузка данных...}

### File: ../src/windows/table_win.tcl
mcset ru {Loading table '%s'...} {Загрузка таблицы '%s'...}

### File: ../src/windows/table_win.tcl
mcset ru {Edit table} {Редактировать таблицу}

### File: ../src/windows/table_win.tcl
mcset ru {New index} {Новый индекс}

### File: ../src/windows/table_win.tcl
mcset ru {Edit index} {Редактировать индекс}

### File: ../src/windows/table_win.tcl
mcset ru {Delete index} {Удалить индекс}

### File: ../src/windows/table_win.tcl
mcset ru {Are you sure you want to delete '%s' index?} {Вы действительно хотите удалить индекс '%s'?}

### File: ../src/windows/table_win.tcl
mcset ru {New trigger} {Новый триггер}

### File: ../src/windows/table_win.tcl
mcset ru {Edit trigger} {Редактировать триггер}

### File: ../src/windows/table_win.tcl
mcset ru {Delete trigger} {Удалить триггер}

### File: ../src/windows/table_win.tcl
mcset ru {Are you sure you want to delete '%s' trigger?} {Вы действительно хотите удалить триггер '%s'?}

### File: ../src/windows/table_win.tcl
mcset ru {Export table} {Экспорт таблицы}

### File: ../src/windows/editor_win.tcl
mcset ru {SQL query} SQL-запрос

### File: ../src/windows/editor_win.tcl
mcset ru Results Результаты

### File: ../src/windows/editor_win.tcl
mcset ru History История

### File: ../src/windows/editor_win.tcl
mcset ru {Execute query (%s)} {Выполнить запрос (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Execute query with plain string results} {Выполнить запрос с представлением результата в текстовом виде}

### File: ../src/windows/editor_win.tcl
mcset ru {Explain query (%s)} {План запроса (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Format SQL code (%s)} {Форматировать код SQL (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Refresh syntax highlighting (%s)} {Обновить подсветку синтаксиса (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Clear history} {Очистка истории}

### File: ../src/windows/editor_win.tcl
mcset ru {Export results} {Экспорт результатов}

### File: ../src/windows/editor_win.tcl
mcset ru {Create view from query} {Создать представление из запроса}

### File: ../src/windows/editor_win.tcl
mcset ru {Execute SQL from file (%s)} {Выполнить SQL-код из файла (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Load SQL from file (%s)} {Загрузить SQL-код из файла (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Save SQL to file (%s)} {Сохранить SQL-код в файл (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Default database for SQL executing
(%s/%s)} {База данных по умолчанию для выполнения SQL-кода
(%s/%s)}

### File: ../src/windows/editor_win.tcl
mcset ru Database {База данных}

### File: ../src/windows/editor_win.tcl
mcset ru {Execution date} {Дата и время выполнения}

### File: ../src/windows/editor_win.tcl
mcset ru {Execution time (s)} {Длительность (с)}

### File: ../src/windows/editor_win.tcl
mcset ru {Rows affected} {Обработано строк}

### File: ../src/windows/editor_win.tcl
mcset ru SQL SQL

### File: ../src/windows/editor_win.tcl
mcset ru {Plain text view} {Текстовый вид}

### File: ../src/windows/editor_win.tcl
mcset ru {Refresh results (%s)} {Обновить результаты (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Copy (%s)} {Копировать (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Cut (%s)} {Вырезать (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Paste (%s)} {Вставить (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Show line numbers} {Показать номера строк}

### File: ../src/windows/editor_win.tcl
mcset ru {Choose the database first.} {Выберите базу данных.}

### File: ../src/windows/editor_win.tcl
mcset ru {Error while trying to collect completion list: %s} {Ошибка при составлении списка автодополнения: %s}

### File: ../src/windows/editor_win.tcl
mcset ru {Can't open %s file for reading.} {Не удается открыть файл %s для чтения.}

### File: ../src/windows/editor_win.tcl
mcset ru {Can't open %s file for writting.} {Не удалось открыть файл %s для записи.}

### File: ../src/windows/editor_win.tcl
mcset ru {SQL code saved in %s.} {SQL-код сохранен в файле %s.}

### File: ../src/windows/editor_win.tcl
mcset ru {Are you sure you want to clear queries history?} {Вы действительно хотите очистить историю запросов?}

### File: ../src/windows/editor_win.tcl
mcset ru Processing... Обработка...

### File: ../src/windows/editor_win.tcl
mcset ru {Processing query...} {Обработка запроса...}

### File: ../src/windows/editor_win.tcl
mcset ru {No results to export.} {Нет результатов для экспорта.}

### File: ../src/windows/editor_win.tcl
mcset ru {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.} {Использование команды ATTACH в редакторе SQL-кода запрещено. Вместо этого, зарегистрируйте присоединяемую базу данных в SQLiteStudio и используйте её имя, отображаемое в дереве баз данных, во всех необходимых SQL-выражениях. Они будут автоматически присоединены по запросу.}

### File: ../src/windows/editor_win.tcl
mcset ru {Query execution...} {Выполенение запроса...}

### File: ../src/windows/editor_win.tcl
mcset ru {Executing SQL query...} {Выполнение SQL-запроса...}

### File: ../src/windows/editor_win.tcl
mcset ru {Error while executing query: %s} {При выполнении запроса произошла ошибка: %s}

### File: ../src/windows/editor_win.tcl
mcset ru {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s} {Неизвестная ошибка при выполнении запроса. Пожалуйста, сообщите о ней! Код возврата=%s. Выполнявшийся запрос: %s}

### File: ../src/windows/editor_win.tcl
mcset ru {%s row(s) affected in %s second(s).} {Обработано строк: %s, время выполнения: %s с.}

### File: ../src/windows/editor_win.tcl
mcset ru {New view} {Новое представление}

### File: ../src/windows/editor_win.tcl
mcset ru {Fill query parameters} {Заполнить параметры запроса}

### File: ../src/error.tcl
mcset ru {Background error} {Фоновая ошибка}

### File: ../src/error.tcl
mcset ru Close Закрыть

### File: ../src/error.tcl
mcset ru {Report the bug} {Сообщить об ошибке}

### File: ../src/dialogs/about_dialog.tcl
mcset ru About {О программе...}

### File: ../src/dialogs/about_dialog.tcl
mcset ru {Packages and plugins} {Модули и плагины}

### File: ../src/dialogs/about_dialog.tcl
mcset ru Licence Лицензия

### File: ../src/dialogs/about_dialog.tcl
mcset ru {Installed plugins:} {Установленные плагины:}

### File: ../src/dialogs/about_dialog.tcl
mcset ru {Used Tcl packages:} {Использованные модули Tcl:}

### File: ../src/dialogs/about_dialog.tcl
mcset ru {SQLite3 engine version: %s} {Версия SQLite3: %s}

### File: ../src/dialogs/searchdialog.tcl
mcset ru {Global expression understeands '*', '?' and \[chars].} {Глобальное выражение понимает '*', '?' и \[символы].}

### File: ../src/dialogs/searchdialog.tcl
mcset ru Find Найти

### File: ../src/dialogs/searchdialog.tcl
mcset ru Replace Заменить

### File: ../src/dialogs/searchdialog.tcl
mcset ru {Do you want to replace marked text?} {Вы хотите заменить помеченный текст?}

### File: ../src/dialogs/searchdialog.tcl
mcset ru {Replace all} {Заменить все}

### File: ../src/dialogs/searchdialog.tcl
mcset ru {Replacing finished.} {Замена выполнена.}

### File: ../src/dialogs/searchdialog.tcl
mcset ru {Cannot match the pattern!} {Совпадения не найдены!}

### File: ../src/dialogs/bind_param.tcl
mcset ru {Query number %s} {Номер запроса %s}

### File: ../src/dialogs/bind_param.tcl
mcset ru {Parameter number %s (named: %s):} {Параметр номер %s (название: %s):}

### File: ../src/dialogs/bind_param.tcl
mcset ru {Execute query} {Выполнить запрос}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ru Collation Сравнение

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ru Sort Сортировка

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ru {Named constraint:} {Именованное ограничение:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ru {On conflict:} {При нарушении:}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ru {Constraint is marked as being named, but there's no name filled in.} {Ограничение помечено как именованное, однако имя не указано.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ru {Collation for column '%s' is enabled, but there's no collation name filled in.} {Для столбца '%s' активировано сравнение, но имя сравнения не заполнено.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset ru {No columns are selected.} {Столбцы не выбраны.}

### File: ../src/dialogs/populate_table.tcl
mcset ru {Number of rows to insert:} {Количество вставляемых строк:}

### File: ../src/dialogs/populate_table.tcl
mcset ru Mode Способ

### File: ../src/dialogs/populate_table.tcl
mcset ru {Select table to display available columns} {Выберите таблицу для отображения стоолбцов}

### File: ../src/dialogs/populate_table.tcl
mcset ru Populate Заполнить

### File: ../src/dialogs/populate_table.tcl
mcset ru {Error occured while populating table:
%s} {Ошибка заполнения таблицы:
%s}

### File: ../src/dialogs/populate_table.tcl
mcset ru Configuration Настройки

### File: ../src/dialogs/populate_table.tcl
mcset ru {You have to type valid number of rows to insert.} {Введите число для указания количества вставляемых строк.}

### File: ../src/dialogs/populate_table.tcl
mcset ru {You have to select at least one column to populate.} {Выберите хотя бы один столбец для заполнения.}

### File: ../src/dialogs/populate_table.tcl
mcset ru Populating... Заполнение...

### File: ../src/dialogs/populate_table.tcl
mcset ru {Populating table '%s'.} {Заполнение таблицы '%s'.}

### File: ../src/dialogs/populate_table.tcl
mcset ru Stop Стоп

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ru {Foreign table:} {Внешняя таблица:}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ru {Local column} {Локальный столбец}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ru {Foreign column} {Внешний столбец}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ru Reactions Реакции

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ru {ON UPDATE} {ON UPDATE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ru {ON DELETE} {ON DELETE}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ru MATCH MATCH

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ru {Deferred foreign key} {Отложенный внешний ключ}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ru {No foreign table selected.} {Внешняя таблица не выбрана.}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset ru {There's no foreign column assigned for local column '%s'.} {Для локального столбца '%s' не указан внешний столбец.}

### File: ../src/dialogs/import_dialog.tcl
mcset ru Table Таблица

### File: ../src/dialogs/import_dialog.tcl
mcset ru {You have to choose database.} {Выберите базу данных.}

### File: ../src/dialogs/view_dialog.tcl
mcset ru View Вид

### File: ../src/dialogs/view_dialog.tcl
mcset ru {View name:} {Название представления:}

### File: ../src/dialogs/view_dialog.tcl
mcset ru {Code executed to get view data:} {Код, выполняемый для получения данных представления:}

### File: ../src/dialogs/view_dialog.tcl
mcset ru Create Создать

### File: ../src/dialogs/view_dialog.tcl
mcset ru Change Изменить

### File: ../src/dialogs/view_dialog.tcl
mcset ru {You have to specify database.} {Укажите базу данных.}

### File: ../src/dialogs/view_dialog.tcl
mcset ru {You have to specify view name.} {Задайте название представления.}

### File: ../src/dialogs/view_dialog.tcl
mcset ru {You havn't wrote a code for the view.} {Вы не задали код для получения данных представления.}

### File: ../src/dialogs/export_dialog.tcl
mcset ru {Export data} {Экспорт данных}

### File: ../src/dialogs/export_dialog.tcl
mcset ru {Only structure, without data} {Экспортировать только структуру}

### File: ../src/dialogs/export_dialog.tcl
mcset ru {Output file} {Выходной файл}

### File: ../src/dialogs/export_dialog.tcl
mcset ru {Export format} {Формат экспорта}

### File: ../src/dialogs/export_dialog.tcl
mcset ru Export Экспорт

### File: ../src/dialogs/export_dialog.tcl
mcset ru {You have to choose file.} {Выберите файл.}

### File: ../src/dialogs/export_dialog.tcl
mcset ru {Can't write to file: %s} {Не удалось записать данные в файл: %s}

### File: ../src/dialogs/export_dialog.tcl
mcset ru {You have to choose table.} {Выберите таблицу.}

### File: ../src/dialogs/export_dialog.tcl
mcset ru {Exporting database '%s'.} {Экспорт базы данных '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset ru {Exporting table '%s'.} {Экспотр таблицы '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset ru {Exporting results.} {Результаты экспорта.}

### File: ../src/dialogs/export_dialog.tcl
mcset ru Exporting... Экспорт...

### File: ../src/dialogs/export_dialog.tcl
mcset ru {Cannot write to file: %s
Please select other file.} {Невозможно записать в файл: %s
Выберите другой файл.}

### File: ../src/dialogs/bug_report.tcl
mcset ru or или

### File: ../src/dialogs/bug_report.tcl
mcset ru {Brief description:} {Краткое описание:}

### File: ../src/dialogs/bug_report.tcl
mcset ru {How to reproduce problem (if possible):} {Как вопроизвести проблему (если возможно):}

### File: ../src/dialogs/bug_report.tcl
mcset ru {What is the problem:} {Описание проблемы:}

### File: ../src/dialogs/bug_report.tcl
mcset ru {Operating system:} {Операционная система:}

### File: ../src/dialogs/bug_report.tcl
mcset ru {Take screenshots of all SQLiteStudio windows and attach them} {Сделайте снимки всех окон SQLiteStudio и приложите их}

### File: ../src/dialogs/bug_report.tcl
mcset ru Send Отправить

### File: ../src/dialogs/bug_report.tcl
mcset ru {Describe your feature request:} {Опишите своё предложение по функционалу:}

### File: ../src/dialogs/bug_report.tcl
mcset ru {Please fill 'Brief' field.} {Пожалуйста, заполните поле 'Краткое описание'.}

### File: ../src/dialogs/bug_report.tcl
mcset ru {Please fill at least one of 'Description' or 'How to reproduce' fields.} {Пожалуйста, заполните хотя бы одно из полей 'Описание проблемы' или 'Как воспроизвести'.}

### File: ../src/dialogs/bug_report.tcl
mcset ru {Please provide valid e-mail address or leave 'E-mail' empty.} {Пожалуйста, введите корректный адрес e-mail или оставьте поле 'E-mail' пустым.}

### File: ../src/dialogs/bug_report.tcl
mcset ru {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.} {Указанный e-mail НЕ будет передан кому-либо, а также использоваться вне целей,
описанных ниже. Он нигде не будет опубликован.
Он будет использован разработчиком SQLiteStudio для связи с вами
при необходимости уточнить детали этого отчёта.

Данное поле является необязательным. Вы можете оставить его пустым.}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Database to convert:} {База данных для преобразования:}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Converted database name:} {Название преобразованной базы данных:}

### File: ../src/dialogs/db_convert.tcl
mcset ru {File to use for converted database:} {Файл преобразованной базы данных:}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Choose new file for database} {Выберите новый файл базы данных}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Database version:} {Версия базы данных:}

### File: ../src/dialogs/db_convert.tcl
mcset ru Convert Преобразовать

### File: ../src/dialogs/db_convert.tcl
mcset ru {Convert database} {Преобразовать базу данных}

### File: ../src/dialogs/db_convert.tcl
mcset ru {You chave to choose database to convert.} {Выберите базу данных для преобразования.}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Error resolving database with name %s!} {Ошибка разрешения базы данных %s!}

### File: ../src/dialogs/db_convert.tcl
mcset ru {You have to specify new database file.} {Укажите новый файл базы данных.}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Cannot use existing file for converted database.} {Невозможно использовать существующий файл для преобразованной базы данных.}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Cannot use existing name for converted database.} {Невозможно использовать существующее название для преобразованной базы данных.}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Cannot find handler for database labeled with: %s} {Не удалось найти обработчик для базы данных: %s}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Error while trying to create database: %s} {При создании базы данных произошла ошибка: %s}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Database converting error} {Ошибка при преобразовании базы данных}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s} {Возникло несколько проблем при преобразовании базы данных, тем не менее она была преобразована, а объекты, вызвавшие проблемы, пропущены. Подробности:
%s}

### File: ../src/dialogs/db_convert.tcl
mcset ru {Choose file} {Выберите файл}

### File: ../src/dialogs/yesno.tcl
mcset ru Warning Предупреждение

### File: ../src/dialogs/yesno.tcl
mcset ru Error Ошибка

### File: ../src/dialogs/yesno.tcl
mcset ru Information Информация

### File: ../src/dialogs/import_db.tcl
mcset ru {Import from one of databases:} {Импорт из базы данных:}

### File: ../src/dialogs/import_db.tcl
mcset ru {Choose database file to import:} {Выберите базу данных для импорта:}

### File: ../src/dialogs/import_db.tcl
mcset ru {No database chosen.} {Не выбрана база данных.}

### File: ../src/dialogs/import_db.tcl
mcset ru {Cannot open specified database.} {Не удалось открыть указанную базу данных.}

### File: ../src/dialogs/import_db.tcl
mcset ru {Error while importing database:
%s} {Ошибка импорта базы данных:
%s}

### File: ../src/dialogs/import_db.tcl
mcset ru {Select file} {Выберите файл}

### File: ../src/dialogs/column_dialog.tcl
mcset ru Column: Столбец:

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Column constraints:} {Ограничения столбцов:}

### File: ../src/dialogs/column_dialog.tcl
mcset ru Add Добавить

### File: ../src/dialogs/column_dialog.tcl
mcset ru Size Размер

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Maximal length of value in column.} {Максимальная длина значения в столбце.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Primary key configuration} {Настройки первичного ключа}

### File: ../src/dialogs/column_dialog.tcl
mcset ru Autoincrement Автоинкремент

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Sort order:} {Порядок сортировки:}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {No foreign column selected.} {Внешний столбец не выбран.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Choose ON UPDATE action, or disable it.} {Выберите действие ON UPDATE или деактивируйте опцию.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Choose ON DELETE action, or disable it.} {Выберите действие ON DELETE или деактивируйте опцию.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Choose MATCH action, or disable it.} {Выберите действие MATCH или деактивируйте опцию.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Foreign key configuration} {Настройки внешнего ключа}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Foreign column:} {Внешний столбец:}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Unique configuration} {Настройки уникальности}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Fill in the condition expression.} {Заполните выражение для условия.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Check condition configuration} {Проверьте настройки условий}

### File: ../src/dialogs/column_dialog.tcl
mcset ru Condition: Условие:

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Not null configuration} {Настройки не NULL}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Fill in the collation name.} {Заполните имя сравнения.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Collating configuration} {Настройки сравнения}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Collation name:} {Имя сравнения:}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Fill in the default value.} {Заполните значение по умолчанию.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Default value configuration} {Настройки значения по умолчанию}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Default value:} {Значение по умолчанию:}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Column primary key is not configured correctly.} {Первичный ключ столбца настроен некорректно.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Column foreign key is not configured correctly.} {Внешний ключ столбца настроен некорректно.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Column 'unique' constraint is not configured correctly.} {Ограничение 'unique' столбца настроено некорректно.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Column 'check' constraint is not configured correctly.} {Ограничение 'check' столбца настроено некорректно.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Column 'notnull' constraint is not configured correctly.} {Ограничение 'notnull' столбца настроено некорректно.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Column 'default' constraint is not configured correctly.} {Ограничение 'default' столбца настроено некорректно.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Column 'collate' constraint is not configured correctly.} {Ограничение 'collate' столбца настроено некорректно.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {No column name is specified.} {Не указано имя столбца.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Column with name '%s' already exists in the table.} {Столбец с именем '%s' уже существует в таблице.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Data type bounds are given, but no data type name is specified.} {Указано ограничение типа данных, но имя типа данных не определено.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Data type precision is given, but no data type size is specified.} {Указана точность типа данных, но длина типа данных не определена.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Data type size has invalid format. Only integer value is allowed.} {Неверный формат длины типа данных. Допустимы только целые значения.}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Data type precision has invalid format. Only integer value is allowed.} {Неверный формат точности типа данных. Допустимы только целые значения.}

### File: ../src/dialogs/db_edit.tcl
mcset ru {Database file:} {Файл базы данных:}

### File: ../src/dialogs/db_edit.tcl
mcset ru {Database name:} {Название базы данных:}

### File: ../src/dialogs/db_edit.tcl
mcset ru {Generate automatically} {Сгенерировать автоматически}

### File: ../src/dialogs/db_edit.tcl
mcset ru {Type name in field below:} {Введите имя:}

### File: ../src/dialogs/db_edit.tcl
mcset ru {Remember it permanently} Запомнить

### File: ../src/dialogs/db_edit.tcl
mcset ru {If disabled, then the database will be registered only
for this single SQLiteStudio session.} {Если опция отключена, то база данных будет зарегистрирована
только на время этой сессии в SQLiteStudio.}

### File: ../src/dialogs/db_edit.tcl
mcset ru {Edit database} {Редактировать базу данных}

### File: ../src/dialogs/db_edit.tcl
mcset ru {Add database} {Добавить базу данных}

### File: ../src/dialogs/db_edit.tcl
mcset ru {You have to specify database file.} {Укажите файл базы данных.}

### File: ../src/dialogs/db_edit.tcl
mcset ru {Type not existing file for new database} {Введите имя несуществующего файла для создания новой базы данных}

### File: ../src/dialogs/db_edit.tcl
mcset ru {Select existing database file} {Выберите существующий файл базы данных}

### File: ../src/dialogs/db_edit.tcl
mcset ru {%s is not supported database!} {%s не является поддерживаемой базой данных!}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru Previous Предыдущий

### File: ../src/dialogs/tips_dialog.tcl
mcset ru Next Следующий

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {Do not show this dialog at startup} {Не показывать при запуске программы}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		} {
			Если вам не нравится открывать множество редакторов SQL-кода, вы можете использовать одно окно редактора,
			поместив в него весь необходимый SQL-код, а затем выделить только ту часть кода, которую необходимо выполнить
			и нажать Выполнить SQL-запрос.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			You can configure all SQL editor syntax colors in settings.
		} {
			Вы можете настроить все цвета синтаксиса редактора SQL-кода в окне настроек.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		} {
			Вы можете использовать сочетание клавиш Control+Space (настраиваемо) для автодополнения слова, которое вы начали печатать в редакторе SQL-кода.
			Механизм автодополнения также может предугадать следующее слово в контексте SQL и отобразить список слов, подходящих в данной ситуации.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		} {
			В программе имеются различные сочетания клавиш (все они настраиваемы), которые помогут упростить и ускорить
			использование SQLiteStudio.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		} {
			При закрытии SQLiteStudio, любые открытые в тот момент MDI-окна будут восстановлены (включая SQL-код, набранный в редакторах)
			при следующем запуске приложения, если опция восстановления предыдущего ссостояния включена в настройках.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		} {
			Вы можете определить собственные SQL-функции, которые будут доступны в базе данных при редактировании её в SQLiteStudio.
			Это поможет сэмулировать функции, реализованные в конечном приложении, которое будет использовать эту базу данных.<br>
			Для создания новой функции воспользуйтесь диалогом Пользовательские функции SQL и нажмите кнопку добавления (с плюсом),
			затем введите её имя и выберите язык, на котором данная функция будет написана (Tcl или SQL).<br>
			Код функции может содержать переменные $0, $1, $2 и так далее - это позиционные параметры, которые передаются в функцию при её вызове.<br><br>
			Пример реализации функции на языке SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			Пример реализации функции на языке Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		} {
			Если вы ищете какое-либо слово в таблице данных, но не хотите писать SQL-выражение для этого, или вы просто не помните
			в каком столбце содержится данное слово, перейдите в табличный вид данных, введите слово в поле фильтра и нажмите "Применить фильтр".
			Будут найдены все вхождения данного слова (включая с префиксами и суффиксами) во всех
			столбцах, и данные таблицы будут отфильтрованы.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		} {
			Вы можете редактировать значения в таблице результатов, но помните, что столбцы, которые не были получены напрямую из таблиц (например, которые являются результатом математических операций над столбцами), не могут быть отредактированы.
			Такие нередактируемые ячейки также пропускаются при вставке каких-либо данных в таблицу результатов.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		} {
			Если вы хотите узнать значение ROWID какой-либо конкретной строки, вы можете просто навести курсор мыши на нужную строку и подождать пару мгновений.
			Появится подсказка со значением ROWID (и иной информацией) для этой строки.<br><br>
			В табличном виде в окне таблицы есть возможность включить показ ROWID вместо порядкового номера в первом столбце. Данная опция доступна в контекстном меню табличного вида.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		} {
			Вы можете поместить результаты запроса внизу текста запроса, вместо переключения в отдельную вкладку. Просто переключите расположение окна с результатами в окне настроек.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		} {
			Вы всегда можете восстановить запросы, которые когда-то выполняли, переключившись на вкладку История в окне редактора SQL-кода.<br><br>
			Количество хранимых записей в истории настраиваемо, но помните, что установка слишком большого значения приведёт к замедлению открытия новых окон редактора SQL-кода,
			так как при этом происходит полное считывание истории.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		} {
			Окно редактора SQL-кода может помочь в написании запросов - намите Control+Space (или то сочетание, которое вы настроили) в окне редактора для вызова диалога автодополнения.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		} {
			Вы можете использовать несколько имён баз данных в одном SQL-запросе, не беспокоясь о необходимости присоединять их к текущей базе данных.
			SQLiteStudio сам об этом позаботится.<br><br>
			Используйте имена баз данных, как они указаны в дереве баз данных слева. Пример:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		}

### File: ../src/dialogs/import_table.tcl
mcset ru Separator: Разделитель:

### File: ../src/dialogs/import_table.tcl
mcset ru {Common separator is \t (tab), but sometimes others can be met.} {Обычно в качестве разделителя используется \t (табуляция), но возможны и другие варианты.}

### File: ../src/dialogs/import_table.tcl
mcset ru {Import data file for '%s' table:} {Импорт файла данных для таблицы '%s':}

### File: ../src/dialogs/import_table.tcl
mcset ru {File '%s' isn't readable!} {Не удается прочитать файл '%s'!}

### File: ../src/dialogs/import_table.tcl
mcset ru {Error while trying to copy data:
%s} {Ошибка копирования данных:
%s}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru Trigger Триггер

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {On action:} Событие:

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {Trigger name:} {Название триггера:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru When: {Тип триггера:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {On table:} Таблица:

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {Execute code for:} {Выполнять код для:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {Execute code only when:} {Условие срабатывания:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {Code executed for above configuration:} {Код триггера:}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {You have to specify view.} {Укажите представление.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {You have to specify table.} {Укажите таблицу.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {You have to specify trigger name.} {Задайте название триггера.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {You have to specify 'action' condition.} {Не задано событие.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {You havn't wrote a code for the trigger.} {Не задан код триггера.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {On view:} Представление:

### File: ../src/dialogs/table_dialog.tcl
mcset ru Columns: Столбцы:

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Table constraints:} {Ограничения таблицы:}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Table name:} {Название таблицы:}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Add column} {Добавить столбец}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Edit selected} {Редактировать выбранный столбец}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Delete selected} {Удалить выбранный столбец}

### File: ../src/dialogs/table_dialog.tcl
mcset ru Type Тип

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Edit column} {Редактировать столбец}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Delete column} {Удалить столбец}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Are you sure you want to delete column '%s'?} {Вы действительно хотите удалить столбец '%s'?}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {There's no column defined.} {Столбец неопределён.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Невозможно проанализировать DDL-код триггера '%s',
поэтому пересоздание его после изменения таблицы невозможно.
Вы хотите продолжить?}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Trigger parsing problem} {Проблема при анализе триггера}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Невозможно проанализировать DDL-код индекса '%s',
поэтому пересоздание его после изменения таблицы невозможно.
Вы хотите продолжить?}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Index parsing problem} {Проблема при анализе индекса}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Modifying table...} {Изменение таблицы...}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Modifying table '%s'.} {Изменение таблицы '%s'.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Could not recreate triggers for modified table.} {Невозможно пересоздать триггеры для изменённой таблицы.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Could not recreate indexes for modified table.} {Невозможно пересоздать индексы для изменённой таблицы.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?} {После изменения таблицы будет невозможно пересоздать триггер '%s'.
Продолжить несмотря на это?}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Trigger recreation problem} {Проблема пересоздания триггера}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?} {После изменения таблицы будет невозможно пересоздать индекс '%s'.
Продолжить несмотря на это?}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Index recreation problem} {Проблема пересоздания индекса}

### File: ../src/dialogs/table_dialog_chk.tcl
mcset ru {Condition expression cannot be empty.} {Выражения для условия не может быть пустым.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset ru {What would you like to do?} {Что необходимо сделать?}

### File: ../src/dialogs/new_version_dialog.tcl
mcset ru {Install it automatically} {Установить автоматически}

### File: ../src/dialogs/new_version_dialog.tcl
mcset ru {Go to download page} {Перейти на страницу загрузки}

### File: ../src/dialogs/new_version_dialog.tcl
mcset ru {Package download} {Загрузка модуля}

### File: ../src/dialogs/new_version_dialog.tcl
mcset ru {Check for updates at startup} {Проверка обновлений при запуске}

### File: ../src/dialogs/new_version_dialog.tcl
mcset ru {New version of SQLiteStudio is available: %s} {Доступна новая версия SQLiteStudio: %s}

### File: ../src/dialogs/blob_edit.tcl
mcset ru Commit Подтвердить

### File: ../src/dialogs/bug_history.tcl
mcset ru Clear Очистить

### File: ../src/dialogs/bug_history.tcl
mcset ru {Reported on} Сообщён

### File: ../src/dialogs/bug_history.tcl
mcset ru Brief {Краткое описание}

### File: ../src/dialogs/bug_history.tcl
mcset ru URL URL

### File: ../src/dialogs/bug_history.tcl
mcset ru Discussion Обсуждение

### File: ../src/dialogs/bug_history.tcl
mcset ru {Clear reports} {Очистить отчёты}

### File: ../src/dialogs/bug_history.tcl
mcset ru {Do you want to clear whole bug reports history?} {Вы хотите очистить всю историю отчётов об ошибках?}

### File: ../src/dialogs/index_dialog.tcl
mcset ru Index Индекс

### File: ../src/dialogs/index_dialog.tcl
mcset ru {Index name:} {Название индекса:}

### File: ../src/dialogs/index_dialog.tcl
mcset ru {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?} {Уникальный индекс не может быть создан,
так как выбранные столбцы содержат дублирующиеся значения.
Отобразить эти значения?}

### File: ../src/dialogs/index_dialog.tcl
mcset ru {Unique values} {Уникальные значения}

### File: ../src/dialogs/index_dialog.tcl
mcset ru {Same values for '%s'} {Одинаковые значения для '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset ru {You have to select at least one column.} {Выберите хотя бы один столбец.}

### File: ../src/dialogs/index_dialog.tcl
mcset ru {You have to specify index name.} {Задайте название индекса.}

### File: ../src/dialogs/functions_dialog.tcl
mcset ru Implementation: Реализация:

### File: ../src/dialogs/functions_dialog.tcl
mcset ru Name: Название:

### File: ../src/dialogs/functions_dialog.tcl
mcset ru {Cannot use two functions with same name! Change name for '%s'.} {Не допускается использование функций с одинаковыми названиями! Измените название '%s'.}

### File: ../src/dialogs/functions_dialog.tcl
mcset ru {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! } {В названии функции нельзя использовать зарезервированные слова 'tcl' или 'sqlfile'! }

### File: ../src/dialogs/functions_dialog.tcl
mcset ru {Function '%s' is not implemented!} {Не задана реализация функции '%s'!}

### File: ../src/dialogs/functions_dialog.tcl
mcset ru {Delete function} {Удалить функцию}

### File: ../src/dialogs/functions_dialog.tcl
mcset ru {Are you sure you want to delete function '%s'?} {Вы действительно хотите удалить функцию '%s'?}

### File: ../src/mainwindow.tcl
mcset ru {Connect to selected database} {Подключиться к выбранной базе данных}

### File: ../src/mainwindow.tcl
mcset ru {Disconnect from selected database} {Отключиться от выбранной базы данных}

### File: ../src/mainwindow.tcl
mcset ru {Remove selected database from list} {Удалить выбранную базу данных из списка}

### File: ../src/mainwindow.tcl
mcset ru {New table} {Новая таблица}

### File: ../src/mainwindow.tcl
mcset ru {Drop table} {Удалить таблицу}

### File: ../src/mainwindow.tcl
mcset ru {Drop index} {Удалить индекс}

### File: ../src/mainwindow.tcl
mcset ru {Drop trigger} {Удалить триггер}

### File: ../src/mainwindow.tcl
mcset ru {Edit view} {Редактировать представление}

### File: ../src/mainwindow.tcl
mcset ru {Drop view} {Удалить представление}

### File: ../src/mainwindow.tcl
mcset ru {Arrange cascade windows layout} {Расположить окна каскадом}

### File: ../src/mainwindow.tcl
mcset ru {Arrange intelligent windows layout} {Упорядочить расположение окон}

### File: ../src/mainwindow.tcl
mcset ru {Refresh databases tree (%s)} {Обновить дерево баз данных (%s)}

### File: ../src/mainwindow.tcl
mcset ru {Open SQL query editor} {Открыть редактор SQL-запросов}

### File: ../src/mainwindow.tcl
mcset ru {Open SQL functions editor} {Открыть редактор функций SQL}

### File: ../src/mainwindow.tcl
mcset ru Databases {Базы данных}

### File: ../src/mainwindow.tcl
mcset ru Tools Сервис

### File: ../src/mainwindow.tcl
mcset ru Connect Подключить

### File: ../src/mainwindow.tcl
mcset ru Disconnect Отключить

### File: ../src/mainwindow.tcl
mcset ru {Remove from list} {Удалить из списка}

### File: ../src/mainwindow.tcl
mcset ru {View main toolbar} {Главная панель}

### File: ../src/mainwindow.tcl
mcset ru {View structure toolbar} {Панель структуры}

### File: ../src/mainwindow.tcl
mcset ru {View windows toolbar} {Панель окон}

### File: ../src/mainwindow.tcl
mcset ru {View tools toolbar} {Панель инструментов}

### File: ../src/mainwindow.tcl
mcset ru {View configuration toolbar} {Панель конфигурации}

### File: ../src/mainwindow.tcl
mcset ru {Refresh databases tree} {Обновить дерево баз данных}

### File: ../src/mainwindow.tcl
mcset ru {Custom SQL functions} {Пользовательские функции SQL}

### File: ../src/mainwindow.tcl
mcset ru {Export database} {Экспорт базы данных}

### File: ../src/mainwindow.tcl
mcset ru {SQLiteStudio home page} {Домашняя страница SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset ru {SQLiteStudio manual} {Справка по SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset ru {SQLite documentation} {Документация SQLite}

### File: ../src/mainwindow.tcl
mcset ru {SQLiteStudio support forum} {Форум поддержкки SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset ru {Report a bug} {Сообщить об ошибке}

### File: ../src/mainwindow.tcl
mcset ru {Send feature request} {Отправить предложение по функционалу}

### File: ../src/mainwindow.tcl
mcset ru {Show bug reports history} {Отобразить историю отчётов об ошибках}

### File: ../src/mainwindow.tcl
mcset ru {Show tips window} {Показать совет}

### File: ../src/mainwindow.tcl
mcset ru ChangeLog {История изменений}

### File: ../src/mainwindow.tcl
mcset ru Roadmap {Планы развития}

### File: ../src/mainwindow.tcl
mcset ru {Check for new version} {Проверить наличие новой версии}

### File: ../src/mainwindow.tcl
mcset ru {Did you know that...} {А вы знаете, что...}

### File: ../src/mainwindow.tcl
mcset ru {Editor %s} {Редактор %s}

### File: ../src/mainwindow.tcl
mcset ru Settings Настройки

### File: ../src/mainwindow.tcl
mcset ru {SQLiteStudio roadmap} {План развития}

### File: ../src/mainwindow.tcl
mcset ru {Can't start web browser, because:
%s} {Не удалось запустить браузер, причина:
%s}

### File: ../src/mainwindow.tcl
mcset ru {Can't start %s web browser, because:
%s} {Не удалось запустить браузер %s, причина:
%s}

### File: ../src/mainwindow.tcl
mcset ru {About SQLiteStudio} {О программе...}

### File: ../src/mainwindow.tcl
mcset ru {SQLiteStudio ChangeLog} {История изменений}

### File: ../src/mainwindow.tcl
mcset ru {There is no new version available.} {Новой версии не обнаружено.}

### File: ../src/mainwindow.tcl
mcset ru {New version} {Новая версия}

### File: ../src/mainwindow.tcl
mcset ru {Report bug} {Сообщение об ошибке}

### File: ../src/mainwindow.tcl
mcset ru {Feature request} {Предложение по функционалу}

### File: ../src/mainwindow.tcl
mcset ru {Reports history} {История отчётов}

### File: ../src/mainwindow.tcl
mcset ru {Reporting bug} {Отправка отчёта об ошибке}

### File: ../src/mainwindow.tcl
mcset ru {Reporting bug to SQLiteStudio bugs database...} {Отправка отчёта в базу ошибок SQLiteStudio...}

### File: ../src/mainwindow.tcl
mcset ru Ignore Игнорировать

### File: ../src/mainwindow.tcl
mcset ru Downloading... Загрузка...

### File: ../src/mainwindow.tcl
mcset ru {Downloading SQLiteStudio v%s...} {Загрузка SQLiteStudio версии %s...}

### File: ../src/mainwindow.tcl
mcset ru {Problem with saving new SQLiteStudio version to:
%s
Details:
%s} {Проблема при сохранении новой версии SQLiteStudio в:
%s
Подробности:
%s}

### File: ../src/data_editor.tcl
mcset ru {There are uncommited rows.
Are you sure you want to close '%s' window anywy?} {Имеются неподтверждённые строки.
Вы действительно хотите закрыть окно '%s'?}

### File: ../src/common/ddl_dialog.tcl
mcset ru {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s} {Невозможно подготовить DDL-код. Настройки в окне диалога заданы неполно.
Подробности:
%s}

### File: ../src/common/color_picker.tcl
mcset ru {Choose color} {Выберите цвет}

### File: ../src/common/shortcut_edit.tcl
mcset ru {Forbidden shortcut key combination: %s} {Запрещенное сочетание клавиш: %s}

### File: ../src/common/common.tcl
mcset ru Copy Копировать

### File: ../src/common/common.tcl
mcset ru Cut Вырезать

### File: ../src/common/common.tcl
mcset ru Paste Вставить

### File: ../src/common/blob_edit_panel.tcl
mcset ru {Text edit} {Текстовый вид}

### File: ../src/common/blob_edit_panel.tcl
mcset ru {Hexadecimal edit} {Шестнадцатеричный вид}

### File: ../src/common/hex_editor.tcl
mcset ru Processing Обработка

### File: ../src/common/hex_editor.tcl
mcset ru {Processing data...} {Обработка данных...}

### File: ../src/sql_editor.tcl
mcset ru {Replace dialog} Заменить

### File: ../src/sql_editor.tcl
mcset ru {Search dialog} Найти

### File: ../src/trees/db_tree.tcl
mcset ru Loading Загрузка

### File: ../src/trees/db_tree.tcl
mcset ru {Loading database list} {Загрузка списка баз данных}

### File: ../src/trees/db_tree.tcl
mcset ru {Given database file doesn't exist or is unreadable.} {Файл базы данных не существует или не читается.}

### File: ../src/trees/db_tree.tcl
mcset ru Vacuum Сжатие

### File: ../src/trees/db_tree.tcl
mcset ru {Integrity check} {Проверка целостности}

### File: ../src/trees/db_tree.tcl
mcset ru {Import schema from other database} {Импорт схемы из другой базы данных}

### File: ../src/trees/db_tree.tcl
mcset ru {Create foreign key} {Создать внешний ключ}

### File: ../src/trees/db_tree.tcl
mcset ru {Show view data} {Показать данные представления}

### File: ../src/trees/db_tree.tcl
mcset ru {Sort databases alphabetically} {Сортировка баз данных в алфавитном порядке}

### File: ../src/trees/db_tree.tcl
mcset ru {Given database is already on the list.} {Выбранная база данных уже есть в списке.}

### File: ../src/trees/db_tree.tcl
mcset ru {Given database name is already on the list.} {Заданное название базы данных уже есть в списке.}

### File: ../src/trees/db_tree.tcl
mcset ru Tables Таблицы

### File: ../src/trees/db_tree.tcl
mcset ru Views Представления

### File: ../src/trees/db_tree.tcl
mcset ru {SQLite system table} {Системная таблица SQLite}

### File: ../src/trees/db_tree.tcl
mcset ru Columns Столбцы

### File: ../src/trees/db_tree.tcl
mcset ru {SQLite system index} {Системный индекс SQLite}

### File: ../src/trees/db_tree.tcl
mcset ru {Remove database} {Удалить базу данных}

### File: ../src/trees/db_tree.tcl
mcset ru {Are you sure you want to remove '%s' database from the list?} {Вы действительно хотите удалить базу данных '%s' из списка?}

### File: ../src/trees/db_tree.tcl
mcset ru {'%s' is a virtual table, therefore cannot be browsed in table window.} {'%s' является виртуальной таблицей, её нельзя просматривать с помощью окна таблицы.}

### File: ../src/trees/db_tree.tcl
mcset ru {'%s' is a virtual table, therefore cannot be edited in table dialog.} {'%s' является виртуальной таблицей, её нельзя редактировать с помощью диалога редактирования таблицы.}

### File: ../src/trees/db_tree.tcl
mcset ru {Integrity check (%s)} {Проверка целостности (%s)}

### File: ../src/trees/db_tree.tcl
mcset ru {Are you sure you want to DROP '%s' table?} {Вы действительно хотите удалить таблицу '%s'?}

### File: ../src/trees/db_tree.tcl
mcset ru {Delete view} {Удалить представление}

### File: ../src/trees/db_tree.tcl
mcset ru {Are you sure you want to delete '%s' view?} {Вы действительно хотите удалить представление '%s'?}

### File: ../src/trees/db_tree.tcl
mcset ru {'%s' view data} {Данные представления '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru {Are you sure you want to make a vacuum?} {Вы действительно хотите произвести сжатие?}

### File: ../src/trees/db_tree.tcl
mcset ru {SQL files} {Файлы SQL}

### File: ../src/trees/db_tree.tcl
mcset ru {Select SQL file to be executed} {Выберите файлы SQL, которые необходимо выполнить}

### File: ../src/trees/db_tree.tcl
mcset ru {SQL executed sucessfly.} {SQL-запрос успешно выполнен.}

### File: ../src/trees/db_tree.tcl
mcset ru {Import database schema} {Импорт схемы базы данных}

### File: ../src/trees/db_tree.tcl
mcset ru {Column: %s} {Столбец: %s}

### File: ../src/grids/dbgrid.tcl
mcset ru {Edit BLOB entry:} {Редактирование записи BLOB:}

### File: ../src/grids/dbgrid.tcl
mcset ru {BLOB edit} {Редактирование BLOB}

### File: ../src/grids/grid.tcl
mcset ru {You have to select a cell before paste any contents.} {Выберите ячейку для вставки данных.}

### File: ../src/grids/grid.tcl
mcset ru {Cut data} Вырезать

### File: ../src/grids/grid.tcl
mcset ru {There are too many columns or rows to paste. Do you want to cut them and paste?} {Слишком много столбцов или строк для вставки. Вы хотите вырезать их и вставить?}

### File: ../src/grids/data_grid.tcl
mcset ru {Insert new row} {Вставить новую строку}

### File: ../src/grids/data_grid.tcl
mcset ru {Delete selected rows} {Удалить выделенные строки}

### File: ../src/grids/data_grid.tcl
mcset ru {Edit cell value} {Редактировать значение ячейки}

### File: ../src/grids/data_grid.tcl
mcset ru {Duplicate row} {Скопировать строку}

### File: ../src/grids/data_grid.tcl
mcset ru {Set NULL value} {Установить NULL-значение}

### File: ../src/grids/data_grid.tcl
mcset ru {Commit selected cells} {Подтвердить выбранные ячейки}

### File: ../src/grids/data_grid.tcl
mcset ru {Rollback selected cells} {Откатить выбранные ячейки}

### File: ../src/grids/data_grid.tcl
mcset ru {Show ordinals} {Показать порядковые номера}

### File: ../src/grids/data_grid.tcl
mcset ru {Show ROWIDs} {Показать значения ROWID}

### File: ../src/grids/data_grid.tcl
mcset ru Constraints: Ограничения:

### File: ../src/grids/data_grid.tcl
mcset ru {%s column has NOT NULL constraint. You have to fill value for it.} {Столбец %s не может содержать NULL-значения.}

### File: ../src/grids/data_grid.tcl
mcset ru {Error while adding new row:
%s} {Ошибка добавления новой строки:
%s}

### File: ../src/grids/data_grid.tcl
mcset ru {Error while updating new row:
%s} {Ошибка обновления новой строки:
%s}

### File: ../src/grids/data_grid.tcl
mcset ru {Error while updating cell value:
%s

What would you like to do?} {Ошибка обновления значения ячейки:
%s

Что необходимо предпринять?}

### File: ../src/grids/data_grid.tcl
mcset ru {Re-edit value} {Заново отредактировать значение}

### File: ../src/grids/data_grid.tcl
mcset ru {Return to value before edition} {Вернуть значение до редактирования}

### File: ../src/grids/data_grid.tcl
mcset ru {Error while deleting selected rows:
%s} {Ошибка удаления выделенных строк:
%s}

### File: ../src/grids/result_grid.tcl
mcset ru {No details are available on this cell.} {Для этой ячейки нет подробной информации.}

### File: ../src/grids/result_grid.tcl
mcset ru {Duplicated ROWID} {Дублирующийся ROWID}

### File: ../src/grids/result_grid.tcl
mcset ru {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?} {Обнаружено более одной строки с ROWID=%s, которые будут затронуты операцией вставки.
В этой ситуации возможны непредсказуемые результаты. Продолжить?}

# New entries

### File: ../src/win_assoc.tcl
mcset ru {File associations} {Файловые ассоциации}

### File: ../src/win_assoc.tcl
mcset ru {Following file extensions could not be associated to the current SQLiteStudio version:
%s} {Следующие расширения файлов не могут быть ассоциированы с текущей версией SQLiteStudio:
%s}

### File: ../src/win_assoc.tcl
mcset ru {Click the link below to find out what is possible reason and solutions.} {Щёлкните по ссылке ниже, чтобы узнать о возможных причинах проблемы и способах её устранения.}

### File: ../src/cfg_win.tcl
mcset ru {Restore last closed task} {Восстановить последнюю закрытую задачу}

### File: ../src/cfg_win.tcl
mcset ru {Restores last closed MDI window.} {Восстанавливает последнее закрытое MDI-окно.}

### File: ../src/cfg_win.tcl
mcset ru {Commit edition in Form View} {Подтвердить изменения в режиме формы}

### File: ../src/cfg_win.tcl
mcset ru {Commits edition in Form View of query results or table data preview.} {Подтверждает изменения, произведённые в режиме формы при просмотре результатов запроса или табличных данных.}

### File: ../src/cfg_win.tcl
mcset ru {Rollback edition in Form View} {Откатить изменения в режиме формы}

### File: ../src/cfg_win.tcl
mcset ru {Rolls back edition in Form View of query results or table data preview.} {Откатывает изменения, произведённые в режиме формы при просмотре результатов запроса или табличных данных.}

### File: ../src/cfg_win.tcl
mcset ru {Switch NULL value in form edit field} {Установить NULL-значение в поле формы}

### File: ../src/cfg_win.tcl
mcset ru {Sets or unsets NULL value in currently selected
column in form view data edit mode.} {Устанавливает или удаляет NULL-значение в текущем выделенном столбце
при редактировании данных в режиме формы.}

### File: ../src/cfg_win.tcl
mcset ru {Show ROWID as default instead of row order number in table data view} {По умолчанию показывать ROWID вместо порядкового номера строки в табличном виде данных}

### File: ../src/cfg_win.tcl
mcset ru {This option affects first column from the left on the data tab of the table window.} {Эта опция затрагивает первый слева столбец во вкладке данных окна таблицы.}

### File: ../src/cfg_win.tcl
mcset ru {Select all contents when editing the table cell} {Выделять всё содержимое при редактировании ячейки}

### File: ../src/cfg_win.tcl
mcset ru {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.} {Если опция активирована, каждый раз при входе в ячейку
для редактирования, её содержимое будет выделено.}

### File: ../src/cfg_win.tcl
mcset ru {Rows per page in Table Window and Editor Results:} {Количество строк на странице данных в окне таблицы и результатах запроса:}

### File: ../src/cfg_win.tcl
mcset ru {Insertion cursor blinking period (milliseconds):} {Период мерцания курсора (миллисекунд):}

### File: ../src/cfg_win.tcl
mcset ru {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.} {Количество миллисекунд, в течение которых курсор в окне редактора SQL совершает одно мерцание.
Установите значение в 0 для отключения мерцания.}

### File: ../src/cfg_win.tcl
mcset ru {View default display mode:} {Режим отображения представления по умолчанию:}

### File: ../src/cfg_win.tcl
mcset ru {Edition dialog} {Диалог редактирования}

### File: ../src/cfg_win.tcl
mcset ru {Data view} {Просмотр данных}

### File: ../src/cfg_win.tcl
mcset ru {Defines what is displayed by default when user opens a view.} {Определяет, что́ будет отображено по умолчанию при открытии пользователем представления.}

### File: ../src/cfg_win.tcl
mcset ru {Database tree display mode} {Режим отображения дерева баз данных}

### File: ../src/cfg_win.tcl
mcset ru {Show indexes and triggers linked under referenced table.} {Отображать индексы и триггеры под соответствующими таблицами.}

### File: ../src/cfg_win.tcl
mcset ru {Show indexes and triggers in their own groups.} {Отображать индексы и триггеры в своих отдельных группах.}

### File: ../src/cfg_win.tcl
mcset ru {Show column names linked under the table.} {Отображать имена столбцов под таблицей.}

### File: ../src/cfg_win.tcl
mcset ru {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.} {Возникла проблема при попытке открытия файла настроек: %s. Похоже, что директория %s была удалена или переименована. Настройки SQLiteStudio не будут сохранены.}

### File: ../src/cfg_win.tcl
mcset ru {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.} {Не удалось сохранить файл конфигурации. Некоторые настройки могли быть утеряны. Пожалуйста проверьте, доступен ли файл '%s' для записи.}

### File: ../src/db/query_executor.tcl
mcset ru {Imbalanced 'BEGIN' ocurrence in query.} {Несбалансированное количество 'BEGIN' в запросе.}

### File: ../src/db/query_executor.tcl
mcset ru {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.} {Результат недоступен для редактирования, так как был использован составной запрос SELECT. Для дополнительной информации см. абзац %s Руководства Пользователя.}

### File: ../src/db/query_executor.tcl
mcset ru {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.} {Результат недоступен для редактирования, так как было использовано ключевое слово DISTINCT. Для дополнительной информации см. абзац %s Руководства Пользователя.}

### File: ../src/db/query_executor.tcl
mcset ru {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.} {Результат недоступен для редактирования, так как была использована конструкция GROUP BY. Для дополнительной информации см. абзац %s Руководства Пользователя.}

### File: ../src/db/query_executor.tcl
mcset ru {Cannot use more than one 'BEGIN'.} {Невозможно использовать более одного 'BEGIN'.}

### File: ../src/db/query_executor.tcl
mcset ru {Imbalanced 'COMMIT' ocurrence in query.} {Несбалансированное количество 'COMMIT' в запросе.}

### File: ../src/db/query_executor.tcl
mcset ru {Imbalanced 'ROLLBACK' ocurrence in query.} {Несбалансированное количество 'ROLLBACK' в запросе.}

### File: ../src/db/db.tcl
mcset ru {Unable to open the database file} {Невозможно открыть файл базы данных}

### File: ../src/db/db.tcl
mcset ru {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.} {Невозможно присоединить базу данных %s. Она не существует, имеет несовместимую версию или формат файла некорректен.}

### File: ../src/db/db.tcl
mcset ru {Could not attach database %s. Error message from SQLite:
%s} {Невозможно присоединить базу данных %s. Сообщение об ошибке из SQLite:
%s}

### File: ../src/db/db.tcl
mcset ru {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.} {Невозможно получить SQL-код для присоединения базы данных %s. Она не существует, имеет несовместимую версию или формат файла некорректен.}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Error from importing plugin:
%s} {Ошибка из модуля импорта:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?} {Количество столбцов в целевой таблице '%s' меньше, чем в импортируемых данных. Что необходимо сделать?}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?} {Количество столбцов в целевой таблице '%s' больше, чем в импортируемых данных. Что необходимо сделать?}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Error creating table '%s':
%s

Importing aborted.} {Ошибка при создании таблицы '%s':
%s

Импорт прерван.}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Error trying to import data to '%s':
%s

Importing aborted.} {Ошибка при импортировании данных в таблицу '%s':
%s

Импорт прерван.}

### File: ../src/plugins/import_plugin.tcl
mcset ru Importing... Импорт...

### File: ../src/plugins/import_plugin.tcl
mcset ru {Importing to table '%s'.} {Импортирование в таблицу '%s'.}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?} {Модуль импорта сообщил об ошибке при запросе данных в строке %s. Подробности ошибки:
%s.

Что необходимо сделать?}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?} {Количество столбцов в строке данных %s отличается от количества, заданного модулем импорта. Что необходимо сделать?}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Problem occured while importing row number %s:
%s

What would you like to do?} {Возникла проблема при импорте строки %s:
%s

Что необходимо сделать?}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Importing finished.} {Импорт завершён.}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Import problem} {Проблема при импорте}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Skip this data row} {Пропустить эту строку данных}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Keep data rows imported so far (%s) and abort} {Сохранить уже импортированные строки (%s) и прервать}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Rollback data rows imported so far and abort} {Откатить уже импортированные строки и прервать}

### File: ../src/plugins/import_plugin.tcl
mcset ru {Ignore it and proceed} {Игнорировать и продолжить}

### File: ../src/plugins/import/csv.tcl
mcset ru {Input file} {Входной файл}

### File: ../src/plugins/import/csv.tcl
mcset ru {Show options} {Показать опции}

### File: ../src/plugins/import/csv.tcl
mcset ru {Column names} {Имена столбцов}

### File: ../src/plugins/import/csv.tcl
mcset ru {Treat first row as column names} {Рассматривать первую строку как имена столбцов}

### File: ../src/plugins/import/csv.tcl
mcset ru {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.} {Если опция активирована, первая строка в CSV-файле будет интерпретирована как имена столбцов.
Они будут проигнорированы при импорте в существующую таблицу.}

### File: ../src/plugins/import/csv.tcl
mcset ru {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.} {Символ, используемый для отделения каждого значения столбца
от других. Разделитель может быть частью значения столбца,
если это значение заключено в кавычки.}

### File: ../src/plugins/import/csv.tcl
mcset ru {NULL handling} {Обработка NULL-значений}

### File: ../src/plugins/import/csv.tcl
mcset ru {Treat following values as NULL:} {Рассматривать следующие значения как NULL:}

### File: ../src/plugins/import/csv.tcl
mcset ru Workarounds {Обходные пути}

### File: ../src/plugins/import/csv.tcl
mcset ru {Expect Microsoft format of CSV} {Ожидать формат CSV как у Microsoft}

### File: ../src/plugins/import/csv.tcl
mcset ru {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.} {Продукты Microsoft используют немного другой формат CSV-файлов.
Используйте эту опцию при импорте CSV-файла, полученного из этих приложений.}

### File: ../src/plugins/import/csv.tcl
mcset ru Encoding Кодировка

### File: ../src/plugins/import/csv.tcl
mcset ru {Convert from encoding:} {Конвертация из кодировки:}

### File: ../src/plugins/import/csv.tcl
mcset ru {Input file cannot be empty.} {Входной файл не может быть пустым.}

### File: ../src/plugins/import/csv.tcl
mcset ru {Input file is not readable.} {Ошибка чтения входного файла.}

### File: ../src/plugins/import/csv.tcl
mcset ru {CSV files} {CSV-файлы}

### File: ../src/plugins/import/csv.tcl
mcset ru {Text files} {Текстовые файлы}

### File: ../src/plugins/import/csv.tcl
mcset ru {File to import from} {Выбор файла для импорта}

### File: ../src/plugins/import/dbf.tcl
mcset ru Auto-detect Автоопределение

### File: ../src/plugins/import/dbf.tcl
mcset ru {dBase files} {Файлы dBase}

### File: ../src/plugins/import/regexp.tcl
mcset ru {Regular expression} {Регулярное выражение}

### File: ../src/plugins/import/regexp.tcl
mcset ru {Visual editor} {Визуальный редактор}

### File: ../src/plugins/import/regexp.tcl
mcset ru {Use Regular Expression Groups to identify columns.} {Используйте группы в регулярном выражении для определения столбцов.}

### File: ../src/plugins/import/regexp.tcl
mcset ru {Case insensitive} {Без учёта регистра}

### File: ../src/plugins/import/regexp.tcl
mcset ru {RegExp error:
%s} {Ошибка регулярного выражения:
%s}

### File: ../src/plugins/export/xls.tcl
mcset ru {If enabled, then first row of exported document will be a list of column names.} {Если опция активирована, первая строка экспортированного документа будет списком имён столбцов.}

### File: ../src/plugins/export/plain.tcl
mcset ru {Fixed column width:} {Фиксированная ширина столбца:}

### File: ../src/plugins/export/plain.tcl
mcset ru {Database: %s (%s, %s)} {База данных: %s (%s, %s)}

### File: ../src/plugins/export/json.tcl
mcset ru {Indented lines} {Отступы строк}

### File: ../src/plugins/export/json.tcl
mcset ru {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.} {SQLiteStudio произведёт разбивку сгенерированного JSON-кода на строки
и расставит отступы согласно их внутренней структуре,
при этом ключ каждого объекта будет расположен на отдельной строке.}

### File: ../src/plugins/export/json.tcl
mcset ru {Align lines} {Выровнять строки}

### File: ../src/plugins/export/json.tcl
mcset ru {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.} {SQLiteStudio выровняет по вертикали значения ключей объекта
для придания табличного вида.}

### File: ../src/plugins/export/json.tcl
mcset ru {Each row as object} {Каждая строка как объект}

### File: ../src/plugins/export/json.tcl
mcset ru {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.} {Если опция отключена, каждая строка экспортируется как JSON-массив.
Если опция активирована, каждая строка экспортируется как JSON-объект.
Ключами каждого объекта будут являться имена столбцов.}

### File: ../src/plugins/export/xml.tcl
mcset ru {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s} {Возникли проблемы при создании файла XSD, тем не менее все данные были успешно экспортированы в XML-файл. Подробности проблемы:
%s}

### File: ../src/plugins/export/html.tcl
mcset ru {First column of exported data
will contain row order number.} {Первый столбец экспортированных данных
будет содержать порядковый номер строки.}

### File: ../src/plugins/export/html.tcl
mcset ru {Column names in header will be prepended with "table_name." prefix.} {Имена столбцов в заголовке будут предваряться префиксом "table_name.".}

### File: ../src/plugins/export/dbf.tcl
mcset ru {Cannot overwrite file '%s'.} {Невозможно перезаписать файл '%s'.}

### File: ../src/plugins/export/pdf.tcl
mcset ru Dimensions Размеры

### File: ../src/plugins/export/pdf.tcl
mcset ru {Paper size:} {Размер бумаги:}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Margin size:} {Размер полей:}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Cell padding:} {Отступ в ячейке:}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Limit amount of data bytes in single cell to:} {Максимальный размер данных в ячейке (байт):}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Font size:} {Размер шрифта:}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Built-in font} {Встроенный шрифт}

### File: ../src/plugins/export/pdf.tcl
mcset ru Font: Шрифт:

### File: ../src/plugins/export/pdf.tcl
mcset ru {TrueType font} {Шрифт TrueType}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Font file:} {Файл шрифта:}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Font encoding:} {Кодировка шрифта:}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Columns and rows} {Столбцы и строки}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Header background} {Фон заголовка}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Empty space} {Пустое пространство}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Fill empty space in cells} {Заполнить пустое пространство в ячейках}

### File: ../src/plugins/export/pdf.tcl
mcset ru {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.} {Если у одного столбца в строке очень длинное значение,
а у других очень короткое, то при включении этой опции пустое пространство
под короткими значениями будет заполнено цветным фоном.}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Minimum height of empty space to fill:} {Минимальная высота пустого пространства для заливки:}

### File: ../src/plugins/export/pdf.tcl
mcset ru {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.} {Если высота пустого пространства в ячейке меньше
указанного здесь значения, заливка осуществлена не будет.}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Empty space background} {Фон пустого пространства}

### File: ../src/plugins/export/pdf.tcl
mcset ru {TTF Fonts} {TTF-шрифты}

### File: ../src/plugins/export/pdf.tcl
mcset ru {All Files} {Все файлы}

### File: ../src/plugins/export/pdf.tcl
mcset ru {Open TTF font} {Открыть шрифт TTF}

### File: ../src/plugins/populating/sql.tcl
mcset ru {Initialisation code} {Инициализирующий код}

### File: ../src/plugins/populating/sql.tcl
mcset ru {Per iteration code} {Код для каждой итерации}

### File: ../src/plugins/populating/sql.tcl
mcset ru {Closing code} {Завершающий код}

### File: ../src/taskbar.tcl
mcset ru {Window with given name already exists. Please type other name.} {Окно с таким именем уже существует. Пожалуйста задайте другое имя.}

### File: ../src/taskbar.tcl
mcset ru {Restore last closed window} {Восстановить последнее закрытое окно}

### File: ../src/windows/table_win.tcl
mcset ru {Import data to table (%s)} {Импорт данных в таблицу (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Add custom number of rows} {Добавить произвольное количество строк}

### File: ../src/windows/table_win.tcl
mcset ru {Commit changes (%s)} {Подтвердить изменения (%s)}

### File: ../src/windows/table_win.tcl
mcset ru {Import data to table} {Импорт данных в таблицу}

### File: ../src/windows/table_win.tcl
mcset ru {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.} {Для таблицы '%s' отсутствует DDL-код в таблице sqlite_master или она более не существует в базе данных. Окно этой таблицы сейчас будет закрыто.}

### File: ../src/windows/table_win.tcl
mcset ru {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.} {Одновременное использование символов %s, %s и %s в имени столбца крайне нежелательно. Рекомендуется переименовать столобец %s в таблице %s. Данные таблицы загружены не будут.}

### File: ../src/windows/table_win.tcl
mcset ru {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.} {У таблицы '%s' отсутствует DDL-код. Возможно она более не существует или это системная таблица.}

### File: ../src/windows/table_win.tcl
mcset ru {Enter number of rows to add:} {Введите количество добавляемых строк:}

### File: ../src/windows/table_win.tcl
mcset ru {Add rows} {Добавить строки}

### File: ../src/windows/table_win.tcl
mcset ru {Index '%s' has no DDL. Probably it's system index and should not be edited.} {У индекса '%s' отсутствует DDL-код. Возможно это системный индекс и редактировать его нельзя.}

### File: ../src/windows/table_win.tcl
mcset ru {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.} {У триггера '%s' отсутствует DDL-код. Возможно это системный триггер и редактировать его нельзя.}

### File: ../src/windows/table_win.tcl
mcset ru {Import data} {Импорт данных}

### File: ../src/windows/editor_win.tcl
mcset ru {Commit row (%s)} {Подтвердить строку (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Rollback row (%s)} {Откатить строку (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Delete selected history entry (%s)} {Удалить выбранную запись из истории (%s)}

### File: ../src/windows/editor_win.tcl
mcset ru {Delete the history entry} {Удалить запись из истории}

### File: ../src/windows/editor_win.tcl
mcset ru {Are you sure you want to delete selected queries history entry?} {Вы действительно хотите удалить выделенную запись из истории?}

### File: ../src/windows/editor_win.tcl
mcset ru {%s row(s) read in %s second(s).} {%s строк прочитано за %s секунд.}

### File: ../src/windows/editor_win.tcl
mcset ru {No SELECT statements found in editor or in selected part of SQL code.} {В редакторе или выделенном участке SQL-кода не найдено ни одного выражения SELECT.}

### File: ../src/windows/editor_win.tcl
mcset ru {More than one SELECT statements found. Please select the one you're interested in and then try again.} {Обнаружено более одного выражения SELECT. Пожалуйста выделите необходимый и попробуйте снова.}

### File: ../src/dialogs/bind_param.tcl
mcset ru {NULL value} {NULL-значение}

### File: ../src/dialogs/bind_param.tcl
mcset ru {You can use '%s' keyboard shortcut to switch NULL value.} {Для переключения NULL-значения вы можете использовать сочетание клавиш '%s'.}

### File: ../src/dialogs/bind_param.tcl
mcset ru {Copy value to other '%s' parameters (%s)} {Скопировать значение в другие параметры '%s' (%s)}

### File: ../src/dialogs/bind_param.tcl
mcset ru {By enabling this all parameters with same name
will also have same value as this one.} {При включении этой опции все параметры с тем же именем
будут иметь то же значение, что и этот.}

### File: ../src/dialogs/populate_table.tcl
mcset ru {On a constraint violation:} {При нарушении ограничения:}

### File: ../src/dialogs/import_dialog.tcl
mcset ru {Import from:} {Импорт из:}

### File: ../src/dialogs/import_dialog.tcl
mcset ru {Import to:} {Импорт в:}

### File: ../src/dialogs/import_dialog.tcl
mcset ru Existing Существующая

### File: ../src/dialogs/import_dialog.tcl
mcset ru {Create new table} {Создать новую таблицу}

### File: ../src/dialogs/import_dialog.tcl
mcset ru Import Импорт

### File: ../src/dialogs/import_dialog.tcl
mcset ru {Import method is not selected.} {Метод импорта не указан.}

### File: ../src/dialogs/import_dialog.tcl
mcset ru {No existing table is selected.} {Не выбрана существующая таблица.}

### File: ../src/dialogs/import_dialog.tcl
mcset ru {Table typed to create already exists. Please change table name.} {Таблица с набранным именем уже существует. Пожалуйста измените имя таблицы.}

### File: ../src/dialogs/export_dialog.tcl
mcset ru {Table or view} {Таблица или представление}

### File: ../src/dialogs/export_dialog.tcl
mcset ru {Exporting view '%s'.} {Экспорт представления '%s'.}

### File: ../src/dialogs/bug_report_login.tcl
mcset ru {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.} {Пожалуйста введите имя пользователя и пароль для использования при отсылке сообщений об ошибках и предложений по функционалу. Если вы ещё не зарегистрированы, вы можете сделать это по ссылке ниже. Отсылка отчётов под собственным именем пользователя упростит их дальнейшее отслеживание. Пароль будет сохранён в зашифрованном виде.}

### File: ../src/dialogs/bug_report_login.tcl
mcset ru Login: Логин:

### File: ../src/dialogs/bug_report_login.tcl
mcset ru Password: Пароль:

### File: ../src/dialogs/bug_report_login.tcl
mcset ru Validate Проверить

### File: ../src/dialogs/bug_report_login.tcl
mcset ru {Validation result} {Результат проверки}

### File: ../src/dialogs/bug_report_login.tcl
mcset ru {Not validated yet} {Ещё не проверено}

### File: ../src/dialogs/bug_report_login.tcl
mcset ru Validating... Проверка...

### File: ../src/dialogs/bug_report_login.tcl
mcset ru {Validating login and password...} {Проверка логина и пароля...}

### File: ../src/dialogs/bug_report_login.tcl
mcset ru {Invalid login or password.} {Неправильный логин или пароль.}

### File: ../src/dialogs/bug_report_login.tcl
mcset ru {Login and password are correct.} {Логин и пароль корректны.}

### File: ../src/dialogs/bug_report.tcl
mcset ru {Your e-mail address or user (both optional)} {Ваш адрес e-mail или имя пользователя (оба необязательны)}

### File: ../src/dialogs/bug_report.tcl
mcset ru {Log in} Войти

### File: ../src/dialogs/bug_report.tcl
mcset ru {Logged in} {Вход выполнен}

### File: ../src/dialogs/bug_report.tcl
mcset ru {Log out} Выйти

### File: ../src/dialogs/bug_report.tcl
mcset ru {Show more (optional)} {Дополнительно (необязательно)}

### File: ../src/dialogs/bug_report.tcl
mcset ru Hide Спрятать

### File: ../src/dialogs/yesno.tcl
mcset ru Question Вопрос

### File: ../src/dialogs/column_dialog.tcl
mcset ru {Use value as:} {Использовать значение как:}

### File: ../src/dialogs/column_dialog.tcl
mcset ru {A literal value} Литерал

### File: ../src/dialogs/column_dialog.tcl
mcset ru {An expression} Выражение

### File: ../src/dialogs/column_dialog.tcl
mcset ru {AUTOINCREMENT is allowed only with INTEGER type of column.} {AUTOINCREMENT можно использовать только у столбца с типом INTEGER.}

### File: ../src/dialogs/assoc_dialog.tcl
mcset ru {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:} {SQLiteStudio обнаружил следующие ассоциации расширений файлов с предыдущими версиями SQLiteStudio:}

### File: ../src/dialogs/assoc_dialog.tcl
mcset ru {Current associations} {Текущие ассоциации}

### File: ../src/dialogs/assoc_dialog.tcl
mcset ru {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.} {Пожалуйста выберите расширения файлов, которые вы хотите ассоциировать с текущей версией SQLiteStudio и нажмите ОК.}

### File: ../src/dialogs/db_edit.tcl
mcset ru {File '%s' doesn't exist!} {Файл '%s' не существует!}

### File: ../src/dialogs/db_edit.tcl
mcset ru {Database named '%s' already exists on databases list. Please pick other name.} {База данных с именем '%s' уже существует в списке баз данных. Пожалуйста выберите другое имя.}

### File: ../src/dialogs/db_edit.tcl
mcset ru {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.} {База данных '%s' уже существует в списке баз данных с именем '%s'. Пожалуйста выберите другой файл базы данных или отмените операцию.}

### File: ../src/dialogs/db_edit.tcl
mcset ru {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.} {Драйвер SQLite 2 плохо работает с не-ASCII именами файлов. Пожалуйста не используйте национальные символы, используйте ASCII-совместимое имя файла.}

### File: ../src/dialogs/table_dialog_pk.tcl
mcset ru {Using autoincrement with more than one column at once is forbidden.} {Одновременное использование автоинкремента для нескольких столбцов запрещено.}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		} {
			Правильные имена таблиц подсвечиваются в редакторе SQL-кода синим цветом (настраиваемо).
			Если введённое вами имя таблицы не подсвечено, то вы допустили ошибку при наборе имени
			или выбрали контекст другой базы данных в редакторе SQL-кода (сверху окна редактора),
			в которой таблицы с таким именем не существует.<br><br>
			Вы также можете зажать клавишу Control, при этом корректные имена таблиц будут подчёркнуты -
			они станут ссылками для быстрого доступа к соответствующим окнам этих таблиц.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		} {
			Вам необязательно подтверждать каждое изменение в таблице данных, нажимая Enter или кнопку "Применить" на панели инструментов.
			Вы можете просто щёлкнуть по другой ячейке (или в любое другое место), чтобы изменения данных подтвердились.
			Для отмены изменений, внесённых при редактировании ячейки, нажмите Escape.<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		} {
			SQLiteStudio предоставляет несколько дополнительных функций SQLite, которые вы можете использовать в редакторе SQL-кода. В их числе:
			tcl() - выполняет произвольный Tcl-код в новом, отдельном интерпретаторе Tcl,<br>
			sqlfile() - выполняет SQL-код из заданного файла в текущей базе данных,<br>
			md5() - вычисляет MD5-хэш заданного аргумента,<br>
			base64_encode() - кодирует заданное значение алгоритмом BASE64,<br>
			base64_decode() - декодирует заданное значение алгоритмом BASE64.<br>
			О других функциях вы можете узнать в Руководстве Пользователя.<br>
			Примеры:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 в степени 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		} {
			Для вставки в ячейку значения NULL (а не просто пустого значения), вам необходимо либо нажать клавишу Backspace при выделенной ячейке, или выбрать "Установить NULL-значение" в контекстном меню табличного вида.<br>
			Это можно сделать и при множественном выделении ячеек.<br><br>
			Режим формы позволяет вам устанавливать значение NULL отдельно для каждой ячейки, используя флажок или сочетание клавиш Alt-n (настраиваемо).<br><br>
			Помните, что вы всегда можете вставить значение NULL, используя SQL-запрос.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		} {
			Вы можете зажать клавишу "Control" и щёлкнуть по таблице с данными для выбора всей строки вместо одной ячейки.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset ru {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		} {
			В окне редактора SQL вы можете выбрать лишь часть SQL-запроса и щёлкнуть "Выполнить" (или нажать %s)
			для выполнения только выделенной части кода.
		}

### File: ../src/dialogs/release_notes_dialog.tcl
mcset ru {Don't show this dialog after update.} {Не показывать это окно после обновления.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset ru {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.} {Определяет список столбцов для действия 'UPDATE OF'.
Необходимо, чтобы таблица для триггера была уже выбрана.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru Details Подробности

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.} {Столбец '%s' более не существует в таблице '%s', поэтому вы не можете его редактировать. Возможно таблица была модифицирована другим приложением.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Constraint change} {Изменение ограничения}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Are you sure you want to change constraint type?
Current constraint configuration will be lost.} {Вы действительно хотите сменить тип ограничения?
Текущая конфигурация ограничения будет утеряна.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Table constraint number %s (%s) is not configured correctly.} {Ограничение с номером %s (%s) настроено некорректно.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {There is already a table with name '%s'. Please change the name of this table.} {Таблица с именем '%s' уже существует. Пожалуйста смените имя данной таблицы.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {There is already an index with name '%s'. Please change the name of this index.} {Индекс с именем '%s' уже существует. Пожалуйста смените имя данного индекса.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {There is already a trigger with name '%s'. Please change the name of this trigger.} {Триггер с именем '%s' уже существует. Пожалуйста смените имя данного триггера.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {There is already a view with name '%s'. Please change the name of this view.} {Представление с именем '%s' уже существует. Пожалуйста смените имя данного представления.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Невозможно проанализировать DDL-код представления '%s',
поэтому воссоздание его после модификации таблицы невозможно.
Вы хотите продолжить?}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {View parsing problem} {Проблема анализа представления}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.} {Невозможно проанализировать DDL-код следующих таблиц, поэтому ни один из их внешних ключей, ссылающихся на таблицу '%s' не будет воссоздан:

%s.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {%s(%s) referencing %s(%s)} {%s(%s) ссылается на %s(%s)}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s} {Следующие внешние ключи не будут воссозданы, т.к. они более не являются корректными:

%s}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Do you want to continue anyway?} {Вы хотите продолжить?}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?} {Следующие таблицы не будут воссозданы с правильными внешними ключами из-за ошибок базы данных:

%s

Вы хотите продолжить?}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Could not recreate views for modified table.} {Невозможно воссоздать представления для изменённой таблицы.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {Could not recreate foreign keys for tables referencing modified table.} {Невозможно воссоздать внешние ключи у таблиц, ссылающихся на изменённую таблицу.}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?} {Воссоздание представления '%s' после изменения таблицы будет невозможно.
Вы хотите продолжить?}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {View recreation problem} {Проблема при воссоздании представления}

### File: ../src/dialogs/table_dialog.tcl
mcset ru {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).} {Вы не можете использовать все четыре символа квотирования в SQL (%s, %s, %s и %s) в имени одного объекта (%s).}

### File: ../src/dialogs/new_version_dialog.tcl
mcset ru {Insufficient privileges to perform automatic update.} {Недостаточно прав для автоматического обновления.}

### File: ../src/dialogs/trigger_dialog_cols.tcl
mcset ru {Trigger columns} {Столбцы триггера}

### File: ../src/dialogs/index_dialog.tcl
mcset ru Available Доступны

### File: ../src/dialogs/index_dialog.tcl
mcset ru Indexed Индексированы

### File: ../src/dialogs/index_dialog.tcl
mcset ru {Modifying index} {Изменение индекса}

### File: ../src/dialogs/index_dialog.tcl
mcset ru {Modifying index '%s'} {Изменение индекса '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset ru {Creating index} {Создание индекса}

### File: ../src/dialogs/index_dialog.tcl
mcset ru {Creating index '%s'} {Создание индекса '%s'}

### File: ../src/dialogs/functions_dialog.tcl
mcset ru {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.} {Используйте $0, $1, $2, $3, ... в качестве позиционных параметров,
которые будут переданы в функцию.
Например, вызов функции my_function('x',5) вызовет функцию
my_function с 'x' как $0 и 5 как $1.}

### File: ../src/mainwindow.tcl
mcset ru {Settings (%s)} {Настройки (%s)}

### File: ../src/mainwindow.tcl
mcset ru {Clear objects filter} {Сбросить фильтр объектов}

### File: ../src/mainwindow.tcl
mcset ru {Enter object name you want to look for} {Введите имя объекта для поиска}

### File: ../src/mainwindow.tcl
mcset ru {Export table or view} {Экспорт таблицы или представления}

### File: ../src/mainwindow.tcl
mcset ru {Import data to a table} {Импорт данных в таблицу}

### File: ../src/mainwindow.tcl
mcset ru Donate Пожертвование

### File: ../src/mainwindow.tcl
mcset ru {Problem occurred while reporting bug. You can ignore it and get back to your work.} {Возникла проблема при отправке отчёта об ошибке. Вы можете проигнорировать её и вернуться к работе.}

### File: ../src/mainwindow.tcl
mcset ru {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history} {Отчёт об ошибке успешно отправлен. Спасибо! Вы всегда можете взглянуть на обсуждение вашего отчёта, выбрав в меню SQLiteStudio пункт 'Отобразить историю отчётов об ошибках'}

### File: ../src/mainwindow.tcl
mcset ru {A timeout occured while downloading new version. Try again, or download it manually.} {Истекло время ожидания при загрузке новой версии. Попробуйте снова или загрузите обновление вручную.}

### File: ../src/mainwindow.tcl
mcset ru {An error occured while downloading new version. Try again, or download it manually.} {Возникла ошибка при загрузке новой версии. Попробуйте снова или загрузите обновление вручную.}

### File: ../src/mainwindow.tcl
mcset ru {Problem with getting new SQLiteStudio version
Details:
%s} {Проблема при загрузке новой версии SQLiteStudio
Подробности:
%s}

### File: ../src/mainwindow.tcl
mcset ru {This is unknown binary distribution. Cannot determinate binary file to download for update.} {Неизвестный бинарный дистрибутив. Невозможно определить бинарный файл для обновления.}

### File: ../src/common/common_sql.tcl
mcset ru {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
} {Невозможно открыть диалог, так как DDL-код запрошенного объекта не поддерживается данной версией SQLiteStudio. Подробности:
}

### File: ../src/common/hex_editor.tcl
mcset ru {Overwrite characters,
instead of inserting} {Перезаписывать символы
вместо вставки}

### File: ../src/trees/db_tree.tcl
mcset ru {Reset autoincrement for '%s'} {Сбросить счётчик автоинкремента для '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru {Erase table data} {Удалить данные из таблицы}

### File: ../src/trees/db_tree.tcl
mcset ru {Export view} {Экспорт представления}

### File: ../src/trees/db_tree.tcl
mcset ru {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.} {У таблицы '%s' отсутствует DDL-код. Возможно это системная таблица, доступ к которой через окно таблицы невозможен.}

### File: ../src/trees/db_tree.tcl
mcset ru {Table '%s' has no DDL. Probably it's system table and should not be edited.} {У таблицы '%s' отсутствует DDL-код. Возможно это системная таблица, редактирование которой невозможно}

### File: ../src/trees/db_tree.tcl
mcset ru {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.} {'%s' является виртуальной таблицей. Клонирование возможно только для обычных таблиц SQLite.}

### File: ../src/trees/db_tree.tcl
mcset ru {Dropping table} {Удаление таблицы}

### File: ../src/trees/db_tree.tcl
mcset ru {Dropping table '%s'} {Удаление таблицы '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru {Dropping index} {Удаление индекса}

### File: ../src/trees/db_tree.tcl
mcset ru {Dropping index '%s'} {Удаление индекса '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?} {У триггера '%s' некорректный DDL-код. Редактирование его в окне диалога невозможно. Вам необходимо удалить его и воссоздать с корректным синтаксисом.

SQLiteStudio может поместить DDL-код этого триггера в новое окно редактора SQL кода, чтобы вы могли увидеть ошибку и исправить её. Вы хотите, чтобы SQLiteStudio сделал это?}

### File: ../src/trees/db_tree.tcl
mcset ru {Fix trigger} {Исправить триггер}

### File: ../src/trees/db_tree.tcl
mcset ru {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.} {У триггера '%s' отсутствует DDL-код.
Возможно это системный триггер, редактирование которого невозможно.}

### File: ../src/trees/db_tree.tcl
mcset ru {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?} {У представления '%s' некорректный DDL-код. Редактирование его в окне диалога невозможно. Вам необходимо удалить его и воссоздать с корректным синтаксисом.

SQLiteStudio может поместить DDL-код этого представления в новое окно редактора SQL кода, чтобы вы могли увидеть ошибку и исправить её. Вы хотите, чтобы SQLiteStudio сделал это?}

### File: ../src/trees/db_tree.tcl
mcset ru {Fix view} {Исправить представление}

### File: ../src/trees/db_tree.tcl
mcset ru {View '%s' has no DDL. Probably it's system view and should not be edited.} {У представления '%s' отсутствует DDL-код. Возможно это системное представление, редактирование которого невозможно.}

### File: ../src/trees/db_tree.tcl
mcset ru {Erase data} {Удалить данные}

### File: ../src/trees/db_tree.tcl
mcset ru {Are you sure you want to delete all data from table '%s'?} {Вы действительно хотите удалить все данные из таблицы '%s'?}

### File: ../src/trees/db_tree.tcl
mcset ru {Deleting data} {Удаление данных}

### File: ../src/trees/db_tree.tcl
mcset ru {Deleting data from table '%s'} {Удаление данных из таблицы '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru Vacuuming Сжатие

### File: ../src/trees/db_tree.tcl
mcset ru {Vacuuming '%s'} {Сжатие '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru {Error while executing SQL:
%s} {Ошибка при выполнении SQL-кода:
%s}

### File: ../src/trees/db_tree.tcl
mcset ru {Database: %s} {База данных: %s}

### File: ../src/trees/db_tree.tcl
mcset ru URI: URI:

### File: ../src/trees/db_tree.tcl
mcset ru Version: Версия:

### File: ../src/trees/db_tree.tcl
mcset ru {File size:} {Размер файла:}

### File: ../src/trees/db_tree.tcl
mcset ru {Schema version:} {Версия схемы:}

### File: ../src/trees/db_tree.tcl
mcset ru {Virtual table} {Виртуальная таблица}

### File: ../src/trees/db_tree.tcl
mcset ru Indexes: Индексы:

### File: ../src/trees/db_tree.tcl
mcset ru Triggers: Триггеры:

### File: ../src/trees/db_tree.tcl
mcset ru {Not null} {Не null}

### File: ../src/trees/db_tree.tcl
mcset ru {Indexed table:} {Индексируемая таблица:}

### File: ../src/trees/db_tree.tcl
mcset ru {Copy index '%s' for table '%s'} {Скопировать индекс '%s' в таблицу '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru {Move index '%s' to table '%s'} {Переместить индекс '%s' в таблицу '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru {Copy trigger '%s' for table '%s'} {Скопировать триггер '%s' в таблицу '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru {Move trigger '%s' to table '%s'} {Переместить триггер '%s' в таблицу '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru {Copy view '%s' for database '%s'} {Скопировать представление '%s' в базу данных '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru {Move view '%s' to database '%s'} {Переместить представление '%s' в базу данных '%s'}

### File: ../src/trees/db_tree.tcl
mcset ru {View '%s' has no DDL, therefore cannot be edited.} {У представления '%s' отсутствует DDL-код, поэтому его редактирование невозможно.}

### File: ../src/trees/db_tree.tcl
mcset ru {Copy view} {Скопировать представление}

### File: ../src/trees/db_tree.tcl
mcset ru {Move view} {Переместить представление}

### File: ../src/trees/db_tree.tcl
mcset ru Move Переместить

### File: ../src/trees/db_tree.tcl
mcset ru {Copy index} {Скопировать индекс}

### File: ../src/trees/db_tree.tcl
mcset ru {Move index} {Переместить индекс}

### File: ../src/trees/db_tree.tcl
mcset ru {Copy trigger} {Скопировать триггер}

### File: ../src/trees/db_tree.tcl
mcset ru {Move trigger} {Переместить триггер}

### File: ../src/trees/db_tree.tcl
mcset ru {Copy table '%s' to database '%s' (include data, indexes and triggers)} {Скопировать таблицу '%s' в базу данных '%s' (включая данные, индексы и триггеры)}

### File: ../src/trees/db_tree.tcl
mcset ru {Copy table '%s' to database '%s' (include data)} {Скопировать таблицу '%s' в базу данных '%s' (включая данные)}

### File: ../src/trees/db_tree.tcl
mcset ru {Copy table '%s' to database '%s' (include indexes and triggers)} {Скопировать таблицу '%s' в базу данных '%s' (включая индексы и триггеры)}

### File: ../src/trees/db_tree.tcl
mcset ru {Copy table '%s' to database '%s' (skip data, indexes and triggers)} {Скопировать таблицу '%s' в базу данных '%s' (пропустив данные, индексы и триггеры)}

### File: ../src/trees/db_tree.tcl
mcset ru {Move table '%s' to database '%s' (include data, indexes and triggers)} {Переместить таблицу '%s' в базу данных '%s' (включая данные, индексы и триггеры)}

### File: ../src/trees/db_tree.tcl
mcset ru {Move table '%s' to database '%s' (include data)} {Переместить таблицу '%s' в базу данных '%s' (включая данные)}

### File: ../src/trees/db_tree.tcl
mcset ru {Move table '%s' to database '%s' (include indexes and triggers)} {Переместить таблицу '%s' в базу данных '%s' (включая индексы и триггеры)}

### File: ../src/trees/db_tree.tcl
mcset ru {Move table '%s' to database '%s' (skip data, indexes and triggers)} {Переместить таблицу '%s' в базу данных '%s' (пропустив данные, индексы и триггеры)}

### File: ../src/trees/db_tree.tcl
mcset ru {Copying table...} {Копирование таблицы...}

### File: ../src/trees/db_tree.tcl
mcset ru {Copying table '%s' from '%s' to '%s'.} {Копирование таблицы '%s' из '%s' в '%s'.}

### File: ../src/trees/db_tree.tcl
mcset ru {Moving table...} {Перемещение таблицы...}

### File: ../src/trees/db_tree.tcl
mcset ru {Moving table '%s' from '%s' to '%s'.} {Перемещение таблицы '%s' из '%s' в '%s'.}

### File: ../src/trees/db_tree.tcl
mcset ru {Could not create object in target database:
%s} {Невозможно создать объект в целевой базе данных:
%s}

### File: ../src/trees/db_tree.tcl
mcset ru {Could not copy data:
%s} {Невозможно скопировать данные:
%s}

### File: ../src/trees/db_tree.tcl
mcset ru {Could not copy table data from source database to target database. Details: %s} {Невозможно скопировать табличные данные из источника в целевую базу данных. Подробности: %s}

### File: ../src/trees/db_tree.tcl
mcset ru {Could not delete object(s) from source database. Details: %s} {Невозможно удалить объект(ы) из источника. Подробности: %s}

### File: ../src/grids/dbgrid.tcl
mcset ru {Cannot commit. Details:
%s} {Подтверждение невозможно. Подробности:
%s}

### File: ../src/grids/data_grid.tcl
mcset ru {Edit cell value in BLOB editor} {Редактировать значение ячейки в редакторе BLOB}

### File: ../src/grids/data_grid.tcl
mcset ru {Generate SELECT from selected cells} {Сгенерировать SELECT из выделенных ячеек}

### File: ../src/grids/data_grid.tcl
mcset ru {Select all} {Выделить всё}

### File: ../src/grids/data_grid.tcl
mcset ru Type: Тип:

### File: ../src/grids/data_grid.tcl
mcset ru {Cannot delete row(s), because it violates constraint. Details:
%s} {Удаление строк(и) невозможно, так как это нарушает ограничение. Подробности:
%s}

### File: ../src/grids/data_grid.tcl
mcset ru {SQL query generated at %s
using selected cells from window '%s'.} {SQL-запрос сгенерирован %s
с использованием выбранных ячеек в окне '%s'.}

### File: ../src/grids/result_grid.tcl
mcset ru {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.} {Столбец '%s' нередактируемый. Можно редактировать только столбцы с соответствующими им ROWID в таблице или SQL-запрос слишком сложен.}

### File: ../src/grids/result_grid.tcl
mcset ru {Data type:} {Тип данных:}

### File: ../src/grids/result_grid.tcl
mcset ru {Could not parse SQL while trying to generate requested query: %s} {Невозможно проанализировать SQL при попытке генерации требуемого запроса: %s}

### File: ../src/grids/result_grid.tcl
mcset ru {Cannot use '%s' statement to generate requested query.} {Невозможно использовать выражение '%s' для генерации требуемого запроса.}

### File: ../src/grids/result_grid.tcl
mcset ru {Cannot determinate selected column with ID=%s.} {Невозможно определить выбранный столбец с ID=%s.}

### File: ../src/grids/result_grid.tcl
mcset ru {Error occurred while trying to generate the query: %s} {При попытке генерации запроса возникла ошибка: %s}

### File: ../src/grids/result_grid.tcl
mcset ru {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s} {SQL-запрос сгенерирован %s
с использованием выбранных результатов в окне '%s'.
Исходный запрос:
%s}

# Old, deprecated entries
mcset ru {Commit edition in Grid view and Form View} {Подтвердить редактирование в режиме формы и в режиме таблицы}
mcset ru {Commits edition in Grid View and Form View of query results or table data preview.} {Подтверждает редактирование результатов запроса или табличных данных в режиме формы и в режиме таблицы.}
mcset ru {Rollback edition in GridView and Form View} {Отменить редактирование в режиме формы и в режиме таблицы}
mcset ru {Rolls back edition in Grid View and Form View of query results or table data preview.} {Отменяет редактирование результатов запроса или табличных данных в режиме формы и в режиме таблицы.}
mcset ru {Auto-commit edition in data grid view} {Автоподтверждение изменений в режиме таблицы}
mcset ru {If enabled, then changes in grid view of data
won't need to be commited manually.
They will be commited automatically as soon as possible.} {Если опция активирована, произведённые изменения
в режиме таблицы не нужно принудительно подтверждать.
Они будут подтверждены автоматически, как только это станет возможным.}
mcset ru {Results per page in Table Window and Editor Results:} {Количество строк на странице:}
mcset ru {Problem occured while tried to open settings file: %s.
Seems like %s directory was deleted or renamed.
The SQLiteStudio settings won't be saved.} {Возникла проблема при попытке открытия файла настроек: %s.
Похоже, что, директория %s была удалена или переименована.
Настройки SQLiteStudio не будут сохранены.}
mcset ru {Could not save configuration file. Some settings might get lost.
Please check if file '%s' is writable.} {Невозможно сохранить файл настроек. Некоторые настройки могли быть утеряны.
Пожалуйста проверьте доступность для записи файла '%s'.}
mcset ru {SQLiteStudio could not interprete typed query, thus execution could not be controlled. All special execution features were disabled for this query.} {SQLiteStudio не смог интерпретировать введённый запрос, поэтому контроль над его выполнением невозможен. Все специальные возможности были отключены для этого запроса.}
mcset ru {Operation terminated by sqlite_interrupt()} {Операция прервана вызовом sqlite_interrupt()}
mcset ru {Could not attach database %s.
It doesn't exists, has incompatible version,
or file format is invalid.} {Невозможно присоединить базу данных %s.
Она не существует, имеет несовместимую версию
или формат файла некорректнен.}
mcset ru {Could not attach database %s.
Error message from SQLite:
%s} {Невозможно присоединить базу данных %s.
Сообщение об ошибке SQLite:
%s}
mcset ru {Could not get attach SQL for database %s.
It doesn't exists, has incompatible version,
or file format is invalid.} {Невозможно получить SQL-код присоединения для базы данных %s.
Она не существует, имеет несовместимую версию
или формат файла некорректнен.}
mcset ru {CSV exporting plugin does not support exporting whole database.} {Плагин экспорта в CSV не поддерживает экспорт всей базы данных.}
mcset ru {There were problems while creating XSD file,
but all data was successfly exported to XML file anyway.
Problems details:
%s} {Возникла проблема при создании файла XSD,
тем не менее все данные были успешно экспортированы в XML-файл.
Подробности проблемы:
%s}
mcset ru {First column of exported data
will contain number row.} {Первый столбец экспортируемых данных
будет содержать номер строки.}
mcset ru {Column names in header will be prepended with \"table_name.\" prefix.} {Названия столбцов будут начинаться с префикса \"название_таблицы.\".}
mcset ru {Commit new row} {Подтвердить добавление новой строки}
mcset ru {First %s rows (%s)} {Первые %s строк (%s)}
mcset ru {Previous %s rows (%s)} {Последние %s строк (%s)}
mcset ru {Next %s rows (%s)} {Следующие %s строк (%s)}
mcset ru {Last %s rows (%s)} {Предыдущие %s строк (%s)}
mcset ru {Commit changes} {Подтвердить изменения}
mcset ru {Rollback changes} {Откатить изменения}
mcset ru {Table '%s' doesn't have DDL in sqlite_master table
or doesn't exist in database anymore.
This table window will be closed now.} {Таблица '%s' не имеет DDL-кода в таблице sqlite_master
или более не содержится в базе данных.
Окно этой таблицы сейчас будет закрыто.}
mcset ru {Using all of %s, %s and %s characters in column name at once is highly discouraged
and should be avoided at all costs.
Therefor changing name of column %s in table %s is recommended.
Table data won't be loaded now.} {Одновременное использование символов %s, %s и %s в названии столбца крайне нежелательно,
и этого следует избегать во что бы то ни стало.
Рекомендуется переименовать столбец %s в таблице %s.
Данные из таблицы загружены не будут.}
mcset ru {Cannot parse trigger DDL. The table was propably created in different SQLite version.
Edit table manually (using SQL queries) to match SQLite version %s syntax.} {Невозможно проанализировать DDL-код триггера. Вероятно, таблица была создана в другой версии SQLite.
Отредактируйте таблицу вручную (используя SQL запросы) так, чтобы синтаксис соответствовал SQLite версии %s.}
mcset ru {Table '%s' has no DDL.
Propably it doesn't exist anymore, or it's system table.} {У таблицы '%s' отсутствует DDL-код.
Вероятно таблицы больше не существует или это системная таблица.}
mcset ru {Index '%s' has no DDL.
Propably it's system index and should not be edited.} {У индекса '%s' отсутствует DDL-код.
Вероятно это системный индекс, и редактировать его нельзя.}
mcset ru {Trigger '%s' has no DDL.
Propably it's system index and should not be edited.} {У триггера '%s' отсутствует DDL-код.
Вероятно это системный индекс, и редактировать его нельзя.}
mcset ru {Commit row} Подтвердить
mcset ru {Rollback row} Откатить
mcset ru {No SELECT statements found in editor
or in selected part of SQL code.} {В редакторе или выделенном участке SQL-кода
не было найдено ни одного выражения SELECT.}
mcset ru {More than one SELECT statements found.
Please select the one you're interested in and then try again.} {Обнаружено более одного выражения SELECT.
Пожалуйста, выделите необходимый вам и попробуйте снова.}
mcset ru {Your e-mail address:} {Ваш адрес e-mail:}
mcset ru {Browse for not existing file to create new database.} {Укажите несуществующий файл для создания новой базы данных.}
mcset ru {Browse for existing database file.} {Укажите существующий файл базы данных.}
mcset ru {Database named '%s' already exists on databases list.
Please pick other name.} {База данных с именем '%s' уже существует в списке баз данных.
Выберите другое имя.}
mcset ru {Database '%s' already exists on databases list with name '%s'.
Please pick other name.} {База данных '%s' уже существует в списке баз данных с именем '%s'.
Выберите другое имя.}
mcset ru {SQLite 2 driver doesn't deal with non-ASCII file names well.
Please do not use national characters, use ASCII-compliant file name.} {Драйвер SQLite версии 2 плохо поддерживает имена файлов с не-ASCII символами.
Пожалуйста не используйте национальные символы, используйте ASCII-совместимое имя файла.}
mcset ru {
			Valid table names in SQL editor are highlighted with blue color (configurable) and underline.
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.
		} {
			Правильные имена таблиц подсвечиваются в редакторе SQL-кода синим цветом (настраиваемо) и подчёркиваются.
			Если введённое вами имя таблицы не подсвечено, то вы допустили ошибку при наборе имени
			или выбрали контекст другой базы данных в редакторе SQL-кода (сверху окна редактора),
			в которой таблицы с таким именем не существует.
		}
mcset ru {
			You do not have to commit each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.
		} {
			Вам необязательно подтверждать каждое изменение в таблице данных, нажимая Enter или кнопку "Применить" на панели инструментов.
			Вы можете просто щёлкнуть по другой ячейке (или в любое другое место), чтобы изменения данных подтвердились.
			Для отмены изменений, внесённых при редактировании ячейки, нажмите Escape.
		}
mcset ru {
			While editing BLOB fields pay attention to different natures of Text Edit mode and Hex Edit mode.
			First one is less powerful, but lets you to append new data. Second allows to edit each byte precisely,
			but it can't append any new data.
		} {
			При редактировании полей типа BLOB обратите внимание на разницу между Текстовым режимом правки и Шестнадцатеричным режимом правки.
			Первый менее функционален, однако позволяет добавлять данные. Второй позволяет точно редактировать каждый байт,
			однако добавление данных невозможно.
		}
mcset ru {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - which runs custom Tcl code in new, separated Tcl interpreter, and sqlfile() - which
			executes SQL from given file in current database.<br>Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');
		} {
			SQLiteStudio предоставляет несколько дополнительных функций SQLite, которые вы можете использовать в редакторе SQL-кода. В их числе:
			tcl() - которая выполняет произвольный Tcl-код в новом, отдельном интерпретаторе Tcl, и sqlfile() - которая
			выполняет SQL-код из заданного файла в текущей базе данных.<br>Примеры:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');
		}
mcset ru {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Remember that you can always set NULL value manually using SQL query.
		} {
			Для вставки в ячейку значения NULL (а не просто пустого значения), вам необходимо либо нажать клавишу Backspace при выделенной ячейке, или выбрать "Установить NULL-значение" в контекстном меню табличного вида.<br>
			Это можно сделать и при множественном выделении ячеек.<br><br>
			Помните, что вы всегда можете вставить значение NULL используя SQL-запрос.
		}
mcset ru {You have to specify 'when' condition.} {Не выбран тип триггера.}
mcset ru {Column '%s' is no longer in table '%s', so you cannot edit it.
Table was probably modified by other application.} {Столбец '%s' более не существует в таблице '%s', поэтому вы не можете его редактировать.
Возможно таблица была изменена другим приложением.}
mcset ru {Unique constraint configuration} {Настройки ограничения уникальности}
mcset ru {Table primary key is not configured correctly.} {Первичный ключ таблицы настроен некорректно.}
mcset ru {Table foreign key is not configured correctly.} {Внешний ключ таблицы настроен некорректно.}
mcset ru {Table unique constraint is not configured correctly.} {Ограничение 'unique' таблицы настроено некорректно.}
mcset ru {Table check constraint is not configured correctly.} {Ограничение 'check' таблицы настроено некорректно.}
mcset ru {There is already a table with name '%s'.
Please change the name of this table.} {Таблица с именем '%s' уже существует.
Пожалуйста, смените имя этой таблицы.}
mcset ru {There is already an index with name '%s'.
Please change the name of this index.} {Индекс с именем '%s' уже существует.
Пожалуйста, смените имя этого индекса.}
mcset ru {There is already a trigger with name '%s'.
Please change the name of this trigger.} {Триггер с именем '%s' уже существует.
Пожалуйста, смените имя этого триггера.}
mcset ru {There is already a view with name '%s'.
Please change the name of this view.} {Представление с именем '%s' уже существует.
Пожалуйста, смените имя этого представления.}
mcset ru {Table '%s' references table '%s'. Please remove foreign key reference to table before editing it.} {Таблица '%s' ссылается на таблицу '%s'. Удалите связь по внешнему ключу с таблицей перед редактированием.}
mcset ru {You cannot use all four SQL quoting characters (%s, %s, %s and %s)
in one object name (which is: %s).} {Вы не можете использовать все четыре символа квотирования SQL (%s, %s, %s и %s)
в одном имени объекта (которым является: %s).}
mcset ru {Database inconsistency} {Противоречивость базы данных}
mcset ru {It looks like index '%s' is configured for column
that doesn't exist in table '%s'.} {Возможно, индекс '%s' использует столбец,
которого нет в таблице '%s'.}
mcset ru {Problem occured while reporting bug.
You can ignore it and get back to your work.} {Возникла проблема при отправке отчёта об ошибке.
Вы можете проигнорировать её и вернуться к работе.}
mcset ru {Bug successfly reported. Thank you!
You can always look at discussion about your report
using menu SQLiteStudio -> Show bug reports history} {Отчёт об ошибке успешно отправлен. Спасибо!
В любой момент вы можете посмотреть обсуждение вашего отчёта,
выбрав в меню SQLiteStudio пункт Отобразить историю отчётов об ошибках}
mcset ru {A timeout occured while downloading new version.
Try again, or download it manually.} {Истекло время ожидания при загрузке новой версии.
Попробуйте снова, или загрузите обновление вручную.}
mcset ru {An error occured while downloading new version.
Try again, or download it manually.} {При загрузке новой версии произошла ошибка.
Попробуйте снова, или загрузите обновление вручную.}
mcset ru {This is unknown binary distribution.
Cannot determinate binary file to download for update.} {Неизвестный бинарный дистрибутив.
Невозможно определить бинарный файл для обновления.}
mcset ru {Window with given name already exists.
Please type other name.} {Окно с таким именем уже существует.
Введите другое имя.}
mcset ru {Cannot open dialog, because requested object DDL code
is not supported by this version of SQLiteStudio.
Details:
} {Невозможно открыть диалог, так как DDL-код запрошенного объекта
не поддерживается данной версией SQLiteStudio.
Подробности:
}
mcset ru {Table '%s' has no DDL.
Propably it's system table and cannot be accessed with table window.} {У таблицы '%s' отсуствует DDL-код.
Возможно это системная таблица, доступ к которой с помощью окна таблицы невозможен.}
mcset ru {View '%s' has no DDL.
Propably it's system index and should not be edited.} {У представления '%s' отсутствует DDL-код.
Возможно это системный индекс и редактировать его нельзя.}
mcset ru {Error while executing SQL:} {Ошибка выполнения запроса SQL:}
mcset ru {Seems like this data grid no longer has database connection, therefor you cannot edit or commit it anymore.} {Похоже, что эта таблица данных более не имеет подключения к базе данных, поэтому дальнейшее редактироване и подтверждение транзакций невозможно.}
mcset ru {Cannot commit.
Details: %s} {Невозможно подтвердить транзакцию.
Подробности: %s}
mcset ru {Type: %s} {Тип: %s}
mcset ru {Blob edit} {Редактирование Blob}
mcset ru {Blob data too big to edit in dialog. Use SQL queries.} {Размер Blob-данных слишком велик для редактирования в диалоге. Используйте SQL-запросы.}
mcset ru {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable.} {Столбец '%s' нередактируемый. Только столбцы с соответствующим ROWID в таблице можно редактировать.}
mcset ru {Column table: %s} {Столбец таблицы: %s}
mcset ru {Pleas provide valid e-mail address or leave 'E-mail' empty.} {Pleas provide valid e-mail address or leave 'E-mail' empty.}
mcset ru {This e-mail will NOT be shared to anyone, neither used for any other\npurpose then described below. It won't be published anywhere.\nIt will be used only by SQLiteStudio developer to eventually contact\nyou if any additional details for this report are necessary.\n\nIt is optional. You can leave it empty.} {This e-mail will NOT be shared to anyone, neither used for any other\npurpose then described below. It won't be published anywhere.\nIt will be used only by SQLiteStudio developer to eventually contact\nyou if any additional details for this report are necessary.\n\nIt is optional. You can leave it empty.}
mcset ru {File to export} {Файл для экспорта данных}
mcset ru {Using all of %s, %s and %s characters in column name at once is highly discouraged
and should be ommited at all costs.
Therefor changing name of column %s in table %s is recommended.
Table data won't be loaded now.} {Using all of %s, %s and %s characters in column name at once is highly discouraged
and should be ommited at all costs.
Therefor changing name of column %s in table %s is recommended.
Table data won't be loaded now.}
mcset ru {Using all of %s, %s and %s characters in column name at once is highly discouraged
in database object names and should be ommited at all costs.
Therefor changing name of column %s in table %s is recommended.
Table data won't be loaded now.} {Using all of %s, %s and %s characters in column name at once is highly discouraged
in database object names and should be ommited at all costs.
Therefor changing name of column %s in table %s is recommended.
Table data won't be loaded now.}
mcset ru {Unknown error while query execution. Please report it! ReturnCode=%2. Query for execution was: %s} {Unknown error while query execution. Please report it! ReturnCode=%2. Query for execution was: %s}
mcset ru {Cannot proceed operation because database file is locked.
Perhaps some other application is accessing it.} {Не удается выполнить операцию, так как файл базы данных заблокирован.
Возможно, файл используется другим приложением.}
mcset ru {Unknown error while query execution. Please report it! Query for execution was: %s} {Unknown error while query execution. Please report it! Query for execution was: %s}
mcset ru {Error while converting database: %s} {Ошибка преобразования базы данных: %s}
mcset ru {Button hint} {Button hint}
mcset ru {Button hint 2} {Button hint 2}
mcset ru {Other hint} {Other hint}
mcset ru {Other hint 2} {Other hint 2}
mcset ru {Create Similar table} {Create Similar table}
mcset ru {There is already an index with name '%s'.
Please change the name of this table.} {There is already an index with name '%s'.
Please change the name of this table.}
mcset ru {There is already a trigger with name '%s'.
Please change the name of this table.} {There is already a trigger with name '%s'.
Please change the name of this table.}
mcset ru {There is already a view with name '%s'.
Please change the name of this table.} {There is already a view with name '%s'.
Please change the name of this table.}
mcset ru You\ cannot\ use\ all\ four\ SQL\ quoting\ characters\ (%s,\ %s,\ %s\ and\ %s)\nin\ one\ object\ name\ (which\ is:\ %s).\"\ \\ You\ cannot\ use\ all\ four\ SQL\ quoting\ characters\ (%s,\ %s,\ %s\ and\ %s)\nin\ one\ object\ name\ (which\ is:\ %s).\"\ \\
mcset ru \n\t\t\tSQLiteStudio\ provides\ some\ extra\ SQLite\ functions\ that\ you\ can\ use\ in\ SQL\ editor.\ These\ are:\n\t\t\ttcl()\ -\ which\ runs\ custom\ Tcl\ code\ in\ new,\ separated\ Tcl\ interpreter,\ and\ sqlfile()\ -\ which\n\t\t\texecutes\ SQL\ from\ given\ file\ in\ current\ database.<br>Examples:<br><br>\n\t\t\t<tab>SELECT\ tcl('return\ \[expr\ \{pow(5,5) \n\t\t\tSQLiteStudio\ provides\ some\ extra\ SQLite\ functions\ that\ you\ can\ use\ in\ SQL\ editor.\ These\ are:\n\t\t\ttcl()\ -\ which\ runs\ custom\ Tcl\ code\ in\ new,\ separated\ Tcl\ interpreter,\ and\ sqlfile()\ -\ which\n\t\t\texecutes\ SQL\ from\ given\ file\ in\ current\ database.<br>Examples:<br><br>\n\t\t\t<tab>SELECT\ tcl('return\ \[expr\ \{pow(5,5)
mcset ru {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the world (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		} {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the world (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		}
mcset ru {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view od table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		} {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view od table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		}
mcset ru {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Remember that you can always set NULL value mually using SQL query.
		} {
			Для вставки в ячейку значения NULL (а не просто пустого значения), вам необходимо либо нажать клавишу Backspace при выделенной ячейке, или выбрать "Установить NULL-значение" в контекстном меню табличного вида.<br>
			Это можно сделать и при множественном выделении ячеек.<br><br>
			Помните, что вы всегда можете вставить значение NULL, используя SQL-запрос.
		}
mcset ru {
			You place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		} {
			You place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		}
mcset ru {Rollback changes (%s)" "Escape} {Rollback changes (%s)" "Escape}
mcset ru {Edit table (%s)" "t} {Edit table (%s)" "t}
mcset ru {Export table data (%s)" "x} {Export table data (%s)" "x}
mcset ru {Rollback new row (%s)" "Escape} {Rollback new row (%s)" "Escape}
mcset ru {Edit index (%s)" "Return} {Edit index (%s)" "Return}
mcset ru {Edit trigger (%s)" "Return} {Edit trigger (%s)" "Return}
mcset ru {
			SQLiteStudio can emulate enforcing foreign keys using triggers. If this feature is enabled in configuration (it is by default)
			then defining foreign keys in the table editor dialog affects triggers in database. Foreign key triggers are prefixed with'fk_',
			so avoid using this prefix when creating custom triggers, because they can be destroyed by foreign key emulation (only if enabled).
		} {
			SQLiteStudio can emulate enforcing foreign keys using triggers. If this feature is enabled in configuration (it is by default)
			then defining foreign keys in the table editor dialog affects triggers in database. Foreign key triggers are prefixed with'fk_',
			so avoid using this prefix when creating custom triggers, because they can be destroyed by foreign key emulation (only if enabled).
		}
mcset ru {No action} {Действие не задано}
mcset ru Restrict {Запрет операции}
mcset ru Cascade {Каскадное действие}
mcset ru {Set Null} Null-значение
mcset ru {Set Default} {Значение по умолчанию}
mcset ru {Tcl editor font} {Редактор Tcl}
mcset ru {Use table constraints} {Ограничения таблицы}
mcset ru {Optional name:} Название:
mcset ru {Columns list} {Список столбцов}
mcset ru {Optional constraint name. Leave it empty to ommit.} {Необязательное название ограничения. Можно не заполнять это поле.}
mcset ru {ON CONFLICT algorithm.} {Алгоритм выражения ON CONFLICT.}
mcset ru {Condition to check.} {Условие для проверки.}
mcset ru {You have to specify table name.} {Задайте название таблицы.}
mcset ru {You have to add at least one column.} {Необходимо добавить хотя бы один столбец.}
mcset ru {You cannot create column with no name.} {Задайте название столбца.}
mcset ru {Incomplete Foreign Key configuration. Finish the configuration, or disable Foreign Key.} {Не закончена настройка внешнего ключа. Завершите настройку или отмените создание внешнего ключа.}
mcset ru {You have to fill check costraint condition.} {Задайте условие для проверки.}
mcset ru {Output format} {Выходной формат}
mcset ru Options {Дополнительная настройка}
mcset ru {First row in exported CSV file will contain list of columns.} {В первой строке CSV-файла будет список столбцов.}
mcset ru {Common separator is \",\" (comma), but sometimes others can be met.} {Обычно в качестве разделителя используется \",\" (запятая), но возможны и другие варианты.}
mcset ru {"CREATE TABLE" for exported data} {"CREATE TABLE" для экспортируемых данных}
mcset ru {SQLiteStudio will create a new table for exported rows in SQL.} {SQLiteStudio сгенерирует SQL-запрос на создание новой таблицы для экспортированных строк.}
mcset ru {First row will be header with names of columns, just like in results grid.} {Первая строка будет содержать названия столбцов, как в таблице результатов.}
mcset ru {First column will be will contain number row.} {В первом столбце будут номера строк.}
mcset ru {You have to enter table name if you want to create one.} {Для создания таблицы необходимо ввести ее название.}
mcset ru {Local columns} {Локальные столбцы}
mcset ru {Foreign columns} {Внешние столбцы}
mcset ru {On delete:} {При удалении:}
mcset ru {On update:} {При обновлении:}
mcset ru {On insert:} {При вставке:}
mcset ru {Precision chars length. Must be less then maximal length.} {Количество знаков в дробной части (должно быть меньше максимальной длины значения).}
mcset ru Constrain Ограничение
mcset ru {Named constrain} {Именованное ограничение}
mcset ru {Auto increment} Автоприращение
mcset ru {Auto increment property requires column to be Primary Key and INTEGER type.} {Использование автоприращения возможно только в том случае, если столбец содержит данные типа типа INTEGER и является первичным ключом.}
mcset ru {Collation type:} {Тип сравнения:}
mcset ru Reference Ссылка
mcset ru {Can't set precision without maximal value length.} {Для настройки точности должа быть задана максимальная длина значения.}
mcset ru {Maximal value length has to be greater than precision by at least 1.} {Максимальная длина значения должна быть больше, чем точность.}
mcset ru {You cannot use CHECK constraint without condition defined.} {Для использования ограничения CHECK должно быть задано условие проверки.}
mcset ru {You have to select foreign key table!} {Выберите таблицу внешнего ключа!}
mcset ru {You have to select foreign key column!} {Выберите столбец внешнего ключа!}
mcset ru {Column with name '%s' already exists.} {Столбец с названием '%s' уже существует.}
mcset ru {Table '%s' already contains data. In that case you cannot
add column with NOT NULL constraint and no DEFAULT value.
Please specify DEFAULT constraint.} {Таблица '%s' уже содержит данные. Для добавления
столбца с ограничением NOT NULL необходимо задать значение по умолчанию.}
mcset ru {You've changed name of column that is probably used in table CHECK constraint.
Be sure to update CHECK constraint condition too.} {Вы изменили название столбца, который, возможно, используется в ограничении CHECK для таблицы.
Необходимо также изменить условие ограничения CHECK.}
mcset ru {Choose existing database} {Выбрать существующую базу данных}
mcset ru {Foreign table} {Внешняя таблица}
mcset ru Results: Результаты:
mcset ru {No database chosen for Editor window.} {Не выбрана база данных окне Редактора.}
mcset ru {Default database for SQL executing} {База данных для выполнения SQL-запросов}
mcset ru {First row from data grid} {Первая строка таблицы}
mcset ru {Previous row from data grid} {Предыдущая строка таблицы}
mcset ru {Next row from data grid} {Следующая строка таблицы}
mcset ru {Last row from data grid} {Последняя строка таблицы}
mcset ru {Error while updating row:
%s} {Ошибка обновления строки:
%s}
mcset ru {Rollback new row} {Откатить добавление новой строки}
mcset ru {Delete row} {Удалить строку}
mcset ru {Are you sure you want to delete selected row?} {Вы действительно хотите удалить выбранную строку?}
mcset ru {Cannot paste:
%s} {Не удалось вставить:
%s}
mcset ru {SQL editor completition} {Автозавершение кода SQL}
mcset ru {Invokes SQL completition in editor window.} {Автозавершение кода SQL в окне редактора.}
mcset ru {Show SQLite system tables in databases tree} {Показывать системные таблицы SQLite}
mcset ru {SQL formatter plugin} {Форматирование SQL}
mcset ru {Ask if clipboard contents should be cutted} {Спрашивать, надо ли вырезать содержимое буфера обмена}
mcset ru {If enabled then SQLite system tables (matching sqlite_*)
are displayed in databases tree.} {Управление видимостью системных таблиц SQLite
(названия вида sqlite_*) в дереве базы данных.}
mcset ru {Results stored as %s in file: %s} {Результаты сохранены в %s-файле: %s}
mcset ru {Cannot open file %s:
%s} {Не удалось открыть файл %s:
%s}
mcset ru {Error while exporting:
%s} {Ошибка экспорта:
%s}
