# SQLiteStudio 'zh_cn' localization file

# Unchanged translations

### File: ../src/win_assoc.tcl
mcset zh_cn {File associations} {File associations}

### File: ../src/win_assoc.tcl
mcset zh_cn {Following file extensions could not be associated to the current SQLiteStudio version:
%s} {Following file extensions could not be associated to the current SQLiteStudio version:
%s}

### File: ../src/win_assoc.tcl
mcset zh_cn {Click the link below to find out what is possible reason and solutions.} {Click the link below to find out what is possible reason and solutions.}

### File: ../src/cfg_win.tcl
mcset zh_cn Ok 好

### File: ../src/cfg_win.tcl
mcset zh_cn Apply 应用

### File: ../src/cfg_win.tcl
mcset zh_cn Cancel 取消

### File: ../src/cfg_win.tcl
mcset zh_cn Theme 样式

### File: ../src/cfg_win.tcl
mcset zh_cn {Select theme to use:} 选中样式:

### File: ../src/cfg_win.tcl
mcset zh_cn {Theme version:} 样式版本:

### File: ../src/cfg_win.tcl
mcset zh_cn Shortcuts 捷径

### File: ../src/cfg_win.tcl
mcset zh_cn {Global shortcuts} 全局捷径

### File: ../src/cfg_win.tcl
mcset zh_cn {Open SQL editor} {打开 SQL 编辑器}

### File: ../src/cfg_win.tcl
mcset zh_cn {Opens SQL editor window.} {打开 SQL 编辑器窗口.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Close selected task} 关闭选中的任务

### File: ../src/cfg_win.tcl
mcset zh_cn {Closes active MDI window.} {关闭活动的 MDI 窗口.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Restore last closed task} {Restore last closed task}

### File: ../src/cfg_win.tcl
mcset zh_cn {Restores last closed MDI window.} {Restores last closed MDI window.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Open settings} 打开设置

### File: ../src/cfg_win.tcl
mcset zh_cn {Opens SQLiteStudio settings window.} {打开 SQLiteStudio 设置窗口.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Next task} 下一个任务

### File: ../src/cfg_win.tcl
mcset zh_cn {Switches task (window) to next, placed on the right from active task on taskbar.} {Switches task (window) to next, placed on the right from active task on taskbar.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Next task (alternative)} {下一个的任务 (可选)}

### File: ../src/cfg_win.tcl
mcset zh_cn {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Switches task (window) to next, placed on the right from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Previous task} 上一个任务

### File: ../src/cfg_win.tcl
mcset zh_cn {Switches task (window) to previous, placed on the left from active task on taskbar.} {Switches task (window) to previous, placed on the left from active task on taskbar.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Previous task (alternative)} {上一个的任务 (可选)}

### File: ../src/cfg_win.tcl
mcset zh_cn {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.} {Switches task (window) to previous, placed on the left from active task on taskbar.
This is alternative shortcut. Does the same thing as one above.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Editor and table window shortcuts} 编辑器和表视窗捷径

### File: ../src/cfg_win.tcl
mcset zh_cn {SQL editor completion} {SQL 编辑器完毕}

### File: ../src/cfg_win.tcl
mcset zh_cn {Invokes SQL completion in editor window.} {在编辑窗口中调用 SQL 完毕.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Execute SQL query} {执行 SQL 查询}

### File: ../src/cfg_win.tcl
mcset zh_cn {Executes SQL query typed in editor.} {执行编辑中的 SQL 查询.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Explain SQL query} {解释 SQL 查询}

### File: ../src/cfg_win.tcl
mcset zh_cn {Calls EXPLAIN on SQL query typed in editor.} {执行编辑中的 SQL 查询 EXPLAIN 功能.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Format SQL code} {格式化 SQL 代码}

### File: ../src/cfg_win.tcl
mcset zh_cn {Formats SQL code typed in editor.} {格式化编辑器中的 SQL 代码.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Load SQL from file} {从文件加载 SQL}

### File: ../src/cfg_win.tcl
mcset zh_cn {Loads SQL from file to the editor.} {从文件加载 SQL 到编辑器.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Save SQL to file} {保存 SQL 到文件}

### File: ../src/cfg_win.tcl
mcset zh_cn {Saves contents of the editor into a file.} 保存编辑器中的内容到文件.

### File: ../src/cfg_win.tcl
mcset zh_cn {Execute SQL from file} {从文件执行 SQL }

### File: ../src/cfg_win.tcl
mcset zh_cn {Executes SQL directly from file, without loading it to the editor.} {Executes SQL directly from file, without loading it to the editor.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Next tab} {后一个 tab}

### File: ../src/cfg_win.tcl
mcset zh_cn {Switches to next tab of editor window (result or history).} {Switches to next tab of editor window (result or history).}

### File: ../src/cfg_win.tcl
mcset zh_cn {Previous tab} {前一个 tab}

### File: ../src/cfg_win.tcl
mcset zh_cn {Switches to previous tab of editor window (query or result).} {Switches to previous tab of editor window (query or result).}

### File: ../src/cfg_win.tcl
mcset zh_cn {Next subtab} {后一个 subtab}

### File: ../src/cfg_win.tcl
mcset zh_cn {Switches to next subtab (form view in results tab).} {Switches to next subtab (form view in results tab).}

### File: ../src/cfg_win.tcl
mcset zh_cn {Previous subtab} {前一个 subtab}

### File: ../src/cfg_win.tcl
mcset zh_cn {Switches to previous subtab (grid view in results tab).} {Switches to previous subtab (grid view in results tab).}

### File: ../src/cfg_win.tcl
mcset zh_cn Refresh 刷新

### File: ../src/cfg_win.tcl
mcset zh_cn {Re-executes SQL query so results data is refreshed.} {Re-executes SQL query so results data is refreshed.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Delete selected row} 删除选中的一行

### File: ../src/cfg_win.tcl
mcset zh_cn {Deletes selected row.} 删除选中的行.

### File: ../src/cfg_win.tcl
mcset zh_cn {Add new row} 添加新行

### File: ../src/cfg_win.tcl
mcset zh_cn {Adds new empty row without commiting it.} 添加新的空行，并且不执行它.

### File: ../src/cfg_win.tcl
mcset zh_cn {Erase cells data} {Erase cells data}

### File: ../src/cfg_win.tcl
mcset zh_cn {Erases data of selected cells.} {Erases data of selected cells.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Next editor database in list} 打开列表中下一个数据库的编辑器

### File: ../src/cfg_win.tcl
mcset zh_cn {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)} {Switches database to next in editor context databases list
(it's drop-down list on top of the editor window)}

### File: ../src/cfg_win.tcl
mcset zh_cn {Previous editor database in list} 打开列表中上一个数据库的编辑器

### File: ../src/cfg_win.tcl
mcset zh_cn {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)} {Switches database to previous in editor context databases list
(it's drop-down list on top of the editor window)}

### File: ../src/cfg_win.tcl
mcset zh_cn {Commit edition in Form View} 在表单视图中执行编辑

### File: ../src/cfg_win.tcl
mcset zh_cn {Commits edition in Form View of query results or table data preview.} {Commits edition in Form View of query results or table data preview.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Rollback edition in Form View} 在表单视图中回滚编辑

### File: ../src/cfg_win.tcl
mcset zh_cn {Rolls back edition in Form View of query results or table data preview.} {Rolls back edition in Form View of query results or table data preview.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Jump to first row in Form View} 表单视图中跳至第一行

### File: ../src/cfg_win.tcl
mcset zh_cn {Jumps to first row of query results grid
or table data preview grid in Form View.} {Jumps to first row of query results grid
or table data preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Go to previous row in Form View} 表单视图中跳至前一行

### File: ../src/cfg_win.tcl
mcset zh_cn {Goes to previous row of query results grid
or table data preview grid row in Form View.} {Goes to previous row of query results grid
or table data preview grid row in Form View.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Go to next row in Form View} 表单视图中跳至后一行

### File: ../src/cfg_win.tcl
mcset zh_cn {Goes to next row of query results grid
or table data preview grid row in Form View.} {Goes to next row of query results grid
or table data preview grid row in Form View.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Jump to last row in Form View} 表单视图中跳至最后一行

### File: ../src/cfg_win.tcl
mcset zh_cn {Jumps to last row of query results grid
or table data preview grid in Form View.} {Jumps to last row of query results grid
or table data preview grid in Form View.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Switch NULL value in form edit field} {Switch NULL value in form edit field}

### File: ../src/cfg_win.tcl
mcset zh_cn {Sets or unsets NULL value in currently selected
column in form view data edit mode.} {Sets or unsets NULL value in currently selected
column in form view data edit mode.}

### File: ../src/cfg_win.tcl
mcset zh_cn Plugins 插件

### File: ../src/cfg_win.tcl
mcset zh_cn {SQL formatter plugins} {SQL 格式插件}

### File: ../src/cfg_win.tcl
mcset zh_cn {Use following SQL formatter plugin:} {使用如下 SQL 格式插件:}

### File: ../src/cfg_win.tcl
mcset zh_cn {Configure formatter plugin} 配置格式插件

### File: ../src/cfg_win.tcl
mcset zh_cn Configure 配置

### File: ../src/cfg_win.tcl
mcset zh_cn {Populating plugins} {Populating 插件}

### File: ../src/cfg_win.tcl
mcset zh_cn {Default table populating plugin:} 缺省的表填充插件:

### File: ../src/cfg_win.tcl
mcset zh_cn Miscellaneous 其他功能

### File: ../src/cfg_win.tcl
mcset zh_cn {Restore session after next start} {Restore session after next start}

### File: ../src/cfg_win.tcl
mcset zh_cn {All windows and their contents (such as SQL code)
will be restored while next application startup.} {All windows and their contents (such as SQL code)
will be restored while next application startup.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Show line numbers in SQL editor} {在 SQL 编辑器中显示行数}

### File: ../src/cfg_win.tcl
mcset zh_cn {All SQL editor windows will contain line numbers on the left side of window.} {All SQL editor windows will contain line numbers on the left side of window.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Underline syntax errors in SQL editor} {Underline syntax errors in SQL editor}

### File: ../src/cfg_win.tcl
mcset zh_cn {Makes errors to be marked with underline.
You can also define foreground and background color for errors.} {Makes errors to be marked with underline.
You can also define foreground and background color for errors.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Show SQLite system tables and indexes in databases tree} {Show SQLite system tables and indexes in databases tree}

### File: ../src/cfg_win.tcl
mcset zh_cn {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.} {If enabled then SQLite system tables (matching 'sqlite_*')
and indexes (matching '(*autoindex*)') are displayed in databases tree.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Open items with single mouse click in databases tree} {Open items with single mouse click in databases tree}

### File: ../src/cfg_win.tcl
mcset zh_cn {Items in database tree are open by double click by default.
This option switches it to single click.} {Items in database tree are open by double click by default.
This option switches it to single click.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Show ROWID as default instead of row order number in table data view} {Show ROWID as default instead of row order number in table data view}

### File: ../src/cfg_win.tcl
mcset zh_cn {This option affects first column from the left on the data tab of the table window.} {This option affects first column from the left on the data tab of the table window.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Do not show 'did you know that...' dialog at startup.} {程序启动时不显示 '你知道吗...' 对话框.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Uncheck this option to show the dialog.} {Uncheck this option to show the dialog.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Check for updates at startup.} 启动时检查更新.

### File: ../src/cfg_win.tcl
mcset zh_cn {If enabled, application will will check
for new version available at startup.} {If enabled, application will will check
for new version available at startup.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Sort custom SQL functions list by name} {Sort custom SQL functions list by name}

### File: ../src/cfg_win.tcl
mcset zh_cn {This list is placed in Custom SQL funcions dialog.} {This list is placed in Custom SQL funcions dialog.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Select all contents when editing the table cell} {Select all contents when editing the table cell}

### File: ../src/cfg_win.tcl
mcset zh_cn {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.} {If this is enabled, then every time you edit the table cell
the contents of that cell will be selected by default.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Ask if clipboard contents should be cut} {Ask if clipboard contents should be cut}

### File: ../src/cfg_win.tcl
mcset zh_cn {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.} {If checked then application will ask user if he wants
to cut off clipboard contents while pasting,
in case when they don't fit into the grid.
If it's not checked, then application will cut
contents without asking.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Rows per page in Table Window and Editor Results:} {Rows per page in Table Window and Editor Results:}

### File: ../src/cfg_win.tcl
mcset zh_cn {More results per page causes slower loading of single data page. Value 1000 should be right.} {More results per page causes slower loading of single data page. Value 1000 should be right.}

### File: ../src/cfg_win.tcl
mcset zh_cn {History entries limit:} {History entries limit:}

### File: ../src/cfg_win.tcl
mcset zh_cn {Number of rows to remember in SQL editor history.} {Number of rows to remember in SQL editor history.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Insertion cursor blinking period (milliseconds):} {Insertion cursor blinking period (milliseconds):}

### File: ../src/cfg_win.tcl
mcset zh_cn {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.} {Number of milliseconds that it takes to blink insertion cursor in SQL editor. Set to 0 to disable blinking.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Web browser:} {Web browser:}

### File: ../src/cfg_win.tcl
mcset zh_cn {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.} {You can type your own webbrowser command here. It has to be in PATH variable.
Address to open will be simply passed as an argument to this command.}

### File: ../src/cfg_win.tcl
mcset zh_cn Language: 语言:

### File: ../src/cfg_win.tcl
mcset zh_cn {Tab in table window on open:} 表视窗中打开的Tab:

### File: ../src/cfg_win.tcl
mcset zh_cn {Table structure} 表结构

### File: ../src/cfg_win.tcl
mcset zh_cn {Table data} 表数据

### File: ../src/cfg_win.tcl
mcset zh_cn {Select which tab should be opened for start in table window,
when you just opened that window.} {Select which tab should be opened for start in table window,
when you just opened that window.}

### File: ../src/cfg_win.tcl
mcset zh_cn {View default display mode:} {View default display mode:}

### File: ../src/cfg_win.tcl
mcset zh_cn {Edition dialog} {Edition dialog}

### File: ../src/cfg_win.tcl
mcset zh_cn {Data view} {Data view}

### File: ../src/cfg_win.tcl
mcset zh_cn {Defines what is displayed by default when user opens a view.} {Defines what is displayed by default when user opens a view.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Editor window results layout} 编辑器视窗结果的布局

### File: ../src/cfg_win.tcl
mcset zh_cn {Show results in separated tab} 在分隔的tab中显示结果

### File: ../src/cfg_win.tcl
mcset zh_cn {Show results in frame below query} 在查询下面的框架中显示结果

### File: ../src/cfg_win.tcl
mcset zh_cn {Database tree display mode} {Database tree display mode}

### File: ../src/cfg_win.tcl
mcset zh_cn {Show indexes and triggers linked under referenced table.} {Show indexes and triggers linked under referenced table.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Show indexes and triggers in their own groups.} {Show indexes and triggers in their own groups.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Show column names linked under the table.} {Show column names linked under the table.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Plain text results} 纯文本结果

### File: ../src/cfg_win.tcl
mcset zh_cn {Display NULL values as:} {显示 NULL 值如:}

### File: ../src/cfg_win.tcl
mcset zh_cn {Maximum column width:} 最大列宽:

### File: ../src/cfg_win.tcl
mcset zh_cn {Values longer than specified here will be cut in plain text results.} {Values longer than specified here will be cut in plain text results.}

### File: ../src/cfg_win.tcl
mcset zh_cn Colors 颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Global colors} {Global 颜色}

### File: ../src/cfg_win.tcl
mcset zh_cn {MDI windows title bar background color} {MDI 窗口标题栏背景色}

### File: ../src/cfg_win.tcl
mcset zh_cn {MDI windows title bar foreground color} {MDI 窗口标题栏前景色}

### File: ../src/cfg_win.tcl
mcset zh_cn {MDI windows title bar button background color} {MDI 窗口标题栏按钮背景色}

### File: ../src/cfg_win.tcl
mcset zh_cn {MDI windows title bar active button background color} {MDI 窗口标题栏按钮前景色}

### File: ../src/cfg_win.tcl
mcset zh_cn {SQL Editor} {SQL 编辑器}

### File: ../src/cfg_win.tcl
mcset zh_cn {Editor standard font color} 编辑标准字体颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Editor background} 编辑背景

### File: ../src/cfg_win.tcl
mcset zh_cn {Selected foreground color} 选中前景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Selected background color} 选中背景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Disabled background color} 禁止背景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Tables color} 表颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Brackets color} 括弧颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Square brackets color} 方括弧颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Keywords color} 关键字颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Variables color} 变量颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Strings color} 字符串颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Comments color} 注释颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Matched brackets foreground color} 匹配括弧前景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Matched brackets background color} 匹配括弧背景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Syntax error color} 语法错误颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Tcl editor} {Tcl 编辑器}

### File: ../src/cfg_win.tcl
mcset zh_cn {Options color} 选项颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Quoted character color} 引用的文字颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Trees colors} 树结构颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Tree background} 树结构背景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Tree standard font color} 树结构标准字体颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Tree selected background color} 树结构选中内容背景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Tree selected foreground color} 树结构选中内容前景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Color for number of objects in tree branch} 树结构分支的对象数量颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Grids colors} 表格颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Grid background} 表格背景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Grid standard font color} 表格标准字体颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Grid selected background color} 表格选中内容背景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Grid selected foreground color} 表格选中内容前景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Grid base column background color} 表格基列背景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Foreground color for cells with NULL value} NULL值单元的前景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Status fields colors} 状态区域颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Background color} 背景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Foreground color} 前景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Error foreground color} 错误的前景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Information foreground color} 信息的前景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Information (second kind) foreground color} {信息 (其他类型) 前景色}

### File: ../src/cfg_win.tcl
mcset zh_cn {Miscellaneous colors} 多种功能的颜色

### File: ../src/cfg_win.tcl
mcset zh_cn {Context hints background color} 上下文提示背景色

### File: ../src/cfg_win.tcl
mcset zh_cn {Context hints foreground color} 上下文提示前景色

### File: ../src/cfg_win.tcl
mcset zh_cn Fonts 字体

### File: ../src/cfg_win.tcl
mcset zh_cn {SQL editor font} {SQL 编辑器字体}

### File: ../src/cfg_win.tcl
mcset zh_cn {Status fields font} 状态区域字体

### File: ../src/cfg_win.tcl
mcset zh_cn {Grid font} 表格字体

### File: ../src/cfg_win.tcl
mcset zh_cn {Tree font} 树字体

### File: ../src/cfg_win.tcl
mcset zh_cn {Tree additional labels font} 树结构的其他标签字体

### File: ../src/cfg_win.tcl
mcset zh_cn {Context hints font} 上下文提示字体

### File: ../src/cfg_win.tcl
mcset zh_cn {Changed language needs application to be restarted.} 改变语言需重启程序.

### File: ../src/cfg_win.tcl
mcset zh_cn {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.} {Problem occured while tried to open settings file: %s. Seems like %s directory was deleted or renamed. The SQLiteStudio settings won't be saved.}

### File: ../src/cfg_win.tcl
mcset zh_cn {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.} {Could not save configuration file. Some settings might get lost. Please check if file '%s' is writable.}

### File: ../src/cfg_win.tcl
mcset zh_cn {SQL formatter options} {SQL 格式器选项}

### File: ../src/db/db_file_types.tcl
mcset zh_cn {All SQLite Databases} {所有 SQLite 数据库}

### File: ../src/db/db_file_types.tcl
mcset zh_cn {SQLite 3 Databases} {SQLite 3 数据库}

### File: ../src/db/db_file_types.tcl
mcset zh_cn {SQLite 2 Databases} {SQLite 2 数据库}

### File: ../src/db/db_file_types.tcl
mcset zh_cn {All files} 所有文件

### File: ../src/db/query_executor.tcl
mcset zh_cn {Query couldn't be parsed correctly by internal SQLiteStudio parser, so it was passed directly to SQLite, without any substitution or other modification.} {查询不能被内部SQLiteStudio解释器正确解释, 因此它被直接传给SQLite, 没有做任何替换或修改.}

### File: ../src/db/query_executor.tcl
mcset zh_cn {Invalid database name: %s} {不合适的数据库名: %s}

### File: ../src/db/query_executor.tcl
mcset zh_cn {Imbalanced 'BEGIN' ocurrence in query.} {Imbalanced 'BEGIN' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset zh_cn {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.} {Results are not editable, because compound SELECT was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset zh_cn {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.} {Results are not editable, because DISTINCT keyword was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset zh_cn {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.} {Results are not editable, because GROUP BY was used. For more details see paragraph %s of User Manual.}

### File: ../src/db/query_executor.tcl
mcset zh_cn {Cannot use more than one 'BEGIN'.} {Cannot use more than one 'BEGIN'.}

### File: ../src/db/query_executor.tcl
mcset zh_cn {Imbalanced 'COMMIT' ocurrence in query.} {Imbalanced 'COMMIT' ocurrence in query.}

### File: ../src/db/query_executor.tcl
mcset zh_cn {Imbalanced 'ROLLBACK' ocurrence in query.} {Imbalanced 'ROLLBACK' ocurrence in query.}

### File: ../src/db/sqlite2.tcl
mcset zh_cn {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite2)} {当调用数据库的 VACUUM 发生错误:
%s
(这是直接来自SQLite2的提示信息)}

### File: ../src/db/db.tcl
mcset zh_cn {An internal logic error in SQLite} 一个SQLite的内部逻辑错误

### File: ../src/db/db.tcl
mcset zh_cn {Access permission denied} 如口许可被禁止

### File: ../src/db/db.tcl
mcset zh_cn {Cannot proceed operation because database is busy.
Perhaps some other application is accessing it.} {数据库正忙不能执行操作.
可能是其他应用正在访问它.}

### File: ../src/db/db.tcl
mcset zh_cn {Cannot proceed operation because database object is locked.
Perhaps some other application is accessing it.} {数据库对象被锁不能执行操作.
可能是其他应用正在访问它.}

### File: ../src/db/db.tcl
mcset zh_cn {A malloc() failed} {一个 malloc() 失败}

### File: ../src/db/db.tcl
mcset zh_cn {Attempt to write a readonly database} 试图向只读数据库写入

### File: ../src/db/db.tcl
mcset zh_cn {Disk I/O error occurred} {发生磁盘 I/O 发生}

### File: ../src/db/db.tcl
mcset zh_cn {The database disk image is malformed} 数据库的磁盘映像错误

### File: ../src/db/db.tcl
mcset zh_cn {Database is full} 数据库满了

### File: ../src/db/db.tcl
mcset zh_cn {Unable to open the database file} {Unable to open the database file}

### File: ../src/db/db.tcl
mcset zh_cn {Database lock protocol error} 数据库锁协议错误

### File: ../src/db/db.tcl
mcset zh_cn {Database is empty} 数据库空了

### File: ../src/db/db.tcl
mcset zh_cn {The database schema changed} 数据库结构变化

### File: ../src/db/db.tcl
mcset zh_cn {String or BLOB exceeds size limit} {String 或 BLOB 操作大小限制}

### File: ../src/db/db.tcl
mcset zh_cn {Library used incorrectly} 库使用不正确

### File: ../src/db/db.tcl
mcset zh_cn {Uses OS features not supported on host} 主机上使用操作系统特征不被支持

### File: ../src/db/db.tcl
mcset zh_cn {Authorization denied} 授权被禁止

### File: ../src/db/db.tcl
mcset zh_cn {Auxiliary database format error} 辅助的数据库格式错误

### File: ../src/db/db.tcl
mcset zh_cn {2nd parameter to sqlite3_bind out of range} sqlite3_bind的第二个参数越界

### File: ../src/db/db.tcl
mcset zh_cn {File opened that is not a database file} 打开的文件不是数据库文件

### File: ../src/db/db.tcl
mcset zh_cn {Error while opening %s database:
%s} {打开数据库 %s 发生错误:
%s}

### File: ../src/db/db.tcl
mcset zh_cn {Not enough parameters passed to function '%s'.} {传入函数的参数不够 '%s'.}

### File: ../src/db/db.tcl
mcset zh_cn {Cannot read file: %s} {不能读文件: %s}

### File: ../src/db/db.tcl
mcset zh_cn {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.} {Could not attach database %s. It doesn't exists, has incompatible version,or file format is invalid.}

### File: ../src/db/db.tcl
mcset zh_cn {Could not attach database %s. Error message from SQLite:
%s} {Could not attach database %s. Error message from SQLite:
%s}

### File: ../src/db/db.tcl
mcset zh_cn {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.} {Could not get attach SQL for database %s. It doesn't exists, has incompatible version, or file format is invalid.}

### File: ../src/db/sqlite3.tcl
mcset zh_cn {An error occured while call to VACUUM on database:
%s
(this is message directly from SQLite3)} {当调用数据库的 VACUUM 发生错误:
%s
(这是直接来自SQLite3的提示信息)}

### File: ../src/completion_routines.tcl
mcset zh_cn {Problem with attaching database:
%s} {连接数据库错误:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Error from importing plugin:
%s} {Error from importing plugin:
%s}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is less than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?} {Number of columns in target table '%s' is greater than number of columns in data to import. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Error creating table '%s':
%s

Importing aborted.} {Error creating table '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Error trying to import data to '%s':
%s

Importing aborted.} {Error trying to import data to '%s':
%s

Importing aborted.}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn Importing... Importing...

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Importing to table '%s'.} {Importing to table '%s'.}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?} {Importing plugin raised error when asked for data row number %s. Error details:
%s.

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?} {Number of columns in data row number %s is different than number of columns declared by importing plugin. What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Problem occured while importing row number %s:
%s

What would you like to do?} {Problem occured while importing row number %s:
%s

What would you like to do?}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Importing finished.} {Importing finished.}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Import problem} {Import problem}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Skip this data row} {Skip this data row}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Keep data rows imported so far (%s) and abort} {Keep data rows imported so far (%s) and abort}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Rollback data rows imported so far and abort} {Rollback data rows imported so far and abort}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn {Ignore it and proceed} {Ignore it and proceed}

### File: ../src/plugins/import_plugin.tcl
mcset zh_cn Abort 中断

### File: ../src/plugins/sql_formatting/enterprise/format_s.tcl
mcset zh_cn name 名字

### File: ../src/plugins/sql_formatting/basic.tcl
mcset zh_cn {Reduce group of whitespaces into one whitespace.} {Reduce group of whitespaces into one whitespace.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset zh_cn {Uppercase keywords.} {Uppercase keywords.}

### File: ../src/plugins/sql_formatting/basic.tcl
mcset zh_cn {Separate ")" and after contents with single whitespace.} {Separate ")" and after contents with single whitespace.}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {SQLite3 only} 只有SQLite3

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn Indentation 缩排

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {New lines} 新行

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {White spaces} 空格

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn Names 名字

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn Comments 注释

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Tab size:} Tab大小:

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Line up keywords in multi-line queries} {Line up keywords in multi-line queries}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Ident contents of parenthesis block} {Ident contents of parenthesis block}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Ident parenthesis block in new line} {Ident parenthesis block in new line}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Before opening parenthesis in column definitions} {Before opening parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After opening parenthesis in column definitions} {After opening parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Before closinging parenthesis in column definitions} {Before closinging parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After closinging parenthesis in column definitions} {After closinging parenthesis in column definitions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Before opening parenthesis in expressions} {Before opening parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After opening parenthesis in expressions} {After opening parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Before closinging parenthesis in expressions} {Before closinging parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After closinging parenthesis in expressions} {After closinging parenthesis in expressions}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After comma} {After comma}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After comma in function arguments list} {After comma in function arguments list}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After logical block of query} {After logical block of query}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After semicolon} {After semicolon}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Never before semicolon} {Never before semicolon}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Before comma in lists} {Before comma in lists}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After comma in lists} {After comma in lists}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Before opening parenthesis} {Before opening parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After opening parenthesis} {After opening parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Before closing parenthesis} {Before closing parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After closing parenthesis} {After closing parenthesis}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Before dot operator (in path to database object)} {Before dot operator (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After dot operator (in path to database object)} {After dot operator (in path to database object)}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Before mathematical operator} 之前的数学运算符

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {After mathematical operator} 之后的数学运算符

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Uppercase keywords} 大写关键字

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Uppercase datatype names} 大写数据类型名字

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Always use name wrapping} 总是使用名字包装

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Preferred name wrapper} 首选的名字包装

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Expand one line comments (/* ... */) to multiline} {Expand one line comments (/* ... */) to multiline}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Indent multi line comments} {Indent multi line comments}

### File: ../src/plugins/sql_formatting/enterprise.tcl
mcset zh_cn {Use "*" character for each line} {Use "*" character for each line}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {, (comma)} {, (逗号)}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {; (semicolon)} {; (分号)}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {\t (tab)} {\t (tab)}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {  (white-space)} {  (空格)}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn Custom 客户化

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Input file} {Input file}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn Browse 浏览

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Show options} {Show options}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Column names} {Column names}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Treat first row as column names} {Treat first row as column names}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.} {If enabled, then first row of CSV file will be interpreted as column names.
They are ignored if data is imported to existing table.}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Columns separator:} 列分割符:

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.} {Character used to separate each column data
from each other. Separator can be part of column value as far,
as the value is enclosed in quotation marks.}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {NULL handling} {NULL handling}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Treat following values as NULL:} {Treat following values as NULL:}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn Workarounds Workarounds

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Expect Microsoft format of CSV} {Expect Microsoft format of CSV}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.} {Microsoft products uses slightly different format of CSV files.
If you're importing an output CSV from such application, use this option.}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn Encoding Encoding

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Convert from encoding:} {Convert from encoding:}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Input file cannot be empty.} {Input file cannot be empty.}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Input file is not readable.} {Input file is not readable.}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {CSV separator cannot be empty.} {CSV separator cannot be empty.}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {CSV files} {CSV files}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {Text files} {Text files}

### File: ../src/plugins/import/csv.tcl
mcset zh_cn {File to import from} {File to import from}

### File: ../src/plugins/import/dbf.tcl
mcset zh_cn Auto-detect Auto-detect

### File: ../src/plugins/import/dbf.tcl
mcset zh_cn {dBase files} {dBase files}

### File: ../src/plugins/import/regexp.tcl
mcset zh_cn {Regular expression} {Regular expression}

### File: ../src/plugins/import/regexp.tcl
mcset zh_cn {Visual editor} {Visual editor}

### File: ../src/plugins/import/regexp.tcl
mcset zh_cn {Use Regular Expression Groups to identify columns.} {Use Regular Expression Groups to identify columns.}

### File: ../src/plugins/import/regexp.tcl
mcset zh_cn {Case insensitive} {Case insensitive}

### File: ../src/plugins/import/regexp.tcl
mcset zh_cn Help 帮助

### File: ../src/plugins/import/regexp.tcl
mcset zh_cn {RegExp error:
%s} {RegExp error:
%s}

### File: ../src/plugins/export/xls.tcl
mcset zh_cn {Column names as first row} {Column names as first row}

### File: ../src/plugins/export/xls.tcl
mcset zh_cn {If enabled, then first row of exported document will be a list of column names.} {If enabled, then first row of exported document will be a list of column names.}

### File: ../src/plugins/export/xls.tcl
mcset zh_cn Encoding: 编码:

### File: ../src/plugins/export/plain.tcl
mcset zh_cn {Export NULL values as:} {导出 NULL 值如:}

### File: ../src/plugins/export/plain.tcl
mcset zh_cn {Fixed column width:} {Fixed column width:}

### File: ../src/plugins/export/plain.tcl
mcset zh_cn {Database: %s (%s, %s)} {Database: %s (%s, %s)}

### File: ../src/plugins/export/plain.tcl
mcset zh_cn {Table: %s} {表: %s}

### File: ../src/plugins/export/plain.tcl
mcset zh_cn {Index: %s} {索引: %s}

### File: ../src/plugins/export/plain.tcl
mcset zh_cn {Trigger: %s} {触发器: %s}

### File: ../src/plugins/export/plain.tcl
mcset zh_cn {View: %s} {视图: %s}

### File: ../src/plugins/export/csv.tcl
mcset zh_cn {If enabled, then first row of exported CSV will be a list of column names.} {If enabled, then first row of exported CSV will be a list of column names.}

### File: ../src/plugins/export/csv.tcl
mcset zh_cn {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.} {Character used to separate each column data
from each other. If separator occures in any data column,
then the value is enclosed in quote characters.
Any quote character in value is replaced with two quote characters.}

### File: ../src/plugins/export/json.tcl
mcset zh_cn {Indented lines} {Indented lines}

### File: ../src/plugins/export/json.tcl
mcset zh_cn {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.} {SQLiteStudio will break the generated JSON code across lines
and indent it according to its inner structure,
with each key of an object on a separate line.}

### File: ../src/plugins/export/json.tcl
mcset zh_cn {Align lines} {Align lines}

### File: ../src/plugins/export/json.tcl
mcset zh_cn {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.} {SQLiteStudio ensures that the values for the keys
in an object are vertically aligned with each other,
for a nice table effect.}

### File: ../src/plugins/export/json.tcl
mcset zh_cn {Each row as object} {Each row as object}

### File: ../src/plugins/export/json.tcl
mcset zh_cn {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.} {If disabled, then each row is exported as JSON array.
If enabled, then each row is exported as JSON object
with column names as object keys.}

### File: ../src/plugins/export/xml.tcl
mcset zh_cn {No extra white-spaces or new lines} 无额外空格或新行

### File: ../src/plugins/export/xml.tcl
mcset zh_cn {XML tags will be places char-by-char, without any extra white-spaces.} {XML tags will be places char-by-char, without any extra white-spaces.}

### File: ../src/plugins/export/xml.tcl
mcset zh_cn {Format output to be human readable} {Format output to be human readable}

### File: ../src/plugins/export/xml.tcl
mcset zh_cn {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.} {Each tag will be placed in new line and whole document
will be justified to be more readable in text editor.}

### File: ../src/plugins/export/xml.tcl
mcset zh_cn {Generate XSD file} {产生 XSD 文件}

### File: ../src/plugins/export/xml.tcl
mcset zh_cn {Generates XML Schema Definition file using
export file name and extension *.xsd.} {Generates XML Schema Definition file using
export file name and extension *.xsd.}

### File: ../src/plugins/export/xml.tcl
mcset zh_cn {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s} {There were problems while creating XSD file, but all data was successfly exported to XML file anyway. Problems details:
%s}

### File: ../src/plugins/export/html.tcl
mcset zh_cn {First row of exported data will be header
with names of columns, just like in results grid.} {First row of exported data will be header
with names of columns, just like in results grid.}

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Row numbers as first column} {Row numbers as first column}

### File: ../src/plugins/export/html.tcl
mcset zh_cn {First column of exported data
will contain row order number.} {First column of exported data
will contain row order number.}

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Full column names} 完整的列名

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Column names in header will be prepended with "table_name." prefix.} {Column names in header will be prepended with "table_name." prefix.}

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Show types} 显示类型

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Column headers will contain data types.} 列头包括数据类型.

### File: ../src/plugins/export/html.tcl
mcset zh_cn {no type} 无类型

### File: ../src/plugins/export/html.tcl
mcset zh_cn {For table:} 对于表:

### File: ../src/plugins/export/html.tcl
mcset zh_cn Unique: 唯一:

### File: ../src/plugins/export/html.tcl
mcset zh_cn Yes 是

### File: ../src/plugins/export/html.tcl
mcset zh_cn No 否

### File: ../src/plugins/export/html.tcl
mcset zh_cn Column 列

### File: ../src/plugins/export/html.tcl
mcset zh_cn Collating 比较

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Sort order} 排序次序

### File: ../src/plugins/export/html.tcl
mcset zh_cn Activated: 活动的:

### File: ../src/plugins/export/html.tcl
mcset zh_cn Action: 行动:

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Activate condition:} 激活条件:

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Code executed:} 执行的代码:

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Exported database: %s} {导出的数据库: %s}

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Generated on %s with %s} {在 %s 上产生，使用 %s}

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Exported table: %s} {导出表: %s}

### File: ../src/plugins/export/html.tcl
mcset zh_cn {Results of SQL query} {SQL 查询结果}

### File: ../src/plugins/export/dbf.tcl
mcset zh_cn {Cannot overwrite file '%s'.} {Cannot overwrite file '%s'.}

### File: ../src/plugins/export/sql.tcl
mcset zh_cn {Name of table for exported data:} 导出数据的表名:

### File: ../src/plugins/export/sql.tcl
mcset zh_cn {Include "CREATE TABLE" statement at the begining.} {Include "CREATE TABLE" statement at the begining.}

### File: ../src/plugins/export/sql.tcl
mcset zh_cn {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.} {Query results exported to SQL INSERTs have to be defined
for some table. It's the name of this table.}

### File: ../src/plugins/export/sql.tcl
mcset zh_cn {Include table declaration} 包括表声明

### File: ../src/plugins/export/sql.tcl
mcset zh_cn {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.} {If enabled, then table DDL (CREATE TABLE)
will be included in exported SQL.}

### File: ../src/plugins/export/sql.tcl
mcset zh_cn {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.} {You need to configure table name to export query results to SQL.
SQL INSERTs require table in their syntax.}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn Dimensions Dimensions

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Paper size:} {Paper size:}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Margin size:} {Margin size:}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Cell padding:} {Cell padding:}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Limit amount of data bytes in single cell to:} {Limit amount of data bytes in single cell to:}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Font size:} {Font size:}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Built-in font} {Built-in font}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn Font: Font:

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {TrueType font} {TrueType font}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Font file:} {Font file:}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Font encoding:} {Font encoding:}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Columns and rows} {Columns and rows}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Header background} {Header background}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Empty space} {Empty space}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Fill empty space in cells} {Fill empty space in cells}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.} {If one column in the same row has very long value
and other columns have short values,
then this option makes empty space left below short values
to be filled with coloured background.}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Minimum height of empty space to fill:} {Minimum height of empty space to fill:}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.} {If the height of empty space in cell is smaller
than value specified here, then no special background will be drawn.}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Empty space background} {Empty space background}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {TTF Fonts} {TTF Fonts}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {All Files} {All Files}

### File: ../src/plugins/export/pdf.tcl
mcset zh_cn {Open TTF font} {Open TTF font}

### File: ../src/plugins/populating/random.tcl
mcset zh_cn {Include alpha characters} {包含 alpha 字符}

### File: ../src/plugins/populating/random.tcl
mcset zh_cn {Include numeric characters} 包含数字字符

### File: ../src/plugins/populating/random.tcl
mcset zh_cn {Include whitespace characters} 包含空白字符

### File: ../src/plugins/populating/random.tcl
mcset zh_cn {Include binary characters} 包含二进制字符

### File: ../src/plugins/populating/random.tcl
mcset zh_cn {Minimum length:} 最小长度:

### File: ../src/plugins/populating/random.tcl
mcset zh_cn {Maximum length:} 最大长度:

### File: ../src/plugins/populating/random_number.tcl
mcset zh_cn {Minimum value:} 最小值:

### File: ../src/plugins/populating/random_number.tcl
mcset zh_cn {Maximum value:} 最大值:

### File: ../src/plugins/populating/random_number.tcl
mcset zh_cn {Constant prefix:} 常数前缀:

### File: ../src/plugins/populating/random_number.tcl
mcset zh_cn {Constant suffix:} 常数后缀:

### File: ../src/plugins/populating/sql.tcl
mcset zh_cn {Initialisation code} {Initialisation code}

### File: ../src/plugins/populating/sql.tcl
mcset zh_cn {Per iteration code} {Per iteration code}

### File: ../src/plugins/populating/sql.tcl
mcset zh_cn {Closing code} {Closing code}

### File: ../src/plugins/populating/constant.tcl
mcset zh_cn {Value to use:} 使用的值:

### File: ../src/plugins/populating/sequence.tcl
mcset zh_cn {Start from:} 始于:

### File: ../src/plugins/populating/dictionary.tcl
mcset zh_cn {Dictionary file:} 字典文件:

### File: ../src/plugins/populating/dictionary.tcl
mcset zh_cn {Dictionary words separator:} 字典单词分隔符:

### File: ../src/plugins/populating/dictionary.tcl
mcset zh_cn Whitespace 空格

### File: ../src/plugins/populating/dictionary.tcl
mcset zh_cn {Line break} 断行

### File: ../src/plugins/populating/dictionary.tcl
mcset zh_cn {Method of using words:} 使用单词的方法:

### File: ../src/plugins/populating/dictionary.tcl
mcset zh_cn Randomly 只读的

### File: ../src/plugins/populating/dictionary.tcl
mcset zh_cn Consecutively 连续地

### File: ../src/plugins/populating/dictionary.tcl
mcset zh_cn {Dictionary file doesn't exist, or unreadable.} {Dictionary file doesn't exist, or unreadable.}

### File: ../src/plugins/populating/dictionary.tcl
mcset zh_cn {Dictionary file is empty!} 字典文件为空!

### File: ../src/plugins/populating/dictionary.tcl
mcset zh_cn {Dictionary file} 字典文件

### File: ../src/taskbar.tcl
mcset zh_cn Database: 数据库:

### File: ../src/taskbar.tcl
mcset zh_cn Table: 表:

### File: ../src/taskbar.tcl
mcset zh_cn {Type new name for a window} 输入新视窗名字

### File: ../src/taskbar.tcl
mcset zh_cn {Window with given name already exists. Please type other name.} {Window with given name already exists. Please type other name.}

### File: ../src/taskbar.tcl
mcset zh_cn {Type new name for a task} 输入新任务名字

### File: ../src/taskbar.tcl
mcset zh_cn {Close selected window} 关闭选中的视窗

### File: ../src/taskbar.tcl
mcset zh_cn {Close other windows} 关闭其他视窗

### File: ../src/taskbar.tcl
mcset zh_cn {Close all windows} 关闭所有视窗

### File: ../src/taskbar.tcl
mcset zh_cn {Restore last closed window} {Restore last closed window}

### File: ../src/taskbar.tcl
mcset zh_cn {Rename selected window} 重命名选中的视窗

### File: ../src/windows/table_win.tcl
mcset zh_cn Structure 结构

### File: ../src/windows/table_win.tcl
mcset zh_cn Data 数据

### File: ../src/windows/table_win.tcl
mcset zh_cn Constraints 约束

### File: ../src/windows/table_win.tcl
mcset zh_cn Indexes 索引

### File: ../src/windows/table_win.tcl
mcset zh_cn Triggers 触发器

### File: ../src/windows/table_win.tcl
mcset zh_cn {Grid view} 表格视图

### File: ../src/windows/table_win.tcl
mcset zh_cn {Form view} 表单视图

### File: ../src/windows/table_win.tcl
mcset zh_cn {Refresh table columns and DDL (%s)} {刷新表的列和 DDL (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Edit table (%s)} {编辑表 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Export table data (%s)} {导出表数据 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Import data to table (%s)} {Import data to table (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Populate table (%s)} {填入表 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Create similar table} 创建相似表

### File: ../src/windows/table_win.tcl
mcset zh_cn {Refresh table data (%s)} {刷新表数据 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Add custom number of rows} {Add custom number of rows}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Add new row (%s)} {添加新行 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Delete selected row (%s)} {删除选中的行 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Commit changes (%s)} {Commit changes (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Rollback new row (%s)} {回滚新行 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {First %s rows} {最前的 %s 行}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Previous %s rows} {前面的 %s 行}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Next %s rows} {后面的 %s 行}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Last %s rows} {最后的 %s 行}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Export table data} 导出表数据

### File: ../src/windows/table_win.tcl
mcset zh_cn {Import data to table} {Import data to table}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Populate table} 填入表

### File: ../src/windows/table_win.tcl
mcset zh_cn {Enter phrase you want to look for} 输入你要查询的短语

### File: ../src/windows/table_win.tcl
mcset zh_cn {Apply data filter} 应用数据筛选

### File: ../src/windows/table_win.tcl
mcset zh_cn {Clear data filter} 清除数据筛选

### File: ../src/windows/table_win.tcl
mcset zh_cn {Total rows: %s} {全部行: %s}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Rollback changes (%s)} {回滚改变 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {First row from data grid (%s)} {数据表格中的第一行 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Previous row from data grid (%s)} {数据表格中的前一行 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Next row from data grid (%s)} {数据表格中的后一行 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Last row from data grid (%s)} {数据表格中的最后一行 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Field switching mode.

Click it to make <Tab> key to insert tab characters.} {字段开关模式.

单击它以使 <Tab> 键能够插入 tab 字符.}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.} {Tab inserting mode.

Click it to make <Tab> key switch between form edit fields.}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Refresh table indexes (%s)} {刷新表索引 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Create new index (%s)} {创建新索引 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Edit index (%s)} {编辑索引 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Delete index (%s)} {删除索引 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Refresh table triggers (%s)} {刷新表触发器 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Create new trigger (%s)} {创建新触发器 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Edit trigger (%s)} {编辑触发器 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Delete trigger (%s)} {删除触发器 (%s)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Constraint name} 约束名

### File: ../src/windows/table_win.tcl
mcset zh_cn {Column name} 列名

### File: ../src/windows/table_win.tcl
mcset zh_cn Default 缺省

### File: ../src/windows/table_win.tcl
mcset zh_cn {Not NULL} {Not NULL}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Primary key} {主键Primary key}

### File: ../src/windows/table_win.tcl
mcset zh_cn Unique 唯一

### File: ../src/windows/table_win.tcl
mcset zh_cn Collate 比较

### File: ../src/windows/table_win.tcl
mcset zh_cn Check 检查

### File: ../src/windows/table_win.tcl
mcset zh_cn {Foreign key} {外键Foreign key}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Index name} 索引名字

### File: ../src/windows/table_win.tcl
mcset zh_cn {On column} 列

### File: ../src/windows/table_win.tcl
mcset zh_cn {SQL code} {SQL 代码}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Trigger name} 触发器名字

### File: ../src/windows/table_win.tcl
mcset zh_cn {On table} 表

### File: ../src/windows/table_win.tcl
mcset zh_cn Name 名字

### File: ../src/windows/table_win.tcl
mcset zh_cn {Data type} 数据类型

### File: ../src/windows/table_win.tcl
mcset zh_cn {Default value} 缺省值

### File: ../src/windows/table_win.tcl
mcset zh_cn {Refreshing dependencies} 刷新依赖

### File: ../src/windows/table_win.tcl
mcset zh_cn {Refreshing table columns...} 刷新表列...

### File: ../src/windows/table_win.tcl
mcset zh_cn {Refreshing table data...} 刷新表数据...

### File: ../src/windows/table_win.tcl
mcset zh_cn {Refreshing table indexes...} 刷新表索引...

### File: ../src/windows/table_win.tcl
mcset zh_cn {Refreshing table triggers...} 刷新表触发器...

### File: ../src/windows/table_win.tcl
mcset zh_cn {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.} {Table '%s' doesn't have DDL in sqlite_master table or doesn't exist in database anymore. This table window will be closed now.}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Check condition} 检查情况

### File: ../src/windows/table_win.tcl
mcset zh_cn {Total rows: %s (filtered)} {全部行: %s (筛选后的)}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Pending commits} 挂起执行

### File: ../src/windows/table_win.tcl
mcset zh_cn {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?} {There are uncommited data modifications.
Reloading data will cancel them.
Are you sure you want to continue?}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Loading data...} 加载数据...

### File: ../src/windows/table_win.tcl
mcset zh_cn {Loading table '%s'...} {加载表 '%s'...}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.} {Using all of %s, %s and %s characters in column name at once is highly discouraged and should be avoided at all costs. Therefor changing name of column %s in table %s is recommended. Table data won't be loaded now.}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.} {Table '%s' has no DDL. Probably it doesn't exist anymore, or it's system table.}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Edit table} 编辑表

### File: ../src/windows/table_win.tcl
mcset zh_cn {Enter number of rows to add:} {Enter number of rows to add:}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Add rows} {Add rows}

### File: ../src/windows/table_win.tcl
mcset zh_cn {New index} 新建索引

### File: ../src/windows/table_win.tcl
mcset zh_cn {Index '%s' has no DDL. Probably it's system index and should not be edited.} {Index '%s' has no DDL. Probably it's system index and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Edit index} 编辑索引

### File: ../src/windows/table_win.tcl
mcset zh_cn {Delete index} 删除索引

### File: ../src/windows/table_win.tcl
mcset zh_cn {Are you sure you want to delete '%s' index?} {你确定要删除索引 '%s' ?}

### File: ../src/windows/table_win.tcl
mcset zh_cn {New trigger} 新建触发器

### File: ../src/windows/table_win.tcl
mcset zh_cn {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.} {Trigger '%s' has no DDL. Probably it's system trigger and should not be edited.}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Edit trigger} 编辑触发器

### File: ../src/windows/table_win.tcl
mcset zh_cn {Delete trigger} 删除触发器

### File: ../src/windows/table_win.tcl
mcset zh_cn {Are you sure you want to delete '%s' trigger?} {你确定要删除触发器 '%s' ?}

### File: ../src/windows/table_win.tcl
mcset zh_cn {Export table} 导出表

### File: ../src/windows/table_win.tcl
mcset zh_cn {Import data} {Import data}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {SQL query} {SQL 查询}

### File: ../src/windows/editor_win.tcl
mcset zh_cn Results 结果

### File: ../src/windows/editor_win.tcl
mcset zh_cn History 历史

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Execute query (%s)} {执行查询 (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Execute query with plain string results} {Execute query with plain string results}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Explain query (%s)} {解释查询 (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Format SQL code (%s)} {格式化 SQL 代码 (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Refresh syntax highlighting (%s)} {刷新 syntax highlighting (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Clear history} 清空历史

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Export results} 导出结果

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Create view from query} 通过查询创建新视图

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Execute SQL from file (%s)} {执行文件中的 SQL (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Load SQL from file (%s)} {从文件加载 SQL  (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Save SQL to file (%s)} {保存 SQL 到文件 (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Default database for SQL executing
(%s/%s)} {Default database for SQL executing
(%s/%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn Database 数据库

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Execution date} 执行的数据

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Execution time (s)} {执行时间 (s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Rows affected} 受影响的行

### File: ../src/windows/editor_win.tcl
mcset zh_cn SQL SQL

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Plain text view} 纯文本视图

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Refresh results (%s)} {刷新结果 (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Commit row (%s)} {Commit row (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Rollback row (%s)} {Rollback row (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Copy (%s)} {拷贝 (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Cut (%s)} {剪切 (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Paste (%s)} {粘贴 (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Show line numbers} 显示行数

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Delete selected history entry (%s)} {Delete selected history entry (%s)}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Choose the database first.} 请先选择数据库.

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Error while trying to collect completion list: %s} {Error while trying to collect completion list: %s}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Can't open %s file for reading.} {不能打开 %s 文件读出.}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Can't open %s file for writting.} {不能打开 %s 文件写入.}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {SQL code saved in %s.} {SQL 代码保存在 %s.}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Are you sure you want to clear queries history?} {Are you sure you want to clear queries history?}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Delete the history entry} {Delete the history entry}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Are you sure you want to delete selected queries history entry?} {Are you sure you want to delete selected queries history entry?}

### File: ../src/windows/editor_win.tcl
mcset zh_cn Processing... 处理...

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Processing query...} 处理查询...

### File: ../src/windows/editor_win.tcl
mcset zh_cn {No results to export.} 没有结果导出.

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.} {Using ATTACH from SQL editor is not allowed. Instead, register the database you want to attach in SQLiteStudio and use it's name visible in databases tree in any SQL statements you need. They will be auto-attached on request.}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Query execution...} 查询执行...

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Executing SQL query...} 执行SQL查询...

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Error while executing query: %s} {执行查询出错: %s}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s} {Unknown error while query execution. Please report it! ReturnCode=%s. Query for execution was: %s}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {%s row(s) read in %s second(s).} {%s row(s) read in %s second(s).}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {%s row(s) affected in %s second(s).} {%s row(s) affected in %s second(s).}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {No SELECT statements found in editor or in selected part of SQL code.} {No SELECT statements found in editor or in selected part of SQL code.}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {More than one SELECT statements found. Please select the one you're interested in and then try again.} {More than one SELECT statements found. Please select the one you're interested in and then try again.}

### File: ../src/windows/editor_win.tcl
mcset zh_cn {New view} 新建视图

### File: ../src/windows/editor_win.tcl
mcset zh_cn {Fill query parameters} 填充查询参数

### File: ../src/error.tcl
mcset zh_cn {Background error} 背景错误

### File: ../src/error.tcl
mcset zh_cn Close 关闭

### File: ../src/error.tcl
mcset zh_cn {Report the bug} 输出bug

### File: ../src/dialogs/about_dialog.tcl
mcset zh_cn About 关于

### File: ../src/dialogs/about_dialog.tcl
mcset zh_cn {Packages and plugins} 包和插件

### File: ../src/dialogs/about_dialog.tcl
mcset zh_cn Licence 许可证

### File: ../src/dialogs/about_dialog.tcl
mcset zh_cn {Installed plugins:} 安装插件:

### File: ../src/dialogs/about_dialog.tcl
mcset zh_cn {Used Tcl packages:} {使用 Tcl 包:}

### File: ../src/dialogs/about_dialog.tcl
mcset zh_cn {SQLite3 engine version: %s} {SQLite3 引擎版本: %s}

### File: ../src/dialogs/searchdialog.tcl
mcset zh_cn {Global expression understeands '*', '?' and \[chars].} {Global expression understeands '*', '?' and \[chars].}

### File: ../src/dialogs/searchdialog.tcl
mcset zh_cn Find 查找

### File: ../src/dialogs/searchdialog.tcl
mcset zh_cn Replace 替换

### File: ../src/dialogs/searchdialog.tcl
mcset zh_cn {Do you want to replace marked text?} 你希望替换选中的文本?

### File: ../src/dialogs/searchdialog.tcl
mcset zh_cn {Replace all} 全部替换

### File: ../src/dialogs/searchdialog.tcl
mcset zh_cn {Replacing finished.} 完成替换.

### File: ../src/dialogs/searchdialog.tcl
mcset zh_cn {Cannot match the pattern!} 不能匹配模式!

### File: ../src/dialogs/bind_param.tcl
mcset zh_cn {Query number %s} {Query number %s}

### File: ../src/dialogs/bind_param.tcl
mcset zh_cn {Parameter number %s (named: %s):} {参数编号 %s (名字: %s):}

### File: ../src/dialogs/bind_param.tcl
mcset zh_cn {NULL value} {NULL value}

### File: ../src/dialogs/bind_param.tcl
mcset zh_cn {You can use '%s' keyboard shortcut to switch NULL value.} {You can use '%s' keyboard shortcut to switch NULL value.}

### File: ../src/dialogs/bind_param.tcl
mcset zh_cn {Copy value to other '%s' parameters (%s)} {Copy value to other '%s' parameters (%s)}

### File: ../src/dialogs/bind_param.tcl
mcset zh_cn {By enabling this all parameters with same name
will also have same value as this one.} {By enabling this all parameters with same name
will also have same value as this one.}

### File: ../src/dialogs/bind_param.tcl
mcset zh_cn {Execute query} 执行查询

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset zh_cn Collation 校正

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset zh_cn Sort 排序

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset zh_cn {Named constraint:} 命名约束:

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset zh_cn {On conflict:} 冲突:

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset zh_cn {Constraint is marked as being named, but there's no name filled in.} {Constraint is marked as being named, but there's no name filled in.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset zh_cn {Collation for column '%s' is enabled, but there's no collation name filled in.} {Collation for column '%s' is enabled, but there's no collation name filled in.}

### File: ../src/dialogs/table_dialog_uniq.tcl
mcset zh_cn {No columns are selected.} 没有列被选中.

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn {Number of rows to insert:} 插入行数:

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn {On a constraint violation:} {On a constraint violation:}

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn Mode 模式

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn {Select table to display available columns} 选中表显示合适的若干列

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn Populate 填入

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn {Error occured while populating table:
%s} {填入表错误:
%s}

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn Configuration 配置

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn {You have to type valid number of rows to insert.} 你必须输入插入行的合理数量.

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn {You have to select at least one column to populate.} 你至少选择其中一列填入.

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn Populating... 填入...

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn {Populating table '%s'.} {填入表 '%s'.}

### File: ../src/dialogs/populate_table.tcl
mcset zh_cn Stop 停止

### File: ../src/dialogs/table_dialog_fk.tcl
mcset zh_cn {Foreign table:} 外表:

### File: ../src/dialogs/table_dialog_fk.tcl
mcset zh_cn {Local column} 本地列

### File: ../src/dialogs/table_dialog_fk.tcl
mcset zh_cn {Foreign column} 外列

### File: ../src/dialogs/table_dialog_fk.tcl
mcset zh_cn Reactions Reactions

### File: ../src/dialogs/table_dialog_fk.tcl
mcset zh_cn {ON UPDATE} 更新

### File: ../src/dialogs/table_dialog_fk.tcl
mcset zh_cn {ON DELETE} 删除

### File: ../src/dialogs/table_dialog_fk.tcl
mcset zh_cn MATCH 匹配

### File: ../src/dialogs/table_dialog_fk.tcl
mcset zh_cn {Deferred foreign key} {预留的外键 foreign key}

### File: ../src/dialogs/table_dialog_fk.tcl
mcset zh_cn {No foreign table selected.} 没有外表被选中.

### File: ../src/dialogs/table_dialog_fk.tcl
mcset zh_cn {There's no foreign column assigned for local column '%s'.} {There's no foreign column assigned for local column '%s'.}

### File: ../src/dialogs/import_dialog.tcl
mcset zh_cn {Import from:} {Import from:}

### File: ../src/dialogs/import_dialog.tcl
mcset zh_cn {Import to:} {Import to:}

### File: ../src/dialogs/import_dialog.tcl
mcset zh_cn Table 表

### File: ../src/dialogs/import_dialog.tcl
mcset zh_cn Existing Existing

### File: ../src/dialogs/import_dialog.tcl
mcset zh_cn {Create new table} {Create new table}

### File: ../src/dialogs/import_dialog.tcl
mcset zh_cn Import Import

### File: ../src/dialogs/import_dialog.tcl
mcset zh_cn {Import method is not selected.} {Import method is not selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset zh_cn {You have to choose database.} 你必须选择数据库.

### File: ../src/dialogs/import_dialog.tcl
mcset zh_cn {No existing table is selected.} {No existing table is selected.}

### File: ../src/dialogs/import_dialog.tcl
mcset zh_cn {Table typed to create already exists. Please change table name.} {Table typed to create already exists. Please change table name.}

### File: ../src/dialogs/view_dialog.tcl
mcset zh_cn View 视图

### File: ../src/dialogs/view_dialog.tcl
mcset zh_cn {View name:} 视图名:

### File: ../src/dialogs/view_dialog.tcl
mcset zh_cn {Code executed to get view data:} 如下执行代码获得视图数据:

### File: ../src/dialogs/view_dialog.tcl
mcset zh_cn Create 创建

### File: ../src/dialogs/view_dialog.tcl
mcset zh_cn Change 修改

### File: ../src/dialogs/view_dialog.tcl
mcset zh_cn {You have to specify database.} 你必须界定数据库.

### File: ../src/dialogs/view_dialog.tcl
mcset zh_cn {You have to specify view name.} 你必须声明视图名字.

### File: ../src/dialogs/view_dialog.tcl
mcset zh_cn {You havn't wrote a code for the view.} 你没有为视图写代码.

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {Export data} 导出数据

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {Only structure, without data} {只有结构, 无数据}

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {Table or view} {Table or view}

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {Output file} 输入文件

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {Export format} 导出格式

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn Export 导出

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {You have to choose file.} 你必须选择文件.

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {Can't write to file: %s} {不能写入文件: %s}

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {You have to choose table.} 你必须选择表.

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {Exporting database '%s'.} {导出数据库 '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {Exporting table '%s'.} {导出表 '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {Exporting view '%s'.} {Exporting view '%s'.}

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {Exporting results.} 导出结果.

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn Exporting... 导出...

### File: ../src/dialogs/export_dialog.tcl
mcset zh_cn {Cannot write to file: %s
Please select other file.} {Cannot write to file: %s
Please select other file.}

### File: ../src/dialogs/bug_report_login.tcl
mcset zh_cn {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.} {Please type username and password to use for reporting bugs and feature requests. If you don't have one, you can set it up at the URL below. Reporting with your own user name will let you track your reports easier. The password will be stored in encrypted format.}

### File: ../src/dialogs/bug_report_login.tcl
mcset zh_cn Login: Login:

### File: ../src/dialogs/bug_report_login.tcl
mcset zh_cn Password: Password:

### File: ../src/dialogs/bug_report_login.tcl
mcset zh_cn Validate Validate

### File: ../src/dialogs/bug_report_login.tcl
mcset zh_cn {Validation result} {Validation result}

### File: ../src/dialogs/bug_report_login.tcl
mcset zh_cn {Not validated yet} {Not validated yet}

### File: ../src/dialogs/bug_report_login.tcl
mcset zh_cn Validating... Validating...

### File: ../src/dialogs/bug_report_login.tcl
mcset zh_cn {Validating login and password...} {Validating login and password...}

### File: ../src/dialogs/bug_report_login.tcl
mcset zh_cn {Invalid login or password.} {Invalid login or password.}

### File: ../src/dialogs/bug_report_login.tcl
mcset zh_cn {Login and password are correct.} {Login and password are correct.}

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Your e-mail address or user (both optional)} {Your e-mail address or user (both optional)}

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn or 或

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Log in} {Log in}

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Logged in} {Logged in}

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Log out} {Log out}

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Brief description:} 摘要描述:

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {How to reproduce problem (if possible):} {怎样使问题再发生 (如果可能):}

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {What is the problem:} 问题:

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Show more (optional)} {Show more (optional)}

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Operating system:} 操作系统:

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Take screenshots of all SQLiteStudio windows and attach them} {Take screenshots of all SQLiteStudio windows and attach them}

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn Send 发送

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Describe your feature request:} 描述你的特征需求:

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn Hide Hide

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Please fill 'Brief' field.} {请填充 '摘要' 字段.}

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Please fill at least one of 'Description' or 'How to reproduce' fields.} {Please fill at least one of 'Description' or 'How to reproduce' fields.}

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {Please provide valid e-mail address or leave 'E-mail' empty.} {Please provide valid e-mail address or leave 'E-mail' empty.}

### File: ../src/dialogs/bug_report.tcl
mcset zh_cn {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.} {This e-mail will NOT be shared to anyone, neither used for any other
purpose then described below. It won't be published anywhere.
It will be used only by SQLiteStudio developer to eventually contact
you if any additional details for this report are necessary.

It is optional. You can leave it empty.}

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Database to convert:} 要转换的数据库:

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Converted database name:} 要转换的数据库名字:

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {File to use for converted database:} 用于转换数据库的文件:

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Choose new file for database} 为数据库选择新文件

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Database version:} 数据库版本:

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn Convert 转换

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Convert database} 转换数据库

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {You chave to choose database to convert.} 你必须选择要转换的数据库.

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Error resolving database with name %s!} {处理数据库 %s 发生错误!}

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {You have to specify new database file.} 你必须界定新数据库文件.

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Cannot use existing file for converted database.} {Cannot use existing file for converted database.}

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Cannot use existing name for converted database.} {Cannot use existing name for converted database.}

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Cannot find handler for database labeled with: %s} {Cannot find handler for database labeled with: %s}

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Error while trying to create database: %s} {Error while trying to create database: %s}

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Database converting error} 数据库转换错误

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s} {Some problems occured while converting database, but it was converted omitting objects causing problems. Details:
%s}

### File: ../src/dialogs/db_convert.tcl
mcset zh_cn {Choose file} 选择文件

### File: ../src/dialogs/yesno.tcl
mcset zh_cn Question Question

### File: ../src/dialogs/yesno.tcl
mcset zh_cn Warning 警告

### File: ../src/dialogs/yesno.tcl
mcset zh_cn Error 错误

### File: ../src/dialogs/yesno.tcl
mcset zh_cn Information 信息

### File: ../src/dialogs/import_db.tcl
mcset zh_cn {Import from one of databases:} 从其中一个数据库导入:

### File: ../src/dialogs/import_db.tcl
mcset zh_cn {Choose database file to import:} 选择数据库文件导入:

### File: ../src/dialogs/import_db.tcl
mcset zh_cn {No database chosen.} 没有数据库被选择.

### File: ../src/dialogs/import_db.tcl
mcset zh_cn {Cannot open specified database.} 不能打开指定数据库.

### File: ../src/dialogs/import_db.tcl
mcset zh_cn {Error while importing database:
%s} {导入数据库错误:
%s}

### File: ../src/dialogs/import_db.tcl
mcset zh_cn {Select file} 选择文件

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn Column: 列:

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Column constraints:} 列约束:

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn Add 添加

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn Size 大小

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Maximal length of value in column.} 列值的最大长度.

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Primary key configuration} {主键Primary key 配置}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn Autoincrement 自动增加

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Sort order:} 排序次序:

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {No foreign column selected.} 没有外列被选中.

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Choose ON UPDATE action, or disable it.} {选择 ON UPDATE 行为, 或禁用它.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Choose ON DELETE action, or disable it.} {选择 ON DELETE 行为, 或禁用它.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Choose MATCH action, or disable it.} {选择 MATCH 行为, 或禁用它.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Foreign key configuration} {外键Foreign key 配置}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Foreign column:} 外列:

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Unique configuration} {Unique 配置}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Fill in the condition expression.} 以条件表达式填充.

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Check condition configuration} {Check 条件配置}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn Condition: 条件:

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Not null configuration} {Not null 配置}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Fill in the collation name.} 以校正名字填充.

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Collating configuration} 比较配置

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Collation name:} 校正名字:

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Fill in the default value.} 以缺省值填充.

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Default value configuration} 配置的缺省值

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Default value:} 缺省值:

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Use value as:} {Use value as:}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {A literal value} {A literal value}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {An expression} {An expression}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Column primary key is not configured correctly.} {Column primary key is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {AUTOINCREMENT is allowed only with INTEGER type of column.} {AUTOINCREMENT is allowed only with INTEGER type of column.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Column foreign key is not configured correctly.} {Column foreign key is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Column 'unique' constraint is not configured correctly.} {Column 'unique' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Column 'check' constraint is not configured correctly.} {Column 'check' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Column 'notnull' constraint is not configured correctly.} {Column 'notnull' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Column 'default' constraint is not configured correctly.} {Column 'default' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Column 'collate' constraint is not configured correctly.} {Column 'collate' constraint is not configured correctly.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {No column name is specified.} 未定义列名.

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Column with name '%s' already exists in the table.} {Column with name '%s' already exists in the table.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Data type bounds are given, but no data type name is specified.} {Data type bounds are given, but no data type name is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Data type precision is given, but no data type size is specified.} {Data type precision is given, but no data type size is specified.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Data type size has invalid format. Only integer value is allowed.} {Data type size has invalid format. Only integer value is allowed.}

### File: ../src/dialogs/column_dialog.tcl
mcset zh_cn {Data type precision has invalid format. Only integer value is allowed.} {Data type precision has invalid format. Only integer value is allowed.}

### File: ../src/dialogs/assoc_dialog.tcl
mcset zh_cn {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:} {SQLiteStudio detected following file extensions associated to previous installation(s) of SQLiteStudio:}

### File: ../src/dialogs/assoc_dialog.tcl
mcset zh_cn {Current associations} {Current associations}

### File: ../src/dialogs/assoc_dialog.tcl
mcset zh_cn {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.} {Please select file extensions you would like to associate to currently running version of SQLiteStudio and click OK.}

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {Database file:} 数据库文件:

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {Database name:} 数据库名字:

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {Generate automatically} 自动产生

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {Type name in field below:} 将名字写在下列区域内:

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {Remember it permanently} 永久记住它

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {If disabled, then the database will be registered only
for this single SQLiteStudio session.} {If disabled, then the database will be registered only
for this single SQLiteStudio session.}

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {Edit database} 编辑数据库

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {Add database} 添加数据库

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {File '%s' doesn't exist!} {File '%s' doesn't exist!}

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {You have to specify database file.} 你必须确定一个数据库文件.

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {Database named '%s' already exists on databases list. Please pick other name.} {Database named '%s' already exists on databases list. Please pick other name.}

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.} {Database '%s' already exists on databases list with name '%s'. Please pick other database file or abort.}

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.} {SQLite 2 driver doesn't deal with non-ASCII file names well. Please do not use national characters, use ASCII-compliant file name.}

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {Type not existing file for new database} 为新数据库输入不存在的文件

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {Select existing database file} 选择已有数据库文件

### File: ../src/dialogs/db_edit.tcl
mcset zh_cn {%s is not supported database!} {%s 是不被支持的数据库!}

### File: ../src/dialogs/table_dialog_pk.tcl
mcset zh_cn {Using autoincrement with more than one column at once is forbidden.} {Using autoincrement with more than one column at once is forbidden.}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn Previous 前一个

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn Next 后一个

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {Do not show this dialog at startup} 程序启动时不显示这个对话框

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		} {
			If you dislike to open multiple SQL editors, you can use single editor,
			write a lot of SQL in it and finally select (mark) only this part of code you want to execute,
			then press Execute SQL.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			You can configure all SQL editor syntax colors in settings.
		} {
			你能够在设置中配置所有 SQL 编辑器中语法颜色.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		} {
			Valid table names in SQL editor are highlighted with blue color (configurable).
			If a table name you expect to be highlighted - is not, it means that you've made a mistake when typing the name,
			or you've got selected other context database in SQL editor (at the top of editor window),
			where that table doesn't exist.<br><br>
			You can also press and hold Control key to underline valid table names - they become links so you can
			open adequate table windows quickly.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		} {
			You can use Control+Space shortcut (configurable) to complete word you've started typing in SQL editor.
			Completion engine can also guess next word by a SQL context and show you filtered list of words matching that context.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		} {
			There are various shortcuts (all of them are configurable) that can make using SQLiteStudio much easier
			and faster.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		} {
			You do not have to confirm each edition in data grid by pressing Enter or "Commit" button at toolbar.
			You can just click on any other cell (or anywhere else) to make edited data commit by itself.
			To rollback changes done while editing cell - press Escape.<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		} {
			If you close SQLiteStudio with any MDI windows opened, they all will be restored (including SQL code typed in editors),
			while next application startup, unless you disable "session restoring" in settings.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		} {
			SQLiteStudio provides some extra SQLite functions that you can use in SQL editor. These are:
			tcl() - runs custom Tcl code in new, separated Tcl interpreter,<br>
			sqlfile() - executes SQL from given file in current database,<br>
			md5() - calculates MD5 checksum of given argument,<br>
			base64_encode() - encodes given argument with BASE64 algorithm,<br>
			base64_decode() - decodes given argument with BASE64 algorithm,<br>
			for more functions see User Manual.<br>
			Examples:<br><br>
			<tab>SELECT tcl('return [expr {pow(5,5)} ]') AS '5 to power 5';<br><br>
			<tab>SELECT sqlfile('C:/schema.sql');<br><br>
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		} {
			You can define your own SQL functions that will be available in database while editing it with SQLiteStudio.
			It helps to emulate functions implemented in target application which uses the database.<br>
			To implement new function go to Custom SQL functions dialog and push add button (one with plus icon on it),
			then enter it's name and choose language you want to use to implement function (Tcl or SQL).<br>
			Implementation code can contain $0, $1, $2 and so on - they are positional parameters passed to function when it's invoked.<br><br>
			Here's example function implementation code using SQL:<br>
			<tab>SELECT 2 * id FROM table_name WHERE id = $1;
			<br><br>
			And here's one implemented with Tcl:<br>
			<tab>set fd [open filename r]<br>
			<tab>set data [read $fd]<br>
			<tab>close $fd<br>
			<tab>return $data
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		} {
			If you're looking for some word in table data, but you don't want to write SQL for it, or just don't remember
			which column contains this word, go to table data view, type the word in filter entry and push "Apply filter".
			It will find all occurances of the word (even with prefixes or suffixes) in any
			column and table data will be filtered to these matched entries only.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		} {
			You can edit values in results grid, but be aware that columns that doesn't come from a table directly (for example they are result of math operations on column) - cannot be edited.
			Such uneditable cells are also ommited when some data has been pasted into the grid.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		} {
			If you want to see ROWID of some specific row, you can just leave your mouse pointer over the row you're insterested in for a moment.
			The tip will pop up with ROWID (and other informations) for that row.<br><br>
			In data grid view of table window you can switch displaying ROWID instead of order number in first column. This option is available from grid view context menu.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		} {
			To put NULL value to a cell (not just empty value) you need to use either Backspace key while cell is selected, or select "Set NULL value" from grid view context menu.<br>
			You can do above while having multiple cells selected.<br><br>
			Form View lets you to set NULL value for each cell separately using checkbox or Alt-n shortcut (which is configurable).<br><br>
			Remember that you can always set NULL value manually using SQL query.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		} {
			You can place results of executed query below actual query, instead of switching to next tab. Just switch SQL Editor window layout in Configuration window.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		} {
			You can always get back to queries you've executed before by switching to history tab in SQL Editor window.<br><br>
			Number of entries kept in history is configurable, but be aware, that if that value is too high, then each time you will open new SQL Editor
			the whole history will be read and it might slowdown the opening process a little.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		} {
			SQL Editor window can help you with writting queries - press Control+Space (or whatever shortcut you've configured) in the window to raise query completion dialog.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		} {
			You can use multiple database names in single SQL query without taking care of attaching them into current database.
			SQLiteStudio will handle it for you.<br><br>
			Use database names as displayed in databases tree on the left side. An example:<br>
			<tab>SELECT t1.*, t2.* FROM table1 t1 JOIN other_database.table2 t2 ON (t1.id = t2.id);
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		} {
			You can hold "Control" key and click on the data grid to select entire row, instead of a single cell.
		}

### File: ../src/dialogs/tips_dialog.tcl
mcset zh_cn {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		} {
			In SQL Editor window you can select just a part of the SQL query and click "Execute" (or press %s)
			to execute only selected part of the code.
		}

### File: ../src/dialogs/import_table.tcl
mcset zh_cn Separator: 分隔符:

### File: ../src/dialogs/import_table.tcl
mcset zh_cn {Common separator is \t (tab), but sometimes others can be met.} {Common separator is \t (tab), but sometimes others can be met.}

### File: ../src/dialogs/import_table.tcl
mcset zh_cn {Import data file for '%s' table:} {导入数据文件到 '%s' 表:}

### File: ../src/dialogs/import_table.tcl
mcset zh_cn {File '%s' isn't readable!} {文件 '%s' 不可读!}

### File: ../src/dialogs/import_table.tcl
mcset zh_cn {Error while trying to copy data:
%s} {Error while trying to copy data:
%s}

### File: ../src/dialogs/release_notes_dialog.tcl
mcset zh_cn {Don't show this dialog after update.} {Don't show this dialog after update.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn Trigger 触发器

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {On action:} 行为:

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {Trigger name:} 触发器名字:

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn When: 当:

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {On table:} 表:

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {Execute code for:} 执行代码:

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.} {Defines column list for 'UPDATE OF' action.
Requires trigger table to be already selected.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {Execute code only when:} 只有如下要求才执行代码:

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {Code executed for above configuration:} 代码按照上述配置执行:

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {You have to specify view.} 你必须界定视图.

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {You have to specify table.} 你必须界定表.

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {You have to specify trigger name.} 你必须界定触发器名字.

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {You have to specify 'action' condition.} {你必须界定 '行为action' 条件.}

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {You havn't wrote a code for the trigger.} 你不能为触发器写代码.

### File: ../src/dialogs/trigger_dialog.tcl
mcset zh_cn {On view:} 视图:

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn Columns: 列:

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Table constraints:} 表约束:

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Table name:} 表名:

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Add column} 添加列

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Edit selected} 编辑选中

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Delete selected} 删除选中

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn Type 类型

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn Details Details

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.} {Column '%s' is no longer in table '%s', so you cannot edit it. Table was probably modified by other application.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Edit column} 编辑列

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Delete column} 删除列

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Are you sure you want to delete column '%s'?} {你确定要删除列 '%s'?}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Constraint change} {Constraint change}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Are you sure you want to change constraint type?
Current constraint configuration will be lost.} {Are you sure you want to change constraint type?
Current constraint configuration will be lost.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Table constraint number %s (%s) is not configured correctly.} {Table constraint number %s (%s) is not configured correctly.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {There's no column defined.} 没有列被定义.

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {There is already a table with name '%s'. Please change the name of this table.} {There is already a table with name '%s'. Please change the name of this table.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {There is already an index with name '%s'. Please change the name of this index.} {There is already an index with name '%s'. Please change the name of this index.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {There is already a trigger with name '%s'. Please change the name of this trigger.} {There is already a trigger with name '%s'. Please change the name of this trigger.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {There is already a view with name '%s'. Please change the name of this view.} {There is already a view with name '%s'. Please change the name of this view.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for trigger '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Trigger parsing problem} 触发器解释问题

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for index '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Index parsing problem} 索引解释问题

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?} {Cannot parse DDL for view '%s',
so cannot recreate it after table modification.
Do you want to continue?}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {View parsing problem} {View parsing problem}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.} {Could not parse following table DDLs, therfore none of their foreign keys referencing table '%s' will be recreated:

%s.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {%s(%s) referencing %s(%s)} {%s(%s) referencing %s(%s)}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s} {Following foreign keys won't be recreated, because they'd not be valid anymore:

%s}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Do you want to continue anyway?} {Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?} {Following tables won't be recreated with proper foreign keys due to database errors:

%s

Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Modifying table...} 修改表...

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Modifying table '%s'.} {修改表 '%s'.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Could not recreate triggers for modified table.} {Could not recreate triggers for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Could not recreate indexes for modified table.} {Could not recreate indexes for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Could not recreate views for modified table.} {Could not recreate views for modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate trigger '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Trigger recreation problem} 触发器再创建问题

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate index '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Index recreation problem} 索引再创建问题

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {Could not recreate foreign keys for tables referencing modified table.} {Could not recreate foreign keys for tables referencing modified table.}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?} {It won't be possible to recreate view '%s' after table modification.
Do you want to continue anyway?}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {View recreation problem} {View recreation problem}

### File: ../src/dialogs/table_dialog.tcl
mcset zh_cn {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).} {You cannot use all four SQL quoting characters (%s, %s, %s and %s) in one object name (which is: %s).}

### File: ../src/dialogs/table_dialog_chk.tcl
mcset zh_cn {Condition expression cannot be empty.} 条件表达式不能为空.

### File: ../src/dialogs/new_version_dialog.tcl
mcset zh_cn {What would you like to do?} {What would you like to do?}

### File: ../src/dialogs/new_version_dialog.tcl
mcset zh_cn {Install it automatically} {Install it automatically}

### File: ../src/dialogs/new_version_dialog.tcl
mcset zh_cn {Go to download page} 转到下载页

### File: ../src/dialogs/new_version_dialog.tcl
mcset zh_cn {Package download} 包下载

### File: ../src/dialogs/new_version_dialog.tcl
mcset zh_cn {Insufficient privileges to perform automatic update.} {Insufficient privileges to perform automatic update.}

### File: ../src/dialogs/new_version_dialog.tcl
mcset zh_cn {Check for updates at startup} 启动时检查更新

### File: ../src/dialogs/new_version_dialog.tcl
mcset zh_cn {New version of SQLiteStudio is available: %s} {新版本的 SQLiteStudio 合适了: %s}

### File: ../src/dialogs/trigger_dialog_cols.tcl
mcset zh_cn {Trigger columns} {Trigger columns}

### File: ../src/dialogs/blob_edit.tcl
mcset zh_cn Commit 执行

### File: ../src/dialogs/bug_history.tcl
mcset zh_cn Clear 清空

### File: ../src/dialogs/bug_history.tcl
mcset zh_cn {Reported on} 报告

### File: ../src/dialogs/bug_history.tcl
mcset zh_cn Brief 摘要

### File: ../src/dialogs/bug_history.tcl
mcset zh_cn URL URL

### File: ../src/dialogs/bug_history.tcl
mcset zh_cn Discussion 讨论

### File: ../src/dialogs/bug_history.tcl
mcset zh_cn {Clear reports} 清空报告

### File: ../src/dialogs/bug_history.tcl
mcset zh_cn {Do you want to clear whole bug reports history?} 你希望清空所有的bug报告历史吗?

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn Index 索引

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn {Index name:} 索引名:

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn Available Available

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn Indexed Indexed

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn {Modifying index} {Modifying index}

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn {Modifying index '%s'} {Modifying index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn {Creating index} {Creating index}

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn {Creating index '%s'} {Creating index '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?} {Unique index cannot be created,
because selected columns contain duplicates.
Do you want to see those values?}

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn {Unique values} 唯一值

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn {Same values for '%s'} {相同的值 '%s'}

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn {You have to select at least one column.} 你至少选择一列.

### File: ../src/dialogs/index_dialog.tcl
mcset zh_cn {You have to specify index name.} 你必须界定索引名.

### File: ../src/dialogs/functions_dialog.tcl
mcset zh_cn Implementation: 实现:

### File: ../src/dialogs/functions_dialog.tcl
mcset zh_cn Name: 名字:

### File: ../src/dialogs/functions_dialog.tcl
mcset zh_cn {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.} {Use $0, $1, $2, $3, ... - as positional parameters
that will be passed to the function.
For example call to my_function('x',5) will call
my_function with 'x' as $0 and 5 as $1.}

### File: ../src/dialogs/functions_dialog.tcl
mcset zh_cn {Cannot use two functions with same name! Change name for '%s'.} {Cannot use two functions with same name! Change name for '%s'.}

### File: ../src/dialogs/functions_dialog.tcl
mcset zh_cn {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! } {Cannot use 'tcl' or 'sqlfile' for function name, these names are reserved! }

### File: ../src/dialogs/functions_dialog.tcl
mcset zh_cn {Function '%s' is not implemented!} {功能 '%s' 未被实现!}

### File: ../src/dialogs/functions_dialog.tcl
mcset zh_cn {Delete function} 删除功能

### File: ../src/dialogs/functions_dialog.tcl
mcset zh_cn {Are you sure you want to delete function '%s'?} {你确定要删除功能 '%s'?}

### File: ../src/mainwindow.tcl
mcset zh_cn {Connect to selected database} 连接选中的数据库

### File: ../src/mainwindow.tcl
mcset zh_cn {Disconnect from selected database} 断开选中数据库的连接

### File: ../src/mainwindow.tcl
mcset zh_cn {Remove selected database from list} 从列表中删除选中数据库

### File: ../src/mainwindow.tcl
mcset zh_cn {New table} 新建表

### File: ../src/mainwindow.tcl
mcset zh_cn {Drop table} 删除表

### File: ../src/mainwindow.tcl
mcset zh_cn {Drop index} 删除索引

### File: ../src/mainwindow.tcl
mcset zh_cn {Drop trigger} 删除触发器

### File: ../src/mainwindow.tcl
mcset zh_cn {Edit view} 编辑视图

### File: ../src/mainwindow.tcl
mcset zh_cn {Drop view} 删除视图

### File: ../src/mainwindow.tcl
mcset zh_cn {Arrange cascade windows layout} 层叠布置窗口布局

### File: ../src/mainwindow.tcl
mcset zh_cn {Arrange intelligent windows layout} 智能化重新布置窗口布局

### File: ../src/mainwindow.tcl
mcset zh_cn {Refresh databases tree (%s)} {刷新数据库树 (%s)}

### File: ../src/mainwindow.tcl
mcset zh_cn {Open SQL query editor} {打开 SQL 查询编辑器}

### File: ../src/mainwindow.tcl
mcset zh_cn {Settings (%s)} {Settings (%s)}

### File: ../src/mainwindow.tcl
mcset zh_cn {Open SQL functions editor} {打开 SQL 功能编辑器}

### File: ../src/mainwindow.tcl
mcset zh_cn {Clear objects filter} {Clear objects filter}

### File: ../src/mainwindow.tcl
mcset zh_cn {Enter object name you want to look for} {Enter object name you want to look for}

### File: ../src/mainwindow.tcl
mcset zh_cn Databases 数据库

### File: ../src/mainwindow.tcl
mcset zh_cn Tools 工具

### File: ../src/mainwindow.tcl
mcset zh_cn Connect 连接

### File: ../src/mainwindow.tcl
mcset zh_cn Disconnect 断开连接

### File: ../src/mainwindow.tcl
mcset zh_cn {Remove from list} 从列表中删除

### File: ../src/mainwindow.tcl
mcset zh_cn {View main toolbar} 查看主工具条

### File: ../src/mainwindow.tcl
mcset zh_cn {View structure toolbar} 查看结构工具条

### File: ../src/mainwindow.tcl
mcset zh_cn {View windows toolbar} 查看视窗工具条

### File: ../src/mainwindow.tcl
mcset zh_cn {View tools toolbar} 查看工具工具条

### File: ../src/mainwindow.tcl
mcset zh_cn {View configuration toolbar} 查看配置工具条

### File: ../src/mainwindow.tcl
mcset zh_cn {Refresh databases tree} 刷新数据库树

### File: ../src/mainwindow.tcl
mcset zh_cn {Custom SQL functions} {客户定制 SQL 功能}

### File: ../src/mainwindow.tcl
mcset zh_cn {Export database} 导出数据库

### File: ../src/mainwindow.tcl
mcset zh_cn {Export table or view} {Export table or view}

### File: ../src/mainwindow.tcl
mcset zh_cn {Import data to a table} {Import data to a table}

### File: ../src/mainwindow.tcl
mcset zh_cn {SQLiteStudio home page} {SQLiteStudio home page}

### File: ../src/mainwindow.tcl
mcset zh_cn {SQLiteStudio manual} {SQLiteStudio 手册}

### File: ../src/mainwindow.tcl
mcset zh_cn {SQLite documentation} {SQLite 文档}

### File: ../src/mainwindow.tcl
mcset zh_cn {SQLiteStudio support forum} SQLiteStudio支持论坛

### File: ../src/mainwindow.tcl
mcset zh_cn {Report a bug} 报告bug

### File: ../src/mainwindow.tcl
mcset zh_cn {Send feature request} 发出特征需求

### File: ../src/mainwindow.tcl
mcset zh_cn {Show bug reports history} 显示bug报告的历史

### File: ../src/mainwindow.tcl
mcset zh_cn {Show tips window} 显示小提示窗口

### File: ../src/mainwindow.tcl
mcset zh_cn ChangeLog 修改的日志

### File: ../src/mainwindow.tcl
mcset zh_cn Roadmap 路线图

### File: ../src/mainwindow.tcl
mcset zh_cn {Check for new version} 检查新版本

### File: ../src/mainwindow.tcl
mcset zh_cn Donate Donate

### File: ../src/mainwindow.tcl
mcset zh_cn {Did you know that...} 你知道吗...

### File: ../src/mainwindow.tcl
mcset zh_cn {Editor %s} {编辑器 %s}

### File: ../src/mainwindow.tcl
mcset zh_cn Settings 设置

### File: ../src/mainwindow.tcl
mcset zh_cn {SQLiteStudio roadmap} {SQLiteStudio 路线图}

### File: ../src/mainwindow.tcl
mcset zh_cn {Can't start web browser, because:
%s} {不能打开web浏览器, 因为:
%s}

### File: ../src/mainwindow.tcl
mcset zh_cn {Can't start %s web browser, because:
%s} {不能打开web浏览器 %s , 因为:
%s}

### File: ../src/mainwindow.tcl
mcset zh_cn {About SQLiteStudio} {关于 SQLiteStudio}

### File: ../src/mainwindow.tcl
mcset zh_cn {SQLiteStudio ChangeLog} {SQLiteStudio 改变的日志}

### File: ../src/mainwindow.tcl
mcset zh_cn {There is no new version available.} 目前无新版本.

### File: ../src/mainwindow.tcl
mcset zh_cn {New version} 新版本

### File: ../src/mainwindow.tcl
mcset zh_cn {Report bug} 报告bug

### File: ../src/mainwindow.tcl
mcset zh_cn {Feature request} 特征需求

### File: ../src/mainwindow.tcl
mcset zh_cn {Reports history} 报告历史

### File: ../src/mainwindow.tcl
mcset zh_cn {Reporting bug} 正在报告bug

### File: ../src/mainwindow.tcl
mcset zh_cn {Reporting bug to SQLiteStudio bugs database...} {Reporting bug to SQLiteStudio bugs database...}

### File: ../src/mainwindow.tcl
mcset zh_cn {Problem occurred while reporting bug. You can ignore it and get back to your work.} {Problem occurred while reporting bug. You can ignore it and get back to your work.}

### File: ../src/mainwindow.tcl
mcset zh_cn Ignore 忽略

### File: ../src/mainwindow.tcl
mcset zh_cn {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history} {Bug successfly reported. Thank you! You can always look at discussion about your report using menu SQLiteStudio -> Show bug reports history}

### File: ../src/mainwindow.tcl
mcset zh_cn {A timeout occured while downloading new version. Try again, or download it manually.} {A timeout occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset zh_cn {An error occured while downloading new version. Try again, or download it manually.} {An error occured while downloading new version. Try again, or download it manually.}

### File: ../src/mainwindow.tcl
mcset zh_cn Downloading... Downloading...

### File: ../src/mainwindow.tcl
mcset zh_cn {Downloading SQLiteStudio v%s...} {下载 SQLiteStudio v%s...}

### File: ../src/mainwindow.tcl
mcset zh_cn {Problem with saving new SQLiteStudio version to:
%s
Details:
%s} {Problem with saving new SQLiteStudio version to:
%s
Details:
%s}

### File: ../src/mainwindow.tcl
mcset zh_cn {Problem with getting new SQLiteStudio version
Details:
%s} {Problem with getting new SQLiteStudio version
Details:
%s}

### File: ../src/mainwindow.tcl
mcset zh_cn {This is unknown binary distribution. Cannot determinate binary file to download for update.} {This is unknown binary distribution. Cannot determinate binary file to download for update.}

### File: ../src/data_editor.tcl
mcset zh_cn {There are uncommited rows.
Are you sure you want to close '%s' window anywy?} {There are uncommited rows.
Are you sure you want to close '%s' window anywy?}

### File: ../src/common/ddl_dialog.tcl
mcset zh_cn {Cannot prepare DDL. Dialog configuration is incomplete.
Problem details:
%s} {不能就绪 DDL. 对话框配置不完整.
问题细节:
%s}

### File: ../src/common/color_picker.tcl
mcset zh_cn {Choose color} 选择颜色

### File: ../src/common/shortcut_edit.tcl
mcset zh_cn {Forbidden shortcut key combination: %s} {Forbidden shortcut key combination: %s}

### File: ../src/common/common.tcl
mcset zh_cn Copy 拷贝

### File: ../src/common/common.tcl
mcset zh_cn Cut 剪切

### File: ../src/common/common.tcl
mcset zh_cn Paste 粘贴

### File: ../src/common/blob_edit_panel.tcl
mcset zh_cn {Text edit} 文本编辑

### File: ../src/common/blob_edit_panel.tcl
mcset zh_cn {Hexadecimal edit} 十六进制编辑

### File: ../src/common/common_sql.tcl
mcset zh_cn {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
} {Cannot open dialog, because requested object DDL code is not supported by this version of SQLiteStudio. Details:
}

### File: ../src/common/hex_editor.tcl
mcset zh_cn {Overwrite characters,
instead of inserting} {Overwrite characters,
instead of inserting}

### File: ../src/common/hex_editor.tcl
mcset zh_cn Processing 处理

### File: ../src/common/hex_editor.tcl
mcset zh_cn {Processing data...} 处理数据...

### File: ../src/sql_editor.tcl
mcset zh_cn {Replace dialog} 替换对话框

### File: ../src/sql_editor.tcl
mcset zh_cn {Search dialog} 搜索对话框

### File: ../src/trees/db_tree.tcl
mcset zh_cn Loading 加载

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Loading database list} 加载数据库列表

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Given database file doesn't exist or is unreadable.} {Given database file doesn't exist or is unreadable.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn Vacuum 空

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Integrity check} 完整性检查

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Import schema from other database} 从其他数据库导入模式

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Reset autoincrement for '%s'} {Reset autoincrement for '%s'}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Erase table data} {Erase table data}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Create foreign key} 创建外键

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Show view data} 显示视图数据

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Export view} {Export view}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Sort databases alphabetically} 按字母序排列数据库

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Given database is already on the list.} {Given database is already on the list.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Given database name is already on the list.} {Given database name is already on the list.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn Tables 表

### File: ../src/trees/db_tree.tcl
mcset zh_cn Views 视图

### File: ../src/trees/db_tree.tcl
mcset zh_cn {SQLite system table} {SQLite 系统表}

### File: ../src/trees/db_tree.tcl
mcset zh_cn Columns 列

### File: ../src/trees/db_tree.tcl
mcset zh_cn {SQLite system index} {SQLite 系统索引}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Remove database} 删除数据库

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Are you sure you want to remove '%s' database from the list?} {你希望从列表中删除 '%s' 数据库?}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.} {Table '%s' has no DDL. Probably it's system table and cannot be accessed with table window.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {'%s' is a virtual table, therefore cannot be browsed in table window.} {'%s' is a virtual table, therefore cannot be browsed in table window.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Table '%s' has no DDL. Probably it's system table and should not be edited.} {Table '%s' has no DDL. Probably it's system table and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {'%s' is a virtual table, therefore cannot be edited in table dialog.} {'%s' is a virtual table, therefore cannot be edited in table dialog.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.} {'%s' is a virtual table. Creating similar tables is possible only for regular SQLite tables.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Integrity check (%s)} {完整性检查 (%s)}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Are you sure you want to DROP '%s' table?} {你确定要删除表 '%s' ?}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Dropping table} {Dropping table}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Dropping table '%s'} {Dropping table '%s'}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Dropping index} {Dropping index}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Dropping index '%s'} {Dropping index '%s'}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?} {The Trigger '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this trigger into new SQL editor window so you can see what's wrong and fix it. Would you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Fix trigger} {Fix trigger}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.} {Trigger '%s' has no DDL.
Probably it's system index and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?} {The View '%s' has invalid DDL statement. You cannot edit it in dialog window. You need to drop it and recreate with valid syntax.

SQLiteStudio can put DDL of this view into new SQL editor window so you can see what's wrong and fix it. You you like SQLiteStudio to do so?}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Fix view} {Fix view}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {View '%s' has no DDL. Probably it's system view and should not be edited.} {View '%s' has no DDL. Probably it's system view and should not be edited.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Delete view} 删除视图

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Are you sure you want to delete '%s' view?} {你确定要删除视图 '%s' ?}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Erase data} {Erase data}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Are you sure you want to delete all data from table '%s'?} {Are you sure you want to delete all data from table '%s'?}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Deleting data} {Deleting data}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Deleting data from table '%s'} {Deleting data from table '%s'}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {'%s' view data} {'%s' 查看数据}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Are you sure you want to make a vacuum?} 你确定要空吗?

### File: ../src/trees/db_tree.tcl
mcset zh_cn Vacuuming Vacuuming

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Vacuuming '%s'} {Vacuuming '%s'}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {SQL files} SQL文件

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Select SQL file to be executed} {选中 SQL 文件将被执行}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Error while executing SQL:
%s} {Error while executing SQL:
%s}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {SQL executed sucessfly.} {SQL 执行成功.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Import database schema} 输入数据库模式

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Database: %s} {Database: %s}

### File: ../src/trees/db_tree.tcl
mcset zh_cn URI: URI:

### File: ../src/trees/db_tree.tcl
mcset zh_cn Version: Version:

### File: ../src/trees/db_tree.tcl
mcset zh_cn {File size:} {File size:}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Schema version:} {Schema version:}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Virtual table} {Virtual table}

### File: ../src/trees/db_tree.tcl
mcset zh_cn Indexes: Indexes:

### File: ../src/trees/db_tree.tcl
mcset zh_cn Triggers: Triggers:

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Column: %s} {列: %s}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Not null} {Not null}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Indexed table:} {Indexed table:}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copy index '%s' for table '%s'} {Copy index '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Move index '%s' to table '%s'} {Move index '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copy trigger '%s' for table '%s'} {Copy trigger '%s' for table '%s'}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Move trigger '%s' to table '%s'} {Move trigger '%s' to table '%s'}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copy view '%s' for database '%s'} {Copy view '%s' for database '%s'}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Move view '%s' to database '%s'} {Move view '%s' to database '%s'}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {View '%s' has no DDL, therefore cannot be edited.} {View '%s' has no DDL, therefore cannot be edited.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copy view} {Copy view}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Move view} {Move view}

### File: ../src/trees/db_tree.tcl
mcset zh_cn Move Move

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copy index} {Copy index}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Move index} {Move index}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copy trigger} {Copy trigger}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Move trigger} {Move trigger}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copy table '%s' to database '%s' (include data, indexes and triggers)} {Copy table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copy table '%s' to database '%s' (include data)} {Copy table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copy table '%s' to database '%s' (include indexes and triggers)} {Copy table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copy table '%s' to database '%s' (skip data, indexes and triggers)} {Copy table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Move table '%s' to database '%s' (include data, indexes and triggers)} {Move table '%s' to database '%s' (include data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Move table '%s' to database '%s' (include data)} {Move table '%s' to database '%s' (include data)}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Move table '%s' to database '%s' (include indexes and triggers)} {Move table '%s' to database '%s' (include indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Move table '%s' to database '%s' (skip data, indexes and triggers)} {Move table '%s' to database '%s' (skip data, indexes and triggers)}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copying table...} {Copying table...}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Copying table '%s' from '%s' to '%s'.} {Copying table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Moving table...} {Moving table...}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Moving table '%s' from '%s' to '%s'.} {Moving table '%s' from '%s' to '%s'.}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Could not create object in target database:
%s} {Could not create object in target database:
%s}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Could not copy data:
%s} {Could not copy data:
%s}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Could not copy table data from source database to target database. Details: %s} {Could not copy table data from source database to target database. Details: %s}

### File: ../src/trees/db_tree.tcl
mcset zh_cn {Could not delete object(s) from source database. Details: %s} {Could not delete object(s) from source database. Details: %s}

### File: ../src/grids/dbgrid.tcl
mcset zh_cn {Edit BLOB entry:} 编辑BLOB入口：

### File: ../src/grids/dbgrid.tcl
mcset zh_cn {BLOB edit} BLOB编辑

### File: ../src/grids/dbgrid.tcl
mcset zh_cn {Cannot commit. Details:
%s} {Cannot commit. Details:
%s}

### File: ../src/grids/grid.tcl
mcset zh_cn {You have to select a cell before paste any contents.} {You have to select a cell before paste any contents.}

### File: ../src/grids/grid.tcl
mcset zh_cn {Cut data} 剪切数据

### File: ../src/grids/grid.tcl
mcset zh_cn {There are too many columns or rows to paste. Do you want to cut them and paste?} 要粘贴太多的行列了。你是否希望剪切和粘贴?

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Insert new row} 插入新行

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Delete selected rows} 删除选中的多行

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Edit cell value} 编辑单元值

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Edit cell value in BLOB editor} {Edit cell value in BLOB editor}

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Duplicate row} 复制行

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Set NULL value} 设置为空值

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Generate SELECT from selected cells} {Generate SELECT from selected cells}

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Commit selected cells} 执行选中的多个单元

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Rollback selected cells} 回滚选中的多个单元

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Select all} {Select all}

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Show ordinals} 按序显示

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Show ROWIDs} {显示 ROWIDs}

### File: ../src/grids/data_grid.tcl
mcset zh_cn Type: Type:

### File: ../src/grids/data_grid.tcl
mcset zh_cn Constraints: 约束:

### File: ../src/grids/data_grid.tcl
mcset zh_cn {%s column has NOT NULL constraint. You have to fill value for it.} {%s 列有 NOT NULL 约束。你必须向其中填入值。}

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Error while adding new row:
%s} {在增加新行时出错：
%s}

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Error while updating new row:
%s} {Error while updating new row:
%s}

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Error while updating cell value:
%s

What would you like to do?} {在更新单元值时发生错误:
%s

你想做什么？}

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Re-edit value} 重新编辑值

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Return to value before edition} 还原编辑前的值

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Cannot delete row(s), because it violates constraint. Details:
%s} {Cannot delete row(s), because it violates constraint. Details:
%s}

### File: ../src/grids/data_grid.tcl
mcset zh_cn {Error while deleting selected rows:
%s} {在删除选中的行时出错:
%s}

### File: ../src/grids/data_grid.tcl
mcset zh_cn {SQL query generated at %s
using selected cells from window '%s'.} {SQL query generated at %s
using selected cells from window '%s'.}

### File: ../src/grids/result_grid.tcl
mcset zh_cn {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.} {Column '%s' is not editable. Only columns with corresponding ROWID in the table are editable or SQL query was too complicated.}

### File: ../src/grids/result_grid.tcl
mcset zh_cn {Data type:} {Data type:}

### File: ../src/grids/result_grid.tcl
mcset zh_cn {No details are available on this cell.} 该单元无适用的细节。

### File: ../src/grids/result_grid.tcl
mcset zh_cn {Duplicated ROWID} {重复的 ROWID}

### File: ../src/grids/result_grid.tcl
mcset zh_cn {There is more than one row with ROWID=%s affected by paste operation.
In this case unpredictable results may occure. Proceed?} {受粘贴操作影响的 ROWID=%s 的行大于1。导致不可预测的结果。是否继续？}

### File: ../src/grids/result_grid.tcl
mcset zh_cn {Could not parse SQL while trying to generate requested query: %s} {Could not parse SQL while trying to generate requested query: %s}

### File: ../src/grids/result_grid.tcl
mcset zh_cn {Cannot use '%s' statement to generate requested query.} {Cannot use '%s' statement to generate requested query.}

### File: ../src/grids/result_grid.tcl
mcset zh_cn {Cannot determinate selected column with ID=%s.} {Cannot determinate selected column with ID=%s.}

### File: ../src/grids/result_grid.tcl
mcset zh_cn {Error occurred while trying to generate the query: %s} {Error occurred while trying to generate the query: %s}

### File: ../src/grids/result_grid.tcl
mcset zh_cn {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s} {The SQL query has been generated at %s
using selected results from window '%s'.
The original query was:
%s}
